### ISSUE TITLE
Chrome/Edge/FireFox Only Playing Partial Audio  (2 of 6 channels?) A Downmix to Stereo Option is preferred. 

### ISSUE THREAD

**Issue by PVrX** [jellyfin/jellyfin-web#1002]
First of all, I would like to commend the hard work the jellyfin team has put in!

The project has really come a long way!

I am having an issue while using jellyfin in any browser. (Windows 10, Laptop Speakers)

I am attempting to playback a tv show : 

(TV Show : formula 1 - drive to survive S02E01 )

with the following audio : 

Title Eng Dolby Digital+ 6 ch Default
Language eng
Codec EAC3
Channels 6 ch
Sample rate 48000 Hz
Default Yes

Upon Playback, it shows the media as playing direct, implying audio too is playing direct.

During the show, only sound effects are audible . Voices are not. 

When I set playback quality lower than the original file bitrate, the video and audio transcode, and now all audio channels are audible, including voice audio.

Is it possible to enable a "downmix to stereo" option for watching JF in a browser? There are no audio settings. Ideally we are able to direct stream content, such that multi channel audio can be transcoded/downmixed into two channels. 

I am not quite sure why it assumes audio is working as intended, and didn't attempt to downmix. 

Thanks for the help guys!

**Comment by anthonylavado** [comment]
What browser are you using? The older non-Chromium version of Edge *did* support Dolby Digital, but I believe this is missing in the new version. It could be that our streaming profiles are outdated if that’s the case.

**Comment by PVrX** [comment]
Chrome version 80.0.3987.149 

Microsoft Edge version 44.18362.449.0

Firefox version 74.0 

:) thanks again for looking into this

**Comment by YouKnowBlom** [comment]
Is the stream being direct played?

**Comment by PVrX** [comment]
Yes

From above "Upon Playback, it shows the media as playing direct, implying audio too is playing direct."

**Comment by anthonylavado** [comment]
@PVrX So it looks like that’s Edge “Classic”, which will report as supporting AC3/EAC3. You can use https://html5test.com to check any browser.

I’m guessing the system isn’t down mixing it correctly then, so we’d likely have to work it out. I imagine if you use Firefox, Chrome, or the new Edge, Jellyfin would transcode the audio down to stereo for you automatically.

**Comment by PVrX** [comment]
How might this explain all three browsers not properly handling the audio?

The only way to get it to play is through transcoding. I am unable to direct stream (meaning the audio alone is encoded). 

Thank you for your response, I appreciate the help.

**Comment by JustAMan** [comment]
Please provide mediainfo of the broken file and Jellyfin server logs around the playback start.

**Comment by Artiume** [comment]
I can't reproduce this. Any 6-ch audio I play on FF 75.0 and Chrome 81. Do you have Audio Transcoding disabled in your user profile?

**Comment by ferferga** [comment]
@PVrX Any update on this based on @Artiume's feedback?
