### ISSUE TITLE
Option to Switch User

### ISSUE THREAD

**Issue by leaderdog** [jellyfin/jellyfin-web#1009]
With people adding desktop clients, thank you to those kind individuals, is it possible for you to add a Switch User option please.

I'm trying to migrate my Windows 10 HTPC to Jellyfin from Plex, but until there's a Switch User option it's not really possible, unless I use kodi which I'd prefer not to use.   And since the keyboard is kept in a cabinet, to reduce clutter, it's not convenient to bring it out each time a different user decides to watch tv.

Thanks, and my apologies if this is a duplicate, I searched for Switch Users but it came up with nothing relevant.

**Comment by dkanada** [comment]
@MrTimscampi this is actually available on Android by storing all credentials on the Java side. I'll need to look into what features need to get reported by AppHost to enable this in the interface though.

**Comment by MrTimscampi** [comment]
@leaderdog The plan is to have a user switcher at some point in the future (The current user menu on the desktop will be replaced by a user switcher, and the options will move completely to the Settings entry in the left drawer).
However, using a straight web browser, I'm not sure we want to allow passwordless user switching. What will likely happen is that we'd have a pin system for fast switching (much like Plex does).

@dkanada Cool, this would make native clients able to auto-switch if the user logged in once, I guess. As a fallback, using pins then falling back to passwords would probably be the best.

**Comment by dkanada** [comment]
It already works on Android since only one person is expected to have access to a phone.

**Comment by dkanada** [comment]
Also, I think it's reasonable to say if someone logs in on a public machine, selects the option to stay logged in, and doesn't log out when they're finished, they would be fine leaving that account available with saved credentials.

**Comment by leaderdog** [comment]
> 
> 
> @leaderdog The plan is to have a user switcher at some point in the future (The current user menu on the desktop will be replaced by a user switcher, and the options will move completely to the Settings entry in the left drawer).
> However, using a straight web browser, I'm not sure we want to allow passwordless user switching. What will likely happen is that we'd have a pin system for fast switching (much like Plex does).
> 
> @dkanada Cool, this would make native clients able to auto-switch if the user logged in once, I guess. As a fallback, using pins then falling back to passwords would probably be the best.

I'm glad to hear there is a solution coming.

Hopefully, not exactly like Plex!  That's one of the reasons I want to get away from it, on the HTPC occasionally one of the other users makes some kind of mistake (or a  PC reboot) and I have to do that PIN thing via the internet again.  In the 2 weeks I've been using it, I've had to do it 4 or so times.  It is extremely annoying ;)  Kodi handles this situation much much better.   

However I get that remote access via web needs better security, but for home use it's just a layer of unnecessary  frustration.

**Comment by MrTimscampi** [comment]
> I have to do that PIN thing via the internet again

Don't worry, I'm not talking about the pairing pins :)

We have login pins the user can enter to quickly unlock their account instead of inputting their full password. But of course, as @dkanada said, we'd have a "always remember this account" option to get a more Netflix-like experience.

**Comment by MrTimscampi** [comment]
Please redirect feature requests and suggestions to https://features.jellyfin.org/
