### ISSUE TITLE
Picture-in-picture support on macOS

### ISSUE THREAD

**Issue by Numline1** [jellyfin/jellyfin-web#101]
High Sierra and Mojave have a support for native PIP (works at least in Chrome and Safari). Youtube seems to have this implemented. This may work in video.js (#142) but I'm not 100% confident about that. It's also described in detail on Apple developers page and seems fairly easy to implemented :) Would be nice to have this, although it's mostly QoL. Thanks!

Ref: https://developer.apple.com/documentation/webkitjs/adding_picture_in_picture_to_your_safari_media_controls

**Comment by anthonylavado** [comment]
This is supported, I just don't understand why `document.pictureInPictureEnabled` is never set to true for Safari. @dkanada?
