### ISSUE TITLE
Do not display blue checkmark on cover art

### ISSUE THREAD

**Issue by grantwest** [jellyfin/jellyfin-web#1010]
When a TV Series or Season has zero unwatched episodes the current behavior is to show a blue circle with a white check mark in the top right hand corner of the cover art. If the Series or Season has unwatched episodes it shows the number in the blue circle. Because every show has a blue circle it becomes harder for a person to easily scan with their eyes to find shows with unwatched episodes. From a user experience perspective it would be better to not display the blue circle at all if there is zero unwatched episodes. In this way the presence of a blue circle at all is communicating information to the user.

![Screenshot from 2020-04-01 10-02-34](https://user-images.githubusercontent.com/4594800/78153355-96f9d980-7400-11ea-9b6b-a2c89a7fa445.png)

**Comment by dmitrylyzo** [comment]
I think #706 is about the same.

**Comment by grantwest** [comment]
Yes you are correct. I will close this one.
