### ISSUE TITLE
JellyFin 10.5.0 Stream URL copy not working

### ISSUE THREAD

**Issue by gwenvador** [jellyfin/jellyfin-web#1013]
**Describe the bug**
Nothing is copying when selecting copy stream URL.  

**System (please complete the following information):**
 - OS: Windows 10 
 - Clients: Browser
 - Browser: Brave 1.4.96
 - Jellyfin Version: 10.5.0
 - Reverse Proxy: none

**To Reproduce**

1. Go to any videos
3. Copy stream URL 
4. Nothing is copied

**Comment by ThibaultNocchi** [comment]
How about 10.5.2? It definitely is working for me with it and Firefox. I remember 10.5.0 introduced a fix but it still had an edge case and was fixed in the later versions.

**Comment by MrTimscampi** [comment]
Closing this as it works on the lastest Chromium with Jellyfin 10.5.3 (And probably before, but due to build issues and all, we won't count them).

Do note that Brave isn't officially a target, but since it's basically Chromium, it should mostly work if that does.
