### ISSUE TITLE
Back button in the player redirects to previous page

### ISSUE THREAD

**Issue by Numline1** [jellyfin/jellyfin-web#102]
The back button (left oriented arrow) in the video player in the upper left corner probably uses JavaScript to redirect to previous page.

This works well when the previously visited page was the episode list (show detail page), however it results in some undesired behaviour when it wasn't.

Example:

- Navigate to https://google.com
- Navigate to https://yourhost.tld/jellyfin/web/index.html#!/videoosd.html
- Click the back arrow button

**Expected result**: Returning to an episode list (show detail page)
**Actual result**: Returning to Google

Not really a huge deal, the videoosd.html page doesn't work when accessed directly anyway, however in some cases it's a top result when using the address bar autocomplete in browsers and it'd be convinient if the back button wen't to Jellyfin home page instead of redirecting the user completely outside the scope of Jellyfin itself.

Tested in latest Chrome stable :) Thanks for feedback!

**Comment by sparky8251** [comment]
We should also aim to correct the back buttons behavior in the server dashboard, such that it doesn't update for each sub menu you enter. 

Aka, clicking it always brings you back to the page you entered the server dashboard pages from.

**Comment by JustAMan** [comment]
Makes sense... that back button is there mostly for non-PC-browser thingies where you probably won't be using the dashboard in the first place.
Or it could behave so only for desktop browsers and remain "normal back button" for other devices.

**Comment by MrTimscampi** [comment]
I would argue that we shouldn't override the normal behavior of the back button of browsers.

When the user navigates through pages in the app, it makes sense to go back to the previous state. However, when the user comes from somewhere else, it can get annoying very quickly if the website or app is hijacking the back button.

In my opinion, most people would expect the back button to go to the previous state of their history, not redirect them by force to a state they haven't been to before.

Nowadays (in 10.5.x), the header is always shown on desktop and as such, the in-app back and home buttons are always available, as well.
