### ISSUE TITLE
Android Device Browsers (chrome/Firefox) not working with JellyFin Web

### ISSUE THREAD

**Issue by mitchelljfranklin** [jellyfin/jellyfin-web#1021]
Hi All,
I have looked at [#1017](https://github.com/jellyfin/jellyfin-web/issues/1017) & [#2552](https://github.com/jellyfin/jellyfin/issues/2552) but appear to be different is certain aspects yet similar in others so thought best to create a new report.

**Describe the bug**
After Upgrading from Release 10.5.0 to 10.5.2 I noticed that on Android devices (MX Pro Box & OPPO A9 2020) when using the following browsers the following occurred.

**Chrome**: _Latest Version_
When navigating to Jellyfin sever Chrome would load but show a blank screen, no buttons and or actions available. 

**Firefox**: _Latest Version_
When navigating to Jellyfin sever Firefox would load the main screen, title bar but not load the actual detail i.e. Library, Keep watching etc. You could however navigate to the Library using the header menu in which the detail i.e. Thumbs etc would load.

In both of these Also tried the show desktop mode setting to validate and clearing all cache and data with the issues still noted being present.

It is to be noted that Android App, Tv App and Desktop browsers do not appear to have the issues.

I then restored from backup to 10.5.0; once done I found that both Android Chrome and Firefox both worked like there Desktop counterparts.

-----------------------------------------------

**System (please complete the following information):**
 - OS: Windows
 - Browser: Android Chrome, Android Browser
 - Jellyfin Version: 10.1.52

**Additional context**
As this was on Android I could not access and or view any browser logs that may contain any errors.

**Comment by Artiume** [comment]
The Firefox ESR issue is marked here https://github.com/jellyfin/jellyfin-web/issues/994

As for the Chrome Mobile issue, I'm not sure. I'm not experiencing that, I'm running a nightly so maybe that has something to do with it. i can try 10.5.2 vanilla and test it out.

**Comment by MrTimscampi** [comment]
@mitchelljfranklin @Artiume The Chrome issue is already fixed in nightly. Due to build issues, 10.5.2 pulled the nightly version of the web client, which was slightly broken at the time (it's a nightly after all).

10.5.3 should be out fairly soon (it's planned for tomorrow, I think) and should solve the build issue.

For the Firefox issue, I'm able to reproduce it even on the desktop version of Firefox ESR. I'll be looking into it, seems like the tabs manager is choking on something.

**Comment by Artiume** [comment]
@mitchelljfranklin verify chrome works again in 10.5.3, if so we can close this ticket since the Firefox issue is tracked already

**Comment by mitchelljfranklin** [comment]
> @mitchelljfranklin verify chrome works again in 10.5.3, if so we can close this ticket since the Firefox issue is tracked already

Hi @Artiume can confirm new release has resolved :) thank you to you and the team.
Ta
Mitch
