### ISSUE TITLE
Custom CSS for each profile?

### ISSUE THREAD

**Issue by leaderdog** [jellyfin/jellyfin-web#1025]
I apologize if this has been answered, but I couldn't find it searching here or in the wiki or on the net.

Can we have separate css profiles for each user?  Mainly I want different background so when the switch user options are setup for desktop feature at a glance we'll know who's profile is running on the htpcs and then user can switch.  Plus overall I'm sure people in the same household may prefer different layouts and looks.  (We did this with Kodi.  Only way to know was to check the exit/switch menu.

Currently only the person with dashboard access can change it, You can give the other user dashboard access, but I don't know if putting in a custom css will stick to just their profile or affect everyone regardless.

Since I'm not very knowledgeable about css, I figured I'd ask before I spend the time to go and find out it does/doesn't work that way.

Thanks.

**Comment by MrTimscampi** [comment]
The custom CSS feature is, for now, intended as a server-wide style. There is no real way to have per-user custom styles, aside from the bundled themes.

You could set a user image for each user (in Settings > User)  to see at a glance which user is connected (The image will be shown in the top-right). 

Custom themes, that would be available per-user are planned and are tracked in #72.

As this feature is already tracked in #72, I'll mark this issue as a duplicate and close it, but feel free to ask for further information here if needed.
