### ISSUE TITLE
Album shuffle does not work as expected

### ISSUE THREAD

**Issue by rexbron** [jellyfin/jellyfin-web#1036]
**Describe the bug**
Hitting shuffle from the album page shuffles random songs, the same as the songs page. 
Ie 
<Album 1> <Song 1>
<Album 2><Song 5>

**To Reproduce**

1. Go to album tab in a music collection. 
2. Click on shuffle icon. 
3. Open play queue
4. See that random songs from all artists are added to the queue

**Expected behavior**

That albums (ie songs in the order they appear on the album) would be shuffled.
<Album 1><Song 1>
<Album 1><Song 2>
...
<Album 1><Song n>
<Album 2><Song 1>
Etc. 

**System (please complete the following information):**
 - OS: Debian 10
 - Browser: All
 - Jellyfin Version: 10.5.3

**Comment by JustAMan** [comment]
Could you please clarify the desired behaviour? I cannot understand what do you mean here.
Should the albums be shuffled somewhere (in a playlist?) but songs within album stay in place, or should the songs within an album be shuffled but albums stay in place, or what?

**Comment by rexbron** [comment]
It's the difference between shuffling the albums (leaving song order intact) and shuffling the songs within the albums.

 As I'm shuffling from the Album page, I'd expect a random selection of albums added to the play list. 

If I was shuffling from the songs page, then I'd expect a random selection of songs.

**Comment by JustAMan** [comment]
Well, actually if I would be shuffling from albums page I'd expect it to play songs from all shown albums shuffled (like it is currently). How would you propose to achieve this (i.e. playing all songs shuffled)?

**Comment by rexbron** [comment]
> Well, actually if I would be shuffling from albums page I'd expect it to play songs from all shown albums shuffled (like it is currently)

Why does it show album covers and not the individual songs? Cause it's an albums page :) 
Clicking on an album takes you to the album itself. Clicking play on an album icon adds all the songs from the album to play list in order.

What is at issue is what you are shuffling, songs or albums. I expect it to shuffle the data displayed, in this case entire albums. 

> How would you propose to achieve this (i.e. playing all songs shuffled)?
Not sure what you mean here.  Shuffling all songs? One could do that from the songs page.

**Comment by bendardenne** [comment]
I would also love this behaviour.

To be fair though, few music players implement it this way (unfortunately).

**Comment by MrTimscampi** [comment]
We are currently following the accepted industry standard. While it'd be good to offer the options, this is a feature request and not a bug.

Please redirect feature requests to https://features.jellyfin.org/
