### ISSUE TITLE
Subtitles from previous episode re-played when playing next episode

### ISSUE THREAD

**Issue by tayhr** [jellyfin/jellyfin-web#1041]
Watching multiple episodes of a TV series in a row, and either waiting for the next episode to begin or clicking the button on the "Up Next" screen, the next episode to play will re-play the subtitles from the previous episode. Video and Audio stream are correct for the new episode.

This issue was created in the jellyfin-androidtv repo, but the problem is the same on jellyfin-web.
ref: https://github.com/jellyfin/jellyfin-androidtv/issues/108

**Comment by Artiume** [comment]
Could you try and find a way to reliably reproduce this error? It'd go a long way to figure out what the issue is

**Comment by JustAMan** [comment]
We'd need quite a lot of details to see what's going on.
What is subtitles format, are they external or internal, what is media info, is "extraction on the fly" enabled?

Also we have a template for reporting bugs, please follow it.

**Comment by tayhr** [comment]
> We'd need quite a lot of details to see what's going on.
> What is subtitles format, are they external or internal, what is media info, is "extraction on the fly" enabled?
> 
> Also we have a template for reporting bugs, please follow it.

format: .srt
they are external.

@Artiume i'll try to reproduce it.

**Comment by tayhr** [comment]
Ok, it seems that the problem on jellyfin-web was solved. I have the latest nightly version and the episode starts with no active subtitles.
The problem is still on android tv.
