### ISSUE TITLE
Live TV Channel Number does not show in Guide on Android App

### ISSUE THREAD

**Issue by coldshouldermedia** [jellyfin/jellyfin-web#1043]
As you can see in this screenshot of the android app the live TV channel number is not listed anywhere in the guide:

![temp](https://user-images.githubusercontent.com/54368516/78717965-a84e5480-78de-11ea-8222-a054568abcae.png)

As opposed to the guide in the web client, where channel numbers are clearly listed.
![chrome_K2p2PEgSIL](https://user-images.githubusercontent.com/54368516/78718137-fb280c00-78de-11ea-94be-a2d8d964bfa8.png)

I find these numbers useful and would like to see them implemented on the android app.

**Comment by sparky8251** [comment]
For some reason, these numbers aren't shown on the android app even though they show on web. The client files are all the same for these, so I wonder why the result is different?

**Comment by Artiume** [comment]
Android is based on web ui. AndroidTV is based on itself. The plan is to eventually have the android app use the same base code as AndroidTV but that's in the future.

**Comment by coldshouldermedia** [comment]
It looks like when scaling the web client in a browser window, at a small enough size, the channel numbers also disappear, creating the same "issue".

**Comment by MrTimscampi** [comment]
There are some plans to rework this screen at a later date, but this is not a bug and is meant to show more useful information on narrow screens.

Please redirect feature requests and suggestions to https://features.jellyfin.org/
