### ISSUE TITLE
Poor Logo Contrast in Live TV Guide

### ISSUE THREAD

**Issue by coldshouldermedia** [jellyfin/jellyfin-web#1044]
**Description**
When browsing the Live TV Guide tab, with the android client or web client theme: set to "dark", dark logos with transparent backgrounds have poor contrast/viability.

**To Reproduce**
1. Use android or web client
2. Set theme: to "dark"
3. Navigate to the guide tab of Live TV, with .xml guide data active

**Expected behavior**
Logos are expected to be more clearly visable, by either having a dynamic background color, or by using a slightly lighter gray, like the one highlighting currently active programs.

Outlined in Red:
![N3DSvfjoRF](https://user-images.githubusercontent.com/54368516/78719778-bc478580-78e1-11ea-8447-1add91db1269.png)

**System:**
 - Browser: Chrome, Android app
 - Jellyfin Version: 10.5.3

**Comment by PrplHaz4** [comment]
I'm seeing this as well with Schedules Direct as the guide provider - not sure it's a problem JF can solve though...

**Comment by MrTimscampi** [comment]
It's indeed a difficult issue to solve because TV logos don't really have any rules and can be black, white or any color.

What I could see is sticking to a fully black or fully white version of logos, depending on the theme used (Essentially what service like Sling, Youtube TV or Hulu, as well as set-top boxes manufacturers like BrightBlue do).

**Comment by MrTimscampi** [comment]
Some references for future use:

![image](https://user-images.githubusercontent.com/19396809/78856595-798fc580-7a27-11ea-8896-2514b7103261.png)

![image](https://user-images.githubusercontent.com/19396809/78856611-81e80080-7a27-11ea-87a2-599f3571fb22.png)

![image](https://user-images.githubusercontent.com/19396809/78856695-b1970880-7a27-11ea-9ecd-284efa28f22e.png)

![image](https://user-images.githubusercontent.com/19396809/78856718-c1165180-7a27-11ea-8d5f-0e3a1fe21718.png)

![image](https://user-images.githubusercontent.com/19396809/78856760-de4b2000-7a27-11ea-8944-4591fe0deb8c.png)

![image](https://user-images.githubusercontent.com/19396809/78856793-f28f1d00-7a27-11ea-930c-c48b575c48ed.png)

**Comment by MrTimscampi** [comment]
While it's eventually planned to rework this, it is not a bug and thus should be redirected to https://features.jellyfin.org/
