### ISSUE TITLE
EdgeHTML hangs when loading admin dashboard pages

### ISSUE THREAD

**Issue by MasterOfStar** [jellyfin/jellyfin-web#1052]
**Describe the bug**

BUG1:I can't click something in the dashboard.(this is the bug video: https://youtu.be/pQNiZa1L9vI )
It's happen in the "jellyfin_v10.5.2-x64_windows.exe" ,and 10.5.0 10.4.3 also has this bug.

BUG2:I uninstall "jellyfin_v10.5.2-x64_windows.exe" and use "jellyfin_10.5.2.portable_windows-x64.zip", I can't look any thing in the Index (this is the bug video: https://youtu.be/81E_elAiP6c )

BUG3:use IE or VIA(it's a Android browser, use Android system WebView.) browser, it's black page.
IE:
![image](https://user-images.githubusercontent.com/21274896/77924179-f4ddd280-72d5-11ea-96dc-109922f070b6.png)
VIA:
![image](https://user-images.githubusercontent.com/21274896/77924288-1939af00-72d6-11ea-84f7-83f3dc11746e.png)

**System (please complete the following information):**
 - OS: server and client all are Windows10 1909 (Chinese language) 
 - Virtualization: NO,run in a PC
 - Clients: Browser
 - Browser: Microsoft edge 44.18362.449.0 with EdgeHtml
 - Jellyfin Version:10.5.2 
 - Storage: local

**Logs**
**log no any  error about webpage**
log:https://raw.githubusercontent.com/MasterOfStar/jellifin-bug-log/master/log 

**I'm a Chinese. my English is very poor, so I use the video to tell you the bug.**

**Comment by JustAMan** [comment]
This is a jf-web bug, so I moved it.

**Comment by MrTimscampi** [comment]
For reference, bug 2 might be #994 

Bug 3 was fixed in #975

**Comment by Artiume** [comment]
For bug 1, is it specific to any browser or all browsers? 10.5.4 is being released tonight. It probably won't be fixed but it's worth upgrading to try

**Comment by MasterOfStar** [comment]
> For bug 1, is it specific to any browser or all browsers? 10.5.4 is being released tonight. It probably won't be fixed but it's worth upgrading to try

Bug 1 just in Microsoft Edge(with EdgeHTML core).

**Comment by Artiume** [comment]
Can we rename the ticket to Edge (html core) fails to display select dashboard pages. Or something to that effect.
