### ISSUE TITLE
Playstation 4 is not recogniced as TV

### ISSUE THREAD

**Issue by Nickbert7** [jellyfin/jellyfin-web#1054]
**Describe the bug**
The web browser of the PS4 is not recognized as a TV, therefore the desktop layout is used instead of the TV layout.
After switching to the TV layout, the focus is working fine, but the select does not work correct, it selects where the cursor is and not the current focused item.

Also in the OSD the AirPlay icon is visible which should not be the case

**To Reproduce**
Open JF with the PS4 web browser

**Expected behavior**
The layout should be the TV layout and the focused item should be selected and not the item behind the hidden cursor.

**System (please complete the following information):**
 - OS: Windows (Server)
 - Browser: PS4 Browser
 - Jellyfin Version: 10.5.2

**Comment by Artiume** [comment]
wait, how do you go to TV layout? I did not know this was a thng

**Comment by MrTimscampi** [comment]
> wait, how do you go to TV layout? I did not know this was a thng

Display > Layout > TV.

This is likely a missing detection in browser.js.

**Comment by dkanada** [comment]
@Nickbert7 we'll need some documentation for the user agent strings that PlayStation devices can use to update the detection.

**Comment by MrTimscampi** [comment]
For reference, we can probably get rid of the parsing and rely on this: https://github.com/lancedikson/bowser

It has support for detecting Playstation 4, Tizen and WebOS.

**Comment by Nickbert7** [comment]
Here is a list of user agents used by the PS4
https://www.psdevwiki.com/ps4/Internet_Browser

It is also already checked here within the browser.js
https://github.com/jellyfin/jellyfin-web/blob/69b9433917355215f56dd20fb774efea136edae3/src/scripts/browser.js#L257

**Comment by MrTimscampi** [comment]
The cause of this is here: https://github.com/jellyfin/jellyfin-web/blob/master/src/components/layoutManager.js#L48

It's setting it for Smart TVs and Xbox, but not for PS4.
