### ISSUE TITLE
Home screen sections duplicated

### ISSUE THREAD

**Issue by baarkerlounger** [jellyfin/jellyfin-web#1060]
**Describe the bug**
The sections on the home screen repeat (duplicate) vertically 7 times.

**Screenshots**
![jellyfin](https://user-images.githubusercontent.com/5101747/79012624-9c70c580-7b5e-11ea-9e17-cc5c77c88b37.png)

**System (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser: Firefox 75 & Google Chrome 78.0.3904.70
 - Jellyfin Version: 10.5.3

**Additional context**
Also reproducible on the Android App

**Comment by vaxevanis** [comment]
any update on this?

**Comment by MrTimscampi** [comment]
I don't think anyone has been able to reproduce it.

**Comment by vaxevanis** [comment]
I undestand. I took a look at this and (at least in my case) it is user related. Creating a new user solves this. 
The problem seems to be created by the nonTizen samsung jellyfin app. Long time ago i altered the Dashboard user settings from the Tv app and this messed up the userSettings.CustomPrefs. I believe  that at some point (after jellyfin v.10.5.1) the schema of the userSettings.CustomPrefs has changed.

```
CustomPrefs:
tvhome: "horizontal"
homesection0: "smalllibrarytiles"
homesection1: "smalllibrarytiles"
homesection2: "smalllibrarytiles"
homesection3: "smalllibrarytiles"
homesection4: "smalllibrarytiles"
homesection5: "smalllibrarytiles"
homesection6: "smalllibrarytiles"
landing-livetv: "guide"
landing-f137a2dd21bbc1b99aa5c0f6bf02a805: ""
landing-7e64e319657a9516ec78490da03edccb: ""
landing-767bffe4f11c93ef34b805451a696a4e: ""
http://localhost:8096/web/index.htmlseries: "{"SortBy":"SortName","SortOrder":"Ascending"}"
http://localhost:8096/web/index.htmlseriesgenres: "{"SortBy":"SortName","SortOrder":"Ascending"}"
http://localhost:8096/web/index.htmlepisodes: "{"SortBy":"SeriesSortName,SortName","SortOrder":"Ascending"}"
http://localhost:8096/web/index.htmlmoviecollections: "{"SortBy":"SortName","SortOrder":"Ascending"}"
http://localhost:8096/web/index.htmltrailers: "{"SortBy":"SortName","SortOrder":"Ascending"}"
guide-indicator-hd: "true"
guide-indicator-live: "true"
guide-indicator-new: "false"
guide-indicator-premiere: "true"
guide-indicator-repeat: "true"
guide-colorcodedbackgrounds: "true"
livetv-favoritechannelsattop: "true"
livetv-channelorder: "Number"
subtitleeditor-language: "gre"
...
```

**Comment by vaxevanis** [comment]
Fixed this by manually altering user preferences on displaypreferences.db

**Comment by baarkerlounger** [comment]
@vaxevanis can you share what you altered and how?

**Comment by vaxevanis** [comment]
@baarkerlounger 

- locate displaypreferences.db file (serverlocation/data/). 
- make a backup of the file just in case.
- open file with db editor of your choice. i used [db browser](https://sqlitebrowser.org/)
- find the record of the  user (probably the one with id:1 )
- edit data cell and remove unwanted keys from the json object. 
The final result should be something like the following:
{
   "Id":"3ce5b65de116d73165d1efc4a30ec35c",
   "ViewType":null,
   "SortBy":null,
   "IndexBy":null,
   "RememberIndexing":false,
   "PrimaryImageHeight":250,
   "PrimaryImageWidth":250,
   "CustomPrefs":{
      "http://localhost:8096/web/index.htmlmoviecollections":"{\u0022SortBy\u0022:\u0022SortName\u0022,\u0022SortOrder\u0022:\u0022Ascending\u0022}",
      "6c18e22f7c03e5d793e233a7084f7d60-movies":"{\u0022SortBy\u0022:\u0022DateCreated,SortName,ProductionYear\u0022,\u0022SortOrder\u0022:\u0022Descending\u0022}",
      "dashboardTheme":"",
      "enableNextVideoInfoOverlay":"true",
      "skipForwardLength":"30000",
      "skipBackLength":"10000",
      "http://localhost:8096/web/index.htmlmoviegenres":"{\u0022SortBy\u0022:\u0022SortName\u0022,\u0022SortOrder\u0022:\u0022Ascending\u0022}",
      "http://localhost:8096/web/index.htmltrailers":"{\u0022SortBy\u0022:\u0022SortName\u0022,\u0022SortOrder\u0022:\u0022Ascending\u0022}"
   },
   "ScrollDirection":"Horizontal",
   "ShowBackdrop":true,
   "RememberSorting":false,
   "SortOrder":"Ascending",
   "ShowSidebar":false,
   "Client":"emby"
} 

If you are not sure what to keep, copy the above code and replace **Id** (and **port number** if you are not using the default) with yours. 
Or create a new user [here](http://localhost:8096/web/index.html#!/userprofiles.html) open displaypreferences.db and copy json object from that user to the default user. You can delete this user later on. 
Restart server.

**Comment by baarkerlounger** [comment]
Turns out the users broken for me were missing: `"ViewType":null,"SortBy":null,"IndexBy":null,` in the data JSON. Not sure why they're required or why they were missing but adding those fields back resolves the view issue. 

Guessing these values should be getting defaulted in code somewhere?

**Comment by MrTimscampi** [comment]
@baarkerlounger To get an idea of whether this needs an actual fix or is user error, can you give us the steps that led you to having duplicate sections?

Did you use a particular client? Updated from an old version of Jellyfin or Emby?

What were the steps that led you to have duplicate sections?

**Comment by baarkerlounger** [comment]
@MrTimscampi I'm not sure unfortunately. Never used Emby. Have bumped Jellyfin minor versions a few times but not sure specifically when this got introduced, I only noticed it after a while.

**Comment by MrTimscampi** [comment]
Closing this, as it was caused by an unsupported client and can't be reproduced otherwise.
