### ISSUE TITLE
Preferences menu is broken

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [jellyfin/jellyfin-web#1061]
**Describe the bug**
When clicking on the preferences button, it overlays over the current screen, and none of the buttons work.

**To Reproduce**
1. Click on the preferences button in the navigation bar

**Expected behavior**
For it to show the menu correctly

**Screenshots**
![](https://e-six-two.one/i/5abcdfsd.jpg)

**Logs**
```
TypeError: view.querySelector(...) is null (menu.js:1:377)
```

**System (please complete the following information):**
 - OS: Windows
 - Browser: Firefox 75.0
 - Jellyfin Version: master server, master jellyfin-web

**Comment by MrTimscampi** [comment]
I'm not able to reproduce it using Firefox 15 on Windows 10 through Browserstack.

Make sure to clean your cache if you have updated Jellyfin recently.

**Comment by ThatNerdyPikachu** [comment]
There we go, thanks.
