### ISSUE TITLE
Missing String on the Favourites Screen

### ISSUE THREAD

**Issue by Boki40** [jellyfin/jellyfin-web#1066]
On the Favourites Screen

![image](https://user-images.githubusercontent.com/59022978/79064676-2a59c700-7cab-11ea-8ece-521e3d8d89f3.png)

**Comment by dkanada** [comment]
What version of the server are you running?

**Comment by MrTimscampi** [comment]
@dkanada Source string seems to be missing

![image](https://user-images.githubusercontent.com/19396809/80065939-4aa34480-853b-11ea-86ca-0a77eac2a494.png)

**Comment by Boki40** [comment]
I currently use the newest available stable build (10.5.4)
