### ISSUE TITLE
Home header button missing in Mobile Layout

### ISSUE THREAD

**Issue by DMouse10462** [jellyfin/jellyfin-web#1073]
**Describe the bug**
Raised by @avid_watcher:matrix.org in #jellyfin-troubleshooting.
The home icon in the upper-right corner of most pages is completely missing from the header when in the mobile layout.

**To Reproduce**

1. Access 10.5.3 jellyfin-web on a mobile device OR set to Mobile in Display settings.
1b. Refresh if display type was set manually.
2. Navigate to any page that the home icon is expected on (a library, for example)
3. Note the missing icon.

**Expected behavior**
Home icon is displayed, unless this is a new "correct" behavior.

**Logs**
N/A? Can be provided upon request.

**Screenshots**
Firefox 47.0.1 (Ubuntu) - Responsive Mode in DevTools:
![Screenshot from 2020-04-12 21-37-09](https://user-images.githubusercontent.com/2002606/79085522-e3012400-7d06-11ea-85ec-6ede8a7db2e0.png)

Chrome 80 Android (OnePlus 3T, 1080x1920 display):
![Screenshot_20200412-214005__01](https://user-images.githubusercontent.com/2002606/79085574-1f348480-7d07-11ea-8c9d-803155167569.jpg)

**System (please complete the following information):**
 - OS: Web - Any, Server - Ubuntu 19.10
 - Browser: Multiple - see above.
 - Jellyfin Version: 10.5.3 (tested jellyfin-web master at https://github.com/jellyfin/jellyfin-web/commit/6246dce3205c074462e5aab767abf6d122394d67 with same results)

**Comment by anthonylavado** [comment]
https://github.com/jellyfin/jellyfin-web/pull/932

**Comment by DMouse10462** [comment]
Hmm, looks like this was an intentional design choice then. I can see some UI situations in which spamming the back button can be annoying, especially with a flow such as:

Home > Library > Series > Season > Episode > Other Episode > Recommended Show > etc...

I can at least get to a point where you're 6 button presses away from the home screen; I could certainly go further. I'm not too bothered by it, but if it came up as an "issue" in chat then it's probably worth discussion.
