### ISSUE TITLE
Embedded MKV S_TEXT/UTF8 subtitles don't render correctly

### ISSUE THREAD

**Issue by Wuzado** [jellyfin/jellyfin-web#1077]
**Describe the bug**
When watching a movie with multiple dialogue lines on screen at the same time, only one dialogue line is rendered, often at a wrong place on screen. When watching on VLC, it's rendered correctly though.

**System (please complete the following information):**
 - OS: Windows 10
 - Virtualization: None
 - Clients: Browser
 - Browser: Firefox 75 on Windows 10 (same PC)
 - Jellyfin Version: tested on stable 10.5.3 and nightly 20200408
 - Playback: WebUI?
 - Installed Plugins: N/A
 - Reverse Proxy: None
 - Base URL: localhost:8096
 - Networking: hosted on LAN, played back at the same PC
 - Storage: local

**To Reproduce**
1. Watch a movie with multiple dialogue lines embedded into MKV container.

**Expected behavior**
VLC:
![VLC](https://user-images.githubusercontent.com/23276409/79069263-2a6abe80-7ccd-11ea-8950-8184c0a46b12.PNG)

**Actual behavior**
![jellyfin](https://user-images.githubusercontent.com/23276409/79069272-3c4c6180-7ccd-11ea-8644-2ee7ce646d04.PNG)

**Comment by Wuzado** [comment]
Yes! Switching to Chrome actually helps with this issue, but it still doesn't position it correctly. Also, @ around 0:00:55, "Capture Quest" text looks like it's not parsed correctly, and says `{\c&H0E1E62&\t(26,108,1 \alpha&HFF&)\t(316,400,1 \c&H91C0DF&\alpha&H00&\t(484,984,1 \c&H0E1E62&))}Capture Quest`

I'm including my .srt file:
https://pastebin.com/e7Xkv1Gh

**Comment by ffiarpg** [comment]
Still an issue.

**Comment by ffiarpg** [comment]
Still an issue.

**Comment by ffiarpg** [comment]
Still an issue.
