### ISSUE TITLE
Toggling fullscreen makes subtitles disappear

### ISSUE THREAD

**Issue by JonnyHaystack** [jellyfin/jellyfin-web#1078]
**Describe the bug**

When you enter or exit fullscreen, any subtitles that are currently displayed will disappear until the next chunk of subtitle text appears.

**To Reproduce**

1. Be watching a video with subtitles
2. Enter or exit fullscreen
3. See that the subtitles vanish, and subsequently toggling fullscreen causes them to appear for a small fraction of a second at a time

**Expected behavior**

Toggling fullscreen should not affect subtitles

**System (please complete the following information):**
 - OS: Server running on Debian 10, client running Arch Linux
 - Browser: qutebrowser
 - Jellyfin Version: 10.5.4

**Comment by JonnyHaystack** [comment]
I think this got fixed although no one's referenced this issue

**Comment by peke91** [comment]
@Camc314 issue still present on browser on LG tv.
Subtitles disappear after period of time.

**Comment by jays1ngh** [comment]
I can confirm issue is still present on LG WebOS.

**Comment by dannymichel** [comment]
This seems fixed now
