### ISSUE TITLE
main menu doesn't appear when button is pressed in TV Mode

### ISSUE THREAD

**Issue by schmidex** [jellyfin/jellyfin-web#1082]
**Describe the bug**
Menu doesn't appear when button is pressed in TV Mode.

**To Reproduce**

1. Switch to "TV-Mode" (Preferences -> Display -> Display Mode -> TV)
2. Refresh (Important!!! otherwise it will work)
3. Go to "home" and press the menu-button in the upper left corner

**Expected behavior**
Menu should appear. Instead the background is darken but nothing else happens

**System:**
 - OS: tested on: Windows, MacOS and LG WebOS
 - Browser: tested in: Chrome, Firefox and Safari
 - Jellyfin Version: 10.5.3

**Additional context**
I tracked the problem down to the ```.hide``` class on the ```.mainDrawer``` Element.
It gets removed for any other than TV-Layout in ```librarymenu.js``` in line 778:
```
if (!layoutManager.tv) {
    navDrawerElement.classList.remove("hide");
}
```
Should I open a pull request and remove the ```.hide``` completly? Or is there any reason for it here?

**Comment by dmitrylyzo** [comment]
At the moment, menu should not be displayed in TV layout because it is not ready for TV layout - navigation is not polished. The button is displayed by mistake.

`isHomePage` makes it visible.
https://github.com/jellyfin/jellyfin-web/blob/6246dce3205c074462e5aab767abf6d122394d67/src/scripts/librarymenu.js#L887

**Comment by schmidex** [comment]
Ah ok. So the bug is not the not the invisible menu. It is the visible button in TV-mode?

**Comment by dmitrylyzo** [comment]
> Ah ok. So the bug is not the not the invisible menu. It is the visible button in TV-mode?

Yes. But in the future, main menu should be available in TV layout. I tried to make it accessible (this part is pretty simple), but got stuck with navigating into it from item containers and just put it off.
