### ISSUE TITLE
Remove Sync/Transcode option from webui.

### ISSUE THREAD

**Issue by dragon2611** [jellyfin/jellyfin-web#109]
Related to https://github.com/jellyfin/jellyfin/issues/183.

If sync isn't planned for jellyfin then please remove the sync buttons from the webUI so people don't try to use it.

Also the transcode button doesn't seem to work either, I'm not sure if that ones intentional or a bug, it would be nice if that worked for people with a lot of storage but lacking cpu power (E.g running on a nas) to do a non real-time transcode.

Edit: My media directory is R/O to jellyfin at the moment so that may have some bearing on this one.

**Comment by sparky8251** [comment]
Any word on progress here @nvllsvm ?

**Comment by nvllsvm** [comment]
No, I stopped progress a day after the last comment due to GPLocalyps. No intention of resuming sync porting.

**Comment by Matt07211** [comment]
Long hold option menu still has sync option if you are planning to remove it completely

**Comment by dkanada** [comment]
Could be in [here](https://github.com/jellyfin/jellyfin-web/blob/master/src/bower_components/emby-webcomponents/sync/sync.js), it's the last file I could find that was explicitly for sync support.

**Comment by dkanada** [comment]
All references to sync and convert have been removed from the web client for now, so this issue can be closed.
