### ISSUE TITLE
forgotpasswordpin submit retun page when entering pin 

### ISSUE THREAD

**Issue by grafixeyehero** [jellyfin/jellyfin-web#11]
![login](https://user-images.githubusercontent.com/32230989/50998985-30a64400-153a-11e9-8907-311ec13a2464.jpg)

**Comment by JustAMan** [comment]
Your fix is still not in public release (and not in `master`).
Please close only when the fix is merged to `master`, which should happen really soon.

**Comment by grafixeyehero** [comment]
sorry
