### ISSUE TITLE
Changing library settings other than paths doesn't save

### ISSUE THREAD

**Issue by 12nick12** [jellyfin/jellyfin-web#110]
The title says it all.

**Comment by cvium** [comment]
Is this still an issue? A lot of js bugs have been squashed since this was opened.

**Comment by sparky8251** [comment]
It is. In fact it is an inherited bug from Emby.

The problem with this is that we can't modify the library paths after they've been set at the database level. Will likely require a companion server issue and wait until the migration to ef core is complete.

**Comment by sparky8251** [comment]
Yeah, and none or very few of them can be changed after creation. In fact, I'd wager that the ways folks have found to modify them are in fact bugs.

There is no save button in the "edit view" despite it sharing similar but different HTML and JS code from the "create view".

**Comment by cvium** [comment]
I am very certain that everything is editable and it saves when the edit library dialog closes.

**Comment by dkanada** [comment]
@cvium is correct, it always saves with no confirmation, which wasn't ideal. I added a save button to explicitly confirm changes in a recent pull request so this issue should be entirely resolved in the next large update.

**Comment by DrPandemic** [comment]
@dkanada if your PR was merged, could we close this issue?
