### ISSUE TITLE
Track selections in detail page lack visual separation

### ISSUE THREAD

**Issue by Delgan** [jellyfin/jellyfin-web#1101]
**Describe the bug**
This is not a bug, but I feel the selection for tracks could be improved.

![Screenshot_2020-04-17 Jellyfin](https://user-images.githubusercontent.com/4193924/79570597-0555c180-80ba-11ea-8f1b-9eced29b0284.png)

In my opinion, there are two minor UI problems here:
* There is not visual separation between `1080P H264` (value) and `Audio` (label).
* There is no space between "Audio" dropdown list and "Subtitles" label

**To Reproduce**

1. Go to the details pages of a movie with multiple audio / subtitle tracks

**Expected behavior**
Visually "clean" separation of content.

**Logs**
Not relevant.

**System (please complete the following information):**
 - OS: Linux
 - Browser: Firefox 74
 - Jellyfin Version: 10.5.4

**Comment by MrTimscampi** [comment]
This was already fixed as part of #949 and should be available in 10.6.0.
