### ISSUE TITLE
LG Browser not play content.

### ISSUE THREAD

**Issue by manzajaro** [jellyfin/jellyfin-web#1102]
**Describe the bug**
Hi, 

In the latest version of jellyfin, the player does not work on LG Webos. When I play the content, only the spinner is displayed. The server did not receive the request, because it shows nothing in the log. I have log in mode debugg in the server.

**To Reproduce**

1. Go to any content
2. Click on Play

**Expected behavior**

Black screen and entry to player.

**Logs**

Nothing on the server and I can't debug LG

**Screenshots**

![20200417_190930](https://user-images.githubusercontent.com/6926926/79595476-398fa900-80df-11ea-896e-454049da8640.jpg)

**System (please complete the following information):**
 - OS: Server (Ubuntu) / Client (LG webos 5)
 - Browser: LG Webos 
 - Jellyfin Version: 10.5.4

**Additional context**

**Comment by Artiume** [comment]
What was the last working version?

**Comment by manzajaro** [comment]
In version 10.5.2 it was the last version that worked

**Comment by Artiume** [comment]
@dmitrylyzo you have any ideas?

**Comment by dmitrylyzo** [comment]
Symptoms ("endless" loading) tells that some module simply does not load due to error.

If debugging is not possible, I use :point_down:
<details>
<summary>diy on-screen logging </summary>

1. Create file `1debug.diff` with this content
```diff
diff -ruN jellyfin-web.master30/components/debug.js jellyfin-web.master30~debug/components/debug.js
--- jellyfin-web.master30/components/debug.js	1970-01-01 03:00:00.000000000 +0300
+++ jellyfin-web.master30~debug/components/debug.js	2020-03-21 23:38:39.557926928 +0300
@@ -0,0 +1,67 @@
+'use strict';
+
+console.log('Debug');
+
+//document.addEventListener('DOMContentLoaded', function() {
+    var debugOutput = document.createElement('textarea');
+    debugOutput.id = '#debugOutput';
+    debugOutput.style.position = 'fixed';
+    debugOutput.style.right = '5em';
+    debugOutput.style.bottom = '5em';
+    debugOutput.style.width = '50%';
+    debugOutput.style.height = '50%';
+    debugOutput.style.opacity = 0.5;
+    debugOutput.style.zIndex = '1000000';
+    debugOutput.tabIndex = -1;
+    debugOutput.readOnly = true;
+    document.body.appendChild(debugOutput);
+
+    if (debugOutput) {
+        var MaxLines = 1000;
+        var lines = 0;
+
+        var append = function(prefix, message) {
+
+            var atEnd = debugOutput.scrollTop + debugOutput.clientHeight + 20 > debugOutput.scrollHeight;
+
+            lines++;
+
+            if (MaxLines > 0 && lines > MaxLines) {
+                debugOutput.value = debugOutput.value.replace(/^.*\n/, '');
+                lines = MaxLines;
+            }
+
+            debugOutput.value += prefix + message + '\n';
+
+            if (atEnd) {
+                debugOutput.scrollTop = debugOutput.scrollHeight - debugOutput.clientHeight;
+            }
+        }
+
+        var console_log = console.log;
+        console.log = function(message) {
+            append('', message);
+            console_log.apply(console, arguments);
+        };
+
+        var console_error = console.error;
+        console.error = function(message) {
+            append('ERROR: ', message);
+            console_error.apply(console, arguments);
+        };
+
+        var console_debug = console.debug;
+        console.debug = function(message) {
+            append('DEBUG: ', message);
+            console_debug.apply(console, arguments);
+        };
+    }
+//});
+
+window.onerror = function (message, file, line, column, errorObj) {
+    console.error(file + ':' + line + ':' + column + '  ' + message);
+
+    if (errorObj) {
+        console.error(errorObj.stack);
+    }
+};
diff -ruN jellyfin-web.master30/scripts/apploader.js jellyfin-web.master30~debug/scripts/apploader.js
--- jellyfin-web.master30/scripts/apploader.js	2020-03-11 09:25:27.073541512 +0300
+++ jellyfin-web.master30~debug/scripts/apploader.js	2020-03-21 23:39:15.977300495 +0300
@@ -23,6 +23,7 @@
         injectScriptElement(
             "./libraries/alameda.js",
             function() {
+                injectScriptElement("./components/debug.js");
                 // onload of require library
                 injectScriptElement("./scripts/site.js");
             }
```

2. Go to `/usr/lib/jellyfin/bin/jellyfin-web`
3. Run command
```sh
patch -p1 < 1debug.diff
```
This will add file `components/debug.js` and inject it in `scripts/apploader.js`
Now, after site refresh, textarea should appear.

To quick turn it off just comment `injectScriptElement("./components/debug.js");` in `scripts/apploader.js`
</details>

**Comment by manzajaro** [comment]
![Inked20200420_140528_LI](https://user-images.githubusercontent.com/6926926/79750392-2b28d380-8311-11ea-970b-48d7a5ef4af4.jpg)
![Uploading Inked20200420_140740_LI.jpg…]()

**Comment by dmitrylyzo** [comment]
First error points to https://github.com/jellyfin/jellyfin-web/blob/51722fd2257eeb493b30b16d36556e2157e4211e/src/components/htmlMediaHelper.js#L187
Try to remove it. This line should not use template strings in stable branch because there is no babel.

**Comment by dmitrylyzo** [comment]
Tried again in emulator 4 through jellyfin-webos app (no browser in emulator) - template strings works.

**Comment by manzajaro** [comment]
Hi,

In jellyfin-webos app when

`console.debug(`seeking to ${seconds} on ${e.type} event`); 
`

![Inked20200420_170630_LI](https://user-images.githubusercontent.com/6926926/79769381-540a9200-832c-11ea-88d9-b6e006607d40.jpg)



![20200420_172445](https://user-images.githubusercontent.com/6926926/79769244-24f42080-832c-11ea-95bf-889c3d24cbd7.jpg)

**Comment by dmitrylyzo** [comment]
> when I commented the line. I can see next log, the video in lg browser and application work.

Good.
`error checking ScrollToOptions` is not a "real" error - just `try/catch` to check `scrollTo` options support, and this means that browser doesn't support it.

> OS: Server (Ubuntu) / Client **(LG webos 5)**

But according to [this](http://webostv.developer.lge.com/discover/specifications/web-engine/),  webOS TV 5.x is Chromium 68, and it should support template strings. I am confused :confused:

**Comment by manzajaro** [comment]
I'm sorry

I have tested the Webos version by making a script and the result is.

Result: {"modelName":"43UJ634V-ZD","firmwareVersion":"05.80.50","UHD":"true",**"sdkVersion":"3.8.0"**}

**Chromium Version 38**

I got confused with the firmware version.

If you need help, I am a developer, I would be happy to help.

Thanks
