### ISSUE TITLE
[Enhancement] User Library Reordering

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-web#1107]
Going into your User Settings > Home and reordering your library can be annoying with large libraries. I was thinking either adding a double arrow so you can rapidly place a library at the top or bottom. Or the ability to click and drag the libraries to their wanted location. 

Another issue but it deserves its own ticket is there's no way to set a default preference. If I create a new user, I have to either manually reorder the libraries from the UI or edit the xml file. 

![image](https://user-images.githubusercontent.com/20715731/79637473-ea349180-814d-11ea-8f59-d23aab3387c6.png)

**Comment by MrTimscampi** [comment]
Please redirect feature requests and suggestions to https://features.jellyfin.org/

**Comment by DMouse10462** [comment]
Wasn't this a tracking issue for a component to be worked on in Vue? It was a part of the UI Components Project, which only had that one item.
