### ISSUE TITLE
npm installing jellyfin-web

### ISSUE THREAD

**Issue by JonEllis** [jellyfin/jellyfin-web#1117]
**Describe the bug**
Appologies if this is me overlooking something silly.

When I install jellyfin-web as a dependency of [Jellyfin Electron](https://github.com/JonEllis/jellyfin-electron/) on linux, the directory in node_modules does not contain any useful code - the only directory is scripts. On macOS I get a dist directory, but no src directory (I see that src is in the .npmignore file, so that is expected)

On macOS I happen have node v13.12.0 and npm 6.14.4, but I've tried this in a docker container with several versions of npm. Also, someone testing my Electron app on non-dockerised Ubuntu 16.04 appears to have the same problem.

**To Reproduce**
```
docker run --rm -it ubuntu:16.04 bash
apt update
apt install -y curl git
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
source /root/.bashrc
nvm install 13.12.0 # gives npm v6.14.4 to match my macOS versions
npm install 'github:jellyfin/jellyfin-web'
```
This gives me this on linux:
```
ls -la node_modules/jellyfin-web/
total 92
drwxr-xr-x  3 root root  4096 Apr 22 20:51 ./
drwxr-xr-x 42 root root  4096 Apr 22 20:51 ../
-rw-r--r--  1 root root    11 Oct 26  1985 .eslintignore
-rw-r--r--  1 root root  5331 Oct 26  1985 .stylelintrc
-rw-r--r--  1 root root  4257 Oct 26  1985 CONTRIBUTORS.md
-rw-r--r--  1 root root 18014 Oct 26  1985 LICENSE
-rw-r--r--  1 root root  2897 Oct 26  1985 README.md
-rw-r--r--  1 root root    39 Oct 26  1985 babel.config.json
-rw-r--r--  1 root root  5474 Oct 26  1985 gulpfile.js
-rw-r--r--  1 root root  5038 Apr 22 20:51 package.json
-rw-r--r--  1 root root   201 Oct 26  1985 postcss.config.js
drwxr-xr-x  2 root root  4096 Apr 22 20:50 scripts/
-rw-r--r--  1 root root  1150 Oct 26  1985 webpack.common.js
-rw-r--r--  1 root root   954 Oct 26  1985 webpack.dev.js
-rw-r--r--  1 root root   752 Oct 26  1985 webpack.prod.js
```
I get the same result on Ubuntu 18.04 too.

**Expected behavior**
On macOS, `npm install 'github:jellyfin/jellyfin-web'` with the same versions of npm and node, the jellyfin-web directory in node_modules contains:
```
$ ls -la
total 160
drwxr-xr-x   16 jon  wheel    512 20 Apr 22:54 .
drwxr-xr-x   42 jon  wheel   1344 20 Apr 22:54 ..
-rw-r--r--    1 jon  wheel     11 26 Oct  1985 .eslintignore
-rw-r--r--    1 jon  wheel   5331 26 Oct  1985 .stylelintrc
-rw-r--r--    1 jon  wheel   4257 26 Oct  1985 CONTRIBUTORS.md
-rw-r--r--    1 jon  wheel  18014 26 Oct  1985 LICENSE
-rw-r--r--    1 jon  wheel   2897 26 Oct  1985 README.md
-rw-r--r--    1 jon  wheel     39 26 Oct  1985 babel.config.json
drwxr-xr-x  942 jon  wheel  30144 20 Apr 22:54 dist
-rw-r--r--    1 jon  wheel   5474 26 Oct  1985 gulpfile.js
-rw-r--r--    1 jon  wheel   5056 20 Apr 22:54 package.json
-rw-r--r--    1 jon  wheel    201 26 Oct  1985 postcss.config.js
drwxr-xr-x    5 jon  wheel    160 20 Apr 22:54 scripts
-rw-r--r--    1 jon  wheel   1150 26 Oct  1985 webpack.common.js
-rw-r--r--    1 jon  wheel    954 26 Oct  1985 webpack.dev.js
-rw-r--r--    1 jon  wheel    752 26 Oct  1985 webpack.prod.js
```
With it's very useful dist directory.
I expected that doing the same on linux would also give me the dist directory.

**Logs**
No errors found

**Screenshots**
None

**System (please complete the following information):**
 - OS: Docker - Ubuntu 16.04 and Ubuntu 18.04
 - Jellyfin Version: master branch

**Additional context**
I've also tried the full URL for npm installing, rather than the `github:` shortcut, and tried specifying by a tagged release - `github:jellyfin/jellyfin-web#v10.5.3`

**Comment by thornbill** [comment]
Have you tried using node 12? This is odd because the Android app installs web in this way without any issues. The only difference I see offhand is we use the lts release of node.

**Comment by JonEllis** [comment]
The same thing happens with node 12.

If I follow the getting started process for jellyfin-android, I have the same thing for the jellyfin-web package.

```
git clone https://github.com/jellyfin/jellyfin-android.git
cd jellyfin-android
npm install
```
```
ls -la node_modules/jellyfin-web
total 88
drwxr-xr-x   3 root root  4096 Apr 23 10:14 .
drwxr-xr-x 623 root root 20480 Apr 23 10:14 ..
-rw-r--r--   1 root root    11 Oct 26  1985 .eslintignore
-rw-r--r--   1 root root  5331 Oct 26  1985 .stylelintrc
-rw-r--r--   1 root root  4257 Oct 26  1985 CONTRIBUTORS.md
-rw-r--r--   1 root root 18014 Oct 26  1985 LICENSE
-rw-r--r--   1 root root  2706 Oct 26  1985 README.md
-rw-r--r--   1 root root  3164 Apr 23 10:14 package.json
drwxr-xr-x   2 root root  4096 Apr 23 10:14 scripts
-rw-r--r--   1 root root  1197 Oct 26  1985 webpack.common.js
-rw-r--r--   1 root root  1143 Oct 26  1985 webpack.dev.js
-rw-r--r--   1 root root   739 Oct 26  1985 webpack.prod.js
```

I haven't set up the android SDK, but I suspect something will fail if the assets from jellyfin-web are not present?

**Comment by thornbill** [comment]
Right. It definitely will not work without the `dist` directory.

**Comment by JonEllis** [comment]
It seems that when I yarn install, I at least get the `src` directory, so I can build it from there.
So I have worked around it in my project by building in a post-install script.

**Comment by MrTimscampi** [comment]
Closing as this is a question and we handle these outside of Github.
