### ISSUE TITLE
Add subtitle delay options when casting (gear icon)

### ISSUE THREAD

**Issue by Dharkhar** [jellyfin/jellyfin-web#1118]
When casting from an android phone, the "gear" icon disappears so it's not possible to set the subtitle's delay.

This first screenshot was taken when playing directly on my phone, the gear is available and I can sync the subs (and set quality, aspect ratio...):

![c91f6ae4-b557-4ce2-8422-07cbe3a880c2](https://user-images.githubusercontent.com/9743581/71768577-6f859480-2f17-11ea-9c09-13dff23cfeaa.jpeg)

This one, still on my phone, but when I cast on my chromecast:

![076eab3c-4a68-4a3b-868c-d3bd568d9c0e](https://user-images.githubusercontent.com/9743581/71768524-04d45900-2f17-11ea-8255-17374e87c8c3.jpeg)

**Comment by MrTimscampi** [comment]
Please redirect feature requests and suggestions to https://features.jellyfin.org/
