### ISSUE TITLE
Playlists strings are not translatable

### ISSUE THREAD

**Issue by Boki40** [jellyfin/jellyfin-web#1120]
![Jegyzet 2020-04-23 185628](https://user-images.githubusercontent.com/59022978/80127162-38092980-8594-11ea-89d1-6dfa4a3e6568.png)
On this screenshot (and on the homepage) the _Playlists_ word is not translatable, and for example on this screen, "New", "Filter" words are also missing.

**Comment by Camc314** [comment]
This is fixed by #1142
