### ISSUE TITLE
Poster image looks to blink while opening details page

### ISSUE THREAD

**Issue by Delgan** [jellyfin/jellyfin-web#1128]
**Describe the bug**
Hi. While re-opening the details page of a movie already cached, the poster image is blinking / flashing / flickering. Like if the image was redraw while it doesn't need to.

![ezgif-3-e2e5de577a85](https://user-images.githubusercontent.com/4193924/80279310-0e1f4680-86fd-11ea-8338-1873d9b3bc0a.gif)

Curiously, I tried to record my screen using an app like `peek`, but the bug was nos visible in outputed video, so I recorded my screen using a smartphone.

As this is easily reproducible on my computer, I can investigate this problem if you have any idea for where I should look at.

**To Reproduce**

1. Re-open the details page of a movie

**Expected behavior**
Image poster should not "blink".

**Logs**
Not relevant.

**System (please complete the following information):**
 - OS: Linux
 - Browser: Firefox 75
 - Jellyfin Version: master (v10.5.4+)

**Additional context**
It also happens on Windows using Firefox, but I could not reproduce it using Chrome.

**Comment by Delgan** [comment]
I guess it happens because the `lazy-image-fadein(-fast)` class is dynamically added after the `img` has been added to the DOM. 

If I comment lines in `fadeIn()`: https://github.com/jellyfin/jellyfin-web/blob/4bef70edccedfe299c31fd27d303f172678e7a7a/src/components/images/imageLoader.js#L34-L40

And instead add the class directly in the `img` tag there: https://github.com/jellyfin/jellyfin-web/blob/d4427e8a370b1d7b25e5aedbcf85c5350ccc2b0b/src/controllers/itemdetailpage.js#L827

Then it works fine.

I don't know how this kind of issue is suppose to be resolved, though.

**Comment by MrTimscampi** [comment]
This is probably due to the code for that poster being somewhat messy. It doesn't really use the Card component (like it should) and doesn't have a placeholder or anything.

The ideal solution would be to replace the entire poster with a card, but that would probably require a rewrite of some of the details page and the card builder...

**Comment by Delgan** [comment]
I think it's fixed with 10.6.0. Thanks. :+1:

**Comment by gordyhike** [comment]
This issue has returned in 10.8.1

**Comment by Delgan** [comment]
@gordyhike Too bad. :grimacing: 

Can you open a new issue, with a video? It will give more visibility I think.
