### ISSUE TITLE
Users Online

### ISSUE THREAD

**Issue by Sicer** [jellyfin/jellyfin-web#1136]
I come from plex and a feature that I find interesting is the one to see in the top bar of online users, can this functionality be implemented?
<img width="964" alt="plex-dashboard-01" src="https://user-images.githubusercontent.com/6973905/80314264-c37ef680-87f0-11ea-935e-41f4e631eaf5.png">

**Comment by eldrippy** [comment]
it's kinda neat but it would be definitely look good inside the general o active devices tab

**Comment by MrTimscampi** [comment]
Please redirect feature requests and suggestions to https://features.jellyfin.org/
