### ISSUE TITLE
The repeat button on nowplaying.html is highlighted improperly

### ISSUE THREAD

**Issue by sparky8251** [jellyfin/jellyfin-web#114]
If you have a music library and are on the now playing page, there is a repeat button.

If you click it once, it turns blue and gets a blue "bubble" around it and turns on repeat, again and the number 1 appears in the middle of the icon. 

3rd click you would expect the repeat button to return to white to indicate the option is off. This does not happen until you click elsewhere in the UI.

**Comment by DrPandemic** [comment]
I actually wrote a commit to "fix" that some weeks ago, but never submitted it. After checking other sites (like gmail and anchor.fm) I realized that they were doing the same thing.

![image](https://user-images.githubusercontent.com/3250155/57576158-b1f9de80-7427-11e9-976d-c54b096e0c3d.png)
![image](https://user-images.githubusercontent.com/3250155/57576222-6562d300-7428-11e9-8d65-35f1a89c6b49.png)


Pretty much all the icons kept the bubble.

I think it's done like that for people that navigate with the keyboard (eg. blind people). I agree that it's annoying, but I'm not sure what's the right approach here.

**Comment by dkanada** [comment]
This issue is probably resolved since we removed the annoying hover background. The new behavior for paper icons (the offending css class) is a blue icon for focus and a circular background on hover. @DrPandemic also made some excellent changes to improve the checkbox focus behavior.
