### ISSUE TITLE
[discussion] Plugin API

### ISSUE THREAD

**Issue by cromefire** [jellyfin/jellyfin-web#1143]
With the end of requirejs we need some other way to provide the plugins with an API they can call into:

_Note: This would only affect the new promise based way to register plugins_

There are the following proposals:
1. **Use `import()`**
    Good:
    - Familiar API
    
    Bad:
    - Would leak internal APIs
    
    Problems:
    - Doesn't work with webpack
    - Not compatible with old browsers
2. **Build own `require()`**
    Good:
    - Familiar API
    
    Bad:
    - No typesafety
    - Puts an object into global namespace
    
    Problems:
3. **Global object**
    Good:
    - Typesafety
    - Controlled API
    
    Bad:
    - Puts an object into global namespace
    
    Problems:
4. **Pass object**
    Good:
    - typesafety
    - Controlled API
    - Can be preconfigured per plugin
    
    Bad:
    - Needs to be passed around by the plugin
    
    Problems:

**Comment by cromefire** [comment]
I'd prefer the passing of an object because it does provide a controlled API, works with typesafety (useful for ts later on) and doesn't pollute the global namespace

**Comment by molszanski** [comment]
Hmm.. I don't understand the options. 
Can you point to some existing plugins you have in mind and you wish to support?

**Comment by molszanski** [comment]
Successful plugin systems that I know:
- webpack plugins. You pass plugins as functions to webpack, and he calls them with a fixed signature and provides objects
- poscss plugins. The same as webpack
- express middleware, node.js streams - fixed function signature with typed passable data

**Comment by cromefire** [comment]
We already have a lot of plugins. Look at android they have one written. You should familiarize yourself with the plugins first.

> Successful plugin systems that I know:
> 
>   * webpack plugins. You pass plugins as functions to webpack, and he calls them with a fixed signature and provides objects
>   * poscss plugins. The same as webpack
>   * express middleware, node.js streams - fixed function signature with typed passable data

Our use case is a lot different here, we need to port existing plugins to some replacement api, because our current api is going to vanish soonish because of infrastructural changes.

This issue is primarily meant to structure the discussion we had in matrix.

**Comment by dkanada** [comment]
@molszanski right now we technically already have frontend plugins, but they need a revision for the ES6 and Vue migrations. All media players, screensavers, and a few other items are plugins.

**Comment by molszanski** [comment]
> We already have a lot of plugins. Look at android they have one written. 
Yeah, I've checked before posting. They didn't look like web based to me, hence the question.

**Comment by cromefire** [comment]
Shush bot
