### ISSUE TITLE
Update page title for navigaion and now playing music

### ISSUE THREAD

**Issue by joytrekker** [jellyfin/jellyfin-web#1147]
When browsing Jellyfin web it seems to update the page title randomly. I can see it updates for entering a video library and playing a video. However it does not appear to update the title for any other pages or for now playing music. I would expect the title to always show the now playing music. When music or a video is not playing then every page should update the title instead of just defaulting to Jellyfin.

**Comment by MrTimscampi** [comment]
In keeping with the decision in #1224 to not implement titles and instead rely on the standard Media Sessions API to provide playback details to the user's environment, I am closing this issue.
