### ISSUE TITLE
Move subtitles up when video controls are shown

### ISSUE THREAD

**Issue by drikqlis** [jellyfin/jellyfin-web#1149]
When video controls are shown currently subtitles are covered by it and it is hard to read them. It would be great if they could go up when controls are shown just like YouTube subtitles, and go back down when controls are hidden. Could it be done by CSS?

**Comment by Artiume** [comment]
For browser rendered subtitles, I feel like this is a feasible fix. But I'm not sure if burned-in subtitles can be done

**Comment by MrTimscampi** [comment]
Please redirect feature requests and suggestions to https://features.jellyfin.org/
