### ISSUE TITLE
More Like This Poster Size Default

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-web#1152]
So currently my library is being rebuilt so metadata is still filling in. One issue I'm seeing is that the default poster size seems to be thumbnail.  

In this snippet, none of the More Like This have Posters yet, a few have Background pictures so I believe that might be having an impact.
![image](https://user-images.githubusercontent.com/20715731/80589445-30a8ac80-89e8-11ea-9e75-b9e2d8f6c8e1.png)

Once a single item has a Poster, they all normalize
![image](https://user-images.githubusercontent.com/20715731/80589781-d825df00-89e8-11ea-9dd4-0f96a652fdc6.png)

**Comment by Artiume** [comment]
I believe it stems from the cards themselves having the wrong default size.

![image](https://user-images.githubusercontent.com/20715731/80750614-61770780-8af6-11ea-891d-59922e2fc07e.png)

**Comment by MrTimscampi** [comment]
@Artiume Is this still a thing?

**Comment by Artiume** [comment]
That one might be trickier to check. I'd have to start a fresh database to see if it occurs. I'll close it for now and reopen it if I need to.
