### ISSUE TITLE
Wizard startup text difficult to see

### ISSUE THREAD

**Issue by BaronGreenback** [jellyfin/jellyfin-web#1154]
Wizard display text can hardly be seen on the latest pull from GitHub

![Untitled](https://user-images.githubusercontent.com/22121540/80611822-092b0180-8a33-11ea-962a-d7b0e158cfd8.png)

**Comment by MrTimscampi** [comment]
@BaronGreenback Is this still a thing?

**Comment by BaronGreenback** [comment]
will download the latest unstable, reset my system and let you know.

**Comment by BaronGreenback** [comment]
Fixed in the latest unstable.
