### ISSUE TITLE
[Mobile] More Like This Missing Menu Icon

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-web#1158]
![Screenshot_20200428-222743_Jellyfin](https://user-images.githubusercontent.com/20715731/80663351-b87ecd00-8a61-11ea-9d2f-81217c6050fc.jpg)

Whereas on the library pages, you get 
![Screenshot_20200429-213424_Jellyfin](https://user-images.githubusercontent.com/20715731/80663416-ea902f00-8a61-11ea-9f15-6a2e901229bb.jpg)

The cards are designed a little different, one has a menu button and the other has a play button. Perhaps a whole new design to marry the both could work. A soft play icon that appears when you hover in the center of the card while the menu gets the lower right spot of the card.

**Comment by Artiume** [comment]
On desktop, the layover has more options. Since space is a concern, we'll have to figure out the best solution

![image](https://user-images.githubusercontent.com/20715731/80752740-0cd58b80-8afa-11ea-9c1c-55b699979713.png)

**Comment by MrTimscampi** [comment]
Not really a bug, but a UI suggestion/improvement.

Please redirect feature requests and suggestions to https://features.jellyfin.org/
