### ISSUE TITLE
[Enhancement] Add bit to video codec details

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-web#1160]
To differentiate between 8bit and 10bit content, its label should be added on the details page of content

![Screenshot_20200430-083028_Jellyfin](https://user-images.githubusercontent.com/20715731/80710699-2e645200-8abd-11ea-8c00-6d01f8bbae45.jpg)

**Comment by hamburglar2160** [comment]
Along with this,  the "**P**rogressive in 720P and 1080P (480?) should be bumped to lowercase.

**Comment by MrTimscampi** [comment]
Please redirect feature requests and suggestions to https://features.jellyfin.org/
