### ISSUE TITLE
Ability to hide watched items in libraries

### ISSUE THREAD

**Issue by peioe** [jellyfin/jellyfin-web#1161]
Hello

Would it be possible to hide watched items (movies, shows) "semi permanently" from libraries ? Currently you can filter them out but you have to do it every time you open a library.
Just being able to have the option stick would be enough, is that possible ?

Thank you everyone, jellyfin is great :)

**Comment by Artiume** [comment]
I think the best way to implement this would be to allow the client to remember the filter settings set and then add something such as a RESET button or something at the bottom of the filter list.

![image](https://user-images.githubusercontent.com/20715731/80864922-f3e0ed80-8c53-11ea-8752-4690d92154e3.png)

**Comment by peioe** [comment]
Yes that's what I meant by having the option stick, that would be perfect imo. At least for my use case.

**Comment by Artiume** [comment]
https://github.com/jellyfin/jellyfin-web/blob/master/src/components/filterdialog/filterdialog.template.html

There's quite a few enhancements to the filter system that I'd like to see, but I don't think they're all possible yet. Filter by subtitle type, codec type, resolution, bitrate and so on.

**Comment by MrTimscampi** [comment]
Please redirect feature requests and suggestions to https://features.jellyfin.org/
