### ISSUE TITLE
wrong align

### ISSUE THREAD

**Issue by dga4130-renato** [jellyfin/jellyfin-web#1169]
![IMG_20200502_072054](https://user-images.githubusercontent.com/43514633/80856052-dd806500-8c46-11ea-81d3-3175bcbaec74.jpg)

**Comment by dmitrylyzo** [comment]
This is web. And I think this is a duplicate of #946

**Comment by dga4130-renato** [comment]
Yes it is .

Il sab 2 mag 2020, 08:47 Dmitry Lyzo <notifications@github.com> ha scritto:
