### ISSUE TITLE
Allow usage of Folder view as default screen for home items

### ISSUE THREAD

**Issue by jy3344511** [jellyfin/jellyfin-web#1170]
![01](https://user-images.githubusercontent.com/49992475/80591454-4fdb2480-8a50-11ea-9159-6fd7e12e6380.jpg)

**Comment by Artiume** [comment]
Go to the Dashboard > Libraries > Display > Enable `Display a folder view to show plain media folders

This will make a new library that's file based on all your other libraries. It's not perfect but I think it'll suite your needs 😁

**Comment by MrTimscampi** [comment]
Please redirect feature requests and suggestions to https://features.jellyfin.org/
