### ISSUE TITLE
Double icons

### ISSUE THREAD

**Issue by Bond-009** [jellyfin/jellyfin-web#1193]
**Screenshots**
![image](https://user-images.githubusercontent.com/21289123/81302811-1e2f1280-907b-11ea-82f3-d762a7cf31fc.png)

**System (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Jellyfin Version: nightly

**Comment by dmitrylyzo** [comment]
Could it be a browser cache issue? I checked `master` branch right now and no double icon.

**Comment by Artiume** [comment]
does MacOs use Firefox Quantum or ESR?

**Comment by Bond-009** [comment]
I'm going to close this as I can't reproduce it on Firefox on Linux and it's probably a cache issue
@Artiume Quantum
