### ISSUE TITLE
Finish up the player revamp #1056

### ISSUE THREAD

**Issue by samuel9554** [jellyfin/jellyfin-web#1195]
Need help to finish the player revamp #1056 

So I've been using the revamp for a few week now and it work great.
It will be nice if someone could finish the context menu. 

If music playing it would be nice to have those options.
- View Artist
- View Album
- Download or sync
- Media Info
- Instant Mix

If series casting to a device
- View Season
- View Serie
- Media Info

If movie casting to a device
- View Movie page
- Media Info

**Comment by hamburglar2160** [comment]
Specifically for "View..." options, the elements for Artist, Album, Season, Series, and Movie should all be clickable and link directly to their details page. This should follow the behavior of the item details pages from 10.5 so this doesn't need to be in a context menu.

This will call for several PRs.

@KristupasSavickas had a great [suggestion ](https://github.com/jellyfin/jellyfin-web/pull/1056#issuecomment-615078338)for hiding the volume slider.

On desktop, the queue should always be visible. It currently defaults to hidden/collapsed. When visible and the next song begins it hides. On mobile, especially for phones from the last few years, having the queue visible by default would be preferable. Really, there doesn't need to be a hide/show queue button--just remove it.

Also on desktop, move the context menu and "save playlist" buttons from low and center over to the same row as the media control buttons, placed next to the repeat and heart buttons. Better yet, place the "save playlist" button into the context menu as that probably is not a very popular button. A shuffle button would be great here too.

On Mobile, let's move the heart and the menu buttons to the bottom right of the album art, perhaps with a 30% opaque radial background in a way that mimics Jellyfin's media library here. Poweramp's [Player UI](https://github.com/jellyfin/jellyfin-web/issues/1148#issuecomment-620939302) has the general idea.
![image](https://user-images.githubusercontent.com/61879508/81343088-52f29800-9082-11ea-9199-83dc97b38671.png) This will free up valuable space for long song, album, or artist names. If there is a freak scenario where the names run too long, consider implementing [CSS scrolling text](https://www.html.am/html-codes/marquees/css-scrolling-text.cfm). Poweramp uses this to great effect when that is actually required. 

This is more personal preference but I'd like to see "Artist - Album Title" on one line. For casted TV episodes,
"Episode Title
Season #, Episode #
Series Name"

**Comment by samuel9554** [comment]
@hamburglar2160 I think all you mentions should be done in a different PR. 
Let take baby step on this one. The last PR was a big one. Not perfect for sure but functional.

> On desktop, the queue should always be visible.

Totally agree with you. This is a issue introduced by the last PR.

> On mobile, especially for phones from the last few years, having the queue visible by default would be preferable. Really, there doesn't need to be a hide/show queue button--just remove it.

I think we should considerate only one design that fit all device. What I can see that could work is a snapping scroll down to see the playlist, like in spotify for the lyrics. See example here.
https://codepen.io/team/css-tricks/pen/yLLqqgP

> The seekbar could be made wider too. This would allow for more granular control. Moving the current and end times below is a good way to do this.
image.

I don't see why we couldn't do that. We just need to call the community to vote on this one since it will be nice to have the same thing everywhere (video playback)...

**Comment by ferferga** [comment]
If we're planning to add synced lyrics in the future (which I want to have), I would leave that space empty for that purpose, se we're in a similar state as Spotify.

**Comment by Artiume** [comment]
Found this artifact, the nowplaying bar doesnt play well with short screens. 

![image](https://user-images.githubusercontent.com/20715731/82128180-27a93080-9787-11ea-9b23-37411b63afb9.png)

**Comment by samuel9554** [comment]
Are you able to scroll down?

**Comment by Artiume** [comment]
I was able to scroll down maybe a quarter inch, not much at all.

**Comment by ferferga** [comment]
> Found this artifact, the nowplaying bar doesnt play well with short screens. 
> 
> ![image](https://user-images.githubusercontent.com/20715731/82128180-27a93080-9787-11ea-9b23-37411b63afb9.png)
> 

That's not mobile layout

**Comment by Artiume** [comment]
Yup, it's mobile

**Comment by ferferga** [comment]
@samuel9554 I guess we can make that bottom bar not sticky in our next revision. So playback buttons are always accessible first.

**Comment by samuel9554** [comment]
> 
> 
> @samuel9554 I guess we can make that bottom bar not sticky in our next revision. So playback buttons are always accessible first.
> 
> Although they're accesible scrolling, we should ease their access.

I think if we unset the background-color it should work.

**Comment by ferferga** [comment]
> > 
> > 
> > @samuel9554 I guess we can make that bottom bar not sticky in our next revision. So playback buttons are always accessible first.
> > 
> > Although they're accesible scrolling, we should ease their access.
> 
> @ferferga I think if we unset the background-color it should work. What do you think?

Wouldn't that conflict with the buttons when the menus are open or when the volume slider is there?
