### ISSUE TITLE
Customize Home Screen never goes away

### ISSUE THREAD

**Issue by devenator** [jellyfin/jellyfin-web#120]
The "Customize Home Screen"-Bar at bottom never goes away, even after clicking it and changing options for the user's homescreen.

**To Reproduce**

1. Open Jellyfin web-gui.
2. "Customize Home Screen" appears a few seconds after the whole page (content) has been loaded at the bottom of the homescreen.

**Expected behavior**
permanently remove it after clicking it once and/or changing any options in User Options.

(My Two Cents: Remove it completely. This was basically part of E-Who-Shall-Not-Be-Named's push for "Explore and Discover (Premier, buybuybuy)", and i find it insulting that every app feels a need to tell me that i can ... customize my options! </My To Cents>)

**Screenshots**

![chs](https://user-images.githubusercontent.com/45917913/52287985-86201600-296b-11e9-9064-fb2e0a21d7a1.jpg)

**System (please complete the following information):**
 - OS: Ubuntu 18.04 X64 (build with docker)
 - Browser: Firefox, Chrome
 - Jellyfin Version: 10.0.1

**Additional context**
This is on a clean, fresh installation, not a migrated one, user also new and not migrated. Also, E*** had the same problem multiple times in ~2017...

**Comment by JustAMan** [comment]
Hmm, I would rather we have it there with a button that says something like "I know I can customize in profile settings", so that clicking that button removes that "customize" bar for this user completely.

So it's still there for new users to see, and is easily dismissable by veterans.

**Comment by devenator** [comment]
Well i've just found out that this was actually added *after* my last E*** Version (old 3.2.x .net), i was pretty certain that i was seeing it there and it went away after clicking around, but acording to [the old forum](https://emby.media/community/index.php?/topic/61194-remove-customize-home-screen-button/), this is basically just trolling by luke, because TWO obvious ways (three-dot-menu AND the profile-icon) to get into the user-profile are not enough.

But the workaround still works:

```
Dashboard -> Settings -> custom css
 
#homeTab .customizeSection {display: none}

```
Again, my2cents: From gmail to youtube, the profile icon in the upper right is used everywhere, if someone really does not get this, it's probably better if he/she/it does not change settings in there anyways. But for me, the custom-css is good enough :)

**Comment by anthonylavado** [comment]
This is fixed in the upcoming release. Thanks!
