### ISSUE TITLE
[suggestion] Add taller, more accessible arrows to home screen carousels

### ISSUE THREAD

**Issue by hamburglar2160** [jellyfin/jellyfin-web#1201]
Currently, the home screen carousels have arrows that are rather small and require some precision to press.
![image](https://user-images.githubusercontent.com/61879508/81354215-08304a80-9099-11ea-98b0-be4e0b2e0fcf.png)
They can be bigger and more easily accessible. This is mostly a CSS change.
HBO and Alamo Drafthouse, at the very least, do this well.
![image](https://user-images.githubusercontent.com/61879508/81354110-cd2e1700-9098-11ea-9112-fa1e3cd15a9f.png)

With this change one press of an arrow could progress the caroseul one item as opposed to x>5 items.

**Comment by dmitrylyzo** [comment]
#998

**Comment by hamburglar2160** [comment]
I noticed that earlier and for some reason closed a different issue. Whoops.
