### ISSUE TITLE
Edit images cropped

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin-web#1207]
**Describe the bug**

Primary, Banner, Logo type images are displayed incorrectly. The full image is not display, just a 16:9 section of them

**To Reproduce**

1. Go to Tv Series
2. Click on 'Edit Images'
3. View image layout

**Expected behavior**

Full image should be displayed, scaled to fit in the area reserved.

**Screenshots**

![image](https://user-images.githubusercontent.com/991618/81431472-ca7a0300-9126-11ea-8c16-428da6658a27.png)

**System (please complete the following information):**
 - OS: LSIO Docker
 - Browser: Chrome
 - Jellyfin Version: 10.5.5

**Comment by masterkoppa** [comment]
Is the goal to have something like this? Or do we want to be smarter about weird aspect ratios (too tall or too wide).

![image](https://user-images.githubusercontent.com/108104/82395943-a964bc80-9a1a-11ea-8852-e9fd0ce2e4bc.png)

If so, it should be pretty straightforward to implement.

**Comment by SenorSmartyPants** [comment]
That would fix the bug I reported. Anything beyond that would be an enhancement in my book.

**Comment by IanS5** [comment]
It might help a bit to make the background around the image a bit lighter, to keep the cards looking similar even if the images have significantly different aspect ratios.
Something along the lines of this maybe:
![image](https://user-images.githubusercontent.com/16871649/82764302-b8ad8680-9ddb-11ea-89c1-b0a20b7acaae.png)

**Comment by Influence365** [comment]
I've opened a pull request with the changes
