### ISSUE TITLE
Embedded subtitles don't work over DirectStream/Transcode (HW)

### ISSUE THREAD

**Issue by Sockolet** [jellyfin/jellyfin-web#1214]
**Describe the bug**
Whenever I play a video using Chome or Firefox with embedded SubRip subtitles inside the MKV container, subtitles are not being showed at all. It works perfectly with external SRT subtitles. It works perfectly with embedded PGS subtitles (well, they are offset, but I understand that's another issue).

**To Reproduce**
1. Open any MKV video with SubRip subtitles embedded and active them.
2. Video is played but subtitles are not being shown.

**Expected behavior**
Subtitles are being showed.

**Logs**
https://pastebin.com/raw/U5WJxwTU (SubRip -> Non-working)
https://pastebin.com/raw/LMZPegrk (PGS -> Working)

**Screenshots**

![image](https://user-images.githubusercontent.com/8806527/81496906-51f87b00-92bb-11ea-80a0-20ad1af74cbc.png)
![image](https://user-images.githubusercontent.com/8806527/81496915-663c7800-92bb-11ea-9d2a-ec135ba90595.png)

**System (please complete the following information):**
 - OS: Ubuntu Server 18.04
 - Browser: Firefox, Chrome, Safari
 - Jellyfin Version: 10.5.5

**Additional context**
I've seen some other similar bugs, but they all mentioned to have been addresed on previous Jellyfin versions... I'm using very latest stable version.
https://github.com/jellyfin/jellyfin/issues/2650
https://github.com/jellyfin/jellyfin/pull/2653

**Comment by Artiume** [comment]
So the SUBRIP version is Direct Streaming while the PGS is burning in. 

If you don't select the subs and play the video without, does it work until selecting the subs or how is it failing?

**Comment by Sockolet** [comment]
If I don't select the subs and I activate them during the playback, they aren't being shown either.

**Comment by BXZ1** [comment]
Could https://github.com/jellyfin/jellyfin-android/issues/384 be related to this by any chance?

**Comment by krishne35** [comment]
Any fix on this im struck with the same issue (10.6.4)

**Comment by Ezzahhh** [comment]
Issue still exists in 10.6.4 for me as well. Subrip subtitles are unusable.
