### ISSUE TITLE
Allow user to enable/disable channels for DVR

### ISSUE THREAD

**Issue by dinki** [jellyfin/jellyfin-web#122]
Currently users are not able to enable or disable channels for the DVR.  Several users have come into chat or reddit requesting this functionality.

This could be added to the existing 'map channels' (Admin panel->Live TV->[pick TV Guide Data Provider]->Map Channels) as a check box type toggle for enable/disable with default being all enabled.

![image](https://user-images.githubusercontent.com/2521542/52345515-09c91980-29e3-11e9-987e-537c69e8ad85.png)

Perhaps the blue icon could be the toggle.

**Comment by halfagascan** [comment]
subscribing to "SOME" iptv service providers, you may receive a list containing many languages that are not relevant to your language. There should be a filter, to limit the channels you wish to receive, filtered by "LANG="somefilter", or channel. Ideally, this would occur prior to downloading any list.In addition a method to sort channels would be an added benefit.

**Comment by sparky8251** [comment]
@halfagascan You should open an independent issue for the language filtering. It's different enough from the original request that it should be tracked elsewhere.

**Comment by MrTimscampi** [comment]
Please redirect feature requests and suggestions to https://features.jellyfin.org/
