### ISSUE TITLE
Upcoming Deprecation of document.registerElement

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-web#124]
Using the Web interface in Chrome (and in the Android app), and noticed this hanging out in the console:

```
[Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.

(anonymous) @ paper-icon-button-light.js?v=10.1.0:15
```

**Comment by cvium** [comment]
That's a general issue though. Lots of components use `document.registerElement`.

**Comment by EraYaN** [comment]
This is now completely broken in the latest beta of Firefox (72.0b3). It does not load at all.

https://developer.mozilla.org/en-US/docs/Web/API/Document/registerElement
And this seems to be the replacement: https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define

**Comment by JustAMan** [comment]
@MrTimscampi will your webpack polyfill efforts fix this?

**Comment by MrTimscampi** [comment]
@JustAMan Funny you ask that, I have an issue with it not being defined and I was thinking about swapping it for the newer standard.

I don't think core-js (Babel's polyfill) has a CustomElement polyfill, but I'll add one manually.

**Comment by trueChazza** [comment]
I'm currently working on this.

**Comment by JustAMan** [comment]
Is this still an issue? `webcomponents.js` which we bring for something implement `document.registerElement` along with `window.customElement`, so this should probably be closed.

**Comment by MrTimscampi** [comment]
We shouldn't rely on deprecated APIs, so yes ;) The polyfill gives us a break from the deprecation date, but we should still get rid of it at some point.
