### ISSUE TITLE
Queue disappears/is empty when playing to remote device

### ISSUE THREAD

**Issue by hamburglar2160** [jellyfin/jellyfin-web#1244]
When playing media (at least music) on a local device with a populated playqueue, then casting to a remote device (Cast, Mopidy, Kodi, etc.), the tracklist disappears and the playqueue seems to be empty.

Selecting any song in an album will result in only the first song being played. Shuffling results in one song being played total.

This is a pretty open-ended issue so I'm not sure how far this goes. mcarlton00 suggests it's a javascript thing.

**Comment by Zen3515** [comment]
Why is this closed? I'm still experiencing this right now.
