### ISSUE TITLE
Transcoding Quality 1080p 4Mbps actually 720p 4Mbps

### ISSUE THREAD

**Issue by adavier** [jellyfin/jellyfin-web#1249]
Selecting 1080p 4Mbps when 720p 4Mbps is available, actually transcodes to 720p.

**To Reproduce**

Play 1080p or greater video,
Select 1080p 4mbps
720p 4mbps will actually be encoded.

This occurs on at least 1920x1080 and 1920x804.

**Expected behavior**
1080p 4mbps transcoding

**System (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox, Chrome
 - Jellyfin Version: 10.5.5

**Additional context**

**Comment by aussetg** [comment]
Same for 1080p 40Mbps, 50Mbps and 60Mbps -> they actually are 4K
