### ISSUE TITLE
Web config is loaded from the wrong URL when the web client is bundled with the server

### ISSUE THREAD

**Issue by mark-monteiro** [jellyfin/jellyfin-web#1254]
**Describe the bug**
The web config file and the config template files are loaded from the wrong URL when the web client is being served by the server. For example, `/config.template.json` is used instead of `/web/config.template.json`

**To Reproduce**
1. Follow the instructions to serve the web client from the server: https://github.com/jellyfin/jellyfin#installing-the-web-client
2. Load the web client
3. See that the config file and template are requested from the wrong URL

**Expected behavior**
The config and config template should use the correct URL and load correctly.

**Logs**
From the server logs:
```log
[12:33:12] [ERR] [44] Emby.Server.Implementations.HttpServer.HttpListenerHost: Could not find handler for /config.template
[12:33:12] [ERR] [44] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: Unable to find the specified file. URL: http://localhost:8096/config.template.json   
```
From the web client logs:
```log
cannot get web config: SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data" webSettings.js:25:16
```

**Comment by pelusa1982** [comment]
the file can be access on:
http://localhost:8096/web/config.template.json 
but the app search for:
http://localhost:8096/config.template.json
