### ISSUE TITLE
Admin dashboard - long filenames hide the time

### ISSUE THREAD

**Issue by ckcr4lyf** [jellyfin/jellyfin-web#1265]
If the filename is very long, the `<div>` for the playback position / time is shifted outside the card, and not visible, along with part of the filename. 

See:
![image](https://user-images.githubusercontent.com/6680615/82224271-f3b74200-9923-11ea-9f12-f722dd92107a.png)

**To Reproduce**
Play a file with very long name and view admin dashboard

**Expected behavior**
Ability to view the playback time, and at least partial, ellipses (...) terminated file name

**Possible Solution**
Move the playback time to below the "Play / Stop" controls

![image](https://user-images.githubusercontent.com/6680615/82224478-2bbe8500-9924-11ea-8d03-df96c59401ff.png)

I can make a pull request for this, but I don't know if this will be an accepted solution since it changes the timer position.

**Comment by Artiume** [comment]
10.4.3 is old, try 10.5.5. I'm on nightly and it appears to be fixed.

![Screenshot_20200518-111746_Remote Desktop](https://user-images.githubusercontent.com/20715731/82230060-3adc0d80-98f9-11ea-92d9-3b236a4fbdcf.jpg)

**Comment by ckcr4lyf** [comment]
Sorry, silly me, was on old WebUI. Thanks
