### ISSUE TITLE
Clarify FreeBSD instruction

### ISSUE THREAD

**Issue by KucharczykL** [jellyfin/jellyfin-web#1268]
https://github.com/jellyfin/jellyfin-web/blob/538462ce8aee79a981ae02ba91cba35c47c7a35e/src/strings/en-us.json#L992

This string is incorrect and thus potentially confusing. Please correct me if I'm wrong but AFAIK the original BSD does not have any jails, that is a feature of FreeBSD and its ilk (most commonly, FreeNAS). Thus I recommend changing the description to:

`For FreeBSD or FreeNAS, you may need to configure storage using a jail in order to allow Jellyfin to access it.`

I can create a PR if we agree on wording.

**Comment by MrTimscampi** [comment]
The wording looks good to me :)

**Comment by KucharczykL** [comment]
Done. Let me know if it's OK like this.
