### ISSUE TITLE
iOS - Screen lock pauses music

### ISSUE THREAD

**Issue by joaovitoriasilva** [jellyfin/jellyfin-web#1278]
When listening to music on iPad or iPhone if the screen locks the music will stop. The screen must be unlocked and I must go to the application to start the music again. It appears that iOS stops the background process associated with this.

**Comment by MrTimscampi** [comment]
@thornbill Do you think this is on the web site or the expo side?

**Comment by thornbill** [comment]
This is a limitation of iOS Safari and the iOS webview. It aggressively stops background processes when the screen locks. I haven’t found any way to avoid this outside of using a native media player.

**Comment by joaovitoriasilva** [comment]
> This is a limitation of iOS Safari and the iOS webview. It aggressively stops background processes when the screen locks. I haven’t found any way to avoid this outside of using a native media player. 

When you say a native player, what do you use?

**Comment by thornbill** [comment]
I think MrMC is the only option that currently supports music. It's interface may not be the best on phones, but it seems to work fine.

Hopefully our app will feature native playback at some point in the not-to-distant future, but no one is currently working on that.

**Comment by anthonylavado** [comment]
Regarding the iOS **app** side, this is the better issue to follow: https://github.com/jellyfin/jellyfin-expo/issues/19

**Comment by Darkwolf1515** [comment]
Just wanted to chime in and say this has never been an issue on either my ipad (on both 13 and 14) or my iphone running 13. plays just fine with screen lock.

**Comment by dkanada** [comment]
Since this is technically an iOS (as well as Android) issue, it should be tracked on those repositories for now.
