### ISSUE TITLE
Add a CBZ/CBR reader

### ISSUE THREAD

**Issue by MrTimscampi** [jellyfin/jellyfin-web#1281]
This is a feature tracking issue for post 10.6.

The goal is to expand on #1263 to add CBZ/CBR support to the web client.

Currently, [this BSD-2-clause component](https://github.com/matthewp/comic-reader) seems like a good candidate to handle the reader part for us.

**Comment by SenorSmartyPants** [comment]
Please implement this as a plugin. I want to use jellyfin primarily for video. Any extra functionality should be optional in my (comic)book.

**Comment by MrTimscampi** [comment]
Metadata is handled in the "Bookshelf" plugin, but the rest is already part of the core server and the web client can already list, add and handle books (including comics).

The readers for various file formats currently have to be part of the web client, but are only loaded when playing content of that type.

If you don't have books in your libraries, this will change absolutely nothing in Jellyfin for you.

**Comment by Darkwolf1515** [comment]
By "feature tracker", do you mean just leaving this so people know a reader is in development, or as in this is where we can request features to be added to the reader. Just trying to learn how things work, so sorry about asking. I do have some features if its the latter.

**Comment by MrTimscampi** [comment]
@Darkwolf1515 For features requests, we ask that you go to https://features.jellyfin.org/

This issue was made before we reworked the issues on this repository, and was mainly a reminder for myself to work on this at some point.  
However, since we made the rules around issues a bit more strict recently (Because with 200 open issues, where about half are feature requests or suggestions, it gets difficult to follow bugs and legitimate issues), this is likely to get closed.

As such, generally, we ask that discussions around new features be done through https://features.jellyfin.org/, while discussions about features currently in development lives on the pull request for it (While staying in the scope of that pull request, of course).

**Comment by Darkwolf1515** [comment]
> 
> 
> @Darkwolf1515 For features requests, we ask that you go to https://features.jellyfin.org/
> 
> This issue was made before we reworked the issues on this repository, and was mainly a reminder for myself to work on this at some point.
> However, since we made the rules around issues a bit more strict recently (Because with 200 open issues, where about half are feature requests or suggestions, it gets difficult to follow bugs and legitimate issues), this is likely to get closed.
> 
> As such, generally, we ask that discussions around new features be done through https://features.jellyfin.org/, while discussions about features currently in development lives on the pull request for it (While staying in the scope of that pull request, of course).

So since its not done, I should ask on #1325 right?

**Comment by MrTimscampi** [comment]
> Should be within the scope, just some page display options.

That PR is for a "barebones" viewer, as in "one page, in one direction". Further improvements will be made in subsequent PRs.

**Comment by Protektor-Desura** [comment]
I thought I would mention here is a bit more featured Comic Book that has an MIT license and uses javascript like the epub reader.

https://github.com/afzafri/Web-Comic-Reader
