### ISSUE TITLE
Downloading a movie does not include external subtitle file(s)

### ISSUE THREAD

**Issue by clizzin** [jellyfin/jellyfin-web#1303]
Downloading a movie only includes the media file and not any external subtitle files (e.g. `.srt` files).

This is on version 10.5.5 running on Ubuntu 19.10.

### To reproduce
1. Go to the "item details" page for a movie with at least one external subtitle file
2. Select a subtitle file from the "Subtitles" dropdown menu
3. Click the "More" menu (ellipses icon)
4. Click "Download"
5. The media file will begin downloading, but not any of the `.srt` files

### What I expect to happen
A few possibilities here:
1. It could download a `.zip` file containing the media file and all external subtitle files
2. It could download a `.zip` file containing the media file and the file associated with the subtitle currently selected in the web UI
3. It could bring up a modal asking the user what they want to do, and the user could then choose the behavior of Option 1 and 2, or something else

Option 1 would probably be simplest to implement and satisfy most use cases.

**Comment by MrTimscampi** [comment]
Please redirect feature requests and suggestions to https://features.jellyfin.org/
