### ISSUE TITLE
Album view: revisit when to show track artists

### ISSUE THREAD

**Issue by bendardenne** [jellyfin/jellyfin-web#1306]
The album view will sometimes show the artist tag for each individual track. However, the logic to choose when to display it feels a bit arbitrary to me and can sometimes lead to weird situations. As far as I can tell, the current logic is that artists are shown when:

- The track has more than 1 artist
- The track has 1 artist, but it does not appear in the list of album artists.

![Screenshot from 2020-05-26 17-35-34](https://user-images.githubusercontent.com/8947051/82920296-6a34ef00-9f77-11ea-9973-040ae8fb9af7.png)

In a scenario like this, it's impossible to know which of the two artists performed tracks 1, 2 and 5. At the same time we get no useful information about track 3 and 4 since that's the same information as the album artist already shown above.

I would like to suggest the following: if, for each track of the album, the artist set is the same as the album artist set, don't show the artists. This is the most common scenario for typical music albums.
Any other time, show the artists for all tracks (as it's weird to show artists for some tracks but not all). Personally I'm in favour of this.

![Screenshot from 2020-05-26 17-45-36](https://user-images.githubusercontent.com/8947051/82921510-c0566200-9f78-11ea-8160-17ffb9b27977.png)

Alternatively:  if the artist set of a given track is the same as the artist set of the album, don't show artist for this track. Show it for any other track. This would probably be the most sensible for albums where most tracks are by one artist and there is one or two with a guest that doesn't appear in the AlbumArtist tag, and you don't want to show the artist for the majority of tracks.

![Screenshot from 2020-05-26 17-52-16](https://user-images.githubusercontent.com/8947051/82922315-be40d300-9f79-11ea-8203-13ed5d516508.png)

**Comment by dkanada** [comment]
Another option is exposing a display preference somewhere in the user settings.

**Comment by MrTimscampi** [comment]
Please redirect feature requests and suggestions to https://features.jellyfin.org/

If you are willing to work on this and want to discuss the specifics before opening a PR, please create a new issue using the "Technical Discussion" template.
