### ISSUE TITLE
Opening the context menu of the "nowplaying.html" bar causes it to be opened two times

### ISSUE THREAD

**Issue by KristupasSavickas** [jellyfin/jellyfin-web#1312]
**Describe the bug**
Opening the context menu of the "nowplaying.html" bar causes it to be opened two times and throws an uncaught error upon closing.

**To Reproduce**

1. Start playing a song (might be true for other media types as well)
2. Click on the three dots in the corner
3. Click outside the context menu to close it

**Expected behavior**
The context menu dissapears

**Logs**
```
index.html#!/music.html?topParentId=7e64e319657a9516ec78490da03edccb:1 Uncaught (in promise) undefined
Promise.then (async)
show @ itemContextMenu.js?v=10.6.0:1
(anonymous) @ nowPlayingBar.js?v=10.6.0:1
2
```

**Screenshots**
![recording-2020-05-27_11 25 07](https://user-images.githubusercontent.com/1362643/82996524-c1859e80-a00d-11ea-8355-2c67164ea6ff.gif)

**System (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chromium
 - Jellyfin Version: `jellyfin-nightly 20200527`

**Comment by ferferga** [comment]
@KristupasSavickas I think I was able to reproduce. Including this in a PR with some last-hour improvements to the player.
