### ISSUE TITLE
Play queue not accessible from mini player bar

### ISSUE THREAD

**Issue by KristupasSavickas** [jellyfin/jellyfin-web#1313]
**Describe the bug**
The playback queue is not accessible from the "nowplaying.html" bar, you have to open the full page which is bad UX.

**Screenshots**
![recording-2020-05-27_12 38 16](https://user-images.githubusercontent.com/1362643/83003733-6658a980-a017-11ea-8925-e80f0c663f46.gif)

**System (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chromium
 - Jellyfin Version: `jellyfin-nightly 20200527`

**Additional context**

**Comment by ferferga** [comment]
@KristupasSavickas Any reference to any service/app that does this like you mention? The only one I know is Play Music and it's because it doesn't have a full screen player like other services/apps

Also, I'm not sure how to make this with a pleasant looking. 

Maybe we have different concepts of what a miniplayer is, but I understand mini player (not in Jellyfin, but also in Spotify and other services as well) as a little "shortcut" to all the quick things you would normally use while playback without stopping you from your normal use of the website and discoverability (specially important in those services for better monetization, doesn't really apply here but still). Rearranging your playlist it's not that thing imo. At last, I'm open at adding something like **Next Up** for showing what's coming next, something that's also not implemented anywhere but I see far more fitting and useful here.

**Comment by KristupasSavickas** [comment]
#1430 improved this somewhat by expanding playlist items by default when entering the "now playing".

For reference here's what opening the jellyfin "now playing" window looks like (ignore the red background, it's a bug reported in a separate issue):
![jellyfin](https://user-images.githubusercontent.com/1362643/86448277-350e8000-bd1f-11ea-815f-c857af8a268b.gif)

I was a Google Play Music user before I hosted my own media and I really liked its playlist view. Here's what the experience is like:
![gpm](https://user-images.githubusercontent.com/1362643/86447591-41460d80-bd1e-11ea-8292-538412dd8a3c.gif)

(couldn't show an example with a populated playlist since GPM seems to be dying)

The main thing I like is that you don't have to navigate to a separate page - you open a small dialog (?) and the rest of the view is unobstructed. Also, it takes up a small amount of space, which is the right choice IMO. A typical playlist entry shouldn't take up a lot of horizontal space - there could be a small album cover (if available), song title (truncated if it's longer than X symbols) artist and album, both of which can live on the separate line. Most clients waste too much space with jellyfin being the worst offender.

Youtube Music is somewhat similar to this, but they do show the video, so the full screen space is taken:
![youtube-music](https://user-images.githubusercontent.com/1362643/86448642-b534e580-bd1f-11ea-873c-5dd7760ff31b.gif)
It's still better than jellyfin as it feels like opening a "temporary overlay" rather that navigating to a separate page and leaving everything behind. Also, decent usage of screen space.

Spotify is the most similar to jellyfin in this regard:
![spotify](https://user-images.githubusercontent.com/1362643/86448864-0d6be780-bd20-11ea-84ef-8fa198c195a7.gif)

I do like that they don't replace the bottom bar itself, only expand the playlist.

The current implementation of the "now playing" window on jellyfin is fine for mobile - it places the cover art in the center, like most native players do, and the songs in the playlist are instantly visible when scrolling, but for desktop it seems completely unsuitable.

Here are some of the things I don't like about Jellyfin which I did not discuss above:
1. There doesn't seem to be a dedicated button to open the playlist view - you have to click on the bar itself, which seems arbitrary and very non intuitive.
2. The entire playlist area is clickable - clicking anywhere in the vertical line of a song starts playing it. I'd limit it only to to a single place - the cover art (maybe on hovering it a triangle "play" symbol could appear to indicate what's going to happen upon clicking), like it's done elsewhere:
![jellyfin-play](https://user-images.githubusercontent.com/1362643/86450738-aa2f8480-bd22-11ea-8791-73d3428fba08.gif)

Youtube Music does this pretty well (I also like being able to drag and drop songs to reorder them):
![youtube-music-item](https://user-images.githubusercontent.com/1362643/86451191-380b6f80-bd23-11ea-92fd-7590474f14df.gif)

Also, adding clickable artist names and album titles to navigate to them becomes a possibility option (the song title could be clickable as well, to jump to that song). Spotify example:
![spotify-item](https://user-images.githubusercontent.com/1362643/86450915-e367f480-bd22-11ea-98e9-17b1aecfb970.gif)


Another thing that annoys me, is that the entire playlist area is clickable. I suggest 

I have the following suggestions, how to improve the **desktop** inferface:
1. (best, hardest to implement) Remove the "now playing" window, add a small dialog to show playlist items like it's done in Google Play Music.
2. Remove separate media controls in the "now playing" window - keep the controls at the bottom, only show playlist items in the expanded view, like it's done on Spotify.

**Comment by ferferga** [comment]
@KristupasSavickas You can also drag and drop items in Jellyfin playlists.

I agree with you that the desktop layout needs a rework. But we didn't had time for 10.6, maybe for 10.7. I'm probably going to mimick the YouTube Music UI.

I also used a lot GPM and I sincerely didn't like their playlist UI. Most of the times the playlist window ended up being closed itself when interacting with it and, although it had its advantages, I don't see a reason to keep it in both places - either on miniplayer or in remotecontrol. I know we have shuffle and repeat on miniplayer but they are quick shortcuts for quick actions and I don't think playlist management it's one of those things. Perhaps this is part of the reason why they deprecate their GPM UI in YTM in favor of a full-screen UI. Of course this is all part of discussion and if enough people has valid reasons to agree that we need that, I might try to implement it. But imo this will make miniplayer overwhelmed.

1. Not sure what do you mean about this

2. This is exactly how Spotify works

**Comment by hamburglar2160** [comment]
I think the minibar in its current state [on desktop] can handle more.  A queue button with a GPM-like overlay for when one doesn't want to open the full player isn't unreasonable. 

[Deezer's, added in UX/UI references](https://github.com/jellyfin/jellyfin-web/issues/1148#issuecomment-656059990), uses a full screen overlay which I'm not a huge fan of. The queue button isn't half bad though. A lyrics button, someday. The "next track" tooltip includes the next track on the playlist. The volume button could be reined in a bit, too.

**Comment by MrTimscampi** [comment]
Please redirect feature requests and suggestions to https://features.jellyfin.org/
