### ISSUE TITLE
Ungrouping Versions performs incomplete Split

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-web#1314]
I merged Episode 3 and Episode 4 and it behaves as properly. Episode 4 disappears and Episode 3 has 2 versions.

If you unmerge the versions, Episode 3 looks normal, however, Episode 4 reappears and has two versions. Inspecting it, it's Ep.3 and Ep.4 again.

![image](https://user-images.githubusercontent.com/20715731/83018593-955d2400-9ff3-11ea-8f4c-112f00aeb212.png)

**Comment by MrTimscampi** [comment]
That's most likely a server-side issue.

**Comment by Artiume** [comment]
Yeah, probably. I don't think it occurred in 10.5.5, need to test and verify the regression

**Comment by Artiume** [comment]
This is definitely a regression, 10.5.5 behaves as expected.

**Comment by Artiume** [comment]
Collections issue, ha. I should update my nightly
