### ISSUE TITLE
Page jumps when entering custom css

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-web#1318]
**Describe the bug**
Selecting the custom css field causes the page to jump to an earlier position of the page. 

**To Reproduce**
1. Go to the General page in the Admin Dashboard 2. Scroll down to the custom css field
3. Click the custom css field
4. Observe the page jump to an earlier position

**Expected behavior**
The page should not jump when entering the text field. 

**Logs**
N/A

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: Ubuntu 
 - Browser: Firefox
 - Jellyfin Version: Nightly

**Additional context**

**Comment by Influence365** [comment]
resolved in jellyfin/jellyfin-web#1327

**Comment by krozic** [comment]
I am running version 10.8.10 and this but seems to have returned. It happens on both the "Dashboard" section as well as the current user's "Settings" section. The bug is present in both chrome and edge web browsers. Is this an issue for others?
