### ISSUE TITLE
Add support for ButterChurn visualizer

### ISSUE THREAD

**Issue by LogicalPhallacy** [jellyfin/jellyfin-web#132]
When playing music it would be cool to have a toggle-able visualizer. Milkdrop is objectively the best visualizer ever made, and a web port exists for it. We should add support (with a toggle) for https://github.com/jberg/butterchurn

**Comment by sparky8251** [comment]
As mentioned, this is likely non-trivial to add. The current web project isn't well structured and it is non-trivial to add existing dependencies to existing project files.

I'm more or less of the mind that "minor" UX enhancements and bug fixes are all we will do for `jellyfin-web` so the new `jellyfin-webng` isn't trying to catch up to a moving target.
