### ISSUE TITLE
Top header search button not in TV layout

### ISSUE THREAD

**Issue by Nazar78** [jellyfin/jellyfin-web#1324]
https://github.com/jellyfin/jellyfin-web/blob/c60011010e579915a5c5a99ee2f2c2325d0e51a4/src/assets/css/librarybrowser.css#L240

Hi, can I know why is the top header search button not supposed to be visible in the TV layout where else it's enabled for all other views? This would made it's not possible to search the whole library from the TV layout. The search tab button seems only to search the current library.

Think `.layout-tv .headerSearchButton` should be replaced with `.layout-tv .searchTabButton` coincide with the rest of the display which also means the search tab button will be made obsolete not being used anywhere?

Thank you.

**Comment by MrTimscampi** [comment]
Bad stalebot, shoo. Note to self: check this later.

**Comment by dmitrylyzo** [comment]
Fixed by #1653
