### ISSUE TITLE
Bug with multiple "Bind to local network" addresses.

### ISSUE THREAD

**Issue by BaronGreenback** [jellyfin/jellyfin-web#1334]
Came across this bug when fixing something else.

The backend code has a string[] as a holder permitting the web to bind to multiple addresses.

The JSON sent from the web interface doesn't send the LocalNetworkAddresses value as a string array but as one string.

It should parse it as a multi-string array.

Hope this makes sense.

**Comment by dkanada** [comment]
@Bond-009 @crobibero @Ullmie02 do you think we should parse this in the API or get web to handle it correctly?

**Comment by Bond-009** [comment]
I think web should handle it

**Comment by dkanada** [comment]
cc @ferferga @MrTimscampi this seems like a good candidate to fix before release. Should we implement some kind of list element or just convert with comma delimiters?

**Comment by ferferga** [comment]
@dkanada Maybe something like what we have for people would be good?

![Screenshot_20200629_110816_org.jellyfin.mobile~2.jpg](https://user-images.githubusercontent.com/10274099/86003393-fe302580-ba11-11ea-9473-538f3153d984.jpg)

**Comment by MrTimscampi** [comment]
> Should we implement some kind of list element or just convert with comma delimiters?

I think, for now, comma delimiters fits the bill.

We can make it nicer afterwards in 10.7+.

**Comment by BaronGreenback** [comment]
think it errors when you save - as it's a string[] at the server end.

**Comment by ferferga** [comment]
@BaronGreenback what's the state of this?

**Comment by BaronGreenback** [comment]
Should be fixed in 10.7

**Comment by BaronGreenback** [comment]
will check

**Comment by BaronGreenback** [comment]
Fixed in the latest web.
