### ISSUE TITLE
Non-US languages fail to properly fallback to en_US translation when they should

### ISSUE THREAD

**Issue by Matt07211** [jellyfin/jellyfin-web#134]
In my testing, EN_GB fails to fallback to EN_US correctly, instead it shows the labels only.

This is less prominent in other languages as they have more translated strings, but the problem is still there all the same

**Comment by RazeLighter777** [comment]
Have you made sure this isn’t a caching error?

**Comment by joshuaboniface** [comment]
Confirmed the issue on rc1 release. Definitely a bug and not cache-related.

**Comment by JustAMan** [comment]
@RazeLighter777 check my PR #135 with the fix
