### ISSUE TITLE
[10.6] desktop music player context menu behavior

### ISSUE THREAD

**Issue by hamburglar2160** [jellyfin/jellyfin-web#1343]
With #1056 and #1195 bringing the web player UI forward, there are two things that can be tightened up for usability as 10.6 comes to a feature freeze.

1. When clicked, the three dotted menu opens a view for "view artist" and "view album" which one can already access clicking the hyperlinked metadata above it. However, after moving to the second track on the queue, this button opens up the context menu as well. For each additional song played on the queue, the context menu will open up an extra time.
Preferred (but not designed for the first iteration of the revamped player) behavior would be to do away, at least on web, with this "view artist/album" menu button and instead invoke the context menu once when on mobile. 

~~2. By default, the queue is hidden. To show it, one must press the erroneously named "playlist" button. When the next song begins, the queue returns to its default hidden state. 
Preferred behavior: Remove 'playlist' button and make the queue persistent.~~ moved to a separate issue

**Comment by ferferga** [comment]
This is known, but had no time to fix it (hopefully I will before 10.6, otherwise 10.6.1). I'll assign it to me so I remember about the menu issue. The playlist one is a different one (you should only make one ticket per issue).

**Comment by MrTimscampi** [comment]
My 2 cents:

1. We should deprecate the tap on metadata and keep the menu links on mobile. It's generally harder to tap on a small-ish part of the screen than it is to access a menu when using touch.

2. Should be a setting, imo.

**Comment by hamburglar2160** [comment]
1. I agree that it's more difficult to tap a relatively smaller part of the screen but even then I do not find it to be a labor. the existing context menu is solid enough-of course it needs to be tweaked, but the new (incomplete) menu isn't the answer. I _really_ appreciate being able to tap the hyperlinked text on both web and mobile as I prefer not to use these menus when I don't have to. There aren't any accidental button presses happening here that would warrant removing the hyperlinks, in my experience. A toggle? I'm totally with you as it relates to hyperlinked metadata in the minibar on the bottom--that's a problem. 

2. (assuming you're referencing my original point #2) On desktop a setting seems unnecessary. 4/5 of the screen is blank space with the queue gone! For reference, the queue is persistent on 10.5.5

**Comment by ferferga** [comment]
@MrTimscampi I think what you mean was already fixed by @samuel9554 and me in #1056

**Comment by hamburglar2160** [comment]
#1430
