### ISSUE TITLE
[10.6] nowplaying.html for TV shows and movies does not have hyperlinked item details

### ISSUE THREAD

**Issue by hamburglar2160** [jellyfin/jellyfin-web#1349]
On current 10.6 master with the revamped nowplaying UI, item details for currently playing music and movies (whether casted or not) are clickable and will lead to their respective item detail pages, as introduced in 10.5 for various items detail screens. This same behavior has not been brought to TV shows **edit: and movies.**

Preferred behavior: hyperlink "Episode Name" to the corresponding episode details screen and "Series name" to series details. Further, introduce the hyperlinked "Season # - Episode #" preceding "Episode" so that it reads:
"Season 4, Episode 2
Thirty-Eight Snub
Breaking Bad"

**Comment by ferferga** [comment]
@hamburglar2160 Can we close this now that #1430 is merged?

**Comment by hamburglar2160** [comment]
FWIW for remotecontrol (while casting) the album is clickable but not the artist for music. For movies and TV content, nothing is. Season # and Episode # also aren't displayed. Regardless--closed.

**Comment by ferferga** [comment]
@hamburglar2160 That's one thing I will remember. There is an API inconsistency between Chromecast and remote players and the one that I'm using locally. I'll try to solve them in a Chromecast update.

**Comment by hamburglar2160** [comment]
I'm also experiencing that, though I can click the album (as noted above), the screen goes lank and that album details screen never loads. I'm stuck with the spinner. While casting.

**Comment by hamburglar2160** [comment]
Also on remotecontrol: fastforwarding 30 seconds *sometimes* goes forward 30 seconds but usually goes to next song instead. Works as intended on non-casting nowplaying.html as we know.
