### ISSUE TITLE
Bad formating for long titles

### ISSUE THREAD

**Issue by sxales** [jellyfin/jellyfin-web#1385]
**Describe the bug**
Long titles don't word wrap and will shove button to the right (often off screen). 

**Screenshots**
![Screenshot_2020-06-08 Jellyfin](https://user-images.githubusercontent.com/29420152/84074222-d52eee80-a997-11ea-9deb-e610d820ee99.png)
![Screenshot_2020-06-08 Jellyfin](https://user-images.githubusercontent.com/29420152/84074238-deb85680-a997-11ea-94e7-18a2704aaebb.jpg)
![Screenshot_2020-06-08 Jellyfin(2)](https://user-images.githubusercontent.com/29420152/84074285-f394ea00-a997-11ea-931b-499f225df1c9.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 77.0.1
 - Jellyfin Version: 10.5.5

**Comment by Influence365** [comment]
Similarly, when on ipad:

![2020-06-08-Longname Styling bug](https://user-images.githubusercontent.com/18101008/84077222-e5ae8b80-a9ce-11ea-8ad8-881d4cb7effc.png)

![2020-06-08-Longname Styling bug 2](https://user-images.githubusercontent.com/18101008/84077433-38884300-a9cf-11ea-8d0a-57debebb2a3f.png)

**Comment by Artiume** [comment]
https://github.com/jellyfin/jellyfin-web/pull/1206 this PR updates a lot of these issues if you want to look it over.

**Comment by Influence365** [comment]
When using an iPad Pro through on google chrome the following still persists:

![IMG_0132](https://user-images.githubusercontent.com/18101008/84137102-1977c880-aa44-11ea-888f-59d4ee5b39c1.PNG)

It is fixed in safari. But still present in chrome. (using #1206 )
