### ISSUE TITLE
[suggestion] Header cleanup

### ISSUE THREAD

**Issue by hamburglar2160** [jellyfin/jellyfin-web#1390]
The header tab is messy and would benefit from a bit of streamlining and consistency.

The suggestions tab in the music and movie libraries include "Latest..." so shouldn't the TV library as well? Currently, the TV library's suggestions tab includes only "continue watching" and "next up.," while the "latest" header tab remains separate. These two things can be combined. #1499 

Collections span across all of the media libraries. You can add playlists, music albums and songs, and TV shows to them. They should therefore be accessible across all of Jellyfin, not just in the header tab for movies. Collections are easily accessible in the hamburger menu when an unrelated user setting is enabled.
![image](https://user-images.githubusercontent.com/61879508/84167397-298fa800-aa44-11ea-8f2a-5ca5d91e81e3.png)
As long as one collection exists, the collections view should remain (persistently) accessible from the hamburger menu--independent of this user setting. Collections can then be dropped from the rather busy movies header tab.

Similarly, playlists span across both video and music libraries. They're only accessible, however, in the music header tab, or in the hamburger menu when any playlist exists which contains a single video item.
As long as one playlist exists, the playlist view should remain persistent in the hamburger menu regardless of whether or not a playlist contains a video item. The question arises of whether or not it's worth removing playlists from the header--I'd argue a hard 'maybe.'

Trailers doesn't do anything and there seems to be very little interest in making it do anything. #1199

Current:
![image](https://user-images.githubusercontent.com/61879508/84164427-812c1480-aa40-11ea-8911-5e208e5714de.png)
![image](https://user-images.githubusercontent.com/61879508/84164777-eda71380-aa40-11ea-887e-55ec518c86c8.png)
![image](https://user-images.githubusercontent.com/61879508/84165210-6efea600-aa41-11ea-99d6-51f106de0ea3.png)

After:
![image](https://user-images.githubusercontent.com/61879508/84164697-d831e980-aa40-11ea-8135-d01518219502.png)
![image](https://user-images.githubusercontent.com/61879508/84164981-23e49300-aa41-11ea-8bea-a7b70b805d6e.png)
![image](https://user-images.githubusercontent.com/61879508/84165296-889fed80-aa41-11ea-8f70-6c612fc2350d.png)

Finally, favorites. Anything can be favorited, yet they're only given their own tab in the movie headers and on 'home.' Instead of leaving there, perhaps move them to one of two places:
1. Into the Hamburger menu
2. Under the user profile image on the top right corner where one currently accesses per-user settings.
HBO and iirc a few other major platforms do this under the name of 'My List' and combine this with per-user settings and 'continue watching'. Down the road, renaming favorites closer to 'my list/queue' would be more suitable to the purpose it serves. 

<details>
<summary>
Here's a reference for that HBO thing:
</summary>

![image](https://user-images.githubusercontent.com/61879508/84173282-12a08400-aa4b-11ea-9151-13e0ca17f505.png)

</details>

Moving favorites out of the movies header tab would bring parity with other libraries. Moving the favorites header tab from 'home' would have even a greater effect--the tba can be done away with completely. This would go a long way on mobile, as well, because 10-20% of the vertical would be freed up.
Before:
![image](https://user-images.githubusercontent.com/61879508/84169643-d9661500-aa46-11ea-80ad-89b0a1d2cb40.png)
After:
![image](https://user-images.githubusercontent.com/61879508/84169746-fbf82e00-aa46-11ea-99c5-1e942756471e.png)

Something to think about.

**Comment by hamburglar2160** [comment]
<details>
<summary>
Here's a reference for that HBO thing:
</summary>
![image](https://user-images.githubusercontent.com/61879508/84173203-f3a1f200-aa4a-11ea-9448-4085e5cfaeee.png)
</details>

**Comment by DMouse10462** [comment]
I have mixed feelings about these suggestions from a user experience perspective, particularly when it comes to feature discovery. Some of these suggestions, however, are completely warranted with some expansion. I split up this comment because it got long and it's probably best that the issues are quoted separately.

### Trailers (Heading) - _Remove_

**Note**: This is _not_ how I feel about the YouTube trailers on the Item Details screen; those are a nice implementation and should be kept, even though it goes against the "external" argument I make below.

This is my main point of agreement. As Jellyfin is more of a library for the things you have already, the feature is inherently unnecessary. The main argument is the old "Trailers" plugin you mentioned that hasn't seen much development effort. 

I do think that such a plugin could be a nice addition, but it belongs in My Media as a Channel (a term I recall from Emby; I'm not sure if we still use that or implement it) since the plugin acts as a provider of media from an external source.

**Comment by DMouse10462** [comment]
### Latest (Heading) - _Move_

I agree that Latest belongs somewhere else, and Suggestions may very well end up being _that_ place, but the Suggestions certainly would need reworking and thus the move becomes part of a separate issue/PR. This is certainly up for discussion as to how to move forward (all of these are, but this specifically needs details worked out).

**Comment by DMouse10462** [comment]
### Favorites (Movie Heading) - _Move / Make Filter Shortcut_

I like the suggestion of bringing in a "My List"-like menu option (probably in Hamburger is best the way things are now) that takes you to a global Favorites list, but there should definitely be other, easy-access entry points. There is currently a "Favorites" filter under the "Filter" category in the Filter menu (is there a better name for that category?). This could be brought out as a heart icon beside the Filter menu to provide a replacement for the heading that (a) saves screen real estate and (b) could be added across all media types. 

This sounds like unnecessary duplication at first glance, but such an important feature should have entry points that match the user's expectations and don't completely break/complicate the workflow of a user who is accustomed to that header. I didn't even know there was a filter in the list for favorite items, so having a dedicated icon for it would be a great way to improve feature discovery.

On the topic of feature discovery, this is a great example of it. Maybe I'm wanting to see all of my favorites; an entry point from the Home page is a great way to access it. Maybe I'm looking for a movie that I love and I'm already in the Movies library; I don't want to have to specify that I'm looking for a movie when I'm already here, so a filter would be better than the general Favorites link here. Duplicate entry points aren't inherently bad.

**Comment by DMouse10462** [comment]
### Collections and Playlists - _It's Complicated_

I see the purpose of both of these and I certainly believe that they should be first-class implementations and discoverable as useful features, but I do agree that the entry points for these are a bit complicated.

If the hamburger menu were persistent on displays that support it, I would suggest adding these to the hamburger menu as sub-items of the libraries themselves (which would expand upon entry). Making the hamburger menu a visible-by-default sidebar instead would also prompt other suggestions about the current state of the menu on desktop, but that's another topic. 

Without this change though, placing these options anywhere other than the header would hinder feature discovery and frustrate users looking for the options after an update.

**Comment by MrTimscampi** [comment]
> If the hamburger menu were persistent on displays that support it

This is slated for 10.7 (See #1245).
