### ISSUE TITLE
"Enable theme videos" option in user "Display settings" always is enabled

### ISSUE THREAD

**Issue by WWWesten** [jellyfin/jellyfin-web#140]
"Enable theme videos" option in user "Display settings" always is enabled

**Steps to reproduce:**

1. Go to user's Settings page
2. Choose Display
3. Remove mark at Enable theme videos
4. Return to previous page
5. To repeat steps 1 & 2

**What happens?**
Enable theme videos option is marked again

**What should happen?**
Mark at Enable theme videos option should removed

**Comment by dkanada** [comment]
I fixed this bug a while ago in a pull request, but I can't find the specific one. You can disable the feature now from that page.
