### ISSUE TITLE
Make sure a browser can actually play a file, rather then relying on what the browser says

### ISSUE THREAD

**Issue by EmeraldSnorlax** [jellyfin/jellyfin-web#1419]
**Describe the bug**

I have some flac files (copyrighted, unfortunately, so it can't be attached) that Firefox and Chromium has issues playing. (Chrome is fine, Android client is fine)
These flacs look like they have ID3v2 tags, which seems to be the cause of the issues so, although they can be direct played, it fails.

Although it's my files' fault, client should retry with a transcoded version if one of the profiles fail with a fallback one when re-encoding is enabled on my profile.

Playing through Gelli and force encoding to AAC 320k plays fine, so no issues with transcoding server-side (here are the transcode logs https://pastebin.com/pTrA8cSM for this)

**To Reproduce**

1. Have a flac that contains ID3v2 tags
2. Play the file
![imagen](https://user-images.githubusercontent.com/10274099/84804814-96d2a880-b003-11ea-918c-20d51b5c447c.png)

**Expected behavior**

Either have the file play, or re-encode to a format the browser supports.
**Logs**
Client: https://pastebin.com/60x7J6WR
Transcode to AAC on mobile (Gelli): https://pastebin.com/pTrA8cSM 

**System**
 - OS: Server is Ubuntu 20.04, client is Arch Linux (Kernel 5.7.2)
 - Browser: Firefox 77 and Chromium 83
 - Jellyfin Version: 10.5.5

**Comment by ferferga** [comment]
Just chiming here because I like to link Matrix conversations in issues as well as many times are really useful for future reference.

All of this start here: https://matrix.to/#/!YjAUNWwLVbCthyFrkz:bonifacelabs.ca/$A5OJ7BKhazBZbj0MgxZuqNPgclViIB_qOUvTpXjTCWs?via=matrix.org&via=feneas.org&via=bonifacelabs.ca

**Comment by bingzhangdai** [comment]
Is this issue resolved? I notice that it is auto closed not because of PR merged. You can mark it as won't fix and close it, but auto closing issue is not a good idea, especially when it is added to the release plan.

**Comment by thornbill** [comment]
We maintain a ton of browser specific overrides in the device profile for cases where the browser does not correctly report its support. The issue mentioned here with Firefox not supporting flac files with invalid tags we do not have any way of specifying in the profile though.
