### ISSUE TITLE
Filter for 4K Movies isn´t working anymore

### ISSUE THREAD

**Issue by FallenLeave91** [jellyfin/jellyfin-web#1426]
**Describe the bug**
I noticed that the filter for 4K Movies isn´t working anymore. SD and HD Filters work just fine. It has been working a few weeks ago. 

**To Reproduce**

1. Movies
2. Filter Icon
3. Type
4. 4K

**Expected behavior**

**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: [Docker]
 - Browser: [Chrome]
 - Jellyfin Version: [10.5.5]

**Additional context**

**Comment by Artiume** [comment]
What was the last working version? and is it fixed in nightly?

**Comment by Influence365** [comment]
From what I can tell, this is working in the nightly and in 10.5.5.
Do you have any logs to share?

**Comment by FallenLeave91** [comment]
I can´t find anythink related in the logs. Somehow it just displays everythink if i select the 4k filter. If i e.g. try the 3D filter it displays nothing (as i dont have any 3d content). The SD and HD Filter work just fine as well.

**Comment by MrTimscampi** [comment]
I don't seem to be able to reproduce this, the filter is working fine here.

**Comment by FallenLeave91** [comment]
So if i select Watched or Unwatched + the 4K Filter it works. Just 4K Filter doesn´t work for me.

**Comment by FallenLeave91** [comment]
Update: After the upgrade to the latest Version i had some Issues which lead me to start from zero. Now the 4K FIlter is working again 👍
