### ISSUE TITLE
Metadata is not converted to HTML Entities

### ISSUE THREAD

**Issue by joytrekker** [jellyfin/jellyfin-web#1428]
Using Jellyfin version 10.5.5

I have a music album (Reanimation by Linkin Park) that contains many song titles with special characters. When viewing the album with jellyfin-web the page layout breaks due to an open bracket `<` in track 15 called `My<Dsmbr` 

Here is the result of the open bracket. The last tracks are forced to the same line.
![Jellyfin](https://user-images.githubusercontent.com/5538589/84965072-bed51100-b0c2-11ea-955d-4346f4db6d81.png)

and the HTML with a broken element named `dsmbr`
![jellyfin1](https://user-images.githubusercontent.com/5538589/84964991-8c2b1880-b0c2-11ea-8c97-0121773c52ab.png)

Jellyfin-web should convert media titles to HTML entities so that random characters in metadata will not break the layout. This should also apply to all metadata.

**Comment by Raul824** [comment]
I had the exact same issue 
Edit the song My<Dsmbr and remove "<" from the name everything will work believe me.
dsmbr is the Song name and < is asking your web browser to use dsmbr in html tag.

**Comment by joytrekker** [comment]
This bug should be open since the issue stil occures in the current version 10.6.4
Some additional info. I also have the artist K/DA in my collection. However jellyfin is seperating the artist into two. Artist K and DA.
