### ISSUE TITLE
Don't display check mark on watched series on the TV Shows page

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin-web#143]
Every series poster has a blue circle with either the number of unwatched episodes or a check mark meaning all episodes are watched. It is hard to scan and just find watched or unwatched series.

Don't display a check mark if the series is watched, display nothing. This could be made configurable as an option if others like the check mark.

**Comment by SenorSmartyPants** [comment]
I'd still like this considered.

**Comment by ckcr4lyf** [comment]
I am able to remove them, but not sure how to go about having a custom user setting or w/ever.

Shall I open a pull request with just removal?

**Comment by ckcr4lyf** [comment]
Got it, makes sense.

Today is my first day with the repo, so still trying to make some sense of the workings and how different functionality is linked together.

I'll try and work on this issue, if I come across something I'll let you guys know.

Thanks.

Also yes, custom css is a good idea, OP should definitely consider that if it's a big deal.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DMouse10462** [comment]
There are strong ties between this and #706. Both issues are working to achieve the same goal; we'd like to better distinguish between unwatched, partially watched, and watched TV series at a glance when browsing the library.

**Comment by MrTimscampi** [comment]
Please redirect feature requests and suggestions to https://features.jellyfin.org/
