### ISSUE TITLE
10.6.0 logout/login i have to select again my server

### ISSUE THREAD

**Issue by lelamamalgache** [jellyfin/jellyfin-web#1433]
**Describe the bug**
i think end users have only one jellyfinserver, when i logout and login, i have to select my server, then connect, then login

**Expected behavior**
when you logout, the jellyserver should be automaticly selected, to show only user selection to login
and add a bouton, change server, if end users have two jellyfinserver or more

**System (please complete the following information):**
 - OS: docker
 - Browser: chrome
 - Jellyfin Version: 10.6.0

**Comment by dmitrylyzo** [comment]
This is due to `standalone` build.

**Comment by lelamamalgache** [comment]
hello @dmitrylyzo 

thank for your answer, but i don't understand

the standalone build is only for 10.6.0 ?
which build should i use to fix it ?

**Comment by MrTimscampi** [comment]
> which build should i use to fix it ?

It will be fixed once #1401 is merged :)

**Comment by Raul824** [comment]
i'd like to point out one more thing when i open up private_ip:8096 it takes to jellyfin page with add server option but then when i put private_ip:8096 it says cannot connect to server make sure jellyfin is running. 
It seems it isn't resolving ":" correctly as i tried with public_ip:443 not working then with the reverse proxy url created with caddy for port 443 and its working.

**Comment by dmitrylyzo** [comment]
@Raul824 If you are talking about that you have to enter server address twice (browser + selectserver), then this is also due to `standalone`.
Second, you have to enter protocol `http`  for IP until [this](https://github.com/jellyfin/jellyfin-apiclient-javascript/pull/53) is merged.

**Comment by Raul824** [comment]
@dmitrylyzo Nope i am saying opening private_ip:8096 takes you to the page but upon entering private_ip:8096(without http) in the add server it gives error. And the workaround is adding http://private_ip:8096.
So if the fix isn't needed maybe the host connection example provided should be changed to add http:// in the front of example ip address provided.

![image](https://user-images.githubusercontent.com/51978647/85196104-2c7b7a00-b31b-11ea-81eb-c96cb4d1cbd2.png)

**Comment by dmitrylyzo** [comment]
`http` was previously assumed, now it is `https` - that broke protocol-less IP address.
I think most users are used to not specifying a protocol.
With PR I mentioned, it will try `https` then `http` if no protocol is specified - just like browser does.

_One-button dialogs are terrible_ :man_facepalming:

**Comment by Raul824** [comment]
I think you should not waste time in these you guys are already doing great work. We can put this as FYI or change the example that's it lets users also do something 👍

**Comment by MrTimscampi** [comment]
> _One-button dialogs are terrible_ man_facepalming

Agreed, these need another pass x)

**Comment by dkanada** [comment]
They're fixed for now in my repository pull request.
