### ISSUE TITLE
10.6.0 active devices, pause stop send message missing

### ISSUE THREAD

**Issue by lelamamalgache** [jellyfin/jellyfin-web#1438]
![image](https://user-images.githubusercontent.com/58141187/85059023-4003d500-b1a3-11ea-9ddb-b27d01a4576b.png)

**Expected behavior**
show pause, stop, send message to an android device

**System (please complete the following information):**
 - OS: docker
 - Browser: chrome
 - Jellyfin 10.6.0

**Comment by MrTimscampi** [comment]
This is entirely controlled by the info we get from the client (See here: https://github.com/jellyfin/jellyfin-web/blob/master/src/controllers/dashboard/dashboard.js#L293)

It seems like Android should send us the required info though (It even reports supporting remote control: https://github.com/jellyfin/jellyfin-android/blob/b4615b0bed602547eaef7dd5dbf0e787089dbb50/src/NativeShell/www/apphost.js#L6-L20)

@thornbill Any insight on this from the Android side of things?

**Comment by lelamamalgache** [comment]
it is the same for jellyfin web with google chrome
![image](https://user-images.githubusercontent.com/58141187/85201181-984eea00-b2fd-11ea-9e3b-a5f45c3bb630.png)

**Comment by ferferga** [comment]
Seems that we unintentionally changed something the API that it's causing this. [In this line](https://github.com/jellyfin/jellyfin-web/blob/master/src/controllers/dashboard/dashboard.js#L540), ``ServerId`` in ``session`` object doesn't exist. 

[Link to relevant Matrix discussion](https://matrix.to/#/!WXGcrduLZmrIdSyCrv:bonifacelabs.ca/$IeZw9HjeMhyWjv2aLrvGAa2iSfc_vObdIuwNxAE1_2g?via=bonifacelabs.ca&via=matrix.org&via=matrix.possumlodge.me)

cc @MrTimscampi
