### ISSUE TITLE
Known Issue: v1.0.1 Media Notification Seekbar is broken

### ISSUE THREAD

**Issue by hamburglar2160** [jellyfin/jellyfin-web#1455]
The seekbar found in the expanded media notification for recent versions of Android is not hooked up to the app, so it doesn't do anything.

**Comment by hamburglar2160** [comment]
Related reading on the Android side: https://developer.android.com/preview/features/media-controls

**Comment by MrTimscampi** [comment]
If someone is interested in tackling this, here's some docs: https://developer.mozilla.org/en-US/docs/Web/API/MediaSession/setActionHandler

You need to hook up `seekto` in `mediasession.js` to seekPercent in playbackManager. Make sure to convert the time given by the Media Session API to a percentage, since that's what PlaybackManager expects.

**Comment by KGT1** [comment]
@MrTimscampi would this be ok?
`        /* eslint-disable-next-line compat/compat */
        navigator.mediaSession.setActionHandler('seekto', function (object) {
            let item = playbackManager.getPlayerState(playbackManager.getCurrentPlayer()).NowPlayingItem;
            // Convert to ms
            let duration = parseInt(item.RunTimeTicks ? (item.RunTimeTicks / 10000) : 0);
            let wantedTime = object.seekTime*1000;
            playbackManager.seekPercent(wantedTime/duration*100,currentPlayer);
        });`

**Comment by KGT1** [comment]
@MrTimscampi would something like this be ok?
```javascript
        /* eslint-disable-next-line compat/compat */
        navigator.mediaSession.setActionHandler('seekto', function (object) {
            let item = playbackManager.getPlayerState(playbackManager.getCurrentPlayer()).NowPlayingItem;
            // Convert to ms
            let duration = parseInt(item.RunTimeTicks ? (item.RunTimeTicks / 10000) : 0);
            let wantedTime = object.seekTime*1000;
            playbackManager.seekPercent(wantedTime/duration*100,currentPlayer);
        });
```

**Comment by MrTimscampi** [comment]
> @MrTimscampi would something like this be ok?
> 
> ```js
>         /* eslint-disable-next-line compat/compat */
>         navigator.mediaSession.setActionHandler('seekto', function (object) {
>             let item = playbackManager.getPlayerState(playbackManager.getCurrentPlayer()).NowPlayingItem;
>             // Convert to ms
>             let duration = parseInt(item.RunTimeTicks ? (item.RunTimeTicks / 10000) : 0);
>             let wantedTime = object.seekTime*1000;
>             playbackManager.seekPercent(wantedTime/duration*100,currentPlayer);
>         });
> ```

Looks alright to me at first glance :)

It might trigger a few linting rules if you open, a PR for it, but these are easily fixable.

**Comment by hamburglar2160** [comment]
On the latest 10.6 master, it appears that no notification shows up at all when casting to the Nightly CAF receiver (except of course for the Google Play Services one) though I'm not 100% sure it's linked to this PR.

Button controls do work.

The seekbar, however, is still faulty for a new reason. It's interactable, but when a song is played, the notification seems to start at ~3 minutes, 5 seconds when the song is actually at 0 seconds. This applies to both the Android 8+ (?) media notification and Android 11 beta's new "media resumption" dev flag.
