### ISSUE TITLE
10.6.0 Unable to open remote control dialog after selecting device

### ISSUE THREAD

**Issue by ConfusedPolarBear** [jellyfin/jellyfin-web#1456]
**Describe the bug**
After upgrading to 10.6.0 nightly, the casting button is non-functional after selecting a device to be remotely controlled. To disconnect from the device (or select a new one) a page refresh is required.

**To Reproduce**
1. Launch two instances of jellyfin web.
2. Click the cast icon from the first instance and select the second instance from the menu.
3. Click the cast icon again. No remote control dialog is displayed.

**Expected behavior**
The remote control dialog appears, with options for remote control, display mirroring and to disconnect.

**Logs**
```
RequireJS error: TypeError: playerInfo.supportedCommands is undefined. Failed modules: site.js:1:8034
    onRequireJsError https://example.com/web/scripts/site.js:1
    delayedError https://example.com/web/libraries/alameda.js:986
Uncaught (in promise) TypeError: playerInfo.supportedCommands is undefined
    showActivePlayerMenuInternal https://example.com/web/components/playback/playerSelectionMenu.js?v=20:1
    showActivePlayerMenu https://example.com/web/components/playback/playerSelectionMenu.js?v=20:1
    execCb https://example.com/web/libraries/alameda.js:1233
    defineModule https://example.com/web/libraries/alameda.js:493
    depFinished https://example.com/web/libraries/alameda.js:526
    waitForDep https://example.com/web/libraries/alameda.js:589
playerSelectionMenu.js:1:2909
```

**Screenshots**
n/a

**System (please complete the following information):**
 - OS: Debian 10 (buster)
 - Virtualization: ESXi
 - Browser: Firefox 78.0b9
 - Jellyfin version: Nightly 20200618 installed from the APT repository
 - Reverse proxy: nginx

**Additional context**
I upgraded jellyfin from 10.5.5.

**Comment by MrTimscampi** [comment]
This is linked to #1438

**Comment by ferferga** [comment]
@ConfusedPolarBear Can you try with my branch? #1430 
Make sure you checkout my branch and that both sides are using my version.

I think I fixed this in the last commit (I'm not able to reproduce it)

We just discovered that (although somewhat related because it seems something in API changed) this probably has nothing to do with #1438

**Comment by ConfusedPolarBear** [comment]
@ferferga - Just tested and confirmed that #1430 fixes this.

**Comment by ferferga** [comment]
@ConfusedPolarBear Thank you very much for testing, will link that PR to this issue.
