### ISSUE TITLE
Jellyfin on Opera Store/Vewd on Hisense Tvs

### ISSUE THREAD

**Issue by mrtntome** [jellyfin/jellyfin-web#1482]
Is there any way to get Jellyfin on non android Hisense Tvs?

**Comment by MrTimscampi** [comment]
We're not aware of any contributor with a Hisense TV (or other Vewd TVs).

Should someone work on such a client, we'd be happy to get it to the store, but it's not in the cards until someone with a TV using that steps up to do it.

**Comment by Schtevo66** [comment]
I have non android Hisense TV's (2 actually), you can run Jellyfin in the browser but it's not easy to control with the TV remote.

I recommend getting a FireTV Stick. The Jellyfin app is in Amazon store. 

If you go into settings for the TV and the FireTV Stick and enable CEC the TV remote will control the FireTV Stick when the TV is set to the sticks HDMI port, makes the whole thing really slick.

**Comment by MrTimscampi** [comment]
Please redirect feature requests and suggestions to https://features.jellyfin.org/
