### ISSUE TITLE
dashboard - popup settings saved on General and notifications

### ISSUE THREAD

**Issue by lelamamalgache** [jellyfin/jellyfin-web#1486]
**Describe the bug**
Hello, could you add the popup "settings saved" on general and notifications, when we click on the button saved ?
https://github.com/jellyfin/jellyfin-web/search?q=toast%28globalize.translate%28%27SettingsSaved%27%29%29%3B&unscoped_q=toast%28globalize.translate%28%27SettingsSaved%27%29%29%3B

**To Reproduce**

1. Go to general or notifications
2. modify something and save
3. there is no popup "settings saved"

to see what is this popup, go to you users list and try to rename your user and save it, a popup at the bottom left says "settings saved"

**System (please complete the following information):**
 - Jellyfin Version: 10.6.0

**Comment by hamburglar2160** [comment]
#1359

**Comment by Camc314** [comment]
@lelamamalgache  Can you check if this is still an issue. I think it should be fixed.
