### ISSUE TITLE
10.6.0 dashboard users - last seen text is too long

### ISSUE THREAD

**Issue by lelamamalgache** [jellyfin/jellyfin-web#1490]
**Describe the bug**
From the dashboard then users, the text "last seen" is too long to be shown or the area text is too short

**Screenshots**

![image](https://user-images.githubusercontent.com/58141187/85884684-4fa69d80-b7e3-11ea-9959-4df99ed51f99.png)
![image](https://user-images.githubusercontent.com/58141187/85884735-664cf480-b7e3-11ea-89ef-f684f09c6225.png)

**System (please complete the following information):**
 - Browser: Chrome
 - Jellyfin Version: 10.6.0

**Comment by lelamamalgache** [comment]
10.6.0 chrome french
![image](https://user-images.githubusercontent.com/58141187/88484356-52291e00-cf6e-11ea-97bc-818f7f26b8cf.png)

![image](https://user-images.githubusercontent.com/58141187/88484387-7b49ae80-cf6e-11ea-9544-2788f75a8e0e.png)

**Comment by Shadowghost** [comment]
Check on #1555  - there are not easily fixable technical complications (just as reference sice you commented there too).
