### ISSUE TITLE
Subtitle offset not changing in Firefox 77.0.1 / Jf 10.5.4

### ISSUE THREAD

**Issue by mahriman** [jellyfin/jellyfin-web#1493]
**Describe the bug**
Trying to change the subtitle offset in Firefox (77.0.1 64-bit) does not work, while the same operation works in Chrome (84.0)

**To Reproduce**
1. Play video in Firefox
2. Try to change subtitle offset, value changes visually but subtitle offset is still the same

**Logs**
No warnings or errors in developer console after having set network.websocket.allowInsecureFromHTTPS = true in about:config trying to see if that had anything to do with the problem.

**System (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 77.0.1 64-bit
 - Jellyfin Version: 10.5.4

**Additional context**
* If trying to type in a value by keyboard and pressing enter, the character cursor resets to the beginning of the offset value. Don't know if this is a clue or normal Firefox behavior, but it doesn't behave like that in Chrome at least. 
* Can't say for sure when this started or if it has ever worked in firefox as I'm normally on Chrome and this was reported by another user.

**Comment by dmitrylyzo** [comment]
> If trying to type in a value by keyboard and pressing enter, the character cursor resets to the beginning of the offset value. Don't know if this is a clue or normal Firefox behavior, but it doesn't behave like that in Chrome at least.

I do not see any cursor manipulation, so this is probably Firefox behavior.

> Can't say for sure when this started or if it has ever worked in firefox as I'm normally on Chrome and this was reported by another user.

Looks like that was from the beginning.

**Comment by mahriman** [comment]
> > If trying to type in a value by keyboard and pressing enter, the character cursor resets to the beginning of the offset value. Don't know if this is a clue or normal Firefox behavior, but it doesn't behave like that in Chrome at least.
> I do not see any cursor manipulation, so this is probably Firefox behavior.

Note that I'm talking about the character / input cursor, not the mouse cursor :)
