### ISSUE TITLE
missing thumbnail on album view for mobile screen size

### ISSUE THREAD

**Issue by dkanada** [jellyfin/jellyfin-web#15]
The android client has always been missing a nice thumbnail on `itemdetails` for albums similar to movies and shows. I will look into this once I have audio playback functional again.

**Comment by drago-96** [comment]
You mean something like this?
![immagine](https://user-images.githubusercontent.com/22937313/51043498-1ebab480-15bf-11e9-9f29-f9757bf1acbb.png)

**Comment by dkanada** [comment]
Interesting, this must be a bug only on the android client then, thanks for adding some context. The android client also uses this repository for the UI so I would expect the image to show, but I didn't see any errors at first glance either.

**Comment by drago-96** [comment]
No wait, this isn't the default behaviour, it's my try to fix it! :D
I was just checking if we were talking about the same thing.

Btw, the same fix could be applied to the artist itemdetail page, which to me didn't show the artist picture.

**Comment by dkanada** [comment]
Nice! Definitely apply the fix for the artist detail page if you have time, this issue has bugged me for months!

**Comment by dkanada** [comment]
closed with #20
