### ISSUE TITLE
10.6.0 Edge doesn't load login page

### ISSUE THREAD

**Issue by xkronusx** [jellyfin/jellyfin-web#1505]
**Describe the bug**

Loading jellyfin on Windows Edge browser, Xbox Edge browser and Xbox jellyfin app no longer works.

Page begins to load and fails to populate anything on the screen, no pictures/login.

**To Reproduce**
1. Go to Edge
2. Load URL
3. Nothing populates

**Expected behavior**
Load webpage, page should load like firefox and chrome.

**Screenshots**
![page load example](https://user-images.githubusercontent.com/36311868/86304244-52870100-bbdc-11ea-9c4a-8131e1955384.png)

**System (please complete the following information):**
 - OS: Docker
 - Browser: Edge
 - Jellyfin Version: 10.6.0 Unstable

**Comment by xkronusx** [comment]
Updated to latest unstable image
Docker image: 20200712.1-unstable

Edge loads splash screen and never goes further 

![image](https://user-images.githubusercontent.com/36311868/87241907-9f957f00-c3f5-11ea-9ef8-5cff9d306ffc.png)

**Comment by Influence365** [comment]
Is that the old version of edge or the newer one based on chromium?

**Comment by xkronusx** [comment]
> Is that the old version of edge or the newer one based on chromium?
> 
> What version number is it?

Unfortunately it is the old non chromium version, from my testing the chromium version works fine.

Which means for PC people a quick edge update fixes that problem. But for the Xbox folk they are stuck with the old Edge until microsoft decides to update them. At the same time it also affects the Xbox app currently because it is a browser wrapper from what I can tell.

Edge info as follows

Microsoft Edge 44.18362.449.0
Microsoft EdgeHtml 18.18363

**Comment by MasterCATZ** [comment]
Ubuntu 20.04 
Jellyfin.Server 10.6.4.0

http://localhost:8096/web/index.html

Chrome , Chromium , Slimjet,  Firefox , 
Android Chrome
all do the black screen 


[21:02:55] [INF] [18] Emby.Dlna.Main.DlnaEntryPoint: SsdpCommunicationsServer disposing sendSocket from 127.0.0.1
[21:02:55] [INF] [18] Emby.Dlna.Main.DlnaEntryPoint: SsdpCommunicationsServer disposing sendSocket from 192.168.2.67
[21:02:55] [INF] [18] Emby.Server.Implementations.ApplicationHost: Disposing NotificationEntryPoint
[21:02:55] [INF] [18] Emby.Server.Implementations.ApplicationHost: Disposing EntryPoint

**Comment by MrTimscampi** [comment]
@MasterCATZ This was an issue specific to Edge 18, due to the use of incompatible Javascript.

I suggest you open another issue or come to the troubleshooting Matrix channel to ask for some help (See here: https://jellyfin.org/contact/)
