### ISSUE TITLE
SUBRIP Subtitles Not Always Displaying

### ISSUE THREAD

**Issue by Cmdrd** [jellyfin/jellyfin-web#1517]
**Describe the bug**
Most media using embedded SUBRIP subtitles are working but there are some media files that will not play SUBRIP subtitles. Have confirmed the subtitles work by opening the same files in VLC and the subtitles show up.

**To Reproduce**
Playing media content with SUBRIP subtitles.

**Expected behavior**
Subtitles to be shown.

**Logs**
No errors in the logs pertaining to the file, the subtitles get extracted as the logs refer to deleting the extracted subtitles once playback ends. No difference in log messages between media where the subtitles work and media that they do not. Can enable further logs if requested.

**System (please complete the following information):**
 - OS: Ubuntu, Windows
 - Browser: Firefox, Edge
 - Jellyfin Version: 10.5.5, 10.6.0

**Additional context**
I can enable additional levels of logging if that will help but there are no errors present in the logs before playback begins or during playback.

**Comment by MrTimscampi** [comment]
This is most likely due to subtitle extraction not being done during scan.

Can you launch a file, let it sit for a bit and then try replaying it?

**Comment by Cmdrd** [comment]
Tried this with both versions, started the file then paused it, left it for about 5 minutes before hitting play again, still no luck getting anything to show up. Have also tried this test with Subtitle Extraction enabled and disabled to see if that would resolve anything and no luck with that either.

**Comment by AlexKalopsia** [comment]
Experiencing this as well
