### ISSUE TITLE
1.6.0 - Desktop Text Selection Disabled

### ISSUE THREAD

**Issue by DMouse10462** [jellyfin/jellyfin-web#1518]
As of #1504, text selection has been completely disabled across the entire app on all platforms (with some exceptions being made in #1513). 

At least for the desktop, selecting text (mainly for the purpose of copying) is a first-class human interface paradigm and removal of such a feature is what I would argue to be a regression in functionality. For a more in-depth explanation of my rationale, see https://github.com/jellyfin/jellyfin-web/pull/1504#issuecomment-653255574. Note the agreement from other end-users both in the form of the reaction emoji and the comment directly below. 

I created this issue as a point for tracking and discussion on this topic. If tags could be added, it would be greatly appreciated. Suggested tags are "ui & ux", "discussion needed", and "enhancement" and/or "regression" depending on the opinions of the core team (either should scare away the stale bot).

If we come to a decision that the overall property should remain but more elements should be excepted beyond those in #1513, I would be more than happy to contribute the necessary code to make those exceptions happen. I'd just rather have some discussion before creating anything that might come across as a PR war.

**Comment by DMouse10462** [comment]
I would argue that non-hyperlink metadata such as titles, person names, and body text (item descriptions) should be exempted from the `user-select: none;` property as they represent metadata that could be frequently subject to searches by the user beyond the sources linked in the "Links" section of the details section.

I agree that `user-select:none;` is a great way to prevent a whole host of issues with glitchy blue highlights and other issues within a browser and provides for a more "app-like" experience, but retaining this functionality where useful would be beneficial, if not simply the sensible default.

As an alternative, providing "click-to-copy" or `user-select:all;` on specific blocks of text for easy copying without the drag-to-select paradigm might be a better solution if the dragging causes the greatest issue here.

For native app examples of selectable body text, see:

- GNOME Contacts, 
- Pop!_Shop, 
- Discord (which even provides a simple click to copy some information, like your username, which follows my alternative suggestion above well), 
- MusicBrainz Picard (individual table and list cells can be copied as a whole by selecting and using keyboard shortcuts), 

and a host of Windows apps that I don't currently have access to on my Linux machine (but can provide examples from; I'd especially be interested in the abilities of iTunes, Windows Media Player, and Plex here). 

Some notable web apps (in response to the Netflix and Spotify examples given in #1504) that *do* allow for text selection include: 
- Prime Video, 
- Shadowz (French horror site), 
- themoviedb.org, 
- IMDb, 
- YouTube, 
- Spotify Web (non-hyperlinked text), 
- HBO NOW (titles and body text),
- Crunchyroll (non-hyperlinked text),
- Funimation
- Hulu (browsing while not logged in - I don't have an account)

**Comment by hamburglar2160** [comment]
#1531

**Comment by DMouse10462** [comment]
#1531 is sufficient for me; thank you for the quick PR!
