### ISSUE TITLE
[10.6.0 Unstable] DLNA PlayTo Volume Control issue

### ISSUE THREAD

**Issue by BaronGreenback** [jellyfin/jellyfin-web#1540]
Hovering over the volume control causes the current volume value to be repeatedly sent to the server, even if it hasn't change.
(traced back to mousemove nowplayingbar.js line 214).

It should only do this if it has changed value.

![image](https://user-images.githubusercontent.com/22121540/87033493-3d166600-c1de-11ea-8ba5-0d293c7f2ec3.png)

Also the playback controls are totally blank at times and don't update.

**Comment by dkanada** [comment]
It should be rate limited though right? I think we have it set to half a second everywhere.

**Comment by BaronGreenback** [comment]
I've come across three issues with volume.

1) the range of values (not all devices have volume 0 - 100) - I'm currently parsing the device description to get this range. How would the client pick get this value - as i can include that in my PR?

2) is seems to be able send the same value multiple times. Could it be limited to if the the value has changed since the last time? (just thinking of server load)

3) Don't know if it's rate limited on the current code. All user interaction is in the PR i'm working on, including the play next, shuffle functionality.

**Comment by BaronGreenback** [comment]
I've parse and ratio'ed volume on the server for non-standard devices, so the client doesn't have to worry about it.

**Comment by MrTimscampi** [comment]
>     1. the range of values (not all devices have volume 0 - 100) - I'm currently parsing the device description to get this range. How would the client pick get this value - as i can include that in my PR?

It is not meant to control the volume of the device, but controls the volume of the HTMLMediaElement used for playback. See [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/volume) for more info.  
We don't want to touch the device's volume, and we've actually been thinking about removing he brightness controls as well, as that should really be handled through the platform and not through us.

**Comment by BaronGreenback** [comment]
Confused now; I'm talking about DLNA PlayTo. 

I thought this entire display was a control front end for the DLNA playback device - where the sound is produced.

Changes that happen on this control panel are sent back to Jellyfin, which in turn transmits them to the DLNA device.
(That's how i've been using it anyway.)

**Comment by MrTimscampi** [comment]
Indeed. However, my guess is that they all use 0-100 because it would be very confusing to have various instances of the component using various min-max limits.

So they all use the same limits as the HTMLMediaElement (because it was likely implemented first by Emby), hence 0-100

**Comment by BaronGreenback** [comment]
Tracing the problem back (In latest chrome btw)

setVolume is called via these 3 events - causing the same volume to be transmitted back to the server each time. (eg. this.value remains at 100 regardless).
```
 volumeSlider.addEventListener("change", setVolume),
 volumeSlider.addEventListener("mousemove", setVolume),
 volumeSlider.addEventListener("touchmove", setVolume),
```

```
 function setVolume() {
       currentPlayer && currentPlayer.setVolume(this.value)
 }
```
clicking the scroll sometimes sends the value back to server - but i think that the majority of the time - the mousemove setVolume is being called again.

Now add into the mix that this code is being periodically called which is resetting the volume back to 100. I suspect it's an asynchronous problem with the latest update being received from the server before the server can process the latest change, so is resetting it back.
```
function updatePlayerStateInternal(event, state, player) {
        !function showNowPlayingBar() {
            if (!isVisibilityAllowed)
                return void hideNowPlayingBar();
            getNowPlayingBar().then(slideUp)
        }(),
        lastPlayerState = state;
        var playerInfo = playbackManager.getPlayerInfo()
          , playState = state.PlayState || {};
        updatePlayPauseState(playState.IsPaused);
        var supportedCommands = playerInfo.supportedCommands;
        if (currentPlayerSupportedCommands = supportedCommands,
        -1 === supportedCommands.indexOf("SetRepeatMode") ? toggleRepeatButton.classList.add("hide") : toggleRepeatButton.classList.remove("hide"),
        updateRepeatModeDisplay(playState.RepeatMode),
        updatePlayerVolumeState(playState.IsMuted, playState.VolumeLevel),  **<-- playState.VolumeLevel = 100**
        positionSlider && !positionSlider.dragging) {
```

**Comment by dmitrylyzo** [comment]
**About limiting**
`apiClient` sends volume update only 1 per 3s. At least it should.
https://github.com/jellyfin/jellyfin-apiclient-javascript/blob/c140555768fc2307b458c1b730dbda94d2abd131/src/apiClient.js#L4-L8
https://github.com/jellyfin/jellyfin-apiclient-javascript/blob/c140555768fc2307b458c1b730dbda94d2abd131/src/apiClient.js#L3018-L3025

**About events**
I wanted to change these events to just `input`, but something stopped me :p
https://github.com/jellyfin/jellyfin-web/blob/3dfc370012ce70c74927d2d811f61f5d6994e9fb/src/components/nowPlayingBar/nowPlayingBar.js#L214-L215

**Comment by BaronGreenback** [comment]
Limiting seems not to work when playTo is in effect. Likewise, the volume control stops working.

Works when playTo not "enabled".

**Comment by BaronGreenback** [comment]
StackTrace 

SessionPlayer.sendCommand (plugin.js)
sendCommandByName (plugin.js)
SessionPlayer.setVolume (plugin.js)
setVolume (nowPlayingBar.js)

**Comment by dmitrylyzo** [comment]
> StackTrace
> 
> SessionPlayer.sendCommand (plugin.js)
> sendCommandByName (plugin.js)
> SessionPlayer.setVolume (plugin.js)
> setVolume (nowPlayingBar.js)

It definitely doesn't use command rate limiting.

The idea of current volume control implementation (_at least as I see it_) is to instantly update volume of (local) player so that user can continuously adjust it, but limit the rate of the server updates.

Probably for remote (PlayOn) session we want to do it only on `change`.
But if there are other "unlimited" controls, limiting of the command rate in `SessionPlayer` or `apiClient.sendCommand` (and others) is reqiured.

**Comment by BaronGreenback** [comment]
How does the server comms work - as occationaly the new volume settings 'sticks' and is passed to the server - only for it to reset back to the original value a second later.

**Comment by dmitrylyzo** [comment]
I am not familiar with `SessionPlayer`.
Could it be that client periodically requests a state (polling) and receives an outdated state (prior volume change)?

**Comment by dkanada** [comment]
> The idea of current volume control implementation is to instantly update volume of player so that user can continuously adjust it, but limit the rate of the server updates.

This is indeed the goal. At first it was spamming the server with way too many volume updates, so we changed it to only update the volume on touch end. That made the local volume level extremely unresponsive though, so the new plan is instant local updates and rate limited remote updates.

**Comment by BaronGreenback** [comment]
This is the controller on the PlayTo though. Local volume control is perfect. 

My set up is as follows:

Web interface selected to playTo my device.
I'm using the web interface to control the volume of the playTo device.
This is when the problems begin.
MouseMove stream the same value to the server and make clicking virtully impossible.
When you do manage to click, the volume is randomly reset back to the original start value.
All the other controls work fine.

Rate limiting is implemented in https://github.com/jellyfin/jellyfin/pull/3536 as i don't want to kill the remote client.

My setu

#3536 does implement rate limiting. 
However, the accumulation of mouse move, and

**Comment by dmitrylyzo** [comment]
> I assume the concept is a dynamic float over control that adjusts the volume to the setting where you hover?
> However, the mousemove and touchmove transmit the same value as the current scrollbar.

Ah, I have reproduced locally what you said. No, this is a bug - you shouldn't receive volume update by hovering. This doesn't harm local player, but remote one will receive old value as you said.
As I said earlier, I tried to replace `mousemove` and `touchmove` with `input` (I think `change` also will be unneeded), and it worked, iirc. But I didn't tested it on all devices, so I left it as is.
_To be clear, I think all hacks with mouse and touch should be in slider. External code should use `change` and `input`._

> Rate limiting is implemented in jellyfin/jellyfin#3536 as i don't want to kill the remote client, so the streaming isn't really a problem.

As I understand, PlayOn is: `WebUI -> JFserver -> Device`, right?
Then you should limit `WebUI` not `JFserver`.

**Comment by BaronGreenback** [comment]
I've rate limited JF PlayTo as i have no idea as to the capabilities of the device which we're talking with.

Once it's all up and working, the rate can get dropped - or even added to the profile.

**Comment by dmitrylyzo** [comment]
@BaronGreenback #1578 is merged, please check if you can continue your dev.
