### ISSUE TITLE
Users can temporarily see libraries they don't have access to after an admin user logs out

### ISSUE THREAD

**Issue by mikfar** [jellyfin/jellyfin-web#1549]
**Describe the bug**
If a user with access to the admin dashboard logs in, then logs out using the back arrow at the top left hand corner of the dashboard, the next user to log in on the same device will have access to all of the previous user's libraries, even if they are not supposed to. 

**To Reproduce**
1. Make 2 users, one will be the Admin user with access to the admin dashboard and all libraries. The other user should have access to fewer libraries than the Admin user. 
2. Login as the Admin user, you will be taken to the dashboard. 
3. Immediately logout using the back arrow at the top left hand corner of the screen. 
4. Login as the user with access to fewer libraries, you will now see all the same libraries as you would on the admin account, even though this user is not supposed to have access to them.

**Expected behavior**
Users should not be able to see libraries that they do not have access to. 

**System (please complete the following information):**
 - OS: Ubuntu 20.04 LTS 
 - Jellyfin 10.5.5 using the linuxserver/jellyfin Docker image
 - Accessed using both Chrome and Firefox on Windows 10

**Comment by dkanada** [comment]
The back button isn't actually a logout button, even though it sends you to the login page when you first install the server. @MrTimscampi is there a way to clear the history in our current router? We should also maybe send users to the home page on installation rather than the dashboard.

**Comment by mikfar** [comment]
> when you first install the server. 
I've had the server installed for a few days now and continue to reproduce the bug succesfully, so it definitely isn't just an upon installation problem.

**Comment by dkanada** [comment]
> Immediately logout using the back arrow at the top left hand corner of the screen.

Is the method different then? The back arrow at the top right will never log you out regardless of what page you're viewing.

**Comment by mikfar** [comment]
> > Immediately logout using the back arrow at the top left hand corner of the screen.
> 
> Is the method different then? The back arrow at the top right will never log you out regardless of what page you're viewing.
When I log in as the admin user, I'm immediately brought to the dashboard, clicking the top left arrow takes me back to the login screen.

**Comment by dkanada** [comment]
Ah, I wasn't seeing it because it only happens on the bundled version. Looking at possible fixes now.

**Comment by dkanada** [comment]
partially fixed by #1551
