### ISSUE TITLE
photoviewer - add Fullscreen button

### ISSUE THREAD

**Issue by lelamamalgache** [jellyfin/jellyfin-web#1556]
**Describe the bug**
Hello,

Could you add a fullscreen button on photoviewer ?

**Screenshots**
![image](https://user-images.githubusercontent.com/58141187/87285533-e66b9d80-c4f7-11ea-87ee-fd27a950a84b.png)

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.5.0

**Comment by MrTimscampi** [comment]
Please redirect feature requests and suggestions to https://features.jellyfin.org/
