### ISSUE TITLE
Clicking on Song Card begins playback

### ISSUE THREAD

**Issue by hamburglar2160** [jellyfin/jellyfin-web#1565]
When browsing the search results for an individual song, clicking anywhere on the displayed cards plays the song.

As there is no song "item details" page, I would expect that clicking on the card (i.e. anywhere that isn't the play button) would either 1. do nothing or 2. bring me to the album that contains the song because the card displays its cover art.

For context, clicking outside of the play button on any other type of card would bring me to its corresponding details page.

**Comment by ferferga** [comment]
Isn't our current behaviour what Spotify does? I think it makes sense because when you search for a song you probably want to directly play it and this adds an additional step.

There is an itemdetails page for songs (you can even add descriptions to them) but they're accesible only by going to the album first, so no problem with this, we can redirect to that page for songs.

**Comment by ferferga** [comment]
@hamburglar2160 As a side note - I think this issue and many more that you recently opened belongs more to [features.jellyfin.org](features.jellyfin.org) where they can be discussed and voted by other users. 

In most of them we end up with a discussion between you and other few people and some of the proposed stuff are a big deal for most of the users, so they should be voted and discussed in a more fitting place, which is features.jellyfin.org - IMHO.

**Comment by hamburglar2160** [comment]
> Isn't our current behaviour what Spotify does? I think it makes sense because when you search for a song you probably want to directly play it and this adds an additional step.

This is rarely the case, especially when I click anything on that result that isn't the big play button in the middle. I would expect that pressing the "play button" would play the song, not the surrounding album space. 

When I'm pressing the surrounding album art, I expect _anything but_ the song to play just as every other item on Jellyfin does. It becomes a significant nuisance when I have a play queue that gets lost because I clicked album art that I would have expected to bring me to a details screen and not play.

The play button illuminates and functions as a play button only when hovered over and clicked upon for albums (and artists, movies, TV episodes...)--it's safe to click around these play buttons and _not_ lose your current playback. That behavior is not consistent with songs and having _that_ play button illuminate when in fact the entire thing is a play button seems glaring. 

A fully accessible item details screen for a song would be a feature. This is a UX headache.
