### ISSUE TITLE
Change subtitle title to actual title instead of language

### ISSUE THREAD

**Issue by Evoley** [jellyfin/jellyfin-web#157]
**Describe the solution you'd like**
Instead of subtitles saying "eng default" it would be nice if it said "Signs and Songs" or any other title indicated in MediaInfo

**Describe alternatives you've considered**
Subtitle
Title Eng Default (would be Signs & Songs)
Language eng (would stay the same)
Codec ASS (would stay the same)
Default Yes (would stay the same)
Forced No (would stay the same)
External No (would stay the same)

**Additional context**
This primarily concerns anime with signs and songs and custom subtitle titles (Dialogue [Manko]). The downside that I can think of to this is that subtitles without titles would probably be messed up.

Example taken from MediaInfo v18.12
> Text #1
ID                          : 4
Format                      : ASS
Codec ID                    : S_TEXT/ASS
Codec ID/Info               : Advanced Sub Station Alpha
Duration                    : 23 min 24 s
Bit rate                    : 55 b/s
Count of elements           : 116
Compression mode            : Lossless
Stream size                 : 9.50 KiB (0%)
Title                       : Signs & Songs
Language                    : English
Default                     : Yes
Forced                      : No

>Text #2
ID                          : 5
Format                      : ASS
Codec ID                    : S_TEXT/ASS
Codec ID/Info               : Advanced Sub Station Alpha
Duration                    : 24 min 13 s
Bit rate                    : 179 b/s
Count of elements           : 555
Compression mode            : Lossless
Stream size                 : 31.9 KiB (0%)
Title                       : Dialogue [Manko]
Language                    : English
Default                     : No
Forced                      : No

**Comment by JustAMan** [comment]
> subtitles without titles would probably be messed up

Well, if they lack titles we should fallback to current behaviour. Plus adding a language code like `Subs Title [lang]` would be good IMHO.
