### ISSUE TITLE
Whole menu is jumping up and down when selecting different items

### ISSUE THREAD

**Issue by Bond-009** [jellyfin/jellyfin-web#158]
**Describe the bug**
Whole menu is jumping up and down when selecting different items

**To Reproduce**
1. Go to the dash
2. Click on some menu items

**Expected behavior**
The menu stays where it is.

**Screenshots**
![2019-02-25_18-35-33](https://user-images.githubusercontent.com/21289123/53357423-2bf0f000-392e-11e9-8282-f5702f5e1bb9.gif)

**System (please complete the following information):**
 - OS: Raspbian
 - Browser: Firefox
 - Jellyfin Version: N/A (build from master)

**Comment by redSpoutnik** [comment]
Hello, I think it is because some menu items (such as Playback or Library) have header tabs which push down menu and content. 
Other pages use header tabs, so changing their positions will impact the whole UI.

**Comment by dkanada** [comment]
The issue might be a div with the `mainDrawer-scrollContainer` class. When a dashboard page has tabs the top margin is 6.1em but without tabs the margin is 6.3em on my device which is causing the navigation drawer to jump around. The offending css class is `withSectionTabs` but I haven't looked at a clean solution yet.

**Comment by redSpoutnik** [comment]
I don't think this issue must be closed now.
The problem still exist on master branch and I have submitted a PR trying to fix it (waiting for review).

Best regards.

**Comment by anthonylavado** [comment]
Should be fixed by #422.
