### ISSUE TITLE
Add config UI for new added options IgnoreVirtualInterfaces and SendOnlyMatchedHost

### ISSUE THREAD

**Issue by fasheng** [jellyfin/jellyfin-web#161]
My PR(https://github.com/jellyfin/jellyfin/pull/978) that to fix DLNA problem on multiple interfaces was merged. It provides two new options named `ServerConfiguration.IgnoreVirtualInterfaces` and `DlnaOptions.SendOnlyMatchedHost`. You could decide to provide UI for them or just delete the hard code options if everything works fine as prefer in next release.

@JustAMan @cvium

**Comment by JustAMan** [comment]
My opinion currently is - I don't see why anyone would like to change their current values, so I would suggest to leave it be as it is now. We can always make those configurable later if we want to.

That said, this issue should stay for tracking purposes.
