### ISSUE TITLE
Admin account cannot reset users' passwords

### ISSUE THREAD

**Issue by rbqbjyur** [jellyfin/jellyfin-web#1610]
**Description**
Hi all, fresh install of Jellyfin 10.6.0 - from docker jellyfin/jellyfin:latest (did not migrate)

Admin can create and initially set users' passwords, but once set there is no option to reset/set a new password for an existing account. - see screenshot 1 (Seems to just be a UI issue) 

This worked fine in 10.5.5

I do note there is a hidden form for this (see screenshot 2)
Removing hide from class, brings back the options, however they are non functional and provide a "Login Failure" popup saying there is an invalid username or password (confirmed 2 new passwords match) - see screenshot 3
Also checked just in case, the password did not actually change (logged in as user using old password)

**To Reproduce**
1. Login as Admin account
2. Go to "Dashboard / Users"
3. Select any User
4. Go to "Passwords" tab
5. Notice absence of Password reset option (See first screenshot)

**Expected behavior**
1. Login as Admin account
2. Go to "Dashboard / Users"
3. Select any User
4. Go to "Passwords" tab
5. Enter new Password into "New password:" and "New password confirm:" input boxes
6. Hit save
7. User now logs in with newly set password

**Screenshots**
![image](https://user-images.githubusercontent.com/68548775/87944026-c1969d80-ca96-11ea-88ab-0c46576ddb0d.png)
Screenshot 1 (Missing New Password options)

![image](https://user-images.githubusercontent.com/68548775/87944548-7335ce80-ca97-11ea-8b44-e078d6fcb031.png)
Screenshot 2 (Hidden New Password options)

![image](https://user-images.githubusercontent.com/68548775/87944753-b6903d00-ca97-11ea-9a7b-4a6056d90006.png)
Screenshot 3 (Attempted set new password)

**System**
 - OS: Docker (jellyfin/jellyfin:latest)
 - Browser: Firefox
 - Jellyfin Version: 10.6.0

**Comment by matjaz321** [comment]
Cannot reproduce it...
Works as expected
![image](https://user-images.githubusercontent.com/17064712/90682431-38c17c00-e265-11ea-83c3-8a64dcc0ed83.png)

**Comment by rbqbjyur** [comment]
Since then, 10.6.1 and onwards have been released, has resolved the problem for me.
