### ISSUE TITLE
Right click -> open as new tab breaks new page

### ISSUE THREAD

**Issue by itsthejoker** [jellyfin/jellyfin-web#1613]
**Describe the bug**
Right clicking -> open in new tab on any non-captured link does not render the new page at all.

**To Reproduce**
1. Go to any page that doesn't have a rendered context menu. Right clicking on `Next Up`, `Latest Movies`, etc. all work, or for convenience so do all the links in the sidebar for the admin panel.
2. Right click on the link, then select "open in new tab"
3. The new tab will have completely unrendered templating, not the finished page.

**Expected behavior**
The new page should render to the link I requested.

**Logs**
None

**Screenshots**
![image](https://user-images.githubusercontent.com/5179553/87994878-0aad1880-cabc-11ea-89b0-bb0f7fca1a3c.png)

**System (please complete the following information):**
 - OS: Docker
 - Browser: Firefox
 - Jellyfin Version: 10.6.0

**Additional context**

**Comment by mhrsolanki2020** [comment]
When I open a link normally by left clicking(not open in new tab) the link is
"http://192.168.193.220:8096/web/**index.html#!/**list.html?parentId=_REDACTED_ID_&serverId=_REDACTED_ID_"
When I right click on library heading "Latest Audio Books" and open it in new tab, the link is 
"http://192.168.193.220:8096/web/list.html?parentId=_REDACTED_ID_&serverId=_REDACTED_ID_"

So in the second link if I inset "**index.html#!/**" it works as expected.

**Comment by itsthejoker** [comment]
This is still valid, I just missed the email two weeks ago :(

**Comment by itsthejoker** [comment]
@joshuaboniface can this be reopened please?

**Comment by thornbill** [comment]
This has been fixed for a long time now.
