### ISSUE TITLE
Animated backdrops/theme videos completely break web UI

### ISSUE THREAD

**Issue by CTalvio** [jellyfin/jellyfin-web#1615]
**Describe the bug**
Animated backdrops/theme videos completely break web UI. When opening an item that has a video file in /backdrops/video.file all UI disappears leaving only the theme video playing. UI does not return once it ends.

**To Reproduce**
1. Have a library item with a file in /backdrops/video.file (my exact filename "video1.mp4")
2. Open that item in web UI (I did not notice this at first after upgrading, seemingly the files had not detected yet)

**Expected behavior**
The video should simply replace the backdrop, the only difference being it is animated
To illustrate, in 10.5 it worked like in the video like in this reddit post by me: https://www.reddit.com/r/jellyfin/comments/htrfrx/but_wait_there_is_more_custom_css/
Now, it looks like this: https://youtu.be/Efk9PL8ADFA

**System (please complete the following information):**
 - OS: Mint 19.1
 - Browser: Firefox 78.0.2
 - Jellyfin Version: 10.6.0

**Comment by theLMGN** [comment]
Just signed into Chrome, see if it's a Firefox CSS issue, broken there too.
![image](https://user-images.githubusercontent.com/12257112/91447651-d40fae00-e870-11ea-9ad6-076457e9c2e2.png)

**Comment by dmitrylyzo** [comment]
Video player hides previous page: https://github.com/jellyfin/jellyfin-web/blob/a674cb68b658590aea9cb3ecebf85d9bdd2315b8/src/plugins/htmlVideoPlayer/plugin.js#L107-L112
_This was made to hide scrollbar, iirc._

We probably need to detect `videoosd` or pass some parameter to player.
