### ISSUE TITLE
Focusing on item thumbnail in the details page on TV mode messes up the UI

### ISSUE THREAD

**Issue by josersanchez0117** [jellyfin/jellyfin-web#1626]
**Describe the bug**
Focusing on the item's thumbnail / poster messes up how the UI looks in the TV mode.
**To Reproduce**

1. Set web client to use TV mode.
2. Navigate to a movie, series, or episode
3. Focus on the item poster (navigate with arrow keys or click on the thumbnail)
4. See bug

**Expected behavior**
Nothing happens/isn't focusable/doesn't mess up the UI

**Logs**
None

**Screenshots**
![image](https://user-images.githubusercontent.com/32964662/88207886-0a289500-cc16-11ea-93c4-70aa9d12add6.png)
Issue on Firefox 78.0.2
**System (please complete the following information):**
 - OS: Windows 10
 - Browser: New Edge (Chromium), Firefox
 - Jellyfin Version: 10.6.0

**Additional context**
I'd expect the thumbnail to not be focusable anyway, since it does no action.

**Comment by Camc314** [comment]
Should be fixed by #1845
