### ISSUE TITLE
Edgium can direct play HEVC on 10.5.0, but can't on 10.6.0

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [jellyfin/jellyfin-web#1631]
**Describe the bug**
HEVC content is able to be direct played on Edgium in Jellyfin 10.5.0, but not in 10.6.0

**To Reproduce**
1. Play a HEVC video

**Expected behavior**
1. The video should be direct played

**System (please complete the following information):**
 - OS: Windows (unsure if macOS Edgium has HEVC support)
 - Browser: Edgium
 - Jellyfin Version: 10.6.0

**Comment by ThibaultNocchi** [comment]
Does it work with JF 10.6.1?

**Comment by nyanmisaka** [comment]
> Does it work with JF 10.6.1?

It should work. I have tried on my edge chromium.
