### ISSUE TITLE
Top navbar doesn't dismiss on scroll down

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [jellyfin/jellyfin-web#1639]
**Describe The Bug**
When scrolling down pages, usually the top navbar dismisses itself after you scroll. This is the behavior on 10.5.0, but it is broken in master (haven't tested in stable 10.6.0).

**Steps To Reproduce**
1. Scroll down in home screen (or any view)
1. Observe the top navbar

**Expected Behavior**
It should dismiss after scrolling down

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Edgium
 - Jellyfin Version: master

**Comment by MrTimscampi** [comment]
This behavior was disabled pre-10.5 and kept only on mobile. See #663 for reference.

The behavior on 10.5 was to have a fixed header in the desktop and TV layouts, with mobile keeping the hide on scroll.
