### ISSUE TITLE
Syncplay generates playback errors

### ISSUE THREAD

**Issue by therhenals** [jellyfin/jellyfin-web#1640]
Install jellyfin in a vps, when using Syncplay is not synchronized, it pauses, I think you should implement a moderate time range between the connected devices to avoid these cuts, ie if for example a device is about 10 seconds ahead of another, do not send the order to synchronize.

**Comment by mhrsolanki2020** [comment]
Facing similar issue. One of the device will work smoothly and the other device constantly tries to sync up and pauses everytime it tries to sync. This happens so frequently ( once or twice a second) that the playback hangs every second.

**Comment by roshanconnor123** [comment]
Facing the same issue
I created a group in My browser and started playing
I joined the group in my android phone via app
It plays smooth in Browser
But stutters in Android (Like Pausing and resuming continuously)

PS: Server is running in my windows server

**Comment by Bellusterra** [comment]
I'm no expert, but I think the subtitle sync issue might be related and can maybe help diagnose the problem.
https://github.com/jellyfin/jellyfin/issues/2547

**Comment by OancaAndrei** [comment]
> Install jellyfin in a vps, when using Syncplay is not synchronized, it pauses, I think you should implement a moderate time range between the connected devices to avoid these cuts, ie if for example a device is about 10 seconds ahead of another, do not send the order to synchronize.

[This PR](https://github.com/jellyfin/jellyfin/pull/4329) adds SyncPlay preferences and will let you tweak how often the active-syncing should happen or if at all.

**Comment by roshanconnor123** [comment]
> > Install jellyfin in a vps, when using Syncplay is not synchronized, it pauses, I think you should implement a moderate time range between the connected devices to avoid these cuts, ie if for example a device is about 10 seconds ahead of another, do not send the order to synchronize.
> 
> [This PR](https://github.com/jellyfin/jellyfin/pull/4329) adds SyncPlay preferences and will let you tweak how often the active-syncing should happen or if at all.

Oh wow
Thank you
Gonna try that now
