### ISSUE TITLE
Read CBZ/CBR/CBT Comic Books

### ISSUE THREAD

**Issue by Protektor-Desura** [jellyfin/jellyfin-web#1648]
Since we can't read comic books at the moment. I thought I would point this javascript out that is under the MIT license that could be used to add this feature to the Jellyfin Web interface. It also has all the uncompress routines as well.

https://github.com/afzafri/Web-Comic-Reader

**Comment by MrTimscampi** [comment]
Thank you for the suggestion.

However, there is already a PR open for such a reader (#1325). We also already have an issue to track this (#1281).
