### ISSUE TITLE
Media controls overlay not disappearing after changing resolution on mobile (Chrome and app)

### ISSUE THREAD

**Issue by ThibaultNocchi** [jellyfin/jellyfin-web#1671]
**Describe The Bug**
I load a video on Android Chrome or on the Android app, it works great. Whenever I open the setting menu then playbacks data, it still works great. When I change resolution and the video resumes, the overlay doesn't disappear even when clicking on the video.

**Steps To Reproduce**

1. Start a video playback on Chrome Android or latest 1.0.2 app
2. Wait for the overlay to disappear, it should work
3. Change resolution, wait for it to process
4. Overlay doesn't disappear

**Expected Behavior**
The overlay should disappear as usual.

**System (please complete the following information):**
 - Platform: Android
 - Browser: Chrome, JF app
 - Jellyfin Version: 10.6.0 - 10.6.1

**Additional Context**
Similar issue has been raised on the Android app repo jellyfin/jellyfin-android#379

**Comment by mhrsolanki2020** [comment]
Facing similar issue. My devices
1. Android
2. iPad 

Since apps on both these devices are just a wrapper of the web-version, bug is in jellyfin-web.

**Comment by mholt** [comment]
I can also reproduce this. Don't have to change the resolution though, just try scrubbing.

**Comment by ThibaultNocchi** [comment]
This seems to have been fixed, at least on 10.6.4
