### ISSUE TITLE
10.6.1 HEVC Encode Does Not Stay Enabled

### ISSUE THREAD

**Issue by Enuqt** [jellyfin/jellyfin-web#1673]
Hey,
Just noticed when VideoToolBox is used HEVC Checkmark is opting out by it self after a few seconds is this a issue

<img width="821" alt="Screenshot 2020-07-28 at 10 45 04" src="https://user-images.githubusercontent.com/23746300/88641410-73e5ea80-d0bf-11ea-9e6e-12710245916f.png">

**Comment by TheGreatestJannet** [comment]
This doesn't seem to be only related to HEVC. I have a iMac Late 2013 and H264 won't stay enabled, although it seems to still be using hardware acceleration as the CPU usage is far to low to be software. Is there a way to see what is supported by your iMac?

**Comment by TheGreatestJannet** [comment]
This is still an issue

**Comment by Enuqt** [comment]
hey if i use docker jellyfin on macos i cant use videotoolbox at all
