### ISSUE TITLE
Strings do not appear translated despite translation strings existing

### ISSUE THREAD

**Issue by KucharczykL** [jellyfin/jellyfin-web#1682]
**Describe The Bug**
Tooltips for the Cast and Search buttons in the header are still in English even when non-English language is selected in Settings -> Display menu.

**Steps To Reproduce**
1. Go to Settings -> Display.
2. Change Display Language to Czech.
3. Hover over Cast or Search buttons.

**Expected Behavior**
The tooltips are translated to the selected language.

**Logs**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/31072879/88791824-a31d5a00-d19a-11ea-920d-70fb95471894.png)

**System:**
 - Platform: Linux
 - Browser: Firefox
 - Jellyfin Version: 10.6.1

**Additional Context**
The offending line is in the `src/scripts/libraryMenu.js` file on line 18:
```
html += `<button type="button" is="paper-icon-button-light" class="headerButton headerButtonRight headerSearchButton hide" title="${globalize.translate('ButtonSearch')}"><span class="material-icons search"></span></button>`;
```

Relevant chat logs (@dmitrylyzo):
```
Looks like it is translated before language is set
Because I have set English for web and Russian for server - I see Russian "Search" instead of English one
Same for Cast
```

**Comment by ThibaultNocchi** [comment]
Ok I think I'm seeing where this is coming from.

The language used to translate is defined in the globalize object, and is the `currentCulture` property in `src/scripts/globalize.js`. The method `updateCurrentCulture()` is used to either load it from the user settings or default to something from the browser it no user settings is available (yet).

This method is called twice in a new page load. First in the same file on its own (line 257) then after the user was successfully signed in, file `src/scripts/site.js` line 229. The first call fails loading from user settings and just retrieve the browser language, then the second one successfully loads the user setting. But the translations for navigation bar are done between the first and second call.

So rendering this navbar should be done after retrieving the user settings, or maybe it can be refreshed after they are loaded.
