### ISSUE TITLE
Clicking on a song plays incorrect item

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-web#169]
**Describe the bug**
In Music, if you click on a track in an album, it will often play an incorrect item.

**To Reproduce**

1. Go to Music, and click on any album to view details
2. Click on Track 1
3. Observe other track play
4. Repeat with other tracks

**Expected behavior**
The correct track should play when selected.

**Logs**
Nothing correlating found just yet. Will update if I see something.

**System (please complete the following information):**
 - OS: Debian, macOS (presume all are affected)
 - Browser: Safari, Chrome (assume all are affected)
 - Jellyfin Version: Latest Master as of 44e16c7 for web, and 40089e2 for core

**Additional context**
This problem is not present in the release of 10.2.2.

**Comment by JustAMan** [comment]
Can this be caused by https://github.com/jellyfin/jellyfin/pull/1011 ?

**Comment by anthonylavado** [comment]
>Can this be caused by https://github.com/jellyfin/jellyfin/pull/1011 ? 

@JustAMan Yes, this is believed to be correct at this time. I might add - we should probably consider this blocking the next release…
