### ISSUE TITLE
Scrollbar shows up during playback on Firefox

### ISSUE THREAD

**Issue by CutterXYZ** [jellyfin/jellyfin-web#1690]
**Describe The Bug**
Starting with Jellyfin 1.6.0, when I click on the fullscreen button during playback, a scrollbar appears on the right of the screen despite there being enough screen size. Scrolling has no effect. Clicking on the fullscreen button again exits fullscreen but the interface overlaps at the bottom (it's drawn under the browser window's bottom border). This is on Firefox. I couldn't reproduce this on Chrome.

**Comment by Camc314** [comment]
What size media are you playing (portrait/landscape/resolution e.c.t)?

**Comment by CutterXYZ** [comment]
Regular 16:9 content in 1280x720 resolution on a 1920x1200 monitor.

**Comment by Camc314** [comment]
I can't seem to reproduce it. Could you try again but add the following in the custom css section in the dashboard:
```
.videoPlayerContainer {
    scrollbar-width: none;
}

.videoPlayerContainer::-webkit-scrollbar {
    display: none;
}
```
hopefully that should hide the scroll bar

**Comment by CutterXYZ** [comment]
The .css doesn't fix it.

**Comment by dmitrylyzo** [comment]
Fullscreen is working normally on Firefox 79.
But scrollbar is displayed on videoplayer page - for some reason Firefox doesn't hide scrollbar on removing of `force-scroll` class.
If I remove this line https://github.com/jellyfin/jellyfin-web/blob/e7180e2633a228c2f3e65616358313fa23eb5795/src/assets/css/site.css#L44 - scrollbar hides as expected.

Using this custom CSS fixes that behavior too:
```css
body {
    overflow-x: unset;
}
```

So probably we should remove that line and trim/fit page content if needed.

**Comment by CutterXYZ** [comment]
Please note that this is not only an issue about the scrollbar but also about the screen size not fitting in the window upon exiting from fullscreen.

**Comment by CutterXYZ** [comment]
Would someone please take a look at this issue please ? It's still present in 10.6.4. Thank you.

**Comment by alex9099** [comment]
I can reproduce this (see #1944 for images and description)

**Comment by dmitrylyzo** [comment]
Fullscreen issue seems to be fixed in Firefox 81. Am I right?

**Comment by alex9099** [comment]
Indeed, seems fixed on firefox 81.0

**Comment by CutterXYZ** [comment]
The first time a video is launched, the scrollbar appears. Then if I enter fullscreen (with the player's fullscreen button) it disappears. When I exit fullscreen it stays hidden.
I'm on 82b4.

**Comment by alex9099** [comment]
I'm on 10.6.4, seems to happen but only on the first video view if i don't go to full screen (it is barely noticeable as the "place i'm now on the page" disappears and only a almost dark bar is there), as soon as i go to full screen once i can go back to movies list and the bar wont be there if i start another movie 

So ->

1. Open jellyfin main page
2. select some movie
3. Bar is there
4. Go back, choose another movie
5. Bar is still there

 and 

1. Open jellyfin main page
2. select some movie
3. Bar is there
4. Double click for full screen
5. Bar no longer there
6. Choose another movie
7. Bar no longer there
