### ISSUE TITLE
Subtitle size and police are not persisted

### ISSUE THREAD

**Issue by gnouts** [jellyfin/jellyfin-web#1696]
**Describe The Bug**

When I change subtitle size or font in my profile settings, it's apply for the current session. If I change device or logout, size and font are back to default.

**Steps To Reproduce**

1. Go to the subtitle profile settings (top-right profile pic > subtitles)
2. Change size. For example set "Larger".
3. Click Save.
4. Logout and login again
5. Go back to subtitle settings

Size is back to "Normal"

**Expected Behavior**
Settings should be persisted between sessions.

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Platform: Docker
 - Browser: Firefox, Brave
 - Jellyfin Version: 10.6.0

**Additional Context**

Bug only affect the last three settings (Size, Font, Shadow).
If I change Language or Subtitle Mode it's persisted. Which is really confusing.

**Comment by dmitrylyzo** [comment]
Subtitle Language, Mode and Burn are tied to user profile (server side) as they are independent of device specifications.
Subtitle appearance (Size, Font, Shadow) is saved on client side - different appearance on each device.

On `master`, if I use same browser (even after closing tab), subtitle appearance is saved and restored properly.

**Comment by gnouts** [comment]
Thanks now I understand why it works like that. Though, I think it's not userfriendly.

If we think subtitle appearance might change often, we should offer to change those settings directly in the player (where you need them).
If we think it's a user profile setting, it should be set once and persisted on logout.

Personally, I'd like a mix of both, like the preferred language. You set you preference once in user profile, which is persisted on logout. If subtitles are not great on a particular movie, i'd like to have the settings in the player so I don't need to stop, go to settings and back to movie to play again.

> On master, if I use same browser (even after closing tab), subtitle appearance is saved and restored properly.
I guess it's because your cookies or localstorage are not cleaned when you only close tab.
If your browser clears cookies when closed, or if you properly logout, it's not persisted.

**Comment by dmitrylyzo** [comment]
> I guess it's because your cookies or localstorage are not cleaned when you only close tab.
> If your browser clears cookies when closed, or if you properly logout, it's not persisted.

I also closed browser. In fact, they are correct even after reboot.
Settings are located in localStorage and they are not supposed to be cleaned up when you logout.
