### ISSUE TITLE
Cmd-[number] causes video seek

### ISSUE THREAD

**Issue by aaroncm** [jellyfin/jellyfin-web#1698]
**Describe The Bug**
During playback, if I use a cmd-number keyboard shortcut to change tabs in my browser, jellyfin interprets this as requesting a seek in the video (1 for 10%, etc). My limited understanding of browser javascript leads me to believe that this is an issue of `onkeydown` vs `onkeypress` treating modifier keys differently.

**Steps To Reproduce**
1. Play a video in jellyfin-web, with the jellyfin tab in the foreground
2. Press a cmd-[number] key to switch to a different tab
3. Observe that the tab has changed as intended, but jellyfin has also jumped position in the video.

**Expected Behavior**
Switch tabs without triggering a video seek.

**System (please complete the following information):**
 - Browser: observed in both Firefox and Chrome derivatives
 - Jellyfin Version: 10.6.1

**Comment by MrTimscampi** [comment]
Fixed by #1697
