### ISSUE TITLE
Season poster on the season page is square

### ISSUE THREAD

**Issue by CTalvio** [jellyfin/jellyfin-web#1717]
**Describe The Bug**
The series poster on the season page is square for some series, cutting off top and bottom of the poster. If there is a season poster it is displayed correctly. But if there is not and the season image is defaulting to the series poster then it displayed square.

**Steps To Reproduce**
Go to a TV series that does not have season posters, open a season, look at series poster.

**Expected Behavior**
It should show the image in poster aspect ratio.

![image](https://user-images.githubusercontent.com/4365015/89092202-5a42ec80-d3b8-11ea-9a9e-8742fe5fdb85.png)
Image taken with custom CSS active but tested without as well, and issue persists.

 - Platform: Windows 10
 - Browser: Firefox 79
 - Jellyfin Version: 10.6.1

**Comment by MrTimscampi** [comment]
It seems fine for me.

![image](https://user-images.githubusercontent.com/19396809/89092712-79d81600-d3b4-11ea-8488-b93b2d92d104.png)

**Comment by CTalvio** [comment]
![image](https://user-images.githubusercontent.com/4365015/89092744-2ae2ae80-d3bd-11ea-899f-41e764f57c61.png)

Removed Custom CSS entirely just for a sanity check. Still happening.

Note, as I wrote in the original post, the season cannot have an image assigned, it has to be using the series image as it does when it does not have it's own image. What happens if you delete the season image @MrTimscampi ?

Added one manually, it works.

![image](https://user-images.githubusercontent.com/4365015/89092780-7bf2a280-d3bd-11ea-879d-c615e0374cf7.png)

**Comment by MrTimscampi** [comment]
Correction, I can reproduce it.

It's due to the server not sending `PrimaryImageAspectRatio` in the item info.

@jellyfin/backend Would it be possible to add this field for the parent item's primary image if the item itself doesn't have one but has a parent?

**Comment by thornbill** [comment]
This seems to have been fixed at some point.
