### ISSUE TITLE
Can't fullscreen on iOS

### ISSUE THREAD

**Issue by Bond-009** [jellyfin/jellyfin-web#1720]
**Describe The Bug**
Pressing the fullscreen button does nothing

**Steps To Reproduce**
1. Start playing a video
2. Press fullscreen
3. Nothing happens

**Expected Behavior**
Fullscreen
**System (please complete the following information):**
 - Platform: iOS
 - Browser: Safari
 - Jellyfin Version: 10.6 - master

**Additional Context**
10.5.5 worked fine

**Comment by nyanmisaka** [comment]
It was fixed several days ago. https://github.com/jellyfin/jellyfin-web/pull/1684

**Comment by Bond-009** [comment]
How did I not notice that?...
