### ISSUE TITLE
Login page, text color is black

### ISSUE THREAD

**Issue by AlfHou** [jellyfin/jellyfin-web#1746]
On the login page all the text describing the fields is black, making it hard to see against the dark background.
I am using arch linux with i3

**Steps To Reproduce**
Start the jellyfin server and client and go to localhost:8096

**Expected Behavior**
I should be able to clearly read the fields on the login page

**Screenshots**
![image](https://user-images.githubusercontent.com/20001253/89221565-c8afc680-d5d3-11ea-8281-d46cef9bbd4e.png)

Highlighed the text fields:
![image](https://user-images.githubusercontent.com/20001253/89221631-df561d80-d5d3-11ea-8e34-53ae4e78c144.png)

**System (please complete the following information):**
 - Platform: Arch Linux
 - Browser: Same issue on Firefox and Chrome (didn't test any other browser)
 - Jellyfin Version: Built from master branch (2020-08-03)

**Additional Context**
Don't know if relevant but my machine specs: 
CPU: Intel i7-3820 (8) @ 3.800GHz
GPU: NVIDIA GeForce GTX 1060 6GB

**Comment by MrTimscampi** [comment]
For reference, the issue comes from this commit: https://github.com/jellyfin/jellyfin-web/commit/1fe25e14ddb6131be62b1ed4dbb12f3a821a5702

**Comment by MrTimscampi** [comment]
Fixed in #1795
