### ISSUE TITLE
Last album view no longer saved.

### ISSUE THREAD

**Issue by Darkwolf1515** [jellyfin/jellyfin-web#1767]
**Describe The Bug**
Jellyfin no longer remembers what you had last selected for music view, will always go back to suggestions.

**Steps To Reproduce**
1. Go to songs, select a view, such as albums, or album artists.
2. Back out of songs
3. Go back into songs, see you are now on suggestions

**Expected Behavior**
For it to save what I had last looked at

**System (please complete the following information):**
 - Platform: Docker, synology
 - Browser: Firefox 72
 - Jellyfin Version: 10.6.2

**Additional Context**
Worked just fine on my windows build, but I just moved to docker today.

**Comment by grafixeyehero** [comment]
@Darkwolf1515 if i am not mistaken this is not a bug b/c this thing work based on user setting and the default setting is set in suggestion. if you go to home setting their is option **Default screen:**  you can edit form drop down menu.

![Screenshot 2020-10-22 202421](https://user-images.githubusercontent.com/32230989/96907968-a75cc900-14a4-11eb-894d-6223ef199f2c.jpg)

**Comment by Darkwolf1515** [comment]
You're right, I suppose an update changed that setting for me, thank you.
