### ISSUE TITLE
Selection dosn't work on Playstation 4 in TV mode

### ISSUE THREAD

**Issue by K5HV** [jellyfin/jellyfin-web#1772]
**Describe The Bug**
When using TV layout in PS4 browser focus is working fine, but the selection doesn't.
It selects where the cursor is and not the current focused item.

**Steps To Reproduce**
1. Open Jellyfin in Playstation 4 browser
2. Go to anywhere
3. Select anything using TV remote or d-pad
4. Nothing will happen or different action will be selected.

**Expected Behavior**
Focused element should be chosen when selected.

**Logs**
N/A

**System (please complete the following information):**
 - Platform: Sony Playstation 4 (FW: 7.51)
 - Browser: Built-in WWW browser
 - Jellyfin Version: 10.6.2

**Additional Context**
I'm pretty sure similar issue was mentioned in #1054

**Comment by K5HV** [comment]
**Screenshots**
![20200806144719](https://user-images.githubusercontent.com/24753934/89534067-acd73b00-d7f4-11ea-9a76-1a2dbdbf0f92.jpg)
I've focused "Guide" but when I want to enter it "Son of a Gun" will be selected (because pointer is there)

**Comment by dmitrylyzo** [comment]
Is this emulated mouse (by TV remote or gamepad)?

**Comment by K5HV** [comment]
TV remote. Same story using d-pad on gamepad.
