### ISSUE TITLE
Playback goes backward or forward when using player menu on Playstation 4

### ISSUE THREAD

**Issue by K5HV** [jellyfin/jellyfin-web#1773]
**Describe The Bug**
When movie is playing and I try to navigate using player menu (click on pause, or open settings), playback goes backward when I try to navigate left and goes forward when I navigate right.
Seems that focus is on movie instead of menu buttons.

**Steps To Reproduce**
1. Start any seekable movie
2. Try to click buttons in player box.
3. Movie will be backwarded/forward

**Expected Behavior**
Movie shouldn't be changed when I navigate player menu.

**Logs**
N/A

**System (please complete the following information):**
 - Platform: Sony Playstation 4 (FW: 7.51)
 - Browser: Built-in WWW browser
 - Jellyfin Version: 10.6.2

**Additional Context**
It seems it happens only on desktop mode. Issue doesn't affect TV mode.

**Comment by K5HV** [comment]
**Screenshots**
![20200806152531](https://user-images.githubusercontent.com/24753934/89537340-7fd95700-d7f9-11ea-84d5-9816ac6dce51.jpg)
![20200806152537](https://user-images.githubusercontent.com/24753934/89537344-810a8400-d7f9-11ea-85a0-6a47a5ee3267.jpg)
![20200806152542](https://user-images.githubusercontent.com/24753934/89537345-810a8400-d7f9-11ea-98e7-abadcdc65d0f.jpg)

During movie playback I swiped three items left (from "previous track" to "pause"). Without selecting anything movie was forwarded around 30s each swipe.

**Comment by dmitrylyzo** [comment]
Switch display mode to TV (`Settings` -> `Display` -> `Display mode`) - keyboard navigation is only for TV.

**Comment by K5HV** [comment]
I'm not using keyboard, but TV remote.
TV mode is affected by other issue. #1772

**Comment by dmitrylyzo** [comment]
> I'm not using keyboard, but TV remote.

You can think of it as a keyboard because TV remote and gamepad are implemented as a keyboard.
A more accurate name is "spatial navigation".
