### ISSUE TITLE
Duplicate SyncPlay commands will never be ignored.

### ISSUE THREAD

**Issue by iwalton3** [jellyfin/jellyfin-web#1777]
https://github.com/jellyfin/jellyfin-web/blob/e8ea789b66c3c9a71bffba9617e93f10105416f8/src/components/syncPlay/syncPlayManager.js#L387

It looks like the line there should be:
```js
this.lastCommand.Command === cmd.Command
```

**Comment by OancaAndrei** [comment]
Nice catch! Along the rewrite, it got corrected in #1945.
