### ISSUE TITLE
Sliders become un-draggable after double click to fullscreen

### ISSUE THREAD

**Issue by bugfixin** [jellyfin/jellyfin-web#1786]
**Describe The Bug**
After a double-click on the video to fullscreen, the OSD control sliders (both volume and playback position) work with single clicks along their length, but do *not* work with normal dragging "slider" functionality. The browser drags the OSD around instead.

**Steps To Reproduce**
1. Start a video
2. Adjust the sliders, watch them drag properly.
3. Double click the center of the screen to fullscreen
4. Attempt to drag the sliders again

**Expected Behavior**
Sliders to remain draggable

**Logs**
N/A

**Screenshots**

**System (please complete the following information):**
 - Platform: JF is running on a debian LXC under proxmox
 - Browser: Chrome  83.0.4103.116
 - Jellyfin Version: 10.6.2

**Additional Context**
Notably, this does not occur if I enter fullscreen via clicking the "fullscreen" button. I can also return the sliders to being functional after clicking empty space in the title bar.

I've noticed if I remove the `<div class="pageContainer flex"></div>` empty element, this behavior does not occur. I doubt that helps but hey.

**Comment by dmitrylyzo** [comment]
That also happens in non-fullscreen in Chrome 83, but works fine in Chrome 79.
I see no purpose in `pageContainer`.
