### ISSUE TITLE
Is currentTime in ticks or ms?

### ISSUE THREAD

**Issue by iwalton3** [jellyfin/jellyfin-web#1790]
Right now there is a bug in the web player, which causes cast clients such as MPV Shim and Chromecast to skip forward entire episodes when using the seek buttons:

When I hit the "seek back" button:
`2524100000000 / 10000000 / 3600` = absolute seek to 70 hours

When I hit the "seek forward" button:
`152050000000 / 10000000 / 3600` = absolute seek to 4.2 hours

The root cause of this problem is the currentTime value is treated as ticks in some sections of the code, and as milliseconds in other parts. This causes inconsistent behavior, and I've seen it worked around with checks like this:

```js
if (player.isLocalPlayer) {
    return player.seekRelative((ticks || 0) / 10000);
} else {
    return player.seekRelative(ticks);
}
```

I'm not sure what units that should be in. For instance, [here are the changes](https://github.com/iwalton3/jellyfin-web/compare/master...iwalton3:currenttime) you'd need to make all instances of currentTime be in milliseconds that I could find.

**Comment by dkanada** [comment]
@Maxr1998 this might be related to the changes you made for the Android client.

**Comment by Maxr1998** [comment]
> @Maxr1998 this might be related to the changes you made for the Android client.

I think my PR just added a new function to see with milliseconds, should affect the other seek methods..

**Comment by iwalton3** [comment]
I was testing with this more. The only issue is if I hit the button multiple times, it will only seek backwards once unless I wait for the state update to be sent back (via the /Playing/Progress call back through via the websocket) between pressings of the button.

I'm not sure if this is a bug or if it requires a design change to stack the requests. I know that the controlled client gets an absolute seek value sent to it, so the controlling client would have to deal with it, probably by updating the local PositionTicks before the action has been confirmed.
