### ISSUE TITLE
[Feature Request] Extend the "Select Server" feature

### ISSUE THREAD

**Issue by mazzystr** [jellyfin/jellyfin-web#184]
This feature request is to extend the "Select Server" feature...
- The user should have the ability to change the label of the server
- The user should have the ability to add multiple servers
- The user should have the ability to view info regarding a configured server

Another option is having multiple endpoints for each server determined on the current WiFi ssid of the internal network then use another endpoint when the device is not ie... on the cellular network and/or another Wifi ssid.  See Android app nzb360 for a demo on how this functionality works.  I have really been enjoying nzb360 because of the endpoint flexibility.  I can be out at dinner with friends, get talking about a show then immediately add it to my queue.

This should give the ability to easily access the same Jellyfin server within an internal network and from the internet (or maybe this functionality is already available and I'm not grokking it).

Thanks.

**Comment by Uatschitchun** [comment]
I would second this request!

**Comment by anthonylavado** [comment]
@uatschitchun Feature Requests should now go to our Fider page, found here: https://features.jellyfin.org

**Comment by mazzystr** [comment]
Feat req moved...
https://features.jellyfin.org/posts/273/extend-the-select-server-feature
