### ISSUE TITLE
Bottom video controls don't auto-hide

### ISSUE THREAD

**Issue by ghost** [jellyfin/jellyfin-web#1865]
Video controls stay on top and hide subtitles. This happens randomly, only workaround is to stop and restart the video.

**Comment by mholt** [comment]
To clarify, I also have this issue with the latest web client.

**Comment by dkanada** [comment]
Do you mean latest stable or unstable web client? The latter would definitely be a problem.

**Comment by mholt** [comment]
Oh, stable -- 10.6; is that not new enough? (I'm referring to the default web player, not the Android app.)

**Comment by dkanada** [comment]
10.6.0 or a newer Z release? We should have pushed a fix around 10.6.2 if I recall correctly, so I guess stable should also be fine by now.

**Comment by mholt** [comment]
Oh wow, I didn't realize 10.6.4 was out already. You're probably right then. I'm upgrading currently.

**Comment by dmitrylyzo** [comment]
> We should have pushed a fix around 10.6.2

10.6.3

**Comment by ThibaultNocchi** [comment]
Maybe this is the same as #1671

**Comment by duncanawoods** [comment]
Still happens on 10.6.4.

It seems to be related to two other visual glitches I see:

- On loading the library, the background is white
- When you hit play on the video, it starts playing behind the library tiles. If you hit back, then the library tiles disappear but then the OSD doesn't auto hide.

*Config*

- Both Windows and Linux
- Firefox
- dark theme 
- `Backdrops` disabled

**Comment by mholt** [comment]
Noooo it's still a problem mister bot :)

**Comment by MrTimscampi** [comment]
> Noooo it's still a problem mister bot :)

Is this still an issue on 10.7 RC1 or only on 10.6.4?

**Comment by mholt** [comment]
I haven't had a chance to try RC1 yet, not sure if I will during the holidays...

**Comment by itshoro** [comment]
This happens for me. Currently on 10.7-RC1 Have no steps for reproduction sadly.

It  was always connected to interacting with Subtitles or Settings Menu.

**Comment by mholt** [comment]
Still not fixed

**Comment by Extarys** [comment]
@mholt I'm curious, I remember having this issue a while ago but it didn't last. Does this happen on more than one browser and still on the latest release? :confused: 

If this happens very often, do you think you can open a terminal (F12) and check the console for any errors that could indicate the source of this?

Reading the history of this issue I think nobody yet detected the origin of this issue.

**Comment by omyno** [comment]
@Extarys Happened to me with Chrome 93 and Jellyfin 10.7.7. The mouse cursor itself disappeared, but not the controls. It didn't matter if it was full screen or windowed mode. Developer console didn't show any errors. Refreshing the page made the controls go away after a few seconds so it's not reproducible.

**Comment by dmitrylyzo** [comment]
There are two possibilities:

1. Some of these are "falsy":
`mouseDown` variable is the most probable candidate. It should probably be initialized `false` in the `viewshow` handler (which I didn't do).
https://github.com/jellyfin/jellyfin-web/blob/a70c83de3cffe65f99824e32b5d85b417ecade48/src/controllers/playback/video/index.js#L315

2. Animation flow glitch: the previous animation doesn't end, the second doesn't start
This part and related:
https://github.com/jellyfin/jellyfin-web/blob/a70c83de3cffe65f99824e32b5d85b417ecade48/src/controllers/playback/video/index.js#L265-L273

But I can't reproduce this issue :man_shrugging:

**Comment by daviddavo** [comment]
What about making it possible to hide it using a keypress?

**Comment by dmitrylyzo** [comment]
> What about making it possible to hide it using a keypress?

This is already possible with `Escape`.
On mobile devices, the OSD can be hidden by touch, but it doesn't solve the problem.

If only someone can reproduce it stably. :innocent:

**Comment by kaphwor** [comment]
> > What about making it possible to hide it using a keypress?
> 
> This is already possible with `Escape`. On mobile devices, the OSD can be hidden by touch, but it doesn't solve the problem.
> 
> If only someone can reproduce it stably. 😇

It happens quite a lot to me.
I have jellyfin on a Rpi, and via WiFi I cast it to Chromecast Ultra. How else can I help debug this issue?
Also, there is a way to control this when casting to Chromecast? I have no 'escape' no touch control way out of this afaik

**Comment by dmitrylyzo** [comment]
@kaphwor I opened PR #3209 to make it possible to hide the OSD via the remote control (`Navigation`) from the `Play On` menu.

I am not sure if it is possible to debug Jellyfin inside the Android app, so as an option you can try to replace `jellyfin-web` on your server (backup the original).

Test branches (with PR changes):
10.7: https://github.com/dmitrylyzo/jellyfin-web/tree/dbg-10.7-osd
10.8: https://github.com/dmitrylyzo/jellyfin-web/tree/dbg-10.8-osd
_You need to build it. Choose the appropriate one for your server._

When you start playback you should see popups (toasts): `startOsdHideTimer` and (after 3 seconds) `hideOsd`. They will overlap, but the idea is that `stopOsdHideTimer` should not be the last.

**Comment by kaphwor** [comment]
I'm not sure about the jellyfin's architecture. is Jellyfin-web a folder within my Jellyfin server container?
I'm assuming that jellyfin-web is the video player type (vs Integrated and external players).
I'm running 10.7.7.

As a side note, i'll also try and compile the Tizen client and run it on my TV :) that sounds huge!

**Comment by dmitrylyzo** [comment]
> I'm not sure about the jellyfin's architecture. is Jellyfin-web a folder within my Jellyfin server container?
> I'm assuming that jellyfin-web is the video player type (vs Integrated and external players).

On Debian/Ubuntu `web` is in `/usr/share/jellyfin/web`. I believe it is in the same location in the container.
Once you have built `jellyfin-web`, you can put the contents of `dist` folder there.
I usually rename `web` to `web.bak` and make a new `web` with the contents of `dist`.

> I've pushed your branch, compiled it and i'm running locally. The options you show in your PR does not happear when I Cast onto ChromeCat Ultra.
> They only happear when casting onto the browser.
> What i'm missing here?

I updated the branches (_tbh, I did it blindly and I am not sure if it helps_): `chromecastPlayer` has no `Select` in the list of supported commands.
https://github.com/jellyfin/jellyfin-web/blob/60495dd16a0c5071e3c987b094b44ca221cc85bf/src/plugins/chromecastPlayer/plugin.js#L627-L642

Anyway, have you seen popups on Chromecast device?
![popup1](https://user-images.githubusercontent.com/56478732/144891796-fede28bb-b883-4d23-ae30-1d8445748e64.png)

**Comment by kaphwor** [comment]
@dmitrylyzo I've already built your branch and (hopefully) today i'll put it in my container. Otherwise tomorrow i'll do it and give you feedback!

**Comment by kaphwor** [comment]
@dmitrylyzo I've tested it and I could not login on mobile saying "Unable to reach server". However I could login on browser but Cast button only shows my own device (PC in this case) and it's missing all the rest of devices within my network :/ 
I've built dbg-10.7-osd branch as I have 10.7.7 Jellyfin version.

**Comment by dmitrylyzo** [comment]
> I've deployd your branch onto my server and sadly I see no difference nor any popup, neither on the TV nor on the phone.

:confused: 
_Just to be sure._ Do you see popups in the browser?
It might also be a good idea to disable the browser cache in the `Network` tab of the browser developer tools.

> This only apply to "browser" view or also applies to the App? I'm currently using the Jellyfin android app

Both. Android app is just a webview with jellyfin-web loaded from your server (unlike Tizen app, where jellyfin-web is built into the app).

**Comment by kaphwor** [comment]
> 😕 _Just to be sure._ Do you see popups in the browser? It might also be a good idea to disable the browser cache in the `Network` tab of the browser developer tools.

They show up yes and seems to be working as intended. I see both popups showing up being the last to close one saying "hideOsd"

Is it possible to hide the OSD on chromecast whenever VolumeDown is triggered (not sure about other side effects for other type of cast/viewing)? That would fix for chromecast users as OSD is not usefull at all :P

**Comment by dmitrylyzo** [comment]
> They show up yes and seems to be working as intended. I see both popups showing up being the last to close one saying "hideOsd"

:+1: 

> Is it possible to hide the OSD on chromecast whenever VolumeDown is triggered (not sure about other side effects for other type of cast/viewing)? That would fix for chromecast users as OSD is not usefull at all :P

I prefer to get a fix. :smile: 

I probably mistakenly thought you run Android app on Chromecast device.
If OSD looks like [this](https://developers.google.com/cast/docs/web_receiver/customize_ui#default_video_ui) then the client is https://github.com/jellyfin/jellyfin-chromecast and your problem should be fixed there.

**Comment by kaphwor** [comment]
> I prefer to get a fix. 😄

Yeah, i feel you 👍 

> I probably mistakenly thought you run Android app on Chromecast device. If OSD looks like [this](https://developers.google.com/cast/docs/web_receiver/customize_ui#default_video_ui) then the client is https://github.com/jellyfin/jellyfin-chromecast and your problem should be fixed there. Probably [jellyfin/jellyfin-chromecast#349](https://github.com/jellyfin/jellyfin-chromecast/issues/349) and [jellyfin/jellyfin-chromecast#16](https://github.com/jellyfin/jellyfin-chromecast/issues/16)

Right haha, It would be a Chromecast with GoogleTV (aka CCwGTV) but that's not the case, it's the ultra. I had no idea that that repository existed! I'll look into it and see if I can be of any help :) 

> Or is this the same OSD as in the browser/Tizen? Like this: ![osd](https://user-images.githubusercontent.com/56478732/145099612-416d69bd-1bd0-4e9f-be87-7ce212207525.png)

Nope :) I cannot replicate the same issue with that OSD. On browser / Tizen is just flawless! not a single hickup! 

Thanks for the help @dmitrylyzo !

**Comment by tamasd** [comment]
I found a way to reproduce this issue when using the web UI on Firefox, using the latest stable (10.7.7).

* open any video
* hover over something that opens a tooltip
* the top part disappears, the bottom bar gets stuck
* a reload is needed to make the bottom bar disappear

**Comment by Migacz85** [comment]
In my case even restart doesn't help...

**Comment by mrkylegp** [comment]
I'm also experiencing this, very annoying.

**Comment by DJPlaya** [comment]
Also confirming this Issue:
* On loading the library, the background can be white
* Bottom playback bar dosent fade out, but the upper bar does

Jellyfin 10.8.0 on x64 Win Server 2019
Opera Browser

What i found out is that reloading the website while media is playing will cause the background to go white and stop the bottom bar from fading out. 
A full reload fixes this issue, reloading from cache like opera/chromium sometimes does will not.

**Comment by BornaV** [comment]
can confirm the issue is present on jellyfin v10.8.3 (docker)
 while using the web player, top bar autohides, but bottom one does not

**Comment by Steltek** [comment]
Seeing this issue in the web player with Jellyfin 10.8.4-1 (Debian) with Chrome Version 104.0.5112.102 (Official Build) (64-bit)

**Comment by Longoon12000** [comment]
> What i found out is that reloading the website while media is playing will cause the background to go white and stop the bottom bar from fading out. A full reload fixes this issue, reloading from cache like opera/chromium sometimes does will not.

Thank you @DJPlaya , this issue suddenly appeared (Server Jellyfin 10.8.5 / Ubuntu 22.04, Client Chrome 105.0.5195.127 / Windows 10) and this workaround worked in solving the issue.

**Comment by TylerPeterson085** [comment]
Has anyone figured out how to reproduce this bug? I think I have a solution, but it's hard to tell if I can't induce this.

@dmitrylyzo: any chance maintainers would accept a small pull request (<10 lines) that purports to fix this bug even though we can't test it?

**Comment by Migacz85** [comment]
I'm not quite sure, last time it happened I thought that maybe it was
because my browser was resized. But this does not need to be the case.
Sometimes it's just stuck, and sometimes it just works fine. I really don't
know what can be the real issue here. The code that is responsible for that
just needs to be highlighted and read from top to bottom.

**Comment by newberryle19** [comment]
I seem to be able to reliably reproduce this bug on the linux client. Opening the client in a regular window (not forced fullscreen), then going into the settings and setting the client to fullscreen and then un setting fullscreen, then attempt to play any video in the library fullscreen and the top title bar will fade away, but the timeline/play on the bottom will not until you exit and restart the client. This is using server version 10.8.8 on a raspberry pi, and client version 1.7.1 on any ubuntu device.

**Comment by JansenSmith** [comment]
A previously stated methology, https://github.com/jellyfin/jellyfin-web/issues/1865#issuecomment-1003335929 , does not result in the issue for me. The methodology in https://github.com/jellyfin/jellyfin-web/issues/1865#issuecomment-1371070622 also did not result in the issue, but i DO remember using the player settings roughly when I last encountered the issue.

Player is in browser: Google Chrome Version 109.0.5414.76 (Official Build) (64-bit)
Also, the browser is in a Windows 10 environment, with the media server itself running Linux.

Here is meat of https://github.com/jellyfin/jellyfin-web/issues/4334 for reference:
Navigation Bar doesn't Disappear when watching a video in Internal Player in Linux
After a series of fullscreen & left-arrow-key seek actions, videoOsdBottom becomes permanently fixed, requiring the tab itself to be closed and a new tab opened to resolve.
videoOsdBottom will remain, after videoOsdTop disappears. After that, wiggling the mouse can be used to bring videoOsdTop back up, but when it disappears videoOsdBottom will still remain.

Jellyfin Version: 10.8.9

Operating System: Linux

Architecture: X64

Docker Image: 	lscr.io/linuxserver/jellyfin:latest@sha256:db5654e2e17b0f3579ed9d27ad6050fc634a223e991fd468b5f5442a0e35f68e
Jellyfin

**Comment by Migacz85** [comment]
In my case on windows 11 in chrome when I click full screen controls don't disappear.
Quick dirty fix:
press ctrl+shift+I  
This will open developer tools 
wait for controls to disappear. Press this key combination again.

You are watching film without the controls

**Comment by daviddavo** [comment]
Why does developer tools hide the controls? Perhaps a window size change suffices?

**Comment by daviddavo** [comment]
That would explain why I haven't had this problem since I bought my second monitor

**Comment by entozoon** [comment]
Here's a simple workaround, for when the video controls bar isn't auto-hiding in Chrome as it should - just paste this into your Settings > Display > Custom CSS code: 
```css
.osdControls { transition: opacity .2s  } .osdControls:not(:hover) { opacity: 0 }
```
It'll make it invisible until you hover the mouse over it

**Comment by sapphyrus** [comment]
A consistent way to reproduce this bug (worked for me with Chrome and Firefox on the demo instance):

1. Play any video
2. Reload the page (F5)
 You will end up back on a semi-broken home page. The background is white and text isn't readable, it stays like that until you reload again or enter and exit a player.
![https://i.imgur.com/2A9Jty3.png](https://i.imgur.com/2A9Jty3.png)
3. Play any video and wait a few seconds, now the top part of the player will disappear but the bottom part will remain
![https://i.imgur.com/MWM0z4J.png](https://i.imgur.com/MWM0z4J.png)

**Comment by CzechErface** [comment]
Nice!  I was running into the same issue and it looks like this should fix it for me as well.  However, the docker images (`jellyfin/jellyfin:latest` and `jellyfin/jellyfin:10.8.10`) do not seem to contain this fix.  Am I doing something wrong or has the change not yet been pushed to the image repository?

**Comment by akash-258** [comment]
The issue is present in the mac client. The autohide doesnt work and I have to reopen the application to resolve this.

**Comment by dmitrylyzo** [comment]
> The issue is present in the mac client. The autohide doesnt work and I have to reopen the application to resolve this.

It hasn't been released yet.

**Comment by daviddavo** [comment]
The problem has not appeared any more on my part. But It also appeared less since I changed the server, so I don't know if its fully solved.

Nevertheless, with the merge of #4564, I think this can be closed
