### ISSUE TITLE
Remote Control Overlap on Mobile

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-web#1879]
**Describe The Bug**
In this case, I'm using the Remote Control view on mobile (iPhone X, using the iOS app). When any of the extra sections are expanded, they will push the playback controls **over** the text of what's now playing.

**Steps To Reproduce**

1. Open the web interface on a computer.
2. Open the web interface through a mobile device.
3. Start remote control session from mobile device to computer client.
4. Start playback, and bring up the full remote control display.
5. Expand any of the additional sections (such as Navigation, Send Message, or Enter Text)

**Expected Behavior**
The controls push up and move past the top (it's okay if I have to scroll to see it again).

**Logs**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/596194/91754670-cf603800-eb97-11ea-9e33-9df790504b44.png)

**System (please complete the following information):**
 - Platform: Debian
 - Browser: Safari (via Expo app)
 - Jellyfin Version: 10.6.3

**Additional Context**
N/A

**Comment by MrTimscampi** [comment]
This should be fixed with #2138, I think?

**Comment by anthonylavado** [comment]
Yep, all good.
