### ISSUE TITLE
Web master fails to load in any browser lacking webassembly support

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-web#1881]
**Describe The Bug**
Since the merge of https://github.com/jellyfin/jellyfin-web/pull/1325. The web interface will fail to load for any browser that lacks support for webassembly. It seems that libarchive does not provide any fallback for old browsers and we aren't checking for support prior to loading it.

**Steps To Reproduce**
1. Open the web interface in an old browser
2. Only the splash screen is displayed

**Expected Behavior**
The web interface should load :stuck_out_tongue_closed_eyes: 

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Platform: iPad
 - Browser: Safari 10.3
 - Jellyfin Version: master

**Additional Context**

**Comment by dmitrylyzo** [comment]
This is probably the same issue as in webOS 1.2 - `class` in `bundle.js`.
With #1894, Safari in iOS 10.3.4 loads site, but no playback.

**Comment by thornbill** [comment]
Fixed by #2131
