### ISSUE TITLE
Hamburger menu icon disappears after logging out and in

### ISSUE THREAD

**Issue by ThibaultNocchi** [jellyfin/jellyfin-web#1890]
**Describe The Bug**
When you log out then login without refreshing the page, the hamburger menu icon disappears. Going to any other page or refreshing puts it back.

**Steps To Reproduce**

1. Logout of the web client
2. Login again
3. Witness the disappearance
4. Go to any other page (search, a movie...) and it has come back

**Expected Behavior**
It should always be here

**Screenshots**
![print_screen_2020-09-01-16-06-41](https://user-images.githubusercontent.com/1619359/91861663-60551300-ec6d-11ea-9a75-924ed96c58f7.png)

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Firefox
 - Jellyfin Version: master

**Comment by grafixeyehero** [comment]
@ThibaultNocchi this happen after this PR #1871

**Comment by dmitrylyzo** [comment]
Fixed by #1949
