### ISSUE TITLE
Unusable player controls for mobile app on small screens

### ISSUE THREAD

**Issue by hewham** [jellyfin/jellyfin-web#1931]
iOS app
iPhone SE 2016

The timebar for music tracks on small phone screens (iPhone SE 2016) is completely blocked by the larger buttons on top

Scrubbing through songs (or long podcasts) is impossible, and there is no landscape orientation to get around it

Screenshot tells the story:

![AE15F95C-F95C-4F0D-95E9-DC92C5ED25DA](https://user-images.githubusercontent.com/28872198/93295526-377b6480-f7bb-11ea-8689-1d02834c1cdc.png)

**Comment by SightSpirit** [comment]
I am also having this problem on my Pixel 2 XL (which has a large screen) with album art that is tall enough. (Android 11; app version 2.0.1) There should probably be a maximum height for art in the player view.
