### ISSUE TITLE
Jellyfin won't remember position when scrolling and editing something

### ISSUE THREAD

**Issue by Romybron** [jellyfin/jellyfin-web#1935]
**Describe The Bug**
Everytime a change is made to metadata, it puts you back on top automatically making large size changes a pain in the butt since you have to scroll down every single time you make a change to something.
**Steps To Reproduce**

1. Edit anything in your library

**Expected Behavior**

Remember the scroll position after a change, avoiding the need to scroll back down every time

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Platform: Windows 10
 - Browser: Chrome
 - Jellyfin Version: 10.6.4

**Comment by Nano0k** [comment]
Still happening in 10.10.3
