### ISSUE TITLE
Feature request: Disable clock/time display on clients

### ISSUE THREAD

**Issue by htpcBeginner** [jellyfin/jellyfin-web#1947]
For folks with sleep issues, an option to disable the display of clock/time on clients would be awesome. 

Most plex clients offer this. I do not see this on Emby.

**Comment by Camc314** [comment]
Are you referring to the Ends At: XX:XX time in the OSD and on the item details page?

**Comment by Camc314** [comment]
Closing - No more info and it is a feature request - please direct to https://features.jellyfin.org/
