### ISSUE TITLE
Research login (hidden?) form input (messing with my password manager auto-login) #Question #Help

### ISSUE THREAD

**Issue by ldexterldesign** [jellyfin/jellyfin-web#1964]
Hi!

Hope you're well

Thanks for invaluable software

What's the (hidden?) login form input for, it's giving my password manager's auto-login headaches?:

<img width="1904" alt="Screenshot 2020-09-30 at 04 41 45" src="https://user-images.githubusercontent.com/1715809/94641841-447b7600-02da-11eb-95df-484f154afa67.png">

Hope to hear back

Sincerely

**Comment by dmitrylyzo** [comment]
(Probably) to disable browser's autocomplete.
https://gist.github.com/runspired/b9fdf1fa74fc9fb4554418dea35718fe
Dunno if it works.

**Comment by ldexterldesign** [comment]
Hi @dmitrylyzo,

Oh god, that gist is depressing, now I remember the hate part of loving front end development

I will run this by my password manager software creators because it's not beyond a culpable use case to ignore hidden inputs but from my perspective (i.e. the owner of my device and installer of my browser and applications, which I would bet money is most JF use cases) please reconsider whether we need this "feature" in JF?

🙏

Hope to hear back

Sincerely
