### ISSUE TITLE
videoOsdBottom vanished after switching video quality or subtitles

### ISSUE THREAD

**Issue by nyanmisaka** [jellyfin/jellyfin-web#1965]
**Describe The Bug**
videoOsdBottom from the [redesigned OSD](https://github.com/jellyfin/jellyfin-web/pull/1825/) vanished after switching video quality or subtitles.

**Steps To Reproduce**
1. Play a movie.
2. Change the video quality to make the play method changed.
     Or choose a PGS graphical sub to enable transcoding.
3. The bottom of OSD vanished once the video get reloaded.
4. Cannot control the playback by using keyboard.

**Expected Behavior**
OSD will not vanish.

**Logs**
Not observed any error in console.

**Screenshots**

![osd-bottom](https://user-images.githubusercontent.com/14953024/94991889-c3adca00-05b8-11eb-862f-8abf83715a39.png)

**System (please complete the following information):**
 - Platform: [Linux, Windows, iPhone]
 - Browser: [Firefox, Chrome, Safari]
 - Jellyfin Version: [10.7.0 unstable 20201002.5]

**Comment by lavanoid** [comment]
This is still a problem for me.

**Comment by dmitrylyzo** [comment]
Issue is from #1951 - I added a call of `hidePrePlaybackPage` for animated background, but it also affects some cases (including described in this issue).
This should be fixed in #1903.
