### ISSUE TITLE
Unchecking `All Libraries` in media deletion settings does not uncheck all the library boxes

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [jellyfin/jellyfin-web#1973]
**Describe The Bug**
Unchecking `All Libraries` in media deletion settings does not uncheck all the library boxes

**Steps To Reproduce**

1. Go to user settings
2. Uncheck `All Libraries` in media deletion settings

**Expected Behavior**
For all of the libraries to become unchecked

**Screenshots**
![image](https://user-images.githubusercontent.com/15848969/95272145-a6256e00-080d-11eb-8caa-5733ae6db5e2.png)

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Chrome Edgium
 - Jellyfin Version: 10.6.4

**Comment by Schtevo66** [comment]
Not sure this is a bug, it works the way I expect it to:
When creating a new account I'll click uncheck all, this then expands a list showing all available libraries allowing my to check or uncheck each individually. yes the default starts with them all selected, but that works for me as it's only the odd one I want to deselect

**Comment by ThatNerdyPikachu** [comment]
> Not sure this is a bug, it works the way I expect it to:
> When creating a new account I'll click uncheck all, this then expands a list showing all available libraries allowing my to check or uncheck each individually. yes the default starts with them all selected, but that works for me as it's only the odd one I want to deselect

Well for me that view is always shown, it doesn't hide or show based on that checkbox. If it did, that would make sense.

So maybe that's the issue at hand here?

**Comment by Schtevo66** [comment]
Sorry, I was looking at the library access not library deletion, but it seems they both work the same way

**Comment by ThatNerdyPikachu** [comment]
> Well for me that view is always shown, **it doesn't hide or show based on that checkbox.** If it did, that would make sense.

So this seems to be the actual bug, hmm.
