### ISSUE TITLE
Live TV is always transcoded

### ISSUE THREAD

**Issue by sprtm** [jellyfin/jellyfin-web#1978]
**Describe The Bug**
Live TV is always transcoded even though codec is supported by the web browser. I'm using TVheadend on a RPi as backend. In Jellyfin I'm using the TVheadend plugin, but the same issue occur with Tuner type set to .m3u or HD Homerun instead of using the plugin. A saved recording of the same channel will play directly in the browser (outside Jellyfin) without issues. Live TV also works if played directly in the TVheadend web GUI.

**Steps To Reproduce**
1. Go to Live TV
2. Click on Channels
3. Click Play on any channel

**Expected Behavior**
Live TV should play direct without transcoding. Since the file can be played directly in the browser without any problems, the codec must be supported.

**Logs**
[log_20201009.copy.log](https://github.com/jellyfin/jellyfin-web/files/5357046/log_20201009.copy.log)
[ffmpeg-transcode-b22be174-0b7d-4459-92c5-66662e9c9846.txt](https://github.com/jellyfin/jellyfin-web/files/5353759/ffmpeg-transcode-b22be174-0b7d-4459-92c5-66662e9c9846.txt)

**Screenshots**
![Screenshot 2020-10-09 at 10 54 41](https://user-images.githubusercontent.com/4703458/95564976-d2b0d400-0a1f-11eb-85f2-6dae46e051cb.png)

**System (please complete the following information):**
 - Platform: macOS 10.15
 - Browser: Safari, Edge, Firefox, Chrome
 - Jellyfin Version: 10.6.4

**Additional Context**
A sample video can be found here: https://www.dropbox.com/s/j963w4tcrwgepwx/Morgonstudion-SVT12020-10-09.ts.zip?dl=0
This is video is recorded with "pass" profile, so the exact same stream as when watching live.

**Comment by topa-LE** [comment]
I have exactly the same problem. With profile "pass" (directstream) Jellyfin transcodes the mpegts stream.

**Comment by sprtm** [comment]
Comment to keep open.

**Comment by riverscn** [comment]
have the same problem

**Comment by andremxmx** [comment]
well, this is not corret but i just delete (change name) of the ffmpeg folder and the channels work grate and fast - this is not the correct way but for testing its grate
