### ISSUE TITLE
Fullscreen on doubleclick

### ISSUE THREAD

**Issue by platinum55** [jellyfin/jellyfin-web#198]
just trigger fullscreen on doubleclick, maybe with an option to disable it, for users who have problems with it.

As a workaround I added this piece of code to videoosd.js around line #1255:

        dom.addEventListener(view, "dblclick", function (e) {
            playbackManager.toggleFullscreen(currentPlayer);
        }, {
            passive: true
        });

This works so far, but sometimes the poster and osd does not hide.. would be cool to have it nicely implemented :)

**Comment by DrPandemic** [comment]
I've been playing around with your snippet and it seems to be working. I'm unable to reproduce your bug where the osd doesn't hide. Which browser are you using? Are you getting this issue on some specific media?

The only thing I would do differently is that I wouldn't bind the event on mobile
```javascript
        if (browser.touch) {
            dom.addEventListener(view, "dblclick", onDoubleClick, {});
        } else {
            dom.addEventListener(view, "dblclick", function () {
                playbackManager.toggleFullscreen(currentPlayer);
            }, {
                passive: true
            });
        }
```

I found only one outside thing that can prevent the osd from hiding and it's the `viewbeforehide` event. But this seems to only be trigger when switching page. A workaround could be to call `startOsdHideTimer()` in the event listener to be sure the timer was not cleared before or during the fullscreen action.

**Comment by platinum55** [comment]
hello mate, I hadn't had the issue again, maybe it disappeared while upgrading from 10.2.2 to 10.3.0 :-) thanks for your enhancement! have a nice day
