### ISSUE TITLE
Duplicate loading animation

### ISSUE THREAD

**Issue by platinum55** [jellyfin/jellyfin-web#199]
when clicking on a movie, there are two loading animations:

http://i.imgur.com/KJkxAGM.png
http://i.imgur.com/dbjqwkz.png

- one from jellyfin
- one from the videoosd I guess

I couldn't find an html element in the player, I think it comes from the videoplayer itself.
Just a cosmetic issue.

**Comment by JustAMan** [comment]
@sparky8251 does this ring a bell from your adventures in fixing the volume control?

**Comment by noah2121** [comment]
+1, same issue here.

**Comment by JustAMan** [comment]
I feel it should be fixed in 10.4.0 release.
@platinum55 or @noah2121 if you see it again please ping us here.
