### ISSUE TITLE
Links in webOS (on LG TV) are not working

### ISSUE THREAD

**Issue by Brice187** [jellyfin/jellyfin-web#1991]
**Describe The Bug**

When opening the link to IMDb rating, a new browser showing a website on the LG TV appears. After some seconds, the native "Connection Error" dialog is displayed. The app freezes and the remote BACK button does not respond. The only solution is to hard kill the app. 

**Steps To Reproduce**

1. Open Movie Library
2. Select Movie and go into Details
4. Click the IMDb-Link below the content abstract (press down button four times)

**Expected Behavior**

Best would be to disable external links for SmartTVs at all (because I do not want to consume websites layouted for a desktop setting on my smart TV)

**Logs**

No logs generated, sry

**Screenshots**

![Step1](https://user-images.githubusercontent.com/2021699/96311864-b22dde80-100a-11eb-9b10-c32f53cbcce6.png)
![Step2](https://user-images.githubusercontent.com/2021699/96311906-cb368f80-100a-11eb-9d38-ff407325edca.png)
![Step3](https://user-images.githubusercontent.com/2021699/96311934-d984ab80-100a-11eb-8de0-c169da4aea36.png)

**System (please complete the following information):**
 - Platform: LG OLED55B8SLC SmartTV  (screen shots taken from webOS Emulator on macOS 10.15.6)
 - Browser: webOS
 - Jellyfin Version: 10.6.4 (Used https://github.com/jellyfin/jellyfin-webos/commit/2427e43fe7f3bfe691c78954c18f2b1ad3e40bb6 to build the .ipk file for my TV/emulator)

**Additional Context**

**Comment by dmitrylyzo** [comment]
Same issue #873 (closed by bot). The easiest way is to not show links at all in TV layout (or TV devices only).

**Comment by MrTimscampi** [comment]
It's already fixed in 10.7: https://github.com/jellyfin/jellyfin-web/blob/master/src/controllers/itemDetails/index.js#L1068-L1071

We're removing external links in the TV layout, as it's doubtful that vendors would allow apps to link to arbitrary websites.

**Comment by dmitrylyzo** [comment]
`Birth place` left: https://github.com/jellyfin/jellyfin-web/blob/6a82956cf46135e44a2a9ad620bcac6118b110f4/src/controllers/itemDetails/index.js#L652-L654
