### ISSUE TITLE
Webapp not respecting LAN playback settings

### ISSUE THREAD

**Issue by mobamoba** [jellyfin/jellyfin-web#200]
**Describe the bug**

In the playback settings on the Web UI, you can have a home network (LAN) speed and an internet speed. The defaults for both are auto. When I changed the LAN speed to 120 mbps 4K and the Internet to 5 mbps, the web player, when playing back across my LAN, played back - and transcoded - everything to 5 mbps, i.e. it ignored the LAN speed setting entirely.
**To Reproduce**

See above.

**Expected behavior**

If you're on a LAN it should play at the LAN speed setting.
**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: Windows 10
 - Browser:  Firefox
 - Jellyfin Version:  10.2.2

**Comment by oddstr13** [comment]
It can be hard to determine whether a remote browser is on the same LAN or connected over the internet.
Some use Jellyfin behind a reverse proxy, which means the remote connected IP will be a local IP even when the actual client is connected over the internet.
Likewise, a VPN tunnel may connect remote computers to the local LAN.

A HTTP header such as `X-JellyfinRemote: 1` could be used to overwrite autodetection in the reverse proxy cause.
A list of rules such as [`192.168.1.2 = remote`, `192.168.1.0/24 = local`, `10.0.0.0/8 = local`] (use first matching) could potentially account for both cases, but only if the reverse proxy is used exclusively for remote connections.

Just something to keep in mind while implementing a fix for this issue.
