### ISSUE TITLE
display language broken in 10.6.4

### ISSUE THREAD

**Issue by steathy** [jellyfin/jellyfin-web#2008]
**Describe The Bug**
display language function broken. it does not change no matter what language I choose.

**Steps To Reproduce**
1. Go to Dashboard -> General
2. Click on Preferred display language
3. Scroll down to any of them. Then apply changes
4. Display language does not change. Only the language in Activity part changes. like "xxxx is online from chrome" "xxxxx has disconnected from Chrome". Those do change after choosing different languages.

**System (please complete the following information):**
 - Platform: Unraid/Synology docker
 - Browser: Chrome, Firefox
 - Jellyfin Version: 10.6.4

**Comment by ThibaultNocchi** [comment]
This doesn't work because the language is managed by the setting in Settings -> Display -> Display language. Modifying it and refreshing should apply the chosen language even in the admin panel.

Though I don't know what the setting in admin is supposed to do.
