### ISSUE TITLE
Changing "Display Language" to Japanese does not work.

### ISSUE THREAD

**Issue by minobp** [jellyfin/jellyfin-web#2020]
**Describe The Bug**
If the `Display Language` is changed to Japanese, it will still be displayed in English.

**Steps To Reproduce**

1. Go to Display setting
2. Select `Japanese ` in Display language setting
3. Click the save button
4. Page reload

**Expected Behavior**
Display will be in Japanese.

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Firefox, Chrome
 - Jellyfin Version: 10.6.4 , 10.7.0

**Comment by targor** [comment]
I can confirm this..
System:
Server: Docker-> newest jellyfin
Client: Windows 10, Fiorefox newest version, and also Chrome newest version.
