### ISSUE TITLE
login page shows user names to public http clients

### ISSUE THREAD

**Issue by meonkeys** [jellyfin/jellyfin-web#2042]
**Describe The Bug**
Inside my local network I use easy PIN log-ins and unhidden users for the handy "click myself to play" functionality in Jellyfin (similar to netflix, amazon prime video, plex, etc). Away from home, my server still shows profile pictures and usernames for any user.

**Steps To Reproduce**
1. Access server public URL from outside local subnet
2. Go to log in page
3. See all user profile pictures and usernames

**Expected Behavior**
Usernames and profile pictures are not shown. Only manual login is allowed from a non-local client IP address.

**Logs**
n/a

**Screenshots**
![login](https://user-images.githubusercontent.com/50639/98433532-d1a1af80-207c-11eb-826b-0797d3b681ee.png)

**System**
 - Platform: Linux ([Docker](https://hub.docker.com/r/linuxserver/jellyfin), behind traefik reverse proxy)
 - Browser: Firefox
 - Jellyfin Version: 10.6.4

**Additional Context**
I marked this as a bug and not a feature request because of the security considerations for leaking usernames.

**Comment by cvium** [comment]
I get what you're saying, but it's not a bug. Feel free to create a feature request and/or a PR.

**Comment by meonkeys** [comment]
Ok! Done. Thank you for your reply and thank you that Jellyfin is so awesome.

https://features.jellyfin.org/posts/931/hide-usernames-and-profile-pictures-when-connecting-from-a-non-local-ip-address
