### ISSUE TITLE
The header for Collections in the Favorites menu says HeaderFavoriteCollections

### ISSUE THREAD

**Issue by n8detar** [jellyfin/jellyfin-web#2045]
**Describe The Bug**
The header for Collections in the Favorites menu says HeaderFavoriteCollections rather than Favorite Collections. I couldn't find it reported anywhere but wouldn't be surprised if it has been.

**Steps To Reproduce**
1. Go to Home.
2. Click on Favorites.
3. Scroll down to the bottom.

**Expected Behavior**
The header is likely supposed to say Favorite Collections.

**Screenshots**
![image](https://user-images.githubusercontent.com/24966292/98454373-a79dcb00-2118-11eb-9674-b875d9f4ae03.png)

**System (please complete the following information):**
 - Platform: Linux (Unraid), Docker (linuxserver/jellyfin)
 - Browser: Firefox, Chrome
 - Jellyfin Version: 10.6.4

**Comment by Artiume** [comment]
Fixed in Unstable
