### ISSUE TITLE
Switching tabs with the keyboard skips chapters in the video

### ISSUE THREAD

**Issue by RealOrangeOne** [jellyfin/jellyfin-web#2056]
**Describe The Bug**

When using the keyboard to switch to specific tabs (in Firefox alt + num), the video skips to chapters (or at least I think it's chapters). This is the same as without the alt key.

**Steps To Reproduce**
1. Play a video
2. Open a new tab
3. Switch back to jellyfin tab
4. Switch to new tab with keyboard using alt + num shortcut (eg alt + 2)
5. Notice video has jumped, but tab has also switched

**Expected Behavior**

The tab should still switch, but video playback should be unaffected

**Logs**
 
N/A

**Screenshots**

N/A

**System (please complete the following information):**
 - Platform: Docker on Ubuntu [compose file](https://github.com/RealOrangeOne/infrastructure/blob/master/ansible/roles/intersect_docker/files/jellyfin/docker-compose.yml)
 - Browser: Firefox 82.0.2 on Linux
 - Jellyfin Version: 10.6.4-1

**Comment by dmitrylyzo** [comment]
I think this is fixed by #1697, but it goes for 10.7

**Comment by RealOrangeOne** [comment]
That definitely looks like my issue. Once 10.7 comes out i'll test this and close
