### ISSUE TITLE
No subtitles played ONLY on Jellyfin webplayer

### ISSUE THREAD

**Issue by Jhyrachy** [jellyfin/jellyfin-web#2057]
**Describe The Bug**
Watching a video with subtitles (included inside the mkv file) does not reproduce them, even if they are shown inside the subtitles selector.  
Subtitles are properly visible on jellyfin android app or using vlc with the stream url

**Media Information**
https://pastebin.com/raw/TujHduDS
(pastebin link since copypasting will destroy the layout)

**Screenshots**
![immagine](https://user-images.githubusercontent.com/5394678/98682893-bb3d7180-2364-11eb-8083-8cdac22eafb4.png)

**System (please complete the following information):**
 - Server: Centos8
 - Player: Windows 10
 - Browser: Firefox 82.0.3
 - Jellyfin Version: 10.6.4

**Comment by itshoro** [comment]
They *do* display after a while for me. It seems like a loading issue.

**Comment by Visne** [comment]
Can confirm they also load after a long while for me. Don't know about fonts, it's happening with .srt subs for me and I don't think .srt supports fonts.

**Comment by Visne** [comment]
This was fixed for me by disabling "Allow subtitle extraction on the fly".

**Comment by Visne** [comment]
Still affects me.

**Comment by Azerom** [comment]
Affect me too. Only on video with embedded sub and only on the web player (work fine on android or with MPV Shim)
I notice that if you go back and play the episodes again the subtitles seem to load instantaneously.
Server: Debian 10
Browser: Firefox 93.0
Jellyfin Version: 10.7.7
Not sure if this is related but my server does not have hardware acceleration.

**Comment by WTechNinja** [comment]
One of my friends had this same problem (on his Ubuntu Server), but he also couldn't select which audio track to play, and it was a major pain. I have my own server and it was working fine so I compared settings and realized his server didn't have ffmpeg installed. If anyone here still has this bug you might want to check that...
