### ISSUE TITLE
Some shortcuts dont work after putting video in full screen (space for play/pause for example) 

### ISSUE THREAD

**Issue by alex9099** [jellyfin/jellyfin-web#2058]
**Describe The Bug**
When pressing space to play pause the video nothing happens after double clicking for full screen (when going to "windowed" same happens). "k" works every time though

**Steps To Reproduce**
1. Start a Video
2. Double click for full screen
3. Try pausing with "space" key
4. Nothing happens

**Expected Behavior**
"space" key should play/pause the media in every condition

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Firefox 82.0.2
 - Jellyfin Version: 10.6.4

**Additional Context**
Not entirely sure if the only trigger for it not to work is full screen. It seems to not work "on will"

**Comment by dmitrylyzo** [comment]
Have you waited until OSD disappears?

**Comment by alex9099** [comment]
Nope, seems like as soon as the OSD disapears the "space" shortcut starts working again

**Comment by dmitrylyzo** [comment]
This is known behavior.
https://github.com/jellyfin/jellyfin-web/blob/50cc30738eb7f679511603b4510e98e1b6fa3c7f/src/controllers/playback/video/index.js#L1029
^ this handles `Space` only when OSD is hidden. A possible reason for this is that `Space` performs `click` on focused button. TV layout uses keyboard navigation and focus is important for that. Other layouts don't use keyboard navigation, but focus is still there (just no marker).

This behavior can probably be fixed for Desktop and Mobile if focus problem is solved.
