### ISSUE TITLE
General TMDB api issues for tv shows.

### ISSUE THREAD

**Issue by Darkwolf1515** [jellyfin/jellyfin-web#2060]
**Describe The Bug**
Overall api issues, it will not find season images, only general show images. and all seasons are the name of the show, rather than season 1, 2, ect.

**Steps To Reproduce**
Set TMDB as your provider for everything in a tv show library.
Witness that it fails to find season images, and names all your seasons the show 
**Expected Behavior**
Season images to be found, seasons named properly. 

**Screenshots**

![image](https://user-images.githubusercontent.com/65789901/98799771-73bbf180-2407-11eb-86c5-2613d15417fe.png)
![image](https://user-images.githubusercontent.com/65789901/98799793-7cacc300-2407-11eb-8a7a-1424106dacf9.png)
![image](https://user-images.githubusercontent.com/65789901/98799855-9221ed00-2407-11eb-8d2d-ec75f1edb64a.png)
![image](https://user-images.githubusercontent.com/65789901/98799885-9b12be80-2407-11eb-80e2-647961aefc1b.png)

**System (please complete the following information):**
 - Platform: Docker
 - Browser: Firefox
 - Jellyfin Version: 10.6.4

**Additional Context**

Yes my library does show the season images, but that's cause I manually added them. I am also unaware if this is a Jellyfin issue, or if just TMDB's api doesn't yet account for season images and ect. This might be a better fit as a server issue but it may also just be a display issue with the web client.

**Comment by cvium** [comment]
Did you make sure to enable TMDB for season images? It's in Advanced settings in the library options.
![image](https://user-images.githubusercontent.com/675118/98801361-ff3a8000-2411-11eb-98f4-94d52bcd5eb7.png)

**Comment by Darkwolf1515** [comment]
Yes. 
![image](https://user-images.githubusercontent.com/65789901/98802848-ceefe300-240b-11eb-9f36-fa92019ce111.png)

**Comment by Darkwolf1515** [comment]
It seems that the season part is being fixed, i saw that in the 1.70 projects, but not the covers.

**Comment by Darkwolf1515** [comment]
Still an issue
