### ISSUE TITLE
Cant turn off image providers.

### ISSUE THREAD

**Issue by Darkwolf1515** [jellyfin/jellyfin-web#2062]
**Describe The Bug**
After TVDB's, questionable choices, I decided to remove them all together as a metadata provider, despite me having unchecked them across all my libraries, their images are still downloaded, and show up as a download option.

**Steps To Reproduce**
Turn off tvdb as a provider
Remove the match from the show
Refresh metadata
See that it has rematches with tvdb and shows its images
**Expected Behavior**
TVDB to leave and never come back.

**System (please complete the following information):**
 - Platform: Docker
 - Browser: Firefox
 - Jellyfin Version: 10.6.4
**Additional Context**
Man, I cant wait till tvdb is gutted from core and made its own optional addon.

**Comment by thornbill** [comment]
In 10.6.4 (and lower) in addition to needing to disable the metadata provider, you need to select the "advanced options" toggle in the edit library dialog and disable it as an image provider.

The advanced toggle will be removed in 10.7 since there's nothing really advanced about those settings. :wink:

**Comment by Darkwolf1515** [comment]
I did that.

**Comment by dkanada** [comment]
@Darkwolf1515 I agree, I don't personally use any of the providers, which is why I've been pushing so hard to get them removed from the main release.

**Comment by Darkwolf1515** [comment]
> 
> 
> @Darkwolf1515 I agree, I don't personally use any of the providers, which is why I've been pushing so hard to get them removed from the main release.

Thankfully your pushing has seemed to work, love the fact that in 10.7 tvdb is an addon.

**Comment by dkanada** [comment]
It's only a plugin by chance in this release, although I think that we might get them all by the next major update.

**Comment by Darkwolf1515** [comment]
> 
> 
> It's only a plugin by chance in this release, although I think that we might get them all by the next major update.

Well I'm happy whenever it comes, removing it from my installation will be the best form of revenge, the petty kind.
