### ISSUE TITLE
Slideshow arrow Navigation

### ISSUE THREAD

**Issue by nerxses** [jellyfin/jellyfin-web#2068]
Currently you guys disable Arrowkey Navigation for non TV-Displays aka. Desktop or Mobile. This takes place in the JS-File keyboardnavigation.js inside "/components/input/". This is the code i found there 

            // Ignore navigation keys for non-TV
            if (!layoutManager.tv && isNavigationKey(key)) {
               return;
            }
This takes me to my Question. Why? 
It so much better to sit on his PC and scroll via your arrow keys through your Pictures because the slideshow itself is either to slow to fast or you wanna go back easily. 
I thought about the reasons, but i cannot find a good one. Can you please enlighten me:)

**Comment by dmitrylyzo** [comment]
`Swiper` should handle arrow keys by itself, iirc

**Comment by MrTimscampi** [comment]
> `Swiper` should handle arrow keys by itself, iirc

It does, the keyboardnavigation file and Swiper have different events bound. I can browse pictures just fine with the arrow keys.

@nerxses Are you somehow unable to navigate a photo slideshow with your keyboard?

**Comment by nerxses** [comment]
ok for me it only works with this lines commented out... strange

**Comment by dmitrylyzo** [comment]
Is it still valid?
Because it is works on Firefox 91, Chrome 92.
