### ISSUE TITLE
Items on the bottom of the page are overlapped by controls

### ISSUE THREAD

**Issue by TwizzyDizzy** [jellyfin/jellyfin-web#208]
**Describe the bug**
Margin to the bottom of the web UI is not enough, as items are overlapped by the controls.

**To Reproduce**
* Open a list of albums/tracks
* scroll to the bottom
* play a tune

**Expected behavior**
More space, so the control bar doesn't overlap the items at the bottom of the page

**Logs**
-

**Screenshots**
![Screenshot from 2019-03-24 18-41-05](https://user-images.githubusercontent.com/179595/54883634-f4f7f680-4e67-11e9-864e-ee1af2966380.png)

**System (please complete the following information):**
 - OS: Jellyfin Server: Raspbian Stretch, Client OS: Debian Stretch
 - Browser: Chromium, Firefox
 - Jellyfin Version: 10.2.2

**Additional context**
-

**Comment by xevidos** [comment]
Does changing the .pageTabContent .is-active padding-bottom from 2em to 5em show all the necessary items?  This seemed to bump the page length enough to fit everything nicely for me.

**Comment by daves00** [comment]
This bug also occurs when you use the web interface, connect to a remote DLNA device and the controls show. A simple workaround is to disconnect from the remote device so the controls disappear. Hopefully the same fix will resolve both issues :). I'll try tweaking the spacing as per the above comment when i next have a chance.

**Comment by dkanada** [comment]
@xevidos I fixed the issue with your suggestion above, seems like the best option for now.

**Comment by TwizzyDizzy** [comment]
Fix lookin' good. Thx @dkanada and @xevidos 😘

Cheers
Thomas
