### ISSUE TITLE
ASS subtitle begin with {...} can not be loaded in video

### ISSUE THREAD

**Issue by swhoro** [jellyfin/jellyfin-web#2081]
**Describe The Bug**

![image](https://user-images.githubusercontent.com/34229589/99513313-7305fb00-29c5-11eb-8e69-08378b99d8e4.png)
For example, from line 27 to 48, text starts with {\fad(200,300)\be1} or {\fad(500,500)\be1\an8} will not be loaded in the video. 
If I delete all the text in {...} and {}, those subtitles can be loaded correctly.
However, line 48 can display correctly.

**Steps To Reproduce**

check hardware acceleration(NVENC)
check "Allow subtitle extraction on the fly"
check "Enable fallback fonts", fallback font folder path is "D:\jellyfin_20201118.1\Resources\fonts"
![image](https://user-images.githubusercontent.com/34229589/99514520-d04e7c00-29c6-11eb-9ac8-de6917525952.png)
set "Preferred subtitle language:" to "Chinese"
set "Subtitle mode:" to "Smart"
set "Burn subtitles:" to "Auto"

**Expected Behavior**

Subtitles starting with {...} can be loaded correctly.

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Platform: Windows 10 20H2 (19042.630) Nvidia driver 457.30
 - Browser: chrominum edge  86.0.622.69
 - Jellyfin Version: unstable jellyfin_20201118.1

**Additional Context**

I have another ass file:
![image](https://user-images.githubusercontent.com/34229589/99516350-0987eb80-29c9-11eb-8ff4-bc4570501674.png)
These subtitles with {...} can be displayed correctly.

**Comment by nyanmisaka** [comment]
I think this might be an upstream issue from [JavascriptSubtitlesOctopus](https://github.com/Dador/JavascriptSubtitlesOctopus).
As we pass the plain SSA/ASS file to this renderer, can you file an issue to them?

**Comment by swhoro** [comment]
> I think this might be an upstream issue from [JavascriptSubtitlesOctopus](https://github.com/Dador/JavascriptSubtitlesOctopus) as we pass the plain SSA/ASS file to this renderer.
> 
> Can you file an issue to them? Thanks.

ok

**Comment by ThaUnknown** [comment]
this is an issue with the font file, subtitle octopus doesnt have a good font fallback and the file you played it back on probably didint include an embedded font file at all, it's an issue with the file and not jellyfin/S.O.
