### ISSUE TITLE
(Unstable) Unable to uninstall plugins

### ISSUE THREAD

**Issue by BaronGreenback** [jellyfin/jellyfin-web#2084]
Chrome Version 86.0.4240.198 (Official Build) (64-bit)

js error when clicking uninstall
![image](https://user-images.githubusercontent.com/22121540/99700513-300e5b00-2a8b-11eb-89a3-9dd642e80a59.png)

index.js?v=19:formatted:144 Uncaught (in promise) TypeError: _ref.default.default is not a function at index.js?v=19:formatted:144

\src\controllers\dashboard\plugins\installed\index.js - deletePlugin,

![image](https://user-images.githubusercontent.com/22121540/99700990-cb073500-2a8b-11eb-866c-a047334440f2.png)

**Comment by thornbill** [comment]
Should have been fixed by #1994
