### ISSUE TITLE
[Unstable] Cannot mark content played from Home Page

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-web#2087]
I can mark content played and unplayed from within the Library but not the home page. Library type is `Other`

Also noticing that content is disappearing from the Latest Section if it is marked played. This shouldn't be happening.

**Comment by Artiume** [comment]
Uncaught (in promise) 
Response { type: "basic", url: "https://domain/Users/uuid?DatePlayed=20201120031138", redirected: false, status: 400, ok: false, statusText: "Bad Request", headers: Headers, body: ReadableStream, bodyUsed: false }

**Comment by thornbill** [comment]
I get the same error in the library pages also. Possibly a server side bug.

Marking as unwatched seems to work as expected.
