### ISSUE TITLE
Music Stop Button Missing on less than 80em

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-web#2099]
Firefox ESR (using v78) is missing the music stop button. Tested on both 10.6.4 and Unstable, both have the issue.

![test](https://user-images.githubusercontent.com/20715731/99904060-987d5800-2c96-11eb-8499-d5ce9cd23641.png)

looks like the issue is 80em. we could probably reduce it to 60-65em

https://github.com/jellyfin/jellyfin-web/blob/26fb54ce9ba58d00ea9cf44b2ed27969343cab7b/src/components/nowPlayingBar/nowPlayingBar.css#L140-L144

**Comment by thornbill** [comment]
Is it not included in the “...” menu?

**Comment by Artiume** [comment]
nope. I am unable to stop the music.

![test](https://user-images.githubusercontent.com/20715731/102495155-c199ca00-4043-11eb-88d7-6b61fd4821ca.png)
