### ISSUE TITLE
Playback Error | This client isn't compatible with the media and the server isn't sending a compatible media format.

### ISSUE THREAD

**Issue by hwittenborn** [jellyfin/jellyfin-web#2112]
**Describe The Bug**
When attempting to play any MP3 files, the error listed in the title appears. 

**Screenshots**

![image](https://user-images.githubusercontent.com/74838472/100019697-1bd89f80-2da4-11eb-869e-e33d99d78483.png)

**System (please complete the following information):**
 - Platform: Ubuntu 20.10
 - Browser: Firefox 83.0
 - Jellyfin Version: 10.6.4

**Additional Info**
Also happens in the iOS app; haven't tested with any other clients

**Comment by joshuaboniface** [comment]
This sounds ike a transcoding error - are there any logs from the Jellyfin server or FFMpeg for the failure?

Also [yay 2112](https://www.youtube.com/watch?v=AZm1_jtY1SQ).

**Comment by hwittenborn** [comment]
I’ll have to look at them tomorrow or so, my server’s off right now while I’m running some bandwidth tests

**Comment by hwittenborn** [comment]
Update: Server at my house is using to much bandwidth with all the stuff I have on it(ISP has caps), I'm just shutting the whole thing down. Consider this closed, I'll try again in the future.
