### ISSUE TITLE
Direct Playback broken in Chrome 73

### ISSUE THREAD

**Issue by tbraeutigam** [jellyfin/jellyfin-web#213]
**Describe the bug**
Direct Playback fails on Chrome 73 (not Firefox 66) on Ubuntu Linux when using master (as of commit 072f4a3cf96dea260304d4e8d1c187d9f6b8b27b )

**To Reproduce**
Start a video file that contains `SupportsDirectPlay: true`

**Expected behavior**
Video plays in browser

**Logs**

Chrome logs `Uncaught (in promise) TypeError: Cannot read property 'then' of undefined` in `playbackmanager.js` and goes to this function:
```javascript
                        filesystem[method](mediaSource.Path).then(function () {
                            resolve(true);
                        }, function () {
                            resolve(false);
                        });
```

`filesystem[method]` in this case refers to the following from `filesystem.js`:
```javascript
        fileExists: function (path) {
            if (window.NativeShell && window.NativeShell.FileSystem) {
                return window.NativeShell.FileSystem.fileExists(path);
            }
        }
```
The `mediaSource` object logs as follows:

```
Bitrate: 5774139
Container: "mkv"
DefaultAudioStreamIndex: 1
ETag: "a36717f915cf8441e3f8e6d8bf9ae3f6"
Formats: []
GenPtsInput: false
Id: "2a0b7d9bd084c5a1881799e966d15e4f"
IgnoreDts: false
IgnoreIndex: false
IsInfiniteStream: false
IsRemote: false
MediaStreams: Array(2)
0: {Codec: "h264", TimeBase: "1/1000", CodecTimeBase: "1001/48000", Title: "Title", VideoRange: "SDR", …}
1: {Codec: "flac", Language: "jpn", TimeBase: "1/1000", CodecTimeBase: "1/48000", Title: "LPCM 4.0 -> flac", …}
length: 2
__proto__: Array(0)
Name: "Video Name"
Path: "/path/to/video.mkv"
Protocol: "File"
ReadAtNativeFramerate: false
RequiredHttpHeaders: {}
RequiresClosing: false
RequiresLooping: false
RequiresOpening: false
RunTimeTicks: 37657649152
Size: 2718006272
SupportsDirectPlay: true
SupportsDirectStream: true
SupportsProbing: true
SupportsTranscoding: true
Type: "Default"
VideoType: "VideoFile"
__proto__: Object
```

**Client System:**
 - OS: Ubuntu Linux
 - Browser: Chrome 73
 - Jellyfin Version: 10.2.2
 - Jellyfin-web Version: master - 072f4a3cf96dea260304d4e8d1c187d9f6b8b27b

**Server System:**
 - OS: Ubuntu Linux
 - Jellyfin Version: 10.2.2
 - Jellyfin-web Version: master - 072f4a3cf96dea260304d4e8d1c187d9f6b8b27b

**Comment by thornbill** [comment]
It looks like we aren't properly handling the case where `window.NativeShell` does not exist in `filesystem.js`. We should always return a `Promise there`. I believe this change should fix it.

```js
        fileExists: function (path) {
            if (window.NativeShell && window.NativeShell.FileSystem) {
                return window.NativeShell.FileSystem.fileExists(path);
            }
            return Promise.reject();
        }
```

@dkanada or @vitorsemeano does one of your open PRs address this?

**Comment by dannymichel** [comment]
Are we sure this has been fixed? I'm getting this error
