### ISSUE TITLE
Plugin installation notification says `version [object Object]` instead of the version

### ISSUE THREAD

**Issue by strugee** [jellyfin/jellyfin-web#2134]
**Describe The Bug**

Basically, what the title says. This is the notification that appears when plugins have been successfully installed, to be clear.

**Steps To Reproduce**

0. Make sure Jellyfin has permission to send browser notifications
1. Go to the plugins page in the admin area
2. Click on "Catalog" then a plugin, then "Install"
3. Wait a second or two for the notification to pop up
4. Notice that the notification text says: "<plugin name> (version [object Object]) installation completed."

**Expected Behavior**

The notification says:

> <plugin name> (version <version>) installation completed.

**Logs**

Nothing interesting in the JS console.

**Screenshots**

I can post some if really necessary, but it's a bit annoying atm since I'm composing this issue on my phone.

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Firefox
 - Jellyfin Version: 10.6.4

**Additional Context**

N/A

**Comment by crobibero** [comment]
Should be fixed by https://github.com/jellyfin/jellyfin/pull/4517
