### ISSUE TITLE
Navigating to show from "Continue Watching"

### ISSUE THREAD

**Issue by Anaphylaxis** [jellyfin/jellyfin-web#2136]
It's currently not possible to go from the "Continue Watching" -> Show Name, Season X - Y -> back to the show, there is no way to get from this page to the actual show, meaning to change episode not in the same season (More from Season X is there), you have to back out and choose "TV Shows" and find your TV Show.

**Comment by dmitrylyzo** [comment]
Title and season links have `tabindex="-1"`, so they are non-navigable.
