### ISSUE TITLE
PluginManager fails to load classes

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-web#2157]
**Describe The Bug**

At this line:
https://github.com/jellyfin/jellyfin-web/blob/db6391c6c130839f96463459b5eece236ee77339/src/components/pluginManager.js#L79

We should also check if the property is a class, if it is a class it should **not** await.

It would also be great if the catch statement on this line:

https://github.com/jellyfin/jellyfin-web/blob/75b7b4d7a70c28fc519b56e1a95d4e87537733f0/src/scripts/site.js#L145

Would log the actual error, right now debugging plugins is a PITA because all errors are hidden...

**Comment by thornbill** [comment]
@nielsvanvelzen you are talking about the `await` on this line not the earlier one right?

https://github.com/jellyfin/jellyfin-web/blob/db6391c6c130839f96463459b5eece236ee77339/src/components/pluginManager.js#L80

**Comment by nielsvanvelzen** [comment]
Yup that one, if a function is returned it _might_ be async or return a promise so we want to always `await` it. (if it's not a promise/async it will resolve just fine). But in the case that a class is returned we do not want to call it as a function because that is illegal in JavaScript (need to use the `new` keyword for classes).

**Comment by thornbill** [comment]
I think we can just always use the `new` keyword here since it isn't trivial to determine if a variable is a Class vs a Function https://stackoverflow.com/questions/30758961/how-to-check-if-a-variable-is-an-es6-class-declaration

**Comment by nielsvanvelzen** [comment]
![image](https://user-images.githubusercontent.com/2305178/100925811-ce1a1080-34e2-11eb-8dc9-cecd4fb02169.png)

Adding the `new` keyword should indeed work.

**Comment by nielsvanvelzen** [comment]
Since I'm using functions now for jellyfin-android we could just not support exposing the class directly but I think it's nice to have as an option.
