### ISSUE TITLE
Dashboard theme option is gone in 10.7

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-web#2189]
**Describe The Bug**
In 10.6 there were two theme options; one for the dashboard and one for everything else. The option to set a theme for the dashboard only is gone in 10.7.

**Steps To Reproduce**

1. Go to display settings
2. Notice the dashboard option is gone

**Expected Behavior**
I should be able to use a separate theme for both the dashboard and everything else.

**Logs**
Not relevant

**Screenshots**
![image](https://user-images.githubusercontent.com/2305178/101279527-30189580-37c3-11eb-8761-89ccf4738e09.png)

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Vivaldi (chromium)
 - Jellyfin Version: 10.7.0~rc1

**Additional Context**
This feature was available since always and when discussed before in the Matrix chats to remove it we determined to not do that. So I'm not sure why it's gone now.

**Comment by MrTimscampi** [comment]
@dkanada It was removed as part of #1502
