### ISSUE TITLE
10.7.2 uses a very low resolution for images in "next up" home section.

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-web#2191]
**Describe The Bug**
![image](https://user-images.githubusercontent.com/2305178/101282866-be971200-37d7-11eb-8111-dc665b449829.png)
Crispy high resolution image. All other sections work fine.

The HTTP request to the image uses this url:
`https://jellyfin/Items/895ed51c4c595d404855abcc06d81d11/Images/Backdrop?maxWidth=355&tag=61a4233cbf0e9cde73d1b8933c4fcb19&quality=80`

The returned image is 355x75. Which is totally wrong.
![image](https://user-images.githubusercontent.com/2305178/101282953-2d746b00-37d8-11eb-9ba7-8ae56d4357b1.png)

**Comment by oddstr13** [comment]
I think we would want a `fitBox=#x#` parameter instead of `maxWidth=#`.

Resize to touch the outside of bounding box provided, instead of `maxHeigh` / `maxWidth` which resizes to touch the inside of the bounding box.

This is not the only instance of this problem: another instance where this can be seen is when the primary image (boxart) has a unexpected aspect ratio (16:9).

**Comment by oddstr13** [comment]
Intended behavior, followed by actual behavior when aspect ratio doesn't match
![image](https://user-images.githubusercontent.com/638706/101296091-d1363900-3821-11eb-9015-694f75e854d7.png)

**Comment by nielsvanvelzen** [comment]
jellyfin-web should send the server the minimum width and height and the server could then resize according to those parameters. Sending the "preferred" width or height will always end up creating a low res picture.
I'm not sure if the API supports this resizing method.

**Comment by oddstr13** [comment]
This regression is caused by the removal of a hack in jellyfin/jellyfin-web#1710.
The provided sample would've still had some visual artifacts with the hack in place, since the image has a very wide aspect ratio, but probably not nearly as noticeable as it is now.

**Comment by nielsvanvelzen** [comment]
In 10.7.2 the URL changed from:

https://jellyfin/Items/895ed51c4c595d404855abcc06d81d11/Images/Backdrop?maxWidth=355&tag=61a4233cbf0e9cde73d1b8933c4fcb19&quality=80

To:

https://jellyfin/Items/895ed51c4c595d404855abcc06d81d11/Images/Backdrop?fillWidth=355&tag=61a4233cbf0e9cde73d1b8933c4fcb19&quality=80

The maxWidth parameter became fillWidth, the resulting image is still the same as in the issue and the bug is not fixed for me.
