### ISSUE TITLE
Edit notitification settings 404

### ISSUE THREAD

**Issue by crobibero** [jellyfin/jellyfin-web#2235]
**Describe The Bug**

**Steps To Reproduce**

1. Go to Notification management
2. Click on any notification type
3. 404

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Firefox
 - Jellyfin Version: master

**Additional Context**

Opens to http://localhost:8096/jellyfin/web/notificationsetting.html?type=ApplicationUpdateAvailable 

instead of http://localhost:8096/jellyfin/web/index.html#!/notificationsetting.html?type=ApplicationUpdateAvailable

When opening the link in a new tab- the correct page is loaded in the current tab, the incorrect page is loaded in a new tab

Reported in +jellyfin:matrix.org

**Comment by thornbill** [comment]
This has been fixed in unstable. Should be good in the next RC.
