### ISSUE TITLE
Prepare script does not work on Windows

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-web#2241]
Yarn will automatically run the `prepare` task when `yarn install` is executed without the `--no-scripts` argument. This is no problem in Posix environments but on Windows it tries to open the .sh file with the editor of preference.
This makes it annoying and bothersome to develop jellyfin-web on Windows.

The simple solution is to not run a platform tied script in the package.json by changing it to a NodeJS script or just remove it entirely.

**Comment by thornbill** [comment]
Should be fixed by #2242
