### ISSUE TITLE
Remote control broken 

### ISSUE THREAD

**Issue by Darkwolf1515** [jellyfin/jellyfin-web#2245]
**Describe The Bug**
Trying to remote control my Firefox session from my iPhone, while I can start content, I cannot control it.

**Steps To Reproduce**
1. Start a remote control session (in app or browser)
2. Start a song, see that you can’t pause it, seek, stop it, ect.

**Expected Behavior**
To have control.

**System (please complete the following information):**
 - Platform: iOS, Docker
 - Browser: Firefox 
 - Jellyfin Version: 10.7-RC1

**Comment by nyanmisaka** [comment]
I can confirm these not only on iOS but also other devices.

**Comment by Darkwolf1515** [comment]
> I can confirm these not only on iOS but also other devices.

Gotcha, I’ll change the title.

**Comment by thornbill** [comment]
This appears to be an issue with inconsistent user id formatting.

Should be fixed by https://github.com/jellyfin/jellyfin/pull/4749

**Comment by nyanmisaka** [comment]
That didn't help. It's still broken in master.
