### ISSUE TITLE
[10.7] Videos with odd number of audio channels not playing on browsers and other devices

### ISSUE THREAD

**Issue by TheNamelessWonderer** [jellyfin/jellyfin-web#2249]
**Describe The Bug**
Certain files will not play in Firefox.

**Steps To Reproduce**

1. Update to 10.7 unstable
2. Click on the movie to play it
3. Open browser console

**Expected Behavior**

The file should play without any errors.
**Logs**
The error is: `HLS Error: Type: mediaError Details: bufferAppendingError Fatal: false` followed by `Uncaught DOMException: An attempt was made to use an object that is not, or is no longer, usable`

**Screenshots**

![image](https://user-images.githubusercontent.com/56267607/102714102-675b6c00-42c4-11eb-933b-1473497704ca.png)

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Firefox
 - Jellyfin Version: 10.7.0 Latest unstable 20 December

**Additional Context**

The file does transcode in FFMPEG correctly but the browser won't load the file. It also plays in macOS Safari but at a very slow speed and with lots of stuttering. Other files play without any errors at all on both Firefox and macOS Safari.

**Comment by TheNamelessWonderer** [comment]
The file also won't play on iPadOS Safari but seeing as it has no console I can't see the error message.

**Comment by Artiume** [comment]
Does ffmpeg transcode it to 8bit or does it maintain 10bit color matrix?

**Comment by TheNamelessWonderer** [comment]
This is what it is using:
```
-map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -pix_fmt yuv420p -preset veryfast -crf 23 -maxrate 8755223 -bufsize 17510446 -profile:v:0 high -level 41 -x264opts:0 subme=0:me_r
ange=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none  -force_key_frames:0 "expr:gte(t,0+n_forced*3)" -vf "scale=trunc(min(max(iw\,ih*dar)\,min(1920\,1080*dar))/2)*2:trunc(min(max(iw/dar\,ih)\,min(1920/dar\,1080))/2)*2" -sta
rt_at_zero -vsync -1 -codec:a:0 aac -ac 3 -ab 384000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/Users/user/.loca
l/share/jellyfin/transcodes/f076e7946c5d27f17638e7f7bfe5c904%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/Users/user/.local/share/jellyfin/transcodes/f076e7946c5d27f17638e7f7bfe5c904.m3u8"
```

**Comment by nyanmisaka** [comment]
Can you set the max audio channel to stereo in playback settings and try again?

**Comment by TheNamelessWonderer** [comment]
Yep that fixes it on firefox!

**Comment by nyanmisaka** [comment]
Seems that Apple doesn't like odd number of channels.

**Comment by TheNamelessWonderer** [comment]
I'm using firefox on Linux which also has the issue. However setting it to stereo has also fixed it on iPadOS and iOS running 14.3!

**Comment by nyanmisaka** [comment]
We may need to avoid transcoding audio to odd number of channels.

BTW can you try to enable the fMP4-HLS option on the iPad so that FLAC 3ch can be remuxed?

**Comment by TheNamelessWonderer** [comment]
How do I enable that?

**Comment by nyanmisaka** [comment]
At the bottom of the audio channel page.

I know that FLAC 2ch and 5.1ch can work normally on iPad.

**Comment by TheNamelessWonderer** [comment]
Setting audio channels back to audio and enabling fMP4-HLS video doesn't play. Setting it to Stereo and fMP4-HLS video does play correctly although it says the audio codec is AAC not FLAC.

**Comment by nyanmisaka** [comment]
Can you set a bitrate limit as large as possible?

**Comment by TheNamelessWonderer** [comment]
At max bitrate and stereo it is still transcoded to AAC.

**Comment by nyanmisaka** [comment]
The lack of bitrate information for this FLAC audio track led to audio transcoding.

**Comment by TheNamelessWonderer** [comment]
Unfortunately every episode is missing bitrate information it seems.

**Comment by nyanmisaka** [comment]
`Search for missing metadata` can be helpful here. I have added better bitrate probing for FLAC in 10.7.

**Comment by TheNamelessWonderer** [comment]
I have tried that but it is still missing.

**Comment by TheNamelessWonderer** [comment]
Scrap that it has found the bitrate!

**Comment by nyanmisaka** [comment]
So is remux FLAC 3ch feasible?

**Comment by TheNamelessWonderer** [comment]
Yes it is. On stereo it still transcodes to AAC but if you set it back to auto it directly plays FLAC.

**Comment by TheNamelessWonderer** [comment]
However it doesn't solve the Firefox issue on Linux. It still requires Stereo.

**Comment by Artiume** [comment]
when you direct play the flac, is the video broken?

**Comment by TheNamelessWonderer** [comment]
On the iPad the video works fine. On Firefox the video doesn’t play with the error above.

**Comment by nyanmisaka** [comment]
Firefox with hls.js doesn't support FLAC.

We should disable transcoding to AAC 3ch.

**Comment by TheNamelessWonderer** [comment]
Does FLAC music not play using hls.js?

**Comment by nyanmisaka** [comment]
Nope. Remuxing FLAC only works in fMP4-HLS on Safari.

**Comment by TheNamelessWonderer** [comment]
Another observation is that if fMP4-HLS is off and audio is set to stereo then it fails to play on Safari. As this is off by default for most users will encounter this issue.

**Comment by TheNamelessWonderer** [comment]
Also fMP4-HLS causes it to transcode the video to HEVC with FLAC audio. Transcoding to HEVC from H264 would use far more processing power than FLAC to AAC. Can it not direct play the video is H264 with FLAC? Both work natively in Safari.

**Comment by nyanmisaka** [comment]
You can disable HEVC encoding in dashboard.

**Comment by nyanmisaka** [comment]
H264 High10 profile is not supported by iOS/iPadOS devices. Not sure if it's supported on MacOS.

**Comment by TheNamelessWonderer** [comment]
Oh yes thank you! Ah I forgot it was High 10. Is fMP4-HLS required to play FLAC with 3 channels?

**Comment by nyanmisaka** [comment]
Not sure but I think transcoding to odd number of channels will cause this issue.

**Comment by TheNamelessWonderer** [comment]
Indeed. It seems to affect Safari and Firefox but I haven't tested Chrome as I don't have it installed.

**Comment by TheNamelessWonderer** [comment]
Also I'd like to mention that at least Firefox doesn't have this issue on 10.6.4. Safari on iPhone won't play it but iPad do play it on 10.6.4.

**Comment by Artiume** [comment]
as in firefox successfully played 3ch audio or the transcoding wasn't messed up?

**Comment by TheNamelessWonderer** [comment]
Well not sure but it is transcoded to MP3 but the number of channels aren't listed.

**Comment by Artiume** [comment]
yeah, that was a bug we finally fixed :P, and it's uncovered new bugs haha

**Comment by TheNamelessWonderer** [comment]
That's fine! Hopefully it isn't too challenging to fix!

**Comment by Artiume** [comment]
normal mp3's max channels is 2ch so it was never a concern. I just think we need to add to the browser profiles that they support only 2ch

**Comment by TheNamelessWonderer** [comment]
I see profiles are changed in Jellyfin not Jellyfin-web so feel free to move this if it is in the wrong location!

**Comment by TheNamelessWonderer** [comment]
This has created another bug. I can open a new issue if you want. It is not allowing FLAC 3 channel to be played if the video is transcoded it seems 
![FAAF15B1-6D26-4703-891A-50E009D1D163](https://user-images.githubusercontent.com/56267607/105575205-e0d1f880-5d61-11eb-9223-9feac06d3a98.png)
