### ISSUE TITLE
Resize album picture

### ISSUE THREAD

**Issue by EFCAugure** [jellyfin/jellyfin-web#2259]
There is a small issue when displaying the album page on the PC web browsers. 
The album picture is not resized and it's not possible to see what is written under it.
![2020-12-19 22_36_02-Window](https://user-images.githubusercontent.com/40027303/102700093-a5b44500-424a-11eb-94e9-dce8e144e0f9.png)

This issue has been shot on the nightly build the 20/12/18.

**Comment by thornbill** [comment]
Looks like you are using some custom css styling. Could you disable those temporarily to verify that is not causing the issue? Thanks!

**Comment by thornbill** [comment]
Also please provide the information requested in the issue template.

```
**Describe The Bug**
<!-- A clear and concise description of what the bug is. -->

**Steps To Reproduce**
<!-- Steps to reproduce the behavior: -->
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected Behavior**
<!-- A clear and concise description of what you expected to happen. -->

**Logs**
<!-- Please paste any log errors. -->

**Screenshots**
<!-- If applicable, add screenshots to help explain your problem. -->

**System (please complete the following information):**
 - Platform: [e.g. Linux, Windows, iPhone, Tizen]
 - Browser: [e.g. Firefox, Chrome, Safari]
 - Jellyfin Version: [e.g. 10.6.0]

**Additional Context**
<!-- Add any other context about the problem here. -->
```

**Comment by EFCAugure** [comment]
Hello thornbill, thanks a lot for your answer!

I disabled the skin plugin (i forgot i had enabled it, sorry) and everything is looking fine now.

The next time i will submit a request i will  first disable every plugin and of course provide the requested infos.

Thanks again for your informations and i'm closing this ticket right now.

Lionel
