### ISSUE TITLE
Firefox requires transcoding to be on, regardelss if its transcoding or not.

### ISSUE THREAD

**Issue by Darkwolf1515** [jellyfin/jellyfin-web#2285]
**Describe The Bug**
On firefox, if transcoding is disabled on a users profile, (audio, video, all of them) video will not play, even if its capable of direct steaming.
**Steps To Reproduce**
1. Find a file you know firefox can direct stream
2. Disable transcoding
3. watch it just sit on the files artwork forever.

**Expected Behavior**
It to play.

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Firefox (who would have guessed!)
 - Jellyfin Version: 1.70 (Though this happened in 10.6.4, I just figured out the issue now.)

(And for some additional context, this also applies to the vue client.)

**Comment by Artiume** [comment]
I just disabled Video, Audio and Remux capability and was able to stream in Firefox on both 10.6.4 and 10.7.0-rc1. Need more information to figure out what the issue is

**Comment by Brissot** [comment]
Hey, could you provide details about the file of inquiry? I am not experiencing the same problem while disabling transcoding on AV1/Opus/VTT webm files.

**Comment by Darkwolf1515** [comment]
> Hey, could you provide details about the file of inquiry? I am not experiencing the same problem while disabling transcoding on AV1/Opus/VTT webm files.

Away from computer for a bit, but I’ll tell you what I recall.

The only files I use are mkv, there may be a mp4 here and there but that was not the case.

When I had all transcoding disabled, the files would show the artwork, and then freeze. When I enabled video, the same thing happened, but I could see the spinning loading icon, and finally enabling it all allowed video to play. Checking my browser from another instance confirmed it was direct playing. My extensions do not interfere with it (private mode changes nothing) and the only browser tweaks I did was ones to stop fingerprinting.

**Comment by Darkwolf1515** [comment]
It may possibly have something to do with subtitles, but it still claimed to direct play. I get I’m being vague but I can’t access my computer right now, I can in a few days but I didn’t want you to think I was ignoring you.

**Comment by Artiume** [comment]
are you sure you restored audio transcoding capability? if you attempt 5.1 audio, you'll get that spinning dial.

**Comment by Darkwolf1515** [comment]
> are you sure you restored audio transcoding capability? if you attempt 5.1 audio, you'll get that spinning dial.

It was the last thing I had to restore in order to get the video to play.

**Comment by Darkwolf1515** [comment]
Truly this could be a reporting issue, where my content requires transcoding in Firefox, but it reports as direct play.

**Comment by Artiume** [comment]
codec details are needed once you can get them

**Comment by Darkwolf1515** [comment]
> codec details are needed once you can get them

Hopefully tomorrow night, but now that we’ve talked a bit I’m starting to think that Jellyfin is just simply incorrectly reporting it as direct stream. But we’ll know tomorrow.

**Comment by Darkwolf1515** [comment]
So, an update, disabling video transcoding allows the video to play, but disabling audio prevents it (still reports as direct play)

Here's the codec 

![Screenshot 2021-01-03 195938](https://user-images.githubusercontent.com/65789901/103499809-4b69d580-4e41-11eb-8822-c7c99866eb07.png)

**Comment by Artiume** [comment]
when you say reports direct play, is this while audio transcoding is disabled? if so, that makes sense. as eac3 isnt supported by firefox

**Comment by Darkwolf1515** [comment]
> 
> 
> when you say reports direct play, is this while audio transcoding is disabled? if so, that makes sense. as eac3 isnt supported by firefox

No, direct play while audio transcoding is enabled.

**Comment by Artiume** [comment]
is this from the playback view or from the dashboard? can i get a screenshot and ffmpeg logs

**Comment by Darkwolf1515** [comment]
Made a mistake, it seems direct streaming and direct playing are not interchangeable terms, sorry.

**Comment by Artiume** [comment]
correct,  all good 👍
