### ISSUE TITLE
[10.7] Transparent Subtitles

### ISSUE THREAD

**Issue by TheNamelessWonderer** [jellyfin/jellyfin-web#2291]
**Describe The Bug**
Some subtitles are transparent in 10.7 making them hard to read.

**Steps To Reproduce**

1. Play a video
2. Watch as some subtitles are transparent

**Expected Behavior**

The Sub titles shouldn't be transparent

**Logs**
10:6 FFMPEG command: `ffmpeg -ss 00:01:39.000 -noaccurate_seek -f matroska,webm -i file:"/path/to/file" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -codec:v:0 libx264 -pix_fmt yuv420p -preset veryfast -crf 23 -maxrate 7834386 -bufsize 15668772 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none  -force_key_frames:0 "expr:gte(t,99+n_forced*3)" -g 72 -keyint_min 72 -sc_threshold 0 -vf "scale=trunc(min(max(iw\,ih*dar)\,1920)/2)*2:trunc(ow/dar/2)*2,subtitles='/Volumes/sda1/TV Shows/Jojo'\\\''s Bizarre Adventure/Season 3/[Some-Stuffs]_Jojo'\\\''s_Bizarre_Adventure_Diamond_is_Unbreakable_27_(1920x1080_Blu-Ray_FLAC)_[8B33D737].mkv:si=0'" -start_at_zero -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 192000  -copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 33 -hls_segment_filename "/Users/user/.local/share/jellyfin/transcodes/f5f139122bdf44f778c29c36b4d383a8%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/Users/user/.local/share/jellyfin/transcodes/f5f139122bdf44f778c29c36b4d383a8.m3u8"`

10.7 FFMPEG command: `ffmpeg -f matroska,webm -i file:"/path/to/file" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -pix_fmt yuv420p -preset veryfast -crf 23 -maxrate 7834386 -bufsize 15668772 -profile:v:0 high -level 41 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none  -force_key_frames:0 "expr:gte(t,0+n_forced_3)" -vf "scale=trunc(min(max(iw,ih_dar),min(1920,1080*dar))/2)*2:trunc(min(max(iw/dar,ih),min(1920/dar,1080))/2)*2" -start_at_zero -vsync -1 -codec:a:0 aac -ac 2 -ab 384000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/Users/user/.local/share/jellyfin/transcodes/429f96bb402453d5392e3e7e80aac2a6%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/Users/user/.local/share/jellyfin/transcodes/429f96bb402453d5392e3e7e80aac2a6.m3u8" `

**Screenshots**

![image](https://user-images.githubusercontent.com/56267607/103438720-ef7b3300-4c2d-11eb-8b63-afe24a74a9d0.png)
![image](https://user-images.githubusercontent.com/56267607/103438740-48e36200-4c2e-11eb-9fc5-c5e1fc4ad898.png)

**System (please complete the following information):**
 - Platform: Linux and iPad
 - Browser: Firefox and Jellyfin Mobile App
 - Jellyfin Version: 10.7-RC2

**Additional Context**
This didn't happen in 10.6 and also it is only with certain subtitles and fonts. In this anime the issue only occurs during the intro where the subs are different to the rest of the episode.

**Comment by nyanmisaka** [comment]
10.6 subtitle burn-in by ffmpeg

10.7 JavascriptSubtitlesOctopus

**Comment by TheNamelessWonderer** [comment]
I see is this an upstream issue then?

**Comment by nyanmisaka** [comment]
I also encountered similar problems on some subtitles before.
JavascriptSubtitlesOctopus may display incorrect transparency for some subtitles.
You can try adding a custom font in dashboard->playback to see if it helps.

**Comment by TheNamelessWonderer** [comment]
Just to confirm that is a JavascriptSubtitlesOctopus issue here is the same video in VLC with the fonts rending correctly.
![Screenshot_20210101_125345](https://user-images.githubusercontent.com/56267607/103438952-8812b280-4c30-11eb-8b44-6b28da20146e.png)

**Comment by TheNamelessWonderer** [comment]
Do you have some fonts I could use?

**Comment by nyanmisaka** [comment]
May be Google fonts?
https://fonts.google.com

**Comment by TheNamelessWonderer** [comment]
I downloaded https://fonts.google.com/specimen/Roboto regular. Made a new folder and extracted them into the folder, put that path into Jellyfin and enabled fallback fonts. Unfortunately it doesn't seem to have done anything and the problem still persists.

**Comment by nyanmisaka** [comment]
Seems there are some issues with alpha channel.
https://github.com/Dador/JavascriptSubtitlesOctopus/commit/aef67726a2200a1ad92b6b3fc38346bb4f8551e5
https://github.com/Dador/JavascriptSubtitlesOctopus/commit/3009691015c06661174baaa1892fda58df5c8b81

**Comment by TheNamelessWonderer** [comment]
I see. Both of them are fixes that are merged are they included in 10.7-RC2?

**Comment by nyanmisaka** [comment]
Sure. But I have never seen it enabled in web browsers.
https://github.com/jellyfin/JavascriptSubtitlesOctopus/blob/58e9a3f1a7f7883556ee002545f445a430120639/src/subtitles-octopus.js#L183

**Comment by TheNamelessWonderer** [comment]
Nope nothing about it being enabled in my browser console.

**Comment by nyanmisaka** [comment]
You can force enable it here and rebuild jellyfin-web with it to test.
https://github.com/jellyfin/JavascriptSubtitlesOctopus/blob/58e9a3f1a7f7883556ee002545f445a430120639/src/subtitles-octopus.js#L460
https://github.com/jellyfin/jellyfin-web/blob/3bd4b991d7271d941b8d606783c12efd4935cfb9/yarn.lock#L4836

**Comment by TheNamelessWonderer** [comment]
How do I enable it? I see a line with a url on it.

**Comment by TheNamelessWonderer** [comment]
This bug isn’t fixed and still happens in 10.7.5.

**Comment by TheNamelessWonderer** [comment]
Still an issue on 10.7.7.

**Comment by dmitrylyzo** [comment]
@TheNamelessWonderer Is there a `\fad` (fading) in the lines that semi-transparent?

**Comment by l4kr** [comment]
I have also noticed ASS/SSA subtitles with motion tracking and/or any sort or special effects to be just static.

I suspect this is a related issue. If not, I will create a new issue.
 
![platend1](https://user-images.githubusercontent.com/73653844/150691013-549b9971-f0d0-4c2a-ac0a-2d9d82b71619.png)
![platend2](https://user-images.githubusercontent.com/73653844/150691031-77015a2f-47d2-465e-af84-fbf0bd57925c.png)
![soul2](https://user-images.githubusercontent.com/73653844/150691036-075ee82c-adff-4e8d-b993-0c16bb8d9fea.png)
![soul1](https://user-images.githubusercontent.com/73653844/150691039-0bc6b616-8963-46b9-a155-ca8f746c2349.png)

**Comment by dmitrylyzo** [comment]
@l4kr
If you post sample events that don't work as expected, I can tell more. But I think this is due to heavy animation, which stalls the oneshot render.

I am waiting for https://github.com/libass/JavascriptSubtitlesOctopus/pull/111 to be merged (we want to migrate to the upstream) and counted about 5 PRs that I am going to open (https://github.com/libass/JavascriptSubtitlesOctopus/pull/111#issuecomment-948920513). [One of them](https://github.com/libass/JavascriptSubtitlesOctopus/pull/111#issuecomment-946164038) should help a bit with heavy animation - it will discard some frames if it can't render in time.

A new rendering mode from another contributor is also expected - using hardware acceleration in the worker.

**Comment by TheNamelessWonderer** [comment]
Hello is there any progress on this? I see your pull request on the repo was closed. Also is https://github.com/jellyfin/JavascriptSubtitlesOctopus/pull/21 planning to make it into 10.8? Thanks!

**Comment by dmitrylyzo** [comment]
Fixed by #3644

**Comment by TheNamelessWonderer** [comment]
Thank you so much!
