### ISSUE TITLE
Jellyfin 10.7~rc2 has caused items to be stuck in Continue Watching and Dashboard

### ISSUE THREAD

**Issue by Jinxyface** [jellyfin/jellyfin-web#2292]
Windows 10

Jellyfin 10.7rc1 no issue, upgraded to rc2 and the issue happened

Essentially items are getting stuck in the "Continue Watching" part of the homescreen, even after being watched

![image](https://user-images.githubusercontent.com/19889486/103441382-24c65780-4c13-11eb-976f-451543144e51.png)

When you go to the dashboard, there's a rogue playback to, when no one is actually playing anything

![image](https://user-images.githubusercontent.com/19889486/103441391-37409100-4c13-11eb-9301-6618c4578ddf.png)

I've tried making them go away, even tried restarting Jellyfin server and rebooting the server, but nothing. These items are just stuck here.

**edit** apparently 4 reboots wasn't enough, the 5th one seemed to solve it though...lol

**Comment by ClockeNessMnstr** [comment]
"When you go to the dashboard, there's a rogue playback too"

Just had this issue with the latest Android TV beta. 
Force stopping the TV app and then marking unplayed/played cleared them for me. 

Hopefully that helps if anyone else sees this.
