### ISSUE TITLE
[bug] more than 301 photos in directory => wrong fullscreen photo

### ISSUE THREAD

**Issue by 4ndreasH** [jellyfin/jellyfin-web#2294]
**Describe the bug**
Whenever a directory contains more than 301 photos I have this error: the webpage with these photos (thumbnails) shows all photos as expected but if I click on a photo to get a fullscreen picture this only works for the first 301 photos. All other photos will show the oldest photo of this folder in fullscreen and not the actual one.

**System (please complete the following information):**
 - OS: OpenSuse Tumbleweed
 - Virtualization:  none
 - Clients: browser
 - Browser: any
 - Jellyfin Version: 10.7.0 rc1 / 10.6.4
 - Playback:  -
 - Installed Plugins: none
 - Reverse Proxy: apache
 - Base URL: none
 - Networking:  -
 - Storage: local

**To Reproduce**
1. rebuild photo library in directory with more than 301 photos.
2. click on thumbnail to view photo

**Expected behavior**
fullscreen photo is same as thumbnail photo

**Additional context**
If I delete the photo library and add it again to completely rebuild all informations the same problem shows up again.

**Comment by Artiume** [comment]
I could expose those values to the admin UI similar to what I've done here

https://github.com/Artiume/jellyfin-web/pull/11

I'm not sure if we need to expose the album limit though, 1000 seems like a high ceiling.

**Comment by DinoHS** [comment]
Would that allow us to override the limit in settings?  Something like that would be much appreciated (from a user point of view), @Artiume!

**Comment by Artiume** [comment]
yeah. i just need to find a sample photo library to test with. i dont have a lot of pictures in my collection.

**Comment by DinoHS** [comment]
> 
> 
> yeah. i just need to find a sample photo library to test with. i dont have a lot of pictures in my collection.

See my first reply ;)

**Comment by Artiume** [comment]
ah thanks

**Comment by DinoHS** [comment]
I'm going through Emby docs and trying to find out about library size limits, but not finding anything at the moment.  Anyone know if there are limits on how many e.g., movies can be added to a library?  Just wondering what they are, and whether photos are getting arbitrarily limited relative to other media types.

**Comment by Artiume** [comment]
this issue isnt limiting the size of a photo library. it's limiting how many to send full size from the server to your client at once.

**Comment by 4ndreasH** [comment]
I just tested 10.7.0 rc3 => the bug still exists

**Comment by kkris9** [comment]
Hello! Same issue here - also after update to 10.7.5.

The 301st (and above) element in a folder can't be opened on a click. Instead jellyfin opens the picture that is used as the thumbnail for the folder. In my specific case the 290th photo is the last one which I can view in full size because the first 10 elements are subfolders. Also changing the sorting does not help.

Both the official jellyfin docker image as well as the one from linuxserver.io show the same behavior. I tried with the android app, the iOS app and via browser. No difference. I also could not find the "playbackmanager.js" that @DinoHS mentioned above and try to change the limit myself, but I am also not a developer...

I appreciate any feedback and do contact me if I can be of assistance to solve the issue.

**Comment by WindLi001** [comment]
I try the method from DinoHS as above, that is, delete 
query.Limit = query.Limit || 300;
in playbackmanager.js (getItemsForPlayback). And it relly works for me on my own server, which have a few thousands picture in one folder.
So I change the code of master branch, and maybe it will be merged in the future version if I do nothing wrong.

**Comment by 4ndreasH** [comment]
I just tested 10.8.0 alpha 1 (31 Oct 2021) => the bug still exists

**Comment by luther84** [comment]
Just stood up my first jellyfin instance, version 10.7.7, and noticed this bug. Found this issue and am reporting that I see it as well. The behavior here seems to be any photos past number 300 show only the oldest photo when select for fullscreen viewing. Thanks!

**Comment by luther84** [comment]
Sorry for replying to myself but after a couple days of tinkering with jellyfin it seems like one of the more "intuitive" ways to solve this would be to present 300 or less photos per page and have multiple pages for folders larger than the limit. So opening a folder with more photos than the limit would get split into multiple pages. I'm envisioning something similar to other libraries like Movies, where items are split into multiple pages.
