### ISSUE TITLE
Camera sync notfication appears as an option.

### ISSUE THREAD

**Issue by Darkwolf1515** [jellyfin/jellyfin-web#2326]
**Describe The Bug**
Could have sword auto image upload was gutted and was not coming back, is this meant to show up?

**Screenshots**
\
![Screenshot 2021-01-11 190859](https://user-images.githubusercontent.com/65789901/104264454-90b28680-5483-11eb-9030-194dde1bfe45.png)

**System (please complete the following information):**

Version: 10.7.0 RC-2

**Comment by thornbill** [comment]
This was fixed by https://github.com/jellyfin/jellyfin/pull/5004
