### ISSUE TITLE
[Request] Additional branding options

### ISSUE THREAD

**Issue by Sidefix** [jellyfin/jellyfin-web#2335]
Hello!

The currently available branding options for the dashboard are missing options for the page title and icons. I was wondering whether there is any consideration for implementing such options, or is there a hard requirement for maintaining the current defaults?

Thank you in advance.

**Comment by miadotcx** [comment]
I would like to expand on this with an actual feature list of requests

- custom favicon
- custom <title> 
- custom themes documentation?

**Comment by mairajha** [comment]
That is exactly what I want

**Comment by mia-cx** [comment]
Friendly bump to prevent autoclose

**Comment by mia-cx** [comment]
this issue is still very much relevant. thank you!

**Comment by thornbill** [comment]
Closing in favor of this [feature request](https://features.jellyfin.org/posts/1919/rebranding).
