### ISSUE TITLE
Web UI doesnt respect Parental Control blocked items with tags

### ISSUE THREAD

**Issue by nextlooper42** [jellyfin/jellyfin-web#2341]
**Describe The Bug**
Jellyfin Web doesnt respect blocked tag settings in profiles. It wont show "stuff" in library, but it will show in "Latest ..." and "Next Up" sections and it can be opened and played from there.

**Steps To Reproduce**
1. Add tag to some movie/tv show eg. "testtag" and save it
2. Open profile that needs to be restricted
2. Add this "testtag" to Blocked items with tags in Parental Control and save it
3. Logout from admin acc
4. Login on that account you want to restrict
4. You can find that item in home screen

**Expected Behavior**
Dont show ANY existence of that item.

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Firefox, Edge Chromium
 - Jellyfin Version: 10.6.4

**Additional Context**
It also shows backgrounds from restricted items on home on restricted profile. Also affect Jellyfin Android app ofc. Afaik Kodi addon respect this, i cannot acces that content there, anywhere (not even recently or on progress sections)... so feature is working there.

**Comment by Jdogzz** [comment]
I can confirm this remains a bug as of Version: 10.7.7. Tested on Windows with Firefox.

**Comment by danieldietsch** [comment]
This is indeed still an issue and makes the current parental controls useless.

**Comment by thornbill** [comment]
This should be fixed in 10.10
