### ISSUE TITLE
10.7.0-rc3/rc4 ASS subtitles broken when using a reverse proxy, due to omitted subpath in URL

### ISSUE THREAD

**Issue by CTalvio** [jellyfin/jellyfin-web#2360]
**Describe The Bug**
When playing media with embedded ASS subtitles using jellyfin-web 10.7.0-rc3 playback will start, but subtitles will fail to load if media is being played through a reverse proxy using subpath.

This is due to the web client trying to access a location without using the proper subpath, which then won't be picked up by the proxy, resulting in a 404 error.

For example: `jellyfin.com/Videos`

Instead of the correct: `jellyfin.com/jellyfin/Videos`

**Steps To Reproduce**

Attempt to play a file with embedded ASS subtitles enabled, while using a reverse proxy with subpath

**Expected Behavior**

The web client should use the correct subpath.

**System (please complete the following information):**
 - Platform: Mint 19.1
 - Browser: Issue occurs in all clients.
 - Jellyfin Version: 10.7.0-rc3

**Comment by CTalvio** [comment]
I have investigated further. Playback functions correctly when accessing the server directly, bypassing nginx.

Based on the browser error logs, Jellyfin-web is trying to access something at /videos without the use of the required /jellyfin subpath requred when a reverse proxy is in use. Instead omitting it, causing a 404 error and the video player to fail accessing the subtitles.

**Comment by CTalvio** [comment]
Workaround: Forwarding /Videos in the proxy config.

`location /Videos {
    # Proxy main Jellyfin traffic
    # The / at the end is significant.
    proxy_pass http://127.0.0.1:8096/Videos;

    proxy_pass_request_headers on;

    proxy_set_header Host $host;

    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $http_host;

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;

    # Disable buffering when the nginx proxy gets very resource heavy upon streaming
    proxy_buffering off;
  }`

With this added, the issue is gone.

**Comment by dmitrylyzo** [comment]
This will probably be fixed by #2443 in the next RC.

**Comment by CTalvio** [comment]
No. Issue persists in RC4.

**Comment by CTalvio** [comment]
Ah. Seems I was wrong. It appears to work now.

Probably my browser cache failed to update in a timely manner, after updating jellyfin-web. Did not think of that. Closing.
