### ISSUE TITLE
[10.7] Bitrate/quality does not change in transcoding

### ISSUE THREAD

**Issue by Hukuma1** [jellyfin/jellyfin-web#2372]
**Describe The Bug**
The bitrate seems to be locked at same value for  transcoding h265 -> h264. Switching `Encoding preset` does not change speed/quality of the transcode.

**Steps To Reproduce**
1. Transcode 1080p h265 to h264
2. Logs show specific bitrate.
3. Change `H264 encoding CRF:` and `Encoding preset`
4. Still same bitrate/quality.

**Expected Behavior**
Bitrate and encode quality should be different.

**Logs**
```
Duration: 01:51:56.76, start: 0.000000, bitrate: 2230 kb/s
    Stream #0:0(und): Video: hevc (Main 10) (hev1 / 0x31766568), yuv420p10le(tv), 1920x802 [SAR 1:1 DAR 960:401], 1999 kb/s, 23.98 fps, 23.98 tbr, 1200k tbn, 23.98 tbc (default)
    Metadata:
      creation_time   : 2020-04-12T02:06:40.000000Z
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 224 kb/s (default)
    Metadata:
      creation_time   : 2020-04-12T02:06:40.000000Z
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_omx))
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[h264_omx @ 0x31b4260] Using OMX.broadcom.video_encode
Output #0, hls, to '/transcode/d0fbcec8c748f07424c068729e518242.m3u8':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (h264_omx), yuv420p, 1920x802 [SAR 1:1 DAR 960:401], q=2-31, 8332 kb/s, 23.98 fps, 90k tbn, 23.98 tbc (default)
    Metadata:
      encoder         : Lavc58.91.100 h264_omx
```

**Screenshots**
<img width="344" alt="jelly" src="https://user-images.githubusercontent.com/54511555/106637946-2cda2580-6538-11eb-96f4-fec65a02d8a7.png">

**Server System (please complete the following information):**
 - OS: Docker on Linux (LinuxServer nightly)
 - Jellyfin Version: 10.7 RC3 (nightly?)
 - Hardware settings & device: Raspberry Pi 4 4GB
 - Reverse proxy: no
 - Other hardware notes: SMB share for transcode folder
 
**Client System (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - Browser (if Web client): Chrome
 - Client and Browser Version: 88.0.4324.104
 
**Additional Context**
<img width="745" alt="cpu" src="https://user-images.githubusercontent.com/54511555/106637997-395e7e00-6538-11eb-885e-648b2cb7e20a.png">

Trying to lower CPU usage for a transcode on my RPi4. Is the 85%+ over all 4 cores normal for this operation?

**Comment by Musouka42** [comment]
I am experiencing this same issue.  No matter what settings I choose for the CRF or encoding preset, the transcoding bitrate does not change.  This is on Jellyfin 10.7.5 running on xUbuntu 20.04.

**Comment by Hukuma1** [comment]
Thanks for reminding me. I think this was tied to my playback bitrate selection. So if you don't change it in the player settings, the encoder won't switch either. Once I switched it, Jellyfin began encoding at specific presets as intended. Please let me know if this fixes your issue as well so I can close this out! Click the little cog wheel/settings icon and switch the quality.

<img width="227" alt="jellyquality" src="https://user-images.githubusercontent.com/54511555/121121767-0e7d8280-c7d5-11eb-82be-ce62255ef647.png">

**Comment by Musouka42** [comment]
Well, now I just feel silly for not trying that beforehand.  Changing the quality setting from the player did fix the issue.  Thank you!

**Comment by Hukuma1** [comment]
I feel worse, trust me. D:

Leaving this for others in the future with Google search helping out. ;)

**Comment by rightsaidfred99** [comment]
This is still a bug because you cannot change this in the android TV client
