### ISSUE TITLE
Video timeline scrub thumbnails

### ISSUE THREAD

**Issue by advancedslicedbanana** [jellyfin/jellyfin-web#240]
**Is your feature request related to a problem? Please describe.**
It's difficult to scrub to different parts of a video without thumbnails.

**Describe the solution you'd like**
I would like to see generated thumbnails appear while scrubbing on the video timeline.

**Describe alternatives you've considered**
While the current chapter thumbnail system gives some context, it leaves large gaps between chapter thumbnails.

**Additional context**
![scrub_thumbnails](https://user-images.githubusercontent.com/13087294/55912051-7f01c800-5ba7-11e9-841a-9ffca29e2aaf.gif)

**Comment by ahmedammar841** [comment]
Yea I agree.
