### ISSUE TITLE
Volume slider scale not linear

### ISSUE THREAD

**Issue by axelsimon** [jellyfin/jellyfin-web#2401]
**Describe The Bug**
When dragging the volume slider control, the sound isn't changed linearly.
For instance, dropping down to a volume of 10 out of 100 is still quite loud, and even 1 is still far louder than "1% of the initial volume".
You can see this also when comparing the Jellyfin-web's slider with the PulseAudio volume in Pulse Audio Volume Control: when you reach 1 in Jellyfin-web, you are still at about 20% volume in PulseAudio.

**Steps To Reproduce**
1. Play something, a song for instance
2. Bring volume down
3. Volume is reduced, but not as much as expected

**Expected Behaviour**
Normal sound control, similar to other apps and PulseAudio in particular.

**Logs**
not relevant

**Screenshots**
Will try to share a screen capture.

**System (please complete the following information):**
 - Platform: Fedora 32
 - Browser: Firefox 85.0
 - Jellyfin Version: 10.6.4

**Additional Context**
None that I can think of.

**Comment by axelsimon** [comment]
AFAICT, this issue is still valid.

**Comment by MrTimscampi** [comment]
This is fixed in unstable (future 10.8)
