### ISSUE TITLE
Playback Speed in v10.7.0 RC3 defaults to 1x after each video play.

### ISSUE THREAD

**Issue by MxD-js** [jellyfin/jellyfin-web#2406]
**Describe The Bug**

Unsure if this can be categorized as a bug or not, or this was the design intent, but when I watch a tutorial video and I sped up the video 1.25 or 1.5x for the video I am watching, it plays at that speed, then on next lecture the speed reverts to 1x. So I am having to set 1.25 on each video as they play.

**Media Information**

standard .mp4 video

**Screenshots**

**System (please complete the following information):**
 - Platform: [e.g. Linux, Windows, iPhone, Tizen] Docker on Linux 
 - Browser: [e.g. Firefox, Chrome, Safari] All
 - Jellyfin Version: [e.g. 10.6.0] v10.7.3 RC3

**Additional Context**

**Steps to reproduce**
1) start any video play
2) set video speed to 1.25
3) video ends, and next video in the series starts,
4) video speed reverts back to 1x

**Comment by MxD-js** [comment]
Update: Final production release of 10.7.0 also has this "bug" would be nice to have a global setting in the user profile or better yet, keep the playback speed setting for the duration of the browser session.

**Comment by Javi** [comment]
Browser session would be best. This would be a killer feature, it's also not being kept on Emby and there's no playback speed controls on Plex at all

**Comment by MxD-js** [comment]
Latest version 10.7.2 still has this "bug"
