### ISSUE TITLE
Weblate for Traditional Chinese hasn't removed purchase related strings

### ISSUE THREAD

**Issue by lostmypillow** [jellyfin/jellyfin-web#242]
Riot (or Matrix) is down for me, so I'm posting here. I thought I already edited the source file so it doesn't include the purchase related strings?

**Comment by lostmypillow** [comment]
Apparently another helpful contributor to the Traditional Chinese added translations for the purchase related strings through Weblate, please remove those source string please. It seems that [this](https://github.com/jellyfin/jellyfin-web/pull/203) did not remove the ones in Traditional Chinese

**Comment by joshuaboniface** [comment]
I've just rebased Weblate in the last ~30 minutes, and the strings seem gone there now based on a search - can you confirm?

**Comment by lostmypillow** [comment]
Thanks, it's gone now!
