### ISSUE TITLE
Next up inconsistent behavor without partially watched series

### ISSUE THREAD

**Issue by Nothing4You** [jellyfin/jellyfin-web#2430]
**Describe The Bug**
Inconsistent behavior when there is no Next Up content based on started series available.

**Steps To Reproduce**
1. Create a new user, so it doesn't have any watched items
2. Now Next Up displays all existing shows
3. Mark any episode as watched
4. Next Up now only shows that series
5. Mark entire series as watched
6. Next Up is gone

**Expected Behavior**
It seems inconsistent to me that the behavior is different in the following situations:
- No episode at all is watched
- All episodes in all started series are watched

It seem to me that either Next Up should disappear in both cases or show (seemingly) random shows in both cases.

**Logs**
–

**Screenshots**
–

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Firefox
 - Jellyfin Version: 10.6.4

**Additional Context**
–

**Comment by Nothing4You** [comment]
Discussion about this on Matrix revealed that there is an API option to skip first episodes now, which however isn't used by any client yet. This may be the resolution to hide it in both cases I guess?

Regardless of that API option it still seems inconsistent to me right now, but that may be an issue in jellyfin, not the web client?

An attempt to change this previously in the jellyfin API has caused issues with the android client and was therefore rolled back according to @cvium.

**Comment by TimGels** [comment]
It seems to be an issue again https://github.com/jellyfin/jellyfin-web/pull/2509#issuecomment-1365206029
