### ISSUE TITLE
Subtitles obscured by playback controls UI

### ISSUE THREAD

**Issue by CloudStu** [jellyfin/jellyfin-web#2441]
**Describe The Bug**
After updating Jellyfin, I've found the player controls take up much more screen real estate, with superfluous information like the Rotten Tomatoes score and other ratings. This covers the subtitles, making it more difficult to read them when the controls UI is active. This is not an issue whilst the video is paused, but is frustrating when using the controls whilst the video is playing, such as changing volume using the Subtitles Offset feature, or any other playback settings.

**Steps To Reproduce**
Play any video with subtitles and interact with the controls.

**Expected Behavior**
I would expect one of:
 - Revert back to the smaller UI that doesn't obscure the subtitles at all.
 - Hide the bottom UI entirely when the Subtitles Offset mode is being used (doesn't solve the issue when interacting with other settings)
 - Move the subtitles above the control bar when it appears.

Personally I don't find the expanded UI adds anything useful to the playback of the video (Film Ratings), prefering a more minimal UI with fewer visual distractions, but this was presumably added for a reason. It isn't a big problem having the extended info when paused, so I offer the suggestions to move the subtitles or hide the playback controls when in Subtitles Offset.

**Screenshots**

![image](https://user-images.githubusercontent.com/79151169/108700343-bf059600-7506-11eb-9447-e254ac8e598b.png)
Above is a screenshot from Firefox. However its worse on my LG TV:
![image](https://user-images.githubusercontent.com/1374626/108704127-d85d1100-750b-11eb-9a4e-18db9dd28bd3.png)

**System:**
 - Platform: Windows, WebOS
 - Browser: Firefox, Edge, WebOS
 - Jellyfin Version: 10.6.4

**Additional Context**
I immediately noticed this change after updating my LinuxServer.io Jellyin installation over the weekend to 10.6.4-1-ls97. I apologise I don't know what version I was on previously - one of the pitfalls of using docker-compose with the 'latest' tag means I couldn't easily see what version I was using beforehand. This also means I can't show you any screenshots from before this behaviour regressed, nor can I even tell you specifically what changed, but I know I was immediately frustrated - _something_ has changed.

Where I sometimes have poorly synced subtitles I find myself using Subtitles Offset multiple times an episode, which is why this issue is so noticeable to me.

**Comment by MrTimscampi** [comment]
Do note we've redesigned the OSD in 10.7, so this is less of an issue:
![image](https://user-images.githubusercontent.com/19396809/108715441-2b8a9000-751b-11eb-9d79-c8b8eea06f62.png)

The OSD was pretty much unchanged before, only the way the subtitles are displayed may have changed since the last version you used.
