### ISSUE TITLE
Option to disable controller input

### ISSUE THREAD

**Issue by PrimordialHelios** [jellyfin/jellyfin-web#246]
**Is your feature request related to a problem? Please describe.**
I frequently watch videos while gaming, and I occasionally use an xbox360 controller. Unfortunately, the controller input is *always* sent to jellyfin's web client, even when it isn't the focused window. This makes watching videos impossible while playing games with a controller, as each button stops, pauses, fast-forwards, etc.

**Describe the solution you'd like**
A toggle option somewhere in the settings to disable controller input. Alternatively, it would be useful if jellyfin-web just didn't grab any input when it isn't focused.

**Comment by Reynbow** [comment]
Please! This is doing my head in.

**Comment by anthonylavado** [comment]
This is available in the next release :-)

**Comment by PrimordialHelios** [comment]
Fantastic! Thanks for all the great work :)

**Comment by TheFeelTrain** [comment]
I would like this to be revisited. 

This is probably an extremely niche problem but I use an Xbox controller to control my mouse cursor among other things with some custom bindings. During video playback (not during music as far as I can tell) the left thumbstick controls seeking so the player will jump around when I try to move my mouse.

The previous fixes do not account for this use case, so a way to outright disable controller input would be appreciated.
