### ISSUE TITLE
No Promise from HTMLMediaElement.play in old browser

### ISSUE THREAD

**Issue by dmitrylyzo** [jellyfin/jellyfin-web#2478]
**Describe The Bug**
Error in console `Playback not allowed! TypeError: Cannot read property 'then' of undefined(…)`.
At this line:
https://github.com/jellyfin/jellyfin-web/blob/68bf09de1611138b8dc5cec63f02242ecd80698c/src/components/syncPlay/ui/playbackPermissionManager.js#L38
In old browsers, `HTMLMediaElement.play` doesn't return `Promise`.

**Steps To Reproduce**
_You need old browser_
1. Go to home page.
2. Click on SyncPlay button.
3. See error in browser console.

**Expected Behavior**
To be error-free :smile: 

**System (please complete the following information):**
 - Platform: Tizen 3.0
 - Browser: Chrome 47
 - Jellyfin Version: web(6383388b72b7692016abf6dc5fb00f2da37ab2a8), server(20210225.1-unstable)

**Comment by thornbill** [comment]
This seems to happen on old versions of Safari also. I saw it on iOS 10.

**Comment by dmitrylyzo** [comment]
#2557 shadowed this error.
https://github.com/jellyfin/jellyfin-web/blob/d760b31080e6b072d16cb7bb3189ed40fbf7ca7e/src/components/syncPlay/ui/playbackPermissionManager.js#L38-L40
