### ISSUE TITLE
10.7 Android - Item Details - Large amount of wasted space when compared to 10.6 (or desktop)

### ISSUE THREAD

**Issue by adavier** [jellyfin/jellyfin-web#2490]
**Describe The Bug**

Large amount of wasted space on 10.7 compared to 10.6 when viewing Film/TV show.
This affects the mobile view and the Android app.

**Steps To Reproduce**

Update to 10.7.0

**Expected Behavior**

**Screenshots**

Normal Mode, Android App is the same (10.7)
![10 7](https://user-images.githubusercontent.com/30839200/110254023-37e40380-7f85-11eb-9a29-55d2f5f9fc09.jpg)

Normal Mode 10.6
![10 6](https://user-images.githubusercontent.com/30839200/110254030-3ca8b780-7f85-11eb-9334-59880b3475e3.jpg)

**System (please complete the following information):**
 - Platform: Android
 - Browser: Tested in Firefox, and Android App
 - Jellyfin Version: 10.7.0

**Comment by thornbill** [comment]
What is the screen resolution?

**Comment by adavier** [comment]
2560x1600

**Comment by adavier** [comment]
2560x1600

**Comment by dmitrylyzo** [comment]
> Chrome on Android displays correctly without Desktop Mode

Looks like `Desktop` layout (in Jellyfin: `Settings` -> `Display` -> `Display mode`). If option is `Auto`, then browser is detected incorrectly - as non-mobile.

**Comment by adavier** [comment]
> Looks like `Desktop` layout (in Jellyfin: `Settings` -> `Display` -> `Display mode`). If option is `Auto`, then browser is detected incorrectly - as non-mobile.
You are correct, it is infact dekstop mode (both in chrome and when Desktop Site is ticked in firefox), which causes some issues like tapping on the tile for a film will automatically play it.

It seems that the mobile site requires some changes for landscape to bring it more inline with the previous version.

**Comment by EdilsonBaggio** [comment]
How to make the browser identify the mobile version?

**Comment by thornbill** [comment]
Fixed in https://github.com/jellyfin/jellyfin-web/pull/2859
