### ISSUE TITLE
Upgrade to 10.7.0 completely broke web interface.

### ISSUE THREAD

**Issue by iqfx** [jellyfin/jellyfin-web#2493]
**Describe The Bug**
After upgrading from 10.6.4 the web ui stopped functioning.

**Steps To Reproduce**
Confirmed cases of this happening have been on Debian 9 and Ubuntu 20.04
1. Have an existing installation of jellyfin 10.6.4
2. Upgrade to 10.7.0 (Using apt-get in my case)

**Expected Behavior**
Upgrade succeeds and able to use the web interface like normal

**Logs**
```
Mar 09 00:59:26 jellyfin jellyfin[588]: [00:59:26] [ERR] Error processing request: Could not find file '/usr/share/jellyfin/web/auto3c6ca3cf906a3cadc4ef3e8b8647fc80.woff2'. URL: http://media.iqfx.nl/jellyfin/web/auto3c6ca3cf906a3cadc4ef3e8b8647fc80.woff2
Mar 09 00:59:26 jellyfin jellyfin[588]: [00:59:26] [ERR] Error processing request: Could not find file '/usr/share/jellyfin/web/auto4111.216eaafc1998676a57da.bundle.js'. URL: http://media.iqfx.nl/jellyfin/web/auto4111.216eaafc1998676a57da.bundle.js
Mar 09 00:59:26 jellyfin jellyfin[588]: [00:59:26] [ERR] Error processing request: Could not find file '/usr/share/jellyfin/web/auto4201.842f5b8e2be0c61096be.bundle.js'. URL: http://media.iqfx.nl/jellyfin/web/auto4201.842f5b8e2be0c61096be.bundle.js
Mar 09 00:59:26 jellyfin jellyfin[588]: [00:59:26] [ERR] Error processing request: Could not find file '/usr/share/jellyfin/web/auto3d1ccc6a42fa9c614ae5c1a2cd99c728.woff2'. URL: http://media.iqfx.nl/jellyfin/web/auto3d1ccc6a42fa9c614ae5c1a2cd99c728.woff2
Mar 09 00:59:26 jellyfin jellyfin[588]: [00:59:26] [ERR] Error processing request: Could not find file '/usr/share/jellyfin/web/auto4258.9967bd8cdf274b59c1e8.bundle.js'. URL: http://media.iqfx.nl/jellyfin/web/auto4258.9967bd8cdf274b59c1e8.bundle.js
Mar 09 00:59:26 jellyfin jellyfin[588]: [00:59:26] [ERR] Error processing request: Could not find file '/usr/share/jellyfin/web/auto42a889d51221715273a8d3b9176addcf.woff2'. URL: http://media.iqfx.nl/jellyfin/web/auto42a889d51221715273a8d3b9176addcf.woff2
Mar 09 00:59:26 jellyfin jellyfin[588]: [00:59:26] [ERR] Error processing request: Could not find file '/usr/share/jellyfin/web/auto4481.f752f84b494404205367.bundle.js'. URL: http://media.iqfx.nl/jellyfin/web/auto4481.f752f84b494404205367.bundle.js
Mar 09 00:59:26 jellyfin jellyfin[588]: [00:59:26] [ERR] Error processing request: Could not find file '/usr/share/jellyfin/web/auto455fafb7b7d43f13c8d3013584231cf4.woff2'. URL: http://media.iqfx.nl/jellyfin/web/auto455fafb7b7d43f13c8d3013584231cf4.woff2
Mar 09 00:59:26 jellyfin jellyfin[588]: [00:59:26] [ERR] Error processing request: Could not find file '/usr/share/jellyfin/web/auto46f8949c5873634fd15b162cab886980.woff2'. URL: http://media.iqfx.nl/jellyfin/web/auto46f8949c5873634fd15b162cab886980.woff2
Mar 09 00:59:26 jellyfin jellyfin[588]: [00:59:26] [ERR] Error processing request: Could not find file '/usr/share/jellyfin/web/auto4a10f1826c3782dd9868545050d23101.woff2'. URL: http://media.iqfx.nl/jellyfin/web/auto4a10f1826c3782dd9868545050d23101.woff2
```

**Screenshots**
![jellyfinwat](https://user-images.githubusercontent.com/39005172/110400122-604c2a80-8077-11eb-811d-2345b8f7bac6.png)

**System (please complete the following information):**
 - Platform: Confirmed cases of this happening have been on Debian 9 and Ubuntu 20.04
 - Browser: Any
 - Jellyfin Version: 10.7.0

**Additional Context**
I'm using the /jellyfin sub url if that makes any difference.

**Comment by thw26** [comment]
I'm the Ubuntu 20.04 user. This is broken for my Firefox and Android client. I am not using a jellyfin sub url/path/dir.

Here is a paste of output from one request (I'm fairly certain about it being a single request F5 refresh):

https://pastebin.com/2mJx32kU

Here's a sample:

```
[2021-03-08 19:34:24.295 -05:00] [ERR] Error processing request: "The operation was canceled". URL: "http://jellyfin.domain.tld/web/main.3309837d9db1402ea3a1.bundle.js"
[2021-03-08 19:34:24.498 -05:00] [ERR] Error processing request: "The operation was canceled". URL: "http://jellyfin.domain.tld/web/7025.8047dd014c638223df19.bundle.js"
[2021-03-08 19:34:25.224 -05:00] [ERR] Error processing request: "Could not find a part of the path '/usr/share/jellyfin/web/components/serviceworker/notifications.js'". URL: "http://jellyfin.domain.tld/web/components/serviceworker/notifications.js"
[2021-03-08 19:34:25.927 -05:00] [ERR] Error processing request: "Could not find file '/usr/share/jellyfin/web/auto0095962de230e8e76d21c78c2130ce89.woff2'". URL: "http://jellyfin.domain.tld/web/auto0095962de230e8e76d21c78c2130ce89.woff2"
[2021-03-08 19:34:25.929 -05:00] [ERR] Error processing request: "Could not find file '/usr/share/jellyfin/web/auto013d88d33df6093c608e5fc9c6de13ef.woff2'". URL: "http://jellyfin.domain.tld/web/auto013d88d33df6093c608e5fc9c6de13ef.woff2"
[2021-03-08 19:34:25.928 -05:00] [ERR] Error processing request: "Could not find file '/usr/share/jellyfin/web/auto00cd17f35016e45af8d4997c1a37d95c.woff2'". URL: "http://jellyfin.domain.tld/web/auto00cd17f35016e45af8d4997c1a37d95c.woff2"
```

**Comment by awb1015** [comment]
Ubuntu 20.04 user here, same issue for me as well. Also updated via PPA. Happy to provide logs if needed

**Comment by joshuaboniface** [comment]
Given the filenames it seems like some weird versioning. Just to be sure, has restarting the server corrected it? Also, to be sure, are both `jellyfin-server` and `jellyfin-web` packages at 10.7.0-1?

**Comment by iqfx** [comment]
> Given the filenames it seems like some weird versioning. Just to be sure, has restarting the server corrected it? Also, to be sure, are both `jellyfin-server` and `jellyfin-web` packages at 10.7.0-1?

I have tried restarting the jellyfin service as well as rebooting the entire vm. Unforttunately did not make a difference

**Comment by thw26** [comment]
Rebooted. Founded jellyfin-server was on 10.6.4-1. Upgraded to 10.7.0-1.

```
jellyfin-web/unknown,now 10.7.0-1 all [installed,automatic]
  Jellyfin is the Free Software Media System.

jellyfin-server/unknown,now 10.7.0-1 amd64 [installed,automatic]
  Jellyfin is the Free Software Media System.
```

No change in server behavior. I am no longer seeing errors populating the logs.

**Comment by thw26** [comment]
During the upgrade process I was asked to keep the `/usr/share/jellyfin/web/config.json` file. I said to keep the already used version. I swapped this with the new version and the GUI loads.

**Comment by iqfx** [comment]
Got the same question. I'm convinced this should not be the cause of the problem, Have you tried running this config?

**Comment by nemomty** [comment]
> During the upgrade process I was asked whether to keep the `/usr/share/jellyfin/web/config.json` file or update its version. I said to keep the already used version (default, N). I swapped this with the new version and the GUI loads.
> 
> ```
> mv /usr/share/jellyfin/web/config.json{,.bak}
> mv /usr/share/jellyfin/web/config.json.dpkg-dist /usr/share/jellyfin/web/config.json
> systemctl restart jellyfin.service 
> ```
> 
> Here's a diff from before the move:
> 
> **diff /usr/share/jellyfin/web/config.json.dpkg-dist /usr/share/jellyfin/web/config.json**
> 
> ```
> 2,41c2
> <   "includeCorsCredentials": false,
> <   "multiserver": false,
> <   "themes": [
> <     {
> <       "name": "Apple TV",
> <       "id": "appletv"
> <     }, {
> <       "name": "Blue Radiance",
> <       "id": "blueradiance"
> <     }, {
> <       "name": "Dark",
> <       "id": "dark",
> <       "default": true
> <     }, {
> <       "name": "Light",
> <       "id": "light"
> <     }, {
> <       "name": "Purple Haze",
> <       "id": "purplehaze"
> <     }, {
> <       "name": "WMC",
> <       "id": "wmc"
> <     }
> <   ],
> <   "servers": [],
> <   "plugins": [
> <     "playAccessValidation/plugin",
> <     "experimentalWarnings/plugin",
> <     "htmlAudioPlayer/plugin",
> <     "htmlVideoPlayer/plugin",
> <     "photoPlayer/plugin",
> <     "comicsPlayer/plugin",
> <     "bookPlayer/plugin",
> <     "youtubePlayer/plugin",
> <     "backdropScreensaver/plugin",
> <     "pdfPlayer/plugin",
> <     "logoScreensaver/plugin",
> <     "sessionPlayer/plugin",
> <     "chromecastPlayer/plugin"
> <   ]
> ---
> >     "multiserver": false
> ```

This fixes the issue

**Comment by iqfx** [comment]
Yes!! That fixed it for me.

replacing the contents of /usr/share/jellyfin/web/config.json
with https://github.com/jellyfin/jellyfin-web/blob/master/src/config.json

Fixed it for me and jellyfin is behaving as expected.

My last comment didn't age that well though ;-;

Thanks alot, ya'll are amazing!

**Comment by awb1015** [comment]
Fix worked for me but oddly only when accessing locally (although all recently added is gone).

When using my domain via Caddy I'm greeted with "Select Server" and there's an option listed called "undefined".  If I click the only button that states "Add Server" nothing seems to work, whether I enter localhost:8096 or 192.168.0.XX:8096

I doubt this is a coincidence but I'm not sure what to do
![screenshot](https://user-images.githubusercontent.com/8460460/110412309-37ad3c00-8049-11eb-999a-274b7accd883.png)
