### ISSUE TITLE
Black screen 10.7.0

### ISSUE THREAD

**Issue by litris** [jellyfin/jellyfin-web#2494]
**Describe The Bug**

Updated to version 10.7.0 and both the black screen appears in iOS and Web.

**Steps To Reproduce**

Black screen
**Expected Behavior**

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Platform: [Ubuntu 18.04.5 LTS server ]
 - Browser: [Firefox, iOS app]
 - Jellyfin Version: [10.7.0]

**Additional Context**

Updated from terminal with sudo apt update and apt upgrade and default option retain “config.json”

**Comment by tete2soja** [comment]
Hello,

I have the same issue with this error showing up in the console log:

```
loading installed plugins main.3309837d9db1402ea3a1.bundle.js:2:995428
{…}
_callbacks: Object { registered: (1) […] }
pluginsList: Array []
<prototype>: Object { … }
main.3309837d9db1402ea3a1.bundle.js:2:995480
Uncaught (in promise) TypeError: e is undefined
```

Maybe can help!

**Comment by litris** [comment]
`

> > Updated from terminal with sudo apt update and apt upgrade and default option retain “config.json”
> 
> Please make sure `config.json` contains plugins section:
> 
> https://github.com/jellyfin/jellyfin-web/blob/0368007ad9c6b5e8f70474e273d59fa0746ea8dc/src/config.json#L27-L41

Thanks!

And then I double the post when I report a BUG from the app iOS doesn't show up in github and then I have two posts equal.

Thanks for the info so I did it and it worked.
