### ISSUE TITLE
Subtitle language not displayed, seeing undefined

### ISSUE THREAD

**Issue by badgersmans** [jellyfin/jellyfin-web#2501]
**Describe The Bug**
I'm getting undefined in the subtitles selection

**Steps To Reproduce**

1. Select subtitles

**Expected Behavior**
I expect to see the language of the subtitles, but I'm getting undefined. Same thing is happening on the android app.

**Logs**

**Screenshots**
![image](https://user-images.githubusercontent.com/64647433/110569299-4dc51480-818f-11eb-9bf2-62622b074928.png)

**System (please complete the following information):**
 - Platform: Raspberry pi running latest raspbian buster
 - Browser: Latest version of Microsoft Edge Dev
 - Jellyfin Version: 10.7.0

**Comment by ThibaultNocchi** [comment]
Is your subtitle tagged with the language? Meaning if either it is a file it must end with `.fr.srt` for instance. Or if it's bundled in say a mkv, it should have metadata language.

**Comment by badgersmans** [comment]
No it is not tagged with the language, my filename for subs would be `subs.srt` so you're saying I need to name all my subs as `subs.en.srt`?

I've noticed if the subs are bundled with the video itself, it works fine.

**Comment by ThibaultNocchi** [comment]
Yup, that should work :)

**Comment by badgersmans** [comment]
Well that worked, amazing! is there anything similar to this that I should be aware of?

**Comment by ThibaultNocchi** [comment]
About subtitles? Not that I'm aware of :P

**Comment by badgersmans** [comment]
wait..but why are the subtitles not in one long line? why does it seem to be breaking the lines?

![image](https://user-images.githubusercontent.com/64647433/110604678-4c154400-81c3-11eb-8bac-6b920f742159.png)


I expect it to look like one long line, like 

> a list which, in the eyes of our allies, never existed.

and not like

> a list which, 
> in the eyes of our allies, 
> never existed.

**Comment by ThibaultNocchi** [comment]
Have you tried using this subtitles file in VLC or something? Maybe it's the way your file is

**Comment by badgersmans** [comment]
nope, doesn't happen in vlc

**Comment by badgersmans** [comment]
nevermind, it seems to only happen with that one in particular, all other subs don't have this issue

thanks for helping!

**Comment by ThibaultNocchi** [comment]
Well then idk, sorry. No problem!
