### ISSUE TITLE
Select Server page : Undefined

### ISSUE THREAD

**Issue by Pafzedog** [jellyfin/jellyfin-web#2508]
**Describe The Bug**

After upgrading to 10.7.0-1 from  latest 10.6, I couldn't have the web interface working correctly (no users shown, no libraries, and after several  refreshes, no more left vertical menu ...)
I dig a bit in Github issues with no success.
When I finally cleaned cookies, web site data, etc.. from my server  I was redirected to "select server page" where was an entry "Undefined" (screenshot attached) that I couldn't click and can't add my server with the correct URL "Failed to connect"
~~So I add my server again with loopback address : 127.0.0.1:8096 and I was able to log in to my jellyfin server.~~
~~But When I refresh browser, I'm back on the "Select server" page with two server : "undefined" and "My working server"~~

**Steps To Reproduce**

1. Go to my Server URL
2. Select the working server
3. refresh the browser
4. I'm redirected to "Select Server page" with "Undefined" server ~~and "My Workin server"~~

**What platform and operating system you're using**

Debian 10 Buster

**How you installed Jellyfin**

Uprgade from repository stable

**Any non-standard configurations you use**

Jellyfin is installed on a dedicated server on internet, behind nginx reverse proxy that handle https.

![Capture d’écran du 2021-03-13 13-35-40](https://user-images.githubusercontent.com/8932092/111030813-989b9200-8404-11eb-9a07-cc8d84542a0b.png)

**Comment by Pafzedog** [comment]
ok, so I misunderstood something.
I close this issue and will come back with better understanding of the problem.
sorry for that.

**Comment by carlocastoldi** [comment]
I have got the same problem if i try to connect outside of my local network. Would you care to share how you fixed it?

**Comment by carlocastoldi** [comment]
Newly opened jellyfin/jellyfin#5575 seems related

**Comment by mariosdev** [comment]
Yeah basically have the same issue. (I opened the issue). 

Should i have opened on the Jellyfin-web repo?

**Comment by Dudleydogg** [comment]
was there ever a solution for this?

**Comment by addmix** [comment]
> Newly opened [jellyfin/jellyfin#5575](https://github.com/jellyfin/jellyfin/issues/5575) seems related

I don't think this is the same issue. In my case, after transferring my Jellyfin instance from a bare metal install to a docker container, it seems that this is only a problem with browser caching of the server. All devices that previously connected to my server, either using a web browser or mobile app, all had to be reset/browser cache cleared before a successful connection was allowed to be made.

As I am also using nginx as a reverse proxy, I wonder if it is a problem with the proxy settings. Is there anything that can be done in nginx configs to invalidate the browser's cached data? Or would something need to be done within Jellyfin's backend to fix the caching issue?
