### ISSUE TITLE
It won't connect to Chromecast on Android 11

### ISSUE THREAD

**Issue by makmonty** [jellyfin/jellyfin-web#2541]
**Describe The Bug**
Recently I upgraded my phone to Android 11 and it stopped connecting to Chromecast. It just shows the spinner and nothing happens.

**Steps To Reproduce**
1. Open Jellyfin
2. Make sure your Chromecast is ready to receive a connection
3. Tap on the cast icon and select Google Cast
4. Select your Chromecast

**Expected Behavior**
It should connect to the Chromecast and the TV should show the Jellyfin logo, and the cast icon should show connected

**Logs**

**System (please complete the following information):**
 - Platform: Android 11
 - Jellyfin Version: 10.7.1

**Additional info**
- I tried with other video platforms, like Netflix, HBO and Youtube. All worked.
- I tried with a different phone with Android 10. It worked.
- It worked on my phone correctly before upgrading my Android version.

**Comment by rodrigost23** [comment]
Related to (maybe duplicate of) #303?
Also, I have the same problem.

**Comment by ThibaultNocchi** [comment]
Have you tried using the unstable cast client? Go to the JF app, in the settings, client preferences, and choose unstable for the cast client :)

**Comment by makmonty** [comment]
@ThibaultNocchi It didn't work :(
I forgot to say that I tried to connect to a Google Home Mini (the little round speaker) and it connects (with the stable cast client), so it's just the Chromecast that doesn't connect.

**Comment by ThibaultNocchi** [comment]
I'll have to refer you to https://github.com/jellyfin/jellyfin-chromecast then, cause this is outside of the app I'd guess

**Comment by rodrigost23** [comment]
Seems related to (and possibly duplicate of) jellyfin/jellyfin-android#303

**Comment by makmonty** [comment]
Yes, it looks the same problem, so I'll close this issue. Thanks.
