### ISSUE TITLE
Rounded progress bars!

### ISSUE THREAD

**Issue by crobibero** [jellyfin/jellyfin-web#255]
**Describe the bug**

Inner progress bar is rounded on dashboard and library pages
**To Reproduce**

1. Start sync
2. View progress (like the image below)
![image](https://user-images.githubusercontent.com/1992688/56448582-5cc22580-62de-11e9-9f5a-8f6324a45484.png)
3. ???
4. 

**Expected behavior**

Not so rounded

**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: docker
 - Browser: Brave browser (chrome) mobile
 - Jellyfin Version: 10.0.3.0

**Additional context**

**Comment by dkanada** [comment]
fixed by @grafixeyehero on master branch
