### ISSUE TITLE
Firefox: Can't play FLAC files with ID3 tags

### ISSUE THREAD

**Issue by atomheartother** [jellyfin/jellyfin-web#2577]
**Describe The Bug**
**On Firefox only**, not Chrome, some FLAC files systematically cause a playback error on Jellyfin when played. The files themselves are fine and play in any other media player I've tried them in, INCLUDING downloading them and opening them with Firefox locally. Firefox is misinterpreting them as mpeg files because of the ID3 tags, I guess? **There is no transcoding involved**, the file works great on Chrome and is sent as a FLAC to both Chrome and Firefox.

**Media Information**
`file`: `Audio file with ID3 version 2.3.0, contains:FLAC audio bitstream data, 16 bit, stereo, 44.1 kHz, 6960744 samples`

**Mediainfo:**
```
General
Complete name                            : Coda/01 We’re Gonna Groove.flac
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
File size                                : 17.8 MiB
Duration                                 : 2 min 37 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 948 kb/s
Album                                    : Coda
Album/Performer                          : Led Zeppelin / Led Zeppelin
Part                                     : 1
Part/Total                               : 1
Track name                               : We're Gonna Groove
Track name/Position                      : 1
Track name/Total                         : 12
Performer                                : Led Zeppelin
Encoded by                               : Exact Audio Copy   (Secure mode)
Label                                    : Swan Song
Genre                                    : Rock
Description                              : Track 1
Recorded date                            : 2008-09-10 / 2008
Writing library                          : flac.exe -6 -V -T "artist=Led Zeppelin" -T "title=We're Gonna Groove" -T "album=Coda" -T "date=1982" -T "tracknumber=01" -T "genre=Rock" -T comment="Track 1" -T "comment=(oan)" "comment=(oan)" " n)" (oan)"
BPM                                      : 0
Comment                                  : Track 1
MCDI                                     : Yes
ALBUMARTIST_CREDIT                       : Led Zeppelin
ALBUMARTISTSORT                          : Led Zeppelin
MUSICBRAINZ_ALBUMSTATUS                  : Official
MUSICBRAINZ_ALBUMTYPE                    : album
ARTIST_CREDIT                            : Led Zeppelin
ARTISTSORT                               : Led Zeppelin
ASIN                                     : B001BWTVOW
CATALOGNUMBER                            : WPCR-13141
COMPILATION                              : 0
RELEASECOUNTRY                           : JP
DISCC                                    : 1
PUBLISHER                                : Swan Song
MUSICBRAINZ_RELEASEGROUPID               : 61de0438-6c34-363f-904e-b4d6267c79b9
MUSICBRAINZ_RELEASETRACKID               : 882ffb62-bc45-3888-a7d0-d0ae6edbb80a
MEDIA                                    : SHM-CD
ORIGINALDATE                             : 1982-11-19
SCRIPT                                   : Latn
TRACK                                    : 1
TRACKC                                   : 12

Audio
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Duration                                 : 2 min 37 s
Bit rate mode                            : Variable
Bit rate                                 : 947 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Bit depth                                : 16 bits
Compression mode                         : Lossless
Stream size                              : 17.8 MiB (100%)
Writing library                          : libFLAC 1.2.1 (UTC 2007-09-17)
Language                                 : English
```

**Screenshots**
I don't have any interesting screenshots of the error, it's a generic error message: "Playback Error: This client isn't compatible with the media and the server isn't sending a compatible media format."

**System (please complete the following information):**
 - Platform: Linux and Windows
 - Browser: Firefox
 - Jellyfin Version: 10.7.1 and 10.8.0

**Additional Context**
I did some investigating, as far as I can see what is happening, again on firefox only, is that the browser is interpreting the FLAC file as a mpeg file, based on the GET response type as written by Firefox:

![image](https://user-images.githubusercontent.com/10134879/112833117-91c47e80-9096-11eb-9dd5-0353ad3e31d3.png)

I have *no clue* why it does that, but it does so consistently. This is either a bug in Firefox or a bug in Jellyfin Web / one of your dependencies. Looking at the requests, what happens is Firefox makes a HEAD request for the file, which correctly identifies it as `audio/flac`, then it makes the GET request, and *somehow* firefox goes "Right, so this bitstream is clearly MPEG".

I posted this issue in the main jellyfin repo at first (https://github.com/jellyfin/jellyfin/issues/5650) but I think it belongs here, the more I think about the bug.

**Comment by atomheartother** [comment]
This is still happening on the latest version.

**Comment by thornbill** [comment]
ID3 tags are not officially supported in the FLAC specification. As a result some decoders will not play FLAC files containing the tags. This is the case for the decoder included in Firefox. More details are covered in this thread on [Reddit](https://reddit.com/r/jellyfin/comments/nisoze/id3_tags_prevent_flac_playback/).
