### ISSUE TITLE
trakt.tv 2.0.0.0 plugin : can't autorize device

### ISSUE THREAD

**Issue by ToXinE** [jellyfin/jellyfin-web#259]
**Describe the bug**
I can't autorize device with trakt.tv plugin 1.0.0.0 or 2.0.0.0

**To Reproduce**
1. Go to admin panel, 
2. Click on plugin and select trakt.tv plugin 
3. select a user
4. click "Autorize"

**Expected behavior**
a QR code or a code should popup

**Logs**
no logs founds

**Screenshots**
![Image trak.Tv](https://i.imgur.com/wn9SUbC.png)

**System (please complete the following information):**
 - OS: Docker
 - Browser: Firefox
 - Jellyfin Version: 10.3.0

**Comment by oddstr13** [comment]
See jellyfin/jellyfin-plugin-trakt#13
