### ISSUE TITLE
Doesn't play next episode when clicking >|

### ISSUE THREAD

**Issue by agilob** [jellyfin/jellyfin-web#2596]
I noticed when 'Play next episode automatically' is not enabled in profile settings this button
![image](https://user-images.githubusercontent.com/2544251/115124522-352bf380-9fb2-11eb-8827-66ef5923e7ce.png)

doesn't do anything when clicked. Making it impossible to skip currently played episode to the next one.

present on  10.7.x

**Comment by tariq7t** [comment]
I can confirm that I have the same bug.

**Comment by HardRom4** [comment]
Can confirm still present on 10.7.5

**Comment by ananananana06** [comment]
Hey
Try stopping jellyfin from app tray then exit and relaunch it if you're still experiencing this i have no idea

**Comment by dmitrylyzo** [comment]
Current implementation (only if you start single item):
- if this option is enabled, the playbackmanager fills the play queue with the next episodes.
- if this option is disabled, the queue consists of only one item, and you simply have nowhere to skip.

I suppose you want it to work like on YouTube - just play to the end, stop and wait for user action, right?

**Comment by agilob** [comment]
"Play next episode automatically'" shouldn't disable manual actions, and if it does, then hide the pointless button. If the button is shown and clicked by a user, then start playing next file from album/directory/series instantly
