### ISSUE TITLE
Select the # sign

### ISSUE THREAD

**Issue by MRDJellyfin** [jellyfin/jellyfin-web#2602]
**Describe The Bug**

**Steps To Reproduce**

**Expected Behavior**

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Platform: [e.g. Linux, Windows, iPhone, Tizen]
 - Browser: [e.g. Firefox, Chrome, Safari]
 - Jellyfin Version: [e.g. 10.6.0]

**Additional Context**

In Windows 10 when the # sign is selected in the alphabet that appears on the right in movies, which is supposed to show all movies that start with numbers like any sign such as ¿? and ¡!, does not select anything. The same happens in any of the versions: Jellyfin Tray App, Jellyfin Desktop (Shim) and Jellyfin Media Player.

**Comment by perniczech** [comment]
Can confirm, filtering by '#' shows no results. 10.7.6 here.
