### ISSUE TITLE
File information: the back button of the mouse

### ISSUE THREAD

**Issue by MRDJellyfin** [jellyfin/jellyfin-web#2603]
In Movies, when you open the option in a movie to see the file information, the back button of the mouse does not work and once it was intended to be used, instead of returning to the menu of the movie in question by pressing the back arrow returns to the main movies menu. This happens in both Jellyfin Tray App and Jellyfin Media Player in Windows 10 (I know that in the Desktop or Shim version it is different because the use of the back button would have to be programmed, which I don't know how to do).

**Comment by dmitrylyzo** [comment]
Fixed by #2660
