### ISSUE TITLE
TV Mode arrow key navigation broken with theme enabled.

### ISSUE THREAD

**Issue by n8detar** [jellyfin/jellyfin-web#2608]
**Describe The Bug**
When the web client is in TV mode with a custom CSS theme enabled using arrow keys to navigate, the page doesn't scroll with the selection. So if you are at the home and use the down arrow to navigate down the page the page remains scrolled at the top of the screen while the selection moves off.

**Steps To Reproduce**

1. Enable any theme. (I tried JellySkin: `@import url("https://prayag17.github.io/JellySkin/default.css");` JellfyFlix: `@import url("https://prayag17.github.io/JellyFlix/default.css");` and Monochromic: `@import url('https://ctalvio.github.io/Monochromic/default_style.css');)`
2. Enable TV Mode (User Settings -> Display -> Display mode (3rd one down) -> TV -> Save -> Refresh Page)
3. Go to the home page
4. Use Arrow keys to navigate
5. Move selection down
6. The page doesn't scroll with the selector

**Expected Behavior**
When navigating with arrow keys it should behave the way it does without a theme enabled.

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Platform: Linux Docker
 - Browser: Chrome
 - Jellyfin Version: 10.7.2

**Additional Context**

**Comment by dmitrylyzo** [comment]
This is because custom theme sets `overflow: scroll` on page container, and `scrollManager` only works with elements marked as `scrollX`/`scrollY`.

[This](https://github.com/dmitrylyzo/jellyfin-web/tree/scrollmanager-dialogs-2) may help, but requires more tests because `scrollManager` doesn't support cascade scrolling.
