### ISSUE TITLE
Subtitle selection for external player 

### ISSUE THREAD

**Issue by Altereno** [jellyfin/jellyfin-web#2615]
Is it possible to pass the subtitle selection from Jellyfin to the external player?

![Screenshot_20210309-235056_Jellyfin.jpg](https://user-images.githubusercontent.com/68705413/110582857-6c48f280-8132-11eb-8bf8-761cf578b0a9.jpg)

When subtitles are selected, I have to reselect them in the external player (VLC).

**Comment by nielsvanvelzen** [comment]
Moved to jellyfin-web because the Android app doesn't generate the playback URL.
