### ISSUE TITLE
Jellyfin loses fullscreen when navigating back

### ISSUE THREAD

**Issue by bugfixin** [jellyfin/jellyfin-web#262]
**Is your feature request related to a problem? Please describe.**
When viewing a video fullscreen in browser, I click the back icon and the jellyfin browser loses fullscreen, making it so that I must re-enter fullscreen with the next video viewed.

**Describe the solution you'd like**
If fullscreen is entered, stay in fullscreen until it is specifically exited (esc pressed, fullscreen button clicked again, doubleclick on video, etc)

**Describe alternatives you've considered**
It's possible to force fullscreen by hitting f11 but I would much prefer a solution that doesn't require a keyboard with f-buttons

**Additional context**
n/a

**Comment by DrPandemic** [comment]
Do you have an example of a website working like that? To me it doesn't sound like a standard/expected behavior.

**Comment by anthonylavado** [comment]
Hrm... YouTube lets me scroll down when I press the fullscreen button on the video, but it definitely breaks back to normal when I navigate back. I also don't know of any website that does that.

**Comment by bugfixin** [comment]
I do not have any exact examples - the idea of fullscreen web browsing isn't very popular on the majority of the public web, but as jfweb is effectively a dedicated media player site, I don't think we should surprise users by exiting fullscreen when simply clicking a ui element to navigate back. If we are exiting fullscreen, perhaps a better ui icon would be an X as with chrome's exit fullscreen icon.

Youtube will remain in fullscreen when navigating forward and back between videos, but exits when a non-video page is visited. Netflix is similar.
