### ISSUE TITLE
Can't see where you're navigating in TV Mode

### ISSUE THREAD

**Issue by catscratchedme** [jellyfin/jellyfin-web#2623]
**Describe The Bug**

When Display is set to TV Mode, navigating through the page with arrow keys does not scroll the screen when the selected element is off-screen

**Steps To Reproduce**

1. Go to: User > Settings > Display
2. Under Display Mode, select TV, and then save
3. Go to the home page
4. One of your tiles will be selected/enlarged by default, to indicate where you can start navigating from
5. Navigate downwards with the arrow keys, even after the selected element is off the screen, the screen doesn't follow it. This means you can't see where you're navigating.

**Expected Behavior**

The screen should automatically scroll to keep your selected element on screen as you navigate with the arrow keys

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Firefox
 - Jellyfin Version: [e.g. 10.7.2]

**Additional Context**
The problem happens both in jellyfin-web and Jellyfin Media Player

**Comment by dmitrylyzo** [comment]
Custom CSS?
It doesn't currently work for custom themes where scrollable element has been changed (#2608).

**Comment by catscratchedme** [comment]
No custom CSS.

But yes, refreshing after I change to `Display mode` makes it so the screen scrolls with navigation. Thanks, didn't know that!

I noticed something else now:
When I have the user profile icon selected, and then navigate left to the search bar, the whole page shifts a bit. I'll go ahead and open a new bug for that. This is happening in Firefox.
