### ISSUE TITLE
Search page

### ISSUE THREAD

**Issue by zdabing** [jellyfin/jellyfin-web#2628]
When I enter keywords to search for movies, there are a lot of movies, and there is no more button in the search interface, which causes the results page to display incompletely and cannot display all matching movies;

Can you add a more button in the search interface, when the search result is much

**Comment by SightSpirit** [comment]
This is a must-have. Jellyfin basically has a broken search engine if it's incapable of displaying all possible results.

**Comment by thornbill** [comment]
Feature requests should be made at https://features.jellyfin.org/. Thanks!
