### ISSUE TITLE
Primary Images fail to load when UI requests non integer scaling

### ISSUE THREAD

**Issue by tlaporte** [jellyfin/jellyfin-web#2629]
**Describe The Bug**

Depending on window size, the UI may request primary images scaled to non integer values. In these cases, the request fails due to a validation error.

**Steps To Reproduce**

1. In Chrome developer tools, set device emulation to "Responsive", 1549x1236, 100%.
2. Go to any tv show/movie in your library.
3. Observe that the primary image is just a blurred placeholder.
4. In your network log there should be a failed GET request against the server, with an error message like "The value '387.25' is not valid."
5. If the emulator settings that I used don't work on your machine, it should be reproducible at any resolution where the UI requests a non integer width or height for the image.

I didn't see this with non primary images, but it might be possible.

**Expected Behavior**

Primary image should load, no network error should appear in the logs.

Perhaps UI should round the width/height scaling values that it requests to the nearest integer.

**Logs**

Failed GET response:
```json
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-249cb87145beda45b076d4962ecaf039-6392203a54514744-00",
  "errors": {
    "fillWidth": [
      "The value '387.25' is not valid."
    ]
  }
}
```
There are no error logs on the server side.

**Screenshots**

![Screenshot 2021-04-28 202229](https://user-images.githubusercontent.com/2347599/116488076-87e19700-a85f-11eb-8dfb-877931d0ca4c.png)

**System (please complete the following information):**

 - Platform: [Windows]
 - Browser: [Firefox, Chrome]
 - Jellyfin Version: [e.g. 10.7.2]

**Comment by dmitrylyzo** [comment]
Should be fixed in next release: https://github.com/jellyfin/jellyfin-apiclient-javascript/pull/167

**Comment by cvium** [comment]
Duplicate #2587
