### ISSUE TITLE
Stuck at start of Jellyfin on Samsung TV on Tizen OS

### ISSUE THREAD

**Issue by durgesh2020** [jellyfin/jellyfin-web#2632]
If I set the server on raspberry pi 4, and turn the raspberry pi 4 off, Jellyfin app for Tizen os on Samsung The Frame 2020 goes into loop. It just displays the rotating circle progress bar. There we can't go to any menu through remote.

**Steps To Reproduce**

1.  Install and setup Jellyfin server on raspberry pi 4 B (4GB model) 
2. Install Jellyfin app on Tizen os (Samsung The Frame TV 55 inches)
3. Login to Jellyfin server through app on Samsung TV
4. Turn off the TV or exit the Jellyfin app
5. Stop the Jellyfin server (by shutdown or stop Jellyfin service)
6. Open Jellyfin app on Samsung TV

**Expected Behavior**
Timeout after N seconds if no server is found (to which login was made earlier) and display server selection screen

**System (please complete the following information):**
 - Platform: Tizen
 - Browser: Jellyfin App on Samsung TV
 - Jellyfin Version: 10.7.2

**Additional Context**
The app on Samsung TV can timeout searching for server (if server is down or not reachable) and return to select server screen or add server screen. It is stuck on connecting server forever. There is no solution than manually uninstall and reinstalling app if server is down.

**Comment by dmitrylyzo** [comment]
https://github.com/jellyfin/jellyfin-tizen/issues/75#issuecomment-829498869

**Comment by durgesh2020** [comment]
Thank you Dmitry! I rebuilt it using new link and it is working fine. But, now I am unable to play DTS 5.1 files on my TV. My TV supports DTS.

**Comment by dmitrylyzo** [comment]
https://github.com/jellyfin/jellyfin-web/blob/e27131edf0462c557d1c53ea4ee65fa6f4ac5b5c/src/scripts/browserDeviceProfile.js#L392-L395
They should be "Direct streamed" (if the video codec is supported).
Is Samsung starting to support DTS again?

**Comment by durgesh2020** [comment]
Thank you for your quick response. Yes Samsung supports DTS 5.1. I have tested this with Emby with same files. My hardware acceleration is OpenMax on Raspberry pi 4 4 GB model. On Jellyfin it doesn't work on TV but works in browser on desktop. My TV is Samsung The Frame 2020 55".

**Comment by MrTimscampi** [comment]
> Yes Samsung supports DTS 5.1

From the manual of your TV:

> The DivX and DTS codecs are not supported by the Samsung TV models released in 2020.

Source: https://www.samsung.com/ca/support/model/QN50LS03TAFXZC/

**Comment by durgesh2020** [comment]
Yes it supports DTS files. My TV model is QA55LS03TAKXXL. I tried playing those files on Emby and they just play well.

**Comment by durgesh2020** [comment]
I am using a home theatre from Sony. Model number is IV 300. That supports all the codes.

**Comment by dmitrylyzo** [comment]
@durgesh2020 Try unchecking `Allow audio playback that requires transcoding` for your user (from Dashboard).
![Screenshot_20210509_191925](https://user-images.githubusercontent.com/56478732/117579445-833c9e80-b0fb-11eb-923a-09fd718b5af2.png)
Not sure if that helps with audio passthrough.
