### ISSUE TITLE
Live TV .m3u opens own stream for every client

### ISSUE THREAD

**Issue by teminvictus** [jellyfin/jellyfin-web#2667]
I wanted to use Jellyfin to stream live tv.
I am using the LiveTV feature with a m3u tuner. The streams are coming from my backend at home.
Streaming works fine, but each client is opening a new stream to my backend, even if it is the same channel.

I was kinda assuming that Jellyfin will distribute the channel to all clients.
So when 2 clients are watching the same channel, only one stream to my backend is used.

Am I getting this wrong?

**Comment by cvium** [comment]
Your assumption is indeed incorrect. We do not currently re-use transcode segments. Any time a client requests an encode/transcode a new one is created.
