### ISSUE TITLE
No option to record in 10.3.0

### ISSUE THREAD

**Issue by skug67** [jellyfin/jellyfin-web#268]
Tuner device = HDHomeRun Prime
Live TV plays fine but there's no option to record a program (or an entire series)

**To Reproduce**

1. Go to LiveTV
2. Click on Programs
3. Scroll down to a show you want to watch/record and click on it
4. Given option to play but not to record

**Expected behavior**
Recording should be an option

**System (please complete the following information):**
 - OS: Debian
 - Browser: Safari
 - Jellyfin Version: 10.3.0
 - Reverse proxy: apache

**Additional context**

**Comment by skug67** [comment]
I just built the debian package from the branch containing this commit and still have the same problem.

**Comment by skug67** [comment]
Update -- it's fixed but there seems to be some sort of caching going on that kept it from showing up.  I was checking on different browsers and it was working when I fired up one I hadn't used for a while.  Then when I went back to a browser I'd used more frequently and cleared a week's worth of history, the recording buttons popped up.

**Comment by sparky8251** [comment]
Caching is a major pain point. There is code put in place to return fake cache results to a browser, tricking the browser into not requesting changed resources.

We tried fixing it once but it made things even worse so we've largely left it alone. It's on the docket however!
