### ISSUE TITLE
Using any Filter in Playlists screen activates all "Features" filters permanently and irreversibly

### ISSUE THREAD

**Issue by deanishe** [jellyfin/jellyfin-web#2744]
**Describe The Bug**
Using Filter on the Playlists screen leaves all "Features" filters permanently active/checked, severely breaking Playlists.

**Steps To Reproduce**

1. Go to Playlists
2. Go to Filters
3. Select Unplayed or a genre (I haven't tried anything else)
4. Go back to Playlists
5. All "Features" filters are now active and cannot be deactivated. Unchecking them has no effect. They remain active and will be checked when you re-open the Filters screen.

**Expected Behavior**
Only filters I select are active and filters I deselect are not active

**System (please complete the following information):**
 - Platform: Linux (Debian Buster)
 - Browser: Firefox or iOS Jellyfin app
 - Jellyfin Version: 10.7.5-1 from jellyfin-web_10.7.5-1_all.deb

**Additional Context**
The only way to reset the filters in the iOS app is to delete it and re-install. Deleting the server from the app configuration does not delete the associated settings for some reason.

**Comment by cris01ca** [comment]
I'm seeing the same behavior when I'M trying to view one of my movie library.  The row at the bottom stays selected and there is no way to unselected them.  The same happens on the android app.  

opensuse tumbleweed
Chrome 91
Jellyfin Version : 10.7.6

**Comment by anthonylavado** [comment]
Myself and the iOS app maintainer aren't seeing this at the moment. I don't have normally have playlists so I created two (one of some music, another of some movies), and I can add filters with no issue. When I come back to the playlists screen, I see the little exclamation mark icon warning me that a filter is in place.

I can navigate out to another screen, come back to playlists, and see that the filter is still present. I can tap on filters again, unselect the filters I applied, and it's back to normal.

Testing on iOS 14.6 with the release version of Jellyfin Mobile, with 10.7.6 running on Debian (Buster).

**Comment by deanishe** [comment]
I checked in the devtools on Firefox (macOS), and the filter keys are all set to `null` in localStorage. Deleting the filter keys with value `null` fixes the playlist filtering.

**Comment by deanishe** [comment]
So, I opened Playlists then Filter, and selected "Unplayed". The following entries were added to Local Storage (Firefox 89.0.2 macOS):

<img width="734" alt="image" src="https://user-images.githubusercontent.com/747913/124670614-84e4d180-deb4-11eb-8aa2-c92d4a7dddf8.png">

Deleting all the entries with value `null` deactivates all the erroneously activated filters.

**Comment by lmas** [comment]
Hmm is this block related to this issue?

https://github.com/jellyfin/jellyfin-web/blob/5c09077a2f12ae44e7b7d356ea8d9f35862b0b60/src/controllers/list.js#L1034-L1040

**Comment by deanishe** [comment]
I was also affected by the usersettings HTTP 500 bug #2507. After deleting all of Jellyfin's data and settings (which I'd sooner not have to do again…), both that problem and this one have disappeared.

So, it appears that this issue is also related to the user data oopsie causing login and settings to be unavailable to admin users.

Should I close this issue, seeing as it seems to share an underlying cause with others, or leave it open?
