### ISSUE TITLE
Subtitles are not visible once the internet browser's bar is hidden

### ISSUE THREAD

**Issue by FluffyDiscord** [jellyfin/jellyfin-web#2755]
**Describe The Bug**
So basically my LG TV has internet browser which I use to access jellyfin server and play stuff. I noticed, that when the browser's url bar goes away, subtitles are no longer visible (rendered?) and I have to bring in back up. I have tried to burn in the subtitles via dashboard settings, but it seems like that does not work.

**Steps To Reproduce**
You need to have LG TV, I presume.

1. Play any movie with a subtitles on
2. Wait about 5 mins for the url bar to hide itself

**Expected Behavior**
Subtitles are visible even when browser's url bar goes away.

**Logs**
Don't think it's relevant. Also, can't get much from tv's browser.

**Screenshots**
Don't think it's relevant.

**System (please complete the following information):**
 - Platform: WebOS
 - Browser: build in
 - Jellyfin Version: 10.7.6

**Additional Context**
none

**Comment by TheLastProject** [comment]
I updated my Docker to 10.8.0 Alpha 5 and this issue appears to be fixed on my LG WebOS TV (running WebOS 03.21.20).

**Comment by Hoohm** [comment]
Works for me too with the `jellyfin/jellyfin:unstable` docker image.

**Comment by thornbill** [comment]
Closing since this appears to be resolved.
