### ISSUE TITLE
Song details page shows album artist instead of song artist

### ISSUE THREAD

**Issue by laurinneff** [jellyfin/jellyfin-web#2793]
**Describe The Bug**
The song details page shows the album's artist instead of the song artist, while in the album page it shows the song artist

**Steps To Reproduce**

1. Set the metadata of a song to have a different album and song artists to make the issue easily visible

**Expected Behavior**
The song details page should display the song artist 

**Screenshots**

Song details: 
![Screenshot_20210717-231701.jpg](https://user-images.githubusercontent.com/29987831/126049629-1cfd99b0-bbee-4959-abbb-df521b5d9a61.jpg)
Album: 
![Screenshot_20210717-231712.jpg](https://user-images.githubusercontent.com/29987831/126049635-93d926d3-310a-4cf4-8eaa-35bec5f6aa1f.jpg)

**System (please complete the following information):**
 - Platform: Android 11
 - Browser: Android WebView 91.0.4472.120 in Jellyfin Android 2.3.0-beta.6, also happens in other browsers
 - Jellyfin Version: 10.7.6

**Comment by SegiH** [comment]
Based on your screenshot, it looks like you're having the problem only on the Android client.

Have you tried a newer version of the Android Jellyfin app ? 

I am using version 2.3.2 from F-Droid (Google Play Store has 2.3.3) also on Android 11 and also on JF 10.7.6 and tested this out by changing the album artist for 1 song and I don't see the same behavior when I play the song and tap on the now playing bar so it opens up the full now playing view. It is showing the Artist, not the Album Artist.

**Comment by laurinneff** [comment]
I don't see how the client is relevant, since the UI is a web browser running Jellyfin Web. But anyways, I get this issue on JF Android 2.3.3

I didn't mean the now playing page. You can get to a page with details about the song by searching

**Comment by SegiH** [comment]
I don't think you understand what I was asking. Is this problem also visible in the Web UI, on Android or both ?

**Comment by laurinneff** [comment]
Still an issue
