### ISSUE TITLE
"Group content" does not merge same entries

### ISSUE THREAD

**Issue by zeus86** [jellyfin/jellyfin-web#2796]
**Describe The Bug**
given 2 movie libraries: 4k and non-4k (to avoid cpu-heavy transcoding for some users). If a movie is present in one resolution (e.g. 1080p) in the non-4k lib and in 4k in the 4k-lib, there are two entires in the library-view of the same movie if "group content" for that user is active. If various resolutions of a movie reside in the same library, they get grouped, and indicated with a counter in the overview. 

**Expected Behavior**
identical entries of same resolution should be grouped if they are in different libraries when "group content" is active for that libs. In this case the state of how far the movie has been watched, is also not grouped (but it is on different versions in the same lib, even if on is an extended cut or something like that, but that's a different story).

**Screenshots**
Same Library (720 and 1080p):
![Screenshot_20210719_224146](https://user-images.githubusercontent.com/11415964/126224608-98455bc0-2dcb-484b-8586-3b859438fe99.png)

Different Library (1080p and 2160p):
![Screenshot_20210719_224157](https://user-images.githubusercontent.com/11415964/126224723-7d6d64d4-f423-4f1c-aec4-7729f56d2e90.png)

**System (please complete the following information):**
 - Platform: Linux, Ubuntu 20.04, x86_64
 - Browser: Firefox
 - Jellyfin Version: 10.7.6

**Additional Context**
I find this quite annoying, because i cannot easily distinguish, which version is which in this case. If anyone could provide some CSS-magic to show all the resolutions to an entry as a tag in the library overview would also be nice, and would definately help here, but i think this is a bug anyways.

**Comment by cvium** [comment]
Not a bug. It works as intended. There's a feature request here https://features.jellyfin.org/posts/350/auto-group-movies-with-different-versions and documentation on the movie grouping here https://jellyfin.org/docs/general/server/media/movies.html#multiple-versions-of-a-movie

**Comment by zeus86** [comment]
> Not a bug. There's a feature request here https://features.jellyfin.org/posts/350/auto-group-movies-with-different-versions and documentation on the movie grouping here https://jellyfin.org/docs/general/server/media/movies.html#multiple-versions-of-a-movie

movies DO acutally moerge together like requested in the feature request you mentioned, but not, if the same movies are from different libraries. if i'd have the same two movies in the same library, they would get merged (see screenshots).

**Comment by zeus86** [comment]
To clarify:

This will result in merged entries:
```
Movies
└── Best_Movie_Ever (2019)
    ├── Best_Movie_Ever (2019) - 1080P.mp4
    └── Best_Movie_Ever (2019) - 2160P.mp4

```

But this will not (if "Movies" and "Movies_4k" are different libraries, but shown as Group together like described):
```
Movies
└── Best_Movie_Ever (2019)
    └── Best_Movie_Ever (2019) - 1080P.mp4
Movies_4k
└── Best_Movie_Ever (2019)
    └── Best_Movie_Ever (2019) - 2160P.mp4
```
...so please reopen

**Comment by zeus86** [comment]
> It's still not a bug. What you're asking for is nice but it's a feature request...

If an existing feature only works under certain circumstances, but not in others, i'd call this a bug, but anyways, let it be a feature request...

**Comment by Shadowghost** [comment]
> If an existing feature only works under certain circumstances, but not in others, i'd call this a bug

Every functionality has its prerequisites to function as intended.
I think our docs are quite clear about the required files structure to make the scanner work as intended.
Anything going beyond that is a feature request since it extends the existing behaviour.

**Comment by nitschis** [comment]
Was there ever a feature request open for this?

**Comment by thornbill** [comment]
Looks like this one mentioned in the other comments would cover it?

https://features.jellyfin.org/posts/350/auto-group-movies-with-different-versions

**Comment by nitschis** [comment]
Maybe a solution like this would be better?

https://features.jellyfin.org/posts/1449/merge-versions-across-library-folders-in-the-same-library

**Comment by Einzelkind1337** [comment]
Three solutions:
1. Put 4K in the same folder as HD
2. Use Cover Artwork with 4K on it for 4K movies
3. (not sure, but I think it can do it): Use "Jellyfin Enhanced" Plugin to display resolution on cover.
