### ISSUE TITLE
Movie thumb view doesn't work properly

### ISSUE THREAD

**Issue by bugfixin** [jellyfin/jellyfin-web#280]
**Describe the bug**
When switching the movie library to thumb view, items without a Thumb image do not display properly

**To Reproduce**
1. Go to your movies section
2. Change view to Thumb
3. Note the lack of buttons/links on items without Thumb images.

**Expected behavior**
All items to be represented properly, regardless of image availability.

**Logs**
No errors thrown in web console or jellyfin logs.

**Screenshots**
![image](https://user-images.githubusercontent.com/31485244/56769450-13525a00-6766-11e9-8607-c625712b7023.png)

**System (please complete the following information):**
 - OS: Debian
 - Browser: Chrome
 - Jellyfin Version: 10.3.1

**Additional context**

**Comment by bugfixin** [comment]
Found this was resolved by #264. Can we push this to release-10.3.z branch?

**Comment by anthonylavado** [comment]
@bugfixin I think Josh responded on Matrix, but for clarity here - it’s pretty much immpossible to forward port if something got put in to master. It breaks many things about the release branch unfortunately

**Comment by bugfixin** [comment]
Makes sense, thanks!
