### ISSUE TITLE
Image play doesn't play the correct version 

### ISSUE THREAD

**Issue by luky92** [jellyfin/jellyfin-web#2802]
**Describe The Bug**
If multiple versions of the movie are present when choosing a version only the play button on top actually plays chosen version the image play button still plays the top version from the version select 

**Steps To Reproduce**
upload multiple versions of a movie 
open the media info 
choose a different in the version select  
click the play button on the image 
the default version of the movie will play instead of the chosen version  

**Expected Behavior**
upload multiple versions of a movie 
open the media info 
choose a different in the version select  
click the play button on the image
the correct ( chosen) version of the movie plays 

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Platform: Linux x64 Ubuntu 20.04
 - Browser Chrome
 - Jellyfin Version: 10.7.6

**Additional Context**

**Comment by luky92** [comment]
still present

**Comment by neingeist** [comment]
Similar to #2370?

**Comment by thornbill** [comment]
Good call. This is a duplicate.
