### ISSUE TITLE
Refreshing the page when watching a video results in a white page of death

### ISSUE THREAD

**Issue by bugfixin** [jellyfin/jellyfin-web#289]
**Describe the bug**
Refreshing the page while watching a video results in a themeless page with no video playing (videoosd.html)

**To Reproduce**
1. Begin watching a video
2. Refresh the page
3. No video plays, the background is white

**Expected behavior**
The video to resume playing, or at least restart, or at worst just redirect me to a functioning media library page.

**Screenshots**
![image](https://user-images.githubusercontent.com/31485244/56829907-d0ea5500-6819-11e9-90f8-dd065a7e8142.png)

**System (please complete the following information):**
 - OS: Debian server, windows client.
 - Browser: Chrome
 - Jellyfin Version: 10.3.1

**Comment by joshuaboniface** [comment]
This has happened to me for ages in Emby and Jellyfin - glad to get it finally fixed!

**Comment by dkanada** [comment]
fixed by #307
