### ISSUE TITLE
jellyfin-web.spec change request

### ISSUE THREAD

**Issue by pjwelsh** [jellyfin/jellyfin-web#2891]
**Describe The Bug**

(apologies for the lack of code-block newlines... can't seem to google my way to getting them to work yet)
jellyfin-web.spec contains lines:
`%if 0%{?centos}
BuildRequires:  yarn`
With CentOS 7 and CentOS 8, there is a "yarnpkg" package than be easily installed via the epel based repositories (epel, epel-multimedia).

**Steps To Reproduce**

Change above lines (at least):
`%if 0%{?centos}
BuildRequires:  yarnpkg`
This works for both CentOS 7 and CentOS 8 for my testing:
1 Build-user: install jellyfin-web src.rpm
2 Build-user: edit ~/rpmbuild/SPECS/jellyfin-web.spec as noted above
3 Root-user: install yarnpkg:
`# dnf install yarnpkg
...
Installing:
 yarnpkg           noarch  1.22.10-2.el8                                       epel-multimedia  1.0 M
Installing dependencies:
 nodejs            x86_64  1:10.23.1-1.module_el8.4.0+645+9ce14ba2             appstream        8.9 M
 npm               x86_64  1:6.14.10-1.10.23.1.1.module_el8.4.0+645+9ce14ba2   appstream        3.7 M
Installing weak dependencies:
 nodejs-full-i18n  x86_64  1:10.23.1-1.module_el8.4.0+645+9ce14ba2             appstream        7.3 M
Enabling module streams:
 nodejs                    10
...`
4 Build user rpmbuild spec file:
`rpmbuild -bb ~/rpmbuild/SPECS/jellyfin-web.spec
...
Processing files: jellyfin-web-10.7.6-1.el8.noarch
Provides: jellyfin-web = 10.7.6-1.el8
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Checking for unpackaged file(s): /usr/lib/rpm/check-files /home/builduser/rpmbuild/BUILDROOT/jellyfin-web-10.7.6-1.el8.x86_64
Wrote: /home/builduser/rpmbuild/RPMS/noarch/jellyfin-web-10.7.6-1.el8.noarch.rpm
...`

**System (please complete the following information):**
 - Platform: Linux CentOS 7 and CentOS 8
 - Browser: NA
 - Jellyfin Version: 10.7.6

**Additional Context**
There are no CentOS 8 builds, easy to build with above changes (and include in the repo?).

**Comment by thornbill** [comment]
Yarn was removed in https://github.com/jellyfin/jellyfin-web/pull/2476
