### ISSUE TITLE
Cannot see "More Like This" titles on portrait when playing music

### ISSUE THREAD

**Issue by cegfault** [jellyfin/jellyfin-web#2896]
When viewing the web interface from any phone or tablet, while in portrait, the playing status bar overlaps the "More Like This" titles.

See screenshot (note that the text cannot be read at the very bottom):
![Screenshot_20210827-132145_Jellyfin](https://user-images.githubusercontent.com/53021412/131187079-03437b67-44f2-4a91-aa68-acdbffae1986.png)

**Comment by thornbill** [comment]
There was an old issue for this that had been closed for going stale. I have reopened it so we can track there. 

https://github.com/jellyfin/jellyfin-web/issues/1035
