### ISSUE TITLE
 Cannot see "More Like This" titles on portrait when playing music

### ISSUE THREAD

**Issue by cegfault** [jellyfin/jellyfin-web#2898]
### Describe the bug

When viewing the web interface from any phone or tablet, while in portrait, the playing status bar overlaps the "More Like This" titles.

1. Have any android phone or tablet in portrait
2. Click on any song or album to start playing
3. Scroll to bottom
4. Observe that the text/titles for "More Like This" cannot be read.

See screenshot (note that the text cannot be read at the very bottom):
![Screenshot_20210827-132145_Jellyfin](https://user-images.githubusercontent.com/53021412/131187331-e74bbcde-4c3d-4815-8268-ec5cce33e07f.png)

### Application version

2.3.1

### Where did you install the app from?

F-Droid

### Device information

Multiple phones and tablets

### Android version

Android 11, LineageOS 18.1, etc

### Jellyfin server version

(nightly release)

### Which video player implementations does this bug apply to?

- [X] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by thornbill** [comment]
There was an old issue for this that had been closed for going stale. I have reopened it so we can track there. 

https://github.com/jellyfin/jellyfin-web/issues/1035
