### ISSUE TITLE
[BUG] Changing URL Does Not Change URL.

### ISSUE THREAD

**Issue by Facinorous-420** [jellyfin/jellyfin-web#2906]
I'm having a problem with JF inside of iFrames. 

It loads fine inside the iFrame, and you can use it no issues.
Though the issues arises when I try to add a button on my site that changes the iFrame url to a specific page in my JF instance, let's say item 1 detail page.

If you are on your JF homepage, the button works and brings you to `item 1`'s detail page. 
Though, let's say you are already deep in your JF instance looking at `item 2`'s detail page. When you click the button to chsnge the iFrame url- it does not switch to `item 1`'s detail page and stays on `item 2`'s detail page. This applies for whatever page you were on previously trying to click the button. It'll just stay on that page. The button will only work if you are on the JF homepage dashboard. 

This is relevant due to Organizr. Organizr works due to iFrames and when I have my Jellyfin in Organizr the Organizr home page buttons which make your page jump to the Jellyfin iFrame and switch its url. Sadly because of the issue above, it only works in this way when your tab was set to the JF homepage.

I tested this outside of Organizr in native html and js in a static website to make sure it was not Organizr causing it, and sure enough I was able to reproduce it.

If I set my url to my homepage, then try changing the iframe it does not work

If I set my url to my homepage, then browse in my JF, then try changing the iframe does not work.

If I set my url to my homepage, then browse in my JF, and push the back button until I'm back on the homepage, changing the iframe works

__

After discussing this in the chat, I have found that this is not just in iFrames but also reproducible by just switching the URL in your browser.
You can browse to an item in your library, copy it's url then browse to another item. Paste the others item into your browser url and it wont switch to the previous item and stay wherever you were.

**Comment by joshuaboniface** [comment]
Transferred to Web repository as this seems front-end related.
