### ISSUE TITLE
Subtitle editor doesn't send isPerfectMatch query when searching

### ISSUE THREAD

**Issue by MBR-0001** [jellyfin/jellyfin-web#2916]
**Describe The Bug**
When searching for subtitles the server allows isPerfectMatch query to be sent ([here](https://github.com/jellyfin/jellyfin/blob/master/Jellyfin.Api/Controllers/SubtitleController.cs#L126)) that tells it whether to only return subtitles that match perfectly, the problem is that the web client never sends it ([here](https://github.com/jellyfin/jellyfin-web/blob/master/src/components/subtitleeditor/subtitleeditor.js#L247))

**Steps To Reproduce**
1. Open any movie/episode
2. Open the subtitle editor
3. Click on the search button
4. Notice that there are subtitles that don't match perfectly despite `Only download subtitles that are a perfect match for my video files` being checked

**Expected Behavior**
The subtitle editor sends the isPerfectMatch query and server returns only subtitles that match perfectly 

**Logs**
N/A

**Screenshots**
![](https://cdn.mbr.pw/49828227690135577.png)
![](https://cdn.mbr.pw/49828572944269338.png)

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Brave v1.29.77 
 - Jellyfin Version: 10.7.6

**Additional Context**
N/A

**Comment by thornbill** [comment]
I believe that setting only applies to automatically downloading subtitles.
