### ISSUE TITLE
Jellyfin Web version number is still displayed as 10.7.6

### ISSUE THREAD

**Issue by Soizzer** [jellyfin/jellyfin-web#2973]
After the 10.7.7 version is installed, the Jellyfin Web version number is still displayed as 10.7.6.

![jellyfin web](https://user-images.githubusercontent.com/73036854/133563583-8c717647-35f4-45e4-b238-cce94613b0f7.png)

**Comment by thornbill** [comment]
This is a known issue that will be fixed in future releases by https://github.com/jellyfin/jellyfin-web/pull/2934.
