### ISSUE TITLE
Subtitles doesn't display correctly on latest Chrome version.

### ISSUE THREAD

**Issue by jomp16** [jellyfin/jellyfin-web#298]
**Describe the bug**
Subtitles doesn't display correctly on Chrome (it's on top, almost not visible)

**To Reproduce**
1. Play some video with subtitles (not hardcoded, like SRT)
2. Check on top of player, subtitles is almost outside of the frame.

**Expected behavior**
Subtitles should be at the bottom, visible.

**Logs**
No log, since this isn't Jellyfin error, but a Chrome one.

**Screenshots**
No screenshot yet.

**System (please complete the following information):**
 - OS: Docker on Linux
 - Browser: Chrome 74.0.3729.108
 - Jellyfin Version: 10.3.2

**Additional context**

It works on Firefox 66.0.3.

Someone on Emby already made a post about it, and the Emby devs already knows about it, but haven't managed to figure out why: https://emby.media/community/index.php?/topic/72967-emby-web-app-stops-showing-subtitles-in-newest-google-chrome/

**Comment by redSpoutnik** [comment]
It seems that the new Chrome version renders "normal" size subtitles on the top. For now, you can fix this by setting an other size.

**Comment by jomp16** [comment]
Yeah, I "fixed" that by using "large" subtitle fonts.

Maybe next Chrome version will fix it by itself?

**Comment by olskar** [comment]
Fixed in Chrome 75, guess this can be closed :)

**Comment by DrPandemic** [comment]
Thanks @olskar for validating. If it's still an issue I'll reopen
