### ISSUE TITLE
Minor UI Issues

### ISSUE THREAD

**Issue by T0W1** [jellyfin/jellyfin-web#302]
the scroll button overlaps with the 3dots. #142 #144 
![Screenshot from 2019-04-29 21-59-22](https://user-images.githubusercontent.com/50248556/57165021-3b8d2900-6df6-11e9-8dd1-871347c30bfa.png)

also this, there is nothing there.
![Screenshot at 2019-05-03 22:51:06](https://user-images.githubusercontent.com/50248556/57165073-58c1f780-6df6-11e9-8939-7c126367efb1.png)

Alphabet list overlaps Dashboard icon when **not** fullscreen.
![Fullscreen-Screenshot from 2019-04-29 23-16-59](https://user-images.githubusercontent.com/50248556/57164054-38dd0480-6df3-11e9-9f14-8e0b167c8eb7.png)
![Screenshot at 2019-04-29 23:15:54](https://user-images.githubusercontent.com/50248556/57164057-39759b00-6df3-11e9-9363-a2eace088984.png)

The Movie and TV Show posters are inconsistent when it comes to showing YEAR.
![Screenshot at 2019-05-04 13:11:08](https://user-images.githubusercontent.com/50248556/57178307-69ae4f80-6e6e-11e9-9ded-ed4dfb8f286e.png)
![Screenshot from 2019-05-04 13-20-35](https://user-images.githubusercontent.com/50248556/57178403-b181a680-6e6f-11e9-8ff0-c68408278fde.png)

**Comment by anthonylavado** [comment]
Just to be clear, is it the display of the years that is the inconsistent part you mention, or the fact that only some shows (like The Grand Tour) show a year in the Poster view?

IIRC there are multiple shows called “The Grand Tour”, so the year must be used to help mark which one you’re looking at.

**Comment by T0W1** [comment]
The first one, I know why the grand tour shows it. However some may even consider that to be inconsistent for the fact that not all shows do this and can even be considered to be redundant because the years can be shown below the name.

**Comment by T0W1** [comment]
@DrPandemic  @dkanada #315
For the left and right scroll buttons maybe change it to the one used in HOME VIDEOS AND PICTURES
as has a smaller area and is unlikely to interfere. (it also look cleaner to me)
![Screenshot from 2019-05-15 20-22-10](https://user-images.githubusercontent.com/50248556/57800254-3bbfe980-7751-11e9-908d-253e947ccf38.png)

**Comment by T0W1** [comment]
I noticed that if I zoom out to 80% in FF that the Alphabet list stops overlapping. 
![Screenshot from 2019-05-26 14-34-07](https://user-images.githubusercontent.com/50248556/58381918-a976db80-7fc3-11e9-88da-11bd03a03798.png)

**Comment by dkanada** [comment]
@T0W1 what is the the resolution of your display? It might be a css issue.

**Comment by T0W1** [comment]
Screen resolution 1366x768

On 26 May 2019 22:09, dkanada <notifications@github.com> wrote:

@T0W1<https://github.com/T0W1> what is the the resolution of your display? It might be a css issue.

**Comment by T0W1** [comment]
@dkanada  on 1366x768@11" it starts to look ok at 67% scaling.

BTW in chrome its absolutely not a issue. Apparently its a Firefox only problem.
