### ISSUE TITLE
Add keyboard/remote navigation

### ISSUE THREAD

**Issue by EraYaN** [jellyfin/jellyfin-web#303]
**Describe the feature you'd like**
To use the webUI as a hosted app on LG webOS 4 TV's (browser won't do streaming) it would be nice to be able to use a keyboard or preferably the remote to control the UI. Right now the magic remote works (since it acts as a mouse). And the main menu does show a highlight around the first menu, it just does not move with arrow keys.

**Additional context**
Both tested using the magic remote and one of the "normal" remotes, and a keyboard.

**Key codes**
The keypress event acts like [Chrome and IE](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) and below are the keyup and keydown codes. So for controls keyup and keydown are the correct events.

*Common keys*

| Key      | Key code | Suggested Action/Notes                                     |
|----------|----------|------------------------------------------------------------|
| 0-9      | 48-57    | Channel switching and number entry (same as keyboard)      |
| OK       | 13       | Enter/OK/Show OSD                                          |
| TEXT     | 459      | Cycle through subtitles (Mimic Kodi behaviour for key `L`) |
| T.OPT    | 1004     | Show subtitle options                                      |
| Ch. Up   | 33       | Next Channel/Next Item in playlist                         |
| Ch. Down | 34       | Previous Channel/PreviousItem in playlist                  |
| Red      | 403      | Remappable action 1                                        |
| Green    | 404      | Remappable action 2                                        |
| Yellow   | 405      | Remappable action 3                                        |
| Blue     | 406      | Remappable action 4                                        |
| Left     | 37       | (same as keyboard)                                         |
| Up       | 38       | (same as keyboard)                                         |
| Right    | 39       | (same as keyboard)                                         |
| Down     | 40       | (same as keyboard)                                         |
	
*Magic Remote keys*

| Key              | Key code | Suggested Action           |
|------------------|----------|----------------------------|
| RemoteTypeButton | 1062     | Toggle Mouse/Keyboard mode |
| cursor on        | 1536     | Switch to Mouse mode       |
| cursor off       | 1537     | Switch to Keyboard mode    |

*Normal Remote keys*

| Key      | Key code | Suggested Action                                                    |
|----------|----------|---------------------------------------------------------------------|
| Subtitle | 460      | Toggle Subtitle on/off (Mimic Kodi key `T`)                         |
| Info     | 457      | Show info                                                           |
| AD/*     | 1028     | (this enables Audio description) not sure what to do with that info |
| REC/*    | 416      | Start recording live tv                                             |
| Play     | 415      |                                                                     |
| Pause    | 19       | Has keypress code 133                                               |
| Stop     | 413      |                                                                     |
| FF<      | 412      |                                                                     |
| FF>      | 417      |                                                                     |
| TV/RAD   | 1014     |                                                                     |

[LG Documentation](http://webostv.developer.lge.com/design/webos-tv-system-ui/remote-control/)

**Comment by EraYaN** [comment]
So the webUI seems to have some support for focus elements, I just can't figure out how these work or where they are directed. Since on webOS for example the first item in the view is "selected" with class `card-focuscontent` (and a whole bunch of other classes. But no amount of button pressing will change it, and searching the code for this strings gives nothing that I recognized as something global.

**Comment by Nickbert7** [comment]
Do you think it would make sense to enable to "display mode" setting?
So also HTPC or browser users could switch to the tv layout and use the keyboard navigation.

![image](https://user-images.githubusercontent.com/14938497/60967403-e05a4400-a31a-11e9-829b-2d432232a0d3.png)

**Comment by EraYaN** [comment]
Is that a mockup or did you add it to the code? If you added it in. Please make a PR.

**Comment by Nickbert7** [comment]
Basically it is already there and gets visible by adding `features.push("displaymode");` into jellyfin-web/src/components/apphost.js
![image](https://user-images.githubusercontent.com/14938497/60969037-d1759080-a31e-11e9-8438-7e4d99340f8e.png)

**Comment by MrTimscampi** [comment]
Closing this as we have it, even though it's currently far from perfect.

**Comment by jackooooo** [comment]
when I use a remote to control the interface a single click up/down results in 2 down movements in the interface. Left and right work fine. Is there a setting I can adjust the sensitivity of the up/down command?
