### ISSUE TITLE
iOS (Safari) comic reader does not work

### ISSUE THREAD

**Issue by florlbright** [jellyfin/jellyfin-web#3045]
**Describe The Bug**
The comic reader does not show anything after downloading the comic book archive. The page just stays white and blank, the button to go back disappears then as well.
As far as I can tell the cbz archive does get downloaded (because in my server logs I can see the network traffic and just downloading it regularly in Jellyfin works too), but it seems the actual comic book viewer is not supported.

**Steps To Reproduce**
1. Go to a comic
2. Press play
3. Wait for the comic book archive to be downloaded
4. See completely blank screen in app or Safari will sometimes try to reload the comic book viewer page or sent you back to the previous page.

**Expected Behavior**
I either expect the comic book viewer to work, or be presented some kind of error or "unsupported platform" message.

**Logs**
`error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."`

**System (please complete the following information):**
 - Platform: iOS 12.5.5 on iPad
 - Browser: Safari 12.1.2
 - Jellyfin Version: 10.7.7

**Additional Context**
I understand this is an old platform with an old browser, so even if no solution is possible at least this issue is logged.

**Comment by MinecraftPlaye** [comment]
@florlbright I just tested it on my iPad and it opens just fine in Safari and in the app. So it might be specific to your version of iOS/Safari, thought I can't test it on those versions.

-  Jellyfin Version: 10.7.7
- Platform: iPadOS 14.8
- Browser: Safari 14.1.2
