### ISSUE TITLE
Can't Copy Mediainfo

### ISSUE THREAD

**Issue by seniorm0ment** [jellyfin/jellyfin-web#3075]
It's not possible to copy mediainfo on mobile browser/in mobile app.
Have not tried on desktop with cursor.

**Comment by dmitrylyzo** [comment]
`Copy` button? :thinking:

**Comment by seniorm0ment** [comment]
You can't highlight it.

**Comment by dmitrylyzo** [comment]
> You can't highlight it by holding/pressing/tapping

I mean, we probably need to add a `Copy` button to that dialog.

**Comment by seniorm0ment** [comment]
Oh, yes. I thought you wrre telling me to use the copy button lol.
