### ISSUE TITLE
Library icons are different in different places

### ISSUE THREAD

**Issue by stephanrenggli** [jellyfin/jellyfin-web#308]
**Is your feature request related to a problem? Please describe.**
The library icons (movies, tv shows, music, etc.) are not the same as in library settings.

Sidebar:
![image](https://user-images.githubusercontent.com/5135902/57200134-f4cf3880-6f87-11e9-918f-d4d051ed6d4e.png)

Library Settings:
![image](https://user-images.githubusercontent.com/5135902/57200128-dec17800-6f87-11e9-8c2f-f42967a82325.png)

**Describe the solution you'd like**
The same icons should be used everywhere.

**Describe alternatives you've considered**

**Additional context**
Low priority as it doesn't have any impact on jellyfin features.

**Comment by dkanada** [comment]
fixed by #326
