### ISSUE TITLE
[bug] Posters display blurred on scrolling up when displaying in "Genre" mode

### ISSUE THREAD

**Issue by debmint** [jellyfin/jellyfin-web#3140]
**Describe The Bug**
When displaying Movies by Genre, after scrolling up, posters begin to display as blurred images.  Most times when scrolling down the first time, posters display properly.  After any up scroll, they begin to display blurred.

**Steps To Reproduce**
1. Select "Genre" when in Movies (I did not try Shows or anything else)
2. Begin scrolling down.  As long as you don't scroll up, posters display properly
3. Scroll up either in process of scrolling down or after reaching bottom of page.
4. After any up scroll, posters begin to display blurred

**Expected Behavior**
The posters once correctly rendered should remain intact as long as the browser stays on that web page

**Logs**
[19:43:53] [WRN] [65] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://localhost:8096/Items/bffbf9a788f817a46410385e81a535c7/Images/Primary?fillHeight=278&fillWidth=185&quality=96&tag=494acfabeb79702f3d61407106089013 to 172.17.0.1 in 0:00:00.8247877 with Status Code 200

**Screenshots**

**System (please complete the following information):**
 - Platform: Linux Mint, Manjaro, Android
 - Browser: [e.g. Firefox, Chrome, Safari]
 - Jellyfin Version: [e.g. 10.7.7] one in a docker container, another in a virtual machine.
      10.7.7
**Additional Context**
Have tried on Chromium, Firefox, Brave, LibreWolf, and Chrome on Android.  This behavior is present on all browsers.
The pattern in above log appears numerous times but these show up even while the page is being correctly rendered.,  The docker is run on a laptop with a 2 GHz Pentium.  The virtual machine is Ubuntu Server running in a 3 GHZ i-5 host.
It would appear that once the web page was rendered it would be the responsibility pf the web browser to remember what's on it unless it was reloaded or something but this does not seem to be the case.    An uninterrupted down scroll renders correctly as you go down, but even a single up scroll starts the corruption.

**Comment by Ranthalion** [comment]
This seems to be the same issue in #1972 (which seems to be closed without resolution).  I'm also seeing this issue on chrome with version 10.7.7.

**Comment by Tropaion** [comment]
Why is this marked as fixed? I still have this, but not only in Genres but in every mode.

**Comment by ferferga** [comment]
@Tropaion Did you clone this client from master and tried it or are you talking about stable? This changes won't get to stable until 10.8

**Comment by Tropaion** [comment]
Sorry, my mistake, I thought it was already in stable. Is there a date when 10.8 will be released?

**Comment by ferferga** [comment]
No, when it's ready as usual 😊.

**Comment by nenevva** [comment]
I still have this problem with my stable build 10.8.1.
