### ISSUE TITLE
"Use episode images in Next Up and Continue Watching sections" toggle under Settings/Display doesn't persist after a refresh

### ISSUE THREAD

**Issue by omeryagmurlu** [jellyfin/jellyfin-web#3173]
**Describe The Bug**
"Use episode images in Next Up and Continue Watching sections" toggle under Settings/Display doesn't persist after a refresh.

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Edge
 - Jellyfin Version: 10.8.0

**Additional Context**
I'm the original PR author who added that toggle.

**Comment by dmitrylyzo** [comment]
Everything works for me on Firefox and Chrome.
Is it reproducible on them?

**Comment by omeryagmurlu** [comment]
I don’t have chrome desktop installed right now, but it is present on the latest firefox and edge, and mobile firefox and safari.

To reproduce, just toggle the settings and click save. After a refresh of the page you’ll see that the setting reverted back to it’s original state.

I’ve tested it with both the latest available alpha and a development build from the master, it happens with them both.

**Comment by omeryagmurlu** [comment]
Here's a demonstration of the problem

https://user-images.githubusercontent.com/8201544/141838625-b89d7ee4-2211-44d7-bdb6-bf75da4072b1.mp4

**Comment by dmitrylyzo** [comment]
I updated Jellyfin to the latest unstable version and you are right - it stopped working (in Chrome).
I think something is broken on the server side.

**Comment by omeryagmurlu** [comment]
Now that I look at it, it's not only this toggle. If I try to reorder the home screen layout from Settings/Home, the same issue occurs, nothing persists after a refresh.
