### ISSUE TITLE
Web home is brooken in Palo moon

### ISSUE THREAD

**Issue by spirillen** [jellyfin/jellyfin-web#3179]
**Describe The Bug**
When you enter jellyfin with the pale moon browser you only get the first (top) row and nothing else.

**Steps To Reproduce**

1. Go to Home
2. First row is showing + The waiting spinner 

**Expected Behavior**
All rows as if it have been with any other Firefox builds

**Logs**
NULL

**Screenshots**
![image](https://user-images.githubusercontent.com/44526987/141845165-566ff9bc-7472-41fd-b56c-8bc3ebcd34ae.png)

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Pale Moon
 - Jellyfin Version: [e.g. 10.7.7]

**Additional Context**
Nope...

**Comment by dmitrylyzo** [comment]
Could you look for errors in the browser console?

**Comment by spirillen** [comment]
The output, if it wasn't exactly what you was hoping for, please let me know, and I'll get back when I feel better :face_with_thermometer: 

<details><summary>The log</summary>

setting page base to /web  
main.0f183787a2f78055e856.bundle.js:2:11165
Stored JSON credentials: {"Servers":[{"DateLastAccessed":<ID>,"LastConnectionMode":2,"ManualAddress":"http://jellyfin:8096","manualAddressOnly":true,"Name":"nfs","Id":"<ID>","LocalAddress":"http://192.0.2.0:8096","AccessToken":"<TOKEN>","UserId":"<UserId>"}]}  
main.0f183787a2f78055e856.bundle.js:2:738634
Begin ConnectionManager constructor  
main.0f183787a2f78055e856.bundle.js:2:728384
"ApiClient serverAddress: http://jellyfin:8096"  
main.0f183787a2f78055e856.bundle.js:2:669386
ApiClient appName: Jellyfin Web  
main.0f183787a2f78055e856.bundle.js:2:669439
ApiClient appVersion: 10.7.6  
main.0f183787a2f78055e856.bundle.js:2:669486
ApiClient deviceName: Web Browser  
main.0f183787a2f78055e856.bundle.js:2:669536
ApiClient deviceId: <deviceId>  
main.0f183787a2f78055e856.bundle.js:2:669586
returning instance from getOrAddApiClient  
main.0f183787a2f78055e856.bundle.js:2:732578
defining core routes
main.0f183787a2f78055e856.bundle.js:2
defining route: /addserver.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /selectserver.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /login.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /forgotpassword.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /forgotpasswordpin.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /mypreferencesmenu.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /myprofile.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /mypreferencesdisplay.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /mypreferenceshome.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /mypreferencesquickconnect.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /mypreferencesplayback.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /mypreferencessubtitles.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /dashboard.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /dashboardgeneral.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /networking.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /devices.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /device.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /quickConnect.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /dlnaprofile.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /dlnaprofiles.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /dlnasettings.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /addplugin.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /library.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /librarydisplay.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /edititemmetadata.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /encodingsettings.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /log.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /metadataimages.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /metadatanfo.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /notificationsetting.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /notificationsettings.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /playbackconfiguration.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /availableplugins.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /repositories.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /home.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /search.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /list.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /details  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /livetv.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /livetvguideprovider.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /livetvsettings.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /livetvstatus.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /livetvtuner.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /movies.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /music.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /installedplugins.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /scheduledtask.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /scheduledtasks.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /serveractivity.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /apikeys.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /streamingsettings.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /tv.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /useredit.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /userlibraryaccess.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /usernew.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /userparentalcontrol.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /userpassword.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /userprofiles.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /wizardremoteaccess.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /wizardfinish.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /wizardlibrary.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /wizardsettings.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /wizardstart.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /wizarduser.html  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /video  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /queue  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: /configurationpage  
main.0f183787a2f78055e856.bundle.js:2:962466
defining route:   
main.0f183787a2f78055e856.bundle.js:2:962466
defining route: index.html  
main.0f183787a2f78055e856.bundle.js:2:962466
Begin getAvailableServers  
main.0f183787a2f78055e856.bundle.js:2:733832
Unhandled promise rejection DOMException [SecurityError: "The operation is insecure."
code: 18
nsresult: 0x80530012
location: http://jellyfin:8096/web/main.0f183787a2f78055e856.bundle.js:2]  
main.0f183787a2f78055e856.bundle.js:2:400634
URL candidates: Array [ "http://jellyfin:8096" ]  
main.0f183787a2f78055e856.bundle.js:2:302923
creating ApiClient singleton  
main.0f183787a2f78055e856.bundle.js:2:1943
"ApiClient serverAddress: http://jellyfin:8096"  
main.0f183787a2f78055e856.bundle.js:2:669386
ApiClient appName: Jellyfin Web  
main.0f183787a2f78055e856.bundle.js:2:669439
ApiClient appVersion: 10.7.6  
main.0f183787a2f78055e856.bundle.js:2:669486
ApiClient deviceName: Web Browser  
main.0f183787a2f78055e856.bundle.js:2:669536
ApiClient deviceId: <deviceId>  
main.0f183787a2f78055e856.bundle.js:2:669586
loaded ApiClient singleton  
main.0f183787a2f78055e856.bundle.js:2:2178
initAfterDependencies promises resolved  
main.0f183787a2f78055e856.bundle.js:2:994866
using default fonts  
main.0f183787a2f78055e856.bundle.js:2:995732
loading installed plugins
main.0f183787a2f78055e856.bundle.js:2
{pluginsList: Array[0], _callbacks: Object}
main.0f183787a2f78055e856.bundle.js:2
Loading plugin (via dynamic import): playAccessValidation/plugin  
main.0f183787a2f78055e856.bundle.js:2:164011
Loading plugin (via dynamic import): experimentalWarnings/plugin  
main.0f183787a2f78055e856.bundle.js:2:164011
Loading plugin (via dynamic import): htmlAudioPlayer/plugin  
main.0f183787a2f78055e856.bundle.js:2:164011
Loading plugin (via dynamic import): htmlVideoPlayer/plugin  
main.0f183787a2f78055e856.bundle.js:2:164011
Loading plugin (via dynamic import): photoPlayer/plugin  
main.0f183787a2f78055e856.bundle.js:2:164011
Loading plugin (via dynamic import): comicsPlayer/plugin  
main.0f183787a2f78055e856.bundle.js:2:164011
Loading plugin (via dynamic import): bookPlayer/plugin  
main.0f183787a2f78055e856.bundle.js:2:164011
Loading plugin (via dynamic import): youtubePlayer/plugin  
main.0f183787a2f78055e856.bundle.js:2:164011
Loading plugin (via dynamic import): backdropScreensaver/plugin  
main.0f183787a2f78055e856.bundle.js:2:164011
Loading plugin (via dynamic import): pdfPlayer/plugin  
main.0f183787a2f78055e856.bundle.js:2:164011
Loading plugin (via dynamic import): logoScreensaver/plugin  
main.0f183787a2f78055e856.bundle.js:2:164011
Loading plugin (via dynamic import): sessionPlayer/plugin  
main.0f183787a2f78055e856.bundle.js:2:164011
SyncPlay WrapperFactory setDefaultWrapper: default  
main.0f183787a2f78055e856.bundle.js:2:212838
SyncPlay WrapperFactory registerWrapper: htmlvideoplayer  
main.0f183787a2f78055e856.bundle.js:2:212704
SyncPlay WrapperFactory registerWrapper: htmlaudioplayer  
main.0f183787a2f78055e856.bundle.js:2:212704
begin onAppReady  
main.0f183787a2f78055e856.bundle.js:2:993060
onAppReady: loading dependencies  
main.0f183787a2f78055e856.bundle.js:2:993094
returning instance from getOrAddApiClient  
main.0f183787a2f78055e856.bundle.js:2:732578
Begin connect  
main.0f183787a2f78055e856.bundle.js:2:737335
Begin getAvailableServers  
main.0f183787a2f78055e856.bundle.js:2:733832
serviceWorker unsupported  
main.0f183787a2f78055e856.bundle.js:2:993889
Begin connectToServers, with 1 servers  
main.0f183787a2f78055e856.bundle.js:2:734541
begin connectToServer  
main.0f183787a2f78055e856.bundle.js:2:734916
"tryReconnect: http://jellyfin:8096"  
main.0f183787a2f78055e856.bundle.js:2:735433
"getTryConnectPromise http://jellyfin:8096"  
main.0f183787a2f78055e856.bundle.js:2:735621
"ConnectionManager requesting url: http://jellyfin:8096/system/info/public"  
main.0f183787a2f78055e856.bundle.js:2:726719
"fetchWithTimeout: timeoutMs: 20000, url: http://jellyfin:8096/system/info/public"  
main.0f183787a2f78055e856.bundle.js:2:727294
finished loading plugins  
main.0f183787a2f78055e856.bundle.js:2:996304
loading packages
main.0f183787a2f78055e856.bundle.js:2
finished loading packages  
main.0f183787a2f78055e856.bundle.js:2:960152
"fetchWithTimeout: succeeded connecting to url: http://jellyfin:8096/system/info/public"  
main.0f183787a2f78055e856.bundle.js:2:727499
"ConnectionManager response status: 200, url: http://jellyfin:8096/system/info/public"  
main.0f183787a2f78055e856.bundle.js:2:727736
"Reconnect succeeded to http://jellyfin:8096"  
main.0f183787a2f78055e856.bundle.js:2:735781
"ConnectionManager requesting url: http://jellyfin:8096/System/Info"  
main.0f183787a2f78055e856.bundle.js:2:726719
"ConnectionManager response status: 200, url: http://jellyfin:8096/System/Info"  
main.0f183787a2f78055e856.bundle.js:2:727736
returning instance from getOrAddApiClient  
main.0f183787a2f78055e856.bundle.js:2:732578
"Setting server address to http://jellyfin:8096"  
main.0f183787a2f78055e856.bundle.js:2:677287
"Requesting url without automatic networking: http://jellyfin:8096/Sessions/Capabilities/Full"  
main.0f183787a2f78055e856.bundle.js:2:672240
calling apiClient.ensureWebSocket  
main.0f183787a2f78055e856.bundle.js:2:729202
opening web socket with url: ws://jellyfin:8096/socket?api_key=<TOKEN>&deviceId=<deviceId>  
main.0f183787a2f78055e856.bundle.js:2:675783
"Requesting http://jellyfin:8096/Users/<UserId>"  
main.0f183787a2f78055e856.bundle.js:2:671163
returning instance from getOrAddApiClient  
main.0f183787a2f78055e856.bundle.js:2:732578
"Requesting http://jellyfin:8096/DisplayPreferences/usersettings?userId=<UserId>&client=emby"  
main.0f183787a2f78055e856.bundle.js:2:671163
resolving connectToServers with result.State: SignedIn  
main.0f183787a2f78055e856.bundle.js:2:734748
processing path request: /web#!/home.html  
main.0f183787a2f78055e856.bundle.js:2:19310
user is authenticated  
main.0f183787a2f78055e856.bundle.js:2:19679
proceeding to page: /web#!/home.html  
main.0f183787a2f78055e856.bundle.js:2:19900
web socket connection opened  
main.0f183787a2f78055e856.bundle.js:2:667449
"Requesting http://jellyfin:8096/Sessions?ControllableByUserId=<UserId>"  
main.0f183787a2f78055e856.bundle.js:2:671163
Received ForceKeepAlive from server. Timeout is 60 seconds.  
main.0f183787a2f78055e856.bundle.js:2:666999
Sending web socket message: KeepAlive  
main.0f183787a2f78055e856.bundle.js:2:676315
Clearing KeepAlive for WebSocket { url: "ws://jellyfin:8096/socket?api…", readyState: 1, bufferedAmount: 27, onopen: bound T(), onerror: bound C(), onclose: function (), extensions: "", protocol: "", onmessage: bound P(), binaryType: "blob" }  
main.0f183787a2f78055e856.bundle.js:2:667300
Received KeepAlive from server.  
main.0f183787a2f78055e856.bundle.js:2:666915
"Requesting http://jellyfin:8096/Users/<UserId>/Views"  
main.0f183787a2f78055e856.bundle.js:2:671163
"Requesting http://jellyfin:8096/Users/<UserId>/Views"  
main.0f183787a2f78055e856.bundle.js:2:671163
Unhandled promise rejection TypeError: r[i].resume is not a function
Stack trace:
p@http://jellyfin:8096/web/8874.a564d0cd5ae4c74b83f3.bundle.js:1:712
loadSections/</<@http://jellyfin:8096/web/8874.a564d0cd5ae4c74b83f3.bundle.js:1:13554
X/<@http://jellyfin:8096/web/main.0f183787a2f78055e856.bundle.js:2:451761
r@http://jellyfin:8096/web/main.0f183787a2f78055e856.bundle.js:2:406550
  
main.0f183787a2f78055e856.bundle.js:2:400634
"Requesting http://jellyfin:8096/System/Endpoint"  
main.0f183787a2f78055e856.bundle.js:2:671163

</details>

**Comment by dmitrylyzo** [comment]
`Unhandled promise rejection TypeError: r[i].resume is not a function`

It fails here https://github.com/jellyfin/jellyfin-web/blob/be195b0e240b4a4b871eb6a7fe8e4830bd9ab12c/src/components/homesections/homesections.js#L125

Is this your first time trying Jellyfin on Pale moon?
Or did it work before?

**Comment by spirillen** [comment]
It have been working for about a ½ year ago back in ~feb/marts (if i remember correctly) then I don't recall why, but the error started and I switched to use FF, probable as I assumed it was a temporary issue with either jellyfin or pale moon.

So yes it have been working like a charm in pale moon earlier.

**Comment by dmitrylyzo** [comment]
On Pale Moon 29.4.2.1, `master` branch (~10.8.0-alpha2) works.

**Comment by spirillen** [comment]
Sounds Weird as that is the version I'm supposedly using

![image](https://user-images.githubusercontent.com/44526987/142059208-d91685b7-c058-4e76-9ab7-c103ea34ef8a.png)

> Does it work in the private window for you?

Nope same result as in the first screenshot. and all extensions are turned off.
