### ISSUE TITLE
[Issue]:  Alpha 2 Fewer options in Collections

### ISSUE THREAD

**Issue by MRDJellyfin** [jellyfin/jellyfin-web#3198]
### Please describe your bug

The sidebar no longer appears (with which you can select by letter) and when you have many collections it makes it difficult to navigate  (It should be noted that this bar does not appear when it is selected in movies / collections both in the stable version and in the Alpha 2, which, it would be good if it could be included in the new version that comes out). Of the options in the horizontal bar they also decreased, the ones that no longer appear I do not use personally, but there could be someone who did (Play all and mix).

Stable 10.7.7

![image](https://user-images.githubusercontent.com/82923908/143373836-7415c032-99cf-4524-b74c-ba808fa25785.png)

Alpha 2

![image](https://user-images.githubusercontent.com/82923908/143373936-a17cdda2-9ce7-441c-93b6-b25930010dc2.png)

### Jellyfin Version

Other

### Environment

```markdown
- OS: Windows 10 Pro 64
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
I have transferred this to the web repo.

The "Play all" button has been removed due to incompatibility. Your sort order seems to have reset and sorts by "IsFolder,SortName". If you click the sort and choose "Sort By: Name" the alpha (letter) picker will show up.
