### ISSUE TITLE
Chromecast no longer found after update to the new app id

### ISSUE THREAD

**Issue by hawken93** [jellyfin/jellyfin-web#32]
I was able to bisect my way to see that https://github.com/jellyfin/jellyfin-web/commit/edde5803295c9b892484ad5606ac02f05acf986b caused the chromecast not to show up in chrome/android in the "play on" dialogue.

I'll do tcpdumps, get logs etc - just tell me what you need :)

**Comment by dkanada** [comment]
Have you tried rebooting your chromecast?

**Comment by hawken93** [comment]
I booted it around a minute before trying it.. I can always try again though. :P

**Comment by dkanada** [comment]
Hmmm I remember someone mentioning that the chromecast locally cached any pages until the next reboot so I thought that might be the fix.

**Comment by hawken93** [comment]
Tried again a couple of times, no dice. tcpdumping for the chromecast also didn't show any signs of even trying. I then tried to use chrome on windows and it doesn't discover or log any errors or relevant information.. I'll dig up the javascript that discovers chromecasts later and go from there.. I'm open for suggestions..

**Comment by joshuaboniface** [comment]
Could this have been because it wasn't published yet? I've done so, can you test again @hawken93 ?

**Comment by anthonylavado** [comment]
Yes, if the app is unpublished, only Chromecasts added as test devices to the account will see it.

**Comment by hawken93** [comment]
I'll let you know when I get another chance to test it :)

**Comment by hawken93** [comment]
All good!

**Comment by surdu** [comment]
I'm having the same issue. I'm running Jellyfin v10.3.7 in a docker container with `network_mode: host` so that Jellyfin sees my whole network, and while it shows all other Jellyfin-capable devices on the network, doesn't show the "Chromecast" entry or any Chromecast devices in the web application.  The Android application, at least, works just fine.

Rebooted both Chromecast and Jellyfin server repeatedly to no effect.

Any pointers on what to do next to debug this issue ?

**Comment by anthonylavado** [comment]
@surdu If you’re using Chrome on a computer, you either have to be on the same machine (using http://localhost), or using HTTPS (https://myjellyfin). Otherwise, Chrome blocks the ability to cast.

If you’re using the Android app, it’s not subject to the same restrictions and should show it.

**Comment by surdu** [comment]
Awesome! Making Jellyfin run on HTTPS was on my list anyways! I'll try that tomorrow! Thank you!
