### ISSUE TITLE
When using a "Book" media type, the suggestions tab says "Music"

### ISSUE THREAD

**Issue by mcarlton00** [jellyfin/jellyfin-web#320]
**Describe the bug**
The "Suggestions" tab in a book library is titled "Latest Music"

**To Reproduce**
1. Add a folder with media type "Books"
2. From home screen, select created folder from "My Media"
3. Look at page heading

**Expected behavior**
The page should be labeled with the appropriate media type (Books, in this case)

**Screenshots**]
https://i.imgur.com/hlvwivG.png

**System**
 - OS: Docker
 - Browser: Firefox
 - Jellyfin Version: 10.3.2

**Comment by bugfixin** [comment]
Could you provide a screenshot of the library configuration? I can't seem to reproduce that display.

**Comment by mcarlton00** [comment]
I added another screenshot of my library creation settings [here](https://imgur.com/a/lQRLmGa).
