### ISSUE TITLE
Back button doesn't close modal dialogs

### ISSUE THREAD

**Issue by viggy96** [jellyfin/jellyfin-web#3207]
Back button works fine for most navigation.
However, if user opens 'media info' or 'edit metadata', then tries to go back using the system back button (or gesture), the respective modal stays open. Once the user taps the back icon at the top left, only then is the modal closed and the user can see that the app did indeed navigate to the previous page in the background.

**Comment by dmitrylyzo** [comment]
This is already fixed in 10.8.0~alpha, no?
https://github.com/jellyfin/jellyfin-web/pull/2660
https://github.com/jellyfin/jellyfin-web/pull/2889
https://github.com/jellyfin/jellyfin-web/pull/2917
https://github.com/jellyfin/jellyfin-web/pull/3028

**Comment by Maxr1998** [comment]
Confirmed as fixed in Jellyfin 10.8.
