### ISSUE TITLE
[Bug] Subtitles Delay

### ISSUE THREAD

**Issue by bosci9** [jellyfin/jellyfin-web#3214]
**Describe The Bug**
When I use a subtitle I downloaded from the OpenSubtiles plugin and set a delay for it, the delay doesn't return to 0s if I switch to a subtitle included with the downloaded movie and the only way to reset it is change the subtitles to the previous one, manually set the delay to 0s, and then selecting the subtitles I want.

**Steps To Reproduce**
1. Download a subtitle file using the OpenSubtitles plugin
2. Enable it
3. Set a delay
4. Change the subtitle to one included in the movie

**Expected Behavior**
I expect to be able to change the subtitles delay even when I use a subtitle included in the movie file

**System:**
 - Platform: [Docker 20.10.7 on Ubuntu Server 20.04.3]
 - Browser: [Firefox 95.0 and Desktop Client 1.6.1]
 - Jellyfin Version: [e.g. 10.7.7]

**Comment by riccbos** [comment]
The issue is still there in the latest release

**Comment by riccbos** [comment]
Issue still exists
