### ISSUE TITLE
chromecast: e.playbackStartTime is not a function

### ISSUE THREAD

**Issue by benediktkr** [jellyfin/jellyfin-web#3216]
When using chromecast, it will always jump to the beginning of a file, and if you try to skip forward it will also start playing the file from the beginning. 

The javascript for the chromecast plugin will throw this error: 

```
cast_sender.js:74 Uncaught TypeError: e.playbackStartTime is not a function
    at e.c.playbackStartTime (main.0f183787a2f78055e856.bundle.js:2)
    at e.ue (playback-video.59dcbbd39f3cd02076bc.bundle.js:1)
    at main.0f183787a2f78055e856.bundle.js:2
    at Array.forEach (<anonymous>)
    at Object.trigger (main.0f183787a2f78055e856.bundle.js:2)
    at e.<anonymous> (chromecastPlayer-plugin.3b1e613c5d041153b04a.bundle.js:1)
    at main.0f183787a2f78055e856.bundle.js:2
    at Array.forEach (<anonymous>)
    at Object.trigger (main.0f183787a2f78055e856.bundle.js:2)
    at e.value (chromecastPlayer-plugin.3b1e613c5d041153b04a.bundle.js:1)
```

The function `playbackStartTime` is not found in `cast_sender.js`, which is hosted at `https://www.gstatic.com/eureka/clank/95/cast_sender.js` so i think it is trying to call a function that has been deprecated. 

The call seems to happen in `main.0f183787a2f78055e856.bundle.js` in my case.

Since im running the official docker image, it seems to come with bundled javascript files. I havent tried running a jellyfin-web in a different way, but I can try that if there isnt an obvious solution to this. 

**Steps To Reproduce**
1. Open jellyfin-web and log in 
2. Pick a video that has been partially watched and start playing it with Chromecast
3. The video starts from the beginning and the above `TypeError` is written to the debug console in the browser. 

or;

1. Open jellyfin-web and log in
2. Pick any video and start playing it with Chromecast
3. Skip forward in the video
4. The video starts from the beginning and the above `TypeError` is written to the debug console in the browser. 

**Expected Behavior**

Skipping forward works and no `TypeError` in the debug console

**System:**
 - Platform: Windows, Linux (client) and Linux (server)
 - Browser: Chrome (Windows), `chromium-browser` (Linux)
 - Jellyfin Version: 10.7.7 (`jellyfin/jellyfin:latest` on Docker)

**Comment by dmitrylyzo** [comment]
https://github.com/jellyfin/jellyfin-web/blob/be195b0e240b4a4b871eb6a7fe8e4830bd9ab12c/src/components/playback/playbackmanager.js#L3200
And it is really not implemented for `chromecastPlayer`.

Looks like it should return datetime of the playback start (in 100ns ticks):
https://github.com/jellyfin/jellyfin-web/blob/be195b0e240b4a4b871eb6a7fe8e4830bd9ab12c/src/components/playback/playbackmanager.js#L2775

**Comment by benediktkr** [comment]
i figured this out, the request for the `cast_sender.js` was actually being denied because of the content security policy. The url Is versioned, and the current version hadnt been added. at some point the functionality started working again, but when the request for 96 failed, it fetched 95 again. 

the fix is here: https://git.sudo.is/ben/infra/commit/c02733b73d8858ef1253bb382156f205452b839e

that url isnt in [the jellyfin docs for nginx](https://jellyfin.org/docs/general/networking/nginx.html) but when i looked at the source i noticed that the 95 url had been added recently in https://github.com/jellyfin/jellyfin-docs/issues/588 so i opened another pull request to add the 96 url to the docs as well: https://github.com/jellyfin/jellyfin-docs/pull/604
