### ISSUE TITLE
Remove version of a movie

### ISSUE THREAD

**Issue by jakobroehrl** [jellyfin/jellyfin-web#3220]
Hi, 
I have accidently added 3 movies to one movie with 3 versions. 
Can I remove the versions and see the 3 movies again?

![image](https://user-images.githubusercontent.com/24530680/145724878-86801350-312e-4efd-9beb-11a8120e5c61.png)

Thanks a lot

**Comment by ThibaultNocchi** [comment]
Just put the different movies in different folders and it should work :)

**Comment by dmitrylyzo** [comment]
If you have grouped them using the `Group versions` menu entry, there is a `Split` button on the item detail page.
![split](https://user-images.githubusercontent.com/56478732/145776907-8863d82f-759a-4ffe-9697-2fab848c4655.png)

**Comment by jakobroehrl** [comment]
> Just put the different movies in different folders and it should work :)

This was the problem, thanks. 

So the versions are build automaticly if I store some movies in the same folder?
