### ISSUE TITLE
BuildRequires: git missing from fedora/jellyfin.spec

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin-web#3221]
10.8.0-alpha3 (45a3ffdd1) is failing to build on EL8 with an `npm` error:

```
+ npm ci --no-audit --unsafe-perm
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/jellyfin/JavascriptSubtitlesOctopus.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /builddir/.npm/_logs/2021-12-13T03_23_08_339Z-debug.log
```

The above mentioned [2021-12-13T03_23_08_339Z-debug.log](https://github.com/jellyfin/jellyfin-web/files/7700796/2021-12-13T03_23_08_339Z-debug.log).

**Comment by ThibaultNocchi** [comment]
Can you retry now? If it doesn't work, can you try cloning the given repo and see if it works?

**Comment by ferferga** [comment]
Do you have git installed?

**Comment by brianjmurrell** [comment]
> Can you retry now?

Maybe I am misunderstanding something, but why would it work now when it didn't work 8h ago?  The only new commit to the repo since I tried last is:

```
* 31d02d804 - (origin/master, origin/HEAD) Translated using Weblate (Hungarian) Translation: Jellyfin/Jellyfin Web Translate-URL: https://translate.jellyfin.org/projects/jellyfin/jellyfin-web/hu/ (3 hours ago) <Csaba>
```

which _really_ is just a translation and nothing more.

> If it doesn't work, can you try cloning the given repo and see if it works?

I am already working from a git clone.

> Do you have git installed?

`git` is not listed as a build requirement in `fedora/jellyfin.spec` and that indeed is the bug.  Adding `BuildRequires: git` resolves the issue.  I will include that in my PR.

**Comment by ferferga** [comment]
@brianjmurrell Please edit the title and add an **Update** header (or something like that) to the issue so it's easily traceable afterwards.

In it's current state, this issue seems to only resemble the lack of git installed in an environment, with nothing to do with RPM specific stuff.

You can also open a new one if you see it more fitting.
