### ISSUE TITLE
Unaccessible 'unstable' builds in releases repo

### ISSUE THREAD

**Issue by WWWesten** [jellyfin/jellyfin-web#3222]
**Describe The Bug**
Unstable builds of jellyfin‐web unaccessible from 22 November for standalone "web" and from 26 November for "combined" packages.

**Steps To Reproduce**

1. Go to 'https://repo.jellyfin.org/releases/server/windows/unstable/'
2. Click on 'combined' or 'web'
3. See error "404 Not Found"

**Expected Behavior**

See the 'web' and 'combined' packages

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Platform: [e.g. Linux, Windows, iPhone, Tizen]
 - Browser: [e.g. Firefox, Chrome, Safari]
 - Jellyfin Version: [e.g. 10.6.0]

**Additional Context**

**Comment by WWWesten** [comment]
Error "404 Not Found" not displayed now. But question was other. Why _unaccessible_ are 'web' and 'combined' builds?

**Comment by WWWesten** [comment]
Ahoi @oddstr13, hvilke nyheter?
Now the 'combined' and 'web' catalogs are gone. ((

Merry Christmas! ))

**Comment by thornbill** [comment]
Unstable builds are broken due to this: https://github.com/jellyfin/jellyfin-web/pull/3180#issuecomment-999986260

**Comment by WWWesten** [comment]
https://github.com/jellyfin/jellyfin/issues/7061

**Comment by thornbill** [comment]
The Fedora and CentOS builds are fixed now, but Azure is failing to copy the build artifacts to our repository... which seems like an issue on the Azure side.

**Comment by Shadowghost** [comment]
Builds are fixed and repo should work again.

The meta package is still broken, so please install `jellyfin-server`, `jellyfin-web` and `jellyfin-ffmpeg` explicitly.
