### ISSUE TITLE
Notification permission prompt interrupts input on first use

### ISSUE THREAD

**Issue by freshgum-bubbles** [jellyfin/jellyfin-web#3243]
**Describe The Bug**

Upon signing into Jellyfin, the user is interrupted with a popup to allow notifications
when entering their username. This happens on the first character of the username.

**Steps To Reproduce**

1. Log out, clear permissions from the page, etc.
2. Get to the sign in page, enter a character of your username.
3. The notification popup is shown when you type the first character of your username.

**Expected Behavior**

I think Jellyfin should wait for me to finish typing in my username and password (and possibly
even login) before prompting me asking for permission for notifications. This would mean I am
not interrupted when typing in my username (which is obviously quite annoying). Notifications are
an auxiliary thing and can wait; typing in my credentials is much more important.

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Platform: [e.g. Linux, Windows, iPhone, Tizen]
 - Browser: [e.g. Firefox, Chrome, Safari]
 - Jellyfin Version: [e.g. 10.6.0]

**Additional Context**

It only happens in HTTPS due to the web platform not allowing the permission
to be garnered by HTTP websites. It also specifically happens when the first
character of the username is clicked, leading me to believe Jellyfin is waiting for
any form of user input then throwing up the notification permission popup as soon
as possible.

**Comment by freshgum-bubbles** [comment]
Ahh, [here is the code](https://github.com/jellyfin/jellyfin-web/blob/5c09077a2f12ae44e7b7d356ea8d9f35862b0b60/src/components/notifications/notifications.js#L6) which seems to be causing all the trouble :D

**Comment by thornbill** [comment]
In the code linked in the comment above, the event listeners should be added within an event listener for the `localusersignedin`. Examples of listening for this event can be found in several other places of the code.
