### ISSUE TITLE
"Active devices" on dashboard not properly stacking/extending

### ISSUE THREAD

**Issue by DornJ** [jellyfin/jellyfin-web#3248]
**Describe The Bug**
The "active devices" part of the dashboard does not properly extend when there are enough devices active.

**Steps To Reproduce**

1. Go to the dashboard
2. Have more than 4 devices active (I have 7 right now - on my 15" 1080p screen if that matters)
3. See the far right edge of the screen, part of an active device is hidden there and inaccessible 
4. See attached image for example (far right)

**Expected Behavior**
The active devices should properly stack/extend to the bottom, not the right. Thus they would be accessible and visible

**Screenshots**
![bug](https://user-images.githubusercontent.com/79381458/147706436-18031699-d2ca-4709-80de-90402360364e.png)

**System (please complete the following information):**
Client:
 - Platform: Linux (PopOS 20.04)
 - Browser: Firefox (95.0.1 (64-bit))
 - Jellyfin Version: 10.7.7

Server:
- Ubuntu server 20.04

**Comment by butts136** [comment]
I have the same problem as you, Any solution instead of Zoom in to 150% or Zoom out to 33% ??

Thanks

**Comment by DornJ** [comment]
Not as far as I know sadly

------- Original Message -------

**Comment by enormouspoon** [comment]
I'm on 10.10.3 and still notice this issue. Has anyone seen any updates or improves to proper stacking?
