### ISSUE TITLE
Untranslatable strings

### ISSUE THREAD

**Issue by Shadowghost** [jellyfin/jellyfin-web#3256]
**Describe The Bug**
Some strings are hardcoded and not translateable:
* Anything in the Notification settings
* Anything in the Tasks settings

Thos strings can and are translated in the server.

**Steps To Reproduce**
1. Change Language to German
2. Go to `Dashboard -> Notifications`
3. Everything is English

**Expected Behavior**
The strings should either be translatable or server should properly serve translated strings based on client language.

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Firefox
 - Jellyfin Version: 10.8 unstable

**Comment by Shadowghost** [comment]
Sleep well my bot.

**Comment by alanazar** [comment]
Can you please confirm if this is still an issue? If so, can you please share a screenshot
I'm checking Weblate and I see all strings have already been translated to German:
https://translate.jellyfin.org/browse/jellyfin/jellyfin-core/de/
https://translate.jellyfin.org/translate/jellyfin/jellyfin-core/de/?offset=&q=Application+update+available&sort_by=-priority%2Cposition&checksum=

**Comment by Shadowghost** [comment]
The problem still exists in current master:
![grafik](https://user-images.githubusercontent.com/3741446/207814122-7fa5ad75-a578-407b-827e-013be9320a80.png)

**Comment by thornbill** [comment]
It's been a bit since we looked into this... aren't the strings translated server-side using the server's "preferred display language" setting? They just aren't translated to the user's language?
