### ISSUE TITLE
Changing display language to Spanish (Latin America) doesn't work

### ISSUE THREAD

**Issue by kugelvlitz** [jellyfin/jellyfin-web#3298]
**Describe The Bug**
Changing user display language to Spanish (Latin America) defaults to the server's preferred display language (in my case US english). I've tried this by leaving the option at auto and manually setting it, both cases give the same result.

I've noticed the server's preferred display language doesn't actually have an option for latin american spanish, might be the cause.

**Steps To Reproduce**
#### If your device is set to spanish of any specific latin american country (excluding Mexico and Argentina)
1. No action needed, UI language should have changed (but it doesn't).

#### If it isn't
1. Go to user settings
2. Go to display
3. On the display language option choose Spanish (Latin American)
4. Refresh page

**Expected Behavior**
UI should change to latin american spanish or just spanish. Either for users with devices set to that language with the auto option, or if manually chosen.

**Logs**
Checked logs but found none relating to this issue.

**Screenshots**
![Screenshot from 2022-01-05 17-54-52](https://user-images.githubusercontent.com/20900242/148306471-fd39336f-8f87-45c5-9da0-a4bf1c7e48f5.png)

**System:**
 - Web Platform: Tested on Arch Linux and Windows
 - Browser: Tested on Firefox and Chrome
 - Jellyfin Version: 10.7.7-2
 - Server OS: Arch Linux

**Comment by kugelvlitz** [comment]
Upon further inspection this might be a bigger issue about localization. As browsers don't have a single option for latin american spanish, but rather a wide selection of country specific options. Ideally latin america should refer to any country specific option on a given list.

**Comment by thornbill** [comment]
Want specific language option are you choosing?

**Comment by kugelvlitz** [comment]
Still an issue

**Comment by dmitrylyzo** [comment]
Fixed by  #4288
