### ISSUE TITLE
[Issue]: 10.8.0 Alpha5 Continues not showing vertical selector (# to Z) in Collections

### ISSUE THREAD

**Issue by MRDJellyfin** [jellyfin/jellyfin-web#3299]
### Please describe your bug

In Windows 10 64, when the Collections are sorted according to their Name and in ascending order, the vertical bar (# to Z) is shown, but if the Collections by Name are shown in descending order, the vertical bar disappears. In the stable version 10.7.7 it also has the same problem.

### Jellyfin Version

Other

### Environment

```markdown
- OS: Windows 10 64
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

<img width="960" alt="Captura de pantalla (101)" src="https://user-images.githubusercontent.com/82923908/148321301-4280225b-b702-4b62-a921-b86de2412127.png">

<img width="960" alt="Captura de pantalla (100)" src="https://user-images.githubusercontent.com/82923908/148321327-001f6524-6dcd-4e4c-a169-a9489d3c3562.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by grafixeyehero** [comment]
@MRDJellyfin @thornbill 
https://github.com/jellyfin/jellyfin-web/blob/fa5588733787caf3129b9d2fb79d2f3de953fc85/src/controllers/list.js#L224-L230
