### ISSUE TITLE
Login disclaimer: Add HTML support

### ISSUE THREAD

**Issue by doc-code-hub** [jellyfin/jellyfin-web#3304]
I am trying to use the "Login Disclaimer" to show the links of my 2 web clients (the original one, and the one written in Vue) but I noticed that the text is inserted as such and not as HTML.

This makes it impossible to have a working link (or even just a \<br> tag).

![image](https://user-images.githubusercontent.com/61033694/148681586-92abefc0-7088-4d12-aca3-d6f31b1fc953.png)

I think it would be nice to add support for this type of interactive Login Disclaimer

--------------------------

If you don't like the idea due to script injection, I would propose a separate property in branding to be able to add a script.

In my case I could solve it by simply running:

```$('#loginPage .disclaimer').html($('#loginPage .disclaimer').text())```

**_What do you think?_**

**Comment by LePips** [comment]
This can be solved using custom CSS and would require clients (if they implement the server message) to support HTML instead of a simple string for that field.

Seems like a won't do.
