### ISSUE TITLE
Fast Forward/Rewind with Scroll Wheel

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-web#331]
**Describe the feature you'd like**
Filing as per Reddit: https://www.reddit.com/r/jellyfin/comments/bmy7zc/fast_forward_and_rewind_with_scroll_wheel/

The user would like to use the scroll wheel to fast forward/rewind the currently playing media, similar to the function in VLC.

**Additional context**
In VLC, the user can scroll on the horizontal axis to scrub media, and on the vertical axis to control volume.

**Comment by DrPandemic** [comment]
I'm personally not the biggest fan. Overloading the scroll behavior really doesn't feel natural on a web app.

Also, I think it would only be for videos. This could not be generalized to any "playing media". The music players pretty much always need the scroll.

This would not produce a uniform experience.

**Comment by anthonylavado** [comment]
I personally think the keyboard shortcuts alone make it a pretty good experience. I did only say I would file the request, doesn’t mean we have to do it :-)
