### ISSUE TITLE
Metadata language priority

### ISSUE THREAD

**Issue by Dm3Ch** [jellyfin/jellyfin-web#332]
**Is your feature request related to a problem? Please describe.**

When you set metadata language to any language that is not so popular as English, you sometimes getting problem, that metadata is not available on selected language.

Moreover, when we are speaking about TV Shows one of two series following each other could have translated metadata and the other not.

**Describe the solution you'd like**

For my opinion it would be nice to have ability to specify multiple metadata languages prioritised. For example:
1) Russian
2) English

**Describe alternatives you've considered**

But for my opinion this idea could be simplified to just add option to peak English metadata when metadata on selected language is not available

**Additional context**

**Comment by DrPandemic** [comment]
I think this could be "solved" by https://github.com/jellyfin/jellyfin/issues/1342. That other issue is tagged for 1.4.0, so we should have it soon(ish).

What do you think?

**Comment by Dm3Ch** [comment]
@DrPandemic Yes, this two issues are same. Thank you.

/close
