### ISSUE TITLE
[Issue] Pagination broken/not working

### ISSUE THREAD

**Issue by felixoswald** [jellyfin/jellyfin-web#3325]
**Describe The Bug**
Jellyfin pagination is broken on :latest or :unstable Docker images with libraries of type "other".
If i create a new library with the same files but of type "movie" everything works fine.

**Steps To Reproduce**
1. get :latest or :unstable docker image
2. setup Jellyfin with a library of type "other" with many files in it (i don't know if this is relevant, but i disabled any metadata and image fetchers)
3. finish setup/scan
4. set users page size to 10
5. open the library to view e.g. movies
 -> unlimited size without any pagination

**Expected Behavior**
Use page size set in user settings

**Logs**
Browser-Log:
```
Requesting http://192.168.188.12:9097/Users/c68b9d4bb69a4900bc4549eff0xxxxxx/Items/09790ec4c9712e6dfb0961f346xxxxxx
@main.jellyfin.bundle.js?27523766f9fe23f5c2fc:2
Requesting http://192.168.188.12:9097/Users/c68b9d4bb69a4900bc4549eff0xxxxxx/Views
@main.jellyfin.bundle.js?27523766f9fe23f5c2fc:2
Requesting http://192.168.188.12:9097/Users/c68b9d4bb69a4900bc4549eff0xxxxxx/Items?Fields=PrimaryImageAspectRatio%2CSortName%2CPath%2CSongCount%2CChildCount%2CPrimaryImageAspectRatio&ImageTypeLimit=1&ParentId=09790ec4c9712e6dfb0961f346xxxxxx&SortBy=SortName&SortOrder=Ascending
main.jellyfin.bundle.js?27523766f9fe23f5c2fc:2
Requesting http://192.168.188.12:9097/System/Endpoint
@main.jellyfin.bundle.js?27523766f9fe23f5c2fc:2
```

**Screenshots**
page size is set to 10 as example:
![image](https://user-images.githubusercontent.com/52625423/149384067-8721156f-542f-4c5a-a8f4-25e5351d5e9d.png)

"real" page size is unlimited without pagination 
![image](https://user-images.githubusercontent.com/52625423/149384509-e024c632-db56-4fd3-8e29-1703703e4d58.png)

**System (please complete the following information):**
 - Platform: Windows, iPadOS, Android
 - Browser: Opera 82.0.4227.43 on Windows, Jellyfin Android App and iOS App
 - Jellyfin Version: latest 10.7.7 and also unstable 10.8.0 as Docker-Image

**Comment by dmitrylyzo** [comment]
Pagination is not implemented for listviews (Collections, Photos, Other).

**Comment by MRDJellyfin** [comment]
Alpha 5 on Windows 10 64
1.-) But if it is implemented in the Collections when they are selected inside the Movies Folder (horizontal options per word)?
2.-) When selecting within the Movies Folder Gender (horizontal options per word) and then a specific Gender, then it is not implemented?
3.-) But if the Gender is selected through the icon that there is (for different options including Genders), then if it is implemented?

**Comment by dmitrylyzo** [comment]
> 1.-) But if it is implemented in the Collections when they are selected inside the Movies Folder (horizontal options per word)?

The `Collections` tab in the movie library has its own controller that implements pagination (and it works fine). The `Collections` library uses `list.js` controller.

> 2.-) When selecting within the Movies Folder Gender (horizontal options per word) and then a specific Gender, then it is not implemented?

`Genres` tab? It also has no pagination (`moviegenres.js` controller), but I think the `Library page size` option doesn't fit there.

> 3.-) But if the Gender is selected through the icon that there is (for different options including Genders), then if it is implemented?

Do you mean selecting genres in the filters? Pagination works on query results with filters applied. Currently, this works for Music, Shows and Movies libraries - the libraries where pagination is implemented. Also the `Channels` tab in LiveTV.

**Comment by MRDJellyfin** [comment]
Thanks for your answer, I have no programming knowledge, my only goal is to make the use of Jellyfin easier to use, that's why I have been looking for those discrepancies (if they can be considered as such) so that they can be fixed (if possible ), since on the one hand the options appear in one way and on the other hand in another way, which causes confusion for a normal user (like me), since the Alpha versions came out I have dedicated my time to looking for them, so that they have knowledge of these and, if possible, they can implement the pertinent corrections before the final version 10.8.0 comes out. I know that the task that all the members of Jellyfin do is not easy, that is why I have tried to help them even in this way, not with the desire to criticize them but to help them and once again thank you very much for the work you do. (and sorry for terrible English)
