### ISSUE TITLE
Last subtitle line dont show up

### ISSUE THREAD

**Issue by EduFdezSoy** [jellyfin/jellyfin-web#3326]
The last line of the subtitles is not showing, only the last line. 

Tested in:
- Firefox: cuts the last line
- Android (exoplayer): working as expected
- VLC: working as expected  
  
The files tested are all **mkv** with **ass** subtitles inside  

I checked the subtitles but cant see anything wrong inside, here is the last line:  
`Dialogue: 0,0:10:25.58,0:10:29.17,Italics,Honda,0000,0000,0000,,That is the task of a comic bookstore.`  

---
**System:**
 - OS: Debian
 - Virtualization: none
 - Clients: Browser
 - Browser: Firefox 82.0.2 (64-bit)
 - Jellyfin Version: 10.6.4
 - Playback: DirectPlay  
 - Reverse Proxy: none
 - Base URL: none
 - Networking: host, local network under a private wiregard vpn 
 - Storage: local

**Comment by dmitrylyzo** [comment]
> Issue is probably caused by the JavascriptSubtitlesOctopus library.

Yes, this can be fixed with https://github.com/jellyfin/JavascriptSubtitlesOctopus/pull/21
There is a better fix for tag parser in the upstream, but that PR has stalled.

**Comment by Feynt** [comment]
Reporting in, can confirm this is still an ongoing issue.  Inserting an extra garbage line into subtitles will allow me to read the final proper line in the videos.

**Comment by dmitrylyzo** [comment]
Fixed by #3644
