### ISSUE TITLE
Hdr subtitles too bright

### ISSUE THREAD

**Issue by bernharl** [jellyfin/jellyfin-web#3327]
**Describe The Bug**
See: https://github.com/jellyfin/jellyfin-webos/issues/73
> When watching an HDR movie the subtitles appear extremely bright. Is there a way to adjust this?

**Media Information**
4k HDR bluray mp4 remux.

**System (please complete the following information):**
 - Platform: Arch Linux server, WebOS client (LG C1 OLED)
 - Browser: jellyfin-webos
 - Jellyfin Version: 10.7.7

**Comment by anthonylavado** [comment]
To help sort out where this ends up - are they external subtitles (e.g. SRT), or are they graphical subtitles from the remux itself (e.g. PGS-SUB)?

If you don't know off hand, it should be listed in the media info of the video in Jellyfin.

**Comment by bernharl** [comment]
They are external SRT files.

**Comment by dmitrylyzo** [comment]
There are several hidden options (from Emby time): https://github.com/jellyfin/jellyfin-web/blob/afd37d62877a765a2284ae55821f0dff35062080/src/components/subtitlesettings/subtitlesettings.template.html#L87-L93
They currently work for text subtitles (SRT only?), but they are just text fields - not easy to enter.
_If someone made a color picker._ :relaxed:

@bernharl This branding CSS might work as a workaround.
```css
.htmlvideoplayer::cue {
    color: #ccc !important;
}
```

**Comment by tomikaka22** [comment]
Any development on this?

**Comment by thornbill** [comment]
A subtitle color picker was added in unstable recently so this should be fixed in the next major release (10.9).

**Comment by draakiiii** [comment]
It would be nice to be able to change the opacity of the subtitles

**Comment by mtbossa** [comment]
> There are several hidden options (from Emby time):
> 
> [jellyfin-web/src/components/subtitlesettings/subtitlesettings.template.html](https://github.com/jellyfin/jellyfin-web/blob/afd37d62877a765a2284ae55821f0dff35062080/src/components/subtitlesettings/subtitlesettings.template.html#L87-L93)
> 
> Lines 87 to 93 in [afd37d6](/jellyfin/jellyfin-web/commit/afd37d62877a765a2284ae55821f0dff35062080)
> 
>  <div class="inputContainer hide"> 
>      <input is="emby-input" id="inputTextBackground" label="${LabelTextBackgroundColor}" type="text" /> 
>  </div> 
>   
>  <div class="inputContainer hide"> 
>      <input is="emby-input" id="inputTextColor" label="${LabelTextColor}" type="text" /> 
>  </div> 
> 
> They currently work for text subtitles (SRT only?), but they are just text fields - not easy to enter.
> _If someone made a color picker._ ☺️
> [@bernharl](https://github.com/bernharl) This branding CSS might work as a workaround.
> 
> .layout-tv .htmlvideoplayer::cue,
> .layout-tv .videoSubtitlesInner {
>     color: #ccc !important;
> }

This has actually fixed my issue. This is the value I'm using, but we can play around this, add background, change shadow... But this is good enough for me.

```css
.layout-tv .htmlvideoplayer::cue,
.layout-tv .videoSubtitlesInner {
    color: rgba(165, 145, 20, 0.78) !important;
}
```

Thank you @dmitrylyzo!
