### ISSUE TITLE
[Issue]: 10.8.0 Alpha 5 Trailer not running

### ISSUE THREAD

**Issue by MRDJellyfin** [jellyfin/jellyfin-web#3333]
### Please describe your bug

In Windows 10 64, in the videos in which the trailer icon is activated when selecting it, only a circle (not complete) appears as if it wants to execute something and it stays that way all the time, doing nothing (in a test, leave it up to 5 minutes ). In the stable version 10.7.7 the trailer immediately runs. I did it both in google and in media player with the same result, the same movies (10) were used for the tests.

### Jellyfin Version

Other

### Environment

```markdown
- OS: Windows 10 64
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![Captura de pantalla (114)](https://user-images.githubusercontent.com/82923908/149322572-07a0a223-d353-4de2-95ac-58b39b62da62.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hasezoey** [comment]
can confirm the fix works after having updated

though i just noticed that when playing remote content (like a trailer from youtube), the remote player is still shown (like in the case of youtube: the title and "more videos")
