### ISSUE TITLE
Allowing media to transcode or to be converted causes forced transcoding of some media types

### ISSUE THREAD

**Issue by exalented** [jellyfin/jellyfin-web#3375]
**Describe The Live TV Bug**
In the per user settings within the dashboard, 'allow video playback that requires transcoding' ticked will cause 'video birate exceeds limit' or 'container bitrate exceeds limit' of Live TV regardless if it's a HLS, mpegts or http source.

**Describe the AV1 issues on WebOS**
AV1 content is not allowed to direct play, even for tvs that support it, if one of the following user settings is set:
`Allow audio playback that requires transcoding`
`Allow video playback that requires transcoding`
`Allow video playback that requires conversion without re-encoding`

**Steps To Reproduce LiveTV forced transcoding**
1. Enable and setup TVHeadend plugin.
2. Tick  'allow video playback that requires transcoding'.
3. Play LiveTV.
4. Witness forced transcode.

**Steps To Reproduce AV1 content transcoding**
1. Have AV1 encoded content
2. Enable one of the 3 allowed transcoding or conversion options in the Media playback section for the user.
3. Play AV1 content on a WebOS TV that supports the codec.
4. Witness forced transcode.

**Expected Behavior**
If the client supports direct playing the content the content should be played without transcoding, muxing or converting the media.

**Live TV Logs**
[jellyfinforcetranscodes.log](https://github.com/jellyfin/jellyfin-web/files/7990342/jellyfinforcetranscodes.log)

**System:**
 - Platform: WebOS, Android
 - Browser: https://github.com/jellyfin/jellyfin-android , https://github.com/jellyfin/jellyfin-webos
 - Jellyfin Version: 10.8.0_alpha1, 20220130.2-unstable docker containers

**Additional Context of Live TV playback issues**
Disabling 'allow video playback that requires transcoding' will allow a remux on WebOS and Android clients.

https://github.com/jellyfin/jellyfin-webos/issues/61

**Additional Context of AV1 playback issues**
Disabling options listed above in the Media playback section will allow direct play on WebOS.

- [ ] Live TV force transcodes because of bitrate
- [X] ~~AV1 content not direct playing on WebOS for those that support the codec~~ (fixed with https://github.com/jellyfin/jellyfin-web/pull/3380)

**Comment by dmitrylyzo** [comment]
@exalented Could you test #3380?

**Comment by exalented** [comment]
> @exalented Could you test #3380 (AV1 codec)?

YES! This works!
