### ISSUE TITLE
BREAKING CHANGE  Users can no longer schedule DVR series recording 

### ISSUE THREAD

**Issue by dinki** [jellyfin/jellyfin-web#338]
**Describe the bug**
A major issue for DVR users.  Users can no longer set up series recordings (aka repeat recordings of a tv series) under 10.3.3

**To Reproduce**

1. Go to Live TV->Guide
2. Click on any program
3. Click 'Record series' button
4. See nothing happens

**Expected behavior**
When clicking the 'record series' button an additional dialog window should provide additional options.  This window does not appear.   I'm pretty sure this was fixed for 10.3.2 but is now quite broken.

**Logs**
Nothing in logs

**Screenshots**
![Capture](https://user-images.githubusercontent.com/2521542/58339659-afc45680-7e0f-11e9-8fc6-0d4bcdf16e68.JPG)

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.3.3

**Additional context**

This one really hurts.  It makes it very difficult to schedule recordings especially with new shows premiering.

**Comment by dinki** [comment]
Here's the error from Chrome dev tools console.  Not sure what it means though:

![Capture](https://user-images.githubusercontent.com/2521542/58341349-a76e1a80-7e13-11e9-8f7a-4511c0c7989f.JPG)

**Comment by anthonylavado** [comment]
Okay, there is also https://github.com/jellyfin/jellyfin/issues/1371 and https://github.com/jellyfin/jellyfin/issues/1385.

Though the others came first, I'm willing to close them as duplicates in favour of this one. Are they the same issue?

**Comment by dinki** [comment]
@anthonylavado Apologies for not searching before posting.  Yes, those two do seem to be for this same issue.

**Comment by anthonylavado** [comment]
@dinki No worries, this seems like it might be a web issue at first glance, so I will mark those others accordingly.

**Comment by dinki** [comment]
@cvium Fix works great.  Closing issue.  Thanks for the quick turnaround guys!
