### ISSUE TITLE
OSD header being hidden

### ISSUE THREAD

**Issue by exalented** [jellyfin/jellyfin-web#3382]
**Describe the 1st instance**

- [ ] When the user is playing audio *and then* starts a new syncplay group the OSD header get's hidden because the audio player inherits the video player and there is no other logic for this.

**Steps To Reproduce Bug 1**
1. Play some music
2. Start a new syncplay group
3. Witness header disappearing (Notice how you can still interact with it).
    Note: In chromium pause music to witness breif unhiding of header
4. Play a video
5. OSD header is now visible again
6. Repeat?

**Describe the 2nd instance**

- [ ] When two or more people play a video using syncplay and exit that video by playing audio the person that leaves will experience a hidden OSD header.

**Steps To Reproduce Bug 2** (found here: https://github.com/jellyfin/jellyfin-web/issues/3382#issuecomment-1029735378)

1. Start SyncPlay group with 2 clients.
2. Start the video playback.
3. Start the audio playback on the first client.
4. The video player is still in use on the second client, and it behaves the same way, hiding the OSD.

**Expected Behavior**
When playing audio the OSD header is always present.

**Logs**
Not relevent

**Screenshots**
![image](https://user-images.githubusercontent.com/9328864/152463260-cfb4a5fa-945b-4b55-892c-883719d7f803.png)

**System:**
 - Platform: Linux, Windows, Android, WebOS, etc
 - Browser: Chromium, WebOS
 - Jellyfin Version: 10.8.0_alpha5, 20220130.2-unstable

**Additional Context**
I've noticed this is not reproducable 100% of the time, but it does happen often.

I believe here are the two functions in question: https://github.com/jellyfin/jellyfin-web/blob/2677b2babe8687085d00abe868f53dd0ab49dbaf/src/controllers/playback/video/index.js#L275
https://github.com/jellyfin/jellyfin-web/blob/2677b2babe8687085d00abe868f53dd0ab49dbaf/src/controllers/playback/video/index.js#L292

**Comment by exalented** [comment]
I've noticed this issue to more reproducable when you have more than 1000ms of latency between the server and the client.

**Comment by dmitrylyzo** [comment]
I don't get how to reproduce the issue, but if you're talking about what I think:
1. Create a playlist: `[video, audio]`
2. Start playing of this playlist.
3. The video player opens.
4. Skip the video.
5. The video player is still in use, and it behaves the same way, hiding the OSD.

Is this the same as yours?

**Comment by exalented** [comment]
> I don't get how to reproduce the issue, but if you're talking about what I think:
> 
> 1. Create a playlist: `[video, audio]`
> 2. Start playing of this playlist.
> 3. The video player opens.
> 4. Skip the video.
> 5. The video player is still in use, and it behaves the same way, hiding the OSD.
> 
> Is this the same as yours?

No. This is incorrect.

The issue is with the OSD header being hidden when it's not supposed to be. Precisely, it it being hidden (like when you experience playing a video) when starting a syncplay group.

In the reproduce notes I mention playing a video as means of 'reseting' the client to get the OSD header to show up again.

Sometimes this bug can be triggered only after you exit playing a video which is why I mentioned it.
