### ISSUE TITLE
TV Mode: Focus always set to My Media first item

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin-web#3413]
**Describe The Bug**

When in TV Display mode, focus is set to first item in "My Media" even if other home sections are displayed first.

**Steps To Reproduce**

1. User menu > Home. Move "My media" so it is not the first section
2. User menu > Display > Display Mode > TV 
3. Reload home screen
4. use arrow keys to move right
5. display will scroll to 2nd item in My media

**Expected Behavior**

Focus should be set to first item in first home section.

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Chrome
 - Jellyfin Version: 10.7.7

**Comment by dmitrylyzo** [comment]
That's because `returnPromise` is `false`: https://github.com/jellyfin/jellyfin-web/blob/6ae47415d0c6483ea26328196e28dd3254d94687/src/components/homesections/homesections.js#L77
But why? :man_shrugging:
