### ISSUE TITLE
Player dimensions wrong reported

### ISSUE THREAD

**Issue by JPVenson** [jellyfin/jellyfin-web#3418]
**Describe The Bug**
Using a 4K resolution monitor and playing back any video (ether with 1080p or 4K video resolution) the stats for nerds report only a "Player dimensions" of 1920x1008 when fully expanded browser and in fullscreen only 1920x1080.

**Steps To Reproduce**
1. Use a 4K native resolution monitor
2. Start playback of any video
3. Go into fullscreen
4. Open settings cog
5. Open "Playback Data"
6. Player Dimensions is 1920x1080

**Expected Behavior**
6. Player Dimensions is 3840x2160

**Logs**

**Screenshots**
![image](https://user-images.githubusercontent.com/6794763/153466644-a50b5e52-57b2-4dbb-bfc1-2c14befc182e.png)

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Edge Version 98.0.1108.43 (Official build) (64-bit)
 - Jellyfin Version: 10.7.7

**Additional Context**

**Comment by dmitrylyzo** [comment]
Do you use system-wide scaling in Windows?
Do you use scaling in the browser?
Could you check what `window.devicePixelRatio` outputs in the browser console?

**Comment by JPVenson** [comment]
> Do you use system-wide scaling in Windows?
Yes 200%
![image](https://user-images.githubusercontent.com/6794763/153494075-4c4deb2d-96f4-41de-8ce3-d9dc41051e9f.png)
> Do you use scaling in the browser?
No 100% browser scale
> Could you check what window.devicePixelRatio outputs in the browser console?
```
window.devicePixelRatio
2
```

**Comment by dmitrylyzo** [comment]
At first glance, we just need to multiply the player dimensions by `window.devicePixelRatio`.
I got the same results using 200% browser scaling.

**Comment by JPVenson** [comment]
Does the player dimensions only have verbose properties or are they used in any other way?

**Comment by dmitrylyzo** [comment]
These dimensions are in virtual (scaled) space. If you set the scale to 50% (even during playback), the player doubles in size, but the video remains the same.
