### ISSUE TITLE
Library settings not submitting.

### ISSUE THREAD

**Issue by lotrez** [jellyfin/jellyfin-web#3421]
**Describe The Bug**
The form with all the settings for a library does not submit.

**Steps To Reproduce**
1. Go in dashboard
2. Go in libraries
3. Hit "Manage library" on any library
4. Change settings
5. Hit "Save"
**Expected Behavior**
The loading icon appears for a short moment and the form closes. Saving the settings in the process.

**Logs**
`main.jellyfin.bundle.js?b1418c5080b0e3ffc59b:2 Uncaught Error: null name
    at e.value (main.jellyfin.bundle.js?b1418c5080b0e3ffc59b:2:768281)
    at HTMLButtonElement.c (8706.4fe838da22447ae51119.chunk.js:1:618)
value @ main.jellyfin.bundle.js?b1418c5080b0e3ffc59b:2
c @ 8706.4fe838da22447ae51119.chunk.js:1`

On a local clone of jellyfin-web:
`jellyfin-apiclient.js:1 Uncaught Error: null name
    at e.value (main.jellyfin.bundle.js:54067:26051)
    at HTMLButtonElement.onEditLibrary (:8080/components_mediaLibraryEditor_mediaLibraryEditor_js.b835b458a96136148946.chunk.js:102:13)`

**Screenshots**
![chrome_BNEhvvb24E](https://user-images.githubusercontent.com/12872141/153651258-9db3ebec-87a1-4909-a78f-89863ca41ebf.png)
![chrome_O5Wb9air7z](https://user-images.githubusercontent.com/12872141/153651257-dfe72b02-2111-46d7-b753-7fc09a1cda6b.png)
![chrome_zYj32rFTt2](https://user-images.githubusercontent.com/12872141/153651256-0cad0bc2-09e0-4259-9fe0-459448884b8b.png)

**System (please complete the following information):**
 - Platform: Ubuntu Server 20.04 In docker container
 - Browser: Chrome 98.0.4758.82
 - Jellyfin Version: 10.8.0-alpha5

**Additional Context**

**Comment by dmitrylyzo** [comment]
Try to `Disable cache` on the `Network` tab in the browser and refresh.

**Comment by dmitrylyzo** [comment]
`ItemId` goes from the server:
https://github.com/jellyfin/jellyfin-web/blob/9a6ba2927b80dd069de333c7184a34dda5a39db3/src/controllers/dashboard/library.js#L154-L156

Since I cannot reproduce, could you check if there is an `ItemId` for bugged library in the `/Library/VirtualFolders` response (`Network` tab)?

**Comment by lotrez** [comment]
No there isn't.
Audio Books and Anime V2 are not bugegd while all the others have this problem.
![image](https://user-images.githubusercontent.com/12872141/153658182-f9d23844-6eac-4f03-a10f-b499b25f1d31.png)

**Comment by adam-stanek** [comment]
Same issue here. No ItemId either. Tested on both 10.7.7 and 10.8.0-beta1. My guess is that something went wrong with the migration to newer version. When I create a new library it gets ItemId.

**Comment by dgalli1** [comment]
Probably  not related  to this  issue, but in my case this didn't work anymore after I migrated from  the linuxserver container  to the  official.

To fix it I had to manually  edit  the  library.db

I had to change the Path  variable for every entry in the "TypedBaseItems" Table with the Type "MediaBrowser.Controller.Entities.CollectionFolder" The Variable AppDataPath was used in the  old entries which didn't work.

For example:
Old Path: %AppDataPath%/root/default/Serien
New Path: /config/root/default/Serien

After this change I had to restart the jellyfin server and now I can edit the settings without any issue

**Comment by brianjmurrell** [comment]
Any resolution to this pretty old bug?  I seem to be hitting it now after having migrated from 10.7 to 10.8.
