### ISSUE TITLE
LG TV can't directplay video with opus audio

### ISSUE THREAD

**Issue by reyqn** [jellyfin/jellyfin-web#3429]
**Describe The Bug**

I'm not sure why, but opus audio directplay is explicitely disabled for lg tvs in the code: if (!browser.web0s)
My TV can play videos with opus audio just fine from usb, so maybe it could be possible through jellyfin?

**Media Information**
directplayprofile { Container: "mkv", AudioCodec: "aac,mp3,ac3,eac3,mp2,pcm_s16le,pcm_s24le,flac,vorbis", VideoCodec: "h264,hevc,mpeg2video,vc1,vp8,vp9,av1", Type: Video }
No opus there.

**Screenshots**
![image](https://user-images.githubusercontent.com/12498695/154092558-12229d52-d143-45b5-98e1-436d4890a12b.png)

**System (please complete the following information):**
 - Platform: LG WebOS 5.3.0-2202 (jellyfin-webos)
 - Browser: Chromium 68 web engine
 - Jellyfin Version: 10.8.0-alpha5

**Comment by dmitrylyzo** [comment]
> So I wasn't sure how to do so, I just downloaded the jellyfin-web-development (not jellyfin-web-production) zip from your link, and served it with node http-server.

I usually rename the installed web (on the server) and put the unpacked/compiled one in its place. Then, after testing, I just revert all back.
_On Ubuntu it is in `/usr/share/jellyfin/web`._

> Connected to it via the web browser (not lg jellyfin-webos app) this time.

LG web browser has the web engine newer than in app.

> Sadly even though the video plays, I don't have sound.
> Could this be related to #2672 maybe? Even though I doubt it since opus is now in my directplayprofile : DirectPlayProfile { Container: "mkv", AudioCodec: "aac,mp3,ac3,eac3,mp2,pcm_s16le,pcm_s24le,opus,flac,vorbis", VideoCodec: "h264,hevc,mpeg2video,vc1,vp8,vp9", Type: Video }

How does it play? `DirectPlay`/`Remux`/`DirectStream`/`Transcode`?
_Can look on Dashboard or in Playback Info._

> Also from what I understand HLS is used only in transcoding?

HLS is used when `Remux`/`DirectStream`/`Transcode`.

> Maybe using the app would work better, but again I'm not sure it makes a difference, I don't really know how jellyfin works...

As I said, the browser and the app have different web engines. Also, sometimes the app has more supported codecs - maybe this is the case.

> The TV must be able to play opus somehow (since the file I try to play with jellyfin has only one audio track and it works with usb), but maybe adding this feature to jellyfin isn't that easy

At least we need it to play `DirectPlay` - this would mean that the video is loaded as is.

**Comment by dmitrylyzo** [comment]
OK, I'm shipping the current version. We can switch to version checking if `canPlayType` doesn't work.

**Comment by reyqn** [comment]
Just chiming in to say I was able to try this out on the lg webos app with the nightly docker release, works perfectly. Thanks again!
