### ISSUE TITLE
Comics: Add support for .zip and .rar comics

### ISSUE THREAD

**Issue by matthewstrasiotto** [jellyfin/jellyfin-web#3446]
**Describe The Bug**

The current behaviour for the comic player is to determine whether a file is a comic based on the extension, either `.cbz`, or `.cbr`

https://github.com/jellyfin/jellyfin-web/blob/29faa698b72a05c1c6ff39a087e2091b10c705df/src/plugins/comicsPlayer/plugin.js#L236

These are simply `.zip` and `.rar` archives, with a different extension to indicate the content type. 

I think it would be helpful to allow these files to be read directly, possibly with a per-library toggle for readign `.zip` and `.rar` files as comics. 

**Media Information**
NA

**Screenshots**
NA

**System (please complete the following information):**
 - Jellyfin Version: 10.7

**Comment by ibz096** [comment]
I'm new to this project, but doesn't line 236 define only if the content is playable. Meaning the play button appears. I'm testing on 10.7 and I am not even able to import .zip files.

**Comment by matthewstrasiotto** [comment]
@ibz096 you might be right - I assumed this method is used for both playback & indexing processes, but I haven't reviewed the codebase that thoroughly. 

This change may also be reflected in some jellyfin server backend settings

**Comment by thornbill** [comment]
Seems like it might be here... https://github.com/jellyfin/jellyfin/blob/076a13abeb344f7a79d81cce030799c8e77dbfaf/Emby.Server.Implementations/Library/Resolvers/Books/BookResolver.cs#L17

**Comment by matthewstrasiotto** [comment]
> Seems like it might be here... https://github.com/jellyfin/jellyfin/blob/076a13abeb344f7a79d81cce030799c8e77dbfaf/Emby.Server.Implementations/Library/Resolvers/Books/BookResolver.cs#L17

that looks exactly like it.

I don't know what the consensus would be re. just allowing .zips as a format, as it there might be instances where people have zips in their book directories that aren't intended to be read as a comics.

Maybe it's fine?

**Comment by MinecraftPlaye** [comment]
> that looks exactly like it.
>
> I don't know what the consensus would be re. just allowing .zips as a format, as it there might be instances where people have zips in their book directories that aren't intended to be read as a comics.
>
> Maybe it's fine?

I'm not sure why anyone would have a zip file in their book library. I mean, wouldn't you just store books and comic files in there?

You might also want to check [out this line in the bookshelf plugin](https://github.com/jellyfin/jellyfin-plugin-bookshelf/blob/d01dea697169a4134a1b11bd468dba246943e634/Jellyfin.Plugin.Bookshelf/Providers/ComicInfo/InternalComicInfoProvider.cs#L125).
All it does is check that the file is a cbz file before opening it and checking it for ComicInfo metadata (which is just a file called `ComicInfo.xml` that lays within the archive)

**Comment by matthewstrasiotto** [comment]
ping

**Comment by thornbill** [comment]
Closing per https://github.com/jellyfin/jellyfin-web/pull/3507#issuecomment-1261278538
