### ISSUE TITLE
Alternate Interface

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-web#345]
**Describe the feature you'd like**
Recording a request for an alternate interface layout, as seen on the forums, and on Reddit.

Links will follow.

**Additional context**
https://www.reddit.com/r/jellyfin/comments/btcjni/interface_ideas_for_the_web_interface_or_actual/
https://www.reddit.com/r/jellyfin/comments/btkdvw/another_mockupf_for_new_interface_elements_yay/

**Comment by ma-karai** [comment]
Also check your forum, the guy made a nice post there :)
