### ISSUE TITLE
AirPlay support

### ISSUE THREAD

**Issue by dprandzioch** [jellyfin/jellyfin-web#346]
**Describe the feature you'd like**
If you are on a Mac, many web players like YouTube support streaming the currently active video to an AirPlay compatible device. It would be great if the Jellyfin web interface would support this since the device-support, at least in the Apple ecosystem, is very limited (no iOS/tvOS app). Since the implementation of AirPlay in smart TVs is also increasing, it could be a good fit.

**Additional context**
<img width="357" alt="Bildschirmfoto 2019-05-28 um 21 12 57" src="https://user-images.githubusercontent.com/4499821/58505520-6d8f7200-818d-11e9-9e45-8f25bee2758a.png">

**Comment by anthonylavado** [comment]
On iOS you can airplay if you fullscreen the video, but I agree - adding a dedicated button is a good way to go.

I tried to make it work a while ago and didn’t get anywhere. I’ll try again.

**Comment by vaheed** [comment]
+1
