### ISSUE TITLE
Going from poster to thumb view breaks the UI

### ISSUE THREAD

**Issue by tehnull** [jellyfin/jellyfin-web#347]
Selecting thumb view in the movie library causes any of the other menu icons on the header to become unusable. Clicking them causes you to be forwarded to a movie title page rendering the user unable to return to poster view or use any library sorting feature changes.

 - OS: Debian
 - Browser: Firefox 60.7.0esr (64bit)
 - Jellyfin Version: 10.3.3

**Comment by oddstr13** [comment]
**Restoring opacity of the offending HTML element;**
![image](https://user-images.githubusercontent.com/638706/58597558-cd167c00-8278-11e9-9a1d-1c9c51150292.png)

**Note the green bars indicating what I've changed (opacity from 0 to 1, added display:none)**
![image](https://user-images.githubusercontent.com/638706/58597581-e3243c80-8278-11e9-85ca-299523adfa44.png)

**Culprit with missing thumbnail**
![image](https://user-images.githubusercontent.com/638706/58597650-39917b00-8279-11e9-97d2-085497f44f2b.png)

**Offending HTML;**
![image](https://user-images.githubusercontent.com/638706/58597694-68a7ec80-8279-11e9-8231-d2af224fc99e.png)

Adding `display: none` in the css shown above restores the functionality of the interface, so you can change listing display back.

I think it may be related to missing Thumb image on the movie ending up blocking the interface

**Comment by oddstr13** [comment]
May be related to #228 and #280.
Potential fix merged #264 — in `master` — and is *not* in `release-10.3.z`.

**Comment by oddstr13** [comment]
As far as I can tell, the changes in #264 does indeed fix this issue.
