### ISSUE TITLE
Allow data format dd/MM/yyyy or Long date 28 February 2022

### ISSUE THREAD

**Issue by sourpatched** [jellyfin/jellyfin-web#3470]
Android shows the "correct date" in long format however Jelly web shows data in MM/DD/YYYY outside the US this is confusing as there is no 28 month. 

I've checked browser language settings and OS setting, all is good.

**Comment by sourpatched** [comment]
Can this be an option?

**Comment by thornbill** [comment]
An option for this already exists under User Menu > Display. There you can change the Date Time Locale to an appropriate value. It will use the browser locale information by default.

![image](https://user-images.githubusercontent.com/3450688/164237349-f269dada-f203-4a8b-94e5-56a869a42d32.jpeg)

**Comment by sourpatched** [comment]
I have it set to UK format, date doesn't change. 

![Screenshot 2022-04-21 at 15-28-48 Jellyfin](https://user-images.githubusercontent.com/99369884/164380856-804d6058-3c27-4624-829d-14b4ea1231eb.png)
e

**Comment by thornbill** [comment]
Where are you seeing the date that is not properly formatted?

**Comment by e5150** [comment]
> Where are you seeing the date that is not properly formatted?

The metadata editor seems to only ever use US-formated dates
