### ISSUE TITLE
Runtime doesn't update when switching movie versions

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin-web#3483]
**Describe The Bug**
See title.

**Steps To Reproduce**

1. Go to movie with more than one version
2. Note runtime
3. switch to other version
4. note runtime doesn't update, but media info does 

**Expected Behavior**

Runtime should show for version selected.

**Screenshots**

Extended version with correct runtime
![image](https://user-images.githubusercontent.com/991618/156895524-eb4ab40e-e3b9-4fa7-8531-85d8c54db4cb.png)
Theatrical with incorrect runtime (still showing extended time)
![image](https://user-images.githubusercontent.com/991618/156895519-fa00c608-7308-4c37-9a61-55653216790f.png)

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Chrome
 - Jellyfin Version: 10.7.7

**Comment by MikeVensel** [comment]
I am now running into this issue. Can this issue be reopened?

**Comment by thornbill** [comment]
This should be fixed in the next major release: https://github.com/jellyfin/jellyfin-web/pull/4496

**Comment by MikeVensel** [comment]
@thornbill Thanks for getting back to me so quickly. I was actually just pulling the repo to take a look myself and noticed that it was fixed.
