### ISSUE TITLE
Double clicking the player skips forward or backward instead of fullscreen

### ISSUE THREAD

**Issue by zjeffer** [jellyfin/jellyfin-web#3486]
**Describe The Bug**

Double clicking the player skips forward or backward instead of fullscreen. This only happens on Windows, not on Linux.

**Steps To Reproduce**

1. Play a video
2. Double click the left half of the screen. The video will skip backwards.
3. Double click the right half of the screen. The video will skip forwards.

**Expected Behavior**

The video should fullscreen. If already fullscreen, it should exit fulscreen.

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Platform: Windows 11
 - Browser: Firefox. Also happens in jellyfin-media-player (but not on Linux)
 - Jellyfin Version: `10.7.7-1`

**Additional Context**

**Comment by thornbill** [comment]
Do you have a touch screen? It sounds like you are getting the touch controls in Windows. They will be removed in the next release. The current touch controls caused a lot of issues and confusion, and so far no one has seemed to miss them in the 10.8 alpha releases.
