### ISSUE TITLE
Stuttering x265 videos

### ISSUE THREAD

**Issue by adyanth** [jellyfin/jellyfin-web#3487]
**Describe The Bug**
When playing HEVC/x265 videos (which is most of what I use) from the browser, the video is a stuttering mess. When the same file is played over the Jellyfin desktop app, everything is good. This is not specific to jellyfin, playing x265 videos in the browser causes this issue. For ex: https://test-videos.co.uk/vids/bigbuckbunny/mp4/h265/1080/Big_Buck_Bunny_1080_10s_1MB.mp4

I would be fine if this invoked transcoding, but that does not happen. I need to set the quality to 480p or lower for it to start transcoding, and then it works fine (albeit with lower resolution)

**Media Information**
ffprobe version 2021-04-18-git-d43b26b30d-essentials_build-www.gyan.dev Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      56. 73.100 / 56. 73.100
  libavcodec     58.136.101 / 58.136.101
  libavformat    58. 78.100 / 58. 78.100
  libavdevice    58. 14.100 / 58. 14.100
  libavfilter     7.111.100 /  7.111.100
  libswscale      5. 10.100 /  5. 10.100
  libswresample   3. 10.100 /  3. 10.100
  libpostproc    55. 10.100 / 55. 10.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Big_Buck_Bunny_1080_10s_1MB.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    title           : Big Buck Bunny, Sunflower version
    artist          : Blender Foundation 2008, Janus Bager Kristensen 2013
    composer        : Sacha Goedegebure
    encoder         : Lavf58.10.100
    comment         : Creative Commons Attribution 3.0 - http://bbb3d.renderfarming.net
    genre           : Animation
  Duration: 00:00:10.00, start: 0.000000, bitrate: 839 kb/s
  Stream #0:0(und): Video: hevc (Main) (hev1 / 0x31766568), yuv420p(tv, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 834 kb/s, 30 fps, 30 tbr, 15360 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]

**Screenshots**
![image](https://user-images.githubusercontent.com/33192449/157292514-bc50e4ec-247b-4536-9d9d-cd0f7726ce3f.png)
![image](https://user-images.githubusercontent.com/33192449/157292585-3319d30e-b4e1-4ada-b584-4cd3cf0a500e.png)

**System (please complete the following information):**
 - Platform: Windows, macOS
 - Browser: Edge, Safari
 - Jellyfin Version: 10.7.7

**Additional Context**
I understand this is a browser issue, but why wont Jellyfin invoke transcoding for these? Is there a way I can force it to transcode to x264?

**Comment by adyanth** [comment]
![image](https://user-images.githubusercontent.com/33192449/157292971-ab841ff9-a5cb-4878-b39e-0dda3452849e.png)
Chrome does the right thing, but Edge does not. Neither does Safari, the two browsers I use.

**Comment by nyanmisaka** [comment]
Update Edge and HEVC extension.
https://www.reddit.com/r/jellyfin/comments/t6bq8t/psa_edge_99_hevc_extension_10503620_fixed_the/

**Comment by adyanth** [comment]
Damn! I have AMD + NVIDIA as you say here, and I also have the device manufacturer extension installed. Let me try uninstalling that.
https://github.com/jellyfin/jellyfin-web/issues/2180#issuecomment-743719231

**Comment by TimGels** [comment]
> And somehow I don't see the issue now on Safari and Edge on macOS either, they are transcoding with VideoCodecNotSupported.

Only Edge on Windows has HEVC support with the extension from the Microsoft store. And the problem (that now has been fixed) with the b-frames lies with Edge in combination with that extension.

> Is there any way to force transcoding though?

I don't think you can force transcoding, but I have not looked into that in a while. I heard some people say they limited the upload and try to do it that way, but I never tested that and sounds a bit hacky. Another way (like you mentioned earlier) is to change the resolution when playing it.

> If not, can that be a feature request?

Sure thing, you can check [here](https://features.jellyfin.org/) if it has been requested already and upvote it, or otherwise make the feature request.

**Comment by adyanth** [comment]
Okay, sure. Thanks!
