### ISSUE TITLE
Video transcoding due to audio?

### ISSUE THREAD

**Issue by EnragedN3wb** [jellyfin/jellyfin-web#3518]
I'm trying to get my Roku TV to direct play 4K HDR content, but it keeps needlessly transcoding the video due to audio format. The TV is using a set of stereo speakers & the videos have 5.1-7.1 depending, but instead of only transcoding/downmixing the audio, it transcodes the video too... Losing HDR in the process. =\

The only way I can get the TV to directplay is to disable video transcoding entirely, meaning I can no longer watch anything on my tablet   when needed...

The only reason given for the transcode is "AudioChannelsNotSupported" & I have tried both without bandwidth limits & with extremely high bandwidth limits(though this is all over LAN anyway).

**Comment by dmitrylyzo** [comment]
If 10.7 - https://github.com/jellyfin/jellyfin/issues/5576
In 10.8, that seems to be fixed to me (at first glance).

**Comment by EnragedN3wb** [comment]
Yeah I'm using 10.7.7 Stable(not portable), but that link is a bit over my head currently.

If I drop the files from the "combined/jellyfin_20220327.5-unstable.zip" [here](https://repo.jellyfin.org/releases/server/windows/unstable/) will that work to update it without losing all my settings or am I better off just waiting for 10.8 stable with the installer?

**Comment by dmitrylyzo** [comment]
You can switch to 10.8 beta (released recently): https://repo.jellyfin.org/releases/server/windows/stable-pre/
:warning: Since we cannot revert the database back, it is a good idea to backup config and data folders first.

**Comment by EnragedN3wb** [comment]
Thanks for the link & the info on backing up settings! I had been looking around in my appdata & install directory for them.

I've upgraded to the 10.8 Beta, but unfortunately the problem persists. :(
![2022-03-28  {18;42;00} 1](https://user-images.githubusercontent.com/21209836/160499145-9bf695e9-62db-4a81-9a64-589d9a075ca8.jpg)

I'm not sure if these will help or not, but I pulled them from the Logs folder:
[log.txt](https://github.com/jellyfin/jellyfin-web/files/8366879/log.txt)
[FFmpeg.Transcode-2022-03-28_18-40-38_f46e1b1ab0cd073fe792cd163d4eb68c_26689f6b.log](https://github.com/jellyfin/jellyfin-web/files/8366880/FFmpeg.Transcode-2022-03-28_18-40-38_f46e1b1ab0cd073fe792cd163d4eb68c_26689f6b.log)

**Comment by dmitrylyzo** [comment]
There was conversation on Matrix about Roku: HEVC is not specified in the device profile.
Here is the PR: https://github.com/jellyfin/jellyfin-roku/pull/543

**Comment by EnragedN3wb** [comment]
ok, so if I'm understanding this correctly the issue is on the side of the Jellyfin app for Roku now, & not the server? Once that PR goes through & the app is updated it should work without me disabling video transcoding?

Sorry if I'm misunderstanding, how this stuff all works internally is something I'm still learning.

**Comment by whiteowl3** [comment]
> ok, so if I'm understanding this correctly the issue is on the side of the Jellyfin app for Roku now, & not the server? Once that PR goes through & the app is updated it should work without me disabling video transcoding?
> 
> Sorry if I'm misunderstanding, how this stuff all works internally is something I'm still learning.

if you are using 10.8 beta server, then yes.  That pull request will not be merged or versioned in as is, it lacks fundamental checks.  If you implement the changes from that pr (sideloading on the roku is easy as pie) and enable transcoding on the server beta, then everything should work on your roku except for graphical subtitles and HDR (if you have an HDR display, I think it will work, please let us all know).  HDR will become more intuitive eventually, graphical subtitles will never work, unless Roku incorporates support in the firmware.

**Comment by EnragedN3wb** [comment]
It's Alive! :D

Just finished testing it out(you were right, easy as pie) & it seems to be working perfectly. I'll do some more thorough testing tomorrow, since the user with the Roku TV was heading to bed as I did this last minute, I can confirm that the TV kicked into HDR mode & everything looked good at a glance.

Should I be worried about those fundamental checks it's lacking or will I be okay to continue using it this way?

**Comment by whiteowl3** [comment]
> It's Alive! :D
> 
> Just finished testing it out(you were right, easy as pie) & it seems to be working perfectly. I'll do some more thorough testing tomorrow, since the user with the Roku TV was heading to bed as I did this last minute. I can confirm that the TV kicked into HDR mode & everything looked good at a glance though.
> 
> Should I be worried about those fundamental checks it's lacking or will I be okay to continue using it this way?

the check it was lacking is "can this roku actually decode hevc" which has now been implemented in the pr. if its working you have nothing to worry about.
