### ISSUE TITLE
Songs in the wrong order if disc number is blank

### ISSUE THREAD

**Issue by TheNamelessWonderer** [jellyfin/jellyfin-web#3532]
**Describe The Bug**
If the Album is missing the disc number then tracks seem to be in any random order instead of in numerical order.

**Steps To Reproduce**

1. Open Jellyfin Web
2. Click on an album without a disc number
3. See error

**Expected Behavior**

The tracks should be in numerical order.

**Logs**

**Screenshots**

![image](https://user-images.githubusercontent.com/56267607/161083915-809a8617-179a-4463-b7de-df22e424ce43.png)
![image](https://user-images.githubusercontent.com/56267607/161084092-dea85339-ba63-493e-ad97-ab8b99274420.png)

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Firefox
 - Jellyfin Version: 10.8 Beta 1

**Additional Context**

This is not an issue on 10.7.7. They always show in numerical order regardless of disc number.

**Comment by thornbill** [comment]
Should be fixed by https://github.com/jellyfin/jellyfin/pull/7548 in the next beta release.
