### ISSUE TITLE
Double tap to fast forward or rewind

### ISSUE THREAD

**Issue by NickBolles** [jellyfin/jellyfin-web#355]
**Describe the feature you'd like**
When playing on an android device the player (VLC I think?) you can double tap to skip 30 seconds, and can continue to tap to increase the time. 

This would be really nice on the web client too. Specifically when chromecasting from a mobile device. In this case the fast forward and rewind buttons are disabled. So you have to use the slider to skip, which is nearly impossible to do for <1min. Although it looks like these might be on the `nowplaying` screen instead of the `playback` screen. The logic could probably be the same.

The rewind/fast forward buttons are hidden [here](https://github.com/jellyfin/jellyfin-web/blob/535f3dbbad204e30d5dbd549313c2025e7c055f3/src/css/nowplaying.css#L204-L211):
```
@media all and (max-width:34em) {

    .nowPlayingInfoButtons .btnNowPlayingFastForward,
    .nowPlayingInfoButtons .btnNowPlayingRewind,
    .nowPlayingInfoButtons .playlist .listItemMediaInfo {
        display: none !important
    }
}
```

**Additional context**
![image](https://user-images.githubusercontent.com/7891759/58764711-3ffd4c80-8530-11e9-9f46-5570a6a28f72.png)

note: this is Emby, but I'm pretty sure it's the same right now on jellyfin

**Comment by olskar** [comment]
This would be a nice feature, but I think it's 10 seconds?

**Comment by NickBolles** [comment]
@olskar probably, I'm not sure the details I'd need to test it. I actually think that the actual fast forward/rewind duration is configurable in the user profile.
