### ISSUE TITLE
Airplay2 functionality does not work unless a video is launched and full screened first (airplay renderers only appear on video controls).

### ISSUE THREAD

**Issue by gannon345** [jellyfin/jellyfin-web#3557]
**Describe The Bug**
Airplay2 functionality does not work unless a video is launched and full screened first (airplay renderers only appear on video controls).

**Steps To Reproduce**
1. Set up music library
2. Play music
3. Select cast button ("play on") at the top right
4. Note that only uPnP renderers appear, no Airplay renderers.

**Expected Behavior**
Airplay renderers should be available for "Play on" / casting option at the top right if source is a music file or audiobook format.

**Logs**
No log errors because it's a functionality that's just not there (but seemingly should be). I can pull logs if requested.

**Screenshots**

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Firefox, Chrome, Safari
 - Jellyfin Version: [e.g. 10.7.7 stable

**Comment by stamatovg** [comment]
https://github.com/jellyfin/jellyfin-web/pull/4480

**Comment by ItsMeRitch** [comment]
Similar issue here

**Comment by thornbill** [comment]
Support for AirPlay in the audio player was added in #4483

**Comment by ItsMeRitch** [comment]
> Support for AirPlay in the audio player was added in #4483

Hi @thornbill 

Apologies, maybe I'm just being stupid but how does one utilise this? 

I have a Jellyfin server and the Official Jellyfin app on iOS. Say I'm watching a movie and want to AirPlay it to my AppleTV, I can't seem to find a way to do this?
