### ISSUE TITLE
Discolored Video

### ISSUE THREAD

**Issue by dannymichel** [jellyfin/jellyfin-web#3578]
**Describe The Bug**
The same file played on jellyfin vs plex looks different. Discolored on jellyfin

**Steps To Reproduce**
Played on both plex and jellyfin direct play. Played both on plex and jellyfin transcoded down to 720p
Tried switching to bwdif deinterlacing method
Tried prefer fmp4-hls media container

**Expected Behavior**
Video to look the same on both

**Screenshots**
Plex
<img width="1254" alt="Screen Shot 2022-04-20 at 1 31 57 AM" src="https://user-images.githubusercontent.com/1161544/164157591-933264ed-a933-4c00-bf7f-016d09727f5f.png">
Jellyfin
<img width="1256" alt="Screen Shot 2022-04-20 at 1 31 39 AM" src="https://user-images.githubusercontent.com/1161544/164157607-9202f139-5a67-4201-ac01-9e6efa1ef801.png">
Media info
<img width="1248" alt="Screen Shot 2022-04-20 at 1 36 39 AM" src="https://user-images.githubusercontent.com/1161544/164157835-285db3ab-12f7-465a-a682-b399d9feed78.png">

**System (please complete the following information):**
 - Platform: Mac OS
 - Browser: Chrome
 - Jellyfin Version: 10.8

**Comment by Shadowghost** [comment]
The file is HDR so make sure you've enabled tone mapping.
The washed out colors is exactly what happens if you try to play a HDR movie on a SDR display.
