### ISSUE TITLE
Rewind and Fast Forward should be Left/Right Arrow

### ISSUE THREAD

**Issue by olskar** [jellyfin/jellyfin-web#358]
It would be nice and stringent if Jellyfin could use the same keyboard shortcuts as people already are familliar with from youtube, netflix etc.

That is Rewind and Fast Forward = Left/Right Arrow

**Comment by DrPandemic** [comment]
Currently for the video player `Left/Right` `jkl` (youtube style) `f` for fullscreen and `m` for mute are already present.

AFAIK, we don't have those shortcut for other medias like music.

**Comment by olskar** [comment]
@DrPandemic Do you mean it should be possible to use jkl when playing a video in jellyfin-web? It does not work for me, perhaps I should file a separate report for that..

**Comment by DrPandemic** [comment]
Something interesting was pointed on matrix today. Are you building yourself or using official builds? Official builds don't have those `jkl` bindings. They'll be in 10.4.0

**Comment by olskar** [comment]
I build from latest Source

**Comment by DrPandemic** [comment]
I'm really unsure what's the issue then. To debug it I would try : 
- Is there any logs in the developer console? (https://developers.google.com/web/tools/chrome-devtools/)
- Did you try with multiple browser? Chrome, Firefox and Edge?
- Did you try in incognito mode?
- If all of the above didn't work and you know how to use the javascript debugger : add a breakpoint on https://github.com/jellyfin/jellyfin-web/blob/master/src/controllers/videoosd.js#L1059, is the function being called when you try to use keyboard shortcuts?

**Comment by anthonylavado** [comment]
If you’re building from source, it may be possible that the -web submodule has to be updated. We typically do this when we create a release, which uses our provided build scripts.

Moving to close in 24h though
