### ISSUE TITLE
Manual Login option still appears if all users are hidden

### ISSUE THREAD

**Issue by RazeLighter777** [jellyfin/jellyfin-web#359]
**Describe the bug**
On the login screen, even if all users are marked as hidden, then there is still a useless option to manually login.

**To Reproduce**
1. Set all accounts to hidden
2. Log out.
3. Observe the useless manual login button

**Expected behavior**
Because manual login is the only option in this scenario, the button is useless and should be hidden in this case

**Logs**

**Screenshots**
![image](https://user-images.githubusercontent.com/25808399/59196631-c92a0a00-8b54-11e9-8d0b-a6fab0247a5f.png)

System (please complete the following information):**
 - OS: Docker
 - Browser: Firefox
 - Jellyfin Version: jellyfin:latest

**Comment by ckcr4lyf** [comment]
Can we close this issue?
