### ISSUE TITLE
No 'Date Episode Added' sort option in TV Shows

### ISSUE THREAD

**Issue by Deathspike** [jellyfin/jellyfin-web#3590]
**Describe The Bug**
It is not possible to sort TV shows by 'Last Episode Added' date, even though Jellyfin server supports it. This makes it practically impossible to find TV Shows with newly added seasons/episodes in a sizeable collection. As an example, I added a 2022-released season to a 2013-series, but I could not find it without scrolling down through 9 years of TV Shows. This is because Date Added uses the date the series was added, not the season or episode, and Release Date similarly uses the date the show first aired. Another product, Plex, has 'Last Episode Added' for this exact purpose.

**Steps To Reproduce**
1. Add a season to an old TV Show.
2. Use any of the existing sort options.
3. Notice the TV Show will never be at the top.

**Expected Behavior**
See description.

**System (please complete the following information):**
 - Platform: All
 - Browser: All
 - Jellyfin Version: 10.8.0-beta2

**Comment by admullis** [comment]
I'd like to see this feature also, for the same reason as Deathspike.

I came to Jellyfin a couple of weeks ago from Plex. I miss the most recently added episode feature that Plex has.

**Comment by FiskFIsk33** [comment]
This is not completed at all, the top comment still accurately describes the current situation.

**Comment by michaelkrieger** [comment]
> This is not completed at all, the top comment still accurately describes the current situation.

Even with #3591 when combined with this for added clarity?

**Comment by FiskFIsk33** [comment]
As of right now you can sort shows by when they were first added, there exists no option to sort by last episode added
![image](https://user-images.githubusercontent.com/9091924/222735313-e4b91fd3-2311-49cb-849d-e2f025a61fbb.JPG)

**Comment by thornbill** [comment]
@FiskFIsk33 Are you running unstable? This feature has not made it to a stable release yet.

**Comment by FiskFIsk33** [comment]
I'm so sorry, my bad

**Comment by thornbill** [comment]
Feature releases coincide with minor version bumps so 10.9.0 at a minimum.

**Comment by D33M0N** [comment]
it seems to be in the sorting options list in in Jellyfin 10.10.3, but it just doesn't work.
