### ISSUE TITLE
EmbyInput createdCallback returns early if the element has "emby-input" class, even if the rest hasn't been initialized.

### ISSUE THREAD

**Issue by matthewstrasiotto** [jellyfin/jellyfin-web#3592]
I had been constructing my emby inputs like so:

```html
<div class="inputContainer">
    <label class="inputLabel inputLabelUnfocused" for="DefaultProvider">Set default Provider:</label>
    <input  is="emby-input" id="DefaultProvider" label="Set default Provider:" type="text"  class="emby-input" />
    <div class="fieldDescription">
       Bla Bla Bla
    </div>
</div>
```

And have been getting the following error

```
Uncaught TypeError: Cannot set properties of undefined (setting 'innerText')
    at HTMLInputElement.__webpack_modules__../elements/emby-input/emby-input.js.EmbyInputPrototype.label (emby-input.js:117:9)
    at eval (eval at __webpack_modules__../elements/emby-input/emby-input.js.EmbyInputPrototype.attachedCallback (main.jellyfin.bundle.js?2d08f1f0ebb475601456:1:1), <anonymous>:1:6)
    at HTMLInputElement.__webpack_modules__../elements/emby-input/emby-input.js.EmbyInputPrototype.attachedCallback (emby-input.js:112:14)
    at _attached (webcomponents-lite.js:2025:1)
    at Object.attached (webcomponents-lite.js:2018:1)
    at upgradeWithDefinition (webcomponents-lite.js:2187:1)
    at Object.upgrade (webcomponents-lite.js:2173:1)
    at added (webcomponents-lite.js:1978:1)
    at webcomponents-lite.js:1987:1
    at webcomponents-lite.js:1919:1
```

Upon review of the source, it's being thrown by this callback:

https://github.com/jellyfin/jellyfin-web/blob/81e240d50dfeda096d7f8b5fc44311ec6d8625fc/src/elements/emby-input/emby-input.js#L111-L114

Essentially, the EmbyInput object is trying to access it's `labelFor` attribute, but the attribute has not been initialized.

Upon investigating the reason for this, it appears that the `createdCallback()` handler is exiting early if the element has a `emby-input` class.

https://github.com/jellyfin/jellyfin-web/blob/81e240d50dfeda096d7f8b5fc44311ec6d8625fc/src/elements/emby-input/emby-input.js#L39-L41

This prevents execution of the initialization code that creates the `labelFor` attribute for the object.

**Comment by matthewstrasiotto** [comment]
For now, I imagine the workaround will be to remove the `class="emby-input"` assignment from the markup, but this behaviour seems like a bug.

**Comment by dmitrylyzo** [comment]
`EmbyInput` creates the label itself - just add the `label` attribute:
https://github.com/jellyfin/jellyfin-web/blob/3ab6d026ae30e45e1ec71fb7cd97eaa97538f502/src/components/displaySettings/displaySettings.template.html#L225

**Comment by matthewstrasiotto** [comment]
> `EmbyInput` creates the label itself - just add the `label` attribute:
> 
> https://github.com/jellyfin/jellyfin-web/blob/3ab6d026ae30e45e1ec71fb7cd97eaa97538f502/src/components/displaySettings/displaySettings.template.html#L225

Yeah, that's not the issue, the issue is that having the emby-input css class on your emby-input element means that the emby-input element doesn't get initialized correctly

**Comment by thornbill** [comment]
Yes that seems to be by design. The component uses the class to indicate the component had already been initialized. You should remove the class and let the component add it.
