### ISSUE TITLE
Opening 10.8.0-beta2 on chrome on Android doesn't go beyond the logo

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin-web#3595]
**Describe The Bug**
When I try to open JF in chrome on android I don't get any further than the logo/splash-screen.

On chrome on Linux, it all works fine.

**System (please complete the following information):**
 - Platform: Android 11
 - Browser: Chrome (latest, up-to-date)
 - Jellyfin Version: 10.8.0-beta2

**Additional Context**
Surely this needs more information but I don't know what else to gather on a chrome/android platform.  On a desktop platform I'd normally enable devtools in chrome and see what's happening.

**Comment by thornbill** [comment]
Have you tried clearing your cache or using a private/incognito tab?

**Comment by brianjmurrell** [comment]
It does work in an incognito window.  But how can one clear the cache/cookies/etc for a single site on Chrome on Android?  It doesn't have the same settings as Chrome on desktop.
