### ISSUE TITLE
"Use episode image" checkbox disappeared after refreshing all libraries metadata

### ISSUE THREAD

**Issue by Brewsk11** [jellyfin/jellyfin-web#3608]
**Describe The Bug**
I decided to batch-refresh all libraries (movies, tv, collections) metadata to change language from English to Polish. After that the next up and continue watching sections no longer showed episode images, instead it's showing images for the series.
Going into display options in settings the button is no longer there (last checkbox is show missing episodes):

![image](https://user-images.githubusercontent.com/26325340/166107452-b8ee6dce-d026-4d98-af16-649ace087677.png)

DOM is missing:
```html
...
<div class="checkboxContainer checkboxContainer-withDescription fldDisplayMissingEpisodes">
	<label class="emby-checkbox-label">
		<input type="checkbox" is="emby-checkbox" class="chkDisplayMissingEpisodes emby-checkbox" data-embycheckbox="true">
		<span class="checkboxLabel">Wyświetlaj w sezonach brakujące odcinki</span>
		<span class="checkboxOutline">
			<span class="material-icons checkboxIcon checkboxIcon-checked check"></span>
			<span class="material-icons checkboxIcon checkboxIcon-unchecked "></span>
		</span>
	</label>
	<div class="fieldDescription checkboxFieldDescription">Ta opcja musi zostać dodatkowo aktywowana w bibliotece seriali, w konfiguracji serwera.</div>
</div>

<button is="emby-button" type="submit" class="raised button-submit block btnSave emby-button">
	<span>Zapisz</span>
</button>
...
```

This functionality was added in #2599

**Steps To Reproduce**
Not sure, I don't really have a way to setup a mock env right now, but try:
1. setup jellyfin, libraries etc. all to English, Poland, display language Polish (not sure if relevant, but this was my config),
1. import some TV show,
1. download episode metadata with images,
1. start watching an episode and exit so it shows in continue watching,
1. in library's settings change metadata config to Polish, Poland,
1. in metadata manager select the library - 3 dots - refresh metadata - replace all metadata, check replace images and save,
1. the continue watching should now show series images and the checkbox in settings - display should be gone

**Expected Behavior**
If that's expected behavior, I would like to see a message somewhere around where the button was why it's now unavailable.

**Logs**
I guess backend log won't help, not sure how to get web logs.

**Screenshots**
Inlined.

**System (please complete the following information):**
 - Platform: Ubuntu Server 20.04
 - Browser: Problem happens in both web-ui (Brave) as well as Android client.
 - Jellyfin Version: 10.7.7

**Comment by Deagan** [comment]
I cannot find this setting on my install either, was there a way to activate it manually in the meantime?

**Comment by Brewsk11** [comment]
I've not found any workaround yet

**Comment by dmitrylyzo** [comment]
This is a 10.8 feature.
