### ISSUE TITLE
[Issue]: Playback Quality setting bitrate to start from the file bitrate instead of 60 Mbps

### ISSUE THREAD

**Issue by CarbonV** [jellyfin/jellyfin-web#3669]
### Please describe your bug

Currently the playback quality displays 60 Mbps as the Max bitrate, it would be nice if it could display the actual file bitrate as the max bitrate with the options going down starting from the max bitrate.
![bitrate3](https://user-images.githubusercontent.com/30235712/169818603-11a10f64-c4db-4ff1-b0a6-0caecf09698e.jpg) ![bitrate2](https://user-images.githubusercontent.com/30235712/169818609-703d40f4-74c4-4d57-934d-f3719e137f07.jpg)![bitrate1](https://user-images.githubusercontent.com/30235712/169818608-29960b1c-feff-47a6-b18c-efac822f05ae.jpg) 

Not 100% sure if this would be a feature or is an Issue but it currently creates a lot of confusion for my users if they are playing direct or not and at what bitrate they are currently playing.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Ubuntu
- Virtualization: /
- Clients: Browser and Android
- Browser: Brave
- Playback Method: Direct Play
- Hardware Acceleration: VAAPI
- Reverse Proxy: Synology
- Storage: Local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CarbonV** [comment]
Just as a little add to this, it would maybe be even nicer to see the current transcode or DirectPlay for audio and video displayed somewhere in the gear icon. The same way that the Playback Reporting plugin reports it.

Example:
![image](https://user-images.githubusercontent.com/30235712/174531475-1852ba6f-3ef0-4bf9-a0aa-8c083ac00723.png)

**Comment by dmitrylyzo** [comment]
> https://github.com/jellyfin/jellyfin-web/issues/3708#issuecomment-1156082697
> This list is more like "Max acceptable bitrate" (at least, this is how it currently works).

In addition, this bitrate is also applied to the next items.

**Comment by CarbonV** [comment]
> 

Completely missed the Playback Info, my bad! I think I understand the max acceptable bitrate, maybe just showing what bitrate is currently being used right now, for example next to auto would add some more intuitiveness.

e.i.: Auto (7Mbps) <- in this example.

Don't know how much work that would be.
