### ISSUE TITLE
[Issue]: Identify not showing up on dropdown menu

### ISSUE THREAD

**Issue by lazydorkk** [jellyfin/jellyfin-web#3672]
### Please describe your bug

Trying to do some manual updating of the metadata as the AniDB plugin seems to have some issues identifying my series automatically from the folder titles. However, the identify option is not available. For ones that it seems to have identified some info, it pops up, but on others it doesn't. I've attached a screen shot of what happens when there's no Identify option and when there is.

Steps to reproduce:
1. In Jellyfin GUI, navigate to "(Folder)" in My Media
2. Right click on folder
3. Identify option not available
![Capture](https://user-images.githubusercontent.com/48865006/170810530-f1f61a75-7b6b-4771-bf5a-1a90a2f119a7.JPG)
![Capture2](https://user-images.githubusercontent.com/48865006/170810531-807c6de2-cdd4-45fc-ad76-538f50eff7f6.JPG)

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Windows
- Virtualization: N/A
- Clients: Brower
- Browser: Brave 1.39.111 Chromium 102.0.5005.61
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins: AniDB
- Reverse Proxy: none
- Base URL: none
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
What exactly are you trying to identity?

**Comment by lazydorkk** [comment]
I am trying to identify the folder as a specific show. Jellyfin has organized everything into the initial subfolder (i.e. Anime -> Death Note), but some subfolders have been identified as shows and the metadata has been pulled by the plugins I have installed, but other subfolders are just identified as folders with media.

Some of the folders I can choose "Identify" in the right click menu to manual associate with metadata, but others I can't. The ones I can't are the ones I'm trying to identify as a specific show in order to pull the metadata. I've attached what the identify menu looks like once I click it.
![Capture3](https://user-images.githubusercontent.com/48865006/170832042-18fcf069-6dbc-4e47-aa9a-af0aea3740a2.JPG)

**Comment by Keewks** [comment]
Hi,
I have always the same problem.
The identify option is not available for some folders.
Thanks

**Comment by EllienoreB** [comment]
Up? I'm also having this issue.

**Comment by BitHappy** [comment]
I also am having this issue. It randomly recognizes some of the shows, and for those the "Identify" button is there, but then for the others it doesn't even give me to option to identify it at all. It just treats it like a folder.
