### ISSUE TITLE
[UI behavior] [Initial Setup Sequence]: During initial wizard setup, use of "<- Previous" on third screen ("Setup your media libraries") causes the first Password field to be corrupted

### ISSUE THREAD

**Issue by jrvmedic** [jellyfin/jellyfin-web#3679]
[UI behavior] [Initial Setup Sequence]: Immediately after install, during initial wizard setup, the use of "<- Previous" on third screen ("Setup your media libraries") causes the first Password field to be corrupted.

This was found while testing unstable/jellyfin-web-20220526.2-1.el7.noarch.rpm The "misbehavior" probably happens on other builds; but I did not test anything except today's server and web builds when I discovered this problem.

This happens from several client operating systems and several browsers, but with all against the same version of the server (unstable/jellyfin-server-20220526.4-1.el7.x86_64.rpm), so I believe those information are not relevant.

If someone needs other versions to be specifically tested, then please let me know and I will endeavor to test them.

After initial setup of Server/Web client, the first use of "localhost:8096" takes you through a sequence of setup screens.
First screen is desired language. Second screen is setting administrative account password. Third screen is "Setup your media libraries". If on the third screen, you don't set up a library, but immediately click the "<- Previous" button, you get taken back to the second screen; however, the first password entry box fills with dots (implying the field has many characters entered into it).

![image](https://user-images.githubusercontent.com/31710230/171068610-a89fb2c7-134c-4102-b3ec-0f1ad0917273.png)

I don't know what the "correct behavior" should be here, but I feel that "corruption" of the first field, and the second password field is left with the prior, use-entered value is NOT polite behavior.

![image](https://user-images.githubusercontent.com/31710230/171068632-df7f0879-abd0-412b-9230-143485f3e495.png)

![image](https://user-images.githubusercontent.com/31710230/171068644-ee5ab732-8697-4fa0-b653-85b78e0b411c.png)

I think the best behavior of the use of the "<- Previous" button, would be to leave the previously entered values in both of the password fields exactly what they were when clicking "Next ->" on the second screen. As it now stands, on my system, the first password entry field has a terribly long entry that must be manually deleted for every character. The second password entry field is left uncorrupted, and has the expected value in it - which i can verify by NOT modifying the second password field, but deleting and then re-entering the first password field, and only then pressing the "Next ->" button.

The next best behavior, would probably be to "clear-to-empty" both the previously entered values - but the user may be annoyed at us for forcing them to re-enter the password; especially if it is a really long and complicated password (as mine usually are - even on test systems).
Jellyfin Version

10.8.0
if other:

jellyfin-web-20220526.2-1.el7.noarch.rpm

**Comment by Will-P77** [comment]
I can still reproduce this issue on the current release.

Environment:
- Platform: macOS
- Architecture: Apple Silicon
- Browser: Safari
- Jellyfin Server: [your version]
- Jellyfin Web: [your version]
- Installation: Fresh install

Steps to reproduce:
1. Start a fresh Jellyfin installation.
2. Open the initial setup wizard.
3. Enter an administrator username and password.
4. Click "Next".
5. On the next setup page, click "Previous".
6. Observe the password fields.

Actual result:
The first password field is unexpectedly replaced with a much longer
password value, while the confirmation field retains the original value.

Clicking "Next" then results in:
"Password and confirmation password must match."

Expected result:
When navigating back to the previous step, both password fields should
either retain the original matching values or both be cleared.

Reproducibility:
Reproduced consistently.

I have attached screenshots showing the state before and after navigating back.

<img width="1015" height="590" alt="Image" src="https://github.com/user-attachments/assets/a538b86c-c80c-4eae-884a-188d6bf6bbe1" />
<img width="1502" height="874" alt="Image" src="https://github.com/user-attachments/assets/8cbe0717-8e95-4cab-ba73-a1c30129825e" />
