### ISSUE TITLE
AAC 2.0 transcoded to mp3 for chrome 74 on iPad

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin-web#368]
**Describe the bug**

AAC audio is transcoded to mp3 on chrome 74 on iPad. I'm very surprised this isn't direct played. The same file is direct played on chrome 74 on windows.

**Expected behavior**
h264/AAC/MKV should be direct played in chrome 74 on iPad.

**Logs**

```
/usr/bin/ffmpeg -ss 00:03:24.000 -fflags +genpts -noaccurate_seek -f matroska,webm -i file:/media/Videos/New/No Trakt/The Daily Show/The Daily Show 24x113 - 2019-06-06 James Corden [WEBDL-720p][AAC 2.0][x264]-TBS.mkv -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -copyts -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 192000 -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 6 -segment_time_delta -204 -individual_header_trailer 0 -break_non_keyframes 1 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 34 -segment_list /config/transcoding-temp/c87476c181804f6315f6342362ebd9b5.m3u8 -y /config/transcoding-temp/c87476c181804f6315f6342362ebd9b5%d.ts
```

**Screenshots**

![Untitled](https://user-images.githubusercontent.com/991618/59122656-eaa2b000-8920-11e9-9217-d1f6ae00e1b3.png)

**System (please complete the following information):**
 - OS: Docker
 - Browser:Chrome 74
 - Jellyfin Version: [e.g. 10.3.4]

**Comment by anthonylavado** [comment]
shoo bot

**Comment by Artiume** [comment]
Can we rename the title to include all browsers? It happens on any device or OS using a browser.

**Comment by JustAMan** [comment]
I don't think so, as original submitter specified in the issue that it works for them using Chrome on Windows...

**Comment by Artiume** [comment]
Yeah, maybe I was looking at AC3 or something, AAC HE-AAC and AAC LC are playing fine in Chrome/FF.

**Comment by Artiume** [comment]
Shoo bot

**Comment by MrTimscampi** [comment]
@SenorSmartyPants Is this still an issue on 10.5.5?

**Comment by MrTimscampi** [comment]
> I don't think so, as original submitter specified in the issue that it works for them using Chrome on Windows...

It might be good to note that, afaik, Chrome for iOS is essentially Safari, unless things changed recently.

**Comment by SenorSmartyPants** [comment]
> @SenorSmartyPants Is this still an issue on 10.5.5?

Yes. Tested with two different MKVs with h264 level 40 (i think that's supposed to be 4.0) and AAC audio. 

And yes, JF reports the client as Safari iPad when I'm using chrome on the iPad.

**Comment by michaelkrieger** [comment]
I’m seeing files with MP3 audio (see screenshot from my library) play completely silent on an iPad/iPhone (iOS) in the Jellyfin app (see screenshot).  They do show the 2CH audio in the player, but no audio comes out.

![B23AF0D8-E6F4-4BCA-8F1A-51D28C7D2467](https://user-images.githubusercontent.com/7321259/85967939-9fc36280-b991-11ea-9db6-ac631e5ede50.jpeg)
![CF40D662-8ED2-40FA-AA5E-1827F492C806](https://user-images.githubusercontent.com/7321259/85967940-a05bf900-b991-11ea-99cc-3c15ef738bb6.jpeg)

**Comment by brianjmurrell** [comment]
Will this fix:

```
Input #0, matroska,webm, from 'file:/video.mkv':
  Metadata:
    encoder         : libebml v1.3.6 + libmatroska v1.4.9
    creation_time   : 2020-06-21T05:05:45.000000Z
  Duration: 00:42:18.00, start: 0.000000, bitrate: 3345 kb/s
    Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 1k tbn, 50 tbc (default)
    Metadata:
      BPS-eng         : 3183695
      DURATION-eng    : 00:42:17.200000000
      NUMBER_OF_FRAMES-eng: 63429
      NUMBER_OF_BYTES-eng: 1009709113
      _STATISTICS_WRITING_APP-eng: mkvmerge v29.0.0 ('Like It Or Not') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-06-21 05:05:45
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(eng): Audio: aac (LC), 48000 Hz, stereo, fltp (default)
    Metadata:
      BPS-eng         : 160000
      DURATION-eng    : 00:42:17.216000000
      NUMBER_OF_FRAMES-eng: 118932
      NUMBER_OF_BYTES-eng: 50744441
      _STATISTICS_WRITING_APP-eng: mkvmerge v29.0.0 ('Like It Or Not') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-06-21 05:05:45
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(dan): Subtitle: subrip
    Metadata:
      BPS-eng         : 76
      DURATION-eng    : 00:42:18.000000000
      NUMBER_OF_FRAMES-eng: 561
      NUMBER_OF_BYTES-eng: 24207
      _STATISTICS_WRITING_APP-eng: mkvmerge v29.0.0 ('Like It Or Not') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-06-21 05:05:45
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (aac (native) -> mp3 (libmp3lame))
```

playing to a Chromcast, which supports AAC directly?

**Comment by Artiume** [comment]
hopefully

**Comment by brianjmurrell** [comment]
Hrm.  Strange.  This one is not being transcoded:

```
Input #0, matroska,webm, from '/video2.mkv':
  Metadata:
    ENCODER         : Lavf57.83.100
  Duration: 00:41:22.03, start: 0.000000, bitrate: 3351 kb/s
    Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 1k tbn, 50 tbc (default)
    Metadata:
      BPS-eng         : 3187081
      DURATION-eng    : 00:41:22.000000000
      NUMBER_OF_FRAMES-eng: 62050
      NUMBER_OF_BYTES-eng: 988792064
      _STATISTICS_WRITING_APP-eng: mkvmerge v46.0.0 ('No Deeper Escape') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-06-08 22:00:51
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      DURATION        : 00:41:22.000000000
    Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp (default)
    Metadata:
      BPS-eng         : 160000
      DURATION-eng    : 00:41:22.026000000
      NUMBER_OF_FRAMES-eng: 116345
      NUMBER_OF_BYTES-eng: 49640534
      _STATISTICS_WRITING_APP-eng: mkvmerge v46.0.0 ('No Deeper Escape') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-06-08 22:00:51
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      DURATION        : 00:41:22.026000000
```

As near as I can tell, anyway.  There is no ffmpeg running and nothing in `/var/lib/jellyfin/transcodes` while this is being watched.

_Stats for nerds_ on Chromecast would be ultimately useful, although I'm not sure how achievable.

But really, why would the previous file be transcoded when the above one is not?

**Comment by brianjmurrell** [comment]
Any thoughts on the above?
