### ISSUE TITLE
Ends at does not account for playback speed

### ISSUE THREAD

**Issue by PythonCoderAS** [jellyfin/jellyfin-web#3682]
**Describe The Bug**

When setting the playback speed to a different number than 1x (such as 2x), I noticed that the "Ends at" time on the bottom does not update accordingly. As I play the video, the time keeps on decreasing to match the projected time end as if the video was being played at 1x speed.

**Steps To Reproduce**

1. Start a video
2. Change playback speed to 2x

**Expected Behavior**
The time to be accurate.

**Logs**
N/A

**Screenshots**
N/A

**System (please complete the following information):**
 - Platform: [e.g. Linux, Windows, iPhone, Tizen] MacOS
 - Browser: [e.g. Firefox, Chrome, Safari] Chrome
 - Jellyfin Version: [e.g. 10.6.0] 10.7.7

**Additional Context**
 The problem is also reproducible on the jellyfin media player app.

**Comment by dmitrylyzo** [comment]
I think this is fixed in 10.8 by #2778

**Comment by PythonCoderAS** [comment]
> I think this is fixed in 10.8 by #2778

This PR was made about 10 months ago. I am surprised it's not in the latest stable release yet.
