### ISSUE TITLE
Safari can't render ASS subtitles

### ISSUE THREAD

**Issue by niklaskorz** [jellyfin/jellyfin-web#3687]
**Describe The Bug**

When selecting a subtitle track with ASS format in Safari, no subtitles are rendered.

**Steps To Reproduce**

1. Play a video
2. Select a subtitle track with ASS format
3. Nothing happens

**Expected Behavior**
The subtitles should be rendered.

**Logs**
```
[Log] warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available. (subtitles-octopus-worker.js, line 1524, column 84)
[Log] libass: setting total libass memory limits to: glyph=40 MiB, bitmap cache=40 MiB (subtitles-octopus-worker.js, line 182)
```

**Screenshots**
<img width="634" alt="grafik" src="https://user-images.githubusercontent.com/590517/172359017-7dd5a0ef-7336-4258-a7d6-a6905bd5967e.png">

**System (please complete the following information):**
 - Platform: macOS 12.4
 - Browser: Safari 15.5 (17613.2.7.1.8)
 - Jellyfin Version: Jellyfin Web 10.7.6

**Additional Context**
The reported warning "Browser does not support creating object URLs" should not occur.
The according lines in `subtitles-octopus-worker.js` are:

```js
            Browser.URLObject = "undefined" != typeof window ? window.URL ? window.URL : window.webkitURL : void 0,
            Module.noImageDecoding || void 0 !== Browser.URLObject || (console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."), Module.noImageDecoding = !0);
```

Both `window.URL` and `window.webkitURL` are defined in Safari 15.5, thus making me wonder how this warning is even reached.

**Comment by dmitrylyzo** [comment]
> Both `window.URL` and `window.webkitURL` are defined in Safari 15.5, thus making me wonder how this warning is even reached.

`window` isn't defined in the worker environment. This warning comes from Emscripten and doesn't affect SSA rendering.

`oneshot already reached end-of-events` indicates that JSO has finished rendering all subtitle events.
The only way to get more info is to add `,debug:1` next to `renderAhead:90` in the `htmlVideoPlayer-plugin.*.js` file.

**Comment by dmitrylyzo** [comment]
`oneshot received (start=2007.9743909906488, empty=-1), render: 0 ms` means `event starts from ~00:33:27.97 and never ends (end-of-events)`.
I guess it couldn't parse the subtitles.

Can I get the subtitle file?

**Comment by niklaskorz** [comment]
There you go: https://send.vis.ee/download/dff0e2d48692fc56/#hgRLbtjBgYQEz9AhI4eVrA

**Comment by niklaskorz** [comment]
For what it's worth, this file works just fine in the Jellyfin Electron app.

**Comment by dmitrylyzo** [comment]
There is some non-printable character on line 12. I removed it, and they started working.

**Comment by niklaskorz** [comment]
Interesting, thanks! Should unprintable characters be ignored by the subtitle renderer?

**Comment by niklaskorz** [comment]
I see, thanks! I'll close this issue then.
