### ISSUE TITLE
Remote access control checkbox not visible in edit user page

### ISSUE THREAD

**Issue by algirdasN** [jellyfin/jellyfin-web#3697]
**Describe The Bug**
On the edit user page, the remote access control checkbox remains hidden even if remote access is enabled on the server. Debugging shows that the property, that controls whether this checkbox is un-hidden (EnableRemoteAccess), is undefined. It seems that this property was removed from ServerConfiguration thus breaking this functionality (https://github.com/jellyfin/jellyfin/commit/69df004b9f62cb65986607d659fde0dcc74004ab#diff-c1f87f62ea1d5291e0845030039c65395f16744a78716712abd7c9f281f0ae60L232-L236)

**Steps To Reproduce**
1. Enable remote access on the server
2. Navigate to edit page for any user
3. Attempt to locate remote access control checkbox under the user name

**Expected Behavior**
Remote access control checkbox should be displayed when remote access is enabled on the server.

**Screenshots**
![image](https://user-images.githubusercontent.com/61432976/173256597-ef88a731-d43e-4a73-8947-c3e8bd54d182.png)

![image](https://user-images.githubusercontent.com/61432976/173256303-bee1bd7c-8596-4dfc-813f-8f4d7fe8bc16.png)

**System (please complete the following information):**
 - Platform: Windows 10
 - Browser: Firefox 101.0
 - Jellyfin Version: 10.8.0

**Comment by thornbill** [comment]
This has been fixed.
