### ISSUE TITLE
UI freezes on Firefox on Jellyfin 10.8 while playing a video when accessed remotely

### ISSUE THREAD

**Issue by methatronc** [jellyfin/jellyfin-web#3705]
Hello,

When using firefox to access jellyfin 10.8, if the following procedure is followed, the interface freezes :
- launch a video ( fullscreen or not, doesn't matter )
- while the interface does not freeze; do
  - access the settings via the cog
  - enter any of the menu
  - exit the settings
- done:  the interface freezes ( the video keeps playing but the menu is unresponsive )

It can take two to four loops, but eventually, the UI will freeze.
It happens both on linux clients and windows clients, no error ( only 200-204 requests are served ).
It does not happen on local access, only when accessing through a reverse proxy ( nginx and nginx proxy manager in my case ).
It does not happen on chromium browsers ( brave and edge in my case ).

Thanks in advance for your help

**Comment by CommandStorm5** [comment]
I can confirm that the issue does occur in Chromium-based browsers. (managed to replicate it in Chrome and Edge)
Opening any menu item and clicking off it a few times reliably bricks it after several repetitions.
Jellyfin: 10.8.0
OS: Ubuntu 22.04
Chrome: 102.0.5005.115
Edge: 102.0.1245.41

**Comment by methatronc** [comment]
> I can confirm that the issue does occur in Chromium-based browsers. (managed to replicate it in Chrome and Edge) Opening any menu item and clicking off it a few times reliably bricks it after several repetitions. Jellyfin: 10.8.0 OS: Ubuntu 22.04 Chrome: 102.0.5005.115 Edge: 102.0.1245.41

My bad, when I tried it on Edge it didn't freeze, must have not tried enough.

**Comment by CommandStorm5** [comment]
Also noticed that when the freeze occurs, the URL does not reflect the current menu opening. For example with the SyncPlay menu on the home screen:

Home screen: `https://jellyfin.example.net/web/index.html#!/home.html`
Normally open menu: `https://jellyfin.example.net/web/index.html#!/dialog?dlg=<13-digit-number>`
Menu closed: `https://jellyfin.example.net/web/index.html#%21%2Fhome.html=`
Repeat a few times
Bricked menu open: `https://jellyfin.example.net/web/index.html#%21%2Fhome.html=`

Same thing applies to playback mode, UI is bricked when URL doesn't reflect the currently open menu.

Curiously enough, the Cast menu does NOT change the URL when open and i am unable to get the UI to brick by opening that one.

**Comment by dmitrylyzo** [comment]
Could it be ClearURL extension again? https://github.com/jellyfin/jellyfin-web/issues/3572#issuecomment-1122858096

**Comment by CommandStorm5** [comment]
Why yes, yes it is. Unable to replicate problem after disabling said extension.

**Comment by methatronc** [comment]
Indeed it does the trick ! Thanks for your insight, I'll have to find a good alternative to ClearURLs now.. 
Have a good day y'all :)
