### ISSUE TITLE
{\an8}  tag support for srt files

### ISSUE THREAD

**Issue by Dnkhatri** [jellyfin/jellyfin-web#3727]
Although {\an8}  not in srt specifications but it has been adopted by most video players and works with them. Even if positioning support is not added atleast the {\an8}  tag should be hidden though in my opinion {\an8} tags have sort of become part of the spec due to adoption by most of the major video players like vlc, mpv, mpc etc.

**Comment by J-C-P** [comment]
I agree
That would be very nice to have it supported or, at least, hidden.
:-)

**Comment by Marce1ek** [comment]
+1

**Comment by Dnkhatri** [comment]
This is still a problem

**Comment by HelXaphod** [comment]
Have been editing srt files to remove {\an8} while saving the originals for that golden day in the future when Jellyfin can use them.  Sill an issue, now, though.

**Comment by nielsvanvelzen** [comment]
From my understanding those are SSA tags, not SRT. So it's not weird that we don't support them. If someone can link some resources that claim these tags are in fact supposed to work in SRT please let us know.

**Comment by thornbill** [comment]
I'm fairly certain we aren't doing anything special for srt rendering so it would be a matter of browser support not jellyfin-web specifically.

**Comment by HelXaphod** [comment]
> From my understanding those are SSA tags, not SRT. So it's not weird that we don't support them. If someone can link some resources that claim these tags are in fact supposed to work in SRT please let us know.

This is representative of what I have been seeing while researching this issue - [moving subtitle text up in *.srt file format](https://superuser.com/questions/642265/moving-subtitle-text-up-in-srt-file-format)

It seems this is an ad-hoc SSA to SRT function support by several players, so far.  That's probably why I keep seeing the tags in SRT files (and have to remove them).

**Comment by AnonymousWebHacker** [comment]
[\an8](https://github.com/jellyfin/jellyfin-androidtv/issues/1804)

**Comment by liimee** [comment]
any updates here? it would be nice if the tags were at least hidden just like on [android tv](https://github.com/jellyfin/jellyfin-androidtv/issues/1804#issuecomment-1537129997).

**Comment by GabrielOsvair** [comment]
"{\an8}" appears in front of my subtitles, is this normal? Can I fix it?

**Comment by fernvenue** [comment]
Still see the tag in subtitles.

**Comment by thornbill** [comment]
> Although {\an8} not in srt specifications

The real solution here would be to _not_ have invalid subtitle files. These style tags are specific to ass/ssa and not supported by srt. Some players support them just because they send all subtitles through the same rendering logic. This is not the case for web browsers and relying on specific implementations of different players to support features not included in the format specification is unwise. 

However as indicated in the linked pull request, jellyfin-web will remove the tags starting in 10.9.0.

**Comment by GabrielOsvair** [comment]
> > Although {\an8} not in srt specifications
> 
> The real solution here would be to _not_ have invalid subtitle files. These style tags are specific to ass/ssa and not supported by srt. Some players support them just because they send all subtitles through the same rendering logic. This is not the case for web browsers and relying on specific implementations of different players to support features not included in the format specification is unwise.
> 
> However as indicated in the linked pull request, jellyfin-web will remove the tags starting in 10.9.0.

Any predictions for the release of v10.9?

**Comment by fernvenue** [comment]
That would be great if we can have this before 10.9 release.
