### ISSUE TITLE
Login disclaimer not showing on 10.8.1

### ISSUE THREAD

**Issue by l4kr** [jellyfin/jellyfin-web#3737]
**Describe The Bug**
Hi! When I change the login disclaimer in server settings it doesn't work even on a clean install.
When tested on 10.7.7 it works perfectly fine. 

**Steps To Reproduce**
1. change login disclaimer

**Expected Behavior**
A disclaimer should show on login page

**Comment by thornbill** [comment]
It seems to be working fine here: https://demo.jellyfin.org/stable
