### ISSUE TITLE
Player Ui not disappearing in Firefox

### ISSUE THREAD

**Issue by lowbit** [jellyfin/jellyfin-web#3738]
**Describe The Bug**
Randomly sometimes ui doesnt disappear in firefox web player even though nothing is being touched.

**Steps To Reproduce**

1. Open movie/tv show, start playing.
2. Stop touching kb/mouse
3. UI doesnt disappear auntil CTRL+F5, and even then sometimes it doesnt.

**Expected Behavior**
UI disappears

**Logs**
/

**Screenshots**
/

**System (please complete the following information):**
 - Platform:Windows 11
 - Browser: Firefox 101.0.1
 - Jellyfin Version: 10.7.7

**Additional Context**

**Comment by cela96** [comment]
Same thing happens to me
The title disappears correctly but the progress bar does not

System:
- Platform: Windows 11
- Browser: Chrome 103
- Jellyfin Version: 10.8.1
