### ISSUE TITLE
Can't shuffle through multiple subfolders inside photo library.

### ISSUE THREAD

**Issue by MCBuckethead** [jellyfin/jellyfin-web#3749]
**Describe The Bug**

In a photos library, if you are in a folder with only folders inside and select "shuffle" or "play all" it gives a PlaybackErrorNoCompatibleStream error. After a quick look, it's failing in playbackmanager.js in playWithIntros where firstItem is still null after resetting. 

**Steps To Reproduce**

1. Go to a photo library.
2. Click on one of the folders that has only sub folders.
3. Select "Play All" or "Shuffle"

**Expected Behavior**

If Shuffle - Shuffle randomly through all items in the sub folders
If Play All - Start from the first folder, go through all files, go through images in next folder, etc...

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Firefox
 - Jellyfin Version: 10.8.1

**Additional Context**

At first, I noticed that I had a video in this photo library in one of the sub folders by mistake and it was always just playing that video. After deleting that video, it gives the current error. That video was in one of the sub folders.
If you have a folder that has files and well as folders in it, it will play the files at that level.

If this is just a feature that hasn't been added, then the bug would be more that it doesn't hide the options when it would fail.

**Comment by Ramsin** [comment]
@MCBuckethead Can you add the directory above that so that the current problematic directory becomes a subdirectory....and try to shuffle once you go down one level (before opening the sub directory)? I'm having the same issue and would like to see if it works the same for you.

I had posted this in the discord...

> If I add my folder (Called Phone Backup) with pictures/video subfolders in it, and hit shuffle, I get...
> 
> "Playback Error - This client isn't compatible with the media and the server isn't sending a compatible media format."
> 
> If I add the directory right above it, then go into 'Phone Backup' as a subfolder and hit shuffle, it works fine.

**Comment by Ramsin** [comment]
Slight update...

If you go into your photo library, then update to 10.8.x, you can still hit shuffle....until you refresh the page, then it gives the error again.

**Comment by Ramsin** [comment]
Ok, I fixed it thanks to [u/VerbTheNoun95](https://www.reddit.com/user/VerbTheNoun95/) from [this post](https://www.reddit.com/r/jellyfin/comments/le5ohc/any_way_to_get_more_verbose_logs_when_playing/)

Of course his was a few years ago so the file that needs to be changed is main.jellyfin.bundle.js from the jellyfin-web folder. In macOS it's `/Applications/Jellyfin 2.app/Contents/Resources/jellyfin-web/`

Search for `MediaTypes:"Photo"` and change the 2 instances (don't know if you have to do both, but I did) to `MediaTypes:"Photo,Video"`

I hope this helps.

**Comment by PMarci** [comment]
I think I had the same problem as OP, and solved mine by changing `Recursive:!1` to `Recursive:!0` on an entry that only had `MediaTypes:"Photo"` specified as an option. I had some folders that had both subfolders and photos in them, and the contents of the subfolders wouldn't come up when clicking `Shuffle`.
The file @Ramsin is referring to is located under `/usr/share/jellyfin/web/main.jellyfin.bundle.js` on Ubuntu, this is where I changed the value as well.
Changing a bundle file doesn't seem the way to go, some additional control over these parameters might be handy, even if only in config files.
