### ISSUE TITLE
Enable Splash screen checkbox is not set with server provided value

### ISSUE THREAD

**Issue by JPVenson** [jellyfin/jellyfin-web#3750]
**Describe The Bug**
When checking the option "Enable the splash screen" in the general admin menu the option is not enabled after saving even when refreshing the webpage.

**Steps To Reproduce**
1. Goto the dashboardgeneral.html menu
2. Tick the checkbox "Enable the splash screen"
3. clicking "Save"
4. Reloading the site

**Expected Behavior**
5. Checkbox is unchecked

**Logs**

**Screenshots**
![image](https://user-images.githubusercontent.com/6794763/177409746-339fcbf8-9d46-435d-8e07-3f81ea7d1420.png)

**System (please complete the following information):**
 - Platform: Linux Docker
 - Browser: Edge
 - Jellyfin Version: 10.8.1

**Additional Context**
having a look into the "branding" api result, the value seems to be persisted, but the returned value is not correctly set on page load.

**Comment by hadicharara** [comment]
This issue should be closed as the bug is fixed.

**Comment by tywentghxst** [comment]
> This issue should be closed as the bug is fixed.

has it been fixed in a future update? because i have the same problem on the latest version

**Comment by JPVenson** [comment]
@tywentghxst The fix was checked in with 7c335792609431bf105411069d19fdb24ebeb603 after the 10.8.1 release and should be patched with the next release.

**Comment by tywentghxst** [comment]
Okay, thanks for the clarification! 🙏
