### ISSUE TITLE
Add more subtitle size options

### ISSUE THREAD

**Issue by HEPOSHEIKKI** [jellyfin/jellyfin-web#3794]
Jellyfin web currently only has 5 subtitle sizing options ranging from very small to large, but even the largest subtitle option looks tiny on a larger display (eg. When watching on a 4k TV) 

Solution: allow users to set subtitle font size, or make the current subtitle size options scale to the viewport.

This is the largest current subtitle option displayed on a 4K TV:
![missa_han_on](https://user-images.githubusercontent.com/51783206/183290645-de89ca34-4327-44cc-af57-fd3048f80fed.png)

**Comment by Xilis** [comment]
Related to #558
