### ISSUE TITLE
Minify Jellyfin's JavaScript files

### ISSUE THREAD

**Issue by whalehub** [jellyfin/jellyfin-web#383]
**Describe the feature you'd like**
I would like you to minify Jellyfin's JavaScript files in order to speed up the page's loading time and responsiveness. You can use UglifyJS 2 to accomplish this task.  

**Additional context**
Here's a report with detailed information about which files need to be minified: https://gtmetrix.com/reports/jellyfin.datahoarder.dev/nZYW8J98

**Comment by dkanada** [comment]
This is a duplicate of #21 but you can always track our progress there.
