### ISSUE TITLE
UI Bug - Artist name overlaps on the control buttons

### ISSUE THREAD

**Issue by ar7x9** [jellyfin/jellyfin-web#384]
The bug is that the names of the artist of the songs are overlapping with control buttons (play, pause, etc.).

Bug occurs when artist name is extremely long.

Overlap should not have occurred

![Image](https://user-images.githubusercontent.com/51527759/60668148-c9b77700-9e5a-11e9-965f-f0b9b137c6d5.png)

**System (please complete the following information):**
 - OS: Windows 1080p 125% scale
 - Browser: Firefox
 - Jellyfin Version: 10.3.5.0

**Comment by anthonylavado** [comment]
Fixed by #403.
