### ISSUE TITLE
CBZ fit width issue

### ISSUE THREAD

**Issue by meet-k-pandya** [jellyfin/jellyfin-web#3861]
### Describe the bug

Steps:
1. Open CBZ file
2. Page is set to fit height causing page overlap, no option to zoom out as well.

Need options to change display behavior. Fit to width, Fit to height, zoom in, zoom out.
Or if it's too complex, I think fit to height instead of fit to width should solve most issues for CBZ files.

I tried looking in the code, but couldn't how this is being handled.

### Application version

2.4.4

### Where did you install the app from?

Google Play

### Device information

Asus ROG Phone 5

### Android version

Android 12

### Jellyfin server version

10.8.4

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by MinecraftPlaye** [comment]
Maybe this might help with the "fit to width" thing: https://stackoverflow.com/a/66833775

**Comment by meet-k-pandya** [comment]
This works, but requires additional handling to manipulate `object-postion` on scroll/touch/up-down arrow keys. Trying to avoid such additional event handling if possible.
