### ISSUE TITLE
Quick Connect feature doesn't work on individual users from the Admin account

### ISSUE THREAD

**Issue by alanazar** [jellyfin/jellyfin-web#3918]
**Describe The Bug**
Quick Connect feature doesn't work on individual users from the Admin account.
Instead it signs them in as the main account (Admin) or whatever account you're using on the server.
Ideally, you should be able to help others sign in to their accounts using Quick Connect from the Admin console.
Otherwise you need to first sign in as them and then do the Quick Connect.

**Suggested Fix**
Ideally, from the Admin panel be able to use Quick Connect per user under their profile or some central page
Otherwise, remove the Quick Connect feature when viewing a user setting that is different than who you're logged in as

**Steps To Reproduce**
1- On the client device sign-in page, click Quick Connect and get the number
2- On the Admin panel while signed in as Admin. Dashboard \ Users \ Open User
3- Click on "Edit this user's profile, image and personal preferences."
4- You're taken to that user's settings
5- Click on Quick Connect and enter the number there
6- Back on client device you're signed is as the Admin with full access to media and server settings

**Expected Behavior**
Following this approach, you should be able to easily help others sign-in to their accounts.
Instead they get signed in as Admin and the only way to revoke access is to get them to sign out or for you to change your password.

**Screenshots**
![image](https://user-images.githubusercontent.com/93149610/190904440-0e9afd07-ae68-4498-a321-71f56d423795.png)
![image](https://user-images.githubusercontent.com/93149610/190904485-89eaccd7-f5c1-4153-a054-edef02b68f76.png)

**System:**
Jellyfin 10.8.4
Windows

**Comment by thornbill** [comment]
Just a note that if we want admins to be able to authenticate users in this manner, I believe we will need API changes to allow passing a user ID.

**Comment by hugo-id** [comment]
Hi, just chiming in I would appreciate this to be fixed too.

And before that time the "quick connect" option really should just be hidden, it could be a problem if the admin doesn't realise what's happened.
