### ISSUE TITLE
Extend NativeShell for Jellyfin theater

### ISSUE THREAD

**Issue by cromefire** [jellyfin/jellyfin-web#392]
**Is your feature request related to a problem? Please describe.**

For the overhaul on Jellyfin theater I need the following features/APIs on `NativeShell`:

 - playback (start/stop/skip/etc.)
 - ~~wake on lan~~
 - exec (currently hardcoded to `false`)

**Describe the solution you'd like**

It would be good, if those would be implemented like all other APIs

**Describe alternatives you've considered**

The current version of Jellyfin theater injects files into Alameda

**Additional context**

See jellyfin/jellyfin-theater-electron#26

**Comment by cromefire** [comment]
@dkanada Can you do something here? This would make the theater integration much easier

**Comment by anthonylavado** [comment]
@jellyfin/web Anyone able to look at this? Thanks!

**Comment by dkanada** [comment]
@cromefire I haven't looked into exec yet so I can't comment on that one, but WoL is already removed from the web client and is probably getting deprecated eventually.

If you look at the NativeShell implementation in android you can see the two media players ExoPlayer and ExternalPlayer. The web client will use `NativeShell.getPlugins` to add any platform specific media players (which is what I think you are referring to when you say `the current version of Jellyfin theater injects files into alameda`) but we haven't found an elegant solution for the issue yet. The native media playback needs to be well integrated and allow for an indeterminate number of methods - android has two custom players for example.

**Comment by cromefire** [comment]
> The web client will use NativeShell.getPlugins to add any platform specific media players (which is what I think you are referring to when you say the current version of Jellyfin theater injects files into alameda) but we haven't found an elegant solution for the issue yet. The native media playback needs to be well integrated and allow for an indeterminate number of methods - android has two custom players for example.

No the current Version inject a number of files like `apphost.js` into the loading process and does not use `NativeShell` at all.

Also the current stable Version of jellyfin (deb) does not support `NativeShell.getPlugins()` yet

**Comment by cromefire** [comment]
> but we haven't found an elegant solution for the issue yet. The native media playback needs to be well integrated and allow for an indeterminate number of methods - android has two custom players for example.

I can Design an API for that

**Comment by cromefire** [comment]
I started to draft something here: https://github.com/cromefire/jellyfin-nativeshell-api

In the event that this gets accepted, it should be imported into the Jellyfin org and published to npm (someone needs to create a Jellyfin org)

**Comment by cromefire** [comment]
Drafted a PRs here: cromefire/jellyfin-nativeshell-api#1

I think we should discuss there how to design an api. Feel free to add your comments to the code.

**Comment by anthonylavado** [comment]
>... published to npm (someone needs to create a Jellyfin org)

Just for reference, I have the Jellyfin org on NPM.

**Comment by cromefire** [comment]
Then you would need push that once it's ready
