### ISSUE TITLE
EPUBs are not readable with new dark mode

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-web#3930]
**Describe The Bug**
EPUBs seem to render with black text on a dark background by default since https://github.com/jellyfin/jellyfin-web/pull/3855 was merged.

**Steps To Reproduce**

1. Open the EPUB player within Jellyfin

**Expected Behavior**
Book text should be legible. We should either:

1. Use epub.js theme support to render in dark mode correctly.
2. Force a light background for the EPUB reader.

Preferably we should use epub.js themes in my opinion. I have not found much documentation for that though.

**Logs**
N/A

**Screenshots**
![Screenshot 2022-09-21 at 14-10-57 Jellyfin](https://user-images.githubusercontent.com/3450688/191581550-e0c35a51-4957-4820-bdd6-6865397c5a1f.png)

**System (please complete the following information):**
 - Platform: Any
 - Browser: Any
 - Jellyfin Version: Unstable

**Additional Context**

**Comment by MinecraftPlaye** [comment]
Oh.

> Preferably we should use epub.js themes in my opinion. I have not found much documentation for that though.

I think the only documentation is that [example here](https://github.com/futurepress/epub.js/blob/master/examples/themes.html). It just registers some css file. I'm not sure how this would be implemented in Jellyfin, but I guess when Jellyfin changes the theme, epubjs needs to be somehow informed of that change.
