### ISSUE TITLE
[Issue]: Loading animation doesn't go away

### ISSUE THREAD

**Issue by Sim0nW0lf** [jellyfin/jellyfin-web#3981]
### Please describe your bug

After updating to 10.8.0 the loading animation doesn't go away...
I have to click on something otherwise it will always stay there!
This issue is visible in the Browser, Windows Client, and Android Phone Client (I only tested those)

I am running jellyfin in docker on arm64.

![image](https://user-images.githubusercontent.com/31454341/173289896-25f15e0b-c924-4d03-a9db-8a747ff2741e.png)

### Jellyfin Version

10.8.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thornbill** [comment]
Could someone check the browser console (press F12) for errors when this happens and include any found here?

**Comment by thornbill** [comment]
This is looking a lot like this issue https://reddit.com/r/jellyfin/comments/xj6s3d/ghost_spinner/
