### ISSUE TITLE
Library Filter Does Not Save At All

### ISSUE THREAD

**Issue by XVicarious** [jellyfin/jellyfin-web#40]
On the webapp (going to my jellyfin instance through a browser), when I use a filter on a library (filter by unplayed, specifically) it doesn't save its state. This issue existed in Emby, but didn't exist in the Android app. I'm going to try building the app again to see if I can reproduce this on the Jellyfin app.

EDIT: Can confirm that this issue exists with the app as well.

**Comment by yotoprules** [comment]
This is something I would really like to see implemented. It can be kind of difficult finding a new show to watch when most of them I've already seen, and everytime I open Jellyfin I have to manually filter.

**Comment by mrx23dot** [comment]
related https://github.com/jellyfin/jellyfin-android/issues/619

**Comment by joheiska** [comment]
up

**Comment by Partybwal** [comment]
Any progress on this? Just started testing Jellyfin as a potential replacement for Plex, and immediately noticed this issue. Are the users really expected to select same filter every time? Is it common that people want their library full of movies that they have already seen? Then again, maybe this makes us better at actually deleting them instead of just filtering them away :)

**Comment by rwjack** [comment]
> Then again, maybe this makes us better at actually deleting them instead of just filtering them away :)

![image](https://user-images.githubusercontent.com/59068073/226617620-50626fdd-0e6f-42b3-ab80-c022f2b77162.png)

**Comment by joheiska** [comment]
> Are the users really expected to select same filter every time? Is it common that people want their library full of movies that they have already seen? Then again, maybe this makes us better at actually deleting them instead of just filtering them away :)

Pretty sure it is just an oversight. Android TV client does remember the filters. Could be implemented here with just cookies.

But yeah, hopefully this is prioritized soon as it is a major UX issue in the web/desktop clients.

**Comment by jvoinot** [comment]
Hello,
It will be great to have this feature. That's the only thing missing for me.
Regards,

**Comment by ricci2511** [comment]
I took a look and it seems that I found a way to fix it.

Will submit a pr in a couple of minutes.

**Comment by yezige** [comment]
mark

**Comment by yezige** [comment]
This old question is really important to me, it is a headache to set filter items every time, if you consider this question https://github.com/jellyfin/jellyfin-web/pull/4697#issuecomment-1636074512, I think we can add highlight color tips, somewhat similar to emby.
![image](https://github.com/jellyfin/jellyfin-web/assets/11436166/37aefb47-2282-4492-8b64-51444ff0c363)

**Comment by jneidel** [comment]
Just wanted to note that this does not apply to all Library types. "Movies" and "Shows" have this problem.

My library of the "Other" type remember my unplayed filter just fine. Same is true for "Collections", "Photos" and "Books".

The two groups also use a different UI for filtering.

**Comment by yezige** [comment]
So sad that it has been moved to v10.10.0 again.

**Comment by JasonBSteele** [comment]
Just moved over from Emby and everything is up and running fine - but then ran into this issue. It is a fairly major problem when you have a large library of mostly watched content.

From the above comments it looks like there was a merge conflict and also feedback on it causing issues as there is no visible indication that a filter has been applied which could lead some to think their content is missing.

On that point I would just say that Emby have implemented it and I am not aware of any issues.

Is this likely to get resolved?

**Comment by cyberknet** [comment]
@ricci2511 with #5717 now complete, will you be updating #4697 ?

**Comment by ricci2511** [comment]
> @ricci2511 with #5717 now complete, will you be updating #4697 ?

Thanks for reminding me of that pr of mine. I'll try to get it done this week, just need to solve the conflicts and test again.

**Comment by ricci2511** [comment]
Actually it seems like #5717 already fixed this issue as mentioned in the description there. I double checked with latest `master` and it works well. Feel free to close #4697 as it's not longer needed.

**Comment by thornbill** [comment]
This is in unstable only at the moment. It is technically a new feature so it will be included in the 10.10.0 release.
