### ISSUE TITLE
Tizen 2.3: Master branch doesn't work

### ISSUE THREAD

**Issue by the4anoni** [jellyfin/jellyfin-web#4055]
**Describe The Bug**
Like in topic. When built with jellyfin-tizen, jellyfin-web master branch just freezes on initial screen

**Steps To Reproduce**
Build jellyfin-tizen and run it

**Expected Behavior**
It works

**Logs**
I don't have any logs

**System (please complete the following information):**
 - Platform: Tizen

**Additional Context**
Using jellyfin-web branch [v10.8.5](https://github.com/jellyfin/jellyfin-web/releases/tag/v10.8.5) fixed issue for me.

**Comment by dmitrylyzo** [comment]
This is usually caused by ES5 incompatible code. It should work after 9d8f9c806c6e8e0c45bb38f87eabdac32bf71bba.
Current master (f0b29fa9cc4e168e499e292176e66073cb38596f) works on webOS 1.2 (~Tizen 2.3).

**Comment by dmitrylyzo** [comment]
@the4anoni Are you on Windows?
https://github.com/jellyfin/jellyfin-tizen/issues/144#issuecomment-1289734592

**Comment by the4anoni** [comment]
> @the4anoni Are you on Windows? [jellyfin/jellyfin-tizen#144 (comment)](https://github.com/jellyfin/jellyfin-tizen/issues/144#issuecomment-1289734592)

Yes, I am on Windows
