### ISSUE TITLE
AV1 transcode forced to VP8 

### ISSUE THREAD

**Issue by snakeeater4526** [jellyfin/jellyfin-web#4060]
**Describe The Bug**
When AV1 is transcoded, it transcode it to VP8 and opus ( in a very shit quality) using only cpu 

**Steps To Reproduce**
watch an AV1 encoded video and switch to a lower resolution like 480p 

**Expected Behavior**
transcode to H264 (with vaapi)

**Logs**
[Log jellyfin.txt](https://github.com/jellyfin/jellyfin-web/files/9795895/Log.jellyfin.txt)
[Log ffmpeg.txt](https://github.com/jellyfin/jellyfin-web/files/9795896/Log.ffmpeg.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/41698614/196062965-80ac90de-04b4-4f4b-b390-ddd95563967d.png)

**System (please complete the following information):**
 - Platform: server ubuntu 22 on proxmox with intel gpu passthrough
 - Browser: tested on firefox but think it's an universal problem
 - Jellyfin Version: 10.8.4

**Additional Context**
no problem with directplay AV1 but since vp8 is probably not decoded well on Android phone, it's quite buggy

**Comment by snakeeater4526** [comment]
I have to add another problem to this... Since the devs recently thoughts that bitrate is the law for transcoding... Now it happen that my 1.5mb av1 video CAN'T  be transcoded to h264 even if forced.... The only exception is when you transcode to lower than the original bitrate ( here 1.5mb). Which I found very dumb because that mean you can't transcode to device that don't support av1... And also that mean if your source is h265 5mb.... You can't transcode h264 10mb.... Which is obviously completely dumb quality wise...

Please go back at least for forced transcoding and please take in consideration those device that don't hw decode av1

**Comment by JPAchilles** [comment]
Seconding this issue, I've been having this issue for the past 5 months without a fix that I could find. I just let it be because there were only a couple people using my media server, but now there's several with clients that don't support AV1 and my server can't keep up
