### ISSUE TITLE
Airplay bug

### ISSUE THREAD

**Issue by inigelcn** [jellyfin/jellyfin-web#4063]
**Describe The Bug**
 trying out Jellyfin as a potential replacement for Kodi or Plex as a music server for streaming to devices or via web player.

I can't seem to connect to my Apple devices, even though as far as I know Airplay is supported. It doesn't see my Homepod minis or my Apple TV 4k as renderers

**Media Information**

**Screenshots**

**System (please complete the following information):**
 - Platform: [e.g. Linux]
 - Jellyfin Version: [ios mobile 1.5.0(5.5.0.0)]

**Additional Context**

**Comment by thornbill** [comment]
The AirPlay option is only shown after a video is started to play. See #3557.
