### ISSUE TITLE
Double escaping in Play Queue

### ISSUE THREAD

**Issue by AntiBlueQuirk** [jellyfin/jellyfin-web#4082]
**Describe The Bug**
The artist's name is double escaped in the Play Queue.

**Steps To Reproduce**
1. Play some music or an audiobook with an Artist tag that has something HTML escapable in it, like a quotation mark.
2. View the play queue.
3. Observe that the artist's name has HTML entities in it.

**Expected Behavior**
The artist's name should not have HTML entities in it.

**System (please complete the following information):**
 - Platform: Linux
 - Jellyfin Version: 10.8.5

**Additional Context**
This is caused by this code. The artist name is escaped outside the template as well as inside.

https://github.com/jellyfin/jellyfin-web/blob/f8b0c941f5e97d99cd27cf69e6fe3962314577d5/src/components/remotecontrol/remotecontrol.js#L148-L150

**Comment by AntiBlueQuirk** [comment]
I just realized that this is a duplicate of literally the last issue, #4078. Ooops.

**Comment by meonkeys** [comment]
Good find, thank you! I tried to improve the title of #4078 for folks searching for this later.
