### ISSUE TITLE
My Media images are blurry

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin-web#409]
**Describe the bug**

My Media images are blurry in nightly-20190811

**To Reproduce**

1. Open JF in chrome on desktop 1080p screen
2. see blurry images

**Expected behavior**

Images should be clear.

**System (please complete the following information):**
 - OS: [e.g. Docker, Debian, Windows]
 - Browser: [e.g. Firefox, Chrome, Safari]
 - Jellyfin Version: [e.g. 10.0.1]

**Additional context**

Images have maxWidth and maxHeight of 202, resulting in a 202x114 image scaled to 280x157 at my window size. Blurry.

**Comment by onny** [comment]
Could you please post a screenshot showing the blurry images?
Best regards
Jonas

**Comment by SenorSmartyPants** [comment]
My media is blurry, Next Up and Latest TV is fine.
![image](https://user-images.githubusercontent.com/991618/64193891-6db1a480-ce43-11e9-8b51-ceafa849726f.png)

**Comment by SenorSmartyPants** [comment]
My media images have links like this
`http://nanners:8096/emby/Items/767bffe4f11c93ef34b805451a696a4e/Images/Primary?maxHeight=202&maxWidth=202&tag=4c16adb4c26775fe8354ec939ae9e85d&quality=90`

Next Up have images like this
`http://nanners:8096/emby/Items/c245a802716b9e2bab9c2a3f76b2045a/Images/Thumb?maxWidth=303&tag=27bede8d89886abd0d47be803e0f6bd9&quality=90`

**Comment by Nickbert7** [comment]
Should be fixed by https://github.com/jellyfin/jellyfin-web/pull/443
