### ISSUE TITLE
No Backdrops on Homescreen from FSK 18 movies

### ISSUE THREAD

**Issue by StevMaHo** [jellyfin/jellyfin-web#4090]
**Describe The Bug**
No Backdrops on Homescreen from FSK 18 movies

**Expected Behavior**

**System (please complete the following information):**
 - Platform: [Windows]
 - Browser: [Edge,]
 - Jellyfin Version: [e.g. 10.8.5]

**Comment by thornbill** [comment]
Just to follow up on this, iirc this behavior is intentional to avoid potentially mature content showing up unexpectedly.
