### ISSUE TITLE
"Playback Error" with all videos

### ISSUE THREAD

**Issue by grannymaster** [jellyfin/jellyfin-web#4096]
**Describe The Bug**
Can't play any videos from my NAS

**Media Information**
https://pastebin.com/tuaekEcd

Playback issues start at this stamp "[2022-10-24 16:34:32.810 +00:00] [INF]"

**Screenshots**
https://i.imgur.com/uDptMei.png
https://i.imgur.com/qUcbgYk.png
https://i.imgur.com/quZyHjF.png

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Firefox, Chrome
 - Jellyfin Version: 10.8.5

**Additional Context**
Enabling transcoding didn't help.

**Comment by thornbill** [comment]
This is not a bug in jellyfin-web. Based on the logs you provided it looks like ffmpeg is missing or misconfigured on your server.
