### ISSUE TITLE
Subtitle uploader dialog doesn't open when in TV layout mode.

### ISSUE THREAD

**Issue by jsayol** [jellyfin/jellyfin-web#4146]
**Describe The Bug**
Subtitle uploader dialog doesn't open when in TV layout mode.

**Steps To Reproduce**

1. Set Jellyfin in TV layout mode.
2. Go to the page for any movie or tv show episode.
3. Click on "More" menu icon.
4. Click on "Edit subtitles" option.
5. Click on "+" (upload) button.
6. Nothing happens, an exception is thrown in the dev console.

**Expected Behavior**

The subtitle uploader dialog should open, just like it does when in Desktop layout mode.

**Logs**

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'on')
    at 3052.c7c3a2dd04a0e90574a9.chunk.js:formatted:95:47
    at 3052.c7c3a2dd04a0e90574a9.chunk.js:formatted:147:18
    at new Promise (<anonymous>)
    at Object.H [as show] (3052.c7c3a2dd04a0e90574a9.chunk.js:formatted:81:20)
    at 2912.2aa61c9a7dfa62ca61d5.chunk.js:1:5901
```

**Screenshots**

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Chrome 107.0.5304.88
 - Jellyfin Version: 10.8.7

**Additional Context**

The problem seems to he [here](https://github.com/jellyfin/jellyfin-web/blob/a71ed46afb30a613085d99950813b9d46f1ebd34/src/components/subtitleuploader/subtitleuploader.js#L135) and [here](https://github.com/jellyfin/jellyfin-web/blob/a71ed46afb30a613085d99950813b9d46f1ebd34/src/components/subtitleuploader/subtitleuploader.js#L141) in the code of the subtitule uploader component. It's trying to reference a property `centerFocus` of the scroller library, but no such property exists. As you can see, this code is only executed when in TV layout mode:

```
    if (layoutManager.tv) {
        scrollHelper.centerFocus.on(dlg, false);
    }
```

**Comment by dmitrylyzo** [comment]
[Here](https://github.com/jellyfin/jellyfin-web/blob/a71ed46afb30a613085d99950813b9d46f1ebd34/src/components/subtitleuploader/subtitleuploader.js#L5) should be `../../scripts/scrollHelper`.

**Comment by jsayol** [comment]
You're right @dmitrylyzo, thanks! I just created a PR to fix this.
