### ISSUE TITLE
Episode detail page doesn't show guest stars

### ISSUE THREAD

**Issue by fffrankieh** [jellyfin/jellyfin-web#4148]
On detail pages for TV episodes, only people with the "Actor" role are shown, not people with the "GuestStar" role.

I can open a PR for this (I already have it working locally) but there are two ways to do it, and I'm not sure which you would prefer.

1. Add another "Guest Cast" section before or after the "Cast & Crew" section. I like this better because I don't need to click the arrows to "scroll" the main cast section over to the guest stars, and usually I am more interested in the guest stars than the main cast on a specific episode, since I already know who the main cast are. For the same reason I prefer the additional section to appear first, like on TVmaze, but it could also come after.

2. Show guest stars in the "Cast & Crew" section after the main cast actors.

**Comment by fffrankieh** [comment]
I just noticed the stalebot comment notification in my spam folder. This is still an issue and I can still open a PR immediately, I just need to know which of the two options will be accepted as a PR.

**Comment by nielsvanvelzen** [comment]
You can open a PR for your preferred option and link to this issue. Worst-case it needs to be changed to the other one. Although I think both have pro's & con's.
