### ISSUE TITLE
Fullscreen button missing on Samsung SmartTV browser

### ISSUE THREAD

**Issue by sphaero** [jellyfin/jellyfin-web#4159]
Can't switch to fullscreen in the player as the button is missing.

**Steps To Reproduce**

1. Just open the Jellyfin Web interface
2. Play a movie/video
3. Notice there is no fullscreen button

**Expected Behavior**
* A fullscreen button to watch the video on the full display

**Screenshots**

Wll follow

**System (please complete the following information):**
 - Platform: Jellyfin 10.8.3 running on a Linux (armhf) server
 - Browser: Samsung SmartTV internal browser

**Comment by sphaero** [comment]
![IMG_20221108_205219](https://user-images.githubusercontent.com/832465/200664306-4fa8c8c8-4627-4331-9cf1-ceef65c6d8c8.jpg)

**Comment by sphaero** [comment]
Ok,fair enough but there's no option on this Samsung TV to set the browser fullscreen that I'm aware of.

**Comment by dmitrylyzo** [comment]
It is called like `Hide top bar`, iirc

**Comment by sphaero** [comment]
I did not find such option anywhere. Although I did manage to get it fullscreen by a very fast double clicking in the middle button of the remote. It's quite counter intuitive as it doesn't work all the time and I can't figure out when it does work and when not.

I guess we can close this issue as it probably should be a feature request to add the fullscreen button on the Tizen browser?

**Comment by dmitrylyzo** [comment]
[Samsung internet browser ➡ full screen mode?](https://r1.community.samsung.com/t5/galaxy-note/samsung-internet-browser-full-screen-mode/m-p/9026558/highlight/true#M25167)

In general, the browser on the TV is not the best way to use Jellyfin.

**Comment by sphaero** [comment]
No you are probably right but the install of the tizen app is not for regular users. Hence I'm testing as much browsers as I can as that's most accessible.
