### ISSUE TITLE
React-router is not restoring scroll position when navigating back

### ISSUE THREAD

**Issue by brutric** [jellyfin/jellyfin-web#4164]
This PR https://github.com/jellyfin/jellyfin-web/pull/3792 causes the movies page to reload every time you click back.
So if you're scrolling down on your movies and click one then click back you will lose your place scrolling because it reloads the entire page

**Comment by thornbill** [comment]
Yeah this is a known issue currently with the react-router implementation on master. It is not restoring the page position when navigating back. It's not specific to that page, but probably most noticeable there.

**Comment by thornbill** [comment]
I believe this was fixed by #4834
