### ISSUE TITLE
视频文件类型识别错误 Video file type identification error

### ISSUE THREAD

**Issue by Soizzer** [jellyfin/jellyfin-web#4165]
版本：10.8.7
操作系统：Windows 10 专业工作站版 21H1
架构：X64

问题：
升级到10.8.7后，剧集类文件夹内的文件，即便按照剧集（节目）的命名规则，Jellyfin仍然将其识别为电影类型而采用文件夹方式显示。原来使用10.7.4的时候则可正常识别为剧集（节目）类型。

Version: 10.8.7
Operating System: Windows 10 Professional Workstation 21H1
Architecture: X64

question:
After upgrading to 10.8.7, the files in the episode folder, even according to the naming rules of episodes (Shows), Jellyfin still recognizes them as movie types and displays them as folders. Originally, when using 10.7.4, it can be recognized as an episode (Shows) type normally.

![微信截图_20221110163018](https://user-images.githubusercontent.com/73036854/201040717-38f822cc-a704-4e8d-a668-c7d352a2952a.png)
![微信截图_20221110163046](https://user-images.githubusercontent.com/73036854/201040728-4e8f5871-eb3d-4155-9c64-82ea3afbf79d.png)
![微信截图_20221110163103](https://user-images.githubusercontent.com/73036854/201040730-fd4e910a-fd68-471e-ab8c-c6da329d909f.png)

**Comment by nyanmisaka** [comment]
https://docs.jellyfin.org/general/server/media/shows.html

```
Shows
└─Zootopia+
    └─Season 1
            Zootopia+ - S01E01.mp4
            Zootopia+ - S01E02.mp4
            Zootopia+ - S01E03.mp4
            Zootopia+ - S01E04.mp4
            Zootopia+ - S01E05.mp4
            Zootopia+ - S01E06.mp4
```

![image](https://user-images.githubusercontent.com/14953024/201067941-8ef6cc72-f70a-46dd-972f-60c2a41fad48.png)

![image](https://user-images.githubusercontent.com/14953024/201068138-2c174266-cc0e-46a4-b47b-104d4a438a2a.png)
