### ISSUE TITLE
Watched TV shows should not have a permanent checkmark

### ISSUE THREAD

**Issue by mdinger** [jellyfin/jellyfin-web#4167]
** Describe the bug

1. Go to a TV show library with watched and unwatched shows
2. The unwatched shows will have a blue number of episodes remaining
3. The watched shows will have a blue checkmark

The blue checkmark should be removed or at least temporary. The number of episodes to watch is useful because it tells you how much remains. A watched show needs no extra information to highlight it is unwatched anymore.

When browsing, they actually make it harder to notice which show you have not seen because all shows have a blue mark. Plex leaves watched shows blank which makes browsing easier to parse visually.

**System:**
 - Jellyfin Version: 10.8.7

**Comment by thornbill** [comment]
This is working as intended currently. Requests for changes to how Jellyfin currently works belong here: https://features.jellyfin.org/
