### ISSUE TITLE
Automatic adding movies to collections

### ISSUE THREAD

**Issue by LordRofl** [jellyfin/jellyfin-web#4169]
**Describe The Bug**
Automatic adding collections in movie options does not pull metadata and pictures from themoviedb like when adding by hand and ticking search for metadata.

**Expected Behavior**
Automatic collection should add all the artwork and metadata.

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Firefox
 - Jellyfin Version: 1.8.7

**Comment by KingIzzymon** [comment]
Are you using this plugin? https://github.com/jellyfin/jellyfin-plugin-tmdbboxsets

I just setup a new jf server using this plugin and its working well now.
