### ISSUE TITLE
Player crashes and sends user to a broken homepage when controls are used

### ISSUE THREAD

**Issue by aMySour** [jellyfin/jellyfin-web#4177]
**Describe The Bug**
On any video on any web browser (tested on Chromium, Firefox and more), when I try to turn on subtitles or use the options from the controls on the bottom of the media player, I get sent to the homepage, but with the theme completely messed up.

**Steps To Reproduce**

1. Open any video (movie, show, etc) in the player
2. Press the subtitles button (if the media has subtitles) or the options button from the player controls
Boom, you're now in a broken homepage

**Expected Behavior**

I expected to have the subtitles turn on when I hit the subtitles button, and the options to open when I hit the options button, not a broken homepage

**Logs**
All the logs after clicking any control of player:
```
[appRouter] "/video" route not found (appRouter.js:123)
Translation key is missing from dictionary: AirPlay (globalize.js:229)
Requesting url without automatic networking: http://<server ip>:8096/Sessions/Playing/Stopped (jellyfin-apiclient.js:1)
nowplaying event: playbackstop (nowPlayingBar.js:630)
[appRouter] "/home.html" route not found (appRouter.js:123)
The Notification permission may only be requested in a secure context. (index.html)
Requesting http:/<server ip>:8096/Users/1e3ca909723042dc8b4efb0dffec3068/Views (jellyfin-apiclient.js:1)
Uncaught (in promise) ActionSheet closed without resolving
```

**Video**
Here's a screen recording of the issue (sorry for the low framerate):
[Video.webm](https://user-images.githubusercontent.com/52638772/202775856-784e6721-7991-442d-96c2-edff5624b5e8.webm)

**Screenshots**

Homepage normally:
![image](https://user-images.githubusercontent.com/52638772/202775068-169f7843-0f71-4a9d-9f00-32a899928b87.png)

Player before clicking media player options:
![image](https://user-images.githubusercontent.com/52638772/202775293-120ba414-daf3-4fb1-a67a-86a4fc1842a0.png)

After clicking (I am sent to the homepage but looking like this):
![image](https://user-images.githubusercontent.com/52638772/202775666-89f5dbaf-0bb2-428e-83db-fe179d49fe25.png)

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Chromium, LibreWolf and Firefox
 - Jellyfin Version: 10.9.0

**Additional Context**
In case it helps, Jellyfin is running on 32-bit Ubuntu Server 22.04 on a Raspberry Pi 4 4GB (ARM)

**Comment by aMySour** [comment]
rip

**Comment by aMySour** [comment]
this is so sad

**Comment by anthonylavado** [comment]
Sorry for what seems like a frustrating response - I don't think we've had any other reports like this. From your video, it looks like you might have some custom theming or CSS applied. Does the issue still happen without that?

**Comment by aMySour** [comment]
I don't recall ever adding any custom CSS or themes

**Comment by aMySour** [comment]
replying to your edits, I don't remember installing plugins either

maybe I was on an unstable version, that would explain it, I haven't tried it in a while

**Comment by aMySour** [comment]
I believe I had installed it with the instructions in the README that tell you to clone from the repo

**Comment by thornbill** [comment]
The README only includes developer documentation. You unintentionally installed an unstable (development) version of Jellyfin. Normal installation instructions can be found on the [Jellyfin website](https://jellyfin.org/downloads/server).
