### ISSUE TITLE
Delete Media confirmation is highlighted the wrong way around

### ISSUE THREAD

**Issue by Cyan101** [jellyfin/jellyfin-web#419]
![ss (2019-08-25 at 23 29 22)](https://user-images.githubusercontent.com/2821230/63652276-f9b33480-c790-11e9-93e6-435ef84ed632.png)

Might be a bit opinionative but deleting should be the highlighted button as its the button taking action, while cancel isn't.

Many programs like discord, reddit, google drive all have their deletes highlighted and their cancels as the background color/non-highlighted.

**Comment by anthonylavado** [comment]
I suppose we could do that and make the Delete button red as well

**Comment by Cyan101** [comment]
Sure.

I've also been changing a bunch of settings on my server and it's not just
the delete popup that has cancel highlighted, so I'd suggest changing the
cancel and "action" button both.

I can have a look at making a PR for this later if you'd like.

**Comment by Cyan101** [comment]
seems like it's actually mislabeled in the HTML

You can see here that the delete button has the button-cancel class, while the cancel button has the button-submit class.

![image](https://user-images.githubusercontent.com/2821230/63678786-80fcb880-c822-11e9-95e0-5450e95f8af9.png)

**Comment by dkanada** [comment]
I think it was a design choice at the time. It's not a bad idea to default to the safe operation rather than the one that will destroy media.

**Comment by Cyan101** [comment]
problem is the design of it clashes against "standards" that most other programs follow, I personally almost deleted some files because I avoided the highlighted button cause I was trying to cancel.

I was going to just make a PR with some CSS changes but since its in the HTML i'm not too sure which files I need to be looking for and changing, especially since its not just for the delete prompt.

**Comment by dkanada** [comment]
Ah I see what you mean. The classes `button-cancel` and `button-submit` apply the color schemes. If you wanted to add another class next to those called `button-red` or something and then flip the button styles that would work.

It would be best to find all instances of inconsistent button coloring and change them all at once with the new class though.

**Comment by Cyan101** [comment]
Yeah, the styles which are correctly coloured are linked to the wrong buttons, you could make another css class with `button-red` or `button-delete` but I think that's a second thing to worry about, first thing should be to find where the buttons are created and fix it up so that they have the correct class on both buttons.

Again, i'm not too sure where these buttons are being built so I don't think i'll be able to PR this
