### ISSUE TITLE
Item details page layout is broken on mobile in master

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-web#4197]
**Describe The Bug**
The margins/padding for the content of the item details page seem incorrect on mobile causing elements on the page to overlap or not be visible.

**Steps To Reproduce**
1. Open and unstable/master instance on a mobile device
2. Go to the item details screen

**Expected Behavior**
Elements on the page should not be overlapping

**Logs**
N/A

**Screenshots**
| master | 10.8.8 |
|---|---|
| ![FECF8516-3198-48CF-9095-28A994BCA0BE](https://user-images.githubusercontent.com/3450688/206727911-3bb14254-ee07-4000-860c-19013d305a97.jpeg) | ![5FD9014D-75D2-4CAE-8C87-F1DFAA783163](https://user-images.githubusercontent.com/3450688/206729550-03ec49c4-e762-4dd1-b879-4a1cd00052b2.jpeg) |

**System (please complete the following information):**
 - Platform: Mobile
 - Browser: All
 - Jellyfin Version: Master

**Additional Context**
Probably a regression introduced by https://github.com/jellyfin/jellyfin-web/pull/3743

**Comment by hadicharara** [comment]
I don't remember seeing this. I could check it out and track it down in a few days.

**Comment by hadicharara** [comment]
Currently investigating. It seems, because I was testing with Firefox, that I didn't detect the problem. On 10.8.8, using Firefox's mobile view, I get a similar result to master.

**Comment by hadicharara** [comment]
`.layout-mobile` doesn't seem to be applied to Firefox.
