### ISSUE TITLE
bufferFull errors on Chromium

### ISSUE THREAD

**Issue by jithatsonei** [jellyfin/jellyfin-web#4212]
**Describe The Bug**
bufferFullError occurs during video playback on Chromium

**Steps To Reproduce**
Unable to reliably reproduce on other machines, error occurs after approx a few minutes of video playback on troubled machine.

**Expected Behavior**
Video should play normally, even when skipping around

**Logs**
FFMpeg output appears normal on Jellyfin server, hls.js is returning a error as seen below:

`main.jellyfin.bundle.js?6722a92df254fd19c303:2 HLS Error: Type: mediaError Details: bufferFullError Fatal: false`

**System (please complete the following information):**
 - Platform: Windows 11 22H2, Dell G5 5590
 - Browser: Chrome M108 (Tested on firefox, works fine on this machine)
 - Jellyfin Version: 10.8.7

**Additional Context**
It would seem this issue has been an occurrence before, since this issue for me appears to be highly transient in nature for repro on other machines I fear it maybe something occurring on my end

**Comment by jithatsonei** [comment]
rel to: PR #2148 Issue #1256

**Comment by Renari** [comment]
I started encountering this today.
