### ISSUE TITLE
[Issue]: Scrolling horizontally is broken in many of the horizontal lists.

### ISSUE THREAD

**Issue by dksilv4** [jellyfin/jellyfin-web#4222]
### Please describe your bug

When interacting with horizontal lists, when the overflow-y is true, the scrolling is quite broken and very unresponsive. 

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Mac OS
- Virtualization: Docker
- Clients: 
- Browser: Chrome, Safari
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thornbill** [comment]
We would need more information about specific examples of the here and how scrolling is broken to be able to attempt to reproduce this. Feel free to open a new issue here with that information and possibly even a screen recording.

**Comment by d86leader** [comment]
I can confirm this. The issue is that if your browser supports two-finger gestures for going backwards and forwards in history, this behaviour will fight with the jellyfin scrolling, producing jumpy scrolls or going through history instead. I will attach a screen recording later.

**Comment by d86leader** [comment]
Here's a recording a friend sent me.

https://user-images.githubusercontent.com/6142210/213209408-13a60a7e-4302-4d6f-b11f-dd7ee3d69407.mp4

1. Horizontal scrolling: you can see how it only scrolls for a couple of frames until the browser gesture takes over
2. Diagonal scroll: for usual web content, diagonal scroll doesn't scroll the horizontal frames, yet here it does. You can also notice that it's janky.
