### ISSUE TITLE
Unable to search by tags

### ISSUE THREAD

**Issue by hkup859** [jellyfin/jellyfin-web#4226]
**Describe The Bug**
I want to preface this with saying I'm a new Jellyfin user and this is probably just an issue with me, but just in case, I'm raising a bug to see if others have this issue. As far as I can tell, Jellyfin supports searching for items by tags. I see multiple references to this ability in prior feature requests/bugs. Basically, I have a new library that has been fully scanned. I edit the metadata on one of the images, specifically the tags, then I try to search by that tag. It does not return anything. I see in the network section in chrome that it looks like 0 records are being returned. I have tried manually refreshing metadata and re-scanning, but it still doesn't work.

Things to note:
* I have 37000+ high resolution photos. This shouldn't make a difference since the query seems to be returning, just without items.
* I have only tested this on photos as that's the only thing I have on jellyfin right now.

**Steps To Reproduce**
1. Update metadata (the tags) on a photo
2. Try to search for that tag.
3. See that no records are returned (no errors, just no records)

**Expected Behavior**
I want tags to be used in searches. When I search for a word that is one of the tags on an item, specifically a photo, it should be returned. Ideally partial matches would work too.

**System (please complete the following information):**
 - Platform: Docker, via Unraid
 - Browser: Chrome
 - Jellyfin Version: 10.8.7

**Comment by bradbeattie** [comment]
A handful of PRs to consider here:

* https://github.com/jellyfin/jellyfin/pull/8842 which implements a quick tag-searching hack. This was merged in and might appear in 10.9.0 (I'm unclear what the process is for pulling in changes from the master branch into subsequent release branches).
* https://github.com/jellyfin/jellyfin/pull/8914 improves the tag searching approach, but has yet to be reviewed. No idea what the timeline is there.
* https://github.com/jellyfin/jellyfin-web/pull/4213 raises the limit of search results from 24 to 240, but hasn't been reviewed and I suspect won't be approved, but without such a change you're going to get a truncated list of results.

**Comment by hkup859** [comment]
@bradbeattie Thanks for these insights! I will keep an eye out for the augmented search with tags in future releases. For what it's worth, I think the amount of records coming back should be user configurable rather than a static field. After the tags in search is released, I may make a PR for the amount being user configurable.

**Comment by bradbeattie** [comment]
@hkup859 Note that with https://github.com/jellyfin/jellyfin-web/pull/4213#issuecomment-1362892692 as a local workaround, you can indeed configure the value. A bit hacky, but it's the solution I'm running with in my environment.

**Comment by hkup859** [comment]
@bradbeattie Unfortunately I use many different clients and implementing a workaround on each would not be feasible. I've been looking for something to work on though and am happy for the challenge of implementing it on different clients (officially).

Good to know! I think I'll keep with the official release, but the unstable docker image could be useful for testing and verifying some things. Thanks again!

**Comment by hkup859** [comment]
On 10.8.8 I still have this error. I see version 10.8.10 is out but I don't see mention of this fix being part of the release. Are these changes in a released version yet?

**Comment by bradbeattie** [comment]
I suspect new features are being held back to 10.9.

**Comment by SAbboushi** [comment]
Running Docker on QNAP QTS (latest JF version as of today's install).  Search does not search tags (Roku, Edge, Chrome)

**Comment by bradbeattie** [comment]
Latest doesn't have it yet. Unstable does.

**Comment by thornbill** [comment]
Yes new features are limited to "minor" version changes (specifically 10.9.0 in this case). Patch version changes (i.e. 10.8.9 -> 10.8.10) only include bug fixes.

**Comment by AnLuoRidge** [comment]
Update: Searching by tags is no longer supported. It is reverted in this [PR](https://github.com/jellyfin/jellyfin/pull/12741).
