### ISSUE TITLE
Showing entries in "next up" section whilst not having watched anything

### ISSUE THREAD

**Issue by TimGels** [jellyfin/jellyfin-web#4227]
**Describe The Bug**
The web client shows a "next up" section with a lot of entries when a new user is created. That user has not watched anything yet and thus should not see the "next up" section on the home page. At minimum it should not show the entries in that section as this is inconsistent behavior (and violates in my opinion some usability heuristics like the `Consistency and standards` heuristic in EUHSA) which can be confusing for users.

**Steps To Reproduce**

1. Create a new user
2. View the homepage
3. The "next up" section is showing a lot of entries

**Expected Behavior**

1. Create a new user
2. View the homepage
3. The "next up" section is not shown (or at least has no entries in it)

**Logs**
N/A

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/43609220/209557095-6b67dafa-7e4b-49b7-a002-f1f95a5ac210.png)

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Firefox
 - Jellyfin Version: 10.8.8

**Additional Context**
It seems that the server provides a parameter in the API to not get "next up" entries back for cases like these. 

We had some discussion about this over at Discord and more people agree that this is unwanted behavior.

This issue seems to have related issues and pr's:

https://github.com/jellyfin/jellyfin-web/pull/2509
https://github.com/jellyfin/jellyfin-web/issues/2430

**Comment by cvium** [comment]
We did at one point disable this but it broke some of the client's that relied on next up data so we rolled it back. It can still be disabled via the settings. This is not a bug.
