### ISSUE TITLE
No homepage thumbnails for books, magazines and photoalbums

### ISSUE THREAD

**Issue by annomatik** [jellyfin/jellyfin-web#4229]
**Describe The Bug**
On the home page of the web client, there are no thumb-nail images for books, magazines and photo albums. Jellyfin can render these media when clicking on the placeholders.

**Steps To Reproduce**

1. Add libraries with either (pdf-)books, (pdf-)magazines or (jpg-)photoalbums.
2. Go to the Jellyfin homepage
3. See, that there are no thumbnails (see screenshot)

**Expected Behavior**

Expected behavior: Jellyfin should show thumbnails

**Logs**

**Screenshots**

![image](https://user-images.githubusercontent.com/28311452/209708111-a58889e8-cd7f-4383-a8ae-b765dedc29af.png)

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Chrome
 - Jellyfin Version: 10.8.8
 
**Additional Context**

**Comment by dmitrylyzo** [comment]
Jellyfin generates thumbnails for "(jpg-)photoalbums" in the "Home Videos and Photos" library.

As for books and magazines, this also should be done on the server side.
