### ISSUE TITLE
Series page only displays one studio when there is more than one

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin-web#4230]
**Describe The Bug**

If a tv series has more than one studio in metadata, only one is displayed.

**Expected Behavior**

All studios should be listed and clickable.

**Screenshots**

![image](https://user-images.githubusercontent.com/991618/209713333-e10be1a4-ce45-4c6c-825e-d38db1e0d285.png)
![image](https://user-images.githubusercontent.com/991618/209713360-742c7d01-e1a5-4316-9c49-d34cd91c9775.png)

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Chrome
 - Jellyfin Version: 10.8.7

**Comment by thornbill** [comment]
Fixed by #4196
