### ISSUE TITLE
Dashboard not updating/refreshing automatically

### ISSUE THREAD

**Issue by jivanpal** [jellyfin/jellyfin-web#4232]
**Describe The Bug**

The dashboard does not automatically update to reflect when libraries are being scanned (and the scanning progress), what content users are viewing (and their playback progress), etc. Manually refreshing the page works around this issue, but some page elements, such as the "i" info button that usually appears beneath a session that is currently streaming content, never appear. This issue does not affect the desktop app (at least the macOS one), it only affects the web app and does so in both Chrome and Firefox (tested on macOS, and in Chrome for Android). It does also affect the "native" Android app (which seems to just use WebView).

**Steps To Reproduce**

1. Open Jellyfin in web browser
2. Log in as an admin.
3. Open sidebar, go to Dashboard.
5. Click "Scan All Libraries". Observe that nothing changes. If you do this from such a broken client whilst also viewing the dashboard in a working client (such as the native macOS app), observe that the working client correctly updates the view.

**Expected Behavior**

The "Scanning Media Library..." element should appear, display scanning progress, and then disappear when scanning is complete.

**Logs**

None.

**Screenshots**

Video demo:
https://user-images.githubusercontent.com/8561591/210011481-64f8b40b-8290-4ab4-b433-916b007765cf.mp4

**System (please complete the following information):**
 - Platform: macOS 10.15.7 Catalina
 - Browser: Chrome 108.0.5359.124, Firefox 107.0.1
 - Jellyfin Version: 10.8.8, native install on Ubuntu 22.04.1

**Additional Context**

I figure it must be a regression somewhere in the Jellyfin 10.8.x series, as this was working for me previously. Can't be sure of exactly which point release I first encountered this issue with, but it was likely 10.8.6.

**Comment by jivanpal** [comment]
Bug still present in version 10.8.10, installed from Jellyfin's Ubuntu repo (package `jellyfin-web 10.8.10-1`, dependency of `jellyfin 10.8.10-1`). This definitely works without issue in both the macOS and Linux (Flatpak) desktop apps. I feel like the bug may be due to one of my plugins, but disabling them all hasn't resolved this. I may be migrating from Ubuntu to Debian soon, and if so I will see if this is reproducible there, and also on a fresh install of Ubuntu.

**Comment by Daivy03** [comment]
I followed your instructions to reproduce the bug, but I could not. I encountered the expected behavior, quote:
> **The Scanning Media Library... element should appear, display scanning progress, and then disappear when scanning is complete**

>[!WARNING]
>I would like to point out that the test was performed on a fresh/clean installation of the latest version of the jellyfin server and the jellyfin media player client

1. the light one on the left is jellyfin-web on Firefox, and the dark one on the right is latest version of jellyfin media player.
>[!NOTE]
>Both firefox browser and jellyfin media player were run on the same windows 11 x64 pc

https://github.com/jellyfin/jellyfin-web/assets/75785698/9cd119ef-84c9-409f-bd2e-d480857ecd17


2. the same test as before but this time i ran the library scan from my jellyfin-android client.

https://github.com/jellyfin/jellyfin-web/assets/75785698/47c46224-568c-48fb-972f-f4403b7c303e



**System:**
 - Jellyfin Server Platform: Debian, Docker
 - Client Browser: Firefox v115.0 Windows 11 x64
 - Jellyfin Version: 10.8.10
 - Client Jellyfin Media Player: v1.9.1 Windows 11 x64
 - Client Jellyfin Android: v2.5.2

> [!NOTE]
> Im runnig Jellyfin-server on docker container.
Docker image: linuxserver/jellyfin

**Comment by jivanpal** [comment]
@Daivy03 Unfortunately I can't watch the two videos in your comment for some reason, but I should be doing that fresh Debian 12 installation sometime soon. I no longer use the MacBook in my original post, but still have to hand so will try testing with it again. As for my current client, that's Chrome or the Flatpak app on Pop OS 22.04 on a Thinkpad T14 Gen1 now, and I experience the issue with *both* of those clients. Must just be a quirk of my setup, I'm hoping it just magically disappears when I migrate the server to Debian.

**Comment by jonmaur** [comment]
I've encountered this issue and I found my way here while searching for a solution.

Quick overview:
- Installed the jellyfin linuxserver docker container on Unraid
- Running a DuckDns, Nginx Proxy Manager reverse proxy setup without my own domain
- I can access my jellyfin server at `http://192.168.1.230:8096` and `https://jellyfin.mydomain.duckdns.org`

I only expirence the refreshing issue when using `https://jellyfin.mydomain.duckdns.org` in a web browser but everything works as expected when I use `http://192.168.1.230:8096`

Hope that helps!

**Comment by thornbill** [comment]
@jivanpal were you also accessing Jellyfin through a reverse proxy when you encountered the issue? This is typically an indication that the websocket connection is not being allowed.

**Comment by jivanpal** [comment]
@thornbill Wow, good catch! Turns out that Nginx was misconfigured, with the block for handling the websockets endpoint not covering the right path; I had written `location /socket/ { ... }` with a trailing slash, [rather than `location /socket { ... }` as given in the documentation](https://jellyfin.org/docs/general/networking/nginx/).

However, this suggests to me that the documentation really ought to use `location = /socket { ... }`, unless Jellyfin uses paths nested under `/socket/` for anything. I say this because `location /socket { ... }` will match any path beginning with `/socket`, such as `/socket1234` and `/sockets/1234`; [see the Nginx docs for more info](https://nginx.org/en/docs/http/ngx_http_core_module.html#location). If both the exact path/endpoint `/socket` and subpaths of `/socket/` are used, then I would recommend either:

1. a regex match, `location ~ ^/socket(/|$) { ... }`; or
2. two `location` blocks for path-matching efficiency, as follows:
  ````
  location = /socket {
    include snippets/jellyfin-websockets.conf;
  }

  location /socket/ {
    include snippets/jellyfin-websockets.conf
  }
  ````

where `snippets/jellyfin-websockets.conf` contains the contents of what would otherwise be a single `location` block.

***

Closing this because my issue is resolved, though. Many thanks!

**Comment by Jandalslap** [comment]
I am having the same issue as OP jivanpal above but my socket location block is correct as per the docs: location /socket/ {...} I thought at first it might be because I forgot to add my base url into the socket proxy pass ie: proxy_pass http://jellyfin:8096/jellyfin/socket; but I have tried with or without base url and it makes no difference. Log does say websocket lost but I have no idea why and I have to refresh the screen to get any current info. What am I missing here?
