### ISSUE TITLE
Music: Expose 'Random' "sort by" option in Albums view

### ISSUE THREAD

**Issue by AndreCarvalho** [jellyfin/jellyfin-web#426]
As per "https://github.com/jellyfin/jellyfin/blob/8985fb8d58c9b968b8e773276d7c3902aa4d55f3/MediaBrowser.Model/Querying/ItemSortBy.cs#L46", this option should be already working in the back-end.
Thanks

**Comment by onny** [comment]
Does this make any sense to have this?
Best regards
Jonas

**Comment by AndreCarvalho** [comment]
Well, for me personally, it does. I used to use Subsonic and it was a very handy way of re-discovering albums I haven't listened in a while. Also, it looks like a low hanging fruit since the backend already supports it (haven't tested it though).
Thanks,
André

**Comment by anthonylavado** [comment]
@jellyfin/web, think this is easy enough to sneak in to 10.4?

**Comment by joshuaboniface** [comment]
@anthonylavado Yea that's fine, I haven't officially announced freeze yet, but let's get it in.

**Comment by AndreCarvalho** [comment]
Hi. Just created a PR for this

**Comment by EraYaN** [comment]
This was closed in #615
