### ISSUE TITLE
Update "Latest {X}" sections to read "Recently Added in {x}"

### ISSUE THREAD

**Issue by Stromwerk** [jellyfin/jellyfin-web#4273]
Updating this labeling would help with translations and make the intention clear in relation to "recently added" vs "new releases".

_This is just a copy of an issue from the Trello roadmap, specifically - https://trello.com/c/THmmXTHu/40-update-latest-x-sections-to-read-recently-added-in-x_

I wanted to add the labels `enhancement` and `good first issue`, however I imagine I don't have the necessary permissions.

**Comment by nielsvanvelzen** [comment]
FYI: If this is renamed in one client it should also be renamed in the others.

**Comment by bhvsh** [comment]
Should I update only this particular string? (will also be updated in en-gb.json as well)
https://github.com/jellyfin/jellyfin-web/blob/cc43f3d46a2fb9c57e8fadac46cda6c92a071a6a/src/strings/en-us.json#L990

Or should I also update the other strings which mentions "Latest" (to "Recently Added")
https://github.com/jellyfin/jellyfin-web/blob/cc43f3d46a2fb9c57e8fadac46cda6c92a071a6a/src/strings/en-us.json#L204
https://github.com/jellyfin/jellyfin-web/blob/cc43f3d46a2fb9c57e8fadac46cda6c92a071a6a/src/strings/en-us.json#L391-L395
https://github.com/jellyfin/jellyfin-web/blob/cc43f3d46a2fb9c57e8fadac46cda6c92a071a6a/src/strings/en-us.json#L506
https://github.com/jellyfin/jellyfin-web/blob/cc43f3d46a2fb9c57e8fadac46cda6c92a071a6a/src/strings/en-us.json#L1468

**Comment by thornbill** [comment]
@bhvsh yes, it looks like all those should be updated
