### ISSUE TITLE
HDR not working in Edge w/ HEVC extensions

### ISSUE THREAD

**Issue by Sawtaytoes** [jellyfin/jellyfin-web#4280]
**Describe The Bug**

When playing HDR content from Jellyfin web, it's transcoding that content instead of sending it to my browser in HDR.

Looks like this (left to right):
- Jellyfin (Edge w/ HEVC extensions)
- Windows 11 Media Player
- Plex (Chrome)

![image](https://user-images.githubusercontent.com/3948069/212186806-9c122f21-3825-4aad-a1f0-383016e08f10.png)

I took this screenshot in SDR mode. In HDR mode, Jellyfin looks the same, but the other two clip as-expected because it's an SDR screenshot:
![image](https://user-images.githubusercontent.com/3948069/212186967-d8605f35-e551-48d1-ac27-47691cc227b7.png)

**Steps To Reproduce**

1. Open Edge in Windows.
2. Go to Jellyfin.
3. Set hardware acceleration to "None" (I have no GPU in this box, and my processor's AVX-512 isn't supported).
4. Click on an HDR10 demo video (h.265 10-bit).
5. Check Playback Info.
6. See transcoding video because of an unsupported format.

**Expected Behavior**

I expect Jellyfin to play HDR content in one of these ways:
- Clipping if I'm in SDR.
- Tone-mapped HDR to SDR.
- Showing in the HDR color space if HDR is enabled in Windows. 

**Logs**

> This video's range type is not supported.
![image](https://user-images.githubusercontent.com/3948069/212187477-d0d6bb17-8876-41ae-a705-962bb875b07b.png)

**Screenshots**

_See above._

**System (please complete the following information):**
 - Platform: Linux x64
 - Browser: Edge w/ HEVC Extensions installed (I paid the $1 to test it out for Jellyfin).
 - Jellyfin Version: 10.8.8
 - CPU: AMD Eypc 7252p

**Additional Context**

This is a new Jellyfin install this week. I'm running it in a Docker container through TrueNAS using the TrueCharts version. I've also modified the resource limitations to 16 threads and 32GB of RAM.

This chart says Edge HDR is supported with the HEVC Extensions which is why I bought them:
![image](https://user-images.githubusercontent.com/3948069/212188098-e90921f2-8931-444e-bee4-42f7ddaa4535.png)

**Comment by dmitrylyzo** [comment]
Does it work if you uncheck the `Allow video playback that requires transcoding` for the user in the Dashboard?

No `hevcVideoRangeTypes` here: https://github.com/jellyfin/jellyfin-web/blob/cf204f0b27c4ac39a4013791c2ae2c6b62fc24eb/src/scripts/browserDeviceProfile.js#L863-L866

**Comment by StaZhu** [comment]
Edge doesn't support PQ HDR tone-mapping well which is a known issue of the browser impl. See this table for more details (https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding#hdr-supports-compared-with-edge--safari).

Chrome supports PQ/HDR tone-mapping well thats why you wasn't facing any issue on Chrome.

**Comment by Sawtaytoes** [comment]
I was having the _same_ issue on Chrome, but I didn't post it because it was shown as unsupported in the docs.

It works in Plex on Chrome, just not Jellyfin. No browser I tested works with Jellyfin.

**Comment by nyanmisaka** [comment]
Edge doesn't browser side tone-mapping at all. So you have to rely on server side tone-mapping.

We currently only support DV/HDR ->SDR tone-mapping with GPU on your server. And CPU based software tone-mapping is WIP.

Chrome does support tone-mapping but it requires this PR: https://github.com/jellyfin/jellyfin-web/pull/4041

**Comment by nyanmisaka** [comment]
Yes. It enables HDR direct play and HEVC transcoding for Chrome.

You can also modify this line to allow HDR in Chrome. https://github.com/jellyfin/jellyfin-web/pull/4041/files#diff-a78ea2803d6a5a5ae575ccbe06597ca3489dd840596c4c7e07b1b9427397364fR883

**Comment by Schaka** [comment]
Thank you, this clarification helped  a lot. I tried the PR locally and it worked. For anyone else looking for a temporary solution - build jellyfin-web locally with #4041

**Comment by brothercheng0924** [comment]
> Yes. It enables HDR direct play and HEVC transcoding for Chrome.
> 
> You can also modify this line to allow HDR in Chrome. https://github.com/jellyfin/jellyfin-web/pull/4041/files#diff-a78ea2803d6a5a5ae575ccbe06597ca3489dd840596c4c7e07b1b9427397364fR883

Hello, I also want to enable HDR direct play for Chrome, but I cannot find the file **src/scripts/browserDeviceProfile.js** in my Synology.
The Jellyfin I am using is installed directly through the SPK file of synology community. 
So what should I do now, I'm sorry I'm a novice in this field.
I'm looking forward to your reply.
