### ISSUE TITLE
Video Type filter 4K won't find movie if version is stored together 

### ISSUE THREAD

**Issue by ThisIsCyreX** [jellyfin/jellyfin-web#4286]
**Describe The Bug**
The "Video Types" filter for 4K won't filter the movie(s) if they are structured as different versions and only show the HD version.

**Steps To Reproduce**
1. Structure your movie with different versions like this:
[Doc: Multiple Versions of a Movie](https://jellyfin.org/docs/general/server/media/movies/#multiple-versions-of-a-movie)
```
Movies
Movie (2021) [imdbid-tt12801262]
├── Movie (2021) [imdbid-tt12801262] - 1080p.mp4
├── Movie (2021) [imdbid-tt12801262] - 2160p.mp4
```
2. Re-scan the library
3. Go to your movie-list and click on the filter-icon
4. Tick the 4K Video Type filter
5. (now the list is empty) - won't show the 4K version
5. HD filter will show the movie

**Expected Behavior**
When ticking the 4K filter, I should see all my 4K movies.
Instead only the "HD" filter works and shows the movie.

**System (please complete the following information):**
 - Platform: Windows 11 22H2
 - Browser: Firefox 108.0.2
 - Jellyfin Version: 10.8.8

**Additional Context**
The 4K filter works if I remove the 1080p version.

**Comment by Bond-009** [comment]
Server issue https://github.com/jellyfin/jellyfin/issues/6609
