### ISSUE TITLE
Bug: Plugin cannot load the configuration normally for the second time

### ISSUE THREAD

**Issue by cxfksword** [jellyfin/jellyfin-web#4290]
**Describe The Bug**
When click same plugin twice, the second time cannot load plugin configuration.

**Steps To Reproduce**
1. Go to `Dashboard -> Plugins`
2. Click on `InfuseSync` plugin
3. Click on left menu `Plugins` go back to plugin list
4. Click on `InfuseSync` plugin again, and this time cannot load plugin configuration

**Expected Behavior**
Plugin can load configuration correctly

**Logs**

**Screenshots**
first click:
<img src="https://cdn.jsdelivr.net/gh/kozalak-robot/assets@main/img/g8s00f.png" alt="g8s00f"/>

second time click:
<img src="https://cdn.jsdelivr.net/gh/kozalak-robot/assets@main/img/tN7q72.png" alt="tN7q72"/>

found that html have two plugin templates with one hidden, and `pageshow` event  do not trigger the second time.
<img src="https://cdn.jsdelivr.net/gh/kozalak-robot/assets@main/img/SCR-20230117-nty.png" alt="SCR-20230117-nty"/>

**System (please complete the following information):**
 - Platform:  Linux docker
 - Browser: Edge/Safari
 - Jellyfin Version: 10.8.7

**Additional Context**

**Comment by thornbill** [comment]
This is probably already fixed in master/unstable since routing has been completely rewritten.

**Comment by cxfksword** [comment]
@thornbill `10.8.9` also has the same issue
