### ISSUE TITLE
Player rewind/fastforward are different

### ISSUE THREAD

**Issue by sazarkin** [jellyfin/jellyfin-web#4308]
**Describe The Bug**
When you fastforward/rewind in browser using shourtcuts [j/l] it goes forward 30 sec but backwards 10 sec

**Steps To Reproduce**
1. Open video
2. Press [l]
3. Goes 30 sec forward
4. Press [j] goes 10 sec backwards

**Expected Behavior**
Should it be the same?
https://github.com/jellyfin/jellyfin-web/blob/68b69ee0c374e2754684d4afaaab54991a6c76a3/src/components/playback/playbackmanager.js#L3476

https://github.com/jellyfin/jellyfin-web/blob/68b69ee0c374e2754684d4afaaab54991a6c76a3/src/components/playback/playbackmanager.js#L3488

In the code it looks the same.

**System:**
 - Platform: Linux
 - Browser: Firefox
 - Jellyfin Version: 10.8.9

Feel free to close if its expected

**Comment by dmitrylyzo** [comment]
They are configurable in the settings (Profile / Playback).
