### ISSUE TITLE
[Issue]: bundle fails to load after refresh in browser

### ISSUE THREAD

**Issue by hasezoey** [jellyfin/jellyfin-web#4315]
### Please describe your bug

Since a few weeks ago (in unstable) jellyfin's webinterface seems to fail to load until doing a hard-refresh (`/`, `/web/` and `/web/#/home.html`, or any in a library) and fails right after again when doing a normal refresh (after a hard-refresh)

Note: jellyfin is running behind nginx, but without buffering (and from what i know also no caching, only handling ssl and setting some headers, the same headers as in [jellyfin's nginx guide](https://jellyfin.org/docs/general/networking/nginx/))
Note: opening jellyfin directly in a new browser (for example a private window) does not have the issue for whatever reason

---

jellyfin seems like it wants to load the file `90248.bundle.js?0091aeea91c98f00a90f`, which does not exist and after a hard-refresh it only loads `24587.bundle.js?49990ec49236df6df894`, but doing a normal refresh right after again will try to load the other (non-existend) file

### Jellyfin Version

Other

### if other:

jellyfin/jellyfin:unstable@sha256:4c64a5b24f84fdcb65283a8c7910a3db98c2b60eb197267c262401fa24b92a99

### Environment

```markdown
- OS: Manjaro 22.0.1
- Virtualization: docker
- Clients: Browser
- Browser: firefox 109.0
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking: host
- Storage: bind (for media and config), volumes otherwise
```

### Please attach any browser or client logs here

```txt
Loading failed for the <script> with source “https://jellyfin.url/web/90248.bundle.js?0091aeea91c98f00a90f”. [web:1:1](https://jellyfin.url/web/#/home.html)
```
or reloading after a hard-refresh:
```txt
GET https://jellyfin.url/web/90248.bundle.js?0091aeea91c98f00a90f [HTTP/1.1 404 Not Found 2ms]
Loading failed for the <script> with source “https://jellyfin.url/web/90248.bundle.js?0091aeea91c98f00a90f”. [web:1:1](https://jellyfin.url/web/#/home.html)
```

### Please attach any screenshots here

![init](https://user-images.githubusercontent.com/10911626/215636657-bc8d7e00-a30e-4388-90a0-a4a2a10689cb.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hasezoey** [comment]
just tested jellyfin `jellyfin/jellyfin:latest@sha256:9c03191ab57d5b97385becaa271714211eb59e3c6fc2e052a438f97999b781e3` (`jellyfin/jellyfin:latest`) and that works without this issue - could it maybe be related to some plugin not working correctly?

<details>
<summary>Installed plugins</summary>

```txt
[12:18:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AniList 5.0.0.0
[12:18:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Cover Art Archive 7.0.0.0
[12:18:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TheTVDB 9.0.0.0
[12:18:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb 10.8.9.0
[12:18:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Studio Images 10.8.9.0
[12:18:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.8.9.0
[12:18:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.8.9.0
[12:18:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.8.9.0
```

</details>

**Comment by AlexEmashev** [comment]
Experience same issue, but have different file: `main.jellyfin.bundle.js?ba0eba4f8e459eb7c494`

Server: Windows PC
Version: 10.8.9
No HTTPS.
Reproduced with Nginx as a reverse proxy as well as direct connection to 8096.
Tried on different devices, like iPad and MacOS.

The issue is goes away as soon as I connect to the Internet from my phone via LTE (before it was my home router). When I switch back to the router issue reappears but loading not entirely stuck, just becomes much longer.

It seems like Swiftfin runs into the same issue. On connection through my home router the app shows a black screen.

Don't know. May be my provider is blocking some resource? Or cached some file.
The only file I see on the Network tab that is served not from my domain is cast_sender.js

I'll try to install newer version.

**Comment by cg219** [comment]
I've run into the same issue. It seems like whatever router is setup in Jellyfins docker image doesn't like wuery strings. Trying to load the bundle without the cachebust `?adasdad`, it finds the file correctly
