### ISSUE TITLE
On mobile rewind button is not visible

### ISSUE THREAD

**Issue by OnkarRuikar** [jellyfin/jellyfin-web#4319]
On mobile rewind and fast forward buttons are hidden for audio. But for video the buttons are visible.
Music does not need rewind but audio books could really use it. Most often I have to rewind audio books to repeat last sentence or technical terms due to difficulty in understanding it first time or due to distractions. On mobile devices the progress bar is already very short so seeking back to right spot is a very tedious task.
It would be really helpful if the rewind button is brought back for mobile devices.

## Expected Behavior
Rewind button to be available for audio files on mobile. It can also be put behind an option to enable the feature so that normal users won't see it.

## Screenshots
![bug](https://user-images.githubusercontent.com/87750369/215932144-6604a116-17cc-4193-8133-315ee1e4a079.png)

## System
 - Platform: Linux Ubuntu
 - Browser: Chrome(mobile)
 - Jellyfin Version: 10.8.8

## Additional Context
- The PR #1430 disabled the buttons for both audio and video.
https://github.com/jellyfin/jellyfin-web/commit/74d32d3cbd5cbe6e2845317cc9d92ed733813570#diff-1547f7efd3dc63c0593db262c29010a576d94029f375dd5ad1f441d54c7b9634R296

- Then PR https://github.com/jellyfin/jellyfin-web/pull/1812 brought them back for video but not for audio.

**Comment by OnkarRuikar** [comment]
Temporary monkey patching can be done in local server by running:
```bash
$ sed -i 's/D(n.querySelector(".btnRewind"),m)/D(n.querySelector(".btnRewind"),null!=l)/g' /usr/share/jellyfin/web/playback-queue.aae448fcf820512c8c53.chunk.js 
```
Note: the random number `aae448fcf820512c8c53` in the file name can be different for you.


After hard refreshing the page on browser it starts showing the rewind button :smile:  
![gptError](https://user-images.githubusercontent.com/87750369/215956307-e4bb42ac-679a-43f1-bd2f-0f8848e05b3d.png)

**Comment by dmitrylyzo** [comment]
Audiobooks probably don't need `Repeat` and `Shuffle` (_I could be wrong_), so they can be replaced with `Fast-forward` and `Rewind` like for movies.
https://github.com/jellyfin/jellyfin-web/blob/ec175a39f1028e7fcb758f17507c6c92d3d87bb3/src/components/remotecontrol/remotecontrol.js#L328-L335
The only question is, does audiobook has its own type?

**Comment by OnkarRuikar** [comment]
> The only question is, does audiobook has its own type?

I think it does:
https://github.com/jellyfin/jellyfin-web/blob/ec175a39f1028e7fcb758f17507c6c92d3d87bb3/src/components/itemHelper.js#L204-L211

**Comment by FireGamer3** [comment]
I think at some point this was addressed but was not referenced by a PR (screenshot is of current master branch)
![image](https://user-images.githubusercontent.com/18491002/232247770-ef0fb9db-a11d-4ebd-be87-da6c4c5f27ff.png)

**Comment by Poltergeisen** [comment]
I'm not seeing this button on a note 20 ultra phone. How can I fix this? Should this be re opened?
