### ISSUE TITLE
User settings can't be accessed

### ISSUE THREAD

**Issue by Shadowghost** [jellyfin/jellyfin-web#4341]
**Describe The Bug**
When trying to edit the user settings, you just get a loading screen.

**Steps To Reproduce**
1. Go to the admin panel
2. Try to edit any user

**Expected Behavior**
Load the user settings.

**Comment by thornbill** [comment]
I still haven't been able to replicate this one for some reason. I have been trying the latest master of web running in the dev server connecting to an unstable docker container for the server.

Have you updated your npm dependencies recently? (I'm grasping at straws :sweat_smile:)

**Comment by Shadowghost** [comment]
Fixed by one of the recent SDK updates.
