### ISSUE TITLE
Media Session Info incorrect, not exposed on Firefox

### ISSUE THREAD

**Issue by dadosch** [jellyfin/jellyfin-web#4353]
**Describe The Bug**
Media Session API provides the Operating System with Info about what is currently played, as well as controls to seek, play, pause etc.

On Chromium, when something is playing in jellyfin-web, the name of the type of media (i.e. "Music") is exposed, as well as another session with the correct title and author of the current playing song. 

![Screenshot_20230213_193139](https://user-images.githubusercontent.com/12801390/218544404-6b892578-2190-408d-889f-13f34968cf33.png)

On Firefox, it seems as if no Media Session Info is exposed, as no currently playing media is reported by the OS/DE (note, with other Media playing websites it works fine)

**Steps To Reproduce**
Open jellyfin-web, see current playing in OS/DE.

**Expected Behavior**
Media Session Info should display info about current playing media.

**Logs**

**Screenshots**

**System (please complete the following information):**
Jellyfin-Version: 10.8.8
Firefox 109.0.1 (64-Bit)
Chromium Version 110.0.5481.77 (Official Build) Arch Linux (64-bit)

**Additional Context**

**Comment by dmitrylyzo** [comment]
Could you open DevTools in Firefox and check `navigator.mediaSession` in the console?

I saw such behavior when used Snap version of Firefox. Moved to Mozilla PPA.

**Comment by dadosch** [comment]
Indeed, there was something wrong with my Firefox setup: Somehow the plugin for connecting to the DE got disabled, and thus the media information didn't get forwarded, and about the second media item in Chromium: it seems to be a function of Chromium afaict, to expose a media control thing for the tab where media is playing, in addition to what the website says. So, sorry for the noise 😅
