### ISSUE TITLE
Add more codec-checkboxes to V4L2 

### ISSUE THREAD

**Issue by RicardoCst** [jellyfin/jellyfin-web#4409]
Currently the options VP9, HEVC and such arent allowed, even though other boards are supporting VP9 like the linux-meson decoder. 
![image](https://user-images.githubusercontent.com/78567799/224636833-876f724c-9a07-42eb-bcb5-9bbdaff27765.png)

**Comment by thornbill** [comment]
Feature requests belong on https://features.jellyfin.org
