### ISSUE TITLE
Broken link to subtitles help

### ISSUE THREAD

**Issue by jameskimmel** [jellyfin/jellyfin-web#4410]
**Describe The Bug**

Broken link to subtitles doc.
**Steps To Reproduce**

1. Go to any product
2. Click on edit subititles
3. Click "help" on the top right
4. points to https://jellyfin.org/docs/general/server/media/subtitles.html which is no longer active

**Expected Behavior**

Remove help or update link

**Comment by charlie-gray** [comment]
I was unable to reproduce this error. When I tried clicking on the help button, I was redirected to [https://jellyfin.org/docs/general/server/media/external-files/](https://jellyfin.org/docs/general/server/media/external-files/). Could you walk through exactly which steps you took to produce the bug. Thanks and apologies in advance if I'm missing something (I'm very new to this project & open source in general).

**Comment by jameskimmel** [comment]
![vlcsnap-2023-03-16-15h38m55s242](https://user-images.githubusercontent.com/17176225/225652061-82370f0f-fbbe-4c1c-b79e-da5c0a888648.png)
![vlcsnap-2023-03-16-15h39m09s342](https://user-images.githubusercontent.com/17176225/225652070-2893cfa6-03b0-478b-af18-e468195d41ea.png)
![vlcsnap-2023-03-16-15h39m25s550](https://user-images.githubusercontent.com/17176225/225652077-7204741d-964f-4cfb-9c4c-95b038c94281.png)

**Comment by jameskimmel** [comment]
Server is 10.8.9 under linux and player is just the webpage in Firefox
