### ISSUE TITLE
On web client, films with no specified background image show the background image from another film

### ISSUE THREAD

**Issue by emes81** [jellyfin/jellyfin-web#4436]
To reproduce:

1. Place several film files in one folder
2. Create a Jellyfin library rooted to the folder from step 1, enable and run image retrieval. Wait til all films have been identified
3. For films for which no background image is found, an unrelated background image will be taken 

Preferable would be to show no background image at all, or to show a default (possibly user-defined?) background image.

**Comment by thornbill** [comment]
Could you provide a more detailed example of what the folder structure looks like? Thanks!

**Comment by emes81** [comment]
Omitting the jpgs and nfos for simplicity's sake:

`
├── media/
│   ├── films/
│   │   ├── film1/film1.mkv
│   │   ├── film2/film2.mkv
│   │   ├── film-a.mkv
│   │   ├── film-b.mkv
`

So, with some films in subfolders and others with the mkv directly in the films folder. In my use case, this is required as the files are shared (archive.org etc) and I cannot change the names/folder structures.
