### ISSUE TITLE
cant find exe

### ISSUE THREAD

**Issue by hagi1422** [jellyfin/jellyfin-web#445]
**Describe the bug**

cant find  jellyfin.exe
**To Reproduce**

**Expected behavior**

**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Docker, Debian, Windows]
 - Browser: [e.g. Firefox, Chrome, Safari]
 - Jellyfin Version: [e.g. 10.0.1]

**Additional context**

**Comment by anthonylavado** [comment]
Hi @hagi1422, this repo "jellyfin-web", is only the web interface. The main server is at https://github.com/jellyfin/jellyfin, and you can get downloads from our [Docs](jellyfin.readthedocs.io).

If you need Windows, go here: https://jellyfin.readthedocs.io/en/latest/administrator-docs/installing/#portable-binaries
