### ISSUE TITLE
Book (epub) do not show sub-entries in the table of contents

### ISSUE THREAD

**Issue by carif** [jellyfin/jellyfin-web#4486]
**Describe The Bug**
A book in the ePub format can have a hierarchical structure of chapters with sub-chapters etc. Those sub-chapters do not appear in the table of contents view in Jellyfin. Only the top-level chapter's get displayed.
In the screenshot section are some screenshots of an example file to illustrate the problem (Jellyfin vs Calibre). But really, any chapter names and chapter-structure has those problems. I could've move some chapters to the top level and added sub-chapters to them, too, e.g.:
```
Cover
Made in Abyss 08
- Chapter 01
- Chapter 02
Side Story
- Chapter 01
- Chapter 02
```

**Steps To Reproduce**
1. Go to your book library.
2. Click on a book to open it. It has to be an ePub file with sub-chapters!
3. Click on the button for the table of contents.

**Expected Behavior**
Show a list of all chapters. 

**Screenshots**
The problem:
![image](https://user-images.githubusercontent.com/9168045/230984858-97eb6bc9-5d1d-4d38-88b1-067f6e648dc9.png)
How it should look like (image from calibre):
![image](https://user-images.githubusercontent.com/9168045/230984975-2c905970-015b-4d47-8b4f-3e1d116ad198.png)

**System (please complete the following information):**
 - Platform: Fedora Linux
 - Jellyfin + Jellyfin Web Version: 10.8.9

**Comment by vincent** [comment]
How the nested chapters should be displayed ?

I saw some readers flatten the list, making all chapters to appear on top-level.
If they are shown as a tree, should we fear about stupidly-deep nesting ?

Also, atm the font size is recursively bigger, caused by a `font-size: 120%`

![image](https://github.com/jellyfin/jellyfin-web/assets/5623/10337cdb-a657-45b7-b831-ff3525f9d850)

**Comment by vincent** [comment]
Here is a first proposal, open for any feedback.

![image](https://github.com/jellyfin/jellyfin-web/assets/5623/2829df5f-7862-43c5-a54b-2bc0a5ab7564)

**Comment by carif** [comment]
> Here is a first proposal, open for any feedback.

I would probably make the "Chapters" and "Part One" things bold to make it a bit easier on the eyes. I'm not sure what other eBook Readers do here, but Apple makes them bold and the Sections and Sub-sections normal and it looks really nice.  


> I saw some readers flatten the list, making all chapters to appear on top-level.
> If they are shown as a tree, should we fear about stupidly-deep nesting ?

Flattening would be an option, but it would make it harder to understand which sub-chapter relates to which chapter. Regarding the question whether we should fear about studiedly-deep nesting. In theory yes, in practice, all the books I've ever seen go at max to the sub-section depth of your first proposal.
