### ISSUE TITLE
Manga reader zoomed in, cant fit to screen

### ISSUE THREAD

**Issue by Crylia** [jellyfin/jellyfin-web#4508]
### Describe the bug

When I try to read a manga on my phone its zoomed in so the page isn't fully viewable, if I try to zoom out it zooms back in.
It seems like its fixed to the manga height, which cuts off the right side.

### Application version

2.4.4

### Where did you install the app from?

Google Play

### Device information

Samsung Note 10

### Android version

Android 10

### Jellyfin server version

Jellyfin.Server 10.8.9.0

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by alexe0336** [comment]
Could you send a video of the issue?

**Comment by Crylia** [comment]
> Could you send a video of the issue?

https://github.com/jellyfin/jellyfin-web/assets/50151522/5617b00f-14e6-408d-8673-70b638563c13

As you can see it's not possible to get the page fully displayed so it's readable. And it sometimes clips off to the last page is visible too
