### ISSUE TITLE
UI not allowing to go anywhere after pressing jellyfin's back button in `/queue`

### ISSUE THREAD

**Issue by hasezoey** [jellyfin/jellyfin-web#4520]
**Describe The Bug**

**Steps To Reproduce**
1. go to `/web/#!/queue` while nothing is playing
2. do a hard refresh (firefox CTRL+SHIFT+F5)
3. click jellyfin's "back" button
4. observe nothing happing
5. try other buttons (like "home")
6. observe also nothing happen

now try to re-hard refresh and click "home" first, observe it working this time

**Expected Behavior**
being able to use other buttons if one fails

**Logs**
no errors

**Screenshots**

**System (please complete the following information):**
 - Platform: Linux
 - Browser: firefox
 - Jellyfin Version:10.8.9

**Additional Context**

PS: this issue was posted before it was finished, accidentally hit "enter" while the text-box was not focused

**Comment by hasezoey** [comment]
can confirm, this is still a issue in `10.8.10`

**Comment by alfred-delacosta** [comment]
Hi @hasezoey 

When I visit the `/web/#!/queue` route, I end up with "Cannot GET" error:
![image](https://github.com/jellyfin/jellyfin-web/assets/132242610/8b81669c-3f9b-4962-ab5a-31c7bb3deba2)

If I visit `/#/queue`. I get the following page:
![image](https://github.com/jellyfin/jellyfin-web/assets/132242610/af83f5c5-6235-4a19-9fb5-88439e30e1d0)

Is that the page you are referencing? 
If so, which back button are your trying to press? The green, red, or blue arrow?
![image](https://github.com/jellyfin/jellyfin-web/assets/132242610/939f177f-9c68-4530-9350-1544d4bbcf54)

**Comment by hasezoey** [comment]
> When I visit the /web/#!/queue route, I end up with "Cannot GET" error:

what version are you running or reverse-proxy settings are you using? because i am still running `10.8.11`(current latest stable in docker) and can visit the page at `/web/#!/queue`

for context, i am using nginx for subdomain management (ie `jellyfin.server`), but the config is the same as [jellyfin suggests in the documentation](https://jellyfin.org/docs/general/networking/nginx/#nginx-from-a-subdomain-jellyfinexampleorg)

if i try to go to `/#/queue`, then i get redirected to `/web/#!#/queue`, which leads me to a blank page, removing the ending `#` and doing a hard-refresh brings me back to `/web/#!/queue`

>  If so, which back button are your trying to press? The green, red, or blue arrow?

sorry if i was not clear, i mean the "red arrow"

---

for context, the following is how the page looks for me, if nothing is running (even on bigger screen)
![Screenshot 2023-10-04 at 17-45-00 Jellyfin](https://github.com/jellyfin/jellyfin-web/assets/10911626/a8a68627-74da-4c78-b153-33f2098abef3)

**Comment by alfred-delacosta** [comment]
Ah that's my problem. I have been testing the Jellyfin Web client on a 10.8.9 server. Let me get the newest server code spun up and I will give this another shot. Thanks for the information!

**Comment by alfred-delacosta** [comment]
I am experiencing some major issues getting my server setup on my computer. I will not be able to work on this bug.

**Comment by hasezoey** [comment]
still a problem in jellyfin `10.8.13` (latest docker)

**Comment by hasezoey** [comment]
can confirm this issue has been fixed since may last comment and `10.9.7`(docker)
