### ISSUE TITLE
Volume slider generates hundreds of Playback requests

### ISSUE THREAD

**Issue by sachk** [jellyfin/jellyfin-web#453]
**Describe the bug**
A progress request is sent by the browser for each fractional movement of the volume bar. This blocks requests for new HLS chunks, slowing down playback.

**To Reproduce**

1. Play anything
2. Open developer tools
3. Move the volume bar
4. See all the progress requests being made

**Expected behavior**
Progress requests are only sent when the volume control stops being moved or aren't sent when volume is changed (I can't think of why the server needs to know the clients volume, but perhaps it's necessary)

**Screenshots**
[Gif of the problem (had to censor personal information)
](https://gfycat.com/inexperiencedtamebelugawhale)

**System (please complete the following information):**
 - OS: Debian 10
 - Browser: Chrome
 - Jellyfin Version: 10.3.7
 - Reverse proxy: Built in SSL Support

**Comment by redSpoutnik** [comment]
This is caused by "mousemove" and "touchmove" volumeSlider's event listeners in videoosd.js, they are triggered for every increment when moving the slider.

I don't know why those two listeners have been set.

I tested to remove them and the "change" listener was enough (triggered only on mouse or touch release) on Chrome, Firefox and Brave.

**Comment by anthonylavado** [comment]
Cc @dkanada, I remember he had some thoughts on why this was the case

**Comment by dkanada** [comment]
This was last modified by @sparky8251 because he felt the change listener wasn't responsive enough, which is a valid point. The two solutions are to either revert back to change or add a time delta check to limit the requests to one per second or something.
