### ISSUE TITLE
Playback error after upgrading to 10.8.10

### ISSUE THREAD

**Issue by rpcsilva** [jellyfin/jellyfin-web#4532]
**Describe The Bug**
Some files which were previously playing now result in a playback error ("This client isn't compatible with the media and the server isn't sending a compatible media format.")

**Media Information**

**Screenshots**
![image](https://user-images.githubusercontent.com/6306787/234038026-04ab42b5-bb98-4e08-987c-db3c829ce29c.png)

**System (please complete the following information):**
 - Platform: Linux, Mint
 - Browser: Firefox, Chromium
 - Jellyfin Version: [e.g. 10.8.10]

**Additional Context**
Can't play any movie, listen to music or see any pictures

**Comment by Ritchie1108** [comment]
turn off the fmp4 option

**Comment by rpcsilva** [comment]
where can I find fmp4 option?

**Comment by maks2204** [comment]
After last update, H265 media now transcoding on chrome browser.
![image](https://user-images.githubusercontent.com/5091505/234332361-b50ce838-b946-4c43-8951-e49294d75d50.png)

windows 11, chrome 112.0.5615.138, jellyfin 10.8.10

**Comment by rpcsilva** [comment]
thank you 
it's solved after reinstall

**Comment by asavageiv** [comment]
This is happening for me too.
Debian Bookworm
Jellyfin 10.8.10-1 

Let me know what logs to provide.

**Comment by Ritchie1108** [comment]
> where can I find fmp4 option?我在哪里可以找到 fmp4 选项？

webui, top right corner, setting-playback

**Comment by asavageiv** [comment]
toggling fmp4 did nothing for me

**Comment by asavageiv** [comment]
reinstalling and using Firefox also did not help

**Comment by rb0135** [comment]
Hi All, I have the same Playback Error issue and narrowed it down to a Library with NO subdirectories, although a Library with sub-directories, with the same files, works perfectly. The error occurs on Shuffle of the Library or if I make a Playlist of the library.

To explain further.
1) I have a library of Music Videos, with various subdirectories of different types of music videos (MP4 or MKV files only), one of those directories is called Assorted. If I shuffle this library, or create a Playlist, all videos play perfectly, and do play the videos in this Assorted directory.
2) I create a Library pointing directly to the Assorted directory (mentioned above) so it only contains those individual files (about 100 files). As soon as I try to Shuffle or play a created playlist from this library, I get the Playback Error.

I hope this information helps.

**Comment by rpcsilva** [comment]
thank you but it's solved after reinstall
never happened again

**Comment by rpcsilva** [comment]
solved after reinstall
