### ISSUE TITLE
Jellyfin listens for input from controllers even when the 'Enable Gamepad' setting is disabled. 

### ISSUE THREAD

**Issue by Pouncingkitten** [jellyfin/jellyfin-web#4580]
Jellyfin currently listens for input from controllers even when the _Enable Gamepad_ setting is disabled. 

I have a wireless (dongle, not bluetooth) xbox controller which uses the [xone] kernel driver. When the controller is turned on Jellyfin responds to input from it. This makes it impossible to use Jellyfin whilst playing a game, or doing something else which uses a controller. 

Server version: 10.8.10

I have not used a controller for more than a few weeks so I don't know if this occurs in previous versions as well.

**Comment by vickyorlo** [comment]
Is this really completed? I'm still expericing this exact issue. Enable Gamepad is off, but my DualSense (via bluetooth) still controls stuff. D-pad left opens search,d-pad down goes back to main menu, circle button skips to next episode, triggers seem to contro the volume... Even when the window is not in focus. Steam Input's desktop configuration is disabled.

**Comment by JasonInOttawa** [comment]
Same here. Enable Gamepad is off, Bluetooth Dualsense still controls Jellyfin even when the window doesn't have focus. I'm running up-to-date software.
