### ISSUE TITLE
Bug: non-english subtitle does not show correctly in Android Chrome

### ISSUE THREAD

**Issue by davidngrc** [jellyfin/jellyfin-web#4602]
Jellyfin Version: 10.8.10

I had movie
The Meg (2018)

I then login Jellyfin UI as admin, and add subtitle for above movie
Step 1, click the above movie
Step 2, click the 3 dot -> Edit Subtitle -> Search -> Chinese -> click search
Step 3, download this subtitle "The.Meg.2018.1080p.BluRay.x264-[YTS.AM]" , Format: srt
Step 4, subtitle downloaded.

Subtitle looks normal in
Firefox v112.0.2 (64bit) snap for Ubuntu
Chromium v113.0.5672.63 (Official Build) snap (64-bit)  for Ubuntu
Firefox v112.2.0 for Android
Kiwi Browser v112.0.5615 for Android

Subtitle garbled in
Chrome v113.0.5672.76 for Android

**Comment by Ritchie1108** [comment]
enable fallback fonts
font files are arranged from small to large

**Comment by davidngrc** [comment]
It work, thank you.
Below are the procedure.

1. sudo apt install fonts-noto-cjk
2. dpkg -L fonts-noto-cjk
3.  enable the fallback font in Jellyfin dashboard and point to /usr/share/fonts/opentype/noto

**Comment by hoonlight** [comment]
Comparing the two logs, here are the differences that seem relevant to me.

```
# Jellyfin 10.9.0

"LocalizedExternal": "\uC678\uBD80",
"LocalizedHearingImpaired": "\uCCAD\uAC01 \uC7A5\uC560",
"DisplayTitle": "\uC77C\uCE58\uD558\uC9C0 \uC54A\uC74C - ASS - \uC678\uBD80"

# Jellyfin 10.0.8

"LocalizedExternal": "External",
"DisplayTitle": "\uC77C\uCE58\uD558\uC9C0 \uC54A\uC74C - ASS - External"
```
