### ISSUE TITLE
Movies do not wrap when searching 

### ISSUE THREAD

**Issue by mobergmann** [jellyfin/jellyfin-web#4603]
**Describe The Bug**
if you search for movies and have more hits than fit your screen width, the elements that overlap are cut off. You cannot scroll to view the remaining elements.

**Steps To Reproduce**

1. Enter a search term, which has many hits
2. Shrink your browser window
3. Only see a few results

**Expected Behavior**
The overflowing search results should warp into the next line.

**Screenshots**
![Screenshot 2023-05-14 at 21-05-42 Jellyfin](https://github.com/jellyfin/jellyfin-web/assets/23003549/28d3ff2b-123a-4d9f-aadd-dadc74fc594d)

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Firefox and Brave
 - Jellyfin Version: 10.8.10

**Comment by thornbill** [comment]
This is intended functionality. When you search, different categories of items are displayed in the results. Each category is displayed as a separate, horizontally scrolling section. Below is an example showing movies, episodes, and songs.

![image](https://github.com/jellyfin/jellyfin-web/assets/3450688/9951412b-c008-4aa9-9f8b-6d2a251b10db)

**Comment by mobergmann** [comment]
@thornbill 
> This is intended functionality. When you search, different categories of items are displayed in the results. Each category is displayed as a separate, horizontally scrolling section. Below is an example showing movies, episodes, and songs.
> 
> ![image](https://user-images.githubusercontent.com/3450688/238812668-9951412b-c008-4aa9-9f8b-6d2a251b10db.jpeg)

But I don't see a vertical scrollbar. I can't even scroll with my vertical mouse wheel. Am I missing something?

**Comment by thornbill** [comment]
I don't think you are. I believe the search you are running is probably only returning movie results. Try searching for something that should be more common like "th" and see what is returned.

**Comment by mobergmann** [comment]
That is not really the point of me. I cannot scroll trough the list of movies. I have all Harry Potter Movies, but only three get shown. If i increase the screen size, I can see a overflowing Harry Potter movie. When I add the `vertical-wrap` class, all movies get shown. If I search on the jellyfin app on my smartphone, I can scroll. 

If wrapping the results is not intended, I would instead suggest adding a scrollbar, to enable scrolling and hint the user, that he/she has more movies, than shown in the results.

**Comment by mobergmann** [comment]
Okay, I did a new install (to enable hardware trans coding) and now I see arrows for scrolling.
