### ISSUE TITLE
Live TV loading stream very slow

### ISSUE THREAD

**Issue by andreacocci95** [jellyfin/jellyfin-web#4637]
**Describe The Bug**
Hi, I installed jellyfin on my home server with docker. I added to jellyfin a m3u link with some channels that works (I tried with other players) and they are been loaded successfully. When I try to reproduce a channel stream, I need to wait more than 1 minute after the player show me the stream.

**Steps To Reproduce**
1. Add a m3u URL under LiveTV (this is the link that I use https://github.com/Tundrak/IPTV-Italia/raw/main/iptvitaplus.m3u)
2. Go to LiveTV -> Channels and try to reproduce for example the first channel
3. You need to wait a long time before the stream start (more than one minute)

**Expected Behavior**
I'm expected to see a really speed loading of channel stream (like other players).

**System**
 - Platform: Linux
 - Browser: Firefox
 - Jellyfin Version: 10.8.10

**Additional Context**
Another problem is: some channels, after the long loading, doesn't reproduce the audio (in the m3u URL that I given is, for example, "Canale 5"). In other players the audio works well, why here not?

**Comment by marciglesias17** [comment]
I have the same problem, does anyone have any recommendation to solve the problem? When I start a channel it takes about 10 seconds, instead, I connect the m3u list in an IPTV app directly on my Android TV and the programs start almost instantly.
