### ISSUE TITLE
"Enable backdrops" doesn't effect backdrop display

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [jellyfin/jellyfin-web#465]
**Describe the bug**
If you attempt to disable backdrops, the checkbox in Display doesn't do anything

**To Reproduce**
1. Try to disable backdrops via Display settings

**Expected behavior**
Backdrops should be enabled or disabled based on the checkbox

**Comment by grafixeyehero** [comment]
The reason why this happening that in itemdetailpage the backdrop doesn't pass through the checking point. 
there are two background file one is autobackdrop and the other is  backdrop. the checking was made in atuobackdrop and pass to backdrop. from itemdetailpage it only pass through backdrop.
here is the example if you remove this code u will see the result
https://github.com/jellyfin/jellyfin-web/blob/79cd6a75523f250f3fc428e3194105708ccf9911/src/controllers/itemdetailpage.js#L524-L525

**Comment by dkanada** [comment]
@grafixeyehero I suppose the proper fix would be to remove the backdrop call in the item details page? This has actually been bothering me for ages, glad someone finally looked into the problem.

**Comment by grafixeyehero** [comment]
if we remove this when user enable the backdrop it will get random backdrop. so for itemdetailpage i will set to clear backdrop.
