### ISSUE TITLE
[Issue] Caching issues when connected via Reverse Proxy (Caddy) preventing login

### ISSUE THREAD

**Issue by Lyamc** [jellyfin/jellyfin-web#4651]
When using a reverse proxy:
1. Connect to the server and login
2. Close the tab
3. Connect to the server
4. CTRL+SHIFT+R to Hard Reload

```
Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://example.com/web/RootApp.tsx","status":404}]
    at g._handleInstall (https://example.com/web/serviceworker.js:1:34195)
    at async g._handle (https://example.com/web/serviceworker.js:1:33610)
    at async g._getResponse (https://example.com/web/serviceworker.js:1:32702)
_handleInstall @ serviceworker.js:1
setTimeout (async)
(anonymous) @ serviceworker.js:1
cachePut @ serviceworker.js:1
_handleInstall @ serviceworker.js:1
await in _handleInstall (async)
_handle @ serviceworker.js:1
await in _handle (async)
_getResponse @ serviceworker.js:1
await in _getResponse (async)
handleAll @ serviceworker.js:1
(anonymous) @ serviceworker.js:1
await in (anonymous) (async)
f @ serviceworker.js:1
install @ serviceworker.js:1
```

It fails loading RootApp.tsx
<img width="1256" alt="Screenshot 2023-05-27 at 11 51 21 AM" src="https://github.com/jellyfin/jellyfin/assets/10787681/b3fd325e-14d4-407f-8034-d4435e3e76ab">
<img width="1256" alt="Screenshot 2023-05-27 at 11 56 07 AM" src="https://github.com/jellyfin/jellyfin/assets/10787681/ae2b70dc-6a34-403d-97a0-0bc23957746f">

## Jellyfin Version
Jellyfin.Server 10.9.0.0

## Environment
- OS: Ubuntu Jammy
- Linux Kernel: Linux media 6.2.9-1-pve
- Virtualization: LXC (Proxmox)
- Clients: Android app, Web app
- Browser: All browsers
- FFmpeg Version: ffmpeg version 4.4.1-3ubuntu5
- Playback Method: n/a
- Hardware Acceleration: n/a
- GPU Model: n/a

##Symptoms
The App will always fail to connect to the media server unless the App Data is deleted.
The Webpage will not proceed past the "Jellyfin" splash screen.

**Comment by KrzaQ** [comment]
I'm having the same issue, have you found a workaround maybe?

**Comment by Lyamc** [comment]
@KrzaQ You can temporarily work around it with a hard reload CTRL + SHIFT + R or CMD + SHIFT + R for the Mac.

You can also do that by opening up the Dev Tools and then you can Right-Click the Refresh button and get a dropdown option.

For phone apps, I found that you have to close the app, clear data from the app, and then you'll be able to login

**Comment by KrzaQ** [comment]
Ctrl+Shift+R worked for me. That being said, I just downgraded jellyfin-web to 10.8.3 and the issue went away.

**Comment by satmandu** [comment]
I am also having the same problem on ChromeOS and in Android Chrome browser. A force refresh isn't working for me.

**Comment by satmandu** [comment]
I just disabled https://chrome.google.com/webstore/detail/disable-html5-autoplay/efdhoaajjjgckpbkoglidkeendpkolai and my issue went away, for what it is worth...

**Comment by abduct** [comment]
Same issue here with the RootApp not being found. Doing a "hard refresh" (ctrl+shift+r) allows the site to load normally.

Further info, if you bypass caddy and visit the web service for jellyfin via lan IP the issue does not appear.

This issue affects browsers (vivaldi, firefox), mobile devices (mobile chrome, vivaldi), etc.

Is this a Caddy issue or Jellyfin issue? Currently using Version: 10.9.0

**Comment by Lyamc** [comment]
I believe it is a Jelly in issue.  I have tried everything to disable cached and cookies through the HTTP headers but it doesn't work. 

IIRC it also affected nginx but I would have to test again to confirm.

**Comment by jaysonsantos** [comment]
Hey there folks, just to add to this.
The issue happens no matter which reverse proxy you are using.
What happens is that when you use `localhost:8096` or `192.168.0.42:8096`, `navigator.serviceWorker` will always be undefined, so the service workers never get registered.
But, when you have something in front `navigator.serviceWorker` will actually have the right data to register service workers.
One way to reproduce locally in an easy way, is to run the following:

```
caddy reverse-proxy --to=http://192.168.1.42:8096 --from=http://:9090
```

open the browser on localhost:9090 and `navigator.serviceWorker` should be filled and probably a few errors already start happening

**Comment by Schaka** [comment]
I've tried the PR and it solved my issues with caching.
