### ISSUE TITLE
HDR content with multiple audio sources won't switch them at all

### ISSUE THREAD

**Issue by LucasMZReal** [jellyfin/jellyfin-web#4661]
When HDR content with multiple audio sources is being steamed, and Jellyfin detects that the device can deal with HDR content without needing to deal with tone mapping, you are not able to switch audio sources. It will show as if it is using another, but it will only actually use the default one.

1. Stream multiple audio sourced HDR content on a device that deals with HDR, usually most modern TVs will work, if it shows an HDR icon when it starts playing, that qualifies.
2. Try switching the audio source away from the default 
3. The audio should change and it doesn't.

I would expect for that to not happen and the other audio track to be used.

 - Platform: LG webOS, both in Jellyfin App and on the browser
 - Browser: Native
 - Jellyfin Version: 10.8.10

I would like to state I am not *sure* if the issue is by this cause exactly, that's just my theory because other content works just fine when switching audio.  If anyone has a similar configuration with content that is HDR and a device that supports it as well, and also with multiple audio sources to see if the issue also happens to you.

**Comment by LucasMZReal** [comment]
@dmitrylyzo WebOS 4.X

**Comment by dmitrylyzo** [comment]
> @dmitrylyzo WebOS 4.X

Since it doesn't support the `audioTracks` property, it should remux to play a secondary audio track.
Is `Allow video playback that requires conversion without re-encoding` enabled for the user?

You said it happens on HDR media. Does it happen on SDR?

**Comment by LucasMZReal** [comment]
@dmitrylyzo that option is enabled, and no, it doesn't happen on SDR.

**Comment by LucasMZReal** [comment]
My model is 50UK6520PSA, it was a bit hidden, anyhow it is 4.4.2-10 (goldilocks-gorongosa).

It happens on Direct, I'm unsure how you would classify or check when it's one of the other ones; but I notice "Direct" on quality under the video settings.

When I change the resolution to something else, it doesn't actually solve the issue, up to the point where it's around -1080p 40Mbps where HDR stops working and Jellyfin decides to just handle HDR-to-SDR conversion itself. When that happens, audio settings work just fine. Like described in the main issue, it seems that it's always when Jellyfin sends out a truly HDR stream to a device.

Also when I was in another resolution setting, but HDR still worked, Jellyfin said under "Panel" and clicking the info button that it was still using direct even though that wouldn't make sense to me since it would need to convert 4K into 1080p (AFAIK?).

**Comment by LucasMZReal** [comment]
Yeah.

HTML Video Player
Direct playback
HTTPS
Video

3840x2160

Format: mkv
Size: 16.7GB
Bitrate: 24.4Mbps
Codec: HEVC Main 10
Bitrate (Video): 23.4 Mbps
Video range type: HDR10
Audio codec: EAC3
Audio bitrate: 768kbps
Audio channels: 6
48000 Hz

**Comment by dmitrylyzo** [comment]
> Yeah.
> 
> HTML Video Player Direct playback HTTPS Video
> 
> 3840x2160
> 
> Format: mkv Size: 16.7GB Bitrate: 24.4Mbps Codec: HEVC Main 10 Bitrate (Video): 23.4 Mbps Video range type: HDR10 Audio codec: EAC3 Audio bitrate: 768kbps Audio channels: 6 48000 Hz

This is playback info. At least I see that you are trying HEVC HDR + DD+.

We need a full **media info** to see other tracks.
_You can get it from 3dot menu on the item details page (just use PC/mobile to ease copying). Or you can use an external program such as MediaInfo or ffprobe._

**Comment by LucasMZReal** [comment]
![Screenshot_20230610-075725-826](https://github.com/jellyfin/jellyfin-web/assets/55422065/aaf17450-b543-435c-9089-945a18cb6b7b)

(Yes, it is a torrent 🫥)

**Comment by brokenmass** [comment]
> Allow video playback that requires conversion without re-encoding

webos 4 actullay support audiotracks. maybe this is related to my ticket : https://github.com/jellyfin/jellyfin-web/issues/4729

**Comment by brokenmass** [comment]
>
> (Yes, it is a torrent 🫥)

you should edit the filename out of the image

**Comment by dmitrylyzo** [comment]
> webos 4 actually support audiotracks. maybe this is related to my ticket : #4729

In terms of switching audio tracks, remuxing is more stable than using `audioTracks`. But the latter option is preferable if it is supported.

Currently, if `SecondaryAudioNotSupported` is set (webOS 4) and the second track is selected, it should remux, but it doesn't (https://github.com/jellyfin/jellyfin-web/issues/4661#issuecomment-1585417129).
