### ISSUE TITLE
Mkv file

### ISSUE THREAD

**Issue by itchygrub** [jellyfin/jellyfin-web#4681]
Android TV app 0.15.10. Client
Not playing mkv files.
Have a lot, not converting to just play.
Jellybin server on synology nas.
They play in browser.
Using Exoplayer

**Comment by thornbill** [comment]
- Be sure to use the issue templates so people have the information they need to help you. 
- You need to provide more specific media details and logs. 
- Android TV app issues should go to https://github.com/jellyfin/jellyfin-androidtv
