### ISSUE TITLE
laggy when pressing forward or backward arrow

### ISSUE THREAD

**Issue by Sparklingx** [jellyfin/jellyfin-web#4682]
laggy seeking (stuck for a moment) when pressing forward or backward arrow to seek forward or backward,  when server ping is 30+

**Comment by thornbill** [comment]
Please use the issue template to ensure people have the necessary information to help you.

**Comment by Sparklingx** [comment]
Dont close it. My description of the problem is pretty clear.  pretty sure everyone else is experiencing it too. I told my friend to test it and his one also lags when he press forward arrow key in his keyboard to seek
