### ISSUE TITLE
ALAC will not play on MacOS when using non-Safari browsers

### ISSUE THREAD

**Issue by felix920506** [jellyfin/jellyfin-web#4686]
**Describe The Bug**
ALAC will not play and will not transcode on MacOS clients when using non-Safari browsers

**Media Information**
[alac_mac_jf_mediaInfo.txt](https://github.com/jellyfin/jellyfin/files/11711422/alac_mac_jf_mediaInfo.txt)

**Screenshots**
None

**System (please complete the following information):**
 - Platform: MacOS 13.1, Macbook Pro 2021
 - Browser: Chrome, Firefox
 - Jellyfin Version: 10.8.10

**Additional Context**
Jf logs of the event:
[alac_mac_jf.txt](https://github.com/jellyfin/jellyfin/files/11711428/alac_mac_jf.txt)

Jf logs when using Firefox on Linux
[[2023-06-10 12:53:18.462 +00:00] [INF] W.txt](https://github.com/jellyfin/jellyfin/files/11712496/2023-06-10.12.53.18.462.%2B00.00.INF.W.txt)

From looking at the logs I think it looks like the client is telling the server it supports ALAC when using a non-Safari browser on MacOS

The problem might lie here where it will report ALAC as supported on MacOS regardless of browser:
https://github.com/jellyfin/jellyfin-web/blob/b13b1ff76d71381bce0d74c1d0ac78d919acaab0/src/scripts/browserDeviceProfile.js#LL123C4-L126C10

This will work on iOS as all browsers in iOS use the same core, but will break on MacOS as MacOS browsers have the freedom to choose the core they want.

This issue was originally reported in the jellyfin main repo:
https://github.com/jellyfin/jellyfin/issues/9855

**Comment by thornbill** [comment]
@felix920506 this was only backported to the master branch a few days ago... it should work there now also
