### ISSUE TITLE
Closing ebook while playing audio skips track

### ISSUE THREAD

**Issue by Cducharme84** [jellyfin/jellyfin-web#4689]
**Describe The Bug**
I use both the audio player (for tunes) and ereader portion and if I close out of the currently open book/file Jellyfin-web appears to treat that as a press of the "next track" button.

Vanilla Jellyfin with no plugins related to audio or ebooks. Happens on Jellyfin-Media-Player as well.

**Steps To Reproduce**
1. Use web or JMP to start any audio file (FLAC and MP3 tested)
2. Open any book concurrently on the same platform/device
3. Press the X in the upper right hand corner of the ebook
4. Your next queued audio track starts playing

**Expected Behavior**
If possible create a separate closure flow within the coding to allow for ebook closure without altering other playing media.

**Logs**
[2023-06-14 20:13:05.579 -04:00] [INF] [58] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Web" "10.8.10" playing "The Collection (14)". Stopped at "4" ms
[2023-06-14 20:13:05.630 -04:00] [INF] [24] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Web" "10.8.10" playing "Thir13teen". Stopped at "17358" ms 

**System (please complete the following information):**
 - Platform: Manjaro
 - Browser:Firefox/Chromium/Falkon tested
 - Jellyfin Version: 10.8.10

**Additional Context**
Workarounds found:
Multiple tabs - the closure appears to be tab independent so you can have your audio in one tab and ebook in another without interfering with each other.
JMP & Web - One playing audio the other reading the book.

Obviously with these reasonable workarounds I think fixing this particular issue may be a "nice to have" rather than vital but thought an issue would be prudent for tracking.

**Comment by vincent** [comment]
That bug annoys me as well.

This seems to be caused by the `stopped` event dispatched [here](https://github.com/jellyfin/jellyfin-web/blob/master/src/plugins/bookPlayer/plugin.js#L68), and by a first naive look at it, it does not seems to have any other side effect.

I don't know the codebase enough yet, but if a maintainer can confirm we can get rid of it, I can make a PR.
