### ISSUE TITLE
Not loaded: jstree

### ISSUE THREAD

**Issue by sachk** [jellyfin/jellyfin-web#469]
**Describe the bug**
jstree does not load on nightlies stopping anything from playing

**To Reproduce**

1. Install jellyfin-nightly
2. Open developer console
3. Play anything

**Expected behavior**
jstree gets loaded, stuff plays

**Logs**
```
Uncaught Error: Not loaded: jstree
    at req (alameda.js?v=10.4.0:94)
    at bundle.js?v=10.4.0:8
req @ alameda.js?v=10.4.0:94
(anonymous) @ bundle.js?v=10.4.0:8
TypeError: Hls is not a constructor
    at plugin.js?v=10.4.0:303
    at plugin.js?v=10.4.0:85
    at Object.execCb (alameda.js?v=10.4.0:392)
    at defineModule (alameda.js?v=10.4.0:145)
    at Object.depFinished (alameda.js?v=10.4.0:153)
    at alameda.js?v=10.4.0:178
Uncaught (in promise) TypeError: Hls is not a constructor
    at plugin.js?v=10.4.0:303
    at plugin.js?v=10.4.0:85
    at Object.execCb (alameda.js?v=10.4.0:392)
    at defineModule (alameda.js?v=10.4.0:145)
    at Object.depFinished (alameda.js?v=10.4.0:153)
    at alameda.js?v=10.4.0:178
```

**Screenshots**

https://i.imgur.com/vcSwoHN.png

**System (please complete the following information):**
 - OS: Debian 10
 - Browser: Chrome 76.0.3809.132
 - Jellyfin Version: 10.4.0

**Additional context**
This also happens in Firefox. I have cleared cache and local storage, but that didn't fix it. This didn't happen on nightly 20190909 but started happening on 20190914.

**Comment by thornbill** [comment]
This is a known issue related to a change in how we include dependencies for jellyfin-web. We're working on some changes to how web gets included in the server to fix it.

The first step in fixing this is to get CI builds of web going https://github.com/jellyfin/jellyfin-web/pull/470. Then we will need to work out how to handle publishing the builds and pulling in the appropriate version for server builds.

**Comment by JustAMan** [comment]
This should hopefully be fixed by https://github.com/jellyfin/jellyfin/pull/1791, need to check and confirm

**Comment by thornbill** [comment]
Should be fixed by https://github.com/jellyfin/jellyfin/pull/1793
