### ISSUE TITLE
Want to display lyrics

### ISSUE THREAD

**Issue by mlb0925** [jellyfin/jellyfin-web#4690]
The jellfyin master already has the Lyrics API, so I hope the client can add the function of displaying lyrics

**Comment by nielsvanvelzen** [comment]
Related roadmap item: https://github.com/orgs/jellyfin/projects/43?query=is%3Aopen+sort%3Aupdated-desc&pane=issue&itemId=30108045

**Comment by thornbill** [comment]
If you want to show your support for this feature you can also upvote the feature request https://features.jellyfin.org/posts/285/add-lyrics-to-songs
