### ISSUE TITLE
Shuffle button not automatically enabled when clicking shuffle in music album via web browser

### ISSUE THREAD

**Issue by nigiriemoji** [jellyfin/jellyfin-web#4693]
**Describe The Bug**
When pressing shuffle button in jellyfin web for music, the shuffle button in player isn't automatically enabled.

**Steps To Reproduce**

1. Go to a music album page
2. Click on shuffle button in top right
3. Look at bottom row media player far right
4. See shuffle button not enabled after clicking shuffle in step 2

**Expected Behavior**
I feel like the shuffle setting in the bottom row player should be enabled once you press shuffle up above when viewing an album and its songs below.

**Logs**

**Screenshots**
By default, shuffle button at bottom right here is off. When I press shuffle in the upper right shuffle button the bottom right shuffle button should enable and show blue.
![image](https://github.com/jellyfin/jellyfin-web/assets/53108354/5e29ba81-9b89-425a-b147-c58830cc2dce)

**System (please complete the following information):**
 - Platform: Windows 11, Jellyfin server in Docker/OMV6
 - Browser: Firefox
 - Jellyfin Version: 10.8.10

**Comment by ricci2511** [comment]
Not sure if this is a bug though, I guess that's the expected behavior.
