### ISSUE TITLE
[Feature Request] [Documentation] Getting started developing

### ISSUE THREAD

**Issue by majora2007** [jellyfin/jellyfin-web#471]
**Description**
I think it would be extremely helpful if there was a CONTRIBUTING.md or README.md that explained clear steps on how to develop the jellyfin-web with a local server. Do we copy the main directory? The dist folder? Where do we copy? Etc.

This should help attract new developers as the setup is daunting with no documentation (except for the good docs on the main jellyfin server setup). 

I figured this would fit better here rather than the feathub.

**Comment by thornbill** [comment]
I really want to make some improvements to simplify this going forward, but here is my current process to run an instance of the website locally and connect to an existing Jellyfin server.

0. Fork and clone this repository.
1. Run `yarn install`.
2. Apply this [patch](https://gist.github.com/thornbill/069f5a979ffbd77a9068bd63cfb4f0a1) to enable multiserver support and make the necessary changes to `index.html` to load the main scripts.
3. Start a web server hosting the static files in `dist/`. PHP and Python include servers that you can use for this anything that can server static files will work. I use `cd dist && sudo python3 -m http.server 80` (`sudo` is needed to bind to port 80 on my operating system).
4. Open the site in a browser. In the case above this would just be at `http://localhost`. The loading spinner will continue to display, but proceed to select "Change Server" then "Add Server" and add your Jellyfin server url.
5. Make changes to the web source.
6. Run `yarn build`.
7. Refresh to view changes in browser.

**Comment by grafixeyehero** [comment]
my setup with vsc
1.Fork and clone jellyfin repository
2.open it with vsc workspace
3.add jellyfin-web submodule in to workspace
4. jellyfin.Server/Program.cs change this
`webDir = Path.Combine(AppContext.BaseDirectory, "jellyfin-web", "src");` to `webDir = Path.Combine(AppContext.BaseDirectory, "jellyfin-web", "dist");`
and this to 
MediaBrowser.WebDashboard/MediaBrowser.WebDashboard.csproj change this
`<None Include="jellyfin-web\src\**\*.*">` to `<None Include="jellyfin-web\dist\**\*.*">`
5.open jellyfin-web in vsc terminal 
6.yarn install 
7.yarn run build 
note: every time you change code must run yarn run build
8.start debugging

**Comment by ringmatter** [comment]
Since https://github.com/jellyfin/jellyfin-web/pull/605 is merged,it's not required anymore to rebuild on every change - you can fire up the webpack dev server using `yarn serve` and open `http://localhost:8080`, select a backend server and change files - webpack will reload automatically.
