### ISSUE TITLE
canPlaySecondaryAudio return false for webos 4 and DTS transcoding issue

### ISSUE THREAD

**Issue by brokenmass** [jellyfin/jellyfin-web#4729]
**Describe The Bug**
I have a LG C9 TV, running webos 4 and i'm using the jellyfin-webos app. 
Webos 4 support DTS and HTMLMediaElement audioTracks property 
If I try to play a video that has a DTS audio track, the file get transcoded (remuxed if i play a non DTS track, audio transcoding DTS to AC3 if I select the DTS track)

**Steps To Reproduce**
1. Play a movie with more than one audio track of which at least one is DTS
2. Notice the movie get remuxed or transcoded ` ( PlayMethod=Transcode, TranscodeReason=SecondaryAudioNotSupported )`

**Expected Behavior**
It should play the movie without remuxing or transcoding

**System (please complete the following information):**
 - Platform: Webos
 - Browser: Webos app
 - Jellyfin Version: 10.8.10
 - 
**Additional Context**
The issue can be fixed by changing `browser.web0sVersion >= 5.0` to `browser.web0sVersion >= 4.0` in https://github.com/jellyfin/jellyfin-web/blob/master/src/scripts/browserDeviceProfile.js#L358C9-L358C9
with that line changed the movie is correcly played directly.

Ignoring the `SecondaryAudioNotSupported` issue, I would still have expected that when playing DTS audio (supported in webos4) it would simply remux and not transcode the audio track.

The issue seems to be caused by the request the app makes  `media:/videos/b08076b6-68eb-2d41-280a-81a9b6d181ca/master.m3u8?MediaSourceId=b08076b668eb2d41280a81a9b6d181ca&VideoCodec=h264,hevc,h264&AudioCodec=aac,mp3,ac3,eac3&AudioStreamIndex=3&VideoBitrate=139360000&AudioBitrate=640000&MaxFramerate=23.976025&api_key` 
I would expect `AudioCodec=aac,mp3,ac3,eac` to include DTS)

**Comment by dmitrylyzo** [comment]
> The issue can be fixed by changing `browser.web0sVersion >= 5.0` to `browser.web0sVersion >= 4.0` in https://github.com/jellyfin/jellyfin-web/blob/master/src/scripts/browserDeviceProfile.js#L358C9-L358C9
> with that line changed the movie is correcly played directly.

That was an assumption by referring to Tizen. Tizen 4/5 also has `audioTracks`, but changing it has no effect.
If your TV works correctly with this change, feel free to open a PR on the `release-10.8.z` branch.

> The issue seems to be caused by the request the app makes `media:/videos/b08076b6-68eb-2d41-280a-81a9b6d181ca/master.m3u8?MediaSourceId=b08076b668eb2d41280a81a9b6d181ca&VideoCodec=h264,hevc,h264&AudioCodec=aac,mp3,ac3,eac3&AudioStreamIndex=3&VideoBitrate=139360000&AudioBitrate=640000&MaxFramerate=23.976025&api_key`

This is because `dts` has not been added to `hlsInTsVideoAudioCodecs` (as [here](https://github.com/jellyfin/jellyfin-web/blob/eecd7d1c03d3c875cb2ab65ca99bd908239e6fba/src/scripts/browserDeviceProfile.js#L493C31-L493C31)).
