### ISSUE TITLE
Unable to play/shuffle collection consisting of multiple TV Shows

### ISSUE THREAD

**Issue by the-fifth** [jellyfin/jellyfin-web#4732]
Playback fails to start when playing a collection of TV shows, either through the toplevel "Play" or "Shuffle" buttons.
So a collection in the below layout:
Collection:
- Show 1:
-- Season 1:
--- Episodes 1..x
-- etc
- Show 2:
-- Season 1
--- Episodes 1..x
-- etc

**Steps To Reproduce**
1. Create collection consistent of top level shows, or top level seasons of shows etc.
2. Visit the collection page and attempt to play via either the play or shuffle buttons
3. Playback fails with the below:
"Playback Error

This client isn't compatible with the media and the server isn't sending a compatible media format."

Note: The media can be played perfectly fine on every other method, including shuffle from the show/season level individually, only fails during the attempt to play from a collection level.

**Expected Behavior**
Playback to commence with a playback comprised of all of the media contained within the collection and subsequent seasons/specials/episodes etc.

**Logs**

**Screenshots**
The spinning 'loading' circle animation persists as well, unknown if related.
![image](https://github.com/jellyfin/jellyfin-web/assets/6196203/e0edc0e7-ecfa-48ac-9104-c44d23729897)

**System (please complete the following information):**
 - Platform: Windows 10 Pro
 - Browser: Firefox
 - Jellyfin Version: 10.8.10

**Comment by solidsnake1298** [comment]
Successfully reproduced in 10.8.11.  Both web and Windows JMP.

**Comment by GAntoine** [comment]
This might be an issue with jellyfin core; the response returned the server (with the given filters) has 0 items, even though there are obviously some shows in the collection: `{"Items":[],"TotalRecordCount":0,"StartIndex":0}% `. Here are the filters used for this request, and changing or removing filters had no effect:

```
Filters=IsNotFolder
Recursive=true
MediaTypes=Audio%2CVideo
Limit=300
Fields=Chapters
ExcludeLocationTypes=Virtual
EnableTotalRecordCount=false
CollapseBoxSetItems=false
```

Was also able to reproduce this on Jellyfin Media Player for macOS.

**Comment by lefixx** [comment]
If I make a collection with one TV series in it, play button and shuffle button **on the collection** dont work.
https://i.imgur.com/yoieeP1.jpeg


If I make a collection by adding **episodes** everything works.

**Comment by takemehi** [comment]
I am not sure if this is related as I run linuxserver/jellyfin but I had the same issue in all libraries/collections and was finally able to fix it.
My Jellyfin runs as a docker container with a bound folder for /config to keep the setup intact when updating the container.
Some file/s in there most likely caused the issue because renaming/removing that folder before a fresh container deployment solved the problem for me.
Play all and shuffle work again.

I hope this helps

**Comment by lefixx** [comment]
did redeployment forced an update too?

**Comment by adammhaile** [comment]
Can confirm this still exists on:
Version: 10.8.13
Operating System: Windows
Architecture: X64
