### ISSUE TITLE
Using Original title instead of title

### ISSUE THREAD

**Issue by tsfoni** [jellyfin/jellyfin-web#4739]
**Describe The Bug**
Instead of using the title of a movie use the original title, so filter by letter would work on non-English titles. 

**Steps To Reproduce**

1. Open movie library
2. Filter by letter
3. You won't see any movie if movie title is non-English.

**Expected Behavior**
Get the title by their original title with filter by letter.

**Screenshots**
![image](https://github.com/jellyfin/jellyfin-web/assets/104026572/bab3a53d-801d-49c1-bc4f-4fe2eb16ebf7)

**Comment by Daivy03** [comment]
## gif demonstration of the bug

> [!NOTE]
> Im runnig Jellyfin on docker container.
Docker image: linuxserver/jellyfin
Jellyfin version: 10.8.10

![Jellyfin issue #4739](https://github.com/jellyfin/jellyfin-web/assets/75785698/f144bdb2-6471-4da1-87bb-83598c3a999b)

**Comment by thornbill** [comment]
In the recording the original title in the metadata is also not in English... is this correct?

**Comment by jimezesinachi** [comment]
Just to confirm, when you say 'original title', you mean 'the original file name's, yes?

**Comment by tsfoni** [comment]
> Just to confirm, when you say 'original title', you mean 'the original file name', yes?

No. I mean original title, the title which is in English.
