### ISSUE TITLE
Gamepad Does Not Function Properly

### ISSUE THREAD

**Issue by TheDarkula** [jellyfin/jellyfin-web#4750]
**Describe The Bug**
In jellyfin-web (via chromium), no input is received with a gamepad.

Using the `jellyfin-media-player` package from the [AUR](https://aur.archlinux.org/packages/jellyfin-media-player), I have enabled gamepad control through Settings -> Controls -> Enable Gamepad.

With the desktop program, the gamepad input is received, but it seems that there is no logical mapping.

The R3 button refreshes the display. The left analogue stick jumps, albeit once, up and down.

**Expected Behavior**
A connected gamepad to behave in an expected way.

**System (please complete the following information):**
 - Platform: Arch Linux
 - Browser: Chromium
 - Jellyfin Version: 10.8.10

**Comment by dmitrylyzo** [comment]
> In jellyfin-web (via chromium), no input is received with a gamepad.

It only works in TV display mode (because other modes have no focus indicator).

> The R3 button refreshes the display. The left analogue stick jumps, albeit once, up and down.

This may be a key mapping of JMP, not web.

**Comment by TheDarkula** [comment]
@dmitrylyzo Ah, enabling `TV` mode was the trick in the browser, thank you.

As for jellyfin-media-player, I did a lot more investigating, and it is being caught by the regex in `~/.local/share/jellyfinmediaplayer/inputmaps/examples/xbox-controller-mac.json`:

```
"idmatcher": "XBOX360.*|.*360.*Controller"
```

The strange thing is, the identifier in the system for my gamepad is `Xbox Wireless Controller`, which does not read like it should match.
