### ISSUE TITLE
Web pages lose their format when opened in a new tab in Dashboard in 10.3.0

### ISSUE THREAD

**Issue by 97carmine** [jellyfin/jellyfin-web#476]
**Describe the bug**
The pages lose the format at the time of opening any option of the left menu of Dashboard in a new tab

**To Reproduce**

1. Go to 'Dashboard'
2. Right click on any option in the left menu, for example, _Users_ and select _Open link in a new tab_
3. See error

**Expected behavior**
Web pages should be displayed the same as clicking on the menu option in the same tab

**Screenshots**

![8GOs1Sr - Imgur](https://user-images.githubusercontent.com/6619414/63208364-8d667000-c0c2-11e9-868c-46980949db8d.png)

**System (please complete the following information):**
 - OS: Debian 9
 - Browser: Firefox
 - Jellyfin Version: 10.3.0
 - Reverse proxy: no

**Comment by thornbill** [comment]
It looks like these links are missing the leading `#`. Adding that should correct this behavior.

**Comment by trueChazza** [comment]
I have looked into this, and it's not as simple as it first seems. 
Here's a record of things I came across to help others starting on this:

- Opening links in new tabs points directly to HTML templates.
- App router does not pickup hard coded leading `#`.
- Including main bundle in HTML templates not possible without major refactor.

**Comment by MrTimscampi** [comment]
I am removing the "Good first issue" label because, in my opinion, this would need a sizeable rewrite of the router.

This will likely be fixed as part of #889

**Comment by thornbill** [comment]
Should be fixed by https://github.com/jellyfin/jellyfin-web/pull/2158
