### ISSUE TITLE
No Shuffle video option library

### ISSUE THREAD

**Issue by ai** [jellyfin/jellyfin-web#4764]
**Describe The Bug**

On desktop web we have Shuffle option on video library menu on My Media page.

![Captura desde 2023-08-28 20-47-21](https://github.com/jellyfin/jellyfin-web/assets/19343/6a4f6a41-4b58-4f6b-9508-f2fa618e467e)

But on mobile web and Android client we haven’t this option:

![Screenshot_20230828-205316](https://github.com/jellyfin/jellyfin-web/assets/19343/214eeb76-594f-4fa2-9f9a-768737f70acc)

**Steps To Reproduce**

1. Open Jellyin mobile app on Home screen
2. Long-press on any library with videos
3. Won’t be able to see an option to shuffle

**Expected Behavior**

- To have Shuffle option like we have on desktop app
- Or to have Shuffle button inside library

**System (please complete the following information):**
 - Platform: Android 13
 - Browser: Chrome
 - Jellyfin Version: 2.5.2

**Comment by trip-flip** [comment]
This seems to be an issue with selecting multiple entries in anything, even on desktop:
![The shuffle icon should appear on top.](https://github.com/jellyfin/jellyfin-web/assets/89428869/5a848be1-9d0b-4c38-92b1-7c8817176e96)

The shuffle button appears only the 3-dot menu on the library box which can be accessed easily through the desktop (referring to the first screenshot to this issue). You can also shuffle within a library on the expected icon:
![The little shuffle icon.](https://github.com/jellyfin/jellyfin-web/assets/89428869/690a6676-bd77-4e3c-acfd-28a6b42dbc00)

There doesn't appear to be a way to shuffle easily through a selection of items in the code, as opposed to the current implementation of shuffling through a library, series, season, etc. (as far as I can tell).

**Comment by ai** [comment]
There is no Shuffle icon in video library icons in Android client and mobile web

![Screenshot_20230829-105554](https://github.com/jellyfin/jellyfin-web/assets/19343/fcda05bd-5788-4a83-8bb0-af4a7e01f0a5)

**Comment by ai** [comment]
The issue is still exist
