### ISSUE TITLE
Chromecast doesn’t appear on list of devices to cast

### ISSUE THREAD

**Issue by avibrazil** [jellyfin/jellyfin-web#4765]
Μy Jellyfin server is accessible from the internet with HTTPS on port 443 (proxy to internal 8096) and a valid Let’s Encrypt certificate. Only IPv6 though, no IPv4; but this shouldn’t be a problem. Google DNS (8.8.8.8) is able to find my host name.

Even so, Jellyfin iOS app, Jellyfin server accessed over Safari or Google Chrome from my iPhone, say Chromecast not supported and my Chromecast device doesn’t appear on the list.

This is Jellyfin server 10.8.10 on Fedora Linux installed from its official RPMs.

How to fix?

thank you

**Comment by thornbill** [comment]
The Jellyfin iOS app [does not support Chromecast](https://github.com/jellyfin/jellyfin-expo/issues/16).

Chromecast does not support any browsers besides desktop and Android Chrome. That is a Google limitation so there is nothing we can do about it.

...and that is why there is a message saying it is not supported 😉

**Comment by Aireezz** [comment]
Can you not implement it to stream directly from the server to the chromecast device like plex? @thornbill
