### ISSUE TITLE
Subtitles too bright when watching HDR content

### ISSUE THREAD

**Issue by OddMagnet** [jellyfin/jellyfin-web#4782]
In #3327 it was mentioned that a subtitle color picker was added in an unstable recently and should be released in 10.9

This was almost a year ago and it seems 10.9 wasn't released yet (and I couldn't find any info on an eta)

Is there any chance for 10.9 to be released in the near future, or this feature being added to an upcoming minor release?

**Comment by nielsvanvelzen** [comment]
https://jellyfin.org/docs/general/faq#when-will-release-x-happen-when-will-feature-x-be-available

**Comment by OddMagnet** [comment]
since 10.9 was mentioned to be released soon close to a year ago I was really hoping that there'd be more than a "when it's ready"

I suppose I'll either have to live with subtitles burning my eyes or look for a Jellyfin alternative
