### ISSUE TITLE
MP3/AUDIO FILES NOT PLAYING

### ISSUE THREAD

**Issue by AliAsgerSaify** [jellyfin/jellyfin-web#4788]
**Describe The Bug**
WHEN PLAYING AUDIO ITS NOT PLAYING INSTEAD SHOWING ERROR: This client isn't compatible with the media and the server isn't sending a compatible media format.

**Media Information**
MP3

**Screenshots**
![image](https://github.com/jellyfin/jellyfin-web/assets/120162464/24d38cae-ff1c-4717-8297-73ef1bd32304)

**System (please complete the following information):**
 - Platform: [e.g. Linux, Windows, iPhone, Tizen]
 - Browser: [e.g. Firefox, Chrome, Safari]
 - Jellyfin Version: [e.g. 10.6.0]

**Additional Context**

LOG:
Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Web" "10.8.10" playing "At_My_Worst". Stopped at "0" ms

**Comment by Jay204** [comment]
This issue is rather unusual. my server has been running stably for six months without any recent changes, but it has suddenly begun reporting an inability to play music. This is not not  a configuration problem; rather, it suggests potential system-level corruption
