### ISSUE TITLE
Unable to open Library Editor

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-web#480]
**Describe the bug**
Using the latest master (0286cc60d5ee10bc4ccc6ac86c88271a8c9e7a33), the library editor will not appear.

**To Reproduce**
1. Go to Dashboard>Libraries
2. Attempt to use "Manage Library" on any visible library

**Expected behavior**
The Library Editor should open.

**Logs**
```
Uncaught (in promise) ReferenceError: jQuery is not defined
    at editor.show (medialibraryeditor.js?v=10.4.0:175)
    at medialibrarypage.js?v=10.4.0:21
    at Object.execCb (alameda.js?v=10.4.0:392)
    at defineModule (alameda.js?v=10.4.0:145)
    at Object.depFinished (alameda.js?v=10.4.0:153)
    at alameda.js?v=10.4.0:178

RequireJS error: ReferenceError: jQuery is not defined. Failed modules: 
```

**System (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser: Safari, Chrome
 - Jellyfin Version: [master@fc99f1](https://github.com/jellyfin/jellyfin/tree/fc99f1f5630d506638836bc8d69e43dc376aa95d
)

**Comment by dkanada** [comment]
Is this with or without the build changes from the server repository?

**Comment by anthonylavado** [comment]
that would be without. That said, I am manually doing this:
- `yarn install`
- copying `dist` to `Jellyfin/MediaBrowser.WebDashboard/jellyfin-web`

So I know it's worked because I am getting the latest themes, and testing fixes, etc
