### ISSUE TITLE
Scrollers disappear on going back

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-web#483]
**Describe the bug**
Using the nightly, the horizontal scrollers can disappear on page load from the back button.

**To Reproduce**
1. Go to main page
2. Select an item in a horizontal scroller
3. Go back (either with page button or browser button)
4. Observe that scroll buttons are gone

**Expected behavior**
The scroll buttons should stay as they were before.

**System (please complete the following information):**
 - OS: Any
 - Browser: Chrome
 - Jellyfin Version: Latest nightly as of 26 Sept 2019

**Additional context**
Issue does not happen in Firefox.

**Comment by joshuaboniface** [comment]
Confirmed in Chromium on Linux.

**Comment by redSpoutnik** [comment]
I think this is caused by the ```display: flex;``` property in emby-scrollbuttons.css, maybe something is missing?
