### ISSUE TITLE
Playback Error instead of File not Found

### ISSUE THREAD

**Issue by ShakeSp33r** [jellyfin/jellyfin-web#4846]
**Describe the bug**
After renaming a video file, Jellyfin return Playback Error (This client isn't compatible with the media and the server isn't sending a compatible media format) instead of warning that the file does not exist.

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: Docker
 - Clients: Browser
 - Browser: All
 - Jellyfin Version: 10.7.7 stable
 - FFmpeg Version: 4.3.2-Jellyfin
 - Reverse Proxy: nginx
 - Base URL: none
 - Storage: local

**To Reproduce**

1. Add video to jellyfin library
2. Play part of video, to make sure it is in DB
3. Rename the video file directly in the OS
4. Try playing the video again with out scanning Library

**Expected behavior**
System should warm that the file does not exist instead of the current warning of incompatible media

**Screenshots**
![Screenshot 2021-11-04 at 11 04 30](https://user-images.githubusercontent.com/69896780/140286610-f83ec20f-7384-4df5-9dd2-4030de539c68.png)

**Comment by thornbill** [comment]
We should be able to use the error type returned from the server to provide more useful error messages (in web) for certain cases although the server will also probably need to expand the error types returned.

**Comment by ebkalderon** [comment]
Looking forward to seeing this in the next release! I understand #5274 fixes this issue, correct?

**Comment by thornbill** [comment]
Yeah #5247 does not fully handle this. We need the server to return additional error types when fetching playback info, but it's a step in that direction.

**Comment by ebkalderon** [comment]
Feature is still not complete yet. Leaving a comment here to make the stale bot go away.

**Comment by thornbill** [comment]
As I mentioned we know display unique error messages for the types of errors returned by the server. The server does not return many types though currently. Requests for new error types should be directed to the server repo now.

**Comment by ebkalderon** [comment]
That's terrific! Glad to see this closed.
