### ISSUE TITLE
Certain Files Just Stop Playing

### ISSUE THREAD

**Issue by phantomr1982** [jellyfin/jellyfin-web#4849]
While playing some recent files using both AC3/EAC3 combined with H264 Codecs inside a MKV container file the files play fine up to around 22 mins then just stop playing like they are paused,this is around 5 mins short of the files max time limit...and as a result I have a handful of "continue watching these" episode across the front screen ??? When you try to exit the jellyfin app (amazon firestick version 015.xx) and go back in or even the following day to try to resume it is still stuck.

I have seen new versions of the app on Android aatv just not for the Firestick so any ideas ??

I can press play again to rewatch fine,but then it sticks at the same point.

**Comment by thornbill** [comment]
Please see https://jellyfin.org/docs/general/getting-help for appropriate troubleshooting forums.
