### ISSUE TITLE
Audiobooks playback cursor and timer don't update in real time

### ISSUE THREAD

**Issue by cesaratteh** [jellyfin/jellyfin-web#4855]
### Please describe your bug

For Audiobooks, the playback cursor and timer don't update in real time on iPhone/IOS (Jellyfin App, Safari, and Chrome)

### To reproduce:
1. Play any mp3 audiobook file from an iPhone using Jellyfin app, Safari browser, or Chrome browser

#### Expected:
The audiobook plays, the playback cursor moves in real time, and the watch time ticks up.

#### Observed behavior:
The audiobook plays, but the playback cursor doesn't move, and the watch time does not tick up. Both the cursor and the time update only when the page is closed/navigated away from and re-opened.

---------------------------------

### One more note:
I tested my hosted instance using a windows PC and couldn't reproduce the issue. Audiobooks time/cursor track in real time. The bug only affects my iPhone.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Windows 10
- Linux Kernel:
- Virtualization: None
- Clients: Jellyfin Mobile for iOS
- Browser: Safari, chrome on IOS
- FFmpeg Version:
- Playback Method: On app, and browsers
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy: Caddy reverse proxy
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MathiasPius** [comment]
I'm seeing the exact same issue both using the Android app and on Firefox on Manjaro Linux

Server version: 10.8.13
Android version: 2.6.0
Firefox version: 122.0

**Comment by jtheuner** [comment]
Same here:

Server Version: 10.8.13
iOS App Version: 1.5.0
iOS : 17.4
Chrome: 123.0.6312.52
