### ISSUE TITLE
Can't trackpad scroll

### ISSUE THREAD

**Issue by dannymichel** [jellyfin/jellyfin-web#487]
**Describe the bug**
You can't horizontally trackpad scroll through .emby-scroller .emby-itemscontainer

**Comment by dannymichel** [comment]
https://www.dropbox.com/s/tc50r669fsbz1g5/scrolling.mp4 vs jellyfin no trackpad scrolling. https://www.dropbox.com/s/tec9x8bcwivaf1e/no-scrolling.mp4 
this is something you can do on plex and emby perfectly
its beed broken on Jellyfin since 10.4. it was fine in 10.3
and its a glaring issue that just has me thinking i can never fully switch to jellyfin

**Comment by ferferga** [comment]
@dannymichel Can you confirm that this is fixed in nightly?

**Comment by dannymichel** [comment]
@ferferga yes it is fixed but https://github.com/jellyfin/jellyfin-web/issues/867

**Comment by ferferga** [comment]
@dannymichel I will leave that one opened then, as the main point stated in this issue has been resolved already :)
