### ISSUE TITLE
Duplicate Season listings when building jellyfin/master with jellyfin-web/master or with jellyfin-web/10.8.x

### ISSUE THREAD

**Issue by satmandu** [jellyfin/jellyfin-web#4876]
**Describe The Bug**
When I build and run a docker container using jelyfin master using https://github.com/jellyfin/jellyfin/blob/master/Dockerfile (which pulls from jellyfin-web/master) I see show seasons duplicated.

When I modify https://github.com/jellyfin/jellyfin/blob/master/Dockerfile to instead pull from jellyfin-web commits on the 10.8.x branch, e.g. using `ARG JELLYFIN_WEB_VERSION=eb7fb6b39d5558d0b6ea5686cb5fc3813b1cf881`, the problem goes away temporarily, but then comes back some time later.

**System (please complete the following information):**
 - Platform: [e.g. Linux, Windows, iPhone, Tizen] Linux
 - Browser: [e.g. Firefox, Chrome, Safari] Any
 - Jellyfin Version: [e.g. 10.6.0] 10.9.0 (master)

**Additional Context**

**Comment by satmandu** [comment]
I guess this could be added to https://github.com/jellyfin/jellyfin-web/issues/4815 ?

**Comment by thornbill** [comment]
> I guess this could be added to https://github.com/jellyfin/jellyfin-web/issues/4815 ?

That's unlikely. You have to enable the experimental layout and the season view should not be different in it (yet).

**Comment by thornbill** [comment]
Also could you provide a screenshot of what you are seeing? Thanks!

**Comment by satmandu** [comment]
@thornbill It turns out that this is also cropping up on the 10.8.z branch... just shows up a little later...

**Comment by satmandu** [comment]
Switching jellyfin-web versions just appears to mean that the season listing duplication shows up a little later...
