### ISSUE TITLE
Edit images margin/padding issue

### ISSUE THREAD

**Issue by dannymichel** [jellyfin/jellyfin-web#488]
**Describe the bug**
There is a margin/padding issue in 'edit images' page.

**Screenshots**
<img width="507" alt="Screen Shot 2019-09-29 at 6 33 20 AM" src="https://user-images.githubusercontent.com/1161544/65831060-40f67e80-e283-11e9-9909-92f36bcc68a8.png">

**Comment by dkanada** [comment]
I think this has been resolved for a while.
