### ISSUE TITLE
Rename Device don't change device name in the devices page

### ISSUE THREAD

**Issue by TravelerVFX** [jellyfin/jellyfin-web#4882]
**Describe The Bug**
When a device is renamed, the name isn't changed on the devices page.
On the Dashboard page, the device name is the new name.

**Steps To Reproduce**

1. Go to 'XXXXX/web/index.html#!/devices.html'
2. Click on the 3 vertical points of a device
3. Click on 'Edit'
4. Add name
5. Click 'Save`
6. Click '<-' top left corner
7. The device name isn't changed

**Expected Behavior**
The device name should have been changed

**Logs**
No log activity of this issue

**Screenshots**
![Screenshot 2023-10-15 at 11 07 14](https://github.com/jellyfin/jellyfin-web/assets/147994162/8d3bde59-3065-492b-a30b-21551cbd1ab0)
![Screenshot 2023-10-15 at 11 18 46](https://github.com/jellyfin/jellyfin-web/assets/147994162/3be58bf8-29c5-440c-ae29-c0128b37181d)

**System (please complete the following information):**
 - Platform: [Mac]
 - Browser: [Firefox]
 - Jellyfin Version: [10.8.11]

**Comment by nielsvanvelzen** [comment]
Does this happen to all devices or only the ones from the Home Assistant integration? Last time I checked the integration did not implement our API correctly which could introduce issues like this one.

**Comment by sevenrats** [comment]
I tested on a chrome browser instance and on a roku

**Comment by TravelerVFX** [comment]
> Does this happen to all devices or only the ones from the Home Assistant integration? Last time I checked the integration did not implement our API correctly which could introduce issues like this one.

Yes it's happening on all devices

**Comment by TravelerVFX** [comment]
> I tested on a chrome browser instance and on a roku

Same on Safari

**Comment by DaftFuzz** [comment]
I wonder if this may be intentional - the _display_ name is set correctly and reported in, for example, the Activity section with the correct device display name on playback. 

This is being saved as a separate entity to the device "name", which appears to not be user-settable (or certainly isn't affected by the process of editing the device as above).

**Comment by scampower3** [comment]
I can confirm that it happens on Firefox too.

Looking here, this part of the code only uses the Name.
https://github.com/jellyfin/jellyfin-web/blob/4ecbe4df64ae5d4eb3f948d5c8a6d1321be81e22/src/controllers/dashboard/devices/devices.js#L122-L128

I think the main problem is that the /Devices api endpoint only provides the Name and not the CustomName. I can see 2 ways of solving this issue:
1) Update the /Devices api endpoint to include CustomName in its response.
2) In devices.js, make requests to the /Devices/Options api endpoint for each of the device ids.

**Comment by TravelerVFX** [comment]
> I think adding the custom name to the `/Devices` endpoint and then showing that in the dashboard is fine. Perhaps we could show it like `Custom name (original name)`, although if you set a custom name yourself you probably don't need to see the original one.

If I have a vote, I would prefer to display just the `Custom name` :-)

**Comment by ph27** [comment]
In 10.10.7, I'm still seeing this issue in the 'Active Devices' section of the dashboard of the web UI. It shows the original name, even though the custom name is correct in Devices.

Apologies if this belongs as a new issue.
