### ISSUE TITLE
Next up only shows 1 episode

### ISSUE THREAD

**Issue by dannymichel** [jellyfin/jellyfin-web#489]
**Describe the bug**
I'm not sure if this was something emby recently introduced but when you click a show at the root page of the show, next up should show not just one episode but any episodes you havent watched.
However, if you click on a season then click the 'I'(info button) next to an episode on that season it gives you the desired multiple next up.

<img width="1440" alt="Screen Shot 2019-09-29 at 11 46 08 AM" src="https://user-images.githubusercontent.com/1161544/65835015-3651de80-e2af-11e9-9ab6-579cc981e9ba.png">

**Comment by joshuaboniface** [comment]
I'm pretty sure this was recently introduced in Emby. I only ever remember a single next up per show from by 3.5.x, and JF has always been like this too. Would be a feature request on https://features.jellyfin.org
