### ISSUE TITLE
HDR Transcoding in Edge Even Though I Have HDR

### ISSUE THREAD

**Issue by SmoochySix4** [jellyfin/jellyfin-web#4899]
**Describe The Bug**
The HDR HEVC movie keeps getting transcoded to non-HDR H264 even though my monitor is HDR, the setting is on in Windows 11, and it works fine in Plex, YouTube, Amazon, Max, etc...

All required browser extensions/codecs from the Microsoft App Store are downloaded.

**Media Information**
```
Input #0, matroska,webm, from '/tank/Movies/Dune (2021) [tmdbid-438631]/Dune (2021) [tmdbid-438631].mkv':
  Metadata:
    encoder         : libebml v1.4.4 + libmatroska v1.7.1
    creation_time   : 2023-02-08T02:32:28.000000Z
  Duration: 02:35:24.99, start: 0.000000, bitrate: 7257 kb/s
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 1920x1080, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      BPS             : 6486574
      DURATION        : 02:35:24.983000000
      NUMBER_OF_FRAMES: 223576
      NUMBER_OF_BYTES : 7560899441
      _STATISTICS_WRITING_APP: mkvmerge v73.0.0 ('25 or 6 to 4') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2023-02-08 02:32:28
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: eac3, 48000 Hz, 5.1(side), fltp, 768 kb/s (default)
    Metadata:
      BPS             : 768000
      DURATION        : 02:35:24.992000000
      NUMBER_OF_FRAMES: 291406
      NUMBER_OF_BYTES : 895199232
      _STATISTICS_WRITING_APP: mkvmerge v73.0.0 ('25 or 6 to 4') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2023-02-08 02:32:28
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2: Video: png, rgb24(pc), 1280x720 [SAR 3780:3780 DAR 16:9], 90k tbr, 90k tbn (attached pic)
    Metadata:
      filename        : cover.png
      mimetype        : image/png
```
**Screenshots**

![Screenshot 2023-10-20 205748](https://github.com/jellyfin/jellyfin-web/assets/6898434/5bec3bb3-257e-4a63-8455-985c19eee892)

![Screenshot 2023-10-20 210959](https://github.com/jellyfin/jellyfin-web/assets/6898434/14654b6e-6b66-4b27-a907-e4417f1a9c5c)

**System (please complete the following information):**
 - Platform: Windows 11
 - Browser: Edge Chromium (newest/no updates available)
 - Jellyfin Version: 10.8.11 hosted on Linux x64 (Ubuntu)

**Additional Context**

**Comment by dmitrylyzo** [comment]
In 10.8, HDR10 isn't specified for HEVC: https://github.com/jellyfin/jellyfin-web/blob/d274d7f74187e2f5fe601e022183ddaa68281c8e/src/scripts/browserDeviceProfile.js#L841-L844

In 10.9, it is enabled for HEVC, but disabled for Edge :man_shrugging: : https://github.com/jellyfin/jellyfin-web/blob/5e8cc3f9150987846c8458cbe1e33f9689b1ba51/src/scripts/browserDeviceProfile.js#L197-L198

**Comment by nyanmisaka** [comment]
Edge does not support tone-mapping when there is no GPU, and when there is a GPU, the tone-mapped color is a mess.

And it has recently introduced more bugs to the point where it cannot decode AV1. But it still reports via canPlaytype that it supports AV1.

**Comment by dmitrylyzo** [comment]
> @dmitrylyzo Do you know how to check if the current display is SDR or HDR in a browser?

Maybe https://stackoverflow.com/a/75213217 (for modern browsers), but I haven't tested.

We could add a checkbox to toggle HDR support (_I had this idea when I was trying to implement the IsHDR param - it is replaced by your VideoRange_). Not all HDR capable panels have sufficient brightness/contrast - scenes become too dark. With this checkbox, we can disable HDR to force tone-mapping.

**Comment by SmoochySix4** [comment]
I am not sure I understand where the issues lie, then, as I have had no issues with the color on Amazon, Plex, or Netflix when using Edge Chromium with HEVC HDR10.

What should be the selection is, if you have tone mapping turned off in the settings, then jellyfin-web should ignore anything related to the video having HDR and just direct stream the video, instead of forcing the transcode. If tone mapping is turned off, what is the point of the transcode to begin with?

**Comment by nyanmisaka** [comment]
> Maybe https://stackoverflow.com/a/75213217 (for modern browsers), but I haven't tested.

Great. Maybe YouTube is using this API, so it can provides HDR video options dynamically.

> We could add a checkbox to toggle HDR support (_I had this idea when I was trying to implement the IsHDR param - it is replaced by your VideoRange_). Not all HDR capable panels have sufficient brightness/contrast - scenes become too dark. With this checkbox, we can disable HDR to force tone-mapping.

Make sense.

**Comment by nyanmisaka** [comment]
For the record, DoVi P5 on Windows Chrome/Edge requires this option. But it's disabled by default.

*chrome://flags/#enable-media-foundation-clear*

![image](https://github.com/jellyfin/jellyfin-web/assets/14953024/78089e05-c25f-4f08-8edd-debac1d33088)

**Comment by SmoochySix4** [comment]
I downloaded the source code, modified the .js file, and currently testing with npm start, but that file is still being transcoded. Still saying the videos range is not supported. Do I need to disable tone mapping as well?

**Comment by dmitrylyzo** [comment]
> I downloaded the source code, modified the .js file, and currently testing with npm start, but that file is still being transcoded. Still saying the videos range is not supported. Do I need to disable tone mapping as well?

Just in case, are you connecting `http://localhost:8081`?

Check the payload for `PlaybackInfo` in the Developer Tools / Network. There should be
```json
"CodecProfiles": [{
    "Codec": "hevc",
    "Conditions": [{
        "Condition": "EqualsAny",
        "IsRequired": false,
        "Property": "VideoRangeType",
        "Value": "SDR|HDR10|HLG"    // <-- here supported video ranges
    }]
}]
```

**Comment by SmoochySix4** [comment]
Okay, I am not sure where that is. First timer with nodejs and the like. But... I did figure out what was wrong on my end. I had checked out 10.8.9, and it didn't work. Works great on 10.8.11. No transcoding at all.

Now, to figure out how to stop it from letterboxing a 1080p video on a 2k monitor...

Thanks for all of the help.

**Comment by dmitrylyzo** [comment]
> Works great on 10.8.11. No transcoding at all.

With [this](https://github.com/jellyfin/jellyfin-web/issues/4899#issuecomment-1774996632) workaround? Or just clean 10.8.11?

**Comment by SmoochySix4** [comment]
Sorry. Yeah, 10.8.11 with the edit to the browserDeviceProfile.js

**Comment by msimic** [comment]
> Edge does not support tone-mapping when there is no GPU, and when there is a GPU, the tone-mapped SDR color is a mess. As for the case where the display HDR has been manually turned on, we need a check to bypass this.
> 
> @dmitrylyzo Do you know how to check if the current display is SDR or HDR in a browser?
> 
> And it has recently introduced more bugs to the point where it cannot decode AV1. But it still reports via canPlaytype that it supports AV1.

if (screen.colorDepth > 24 && window.matchMedia('(color-gamut: p3)').matches) { 
  /* use HDR content, or if you want you can check also for [rec2020](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/color-gamut#rec2020) */ 
} else { 
  /* use SDR content */ 
}

**Comment by nyanmisaka** [comment]
I think most people can infer from the context that no GPU means the GPU hardware acceleration is disabled in Chrome (artificial/driver bug list/driver not installed).

**Comment by Avamander** [comment]
I have a similar experience, basically everything HEVC (up to 8K@60, 10bit, PQ/HLG), VP9, AV1 decodes fine but Jellyfin Web tends to start transcoding quite often. Basically everything except Dolby Vision P5 and Rext plays correctly, which [this test page](https://lf-tk-sg.ibytedtos.com/obj/tcs-client-sg/resources/video_demo_hevc.html) confirms. (The MediaFoundation flag suggested above changed nothing, Edge just doesn't seem to handle the DV P5 color space correctly)

If at all possible a checkbox to fall back to transcoding in those few rare cases would be significantly nicer.
