### ISSUE TITLE
Firefox opens "Find in page" when j, k, l is pressed in playing video

### ISSUE THREAD

**Issue by Erutuon** [jellyfin/jellyfin-web#4908]
**Describe The Bug**
In Firefox, when you press j, k, or l while playing a video, the desired action, but also opens up a basic "Find in page" dialog at the bottom of the page with the letter in the input box.

**Steps To Reproduce**
1. Open Jellyfin in Firefox
2. Play video
3. Press j, k, or l

**Expected Behavior**
The desired action should happen and "Find in page" should not open.

**Screenshots**
After pressing j (top and bottom of screen cropped out for privacy):
![image](https://github.com/jellyfin/jellyfin-web/assets/5840197/d0b9112a-4113-4739-b9c0-09ce44e998e2)

**System (please complete the following information):**
 - Platform: Windows (operating system on which I'm viewing the video; the server runs Linux, but that probably has no relevance for the web interface)
 - Browser: Firefox
 - Jellyfin Version: 10.8.11

**Comment by GAntoine** [comment]
Just tried it on Firefox (Dev Ed) on macOS and the finder bar doesn't appear, maybe this is a FF-on-Windows only issue?

**Comment by cpmsmith** [comment]
I'm guessing this requires the "search for text when you start typing" setting to be checked to happen?

<img width="511" alt="image" src="https://github.com/jellyfin/jellyfin-web/assets/9437625/b989fc2f-5c3c-4d9f-b1af-1d08edc6f692">

**Comment by cpmsmith** [comment]
Yep, I can confirm it happens on macOS when that setting is enabled. I expect it just needs some judicious `e.preventDefault`s in [`onKeyDown` over here](https://github.com/jellyfin/jellyfin-web/blob/05e2186882c5c0d35bdb6ad80195e379b276c5b7/src/controllers/playback/video/index.js#L1176).
