### ISSUE TITLE
After Update on Arch Linux, Jellyfin is trying to do a new setup Wizard. All previous browsers are able to connect to the server with no problems.

### ISSUE THREAD

**Issue by semliki** [jellyfin/jellyfin-web#4910]
**Describe The Bug**
After updating on Arch Linux about a week ago, Jellyfin is now trying to get me to go to /wizardstart.html when i have already set up the server. This **only** happens on browsers that I have not logged in with prior, the ones that have the account in my local cache storage are fine, can login, and can even log out and into another account. If they visit the login page directly though, it redirects to wizardstart.html. It seems to be treating itself as both a completely installed system, only for those who have already logged in prior to the update, and a clean install that hasn't been set up for those who are freshly visiting. 

**Steps To Reproduce**
1. Be on Arch
2. Update system & jellyfin
3. Go to any browser not logged in

**Expected Behavior**
Do I even need to fill this lol?

**Logs**
Logs literally are showing absolutely nothing (to my eye). It only gave an error once I started going thru the startup wizard. This log should show more, but it really doesn't. Maybe I'm missing something, but it's only seeming to log when someone accessed the site. It's not showing that it's redirecting you, or that there's even an error.

[Log.txt](https://github.com/jellyfin/jellyfin-web/files/13079070/Log.txt)

**Screenshots**

**System (please complete the following information):**
 - Platform: Server is on Arch Linux latest.
 - Browser: All of them, on all platforms. Yes, I have tried *all* of them.
 - Jellyfin Version: Latest in Arch Repos. Using Caddy to serve.

**Additional Context**
This is really damn annoying, as I share this server with quite a few people and I was hoping to ignore the issue until it hopefully got fixed next dot release or something, but it's unfortunately become a problem before then. Because of the nature of my server, if this bug report doesn't get any traction within probably 24ish hours i'm liable to wipe the slate and do a clean reinstall of either jellyfin or the whole system so I might not be able to send more information.

**Comment by pokkst** [comment]
I am also running into this issue on an Arch install. Uninstalling and reinstalling does not fix the issue. I've tried everything short of completely wiping Arch and trying Ubuntu or something, and every time on a logged-out device it brings me to the wizard. For apps like Swiftin I just get an error when trying to login.

**Comment by pokkst** [comment]
I tried once more, completely uninstalling everything, this time I installed from AUR, which appears to be version 10.9.0 instead of 10.8.11, and that seems to have fixed the issue for now. Possibly not an ideal solution for some as I'm unsure of plugin backwards compatibility, but it at least fixes the login issue.

**Comment by jackrosenthal** [comment]
I am seeing this issue as well.  Happy to provide logs or any other info that would be useful for debugging.

**Comment by FieldofClay** [comment]
I fixed this by changing  <IsStartupWizardCompleted> to true in /etc/jellyfin/system.xml. 

It appears with the latest update, the contents of /var/lib/jellyfin/config get moved to /etc/jellyfin and the Wizard flag gets set to false.

**Comment by charludo** [comment]
Same here. Additional info: I went through the setup wizard again, and this did not create a new user, but instead changed the username and password of the first existing, non-admin user (things like profile picture, settings, library state remained the same)

**Comment by danielshub** [comment]
This issue still exists on Arch. After updates/reinstalls, `IsStartupWizardCompleted` is set to false in `/etc/jellyfin/system.xml` . The `system.xml` file is not owned by any Arch package so it seems like it might be a Jellyfin issue and not an Arch issue.

**Comment by Mubelotix** [comment]
The issue occured on Debian. My install restarts jellyfin around 5 times a day, and I have had the issue only once after about 400 days. There seems to be a race somewhere (I'm running the latest version published as of today)
