### ISSUE TITLE
Deleting a playlist deletes all playlists

### ISSUE THREAD

**Issue by cinderblockgames** [jellyfin/jellyfin-web#4928]
**Describe The Bug**
I just deleted a playlist that I made while trying to download a song off Finamp, and it also deleted the other three playlists that my wife had made. 

**System (please complete the following information):**]
 - Jellyfin Version: hotio/Jellyfin:10.8.11-1

**Comment by oddstr13** [comment]
The `latest` tag is not suitable as a version reference, as it is a moving tag.
Right now, it corresponds to [`release-10.8.11-1`](https://hub.docker.com/layers/hotio/jellyfin/release-10.8.11-1/images/sha256-9687877c585897fcfadb25d578263349ad16c6115c0b6828242b96e1d6305576?context=explore), but that is subject to change at any moment.
If you have not pulled the tag recently and recreated your container, it might correspond to an older release.

**Comment by cinderblockgames** [comment]
Fixed, thanks.
