### ISSUE TITLE
Error setting up new tv provider on Nightly

### ISSUE THREAD

**Issue by dinki** [jellyfin/jellyfin-web#493]
**Describe the bug**
User can no longer add a tv provider on Nightly

**To Reproduce**
Admin->Live TV->Live TV->TV Guide Data Providers-> '+'-> any of the options

**Expected behavior**
User should be able to add providers

**Logs**
```Could not find file 'jellyfin-web/components/tvproviders/.template.html'.```

**System (please complete the following information):**
 - OS: Linux Docker
 - Browser: All
 - Jellyfin Version: Nightly

**Additional context**

According to @thornbill :  "I saw the code for that the other day. It looks like it's missing the provider type for some reason. It should be like some-provider.template.html."

**Comment by dinki** [comment]
Not an issue.  Fixed in latest nightly.  Apologies.

**Comment by thornbill** [comment]
I suspect this was fixed by https://github.com/jellyfin/jellyfin-web/pull/490

**Comment by grafixeyehero** [comment]
i think this was fix in this PR https://github.com/jellyfin/jellyfin-web/pull/542
