### ISSUE TITLE
Disabling pagination by changing from display 100 items to 0 causes large music libraries to not load properly

### ISSUE THREAD

**Issue by q5BWr6gN** [jellyfin/jellyfin-web#4932]
**Describe The Bug**

Disabling pagination of items causes my large music library to not load individual items from the "Songs" page. However, items load as expected when pagination is enabled, or when other sections in the library are used to play from a smaller number of items, such as the "Suggestions" section. Additionally, playback still works from the "Songs" page when the three dots are selected to create an "Instant Mix".

**Steps To Reproduce**

1. Ensure your user display settings are changed from library page size 100 to 0 in order to disable paging, and save.
2. Go to your music library folder with ~800 items, including items lasting up to 8 hours.
3. Click on "Songs".
4. Click on any item to begin playback.
5. Observe the load circle animation, but nothing happens.

**Expected Behavior**

Items should load properly when pagination is disabled.

**Logs**

None seem to be produced.

**Screenshots**

N/A

**System (please complete the following information):**
 - Platform: Windows 10 x64
 - Firefox
 - Jellyfin Version: 10.8.10

**Additional Context**

The same machine that acts as the Jellyfin server is being used for playback. When an android device running the Jellyfin app is used to connect to the same server with pagination disabled, the same issue is observed, and the issue is also resolved when pagination is reenabled.

**Comment by thornbill** [comment]
The current implementation for infinite scrolling is a bit of a hack that breaks in weird ways. I generally do not recommend it.

**Comment by thornbill** [comment]
We should add a warning that disabling pagination does not work properly in some situations.

**Comment by HammyHavoc** [comment]
Is this not actually planned, or is the bot just overly aggressive with closing issues?

**Comment by nicekiwi** [comment]
> The current implementation for infinite scrolling is a bit of a hack that breaks in weird ways. I generally do not recommend it.

Can we get a task in the backlog to improve this?
