### ISSUE TITLE
Shuffling music with pagination on only shuffles from the current page, not all songs

### ISSUE THREAD

**Issue by q5BWr6gN** [jellyfin/jellyfin-web#4933]
**Describe The Bug**

With pagination on and selecting the "Songs" section of the music library, shuffling only draws from the current page, and not all songs available in that folder.

**Steps To Reproduce**

1. Go to your music library with pagination on, and have enough items in your library to create multiple pages
2. Click on any item to begin playback
3. Click on shuffle and repeat on the playback bar
4. Click the next song button
5. Observe that only music from the current page is used for shuffle (a large library sorted by A-Z will only show songs from the beginning of the alphabetical order).

**Expected Behavior**

Shuffling from the song section, regardless of the current page, should shuffle from all songs in the music library and not just from the current page.

**Logs**

None produced.

**Screenshots**

![image](https://github.com/jellyfin/jellyfin-web/assets/31933131/97f0fbbc-5d9a-4d80-8011-01fdf5070e91)

**System (please complete the following information):**
 - Platform: Windows 10 x64
 - Browser: Firefox
 - Jellyfin Version: 10.8.10

**Additional Context**

**Comment by dmitrylyzo** [comment]
`Shuffle` on the "Now playing" bar is for shuffling the current play queue.

In the next release there will be a `Shuffle` for library (https://github.com/jellyfin/jellyfin-web/pull/3741). But it still won't play the entire library - it takes 300 random songs.

**Comment by rmackinnon** [comment]
From what I've observed, if I enqueue on the android TV app, it limits the queue to approximately 180 songs, and doesn't  seem to shuffle the tracks.

UX wise, if a user chooses to enqueue a playlist of an entire collection (for my example 872 tracks), and selects shuffle they would expect it to shuffle the whole playlist.  Whereas if the list is over a certain size, we should probably notify the user the shuffle on the queue is limited to 300 items. What kind of bottle neck is there that is limiting large scale shuffling?

In my use case, where I have a large collection, I'm looking to shuffle my entire Verve Master's collection. While I love me some Chic Corea, hearing him (and the same artist tracks) everytime I shuffle the collection isn't always so great.
