### ISSUE TITLE
Black screen on Tizen 5.0 (2019) after #35429ca

### ISSUE THREAD

**Issue by rafma0** [jellyfin/jellyfin-web#4940]
**Describe The Bug**
A black screen appears on Tizen 5.0 (2019) after commit  https://github.com/jellyfin/jellyfin-web/commit/35429ca61f223932e86c597a6aec745783b0b7c5

**Steps To Reproduce**
- Compile latest jellyfin-web and jellyfin-tizen
- Deploy to TV and run

Result: The splash screen is displayed, followed by a black screen. Pressing the return button only displays the quit message once.

**Comment by dmitrylyzo** [comment]
> Uncaught (in promise) TypeError: Cannot read property 'removeEventListener' of undefined
