### ISSUE TITLE
Disable sync correction for SyncPlay by default

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-web#4972]
**Describe The Change**

The sync correction functionality seems to cause a lot of issues when most people probably don't care about super precise syncing. We already disabled this by default for mobile #2946.

**Comment by DinuD** [comment]
I've opened a PR for this but since this is my first open-source contribution I'm not sure if I should be asking people to take a look or just wait until it gets merged (or doesn't lol). Apologies if I've done anything wrong.
