### ISSUE TITLE
Gamepad not working

### ISSUE THREAD

**Issue by rgabbo** [jellyfin/jellyfin-web#4983]
**Describe The Bug**
My EasySMX gamepad (xinput) is not recognized. I tested it on https://greggman.github.io/html5-gamepad-test/ and is working properly.

**Steps To Reproduce**
1. Activate gamepad on Controls>Enable Gamepad
2. Nothing happens if input arrives from gamepad

**Expected Behavior**
Jellyfin should recognize the gamepad

**System (please complete the following information):**
 - Platform: [e.g. Linux, Windows, iPhone, Tizen]
 - Browser: Firefox 119
 - Jellyfin Version: 10.8.12

**Comment by dmitrylyzo** [comment]
Don't forget to switch display mode to "TV" and refresh.
