### ISSUE TITLE
10.8.12 release was build with outdated translations

### ISSUE THREAD

**Issue by tlpbu** [jellyfin/jellyfin-web#4985]
**Describe The Bug**
I have done plenty of franslations and fixes of historically wrong translations and bad wording for Latvian and I see those in [source code](https://github.com/jellyfin/jellyfin-web/blob/master/src/strings/lv.json) however after 10.8.12 release translations are still not visible in UI.

**Expected Behavior**
To have latest translations visible in Jellyfin UI.

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Any
 - Jellyfin Version: 10.8.12

**Additional Context**
Deployed form jellyfin/jellyfin:latest Docker image.

**Comment by thornbill** [comment]
Unfortunately we don't have a workflow to backport translation updates to bugfix releases. The updates will be released with the next feature release (10.9.0).

**Comment by tlpbu** [comment]
Uff, just checked it basically takes years while it become available judging by the fact 10.8.0 appearde before ~1,5h years. Any way to conveniently get new translations at least on my machines?
