### ISSUE TITLE
Nintendo Switch gamepads do not work

### ISSUE THREAD

**Issue by TriVoxel** [jellyfin/jellyfin-web#4986]
**Describe The Bug**

I've discovered gamepad input only works in TV mode under display settings. This worked well for an Xinput controller. However, my Nintendo Switch controller does not work. None of them do. Not My 1st party controller, my Gulikit controller, or my 8bitdo. Tested in Firefox, GNOME Web, and the "Jellyfin Media Player" Flatpak app on Flathub.

**Steps To Reproduce**

1. Go to Settings > Controls
2. Toggle "Enable Gamepad" on and Save
3. Go to Settings > Display
4. Set "Display Mode" to "TV" and Save
5. Try to control with Xinput controller such as Xbox Series S/X controller
6. Try to control with Nintendo Switch controller

**Expected Behavior**

As Linux uses SDL, it should support any controller, especially common ones like Switch

**System:**
 - Platform: Linux
 - Browser: Firefox, GNOME Web (uses WebKitGTK), Jellyfin Media Player (Flathub)
 - Jellyfin Version: 10.8.11

**Comment by msimic** [comment]
Nintendo controllers don't adhere to any controller input standards.
Are you using the dkms-hid-nintendo / Joycond driver?

If so this might be a high effort thing with low benefit, and you might be screwed.

**Comment by TriVoxel** [comment]
> Nintendo controllers don't adhere to any controller input standards. Are you using the dkms-hid-nintendo / Joycond driver?
> 
> If so this might be a high effort thing with low benefit, and you might be screwed.

I just use the default kernel driver. I'm pretty sure it still uses SDL for mapping
