### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'maxChannelCount')

### ISSUE THREAD

**Issue by szotsaki** [jellyfin/jellyfin-web#5009]
**Describe The Bug**

On Web UI when I try to play a song or a film, I get the following error message. Then the playback won't start.

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'maxChannelCount')
    at main.jellyfin.bundle.js?bd5d0bec6156aabfd326:2:328208
    at main.jellyfin.bundle.js?bd5d0bec6156aabfd326:2:328233
    at b (main.jellyfin.bundle.js?bd5d0bec6156aabfd326:2:328278)
    at main.jellyfin.bundle.js?bd5d0bec6156aabfd326:2:32552
    at new Promise (<anonymous>)
    at Object.getDeviceProfile (main.jellyfin.bundle.js?bd5d0bec6156aabfd326:2:32230)
    at e.value (htmlAudioPlayer-plugin.c5b2001e4020ba039b8e.chunk.js:1:4985)
    at le (main.jellyfin.bundle.js?bd5d0bec6156aabfd326:2:150677)
    at main.jellyfin.bundle.js?bd5d0bec6156aabfd326:2:148215
```

**Steps To Reproduce**

1. Go the web UI
2. Click on the Play button of a random song
3. The error appears in developer console and playback won't start

**Expected Behavior**
Playback starts

**Logs**
This is the location of the code:
```
var r = s.Z.safari || s.Z.chrome || s.Z.edgeChromium || s.Z.firefox || s.Z.tv || s.Z.ps4 || s.Z.xboxOne
                      , o = d(t) || f(t)
                      , i = function() {
                        if (null != v)
                            return v;
                        v = -1;
                        var e = window.AudioContext || window.webkitAudioContext || !1;
                        if (e) {
                            var t = new e;
                            v = t.destination.maxChannelCount  <-----
                        }
                        return v
                    }();
```

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Vivaldi
 - Jellyfin Version: 10.8.12

**Comment by Giwayume** [comment]
This means the destination of the AudioContext object is undefined. In other words, your web browser couldn't find any playback devices such as speakers.

Does this sample page work for you to play audio in your browser?
https://mdn.github.io/webaudio-examples/audio-analyser/

If not, perhaps this just requires a better error message.

**Comment by szotsaki** [comment]
I found the root cause: one of my privacy extensions disabled the access to the audio system. So, the issue was on my side, but I agree that a JS `destination` check with a pop-up error message would be nice.
