### ISSUE TITLE
Latest commits introduced navigation issues on Web and within apps

### ISSUE THREAD

**Issue by pokkst** [jellyfin/jellyfin-web#5025]
**Describe The Bug**
After updating my Jellyfin installation through the jellyfin-git package in the AUR, I have noticed strange web client issues. Navigation bar disappearing, movies and shows don't display the year below them on the home page under "Recently Added" anymore, among other issues that have broken some of my clients such as Finamp and Findroid (libraries no longer load, but I think this is more of a jellyfin bug and not jellyfin-web).

**Steps To Reproduce**
Issue 1:
1. Go to home page
2. Go to admin dashboard
3. Refresh web browser
4. Resulting page has client list behind side menu, rather than resized to fit next to the menu:
![1](https://github.com/jellyfin/jellyfin-web/assets/47200567/d3e7199f-bfe9-4a86-8377-96a334740077)

Issue 2:
1. Go to home page
2. Go to admin dashboard
3. Click Jellyfin icon in top left to go back to home page
4. Resulting page has no navigation bar:
![2](https://github.com/jellyfin/jellyfin-web/assets/47200567/585d6646-d6c3-4280-8eae-c24970cab714)

Issue 3:
1. Go to home page
2. "Recently Added" sections are not shaped correctly (Music library items are not squares, Movies/shows are not posters with the year below them):
![3](https://github.com/jellyfin/jellyfin-web/assets/47200567/72bd8f5c-c09a-4e5d-88cf-12e70d3fe6b6)

Issue 4:
When browsing Music, Movie, TV library, the navigation bar is missing the center buttons to view all, suggestions, episodes, etc.

**Expected Behavior**
Issue 1:
The content should be resized to fit next to the side menu. This is already the case, up until the web browser is refreshed.

Issue 2:
There should be a navigation bar. Additionally, there should be center buttons in the navigation bar when browsing various libraries, such as a view-all button, suggestions, albums, genres, episodes, etc. depending on the library type. Currently, this is not the case no matter what I try.

Issue 3:
Music albums should be square album covers, Movies/TV shows should be posters with the year below

**Logs**
n/a

**Screenshots**
Added above.

**System (please complete the following information):**
 - Platform (Server): Linux (Manjaro)
 - Platform (Client): Linux, Windows, Finamp (Android), Findroid (Android), Roku
 - Browser: Firefox, Mullvad Browser, Tor Browser, Brave
 - Jellyfin Version: 10.9.0

**Additional Context**
n/a

**Comment by thornbill** [comment]
An issue on GitHub should only report a single issue otherwise it is impossible to track when something is resolved.

Issues 3 and 4 in your list are regressions from https://github.com/jellyfin/jellyfin/pull/9764 that should be fixed server side.

**Comment by pokkst** [comment]
Issue 1: https://github.com/jellyfin/jellyfin-web/issues/5034

**Comment by pokkst** [comment]
Issue 4: https://github.com/jellyfin/jellyfin/issues/10658

**Comment by thornbill** [comment]
Thank you for creating separate issues for these!
