### ISSUE TITLE
Latest updates broke web navigation bar

### ISSUE THREAD

**Issue by pokkst** [jellyfin/jellyfin-web#5033]
**Describe The Bug**
Navigation bar disappears under certain conditions. Refreshing the page usually fixes the issue.

**Steps To Reproduce**
1. Go to home page
2. Go to admin dashboard
3. Click Jellyfin icon in top left to go back to home page
4. Resulting page has no navigation bar

**Expected Behavior**
There should be a navigation bar.

**Logs**
n/a

**Screenshots**
![2](https://github.com/jellyfin/jellyfin-web/assets/47200567/aba7684f-ac8a-46f0-be6c-965aa38efb13)

**System (please complete the following information):**
- Platform (Server): Linux (Manjaro)
- Platform (Client): Linux, Windows
- Browser: Firefox, Mullvad Browser, Tor Browser, Brave
- Jellyfin Version: 10.9.0

**Additional Context**
n/a

**Comment by solidsnake1298** [comment]
This issue also happens on Android 2.6.0.  Same steps to replicate.

**Comment by pokkst** [comment]
@thornbill This bug still occurs.

**Comment by solidsnake1298** [comment]
Did you pull down the latest release?  This bug hasn't happened for me for a while.

**Comment by pokkst** [comment]
Yes. It was fixed for me a bit too, but latest commits broke it again.

**Comment by solidsnake1298** [comment]
Can you show us your dashboard?  Recent versions of unstable show the build date.  I don't have this issue with 2024031105.

![image](https://github.com/jellyfin/jellyfin-web/assets/137357145/323e329b-9184-4c4d-b209-e2ebabef9960)

**Comment by pokkst** [comment]
Mine doesn't have that at all.

**Comment by pokkst** [comment]
Docker unstable.

**Comment by solidsnake1298** [comment]
Bring down your Jellyfin unstable container then run this command.

`docker volume prune --force --all`

This will remove the unstable VFS and unstable image.  When you start the unstable docker back up it will re-pull the latest image.  Unsure your docker compose is NOT pulling a specific tag.

**Comment by pokkst** [comment]
I do not think that is the issue, but I will try.

**Comment by pokkst** [comment]
I was right, that is not the issue. I am running the latest image. Issue still occurs.
