### ISSUE TITLE
Play/Pause keyboard button does not work in Safari

### ISSUE THREAD

**Issue by rickykresslein** [jellyfin/jellyfin-web#5062]
**Describe The Bug**
When playing media in Jellyfin on Safari, the "Play/Pause" button on the keyboard does not work properly. If the media is playing and I hit the play/pause key, the media pauses. But pressing the key again does not do anything.

_This also happens on Orion, which is a browser based on WebKit (Safari)._

**Steps To Reproduce**

1. Play a video in Jellyfin web
2. Press the "Play/Pause" key on the keyboard to pause the video
3. Press the "Play/Pause" key on the keyboard again and nothing happens

**Expected Behavior**
The video should resume playing when the "Play/Pause" key is toggled.

**System (please complete the following information):**
 - Platform: macOS 14.2
 - Browser: Safari and Orion
 - Jellyfin Version: 10.8.13

Any help or fix to get this working would be greatly appreciated.

**Comment by awefdev** [comment]
I took a look into this some and it's a very strange bug. It happens in Brave as well. The `addActionHandler()` for play/pause does get called, but it doesn't actually call the callback passed in. I'll ask around and see if there's anything else I can dig up on it.

**Comment by midriasi** [comment]
Facing the same issue with Safari to this day. Sad to see this got stale. Any idea if there is a fix or workaround?

**Comment by mkozjak** [comment]
Definitely faced this with latest Jellyfin 10.10.6 on macOS Sequoia 15.3.1 running Safari 18.3.
