### ISSUE TITLE
Still see the tag in subtitles.

### ISSUE THREAD

**Issue by fernvenue** [jellyfin/jellyfin-web#5064]
Still see the tag in subtitles.

_Originally posted by @fernvenue in https://github.com/jellyfin/jellyfin-web/issues/3727#issuecomment-1872553914_

**Comment by fernvenue** [comment]
I think maybe add an option to make Administrator can set the default *Brun subtitles* option?

**Comment by nielsvanvelzen** [comment]
Did you try this with 10.9? You didn't use our issue template..

**Comment by fernvenue** [comment]
> Did you try this with 10.9?

Nope, I thought that 10.9 have not been released yet?

> You didn't use our issue template..

Sorry, that's because I just created this issue from another closed issue so...My bad.

**Comment by nielsvanvelzen** [comment]
> I thought that 10.9 have not been released yet?

Well there is your answer, the changes are not released yet.

**Comment by fernvenue** [comment]
Ah! Thanks for your explaination, sorry to bother you! I thought that the changes already releases, not noticed the version. Sorry again.
