### ISSUE TITLE
Allow Multiusers: how to toggle tokens?

### ISSUE THREAD

**Issue by distante** [jellyfin/jellyfin-web#5074]
Disclaimer: I have 0 experience in React, I am an Angular dev.

I just started using Jellyfin some days ago, it looks like a nice media manager. The only thing missing for me is allowing multiuser (with maybe pin protection).

So today I thought, maybe I can help so I cloned the Repo and tried to find out where is the login being made for a couple of hours. As for now, looks like the `jellyfin-web` just made calls to the (now deprecated) `jellyfin-apiclient` lib.

But there I just found out `ApiClient.authenticateUserByName` for the first login on the `ApiClient` class. So I am assuing the `ajax` method call is what handles the token using the apiClient instance internal state? I am right here?

Next I tried just login a new user directly from the console with `ApiClient.authenticateByName` I found out something nice. I CAN log more than one user at the time (althought the change is not visible until I refresh the browser or open a new view):

```js
ApiClient.authenticateUserByName("familia", "super-safe-password-here").then(v => {
    console.log(v)
});
```

<img width="700" alt="image" src="https://github.com/jellyfin/jellyfin-web/assets/5490201/226e2e43-dd00-4c4d-a8e2-0ea07a787be2">

The `jellyfin_credentials` entry on local storage gets updated when I call it with the correct `userId` and `token` for my server.

The problem I have now is that I can not figure out how to toggle the active user+token.

I tried manually patching localStorage (with the data of my previous logged in user):

```js
let userId = 'the-previous-user-id';
let accessToken = 'what-was-on-local-storage-jellyfin_credentials';

let jellyfin_credentials = JSON.parse(localStorage.getItem("jellyfin_credentials"));

jellyfin_credentials.Servers[0].UserId = userId;
jellyfin_credentials.Servers[0].AccessToken = accessToken;

localStorage.setItem('jellyfin_credentials', JSON.stringify(jellyfin_credentials));
ApiClient.setAuthenticationInfo(accessToken, userId)
```

But after refresh I get kick out.

I have no idea what to call to toggle the user and token that already exists and are approved by the jellyfin backend.

I also tried to find out something on the `api-client` but I have no idea how it even stores something on the local storage since nothing in this code seams to do that:

https://github.com/jellyfin-archive/jellyfin-apiclient-javascript/blob/0595869949a6da0b9e62f6a2c4a4e349f5282109/src/apiClient.js#L515-L549

Any pointers?

**Comment by thornbill** [comment]
This is not going to be easy. The server supports multiple tokens per device in master/unstable, but as you have kind of already found web definitely does not at the moment. One of the main causes of this is because the apiclient only supports a single token per server in the [credentials functions](https://github.com/jellyfin-archive/jellyfin-apiclient-javascript/blob/6e3ace3aac1228870fd85b1af41502c3bb688e6d/src/credentials.js#L57). We would also need to store the last logged in user instead of just the server and have a ui to list saved users per server and a ui to configure all of that behavior.

**Comment by distante** [comment]
This means that first the web needs to migrate to the new Typescript version of the api client? Or the deprecated Javascript version is still being maintained?

I tried to have different instances of the api client per user, or monkey patch the existing credentials but as I stated, I tried moving the storage entries but the servers returned not authenticated (both on my live version and test version with the master branch).

**Comment by thornbill** [comment]
We don't really plan on releasing any new versions of the apiclient unless absolutely necessary

**Comment by 8bitreid** [comment]
What if you did this feature like stream services do? one account can have up to `n` profiles. This would mean a user can log in with their account and have different profiles to track watch history, and each profile can have different content restrictions. i.e. a "kids" profile. Or should this issue be moved to https://github.com/jellyfin/jellyfin?

**Comment by thornbill** [comment]
The original discussion about switching accounts is being tracked under the following feature request: https://features.jellyfin.org/posts/2348/multiple-account-switch

Multiple profiles under a single user account is likewise tracked here: https://features.jellyfin.org/posts/493/add-user-group-support-was-users-within-users
