### ISSUE TITLE
Get rid of lodash-es

### ISSUE THREAD

**Issue by goremykin** [jellyfin/jellyfin-web#5080]
Hi! I just noticed that we use lodash-es in 4 places - debounce once, isEmpty once and isEqual two times.
What do you think about deleting such a heavy library (636 kB unpacked) if we hardly use it?

Can I implement these methods and create a pull request?

**Comment by IlmariKu** [comment]
I would delete with only that usage. If only 4 occurrences and all of those could be implemented with just regular Javascript.

**Comment by thornbill** [comment]
> What do you think about deleting such a heavy library (636 kB unpacked) if we hardly use it?

This _should_ not matter if tree-shaking is working correctly...

We are a very small team with only 2-3 regular contributors/maintainers so the less code we need to maintain the better imho.

**Comment by goremykin** [comment]
> This _should_ not matter if tree-shaking is working correctly...
Agree. If it works it makes less sense
