### ISSUE TITLE
[Issue]: "Cast & Crew" arrow buttons cut off actor info

### ISSUE THREAD

**Issue by dathbe** [jellyfin/jellyfin-web#5088]
### Please describe your bug

When a screen width makes it so the fist page of cast & crew ends with a half picture of a cast member, clicking the right arrow button will move a full page to the right, leaving that same cast member with the back half of the picture.

I would expect the right arrow to scroll so that the last _fully displayed_ cast member is just off the screen, so that any partial cast member now appears first in the list.  

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian
- Linux Kernel: N/A (will look up if someone thinks this would be helpful)
- Virtualization: Docker
- Clients: Web UI
- Browser: Firefox and Chrome-based
```

### Jellyfin logs

```shell
N/A
```

### FFmpeg logs

```shell
N/A
```

### Please attach any browser or client logs here

N/A

### Please attach any screenshots here

![2024-01-09 11_45_51-Jellyfin — Mozilla Firefox](https://github.com/jellyfin/jellyfin/assets/14321825/b0ad2f08-44ff-4877-9217-9348f4eff856)
![2024-01-09 11_46_12-Jellyfin — Mozilla Firefox](https://github.com/jellyfin/jellyfin/assets/14321825/59888625-2cba-41be-aa88-2f3b2d9a9e0d)

Notice that Vera Lewis gets a half photo on page 1 and page 2 of the cast & crew info.

I suspect the button does something approximately as follows:
"The screen is wide enough that it is displaying 900 pixels of cast & crew information, I should therefore scroll 900 pixels right"
But in reality it should do something a little bit more nuanced, like:
"The screen is wide enough that it is displaying 900 pixels of cast & crew information, I know that each cast photo is 200 pixels wide, so only 4 crew members are fully shown.  I should scroll 4 crew members = 800 pixels."

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thornbill** [comment]
This might be fixed in master.

**Comment by photonconvergence** [comment]
Confirming this is mostly fixed in master. 
Behavior can still be a little odd depending on screen size (for example, see inconsistent padding and slight image crop at the start of the row in screenshots below) but text is no longer cropped.

![actors_1](https://github.com/jellyfin/jellyfin-web/assets/116527579/9a996c13-06d9-4af7-a6c6-59ffeb9bd307)
![actors_2](https://github.com/jellyfin/jellyfin-web/assets/116527579/0291340e-0a78-421c-9869-2feeaea075d0)
