### ISSUE TITLE
[Issue]: Downloading *.woff2 on login screen recursively when reversed proxied through caddy

### ISSUE THREAD

**Issue by jakanaka** [jellyfin/jellyfin-web#5132]
### Please describe your bug

While reversed proxied through caddy, while login remotely with domain name, woff2 files keeps getting downloaded again and again. see in network tab

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Ubuntu, Windows
- Linux Kernel: 5.15.0-91
- Virtualization: None
- Clients: Web
- Browser: Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thornbill** [comment]
The web interface can download a lot of font files for multi-language support and icons. If it really is downloading the exact same file multiple times then maybe that is an issue with the reverse proxy config. There really isn't enough information provided here to be able to find any answers though. At a minimum we would probably need a screenshot of the network inspector showing the full file names, but I think this should go through the normal support channels first to determine if it is a Jellyfin issue vs a config issue.

https://jellyfin.org/docs/general/getting-help
