### ISSUE TITLE
Google Cast still Unsupported on Motorola Edge 30

### ISSUE THREAD

**Issue by mechanarchy** [jellyfin/jellyfin-web#5155]
**Describe The Bug**
See #4747 for history; I have a Motorola Edge 30 Fusion device, and despite the fix in #4748 I'm still not able to cast from the Jellyfin Android app.

**Steps To Reproduce**
1. Install Jellyfin from Google Play
2. Login to server hosted at `https://jellyfin.domain.tld`
3. Click the Cast/'Play On' icon
4. See error `(Google Cast Unsupported)`

**Expected Behavior**
Google Cast should work. It certainly does for other applications on my phone; and does for Chrome on my laptop when accessing the same Jellyfin server.

**System (please complete the following information):**
 - Platform: Android 13; Jellyfin Android v2.6.0
 - Browser: Firefox Android
 - Jellyfin Version: 10.8.13

**Comment by thornbill** [comment]
![image](https://github.com/jellyfin/jellyfin-web/assets/3450688/ef5f77eb-5a3f-46a0-bf68-0d5e1b91e755)

**Comment by mechanarchy** [comment]
Thanks, I could see it was in master and that there were releases newer than that PR's merge date, but I did not realise the fix wasn't in them.
