### ISSUE TITLE
Collections not visible 

### ISSUE THREAD

**Issue by consier** [jellyfin/jellyfin-web#5162]
I am unable to create collections because they do not persist when switching tabs. 

They do not appear in the Collections tab, and they are not visible when using the 'add to collection' functionality on posters. 

Additionally, the Collections library poster does not show up. However, when I activate grouping movies into collections, they do appear in the movie library.

 - Platform: [MacOS, iOS]
 - Browser: [Firefox, Safari]
 - Jellyfin Version: [10.8.13]

**Comment by felizk** [comment]
Hello! I figured out why this happens. When you first add something to a collection, a collection library is created. If you have customized which libraries you have access to, then the new Collection library will not be accessible by default.

To see collections you have to go to your users' settings and enable the Collections library.

**Comment by felizk** [comment]
You could argue this is a bug and that the Collections library should be enabled by default for users. Or that Collections shouldn't even be a library.

**Comment by Qrrbrbirlbel** [comment]
It would be helpful if the Collection entry in the top menu wouldn't show up then.
It is really weird to be able to create and add to collections and to see a menu entry collection but to not actually be able to see them.

That said, the collections are a weird thing anyway, they're not a library even though the user settings treat them like one and they show up in movie libraries even though they are above them (they can also contain series, season, episodes, artists, albums, tracks, …).
