### ISSUE TITLE
Latest Movies showing backdrop images instead of posters

### ISSUE THREAD

**Issue by krakhead22** [jellyfin/jellyfin-web#5191]
**Describe The Bug**
On my home screen in the web interface the Latest Movies section shows the "Backdrop" instead of the Primary or Poster image.

**Steps To Reproduce**
I don't know what created the situation, if this behavior is present in a fresh install, or if my server instance is "different". I have been running jellyfin for years and have upgraded it a few times, so that could be a source.

I looked into the code and I think the underlying issue is related to this line (https://github.com/jellyfin/jellyfin-web/blob/779ad905395bd44c7eefc1ebe7f3ce720655f463/src/components/homesections/sections/recentlyAdded.ts#L59C39-L59C47)

It looks like viewType comes from the parent.CollectionType. For my movies collection the Collection type is "Movies" while the line referenced above is expecting "movies" (no capital). Not sure where this difference came from.

**Expected Behavior**
Movies should show poster view on the home screen

**System (please complete the following information):**
 - Platform: Debian Linux
 - Browser: Chrome 
 - Jellyfin Version: 10.8.13

**Additional Context**
I don't use the web interface frequently, and only updated to 10.8.13 recently, maybe it has always been this way or the update caused it.

**Comment by thornbill** [comment]
Sounds like https://github.com/jellyfin/jellyfin-web/issues/5041 but that was only present in unstable
