### ISSUE TITLE
Profile page always updates password even without old password

### ISSUE THREAD

**Issue by iamtherobin** [jellyfin/jellyfin-web#5199]
Not sure if this is web or windows server issue, but this seems to be the busier repo.

I have been playing around with a Jellyfin server for my desktop. I found in setting up the server I got locked out of my initial account twice and had to completely wipe out the data and start again because it kept saying my password was incorrect.

It turns out when I went to my profile page to apply a new avatar and saved the profile, it deleted the password because I did not enter anything into the new password field. It then updated the profile to not have a password. This meant entering a password would always fail to login. However, entering the account name without a password would indeed allow access to the account.

I might be a rare case due to using Windows 7, but this would be a serious security concern that needs looking into.

**Steps To Reproduce**
This is the exact jellyfin I am using https://repo.jellyfin.org/releases/server/windows/versions/stable/combined/10.8.13/jellyfin_10.8.13.zip
I launched it using batch file with one line: "C:\Portable Software\jellyfin\system\jellyfin.exe" -d "C:\Portable Software\jellyfin\data"

I login through the web interface at localhost:8096 and setup the initial account.

When at the profile details page, regardless of whether or not I enter the previous password (or an incorrect password), once I click save the password will be updated with whatever is in the new password field. If I enter nothing into the field, it will wipe out the password allowing access to the account without a password.

**Expected Behavior**
Password should not update without correctly entering the previous password or a valid new password. User should be warned if previous password was incorrect or if no new password was entered.

**Logs**
No errors show up in the log.

**Screenshots**
Here is an example of what happens when I click save from the profile page without entering any old or new password. The account will be updated without a password and the second screenshot shows the account without the old password field because there is no more password on the account.

<a href="https://imgur.com/mFVoW3K"><img src="https://i.imgur.com/mFVoW3Km.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/sCkGjOU"><img src="https://i.imgur.com/sCkGjOUm.png" title="source: imgur.com" /></a>

**System (please complete the following information):**
 - Platform: Windows 7
 - Browser: LibreWolf 116
 - Jellyfin Version: 10.8.13

**Additional Context**

**Comment by iamtherobin** [comment]
Same behaviour occurs on arch linux. Installed packages were jellyfin-server and jellyfin-web using pacman.

**Comment by thornbill** [comment]
This seems to be a duplicate of https://github.com/jellyfin/jellyfin/issues/9208. The save button is only there to apply password changes. Profile picture updates happen immediately when you upload a new picture. You should be required to enter your current password though unless you are an admin updating another user's profile.

**Comment by btopherjohnson** [comment]
I was able to reproduce this. I am able to change my password without entering my old password as an admin but not an unprivileged user from the profile page.

However, as an admin you can reset any password (including your own) and enter a new one. So maybe it's not necessary?

**Comment by thornbill** [comment]
An admin changing their own password should require the old password to be entered... that part sounds like a server bug possibly.

As far as making it clear that changing the profile picture does not require clicking save, here is some feedback from our UI/UX lead:

	1.	Remove the Save button from all the other settings pages. Toggling a switch & selecting an option from a dropdown is universally understood as a finite action. You want to change an option, you toggle that switch -> the option is changed. NOT toggle a switch and present the option as changed, but only apply the change after you click Save; with no indication that it won't be applied if you go back, (and also no indication of what options you actually modified before saving without you remembering them all - that's a problem on long settings lists.)
	2.	Add a large header before every section:
	•	User profile
	•	CHANGE PASSWORD (text header)
	•	change password options
	•	save/reset buttons
	•	EASY PIN CODE (text header)
	•	options
	•	buttons
	3.	Change the label of the Save buttons to Change password and Set/Apply/Change Easy PIN. Also, the "Enable in-network sign in with my Easy PIN code" checkbox should not be linked to the Save button.
	4.	The Save buttons should be disabled before there's any change made to the text fields. And show a warning every time you try to save a blank password or the current password doesn't match.

**Comment by btopherjohnson** [comment]
> An admin changing their own password should require the old password to be entered... that part sounds like a server bug possibly.

Should I open a separate issue? You can change your password as an admin without entering your own password (assuming you are signed in). 

You can also hit "reset password" and just enter a new password as a unprivileged user (again, assuming you are signed in). 

I'm on 10.8.13

**Comment by thornbill** [comment]
I double checked and it doesn't seem like that fix was backported to 10.8. It should be fixed in master/unstable though.

**Comment by btopherjohnson** [comment]
Sweet, I checked out master and it works right now... Although non-admin users can still change their password without their old one by selecting "reset password". Does that seem right? It seems a bit redundant to have both options for normal users.
