### ISSUE TITLE
Photos - Play All

### ISSUE THREAD

**Issue by markster1700** [jellyfin/jellyfin-web#5206]
**Describe The Bug**
I honestly think this should have been fixed many, many years ago. When invoking this functionality the photos switch/change every 3 seconds. Who tested this and why anyone would release code like that? At the very least it should be a default with somewhere around 7 seconds and have users control the value.  When implementing any functionality once needs to thing aboiut how it is going to be used. Otherwise do not implement at all. This needs to be fixed right away.

**Comment by nielsvanvelzen** [comment]
Lol

**Comment by JPVenson** [comment]
Closed as Feature requests shall be organized at feature.jellyfin.org

**Comment by markster1700** [comment]
> Lol

Really?? These are your communication skills? No wonder.

**Comment by nielsvanvelzen** [comment]
Oh your post was not satire? I honestly think you should have mentioned that many, many years ago.

**Comment by thornbill** [comment]
Feature request: https://features.jellyfin.org/posts/2139/allow-picture-slideshow-delay-to-be-configurable
(Abandoned) Pull request: https://github.com/jellyfin/jellyfin-web/pull/3744
