### ISSUE TITLE
menuLinks not working

### ISSUE THREAD

**Issue by bobthebignose** [jellyfin/jellyfin-web#5220]
**Describe The Bug**
MenuLinks configuration in config.json does not work.

**Steps To Reproduce**
1. Use Jellyfin docker (hotio's version here)
2. Config the config.json path as per Jellyfin documentation
3. Use default template of config.json and add menulinks items.
4. Restart Jellyfin, clear cache and cookies.
5. Still no menulinks appearing.

**Expected Behavior**
Custom menu links should appear.

**Screenshots**

**System (please complete the following information):**
 - Platform: Docker (hotio)
 - Browser: Chrome, Edge and iOS Safari
 - Jellyfin Version: 10.8.13

**Additional Context**

```
{
  "includeCorsCredentials": false,
  "multiserver": false,
  "themes": [
    {
      "name": "Apple TV",
      "id": "appletv",
      "color": "#bcbcbc"
    }, {
      "name": "Blue Radiance",
      "id": "blueradiance",
      "color": "#011432"
    }, {
      "name": "Dark",
      "id": "dark",
      "color": "#202020",
      "default": true
    }, {
      "name": "Light",
      "id": "light",
      "color": "#303030"
    }, {
      "name": "Purple Haze",
      "id": "purplehaze",
      "color": "#000420"
    }, {
      "name": "WMC",
      "id": "wmc",
      "color": "#0c2450"
    }
  ],
  "menuLinks": [
    {
        "name": "Custom Link",
        "url": "https://jellyfin.org"
    },
    {
        "name": "Custom Link w. Custom Icon",
        "icon": "attach_money",
        "url": "https://demo.jellyfin.org/stable"
    }
  ],
  "servers": [],
  "plugins": [
    "playAccessValidation/plugin",
    "experimentalWarnings/plugin",
    "htmlAudioPlayer/plugin",
    "htmlVideoPlayer/plugin",
    "photoPlayer/plugin",
    "comicsPlayer/plugin",
    "bookPlayer/plugin",
    "youtubePlayer/plugin",
    "backdropScreensaver/plugin",
    "pdfPlayer/plugin",
    "logoScreensaver/plugin",
    "sessionPlayer/plugin",
    "chromecastPlayer/plugin"
  ]
}
```

**Comment by thornbill** [comment]
Did you restart the container or just the Jellyfin service?

**Comment by thornbill** [comment]
Ah I wonder if it is just a path difference in the hotio container. I believe both hotio and lsio use different directory structures than the official image.
