### ISSUE TITLE
Audio stuttering when transcode playing ogg vorbis in Safari

### ISSUE THREAD

**Issue by felix920506** [jellyfin/jellyfin-web#5221]
**Describe The Bug**
When transcode playing ogg vorbis files in safari, the audio stutters.
This doesn't seem to happen when transcoding from other formats (eg. opus)

**Media Information**
```
last
Container: ogg
Path: /Users/user/Music/test_music_lib/Arcaea All Songs/last.ogg
Size: 4 MB

Audio
Title: Last - VORBIS - Stereo
Codec: VORBIS
AVC: No
Layout: stereo
Channels: 2 ch
Bitrate: 192 kbps
Sample rate: 44100 Hz
Video range: Unknown
Video range type: Unknown
Default: No
Forced: No
External: No

Image
Codec: MJPEG
AVC: No
Profile: Baseline
Resolution: 768x768
Bit depth: 8 bit
Video range: Unknown
Video range type: Unknown
Color space: bt470bg
Pixel format: yuvj444p
Ref frames: 1
```

**Screenshots**
None

**System (please complete the following information):**
 - Platform: MacOS, iOS
 - Browser: Safari
 - Jellyfin Version: Master (Unstable)
 
**Additional Context**
Playing around in the source code and using hls.js instead of Safari's native HLS support seems to solve the issue on MacOS Safari

**Comment by bleak183** [comment]
I'm getting stuttering/no audio with transcoded AAC in Safari as well

**Comment by felix920506** [comment]
Dropping by to add some more info.

The exact same issue happens in FinAmp, and recordings of the issue happening can be heard here. While the recordings are not on Safari, playing back in Safari and in FinAmp stutters in exactly the same way.

https://github.com/jmshrv/finamp/issues/600#issuecomment-2008653724

**Comment by bleak183** [comment]
> @bleak183 You sure it is the same issue?

I apologize, it indeed doesn't seem to be the same issue. Yours might be related to ogg vorbis specifically.
