### ISSUE TITLE
Live tv working via jellyfin media player, but not from web

### ISSUE THREAD

**Issue by AlessandroTischer** [jellyfin/jellyfin-web#5222]
**Describe The Bug**
I'm trying to watch live tv from [here](https://github.com/Tundrak/IPTV-Italia/raw/main/iptvitaplus.m3u). Some channels work just fine, some others (all the mediaset ones) work on any iptv app, they work via jellyfin media player on windows, but not on the jellyfin web player (thus, neither on smartphones or smart tv). Unfortunately I think this m3u playlist is only playable if you are localized in italy, so other than with a vpn I'm not sure how you could debug it...

**Screenshots**
![image](https://github.com/jellyfin/jellyfin-web/assets/23379317/298c97c0-778b-49f2-a34d-aad583c8806f)

**System (please complete the following information):**
 - Platform: [Windows, Android, TizenOS]
 - Browser: [Chrome, Jellyfin Apps]
 - Jellyfin Version: [Latest docker]

**Comment by ruiribeiro2020** [comment]
Hello,
Funny, the same thing happened to me since February 24th.

Is there an error in jellyfin?

**Comment by AlessandroTischer** [comment]
> Hello,
> Funny, the same thing happened to me since February 24th.
> 
> Is there an error in jellyfin?

As far as I know this is a common problem with this Playlist, but only on jellyfin. I have no error logged in jellyfin...

**Comment by marcocancarini** [comment]
I guess it's a transcoding problem. Web browser is the most problematic

**Comment by AlessandroTischer** [comment]
> I guess it's a transcoding problem. Web browser is the most problematic

I think so too. Unfortunately the TV apps are based on the web...

**Comment by AlessandroTischer** [comment]
After latest update, mediaset channels started working, but with no audio. Guess it's still a step forward :-)

**Comment by vakkD** [comment]
Anything more on this? Have updated to the latest but most channels aren't working. Not sure if it is related but I am getting this error on web "Playback failed due to a fatal player error.", and "master.m3u8: Invalid data found when processing input" in the ffmpeg log.
