### ISSUE TITLE
DLNA options visible in dashboard when plugin is not installed

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-web#5234]
**Describe The Bug**

In Jellyfin 10.9 the DLNA functionality is moved to a plugin. This plugin is not installed by default.

However, right now if you navigate to the dashboard it still shows the DLNA settings. Opening these pages will make jellyfin-web load indefinitely.

**Expected Behavior**

No DLNA pages available.

**Logs**

web

DLNA Settings page

```
Uncaught (in promise) 
Response { type: "cors", url: "http://127.0.0.1:8097/System/Configuration/dlna", redirected: false, status: 404, ok: false, statusText: "Not Found", headers: Headers(1), body: ReadableStream, bodyUsed: false }
```

DLNA Profiles page

```
Uncaught (in promise) 
Response { type: "cors", url: "http://127.0.0.1:8097/Dlna/ProfileInfos", redirected: false, status: 404, ok: false, statusText: "Not Found", headers: Headers(1), body: ReadableStream, bodyUsed: false }
```

server (unrelated I guess)
```
[14:38:33] [ERR] [26] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL GET /System/Configuration/dlna.
MediaBrowser.Common.Extensions.ResourceNotFoundException: Configuration with key dlna not found.
   at Emby.Server.Implementations.AppBase.BaseConfigurationManager.<>c.<GetConfiguration>b__41_0(String k, BaseConfigurationManager configurationMana
ger) in Emby.Server.Implementations\AppBase\BaseConfigurationManager.cs:line 292
```
**Screenshots**

![94900002cd](https://github.com/jellyfin/jellyfin-web/assets/2305178/f180316f-1b66-462e-a7bf-cf43f5d7a6aa)

**System (please complete the following information):**
 - Platform: All
 - Browser: All
 - Jellyfin Version: 10.9.0 master branch at 2024-02-27

**Additional Context**

Not sure what the best solution here is. We could move the web part for DLNA to the plugin but that would make it hard to maintain and integrate in the new React magic. So perhaps we should look if the plugin is installed&enabled and conditionally show these pages? We'd need to make sure that they also don't work when opening the pages directly.

**Comment by TimGels** [comment]
I am conflicted in the possible solution. Easiest is to check if the plugin is installed and then hide or show it. But this also means we have logic for specific plugins in the core, and it can be a slippery slope. "Why can there be no logic in core for x but there is for plugin y". I believe we should choose/ implement a solution that has the downsides and upsides well thought out. I am possibly overthinking this, but I wanted to share my thought on this : )

**Comment by thornbill** [comment]
Update from discussions in matrix:

The plugin already contains the configuration page. The profile editor has been removed since it is now easier to ship profile updates via the plugin. Users can also add/modify profiles via xml files. 

We should remove these pages from web and add a page that just says to install the plugin similar to what we did for notifications.
