### ISSUE TITLE
Call translateKeyFromModule before register, occured some warning in console

### ISSUE THREAD

**Issue by zzyyll2** [jellyfin/jellyfin-web#5237]
**Describe The Bug**
Can not get any items that need to be translated, because at this moment, register method has not been called.

add some code to print more log
![image](https://github.com/jellyfin/jellyfin-web/assets/22398806/082a47c5-b6c0-4ca7-a943-1ab568576fc6)

result:
![image](https://github.com/jellyfin/jellyfin-web/assets/22398806/e8796b2f-b039-4515-ade1-a72a8729c908)

**Comment by thornbill** [comment]
Is this just happening on page load? Is it a specific page? I need some steps to be able to reproduce the issue.

**Comment by zzyyll2** [comment]
> Is this just happening on page load? Is it a specific page? I need some steps to be able to reproduce the issue.

jellyfin-web is master branch and latest version
jellyfin server version is 10.8.13

Reproduce the issue:
1. use chrome browser, press f12 to open dev tools, then switch to console
2. open jellyfin home page, like http://192.168.31.115:8096/
3. you will find the warning message printed in the console
