### ISSUE TITLE
Controllers should not act on UI when not in focus

### ISSUE THREAD

**Issue by xkronusx** [jellyfin/jellyfin-web#525]
**Describe the bug**

Jellyfin Web always accepts control inputs from xbox one controllers even when not in focus.

**To Reproduce**

1. Have controller connected
2. Click any face buttons
3. Web page will go back, stop, start, attempt to open NULL pages etc.

**Expected behavior**
Xbox Controller should not have control of client by default (web). Should be a toggle option to disable.

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version:  10.4.0
 - Reverse proxy: Traefik

**Comment by anthonylavado** [comment]
_moved to web_

**Comment by anthonylavado** [comment]
This has also come up again with someone else on the forums, using a joystick: https://forum.jellyfin.org/t/weird-problem-setting-up-one-pw-field-full-of-chars-one-empty/891/10

And also with a steering wheel: https://github.com/jellyfin/jellyfin/issues/1762

**Comment by t3knical** [comment]
for the time being till a button is made in the settings, navigate to \jellyfin-web\components\serverNotifications\gamepadtokey.js and comment out //runInputLoop(); near the end.

**Comment by djpbessems** [comment]
I'm having the exact same issue. I have a X55 Rhino HOTAS.

I don't think a toggle-preference is going to be good enough though, the gamepadtokey.js should probably be made aware of the concept of more than 2 axis and if it encounters more, than it should disregard any axis that is not at a zero-state or near zero (deadzone).

**Comment by djpbessems** [comment]
I'm having the exact same issue. I have a X55 Rhino HOTAS.

I don't think a toggle-preference is going to be good enough though, the `gamepadtokey.js` should probably be made aware of the concept of more than 2 axis and if it encounters more, than it should disregard any axis that is not at a zero-state or near zero (deadzone).

For now, a better solution than to edit the .js file is to go to `about:config` in either Firefox or Chrome and toggle the setting `dom.gamepad.enabled` to `false`

**Comment by mijofa** [comment]
I've run into this a couple times and only just figured out this is what's actually causing it, there was *so much* confusion!
Consider this a +1/upvote/whatever for this issue

**Comment by t3knical** [comment]
> I'm having the exact same issue. I have a X55 Rhino HOTAS.
> 
> I don't think a toggle-preference is going to be good enough though, the `gamepadtokey.js` should probably be made aware of the concept of more than 2 axis and if it encounters more, than it should disregard any axis that is not at a zero-state or near zero (deadzone).
> 
> For now, a better solution than to edit the .js file is to go to `about:config` in either Firefox or Chrome and toggle the setting `dom.gamepad.enabled` to `false`

what a legend i didn't even know chrome had the option, i tried to find it but couldn't so i dived right to the code :)

**Comment by burythehammer** [comment]
I often play games whilst watching something on another monitor. Was driving me crazy trying to turn it off.

**Comment by ferferga** [comment]
This is fixed by #746. Gamepads won't work when the JF is not focused and will work when it is focused.

However, I don't understand what would be the use case of having a toggle to disable the gamepads @xkronusx . If you don't want to use the gamepad, it should be as simple as disconnecting it, right?

(Talking out from the complete ignorance, I don't own a gamepad, so I'm wondering what else is needed to get this fixed and closed).

**Comment by djpbessems** [comment]
Gamepads are not the only peripherals affected; joysticks and throttles (https://en.wikipedia.org/wiki/HOTAS) are also handled by gamepadtokey.js. More advanced throttles do not have a spring that puts their axis' back into the zero position, so will always trigger keypresses.

Disconnecting these devices is not necessary normally, and frankly not desired (the USB cables are tucked away behind my desk and at the back of my PC).

**Comment by MrTimscampi** [comment]
> More advanced throttles do not have a spring that puts their axis' back into the zero position, so will always trigger keypresses.

This is another issue than what the title suggests, so should be separate, in my opinion.

**Comment by ferferga** [comment]
@djpbessems Did you try pulling the maste branch? Because all devices affected by gamepadtokey.js should now not be enabled when the window is not in focus. Which was the main point of this issue.

Only that was changed, nothing else about the behaviour or how keys are mapped is different. I know that there are many issues with gamepads, as I experienced some of them when I accessed my server through my friend's Xbox. However, I'm not able to fix any of them properly because I don't own any input device different from the keyboard and the mouse. At least without someone else's help is impossible.

If you mean something else, I completely agree with @MrTimscampi .

**Comment by djpbessems** [comment]
I guess it's a different issue, but I stopped using jellyfin, so no longer have a vested interest.

**Comment by ferferga** [comment]
@djpbessems Oooh, that's sad :(. Hope to see you again around here. 

I don't want to clutter this issue more, as this is out of scope, but know that there are support channels in Matrix, Reddit, the forums, etc to get support for issues or provide your feedback. Would be great if you post your feedback in some of those channels about why you stopped using Jellyfin, if you don't mind, we would love listening to your opinion

@dkanada I guess then that we can link this issue to #746 and close this.
