### ISSUE TITLE
Transparent subtitles when playing (non-burned in) ASS subtitles

### ISSUE THREAD

**Issue by NoisyFlake** [jellyfin/jellyfin-web#5267]
**Describe The Bug**

When playing a video with ASS subtitles using the web player, subtitles are semi-transparent, making them hard to read.

**Steps To Reproduce**

1. Load any video with ASS subtitles
2. Make sure subtitles are **not** being transcoded/burned in

**Expected Behavior**

Subtitles don't have transparency, as seen when e.g. playing via VLC or when having subtitles burned in.

**Logs**

**Screenshots**

Jellyfin Web:
![image](https://github.com/jellyfin/jellyfin-web/assets/12649723/20733f83-c947-4f59-ac99-f8967e01f39b)

VLC:
![image](https://github.com/jellyfin/jellyfin-web/assets/12649723/dce2d1dc-6b22-440a-a982-31c75f98782a)

**System (please complete the following information):**
 - Platform: Arch Linux
 - Browser: Firefox
 - Jellyfin Version: 10.8.13

**Additional Context**

Other subtitle formats like SRT and PGS play correctly.

I've found #2291, which was resolved, but it looks like exactly the same problem. Was it maybe reintroduced?

Also, here's the relevant part of the .ass file, just to make sure that it's not having some kind of transparency setting. Playing with the AlphaLevel setting seems to do nothing.
```
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, TertiaryColour, BackColour, Bold, Italic, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, AlphaLevel, Encoding
Style: Default,Trebuchet MS,18.5,13487565,65535,65535,-2147483640,0,0,1,2.0,2.0,2,10,10,30,0,1

[Events]
Dialogue: Marked=0,0:00:19.06,0:00:20.14,*Default,NTP,0000,0000,0000,,(Dwight)\NDo you need anything?
```

**Comment by dmitrylyzo** [comment]
#2291 was due to skipping of fading animation.

Are you referring the outline?

The fonts are different: VLC can use system fonts, Jellyfin - can't.

There are 2 options:
1. Use `Fallback fonts` feature.
2. Embed fonts into the video file (in case of MKV).

**Comment by NoisyFlake** [comment]
The different fonts are not an issue. I‘m talking about both the outline and the shadow being semi transparent, thus creating a weird effect when they overlap where you can’t really tell what’s outline and what’s shadow. In my opinion, they should be completely solid (like e.g. VLC renders them).

**Comment by dmitrylyzo** [comment]
The outline is font specific. For ASS Jellyfin uses only fonts (_according to the style in the subtitles_) that are: embedded in the video, fallback fonts and the default one.

So, to make them look the same, you need to use one of the mentioned options.

**Comment by NoisyFlake** [comment]
Well, since there is no indication in the subtitles file to render anything with transparency, I'd say it's a bug in libass. Weird that nobody noticed it so far though?

**Comment by dmitrylyzo** [comment]
Jellyfin 10.9 will use JASSUB. It uses an updated libass, which seems to have this bug fixed:
![Screenshot_20240310_002328](https://github.com/jellyfin/jellyfin-web/assets/56478732/d7ddbbd6-3ee6-46b3-8270-886e5479bcce)

**Comment by dmitrylyzo** [comment]
I re-tested this with our JSO 4.1.1 fork (used in JF 10.8.x) and was unable to reproduce it.

JSO 4.1.1
![jso-1](https://github.com/jellyfin/jellyfin-web/assets/56478732/5a776f77-573e-4e94-a142-4306b795be06)

VLC 3.0.8
![vlc](https://github.com/jellyfin/jellyfin-web/assets/56478732/0ee6f439-a539-4e16-8cde-c0a3235e70c2)

Could you post `[Script Info]` block of subtitles or entire subtitles?
