### ISSUE TITLE
Playback - Transcoding Page (encodingsettings.html) Saving Issue 

### ISSUE THREAD

**Issue by BlackSiO2** [jellyfin/jellyfin-web#527]
**Describe the bug**
Each time the Playback - Transcoding page is saved it causes \transcodes to be appended to the Transcode Path .

**To Reproduce**
1. Go to Playback - Transcoding
2. Make changes and click save or just click save.
3.  Transcode Path increases by \transcodes each time the page is saved and refreshed.
4. Eventually, if done enough times you can no longer save changes.

**Expected behavior**
Transcode path to stay the same on saving, unless the path is purposely changed.

**System (please complete the following information):**
 - OS: [Windows]
 - Browser: [e.g. Firefox, Chrome]
 - Jellyfin Version: [e.g. 10.4.0]

**Comment by anthonylavado** [comment]
Lots more information here: https://github.com/jellyfin/jellyfin/issues/1988#issue-518712059

**Comment by Bond-009** [comment]
Fixed by https://github.com/jellyfin/jellyfin/pull/1991
