### ISSUE TITLE
Login page instead of home screen after finished show

### ISSUE THREAD

**Issue by drikqlis** [jellyfin/jellyfin-web#529]
**Describe the bug**
After show is finished Jellyfin redirects to login page with user selection instead of home screen. However if you refresh the page or press the home button it will go to home screen, so it is not like you are logged out.

**To Reproduce**

1. Install Jellyfin 10.4.0
2. Open any show/movie and let it finish.
3. Sometimes (not always but often) it will go to login screen.

**Expected behavior**

It should go back to where it was/home screen.

**System (please complete the following information):**
 - OS: Ubuntu 18.04.2 LTS
 - Browser: Tested on custom Chromium, Chrome, Firefox
 - Jellyfin Version: 10.4.0
 - Reverse proxy: Normally nginx, but tested without, problem still persist

**Additional context**

Started after update to 10.4.0, previously everything was working correctly.

**Comment by JustAMan** [comment]
Can this be caused by https://github.com/jellyfin/jellyfin-web/pull/307 ?

**Comment by anthonylavado** [comment]
Or more accurately, https://github.com/jellyfin/jellyfin-web/pull/152

Seems like it. Will need to try these steps (assuming this repros):
* Log in to server, but uncheck "Remember me:
* Start playing media directly from the first page
* Get to media end
