### ISSUE TITLE
Disappearing Buttons in Playback Menu

### ISSUE THREAD

**Issue by arhamqureshi** [jellyfin/jellyfin-web#530]
There is a bug on the Jellyfin Android app and also on the web version of Jellyfin on Chrome for Android. When pausing the video and letting the buttons menu fade away, it causes the last pressed button to also disappear. Best shown using screenshots:

1. All buttons are present. In this screenshot I have paused the episode.
![All_Buttons](https://user-images.githubusercontent.com/29435325/66826521-59aba780-ef98-11e9-8553-cdce4a9ae2a0.jpeg)

2. ~~I let the menu with all the buttons fade away~~ I tap the screen to hide the menu/controls bar, and after tapping on the screen again the menu reappears with one less button (the last button I pressed, in this case the pause/play)
![Pause_Play_Missing](https://user-images.githubusercontent.com/29435325/66826536-616b4c00-ef98-11e9-9a02-9acee0215fbd.jpg)

3. I was able to replicate this with all of the buttons in the bottom menu, and they've all now disappeared.
![All_Missing](https://user-images.githubusercontent.com/29435325/66826547-67f9c380-ef98-11e9-9ae8-fe6224ce2bd1.jpg)

The screenshots are from the latest Jellyfin app on Android, however I was able to replicate the same issues via Chrome on my Android Device.

EDIT: Better (smaller) screenshots..
EDIT2:
**How To Replicate:**
1. Start playback
2. Press pause/play, and let controls auto fade
3. Tap screen to show controls
4. Hit play, and hide the controls manually by tapping the screen again
5. Tap the screen once more to show controls. Pause/play is now missing

**Comment by JustAMan** [comment]
This looks to be a jellyfin-web issue (though most likely in the part which is mobile-specific), so transferred.

ping @dkanada

**Comment by dkanada** [comment]
I hadn't seen this before, but I was able to reproduce it by exiting and entering the app during video playback. Are you sure you were able to trigger the issue simply by letting the controls disappear?

**Comment by arhamqureshi** [comment]
> I hadn't seen this before, but I was able to reproduce it by exiting and entering the app during video playback. Are you sure you were able to trigger the issue simply by letting the controls disappear?

I just tried it again, you are correct that it indeed does not happen when it fades away. However, the bug is present if you pause/play the video and then tap the screen to hide/show the controls bar. I will make the edit in the initial issue. My apologies.

**Comment by deanishe** [comment]
> I just tried it again, you are correct that it indeed does not happen when it fades away.

It does on iOS. Please see my accidental duplicate issue #2018 for a screen recording.

**Comment by dausruddin** [comment]
I can easily reproduce the bug in latest Android app by
- pause the video 
- tap screen to hide controls
- tap again to reveal and the play button is gone.

**Comment by evanfoster** [comment]
I run into this issue multiple times a day using the latest Android app. I could have sworn that I could reproduce this just by rotating the screen vertically then horizontally, but I haven't found consistent reproduction steps. It's happened to me while the video was paused or playing.

**Comment by stom66** [comment]
Getting this issue with 10.8 when using jellyfin-web and external SRT files. There also appears to be an issue with old subtitles being cached somehow, despite removing the files from the drive or renaming media.
