### ISSUE TITLE
Doesnt ask if I want to save password on successful login

### ISSUE THREAD

**Issue by agilob** [jellyfin/jellyfin-web#531]
**Describe the bug**
Doesnt ask if I want to save password on successful login

**To Reproduce**

1. Go login
2. Click type username and password
3. Should ask if I want to save username and password but doesnt

**System (please complete the following information):**
 - OS: docker
 - Browser: firefox 69.0.2
 - Jellyfin Version: 10.4

**Comment by anthonylavado** [comment]
@Agilob Do you mean that Firefox (or other) doesn’t ask? I don’t think we have this feature ourselves because the “Remember Me” checkbox exists.

**Comment by agilob** [comment]
I can use "remember me" but when I remove cookies I want my username+pass saved in my browser ad synced between devices.

**Comment by anthonylavado** [comment]
@agilob Okay, so it is that the browser doesn't ask you if you want to save the username/password.

**Comment by agilob** [comment]
bump

**Comment by arantes555** [comment]
I've had this issue on some sites I wrote when the login form was not wrapped in a `<form>` element. For some reason, Firefox really needs to see a `<form>` in order to understand that there is something to remember.

(As a workaround, you can save the password manually in firefox's password manager. The auto-complete works a bit better and does not always need an actual `<form>` to auto-fill your passwords)

**Comment by ferferga** [comment]
I just pulled the changes and tested [right now](https://github.com/jellyfin/jellyfin-web/tree/5df8202d7d104792a40481e5fce3629344ed0361) with master branch and Firefox prompted me for saving the password. 

Can you test cloning master, so we can confirm this is fixed? (or installing jellyfin-nightly, which also has the latest changes)

**Comment by arantes555** [comment]
FYI Firefox changed a few things in the password manager recently, I believe it was in FF70.

**Comment by agilob** [comment]
The issue has been reported for firefox 69, day after new stable release of jellyfin.

**Comment by ferferga** [comment]
@agilob But it's fixed? Because in latest stable the login fields are wrapped inside ``<form>`` tags, so either @arantes555 is confused and that's not the problem or it's an issue that Firefox had for a while and it's now fixed.

**Comment by dkanada** [comment]
I just tried with Jellyfin Nightly and Firefox 72 and got a prompt.

**Comment by ferferga** [comment]
@dkanada Shall we close this?
