### ISSUE TITLE
Firefox Cannot Play HEVC

### ISSUE THREAD

**Issue by felix920506** [jellyfin/jellyfin-web#5337]
**Describe The Bug**
HEVC Video files don't play in Firefox. It endlessly spins.
It seems like it is trying to direct play but Firefox doesn't support HEVC
https://caniuse.com/hevc

**Media Information**
```
S01E01
Container: mkv
Path: /Users/user/Movies/test_shows_lib/tenten_kakumei/season 1/S01E01.mkv
Size: 244 MB

Video
Title: 1080p HEVC SDR
Codec: HEVC
AVC: No
Profile: Main 10
Level: 120
Resolution: 1920x1080
Aspect ratio: 16:9
Anamorphic: No
Interlaced: No
Framerate: 23.976025
Bitrate: 1443 kbps
Bit depth: 10 bit
Video range: SDR
Video range type: SDR
Color space: bt709
Color transfer: bt709
Color primaries: bt709
Pixel format: yuv420p10le
Ref frames: 1

Audio
Title: Stereo - 日文 - AAC - Default
Language: jpn
Codec: AAC
AVC: No
Profile: LC
Layout: stereo
Channels: 2 ch
Bitrate: 159 kbps
Sample rate: 44100 Hz
Default: Yes
Forced: No
External: No

Subtitle
Title: CHS - Chi - Default - ASS
Language: chi
Codec: ASS
AVC: No
Default: Yes
Forced: No
External: No

Subtitle
Title: CHT - Chi - Default - ASS
Language: chi
Codec: ASS
AVC: No
Default: Yes
Forced: No
External: No
```

**Screenshots**
<img width="1512" alt="截圖 2024-03-27 下午9 17 24" src="https://github.com/jellyfin/jellyfin-web/assets/25688628/3e9bacfd-40bc-4e29-a274-7dd82dd4c7b6">

**System (please complete the following information):**
 - Platform: macOS
 - Browser: Firefox 123.0.1
 - Jellyfin Version: 10.9.0 build 2024032505

**Additional Context**
Same video plays fine in Chrome

**Comment by nyanmisaka** [comment]
The only reason this happens is that Firefox on macOS incorrectly reports that it has HEVC support, causing jellyfin-web to be tricked into remuxing from HEVC MKV to HEVC fMP4. So that playback fails.

You can disable it in this. https://github.com/jellyfin/jellyfin-web/blob/master/src/scripts/browserDeviceProfile.js
