### ISSUE TITLE
No focus marker on unchecked radiobuttons

### ISSUE THREAD

**Issue by dmitrylyzo** [jellyfin/jellyfin-web#536]
**Description**
No focus marker on unchecked radiobuttons.

**To Reproduce**
1. Turn on TV layout.
2. Open page "TV Shows"/"Movies".
3. Click on "Sort".
4. Navigate with keyboard to change focus.

**System**
Browser/TV: Firefox 69.0.2, Tizen 4.0

**My Investigations**
CSS style for focus marker is shadow for inner circle. When the radiobutton is unchecked, inner circle has _transform: scale3d(0,0,0)_, and shadow not shown.
![jellyfin-web_issue02_01](https://user-images.githubusercontent.com/56478732/66945470-c3d75180-f057-11e9-9578-b993b37044c0.png)
![jellyfin-web_issue02_02](https://user-images.githubusercontent.com/56478732/66945520-de112f80-f057-11e9-9c8c-1e60382cc603.png)

**Comment by dkanada** [comment]
@DrPandemic do you have any thoughts on this? I think you were the one who improved the checkbox elements.

**Comment by telans** [comment]
This seems to have been 'fixed' (in the sense that I can no longer un-focus, which I believe is correct) on master, but not in 10.4.3

![layer_gif](https://user-images.githubusercontent.com/45819748/74884295-c1209c00-536a-11ea-8e72-a55348932837.gif)

**Comment by dmitrylyzo** [comment]
Still no focus marker on **unchecked** radio button.
Firefox 72.0.1
Chrome 79.0.3945.79
Jellyfin-web: jellyfin-nightly_20200219
