### ISSUE TITLE
"Allow encoding in MJPEG format (used during trickplay generation)" not being saved

### ISSUE THREAD

**Issue by GeorgeH005** [jellyfin/jellyfin-web#5363]
**Describe The Bug**
The button "Allow encoding in MJPEG format (used during trickplay generation)" gets reset after each reload of the page. It is not clear to me if it is actually being enabled, and as such is a web issue, or if it's not being saved properly, in which case it is probably a server issue.

**Steps To Reproduce**
1. Go to Settings
2. Click on Playback
3. Scroll down to Encoding Format Options
4. Check "Allow encoding in MJPEG format (used during trickplay generation)"
5. Save.
6. Reload.
7. Button should have been toggled back.

**Expected Behavior**
"Allow encoding in MJPEG format (used during trickplay generation)" should remain enabled after saving.

**Logs**
Not aware of any relevant log entries.

**System (please complete the following information):**
Jellyfin Web.

**Additional Context**
N/A

**Comment by thornbill** [comment]
There were some changes to how this is handled server side but the corresponding web changes have not been merged yet.

https://github.com/jellyfin/jellyfin-web/pull/5331
