### ISSUE TITLE
Unstable: Firefox/Chromium cannot play AV1

### ISSUE THREAD

**Issue by solidsnake1298** [jellyfin/jellyfin-web#5364]
**Describe The Bug**
When I play AV1 video in Firefox or Chromium on Linux the browser displays a spinning icon endlessly.  The server log does not show the resulting playback method that was determined.  This is the only line that appears when I initiate playback of an AV1 video.

`
[2024-04-01 21:46:00.897 +00:00] [INF] [57] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "Chris". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
`

**Media Information**
```
Princess Mononoke
Container: mkv
Path: /media/library/Anime Movies/Princess Mononoke/Princess Mononoke.mkv
Size: 12990 MB

Video
Title: 1080p AV1 SDR
Codec: AV1
AVC: No
Profile: Main
Level: 8
Resolution: 1920x1080
Aspect ratio: 16:9
Anamorphic: No
Interlaced: No
Framerate: 23.976025
Bitrate: 13542 kbps
Bit depth: 8 bit
Video range: SDR
Video range type: SDR
Pixel format: yuv420p
Ref frames: 1

Audio
Title: Surround 5.1 - English - DTS-HD MA - Default
Language: eng
Codec: DTS
AVC: No
Profile: DTS-HD MA
Layout: 5.1
Channels: 6 ch
Bitrate: 3981 kbps
Sample rate: 48000 Hz
Bit depth: 24 bit
Default: Yes
Forced: No
External: No

Subtitle
Title: English - Default - PGSSUB
Language: eng
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: Yes
Forced: No
External: No

Audio
Title: Surround 5.1 - English - DTS
Language: eng
Codec: DTS
AVC: No
Profile: DTS
Layout: 5.1
Channels: 6 ch
Bitrate: 1536 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No

Audio
Title: Surround 5.1 - French - Dolby Digital
Language: fra
Codec: AC3
AVC: No
Layout: 5.1
Channels: 6 ch
Bitrate: 640 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No

Audio
Title: Surround 5.1 - Japanese - DTS-HD MA
Language: jpn
Codec: DTS
AVC: No
Profile: DTS-HD MA
Layout: 5.1
Channels: 6 ch
Bitrate: 3985 kbps
Sample rate: 48000 Hz
Bit depth: 24 bit
Default: No
Forced: No
External: No

Audio
Title: Surround 5.1 - Japanese - DTS
Language: jpn
Codec: DTS
AVC: No
Profile: DTS
Layout: 5.1
Channels: 6 ch
Bitrate: 1536 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No

Subtitle
Title: English - PGSSUB
Language: eng
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: French - PGSSUB
Language: fra
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No
```

**System (please complete the following information):**
 - Platform: Ubuntu 23.10
 - Browser: Firefox 124.0.1
 - Jellyfin Version: 10.9 (2024040105)
 
![image](https://github.com/jellyfin/jellyfin-web/assets/137357145/189a5bde-c57e-493c-9fa2-1b57404ca3b3)

**Comment by nyanmisaka** [comment]
DirectPlay or Remuxing?

**Comment by solidsnake1298** [comment]
That's the problem.  It doesn't even get far enough to make that determination.  The log line I posted is the only message that is written to the server log.  Normally it is the following line that would report the playback method.

**Comment by felix920506** [comment]
Was able to confirm using latest unstable build (2024040105)
On MacOS with normal ffmpeg 6.1.1 the following results:
AV1+1xOPUS in WebM / MKV -> direct plays
AV1+2xOPUS in MKV -> (supposed to remux) doesn't play, no ffmpeg started

AV1+2xOPUS in MKV w/ burning in subs by JF:
-> AV1 doesn't play, no ffmpeg process started, master.m3u8 below for reference
-> HEVC / H264 plays

```
#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=5812140,AVERAGE-BANDWIDTH=5812140,VIDEO-RANGE=SDR,CODECS="av01.0.4M.08,Opus",RESOLUTION=720x480,FRAME-RATE=29.97
main.m3u8?DeviceId=TW96aWxsYS81LjAgKE1hY2ludG9zaDsgSW50ZWwgTWFjIE9TIFggMTAuMTU7IHJ2OjEyMS4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzEyMS4wfDE3MDYwNDI5NzYyODE1&MediaSourceId=a45732fe2865911c599ee8ae83adf5e4&VideoCodec=av1,h264,av1&AudioCodec=opus&AudioStreamIndex=2&SubtitleStreamIndex=3&VideoBitrate=2135090036&AudioBitrate=192000&AudioSampleRate=48000&MaxFramerate=29.97003&PlaySessionId=754b8327157c40528ab7a4a8c603c022&api_key=a2a04d6f14cf44d2b09e9ca7a5e2ee9a&SubtitleMethod=Encode&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=d16e4fbf9dc62b522b09b47c1f1d8e83&SegmentContainer=mp4&MinSegments=2&BreakOnNonKeyFrames=True&av1-level=4&av1-videobitdepth=8&av1-profile=main&av1-audiochannels=6&av1-rangetype=SDR&TranscodeReasons=SubtitleCodecNotSupported,%20SecondaryAudioNotSupported
```

**Comment by gnattu** [comment]
Browsers are very picky about the AV1 profiles string. The profiles string we generated is rejected by the browser, and then it will ignore this entry in the `master.m3u8`. Since there are no more streams in our `master.m3u8`, the browser stops processing as it cannot find a playable stream.

We need to lie to the browsers to get the transcoding playback to work properly.
