### ISSUE TITLE
Jellyfin Web 10.9 hangs after a bit of playback

### ISSUE THREAD

**Issue by GeorgeH005** [jellyfin/jellyfin-web#5367]
**Describe The Bug**
No matter the device (Jellyfin Web, jellyfin Web through the android app, findroid, jellyfin webos), and the playback method (transcoding, direct play, direct stream), after a seemingly random amount of minutes of playback, usually < 1hour, jellyfin becomes inaccessible from every device, even when connecting directly (not via reverse proxy) on the same network.

**Steps To Reproduce**
1. Go to any media file.
2. Click on Play
3. Wait...
4. Playback will freeze and server will become inaccessible.

**Expected Behavior**
Playback continues normally and the web server is still accessible.

**Logs**
There aren't any! The only notable entry is the following, which appears after a small amount of time

```[WRN] WS "<IP address here>" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."```

While the web interface is inaccessible the server is still running, and sometimes recovers without a restart.

**System (please complete the following information):**
 - Platform: Debian 12 LXC
 - Browser: Chrome, jellyfin android, jellyfin webOS
 - Jellyfin Version: 10.9.0 (2024040106)
**Additional Context**
Storage is mounted via nfs, confirmed to work flawlessly before 10.9.0

10.8.13 did not exhibit issues

**Comment by jellyfinlover** [comment]
Meet similar problem after upgrading to 10.9.1. It happens on both Windows Jellyfin Media Player and Android client, after clicking play button the server just hang there.
