### ISSUE TITLE
Size of filter dialog is not enough (TV)

### ISSUE THREAD

**Issue by dmitrylyzo** [jellyfin/jellyfin-web#537]
**Describe the bug**
Size of filter dialog is not enough for Russian language on TV. On PC is good enough.

**To Reproduce**
1. Change language to Russian.
2. Go to 'TV Shows'/'Movies'
3. Click on 'Filter'
4. Open up first group (Filters)
5. Content is overflow

**Expected behavior**
Content of filter dialog must not overflow.

**Screenshots**
Tizen browser (Russian)
![jellyfin-web_issue01_04-browser](https://user-images.githubusercontent.com/56478732/66950321-cd18ec00-f060-11e9-9f1c-3984d5388377.png)

Tizen browser (English)
![jellyfin-web_issue01_06-browser_eng](https://user-images.githubusercontent.com/56478732/66950622-68aa5c80-f061-11e9-840c-74d80c03797b.png)

Tizen app (Russian) - even worse
![jellyfin-web_issue01_05-app](https://user-images.githubusercontent.com/56478732/66950332-d3a76380-f060-11e9-9b18-508d80a88635.png)

Chrome in device mode (Russian) 1920x1080 100%
UserAgent: `Mozilla/5.0 (SMART-TV; Linux; Tizen 4.0) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/2.1 Chrome/56.0.2924.0 TV Safari/537.36`
![jellyfin-web_issue01_07-chrome](https://user-images.githubusercontent.com/56478732/66951399-f2a6f500-f062-11e9-9670-6f39e1b0a107.png)

Chrome in normal mode (Russian)
![jellyfin-web_issue01_08-chrome_norm](https://user-images.githubusercontent.com/56478732/66951881-14ed4280-f064-11e9-9944-5802977fa895.png)

**System (please complete the following information):**
 - OS: Tizen 4.0, Kubuntu 19.04
 - Browser: Tizen 4.0, also in Firefox 69.0.2 and Chrome 76.0.3809.100 in "device mode", but it is not exact. Chrome in device mode is equal to app. Firefox is a little worse.
 - Jellyfin Version: 10.4.0+ (develop)

**Additional context**
Dialog has fixed 300px width. On Tizen fonts have become larger.

**Comment by dmitrylyzo** [comment]
5b46f0263a6da91529c5869181e2d8ddd5dfb1a0 issue still exists.

Currently, filter dialog uses this on TV:
```
/* components/filterdialog/style.css */

@media all and (min-width:400px) {
    .dynamicFilterDialog {
        width: 300px;
        margin-left: -150px !important;
        left: 50% !important
    }
}
```

Maybe add something like this (because font size is bigger only in TV layout):
```
@media all and (min-width:400px) {
    .dynamicFilterDialog {
        width: 300px;
        margin-left: -150px !important;
        left: 50% !important
    }

+   .layout-tv .dynamicFilterDialog {
+       width: 600px;
+       margin-left: -300px !important;
+   }
}
```

**Comment by JustAMan** [comment]
Cannot we use `em` unit instead of `px` here to override the need of separate rules?..

**Comment by dmitrylyzo** [comment]
```
@media all and (min-width:400px) {
    .dynamicFilterDialog {
        width: 20.16em;                             ~ 300px/14.88px (font size in px)
        margin-left: -10.08em !important;
        left: 50% !important
    }
}
```
Looks the same as on desktop.

**Comment by JustAMan** [comment]
> Looks the same as on desktop.

Does it mean that it's now working okay on both TV and desktop, or what?

**Comment by dmitrylyzo** [comment]
> Does it mean that it's now working okay on both TV and desktop, or what?

Now this is okay on both.

On desktop, visually no change (in web inspector width is 300.05px).
On TV, the proportions are slightly different due to the lack of a scrollbar.

Firefox 72 (before)
![filter-firefox-before](https://user-images.githubusercontent.com/56478732/72520219-05031b80-386a-11ea-9b5b-e201e6842961.png)
Firefox 72 (after)
![filter-firefox-after](https://user-images.githubusercontent.com/56478732/72520234-0cc2c000-386a-11ea-8a28-011770912c6e.png)

WebOS 3 (before)
![filter-webos-before](https://user-images.githubusercontent.com/56478732/72520382-632ffe80-386a-11ea-893b-a52c05b69a29.png)
WebOS 3 (after)
![filter-webos-after](https://user-images.githubusercontent.com/56478732/72520396-69be7600-386a-11ea-9bc5-9bd12f4ce112.png)

**Comment by JustAMan** [comment]
@dmitrylyzo I sense a PR incoming... 😄
