### ISSUE TITLE
Previously bookmarked URL fails to redirect properly

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-web#5388]
**Describe The Bug**

I have a bookmark for my Jellyfin instance of which the path is `/web/index.html#!/home.html`. When I open this bookmark in 10.9 it redirects to `/web/index.html#/!/home.html` which is invalid (should be `/web/index.html#/home.html`). The page will not load.

**Steps To Reproduce**
1. Open a new tab in your browser that does not have jellyfin-web loaded
2. Set the URL to `/web/index.html#!/home.html`
3. ??
4. Profit

**Expected Behavior**

Either the redirect should be fixed or the "wrong" URL should be loaded correctly.

**Logs**

No relevant logs found

**Screenshots**

![Untitled](https://github.com/jellyfin/jellyfin-web/assets/2305178/f033a358-a456-48b9-b2a2-ee3810570159)

(Guess which theme I use)

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Firefox 124.0.2
 - Jellyfin Version: 10.9 (web f2a5163096d2ced007ce96b0c4e2f711a5a02a75)

**Additional Context**

Only thing keeping me from using Jellyfin

**Comment by nielsvanvelzen** [comment]
Another way to reproduce this issue:

1. Go to our stable (10.8) demo: https://demo.jellyfin.org/stable/
2. Sign in
3. Change to URL to the unstable instance
4. ??
5. Profit

The same behavior exists

**Comment by nvllsvm** [comment]
Caused by https://github.com/jellyfin/jellyfin-web/pull/4958
