### ISSUE TITLE
Use css variables

### ISSUE THREAD

**Issue by enter-a-random-username** [jellyfin/jellyfin-web#5396]
At the moment adjusting something like primary color would result in a lot of lines or a fork with search and replace.

Some things in react are nearly impossible, because it generates unique classes and does a lot of inline stuff. A CSS variables (c|s|w)hould improve the situation. Even options like gutter would be possible and everybody could adjust it in few seconds  without patching or overwriting  SCSS, CSS, TS, TSX and JS files. Just use var(--primary) or other set color in all filetypes.

**Comment by thornbill** [comment]
This is already planned in [the roadmap](https://github.com/orgs/jellyfin/projects/43).
