### ISSUE TITLE
"Add Image" button is missing on mobile implementation 

### ISSUE THREAD

**Issue by SmearyThrower** [jellyfin/jellyfin-web#5426]
Currently it's not possible to change your jellyfin account's pfp on the mobile site/app.

ON DESKTOP 
![Screenshot (1)](https://github.com/jellyfin/jellyfin-web/assets/93036561/5fd41345-4e3c-4734-83a0-9668e9604a26)

ON MOBILE 
![Screenshot_20240427_192238_Jellyfin](https://github.com/jellyfin/jellyfin-web/assets/93036561/55fcc8e1-1931-4a2e-9c06-fc75b8ae037b)

**Comment by jwaresoft** [comment]
Tried to replicate this to work on it, and was unable to in master.  @SmearyThrower does this still replicate for you if you update jellyfin?

**Comment by ArthurBussiere** [comment]
Also tried to replicate and was unable to reproduce.

**Comment by SmearyThrower** [comment]
has been fixed in the latest
