### ISSUE TITLE
Gamepad not working in browser

### ISSUE THREAD

**Issue by ihatetoregister** [jellyfin/jellyfin-web#5445]
**Describe The Bug**

I want to navigate the jellyfin web UI with gamepad. 

**Steps To Reproduce**

1. Connect game controller
2. Load the jellyfish web UI in brower (tested wit Safari and Firefox)
3. Try navigate UI with game controller

**Expected Behavior**

Navigate UI with game controller

**Logs**

Can be provided on request

**Screenshots**

**System (please complete the following information):**
 - Platform: Server (Linux, Ubunu), Client (MacOS)
 - Browser: Safari and Firefox
 - Jellyfin Version: 10.8.13

**Additional Context**

Trying to figure out why it does not work as the feature is supposed to implemented:

https://github.com/jellyfin/jellyfin-web/blob/1711664e51e8908ad148f719036cc24ac539fdfb/src/scripts/settings/appSettings.js#L27
https://github.com/jellyfin/jellyfin-web/blob/1711664e51e8908ad148f719036cc24ac539fdfb/src/scripts/gamepadtokey.js#L88
https://github.com/jellyfin/jellyfin-web/blob/1711664e51e8908ad148f719036cc24ac539fdfb/src/scripts/keyboardNavigation.js#L200 

Could not find the setting mentioned, maybe I'm just blind. I just have a feeling this is not implemented in the server itself, but in the desktop app layer? Could someone confirm this?

Game pad is working fine with Xbox Cloud Gaming and this test page:
https://gamepadtester.net/

**Related**
https://github.com/jellyfin/jellyfin-web/issues/5016

**Comment by ihatetoregister** [comment]
Ok, after a few hours of fiddling it seem to work, it's just very well hidden. For future reference, here is how to enable it:

1. Setting -> Display -> Display mode: TV
2. Settings -> Controller -> Enable gamepad

Could we enable this by default maybe?

**Comment by dmitrylyzo** [comment]
> Could we enable this by default maybe?

No. TV mode is designed for TVs. It lacks some features that Desktop and Mobile have. For example, there's no Dashboard.
So it is up to the user to enable the TV mode.

In case you are using Jellyfin Media Player: AFAIK, you can run it with the "tv" option (not sure what it's called), then TV mode will be selected automatically.

FYI, keyboard (gamepad) navigation is only available in TV mode, as there is no focus indicator in Desktop and Mobile.
