### ISSUE TITLE
Some settings are saved for the browser, not for the user

### ISSUE THREAD

**Issue by EvgeniyDoctor** [jellyfin/jellyfin-web#5456]
**Describe The Bug**

Jellyfin does not save settings in "Localization": "Display language" and "Date time locale" for user. Instead Jellyfin saves it for browser. I have a lot of devices and a lot of operating systems, and every time i have to choose same things over and over again.
I consider this as an error, but if this behaviour is intentional - well, this is a pretty wierd decision.

**Steps To Reproduce**

1. Go to user settings
2. Click on "Display"
3. Change values for "Display language" and "Date time locale" from "Auto" to something else
4. login as the same user in another browser
5. see "Auto" and "Auto" in these fields again

**Expected Behavior**

Settings should be saved for user, not for browser.

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Platform: Linux, DSM 6
 - Browser: Brave, Vivaldi
 - Jellyfin Version: 10.8.13

**Additional Context**

**Comment by thornbill** [comment]
This is currently working as expected, but it could definitely be improved... a related feature request can be found [here](https://features.jellyfin.org/posts/2162/user-settings-saved-across-devices)
