### ISSUE TITLE
Web interface broken in some browsers like Waterfox or IceWeasel

### ISSUE THREAD

**Issue by snintendog** [jellyfin/jellyfin-web#546]
When Using the Web interface on a desktop browser the listed tabs in the dashboard fail to load
General
Playback
DLNA
Live TV
DVR
Scheduled Tasks
any Plugin added tab
and The Metadata Page
However This doesnt happen at all on mobile browsers and the android app
Tested desktop Browsers include Firefox,waterfox,opera,Microsoft edge, Internet explorer
Tested Mobile browsers are Icecat, Chrome, Unamed sony made browser, and the official android app(need to test tv one)
when trying on a fresh install the wizard is affected as well.

The background is on a Win10 x64 machine the tested ones that replicate it are the portable install of 4.0 and the installer. Originally a 3.7 portable was on there i have tested a clean install as well with both version of 4.0 no profiles with and without installed as service complete removal of appdata folder and the like still causes this. I have tested with adblockers and script blockers off.

**Logs**
[log_20191020.log](https://github.com/jellyfin/jellyfin/files/3748034/log_20191020.log)

**Screenshots**
![jellyfin issue](https://user-images.githubusercontent.com/5448989/67162469-35eab780-f332-11e9-94ce-5df935cf46bd.PNG)
as shown the browser navigates to the general tab but nothing loads the working tabs work as intended. 
![jellyfin issue 2](https://user-images.githubusercontent.com/5448989/67162649-f02eee80-f333-11e9-9dca-63c4ce976f1c.PNG)
This is the wizard the box is expanded to select language.

 - OS: Win10x64 portable and install
 - Browser: Waterfox 56.2.12 and 56.2.14, Microsoft Edge, Icecat mobile and chrome mobile Noting that requesting the desktop site there doesnt break the tabs
 - Jellyfin Version:10.4.0
 - Reverse proxy: none

**Comment by anthonylavado** [comment]
@snintendog I don't think we'll ever be able to support IE 11, but we can see about the others. Edge is going to eventually be Chromium, so I'm less worried about that.

@jellyfin/web Looks like there's several JS errors in:

* Waterfox
* GNU IceCat

I'm not sure what versions of Gecko those are running and what the source of the error is though.

**Comment by snintendog** [comment]
NP IE and edge are just what i use for checking standard tests if something is broken on a page looks like the internet is now more chrome focused now might have to find a good fork of it that doesn't eat ram.

https://github.com/MrAlex94/Waterfox this is the the github of waterfox if it helps any.

**Comment by snintendog** [comment]
Would like to confirm that 10.4.1 is having the same issue. Same method to reproduce. Waterfox is up to date now on 2019.10(they changed how they number the versions since last time) issue still persists.  Firefox and chrome still work Perfectly fine.

**Comment by dkanada** [comment]
If you could post the browser logs when you try to load the site that might indicate an issue. I'm 90% sure the issue isn't a server problem but a browser compatibility problem.

**Comment by snintendog** [comment]
Its no doubt a JS error we ruled out the server last time during 10.4.0 question is why and how to work around it.

[jellyfin 10.4.1 error].txt](https://github.com/jellyfin/jellyfin-web/files/3827550/jellyfin.10.4.1.error.txt)

this is about all i can do not sure where i can find the full log apparently there is a type error in  fnchecked.js?v=10.4.1 "TypeError: $ is undefined" and in legacy/fnchecked however Firefox never loads this and is fine log is the same except that TypeError fnchecked is never sent to it. 10.3.7 works but the fnchecked is never being sent to waterfox in it like firefox in 10.4.1 not sure what is triggering FNchecked to be sent or what it does.... checking all other pages that gives issues different JS but the same error occurs "RequireJS error: TypeError: $ is undefined. Failed modules:   site.js:381:9" 

got ahold of an old ipad. safari is also doing this, ipad chrome as well The Ipad is on IOS 10.3.3 so it is older and out of date it seems that there is new expression in the JS that throws off anything that isn't cutting edge compatibility wise must have been introduced semi recently 2-3 years esitmate.

**Comment by JustAMan** [comment]
Might be related to https://github.com/jellyfin/jellyfin-web/issues/572

**Comment by dkanada** [comment]
We changed the define statement for jQuery which is also used in a legacy function called `fnchecked` that I've been meaning to remove. Alas, it still exists, and apparently something is wrong with the jQuery dependency in that file.

**Comment by JustAMan** [comment]
So this should hopefully be fixed when we introduce Babel part into webpack... right @MrTimscampi ?

**Comment by dkanada** [comment]
indeed

**Comment by MrTimscampi** [comment]
It should help, however for Firefox (and Firefox-based browsers) we support pretty much the last 2 version (So 72 and 73) as well as ESR (on which Waterfox is apparently based, so Firefox 68).

Our Smart TV targets should cover most of what's needed for older Firefox versions, but no guarantee :p

We dropped support for IE11 as well (It's still technically in the code, but nobody tests it in the team and we don't target it in the Browserslist)

**Comment by snintendog** [comment]
Would like to report that waterfox 2019.10(droped for newer version) is still experiencing the same problems in the same area /general tab users play back in the dashboard using latest Firefox/Chrome still works as does the Waterfox Current branch. Interestingly though the 2020.03.1 of Waterfox classic is now working it seems they finally fixed it on their end. 
![Jellyfin 10 5 0 Web issue](https://user-images.githubusercontent.com/5448989/76693914-acba8100-6642-11ea-8de3-ba495ecbdc4d.PNG)

IE 11 is as expected not working due to how archaic it is though interestingly i had at least gotten the log in screen this time its only loaded the background to it.

The archaic Version of Safari 10 from my Old Ipad 2 does however works perfectly. On the same ipad the 71.0.3578.89 chrome on it works perfectly as well. Until i get a better way of doing this for the older generation Safari is my go to for just adding it to the Home Screen

Ice Cat mobile is Also working as intended still an older version a newer one released...the new one works as well 68.4.2 ESR

The 3 things i personally needed has been fixed. I'd say this is Good as it possibly will be.
