### ISSUE TITLE
Videos encoded with Opus 5.1 don't play properly on some stereo clients 

### ISSUE THREAD

**Issue by SmearyThrower** [jellyfin/jellyfin-web#5469]
**Describe The Bug**
Videos encoded with Opus 5.1 codec are not being played properly on some stereo clients(only tested on web player Android). which causes distorted audio.

**Expected Behavior**
The videos should be played with played as expected without transcoding or worst case should be direct streamed to stereo for clients that do not support surround sound.

**Screenshots**

https://github.com/jellyfin/jellyfin-web/assets/93036561/d55bacb0-adeb-48bc-8a01-2d903ea8ef3c

[This issue has been replicated across multiple files. Files one and two, both encoded with Opus 5.1, exhibit the problem, while file three, encoded with Opus 2.0, plays correctly.]

https://github.com/jellyfin/jellyfin-web/assets/93036561/ef4e6990-1bfa-4fa5-af05-8685f8c9007f

[How file one is supposed to sound.]

**System (please complete the following information):**
 - Platform: Android 14
 - Browser: Chrome/WebView 124
 - Jellyfin Version: 10.9

**Comment by Ewillian9** [comment]
I had similar issues too, no idea if it also apply on 7.1

**Comment by gnattu** [comment]
See jellyfin/jellyfin-ffmpeg#386

**Comment by gnattu** [comment]
Should be fixed: https://github.com/jellyfin/jellyfin-ffmpeg/pull/386

**Comment by SmearyThrower** [comment]
fixed🔥
