### ISSUE TITLE
Missing deprecated tabs in dashboard 10.9

### ISSUE THREAD

**Issue by shemanaev** [jellyfin/jellyfin-web#5484]
**Describe The Bug**

Is there any migration path for deprecated tabs functionality from? https://github.com/jellyfin/jellyfin-web/blob/a634bc798e4ce563d9266ce2edc40b1812c0d48d/src/components/AppHeader.tsx#L20-L26

Mainly interested in this method:

```js
LibraryMenu.setTabs();
```

I've been using it in plugin UI (like it was [implemented in Playback Reporting plugin](https://github.com/jellyfin/jellyfin-plugin-playbackreporting/blob/c8f24e261cbb8bbc63485a539bf63ef1d4a0aa8f/Jellyfin.Plugin.PlaybackReporting/Pages/user_report.js#L74)) and now it appears to be broken (there are no more tabs in Playback Reporting).

**Steps To Reproduce**

**Expected Behavior**

**Logs**

**Screenshots**

10.8
![10.8](https://github.com/jellyfin/jellyfin-web/assets/1058537/7b205902-bf42-4254-b7a2-77c918d9e11f)

10.9
![10.9](https://github.com/jellyfin/jellyfin-web/assets/1058537/7ffbe1eb-7280-423e-9a91-ff08ed6dc9a7)

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Firefox
 - Jellyfin Version: 10.9

**Additional Context**

**Comment by Cloud9Developer** [comment]
Nice! was just looking for this! Any ETA on release with this fix?

**Comment by thornbill** [comment]
[Now](https://forum.jellyfin.org/t-new-jellyfin-server-web-release-10-9-2) 😎

**Comment by Cloud9Developer** [comment]
My hero!

**Comment by Kevinjil** [comment]
Hi @thornbill, the old behaviour does not seem to be fully restored, as noted in https://github.com/Kevinjil/Jellyfin.Xtream/issues/99#issuecomment-2118715661. Is it intended that you can no longer use `ApiClient.getUrl("web/ConfigurationPage", "MyName")` as tab `href`?

**Comment by thornbill** [comment]
You should only specify the part of the path after the `#`
