### ISSUE TITLE
Trickplay cannot be turned on or off on mixed libraries

### ISSUE THREAD

**Issue by BobHasNoSoul** [jellyfin/jellyfin-web#5490]
**Describe The Bug**
people say you can enable trickplay in each library however there is no option for it once the library has been created, this gives you no option to turn it on for the older librarys that were already made.

**Steps To Reproduce**

1. Go to '/web/index.html#/dashboard/libraries'
2. Click on 'the ... for the library that you want to enable trickplay for'
3. Click on 'manage library'
4. Scroll down and look for the trickplay option there isnt one

**Expected Behavior**
for it to have a way to turn it off or on for existing libraries without the need to delete the library and rescan it when deciding to turn trickplay off or on.

**Logs**
there are no relevant logs

**Screenshots**
no applicable screenshots 

**System (please complete the following information):**
 - Platform: Ubuntu 
 - Browser: Firefox and Chrome
 - Jellyfin Version: 10.9.0

**Additional Context**
pretty sure its a bug or an oversight.. sorry if it isnt and im just using it wrong.

**Comment by BobHasNoSoul** [comment]
temporary workaround is to manually edit the chunk.js  (seems to be different for me and my docker build so im not sure the naming standard but it is this on my normal install `95454.d1b2509d245890e33deb.chunk.js`) to add this 


`<div class="trickplaySettingsSection hide"> <h2>${Trickplay}</h2> <div class="checkboxContainer checkboxContainer-withDescription fldExtractTrickplayImages"> <label> <input type="checkbox" is="emby-checkbox" class="chkExtractTrickplayImages"/> <span>${OptionExtractTrickplayImage}</span> </label> <div class="fieldDescription checkboxFieldDescription">${ExtractTrickplayImagesHelp}</div> </div> <div class="checkboxContainer checkboxContainer-withDescription fldExtractTrickplayDuringLibraryScan advanced"> <label> <input type="checkbox" is="emby-checkbox" class="chkExtractTrickplayDuringLibraryScan"/> <span>${LabelExtractTrickplayDuringLibraryScan}</span> </label> <div class="fieldDescription checkboxFieldDescription">${LabelExtractTrickplayDuringLibraryScanHelp}</div> </div> </div>`

inside the the html section that works and gives it the ability to be enabled on preexisting libraries without the need to delete and rescan the full libraries some users already have.

note: to find the exact chunk to edit you need to use network tab after opening the admin page for libraries inside of your firefox or chrome browser, then open the manage libraries page and the chunk should be inside the network tab with another one you are looking for the library settings page.

**Comment by ferferga** [comment]
Is your web client also in 10.9?

**Comment by BobHasNoSoul** [comment]
It is the 10.9.0 webclient from the deb file provided for jellyfin-web from
the Ubuntu sudo apt install jellyfin-web

The admin page has updated to 10.9.0 also just has this one bug for me but
the edit in my previous post fixes this issue

**Comment by nicknsy** [comment]
This is likely related to https://github.com/jellyfin/jellyfin/issues/11284 if your library types are set to mixed movies & tv shows.

**Comment by anujsedhai** [comment]
i'm also facing the same issue.
Jellyfin version: 10.9.2 (Docker installation)
Docker base image: linuxserver/jellyfin

**Comment by Patryk122PL** [comment]
Same issue Docker image: jellyfin/jellyfin:10.9.4.

Trickplay settings is visible while configuring new mixed type library, but after saving it, it's no longer there. Confirmed on multiple browsers and with cache removed.

**Comment by Xeddius** [comment]
Updated Jellyfin, enabled Trickplay, no option visible for any existing library.

**Comment by sethro2** [comment]
I just upgrade to v10.9.7 of the Windows installer and seeing the same issue.  Trickplay could be toggled on a "movies" library however not for the libraries listed as "other" which contain tv shows and personal videos.

**Comment by voronind-com** [comment]
I still can't see it on `10.10.5`. Am I missing something?
