### ISSUE TITLE
[Issue]: Secondary subtitle does not appear to work with .ass subs (maybe only works with srt?)

### ISSUE THREAD

**Issue by xrishox** [jellyfin/jellyfin-web#5491]
### Please describe your bug

When I load up a video file that uses srt subtitles secondary subtitle appears to work as expected, but if you switch to .ass subs the feature disappears.

### Reproduction Steps

go to the web player, load a video with .ass subtitles (for example most anime) and see that the secondary subtitle isn't there. then switch to srt and see that that feature appears.

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS:linux 24.04
- Linux Kernel:
- Virtualization: docker
- Clients:web browser
- Browser: chromium browsers on both windows and macos.
- FFmpeg Version:whatever ships with the docker container
- Playback Method:web browser
```

### Jellyfin logs

```shell
this isn't something that shows in the logs?
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thornbill** [comment]
Yeah this only works for simple text format subtitles. Issue based subtitles and complex formats like ass/ssa cannot be supported because there is no way to ensure the subtitles do not overlap.

**Comment by DrMcCoy** [comment]
If you look at mpv, it currently allows that. It even allows for (optional) full styling of the secondary subtitles, but that usually doesn't work well (as you said).

However:
- By default, it strips all formating from the secondary subtitles
- It then positions the subtitles at the top by default, with the assumptions that even a fully-style primary subtitle track usually displays them at the bottom

You could do that same. Or, at least, allow for primary subtitles ASS, secondary subtitles SRT, which doesn't have most of the issues from the get-go. This is also not functional in Jellyfin Web at the moment. Jellyfin only allows for SRT primary *and* secondary, as soon as ASS is involved, even for the primary one, it disallows a secondary one.
