### ISSUE TITLE
Loading Webpage "hangs" until reload with CTRL + SHIFT + R (without cache)

### ISSUE THREAD

**Issue by DaRealHansForSure** [jellyfin/jellyfin-web#5494]
**Describe The Bug**
Every now and then, when you call up the Web UI, it gets stuck at the Jellyfin logo.

In the Network tab you can see that it is no longer loaded as the main chunk.
However, if you call up the page again with CTRL + SHIFT + R, everything loads normally.

This happens from time to time. Disable Cache in the Network Developer does not help either.

Version 10.8.z rlease of jellyfin-web works as expected.

**Steps To Reproduce**
1. Start instance with web 10.9.1
2. Finish the first setup
3. Login
4. Wait some time, and call the jellyfin web page again

**Expected Behavior**
Loading fully Web UI

**Logs**
No Errorlogs appears in Browser.

**Screenshots**
![bla](https://github.com/jellyfin/jellyfin-web/assets/3436574/264d365c-3c68-4964-861a-2a73f3ae8d01)
![bla2](https://github.com/jellyfin/jellyfin-web/assets/3436574/c7167228-fae5-489d-af0e-bf29489321c4)

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Brave 1.65.132
 - Jellyfin Version: 10.9.1

**Comment by DaRealHansForSure** [comment]
I have just made some additional observations.

When this error occurs, I see activity on the “<head>” element in the DOM in the Dev Tools, but nothing is effectively changed visually (too fast)

**Comment by ItzzCode** [comment]
Also experiencing this issue on Firefox 125.0.3 for Linux Mint, using the same version. It only began occurring when I upgraded.

**Comment by hjpaul7** [comment]
+1 also seeing this

**Comment by dmitrylyzo** [comment]
> ![bla](https://private-user-images.githubusercontent.com/3436574/330125012-264d365c-3c68-4964-861a-2a73f3ae8d01.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODgwNjIsIm5iZiI6MTcxNTY4Nzc2MiwicGF0aCI6Ii8zNDM2NTc0LzMzMDEyNTAxMi0yNjRkMzY1Yy0zYzY4LTQ5NjQtODYxYS0yYTczZjNhZThkMDEuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTRUMTE1NjAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDEyNWNjZjNkZjI3ZjFjNGZhNjc1YTI1ZjkwODYzODc2N2JhYzExYTQzM2MzNmFhZjFmYWZlOGQ4MDU5NDE4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.n5gjSBikTi0ycmroIT6vk3CvzY7aV3ue6MwPyYwqvSk)

That's the old logo.
Do you use a reverse proxy (_you on Windows, but still_)?
Some proxies can cache a lot.

**Comment by ItzzCode** [comment]
Not the OP, but it occured to me even though I connected directly to the Jellyfin Server without a reverse proxy (inadvisable I know, but eh).

**Comment by cthulhuz** [comment]
I have experienced the same issue. Had to downgrade to 10.8 due to it.

**Comment by DaRealHansForSure** [comment]
I experienced this bug already in a early state of 10.9 Web as Information

**Comment by buzzkillingtonne** [comment]
I've also been experiencing this issue.

Server running on Debian 12, accessing from Firefox and Chrome on both Windows and EndeavourOS. When it happens again I'll need to test accessing it without the NGINX reverse proxy, however restarting the service on the server seems to fix the issue temporarily.

**Comment by ramonskie** [comment]
also experiencing this issue since 10.9.1
browser: brave, firefox

jellyfin is hosted on docker within a synology nas behind the synology.me proxy

**Comment by Ryah** [comment]
Also experiencing this

Hosted on Docker.
Hangs on everything I try it on. Edge, Chrome, Floorp, and Android. 

Can only access it with Jellyfin-vue frontend or Jellyfin Media Player.

Found no solution so far. Even clearing cache and cookies didn't help.

**Comment by thornbill** [comment]
Please check the browser console for errors

**Comment by Ryah** [comment]
![image](https://github.com/jellyfin/jellyfin-web/assets/14987609/07c64506-4688-476d-9727-dba8ee9dfa23)

Sorry, here's the errors I found in console.

**Comment by Ryah** [comment]
![image](https://github.com/jellyfin/jellyfin-web/assets/14987609/32c9e3f5-4077-4293-9565-7d790d9c73e8)
Sorry, here are the errors I'm seeing in console.
