### ISSUE TITLE
Album cover missing when view is smaller

### ISSUE THREAD

**Issue by nvllsvm** [jellyfin/jellyfin-web#55]
**Larger Size** - The album cover is clearly visible.
![image](https://user-images.githubusercontent.com/6550543/51517489-e8fca380-1de8-11e9-8535-3809bedb6d32.png)

**Window Shrunk Slightly** - No album cover, empty space instead.
![image](https://user-images.githubusercontent.com/6550543/51517521-fd40a080-1de8-11e9-847b-88d54b49d6a1.png)

**Comment by dkanada** [comment]
I think this was fixed in #15, what version of the web client are you using?
