### ISSUE TITLE
External subtitle slowly go out-of-sync on 10.9

### ISSUE THREAD

**Issue by Eisaichen** [jellyfin/jellyfin-web#5513]
**Describe The Bug**
External subtitles will slowly go out of sync and get worse while playing continues.
It's synced when the playing just started. subtitle files are good, it is synced when playing with other players and also synced on 10.8.13.
fallback font is used. won't have this issue if transcoding.
It started about two months ago with 10.9 unstable build.
Subtitle type: ASS
Video for test: https://1drv.ms/u/s!AmrsUQ8bL7octplXoHqfBMdYMJSurg?e=ZQcTEj

**Steps To Reproduce**
1. Play a video that is longer than an hour.
2. Enable External subtitle
3. Play it for 10 minutes or longer
4. Check the subtitle to see if it's still in sync

**Expected Behavior**
Subtitles are in sync for the entire time.

**Logs**
No errors

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Edge
 - Jellyfin Version: 10.9.1

![image](https://github.com/jellyfin/jellyfin-web/assets/12467320/0c150f93-3d85-4a9d-bfb3-c414586ecbd5)

**Comment by PCJones** [comment]
Pretty sure I'm having the same problem since upgrading to 10.9. Client doesn't seem to matter, experienced it on Jellyfin Media Player (Windows) and Findroid.

Running on Debian 11 via linuxserver docker image.

**Comment by PeachesMLG** [comment]
Im also experiencing this, Sometimes it can be as much as 10 seconds ahead.

Restarting my servers and refreshing the cache seems to "fix" it

**Comment by Eisaichen** [comment]
This issue seems fixed with the latest version 10.9.2.
Close this issue for now, please let me know if you guys still experiencing the problem.

**Comment by Eisaichen** [comment]
10.9.2 seems to mitigate this problem with this PR https://github.com/jellyfin/jellyfin/pull/11689, however, it is not completely fixed.
And the audio seems also out of sync with the subtitles.
