### ISSUE TITLE
[Issue]: At the end of video playback its not possible to skip backwards

### ISSUE THREAD

**Issue by ItsOnlyBinary** [jellyfin/jellyfin-web#5516]
**Describe The Bug**
When the video playback finishes and the static show image is shown (black screen on JMP) it is not possible to skip to a previous point within the video and have playback resume.

It appears the currently playing video is unloaded even though the progress bar and other parts are still shown, clicking "skip to previous" loads the previous episode starting at the new time selected for the ended video.

This seems to also have the side effect on JMP that pressing "back" does not exit fullscreen, leaving you stuck in fullscreen mode without scroll working correctly and the only way to exit fullscreen is to start another video. (I will create a separate issue on JMP repo for this but I suspect solving the current media being unloaded would solve that issue too)

**Steps To Reproduce**
1.    Ensure "Play next episode automatically" is disabled (I have "show next video info during playback" enabled)
2.    Start an episode
3.    Skip near the end
4.    Let it play until the end
5.    Try and skip to a position before the end of the show

**Expected Behaviour**
Expect the player to resume playing from the chosen position.

**Logs**
No applicable log entries found in either browser console or jellyfin.

**Screenshots**

**System (please complete the following information):**
 - Platform: Windows 10
 - Browser: Firefox 125.0.3
 - Jellyfin Version: 10.9.1

**Additional Context**

**Comment by ConnorS1110** [comment]
I have a PR up for this now, but I've got a feeling the owners are not going to like the solution, but playback is a very complicated web of events and this is currently the best I could come up with. We''ll see what happens with it
