### ISSUE TITLE
Unable to save modified metadata path setting

### ISSUE THREAD

**Issue by ConnorS1110** [jellyfin/jellyfin-web#5520]
**Describe The Bug**
Cannot saved settings of modified metadata path

**Steps To Reproduce**
1. Go to Admin Dashboard
2. Go to "Paths"
3. Change metadata path to a different location
4. Click "Save"
5. Get an error message saying "There was an error processing the request. Please try again later."

**Expected Behavior**
When I change the location of the metadata folder, I should be able to save that setting

**Logs**
```
XHRPOST
https://<my-url>/System/Configuration
[HTTP/2 500  9ms]

	
POST
	https://<my-url>/System/Configuration
Status
500
VersionHTTP/2
Transferred239 B (25 B size)
Referrer Policy no-referrer
DNS Resolution DNS over HTTPS

    	
    access-control-allow-origin
    	*
    alt-svc
    	h3=":443"; ma=2592000
    content-type
    	text/plain
    date
    	Thu, 16 May 2024 13:28:23 GMT
    server
    	Caddy
    server
    	Kestrel
    X-Firefox-Spdy
    	h2
    x-response-time-ms
    	6.2165
    	
    Accept
    	*/*
    Accept-Encoding
    	gzip, deflate, br, zstd
    Accept-Language
    	en-US,en;q=0.5
    Authorization
    	MediaBrowser Client="Jellyfin Web", Device="Firefox", DeviceId="<device-id>", Version="10.9.1", Token="<token>"
    Connection
    	keep-alive
    Content-Length
    	3862
    Content-Type
    	application/json
    Host
    	<my-url>
    Origin
    	https://<my-url>
    Priority
    	u=4
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	same-origin
    Sec-GPC
    	1
    TE
    	trailers
    User-Agent
    	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0
```

**System (please complete the following information):**
 - Platform: Windows 11 23H2
 - Browser: Firefox
 - Jellyfin Version: 10.9.1

**Additional Context**
Due to the MASSIVE size that trickplay takes up, I can't keep that locally. I wanted to move the metadata folder to an external hard drive that actually has the space to accommodate for this feature

**Comment by thornbill** [comment]
Looks like this generated a server error so providing the server logs from this time would be helpful.

**Comment by thornbill** [comment]
Does the Jellyfin user have execute permissions for that directory? If it only has read it might see that it exists but be unable to actually open it.

**Comment by ConnorS1110** [comment]
Changing the permissions and making sure the correct group owned the folder worked. I have a task running to generate trickplay images (going on day 3 and its halfway done). Will that task move the already generated and newly generate trickplay images to the new folder, or do I need to restart?

**Comment by thornbill** [comment]
Great! Yes, I believe those will need regenerated.

**Comment by ConnorS1110** [comment]
If I change metatdata locations, is it supposed to move the already existing metadata over? I see all the images for my titles in my media libraries just completely gone now. If it is supposed to migrate how long should that take? I changed the location over 4 hours ago now so I would expect whatever migration would be done by now. Is there a way I can force rebuild all the metadata?

**Comment by thornbill** [comment]
I don't believe Jellyfin migrates anything but I'm not sure.
