### ISSUE TITLE
Jellyfin Web - Activity Dashboard, not resizeable columns

### ISSUE THREAD

**Issue by h1ght** [jellyfin/jellyfin-web#5524]
**Describe The Bug**

It is not Possible to resize the columns in the table in the dashboard activity.
**Steps To Reproduce**

open dashboard activity and try to resize

**Expected Behavior**
expected to resizes the columns to expand the infos withtin.
**Logs**
doesnt get needed?
**Screenshots**
![Uploading user.PNG…]()

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Firefox and Edge, tested with 2 different PCs
Server-Version
10.9.1
Web-Version
10.9.1
Build-Version
10.9.1

**Additional Context**
official docker image jellyfin/jellyfin

regards

**Comment by Bedz01** [comment]
Yep, same issue for me.
![JELLY](https://github.com/jellyfin/jellyfin-web/assets/10061448/d741db71-bd0d-4b49-b53c-82bda7c3ff42)

**Comment by LittleBigOwI** [comment]
This isn't a bug. Jellyfin is currently using @mui/x-data-grid v.6 to render the activity page, which does not come with resizeable columns by default. 

See:
- [mui v6 docs](https://v6.mui.com/x/react-data-grid) (no resizeable columns for free version)
- [mui v7](https://mui.com/x/react-data-grid/) (resizeable columns on free version)

**Comment by thornbill** [comment]
This has been added for the upcoming 10.10 release.
