### ISSUE TITLE
alphaPicker: page padding on the wrong side in TV mode

### ISSUE THREAD

**Issue by dmitrylyzo** [jellyfin/jellyfin-web#553]
**Describe the bug**
In TV mode, the page with alphaPicker has padding on the opposite to the alphaPicker side. As a result, on a real TV (and in device mode of browsers) keyboard navigation jumps out from the alphaPicker to an overlaped card.

**To Reproduce**
1. Turn on the TV display mode in the settings (or activate device mode with TV UserAgent in browser).
2. Go to Music/Albums (or other pages with the alphaPicker).
3. The alphaPicker on the right, but the padding (the wider one) on the left.

**Expected behavior**
In Desktop and Mobile display modes padding is on the right (as the alphaPicker). So I suppose the same should be in TV display mode.

**Screenshots**
TV (Firefox)
![jellyfin-web_issue04_03-tv](https://user-images.githubusercontent.com/56478732/67625895-ff8acc00-f84c-11e9-8819-0dfe8686680a.png)

TV (Firefox)
![jellyfin-web_issue04_02-tv](https://user-images.githubusercontent.com/56478732/67625899-07e30700-f84d-11e9-9659-9ff64f2777bc.png)

Desktop (Firefox)
![jellyfin-web_issue04_01-desktop](https://user-images.githubusercontent.com/56478732/67625897-0580ad00-f84d-11e9-80df-1284061a3932.png)

**System**
 - OS: Kubuntu 19.04 x64
 - Browser: Firefox 70, Chrome 76.0.3809.100
 - Jellyfin Version: 10.4.z (0d8bc6fb46f0f105b34869d82d0ab826b0e78251)

**Comment by JustAMan** [comment]
This is intentional (don't know why tho), see in unminify PR: https://github.com/jellyfin/jellyfin-web/pull/509/files#diff-1300564f83a1c0f9bc3221666118b2eaR219-R223

**Comment by dkanada** [comment]
We should fix it regardless, not sure why it does that in the first place.

**Comment by JustAMan** [comment]
Wasn't saying we shouldn't, was just giving a reference to a potential place where this thing happens.

**Comment by JustAMan** [comment]
shoo bot, it should be fixed soon

**Comment by dmitrylyzo** [comment]
Fixed in `master`
