### ISSUE TITLE
Sync Play Button hidden even though permission is set correctly

### ISSUE THREAD

**Issue by Rankarusu** [jellyfin/jellyfin-web#5557]
**Describe The Bug**
I really hope this is the right place to post this issue. Maybe I'm just too dumb to find the right option in the admin panel, but i recently noticed the sync play button missing in the web player. I checked if it has something to do with incorrect permissions but my user has "CreateAndJoinGroups" set, which is also what the server delivers via json when the user endpoint is called. Funnily enough, the button is there. I can remove the "hide" CSS class from it via dev tools and use it like nothing happened.

**Steps To Reproduce**
1. Open Jellyfin web
2. Open dev tools
3. find header buttons via inspect
4. Remove hide class from sync button

**Expected Behavior**
Button is shown when permission is set

**System (please complete the following information):**
 - Platform: Arch Linux, Windows 10
 - Browser: Brave, Chrome
 - Jellyfin Version: 10.9.2

**Comment by thornbill** [comment]
Please verify that syncplay is included in the list of "plugins" enabled in the web config. Typically you should receive an updated version of the config file when you update Jellyfin, but if you have made customizations in the past that might not be the case.

[Default config.json for 10.9](https://github.com/jellyfin/jellyfin-web/blob/release-10.9.z/src/config.json#L48)
[General documentation about config.json](https://jellyfin.org/docs/general/clients/web-config)

**Comment by Rankarusu** [comment]
> Please verify that syncplay is included in the list of "plugins" enabled in the web config. Typically you should receive an updated version of the config file when you update Jellyfin, but if you have made customizations in the past that might not be the case.
> 
> [Default config.json for 10.9](https://github.com/jellyfin/jellyfin-web/blob/release-10.9.z/src/config.json#L48) [General documentation about config.json](https://jellyfin.org/docs/general/clients/web-config)

Ah, that was it. Yeah, I edited that config. Thank you so much!
