### ISSUE TITLE
Upgrading Jellyfin server from v10.8.13 to v10.9 will retain previous dummy chapter interval value despite the Web UI showing a value of 0.

### ISSUE THREAD

**Issue by maru801** [jellyfin/jellyfin-web#5559]
**Describe The Bug**
Before upgrading my server to v10.9, I didn't have chapter image extraction enabled on any of my libraries, so I never touched and left alone the dummy chapter interval setting at its default value. After I upgraded to v10.9 when it came out, I decided to enable chapter images on all of my libraries. However, I only wanted it to create chapters for items in my libraries that actually had chapter files. I didn't want to create dummy chapters. When updating from v10.8.13 to v10.9.#, the dummy chapter interval value is set to 0 in the dashboard. So I assumed dummy chapters were disabled because the setting states a value of 0 will disable dummy chapters.

So after the chapter image scheduled task I manually ran was finished, I found that all of my video files that didn't have any chapter files had chapter images created with 5 minute intervals. What clued me in why these were so (5-min intervals) was this comment from another issue: https://github.com/jellyfin/jellyfin-web/issues/5555#issuecomment-2119130785

That got me to think that when you update the server to v10.9 from v10.8.13, the default value of 300 doesn't really get changed to 0, only the display on the Web UI. The user has to manually change the value, save it, then change and save back to 0 to truly disable them and get the server to understand you want a value of 0.

I did just that, then went to test it out. I deleted the chapters of a few videos that don't have chapter files, and sure enough, Jellyfin doesn't create the 5-min interval chapters anymore for them.

**Steps To Reproduce**
1. Install v10.8.3 and never touch any chapter image settings (leaving them all as default)
2. Upgrade your server to v10.9.2
4. Don't mess with the dummy chapter value in the upgraded server
5. Enable chapter extraction on a library that has some videos without chapter files, then run a chapter image extraction scan on it
6. You'll see dummy chapters created in 5-min intervals on videos that don't have chapter files

**Expected Behavior**
If the Web UI shows a value of 0 for the dummy chapter interval, and it states the value of 0 will disable dummy chapters, no dummy chapters should be made.

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Chrome, Firefox
 - Jellyfin Version: v10.9.2

**Additional Context**
This issue happened to me when I was on v10.9.1, but I assume v10.9.0 to v10.9.2 are affected.

**Comment by maru801** [comment]
Ok, so I don't have an idea on why the dummy chapters are being produced. I reset the dummy chapter interval to 0, and my server regenerated all the dummy chapter images again after I ran the chapter creation task. I'm at a loss on why these won't stay disabled.

For some reason, they were not recreated when I deleted a few, but when I deleted all the chapter folders from my config folder, then recreated them all, they were brought back.

**Comment by rickgitdone** [comment]
I have loaded the latest version on docker v10.9.3 and all related issues with audio and Firefox seem to be resolved.

**Comment by maru801** [comment]
> I have loaded the latest version on docker v10.9.3 and all related issues with audio and Firefox seem to be resolved.

Did you post this by mistake under this issue?

Anyways, to give an update, I found out why the dummy chapters were coming back despite having been deleted and setting the interval to 0.

After setting the interval to 0, all I had to do was to rescan the episodes/movies with anything but the "Scan for new and updated files" to actually update the server that it no longer has dummy chapters. After that, the dummy chapters disappear and any future chapter extraction task will not produce any more.

**Comment by maru801** [comment]
I'm going to close this issue as it seems like it will get sorted as time moves on. Eventually, nobody will be upgrading from v10.8.13.

For those affected by this, do the following:
1. Change the dummy chapter interval to any number, then back to 0 (to truly set it to 0)
2. Run a scan with either "Search for missing metadata" or "Replace all metadata" over the affected videos that don't actually have chapters. If you want to do it library-wide, run the scan in "Dashboard > Libraries" and choose a specific library to run it in.
3. If you reload the video page, the dummy chapters should be removed and no longer regenerate on the next chapter extraction task.
