### ISSUE TITLE
Since v10.9, a lot of my cover art for media is displayed in a square which crops out a lot of the image.

### ISSUE THREAD

**Issue by maru801** [jellyfin/jellyfin-web#5560]
**Describe The Bug**
Before v10.9, all the cover art for my shows were properly displayed in a rectangle, with only some image resolutions causing the cover art display to actually become a square (500px x 500px cover art for example).

Now, a lot of my cover art is for some reason becoming a square. Not all of my covers have this happen, but it appears to be random. I don't know what image resolutions will cause this.

Here's pictures describing what's happening:
[This is a show cover that's a square](https://i.imgur.com/OTxFAG8.jpeg)
[This is the actual image that's being displayed](https://i.imgur.com/hGnlGpX.jpeg)

[Example of how they're supposed to be](https://i.imgur.com/AGzvjWT.jpeg)

**Steps To Reproduce**
1. Look around your libraries and look for cover art that became squares when displayed.

**Expected Behavior**
Media cover art should be rectangles instead of being shrunk to a square.

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Chrome, Firefox
 - Jellyfin Version: 10.9.2

**Comment by Debouelesmorts** [comment]
I'm experiencing the same problem since upgrading from version 10.8.13 to 19.2.

**Comment by kandykarter** [comment]
I have this issue as well, so far only noticed on one film, corrected by switching to a similar poster with a more "standard" size, 1500x1000.


![Screenshot from 2024-05-20 10-37-25](https://github.com/jellyfin/jellyfin-web/assets/107814899/99e92b62-80f8-4caf-b755-21f0a85911cc)

**Comment by Debouelesmorts** [comment]
I have several thousand films and unlike @kandykarter this bug affects my covers by the hundreds.

**Comment by scampower3** [comment]
What are the aspect ratios of the problematic images?

**Comment by 1hitsong** [comment]
Fixed by #5587
