### ISSUE TITLE
Copy Stream URL not working with Firefox

### ISSUE THREAD

**Issue by nyanloutre** [jellyfin/jellyfin-web#557]
**Describe the bug**

With firefox, the Javascript bit that is writing to the clipboard is blocked with this error:
`document.execCommand(‘cut’/‘copy’) was denied because it was not called from inside a short running user-generated event handler.`

**To Reproduce**

1. Use Firefox
1. Click on any media menu
1. Click on "Copy Steam URL"

**Expected behavior**

URL should be written to the clipboard

**System (please complete the following information):**
 - OS: NixOS
 - Browser: Firefox
 - Jellyfin Version: 10.4.0

**Comment by nottherealbatman** [comment]
This is probably because the click event is not set on the "copy" button, firefox blocks the copy action if that is the case. [This mdn link explains it ](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard)

**Comment by brianjmurrell** [comment]
Same on Chrome on Android.

**Comment by brianjmurrell** [comment]
Real pity since it's the only way to get media to play on an external player on Android.

**Comment by ThibaultNocchi** [comment]
I've looked into it and there may be three different solutions:

* Executing the current method from the click handler, but I'm not too familiar with this project and seeing how it's currently done, I guess it may not be the solution.
* Using the Clipboard API, but it needs user permissions and FF (at least) doesn't pass them to the user when in using HTTP (still may be better than nothing).
* Using a 3rd party plugin, but I'm not sure what the stand here is about it.
* Keep the current command and if it fails, display an alert or something to let the user copy the URL by itself.

I'm pretty new to contributing to a big project and I'd like your advice on it.

Moreover, the current implementation uses a try / catch to check if the copy succeeded, but the command returns true or false whether it worked.

**Comment by ThibaultNocchi** [comment]
A workaround has been pushed to master to allow manually copying the URL #754.

**Comment by dessalines** [comment]
What version of jellyfin will have this fixed?

**Comment by dkanada** [comment]
0.5.0

**Comment by dkanada** [comment]
10.5.0
