### ISSUE TITLE
Next up episode dialogue not working on Chrome

### ISSUE THREAD

**Issue by cmck359** [jellyfin/jellyfin-web#5578]
**Describe The Bug**
When interacting with the next up episode dialogue changes to the player controls are occurring. For instance, when attempting to play the next episode, the playback position is being changed, as though the dialogue is not present.

The playback controls are not visible underneath the dialogue.

<img width="466" alt="Screenshot 2024-05-22 at 03 46 48" src="https://github.com/jellyfin/jellyfin-web/assets/83162233/98c6c55d-92a8-4986-ac17-350aba45045c">

The issue appears to affect both versions 10.8.13 & 10.9.2. I have tried disabling all extensions and this did not stop the bug from occurring.

**Steps To Reproduce**
1. Use Chrome Version 125.0.6422.60 (Official Build) (arm64)
2. Play TV episode (must have episodes following it)
3. Watch till end of episode
4. Try interacting with dialogue

**Expected Behavior**
The "Start Now" and "Hide" buttons should trigger their respective functions.

**Logs**
N/A

**Screenshots**

**System (please complete the following information):**
 - Platform: MacOS Sonoma 14.2
 - Browser: Chrome Version 125.0.6422.60 (Official Build) (arm64)
 - Jellyfin Version: 10.9.2 & 10.8.2

**Comment by vivekkairi** [comment]
Someone has fixed this 

#5595

**Comment by cmck359** [comment]
Underlying issue is fixed in  #5653
