### ISSUE TITLE
Incorrect episode release date

### ISSUE THREAD

**Issue by NotSaifA** [jellyfin/jellyfin-web#5598]
**Describe The Bug**
The episode air date is offset by -1 day if the episode was released during standard time, but media info page is being viewed while observing daylight time.

**Steps To Reproduce**
1. Set episode metadata release date to any date during standard time. (e.g. January 12 2024).
2. Go to info page of episode while observing daylight time.
3. Episode release date shows "January 11 2024" even though metadata shows "January 12 2024".

**Expected Behavior**
Show release date in info page as set in metadata.

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Firefox
 - Jellyfin Version: 10.9.2

**Comment by scampower3** [comment]
Fixed by https://github.com/jellyfin/jellyfin-web/pull/5599
