### ISSUE TITLE
Sound works great in Jellyfin Vue but all other jellyfin apps based on Jellyfin Web have issue with possibly downmixing (background sounds instead of dialogue)

### ISSUE THREAD

**Issue by ljubomirb** [jellyfin/jellyfin-web#5605]
### Description of the bug

I have a problem with sound, and you can find many users have the same for years.
When watching movie in 5.1 on android in **original jellyfin**, all I hear are background noises. If it is a downmixing problem or what, not sure.
The issue does not exist on PC (Win 10, chrome).
But the problem is on android. For example - chrome, it does this problem. I can, however, copy stream and paste to android VLC, and that works.

If I use android app, it still does not work, except if i put it to client hw as pointed by many users.

BUT!
In android chrome with **jellyfin-vue (this repo)** it works on android, and there is no problem whatsoever! So, please, check what is so different here, and maybe fix this long lasting problem (you can easily see that users have issue with this for a long time).

### Steps to reproduce

Watch 5.1 sound movie, x264, server is docker, iGPU, but it should not matter because everything works on chrome on PC. Only android chrome, and jellyfin app do not work as intended.

### Expected behavior

I expect to hear downmix to stereo in such way i can hear dialogue. No matter option used, only i mentioned combination it worked as should. Maybe just pass 5.1 sound without any change?

### Platform

Android

### Browser

Chrome

### Jellyfin server version

10.9.2

**Comment by thornbill** [comment]
Server logs from it working and not working are probably going to be needed to identify the issue.

**Comment by ljubomirb** [comment]
> If the issue doesn't exist in Jellyfin Vue, why do you think this is the most appropiate place so it gets the attention it deserves in the correct place?
> 
> Moving this to web

Because you are doing something different then what app and web versions have. So I figure you would know what it is that you did differently. This error exists for at least a year, since I stumbled upon many users with same problem. And the only solution is **NOT to use web page in Android**, but Android native app, and within it - change to native player. It "may" indicate this is actually problem with just the web version alone if app is actually embedded web browser, but I don't know that (i have no exposure to android ap developing), yet it looks the same. But this (vue) has something different done. The only thing I see is obviousl  is that it has a menu to change sound track (channel).
Btw, here is one example of the same isssue, just to see that is not new. ([link](https://www.reddit.com/r/jellyfin/comments/10ynge4/no_talking_only_background_sound_on_android_app/)). But while digging I've found more places/forums where users were complaining and trying to find solution. The biggest problem for me was (and I hope someone else will read it here), that the solution people were giving was only available for **Android app** (there is no "client" menu in web version).
Again, it has to do only with 5.1 audio, x264 (non transcoded).

**Comment by ljubomirb** [comment]
> Server logs from it working and not working are probably going to be needed to identify the issue.

Ok, what part of logs? There is a lot of text. I can paste it all. There is a log in web page, and a log in docker.
Again, this is iGPU, linux, docker, using for transcoding  /dev/dri/renderD128 (passed trough docker), VAAPI, which did not work at all until i found out jellyfin also requires for iGPU this in grub:  **GRUB_CMDLINE_LINUX_DEFAULT="quiet splash i915.enable_guc=2"**

**Comment by thornbill** [comment]
- Enable [debug logging](https://jellyfin.org/docs/general/administration/troubleshooting#debug-logging)
- Copy 10-20 lines around the start of playback

This should include information about the media formats that the web client reports that is supported. I suspect there is a difference between what web and vue are reporting so it would be good to have both to compare.
