### ISSUE TITLE
Mobile App not showing or providing the ability to repeat either single or playlist

### ISSUE THREAD

**Issue by mitchelljfranklin** [jellyfin/jellyfin-web#561]
Hi,

I have looked and double checked but looks like repeat button is not available on the android app; within the web interface this also disapers when on mobile so assume this would be similar; understand why to only show the main controls but would be great to have the ability to set a song or playlist on repeat

**Comment by JustAMan** [comment]
You've rightfully noted that in Web UI it behaves the same (as our current Android app uses bundled web inside).
So I've moved the issue to more appropriate repo.

**Comment by dkanada** [comment]
The repeat button is available on the playlist page, although it's definitely not the best design.

**Comment by mitchelljfranklin** [comment]
I dont use playlists so not a real option for me; but at the end of the day this is one user :).

If interested the below change would allow the repeat button to be shown on Mobile / max width smaller then 47em screen size. 

under src/components/remotecontrol/remotecontrol.css at line 227 if the following is removed and or commented out this enables the repeat toggle to be made visible.


```css
@media all and (max-width: 47em) {
    .nowPlayingInfoButtons .repeatToggleButton {
        display: none !important;
    }
}
```

**Comment by JustAMan** [comment]
You can use [custom css](https://jellyfin.org/docs/general/clients/css-customization.html) feature to tweak your instance without actually patching the source.

**Comment by mitchelljfranklin** [comment]
> 
> 
> You can use [custom css](https://jellyfin.org/docs/general/clients/css-customization.html) feature to tweak your instance without actually patching the source.

I do that for my server but for the mobile apps this would need to be done at the source since it uses the webfront end

**Comment by MrTimscampi** [comment]
The mobile app should be loading the branding (including custom CSS) from your server when it loads. If it doesn't, it's likely a bug that we'd need to look into.

**Comment by mitchelljfranklin** [comment]
Oh I didn't realize that at all; I thought it was just for the web app its self; OK to applied it and tested - it is coming through but the remote CSS is overriding the Css,css (Assume due to the order of ingestion)
![image](https://user-images.githubusercontent.com/56988354/76155035-35f92180-6132-11ea-9df9-2c83257f4306.jpg)

**Comment by dkanada** [comment]
@thornbill actually fixed this for the next release if I recall correctly.

**Comment by mitchelljfranklin** [comment]
> 
> 
> @thornbill actually fixed this for the next release if I recall correctly.

Thanks @dkanada , @MrTimscampi  & @JustAMan can confirm latest release fixes and now the mobile app is showing the update from the custom CSS. Big Thank you just in General for the work you and the team do :)

**Comment by darkbee101** [comment]
> > @thornbill actually fixed this for the next release if I recall correctly.
> 
> Thanks @dkanada , @MrTimscampi & @JustAMan can confirm latest release fixes and now the mobile app is showing the update from the custom CSS. Big Thank you just in General for the work you and the team do :)

Hi there! I am trying to add the repeat button to android app too but can't do so :/ Did you add the code in the settings of jellybin?
Thanks for the help!
