### ISSUE TITLE
MKV no longer play directly on Edge Chromium on Windows as it's detected as Chrome

### ISSUE THREAD

**Issue by CasperMcFadden95** [jellyfin/jellyfin-web#5611]
**Describe The Bug**
`browser.edg` is `undefined` and `browser.chrome` is set when running Microsoft Edge on Windows 11.

This leads to `browser.edgeChromium` to be unset
https://github.com/jellyfin/jellyfin-web/blob/a41f7ad6c773fc59bb8059833e47b79d873a2839/src/scripts/browser.js#L257

**Steps To Reproduce**

1. Play an MKV in Edge on Windows causes a remux

Cause:
1. Open Jellyfin in Edge Windows or pass the `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0` string to https://github.com/jellyfin/jellyfin-web/blob/a41f7ad6c773fc59bb8059833e47b79d873a2839/src/scripts/browser.js#L188
2. Reverting the change made in #4748 (#4747) fixes this.
3. `testCanPlayMkv` will then return true https://github.com/jellyfin/jellyfin-web/blob/669784bde5cc12f998c176a49542990e5a12e61e/src/scripts/browserDeviceProfile.js#L200

**Expected Behavior**
Edge Chromium should not be detected as Chrome

**Logs**
Not Applicable

**Screenshots**
Not Applicable

**System (please complete the following information):**
 - Platform: Windows 11
 - Browser: Edge Chromium `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0`
 - Jellyfin Version: [e.g. 10.9.2]

**Additional Context**
Not Applicable

**Comment by scampower3** [comment]
Fixed by https://github.com/jellyfin/jellyfin-web/pull/5612

**Comment by CasperMcFadden95** [comment]
Thanks @scampower3 for fixing this quickly!
