### ISSUE TITLE
"Next episode" box language implies the next episode will autoplay even when autoplay is off

### ISSUE THREAD

**Issue by TheHYPO35** [jellyfin/jellyfin-web#5643]
This one is fairly straight forward. I have "play next episode automatically" off, but I have "show next video info during playback" on.

The box that appears with about 30 seconds to go says "Next episode playing in [countdown]" with a "Start now" button. It doesn't actually auto-play.

This is all well and good, but the verbiage should not suggest that the next episode will play if the autoplay feature is off. The verbiage of that first line should be changed to something like simply "Next episode:" 

I noted this bug that was resolved relatively recently that _might_ be related, so I thought I'd link it: https://github.com/jellyfin/jellyfin-web/pull/5398

**Steps To Reproduce**
1. Settings > playback
2. Play next episode automatically [off]
3. Show next video info during playback [on]
4. Play a TV episode that isn't the last episode of a show. Skip to the last minute and wait for the popup to appear

![NextEp1](https://github.com/jellyfin/jellyfin-web/assets/118507638/1fc02b53-63a6-4275-a7cc-f0b66fc8d20b)

I don't think logs are relevant unless someone tells me that the wording actually is supposed to be different if auto-play is off - I'm assuming this was just an oversight that the wording is currently coded to be the same whether autoplay is on or off. If it should already be using different language, let me know and I can produce logs.

**System (please complete the following information):**
 - Platform: Windows 10
 - Browser: Chrome (10.9.3) and Jellyfin Media Player (10.9.2)
 - Jellyfin Version: 10.9.3

**Additional Context**

**Comment by ConnorS1110** [comment]
I have a PR up for this, but I would call this more of an enhancement than a bug. There wasn't anything that was broken its just that what you are seeing visually can be misleading

**Comment by TheHYPO35** [comment]
I think it's a "6 of one, half dozen of the other" situation. I would personally call it a bug, as the text does not correctly indicate what is actually happening, or alternatively, the text says something will happen that doesn't actually happen (even if it not happening is what the user has set it to). It's not a "it would be nice if this text were different". It's a "the text is actually wrong". To me, that's a bug. But either way, the important part is that it's identified to be corrected. Cheers
