### ISSUE TITLE
Autoplay play now hide buttons are not clickable because of playbar conttrols still active 10.9.3

### ISSUE THREAD

**Issue by luky92** [jellyfin/jellyfin-web#5647]
**Describe The Bug**

**Steps To Reproduce**

1. Start playing an episode of any series make sure autoplay next episode is on 
2. wait for the next episode in x s popup 
3. try to click play now button
4. button will not work but the peisode might rewind depending on cursor possition ( looks like palybar controls are still active but invisable)

**Expected Behavior**
button skips to next ep 

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Platform: docker linuxserver image
 - Browser: Chrome
 - Jellyfin Version: 10.9.3

**Additional Context**

**Comment by dmitrylyzo** [comment]
https://github.com/jellyfin/jellyfin-web/issues/5650#issuecomment-2145113706

**Comment by dmitrylyzo** [comment]
Should be fixed in the next point release (by #5653).
