### ISSUE TITLE
Client holds onto incorrect server address

### ISSUE THREAD

**Issue by Player3324** [jellyfin/jellyfin-web#5648]
### Please describe your bug

The web client stores the server's address in the browser's (and presumably app's) site data, as observable in the js console log for `Stored JSON credentials: [...] ManualAddress: <address>`.

This stored address is not necessarily the same as the one used in the URL to connect to Jellyfin. In my case I connected to `http://192.168.0.x:8096`, but it stored the globally routed IPv6 address `http://[2a02:x]:8096` in the above JSON site data. The server has multiple IP addresses, like most IPv6 enabled systems.

While the other address works fine initially (assuming the network is properly configured) it can break easily and unexpectedly. In my case the IPv6 address is based on a dynamically assigned prefix, so it changes regularly. Others might see this problem due to DHCP assigned IPv4 or any other scenario with more than one IP on a host.

The Android app seems to suffer from the same problem internally, we had all of them break in a similar way. Server added in the app with the static IPv4, app presumably stores dynamic IPv6 instead, broke as IPv6 changed. Clearing app data works around it similar to the browser's site data reset.

There is also a related usability problem with Jellyfin's web client preferring the stored host over the host in the url for cases where the two are supposedly identical, which should be the most common case. I'd expect it to not store the remote host at all there, only if I added a different server myself, so it tracks any server IP changes as long as I adjust the URL. Only people that use the web client to connect to a different host than the one hosting the client should even experience the problem and then get better guidance than essentially a timeout and poor insight into which address was actually in use.

This issue might be behind some users' complaints around the web ui loading slowly and ultimately failing that were worked around by clearing site data.

The underlying problems appear to be:
- Jellyfin may determine and store the host address incorrectly for a multi-IP host, not always matching what the user requested
- Jellyfin's web client stores the address explicitly instead of some representation of "use the same address as the URL" where it can do so as is commonly the case

### Reproduction Steps

1. Run Jellyfin on a host with multiple IPs, preferably with IPv6 enabled.
2. Navigate (open browser) to the IPv4, if the scenario is matching it'll store the IPv6 instead of the IPv4. If the server has multiple IPv4 this could also lead to it holding onto the wrong IPv4 address, IPv6 is not strictly necessary for this bug.
3. Change the stored, but not requested IP, e.g. drop the IPv6 address.
4. Navigate to the Ipv4 again, observe how it doesn't load and tries to send requests to the stored IPv6

The problem case should be successfully replicated once you see a different ManualAddress from the one in the original request URL after step 2.

### Jellyfin Version

10.9.0

### if other:

10.9.4

### Environment

```markdown
- OS: Ubuntu 24.04
- Clients: Firefox 126, Android
- Networking: Dual stack lite with static local IPv4, global IPv6 with dynamic prefix and IPv4 routed via NAT - accessed through LAN
```

### Jellyfin logs

```shell
no related log output
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thornbill** [comment]
Could you provide the address values in local storage from when it is working and then when it is not?

> There is also a related usability problem with Jellyfin's web client preferring the stored host over the host in the url for cases where the two are supposedly identical, which should be the most common case.

Using the stored server address should be much faster than attempting multiple api calls to find the right address regardless.

**Comment by thornbill** [comment]
There are multiple addresses stored. I need specifics to be able to investigate this.

**Comment by gnattu** [comment]
It seems like the LocalAddress is promoted to ManualAddresses from my observation. They will be same when this occurs but I don't have reliable way to reproduce this. But I do think it is good enough for all embedded web clients to never use that stored address in json because the "previously connected" client does not mean anything good in this case and the "default server" specified by user makes more sense.
