### ISSUE TITLE
Up Next container buttons not clickable

### ISSUE THREAD

**Issue by pvico12** [jellyfin/jellyfin-web#5650]
**Describe The Bug**
Up Next Video container buttons not clickable. Instead they fast forward./backwards.

**Steps To Reproduce**
1. Watch any media in a TV series until the last minute of the episode. Up next container appears.
2. Click any button in the Up Next container.

**Expected Behavior**
Buttons should perform their regular operation.

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Chrome
 - Jellyfin Version: 10.9.0

**Comment by thornbill** [comment]
Are you using any custom css? https://github.com/jellyfin/jellyfin-web/pull/5595#issuecomment-2141960724

**Comment by pvico12** [comment]
@thornbill nope, but I did miss that issue so I opened a duplicate issue

**Comment by pvico12** [comment]
will look into hiding OSD instead of applying custom css
