### ISSUE TITLE
Unexpected Application Error! Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by ltqxm** [jellyfin/jellyfin-web#5655]
### Please describe your bug

10.9.4 version of Jellyfin adjusts the page of the user's access to the directory. Click to report the error. As shown in the figure below, can you help see what I should do?

### Reproduction Steps

![image](https://github.com/jellyfin/jellyfin/assets/81942881/4e06b33c-1579-4e8c-8a2c-527a9e76f83d)
![f093ebe552ab5de24f33395ac5b132b](https://github.com/jellyfin/jellyfin/assets/81942881/a6610f6d-ec60-4da5-9264-44a5c7c04682)

### Jellyfin Version

10.9.0

### if other:

10.9.4

### Environment

```markdown
- OS:ubuntu 22.04.4
- Linux Kernel:
- Virtualization:
- Clients:ALL
- Browser:ALL
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:GTX1060
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thornbill** [comment]
I have not been able to reproduce this and searching for usages of `.split()` have not lead me to anything obvious...

**Comment by venkat-karasani** [comment]
Not able to reproduce this, @ltqxm are you seeing this issue in 10.9.7 as well? If you are seeing this, can you share steps to reproduce the issue?
