### ISSUE TITLE
Markdown is not displayed correctly on episode's overview preview area.

### ISSUE THREAD

**Issue by maru801** [jellyfin/jellyfin-web#5679]
**Describe The Bug**

Markdown-formatted text works fine in overviews everywhere except for in the overview preview area for episodes. It is not being properly displayed when shown on this display area. If you open the detail view of the episode, the markdown will properly display then.

**Steps To Reproduce**

1. Go to any episode, add in some markdown italics or bold, etc. to the overview in the metadata.
2. Navigate to the episode and see that its preview overview display does not handle markdown correctly as compared to when you open the episode page.

**Expected Behavior**

Markdown should properly display on episode overviews in both views.

**Logs**

N/A

**Screenshots**

[Example of markdown not being displayed correctly](https://i.imgur.com/ZphlWeC.jpeg)
[Same markdown being displayed correctly when the episode detail page is opened](https://i.imgur.com/ixLSGhK.jpeg)

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Brave
 - Jellyfin Version: 10.9.6

**Additional Context**

N/A

**Comment by Chaitanya-Shahare** [comment]
Can I work on this issue?

**Comment by Shadowghost** [comment]
Sure, if you have the time, feel free to pick it up.

**Comment by Chaitanya-Shahare** [comment]
I think this issue should be closed.

**Comment by maru801** [comment]
I was just waiting for the release that includes your pull request that fixes the issue to come out before marking this as closed. Shouldn't be a problem closing this now however. Will do.
