### ISSUE TITLE
Playlist dropdown when adding items should only show compatible playlists

### ISSUE THREAD

**Issue by Shadowghost** [jellyfin/jellyfin-web#5682]
**Describe The Bug**
When adding items to a playlists, the dropdown includes all available user playlists. This is irritating since items cannot be added to any playlist but only to ones with matching media type.

**Steps To Reproduce**
1. Create playlist with one video
2. Click three dot menu on a album
3. Add to playlist
4. Seems to be successful but essentially does nothing because media type does not match

**Expected Behavior**
* Server should report an error (jellyfin/jellyfin#12018)
* Web should not show incompatible playlists in the dropdown

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Platform: [e.g. Linux, Windows, iPhone, Tizen]
 - Browser: [e.g. Firefox, Chrome, Safari]
 - Jellyfin Version: 10.9.6

**Additional Context**

**Comment by venkat-karasani** [comment]
@Shadowghost I am not able to reproduce the issue. I created a playlist with a single video and after that I was able to add an album successfully to it. When I opened the playlist, I see the video and the songs from that album in it. Am I missing anything?

**Comment by Shadowghost** [comment]
It's only happening if the original playlist is a music playlist I think

**Comment by trajano** [comment]
This feature seems to work.
