### ISSUE TITLE
Stuck page titles on admin Dashboard

### ISSUE THREAD

**Issue by BotBlake** [jellyfin/jellyfin-web#5686]
**Describe The Bug**

The html page titles in the Admin Dashboard arent changing everywhere.
e.g. the DLNA Page sets it. If you go back to the "Home" admin Dashboard, the Page title still says "DLNA".

This happens for: DLNA, Notifications and Activity

**Steps To Reproduce**

1. Go to the Admin Dashboard (through Jellyfin Web)
2. Click on DLNA (or Notifications / Activity)
3. See the Page title that matches the Tab you opened
4. Click on any Tab that isnt DLNA, Notifications or Activity
5.  See the Page title still being the one from the previous page.
--> This title only changes on theese three pages

**Expected Behavior**

The Title should reset when switching to another page,

**Logs**

**Screenshots**

![grafik](https://github.com/jellyfin/jellyfin-web/assets/94436780/cce811a1-923a-4aa5-9939-595860a3334f)

**System (please complete the following information):**
 - Platform: TrueNAS Scale, Docker, Ubuntu, 
 - Browser: Firefox, Chrome
 - Jellyfin Version: 10.9.6

**Additional Context**

**Comment by thornbill** [comment]
It seems there was some magic in the old drawer that would update the title when you clicked a link... https://github.com/jellyfin/jellyfin-web/blob/1d647bcf037d46ca13028824d0c5c2dfb5ae6e1b/src/scripts/libraryMenu.js#L387

**Comment by venkat-karasani** [comment]
identified the root cause, will fix and create a PR.
