### ISSUE TITLE
Unexpected Application Error!

### ISSUE THREAD

**Issue by jibaine** [jellyfin/jellyfin-web#5690]
**Description**

When I click on a user to access its parameter I get an error page

**Steps To Reproduce**

1. Go to Dashboard/Users
2. Click on a user Tile
3. See error

**Expected Behavior**
Access to user's parameters

**Logs**

Error: Must supply a userId
    at e.value (https://xxx.fr/web/node_modules.jellyfin-apiclient.bundle.js?c70b2c6c93640e33833a:2:40105)
    at U (https://xxx.fr/web/users-profile.34f422d31086625e3bb8.chunk.js:1:1578)
    at https://xxx.fr/web/users-profile.34f422d31086625e3bb8.chunk.js:1:6181
    at https://xxx.fr/web/users-profile.34f422d31086625e3bb8.chunk.js:1:6340
    at Fi (https://xxx.fr/web/node_modules.react-dom.bundle.js?c70b2c6c93640e33833a:2:103916)
    at t.unstable_runWithPriority (https://xxx.fr/web/7466.bundle.js?c70b2c6c93640e33833a:2:27602)
    at jl (https://xxx.fr/web/node_modules.react-dom.bundle.js?c70b2c6c93640e33833a:2:44769)
    at Mi (https://xxx.fr/web/node_modules.react-dom.bundle.js?c70b2c6c93640e33833a:2:103384)
    at https://xxx.fr/web/node_modules.react-dom.bundle.js?c70b2c6c93640e33833a:2:103295
    at $ (https://xxx.fr/web/7466.bundle.js?c70b2c6c93640e33833a:2:26662)

**Screenshots**
![error](https://github.com/jellyfin/jellyfin-web/assets/6840520/f2422cef-054a-44b2-ad82-16a9ef213335)

**System (please complete the following information):**
 - Platform: VM Debian Bookworm
 - Browser: Chrome
 - Jellyfin Version: 10.9.6

**Comment by thornbill** [comment]
What is the url of the page when the error occurs? Do you happen to have any plugins installed that mangle urls like clearurls?

**Comment by JuanJesusAlejoSillero** [comment]
This happens to me too.

Using the jellyfin/jellyfin docker image on version 10.9.6.

Strangely, I confirmed **it doesn't happen in a private window** using Firefox, I haven't checked other browsers.

Having seen that it works, I've tried **deleting the cache and all related information** for my jellyfin site in Firefox, but it still happens unless I use incognito mode.

Also, I couldn't edit my scheduled tasks, it just hangs endlessly loading, but it works in incognito as well.

**Comment by thornbill** [comment]
I ended up replicating this by having an extra "?" in the url. That probably breaks the react hook for getting url params.

**Comment by JuanJesusAlejoSillero** [comment]
> I ended up replicating this by having an extra "?" in the url. That probably breaks the react hook for getting url params.

Yes, that's it, I tried removing the '?' character from the URL manually and it works now.

It actually doesn't add the interrogation anymore and just works even if I open a new jellyfin tab.

Thanks a lot

**Comment by patrickhuitema** [comment]
Got the same problem in windows, every new user: Unexpected Application Error!
Must supply a userId
