### ISSUE TITLE
Can't save video progress

### ISSUE THREAD

**Issue by kolbdog323** [jellyfin/jellyfin-web#5701]
I am trying to play videos but whenever i stop a video and then resume it no matter what point of the video it wont resume the last point where I am at. Not sure how to fix this. I am using the sever. Do I need to use the media player to save the progrss and  not the web one?

**Comment by thornbill** [comment]
I would recommend reaching out in chat or in the forum for help troubleshooting your issue. Progress should be saved automatically. https://jellyfin.org/contact
