### ISSUE TITLE
Problem with adding of quality levels (src/components/qualityOptions.js)

### ISSUE THREAD

**Issue by artyums** [jellyfin/jellyfin-web#5704]
**Describe The Bug**
Tried to slightly change _src/components/qualityOptions.js_ file of Jellyfin-web 10.9.6 to add some more quality levels:
[qualityOptions.js.txt](https://github.com/user-attachments/files/15815593/qualityOptions.js.txt)

Made the last digit different as said in comment:
> Quality options are indexed by bitrate. If you must duplicate them, make sure each of them are unique (by making the last digit a 1)

When I'm trying to play any video via Jellyfin-web, I see new quality levels in player, but when I choose (for example) "1080p - 1 Mpbs" - it automatically changes to "4K - 1 Mbps". 
When I choose "720p - 1 Mbps" - it also changes to "4K - 1 Mbps". 
And so on, quality always changes to "4K - 1 Mbps".
Only if I choose higher quality level (ex., "4K - 5 Mbps") - it persists.

When I used Jellyfin 10.9.0, this trick worked well and quality was changing as expected.

**Steps To Reproduce**
1. Use qualityOptions.js.txt file from link above. Rename it to qualityOptions.js
2. Build Jellyfin server with modified Jellyfin-web.
3. Try to play video and manually change quality level. 

**Expected Behavior**
Quality changes as expected.

**System (please complete the following information):**
 - Platform: Debian 12.5
 - Browser: any
 - Jellyfin Version: 10.9.6

**Comment by thornbill** [comment]
We don't support or encourage modifying the built files.
