### ISSUE TITLE
iPad OS with Chrome 79.0 cannot load web page

### ISSUE THREAD

**Issue by FanyangMengDev** [jellyfin/jellyfin-web#572]
**Describe the bug**
iPad OS with Chrome 79 cannot view jellyfin, it just display a black and blank page, but the Safari can display and use Jellyfin web page normally.

**To Reproduce**

1. Use my iPad Pro 2018 with iPad OS 13, and open Chrome 79 which is from the Testflight
2. Input URL of my own Jellyfin
3. The error dispalys. Just a black and blank page. Which actually already happened in 10.4.0, now is 10.4.1

**Expected behavior**
It should be displaying log in page properly as Safari does

**Logs**
iPad Chrome cannot export logs

**Screenshots**
No need to upload screenshots because it is just black and blank page

**System (please complete the following information):**
 - OS: iPad OS 13
 - Browser: Chrome (Also tried with Alook browser which is not working as the Chrome)
 - Jellyfin Version: 10.4.1
 - Reverse proxy: nginx

**Comment by FanyangMengDev** [comment]
Actually I think reverse proxy is not a problem. I just think that maybe it is just a bug of your software.
Because you know as I said, it works well on Safari, so I strongly recommend you to check if all the browser works fine.
Thanks.

**Comment by anthonylavado** [comment]
I don't believe anyone on the core team or web team has an iPad Pro to test with. The best I could test with was my iPhone, and it loads just fine.

I also tried on two computers, my Mac and a Windows laptop, with Chrome 79, and it worked as intended.

**Comment by dmitrylyzo** [comment]
It failed at `scripts/browser.js:305`
<details>
  <summary>RequireJS error: TypeError: undefined is not an object (evaluating 'browser.iOSVersion[0]').</summary>

```
http://192.168.2.18:8096/web/scripts/browser.js?v=10.4.1:305:48
execCb@http://192.168.2.18:8096/web/bower_components/alameda/alameda.js?v=10.4.1:392:38
defineModule@http://192.168.2.18:8096/web/bower_components/alameda/alameda.js?v=10.4.1:145:37
main@http://192.168.2.18:8096/web/bower_components/alameda/alameda.js?v=10.4.1:347:74
takeQueue@http://192.168.2.18:8096/web/bower_components/alameda/alameda.js?v=10.4.1:84:124
http://192.168.2.18:8096/web/bower_components/alameda/alameda.js?v=10.4.1:277:42
http://192.168.2.18:8096/web/scripts/browser.js?v=10.4.1:305:48
execCb@http://192.168.2.18:8096/web/bower_components/alameda/alameda.js?v=10.4.1:392:38
defineModule@http://192.168.2.18:8096/web/bower_components/alameda/alameda.js?v=10.4.1:145:37
main@http://192.168.2.18:8096/web/bower_components/alameda/alameda.js?v=10.4.1:347:74
takeQueue@http://192.168.2.18:8096/web/bower_components/alameda/alameda.js?v=10.4.1:84:124
http://192.168.2.18:8096/web/bower_components/alameda/alameda.js?v=10.4.1:277:42
RequireJS error: TypeError: undefined is not an object (evaluating 'browser.iOSVersion[0]'). Failed modules:
```
</details>

`Mozilla/5.0 (iPad; CPU OS 13_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/78.0.3904.84 Mobile/15E148 Safari/604.1`

**Comment by FanyangMengDev** [comment]
It's not just happening on me 👆

**Comment by anthonylavado** [comment]
> @anthonylavado
> It's not just happening on me 👆

@FanyangMengDev Never said it was, just said I couldn't test the same way you were
