### ISSUE TITLE
Edit: Having a baseurl makes the title bar show for the web page added to the home screen on iOS

### ISSUE THREAD

**Issue by drazil100** [jellyfin/jellyfin-web#575]
Without a base url or back on 1.4.0
![17B59BBA-4644-4627-B66D-074CAB9EA1DC](https://user-images.githubusercontent.com/17794391/68326703-921f3c80-0091-11ea-80df-621171526603.jpeg)

Since updating to 1.4.1 and having the baseurl set to /jellyfin it looks like this.
![332437E7-73C2-431D-82B0-A35C040A6FFC](https://user-images.githubusercontent.com/17794391/68326777-b4b15580-0091-11ea-84d9-1744179d2186.png)

original report assumed that /jellyfin was permanent and unchangeable (my bad). Issue edited to reflect that this is related to the baseurl feature.

**Comment by anthonylavado** [comment]
@drazil100 We've got this fixed for the next version of the server. Just one note - if you do change the baser, you will need to add it to your home screen again. You'll know because the existing icon will no longer work (it has the wrong URL).
