### ISSUE TITLE
Dolby Vision with HDR fallback has incorrectly sized enhancement layer

### ISSUE THREAD

**Issue by ChrisRosser** [jellyfin/jellyfin-web#5783]
**Describe The Bug**
When Playing Dolby Vision content with HDR10 fallback with a non-standard aspect ratio the enhancement layer is incorrectly sized over the base layer. It looks like the black bars top and bottom are exactly double the width on the enhancement layer (maybe some offset being applied twice?)

**Steps To Reproduce**

Play Dolby Vision content with HDR10 fallback.

**Expected Behavior**
Enhancement layer should perfectly match the underlying base layer.

**Logs**

**Screenshots**
![image](https://github.com/user-attachments/assets/bcb8a44a-dc33-43a5-95fc-75ac2688b785)

**System (please complete the following information):**
 - Platform: webOS LG G3
 - Jellyfin Version: 10.9.7

**Additional Context**

**Comment by ChrisRosser** [comment]
https://github.com/jellyfin/jellyfin-webos/issues/239

also mentioned here.

**Comment by ChrisRosser** [comment]
I can confirm the issue is present with prefer fMP4 enabled and disabled. This setting doesn't appear to make any difference to this particular problem. The key issue appears to be aspect ratio.

File that works perfectly:
Codec: HEVC
AVC: No
Profile: Main 10
Level: 150
Resolution: 3840x2160
Aspect ratio: 16:9
Anamorphic: No
Interlaced: No
Framerate: 24
Bitrate: 18942 kbps
Bit depth: 10 bit
Video range: HDR
Video range type: DOVIWithHDR10
DV title: DV Profile 8.1 (HDR10)
DV version major: 1
DV version minor: 0
DV profile: 8
DV level: 6
DV rpu preset flag: 1
DV el preset flag: 0
DV bl preset flag: 1
DV bl signal compatibility id: 1
Colour space: bt2020nc
Colour transfer: smpte2084
Colour primaries: bt2020
Pixel format: yuv420p10le
Ref frames: 1

Problem file:
Codec: HEVC
AVC: No
Profile: Main 10
Level: 153
Resolution: 3840x1608
Aspect ratio: 2.40:1 <<<<<< This is the only real difference between these two files.
Anamorphic: No
Interlaced: No
Framerate: 23.976025
Bitrate: 25653 kbps
Bit depth: 10 bit
Video range: HDR
Video range type: DOVIWithHDR10
DV title: DV Profile 8.1 (HDR10)
DV version major: 1
DV version minor: 0
DV profile: 8
DV level: 6
DV rpu preset flag: 1
DV el preset flag: 0
DV bl preset flag: 1
DV bl signal compatibility id: 1
Colour space: bt2020nc
Colour transfer: smpte2084
Colour primaries: bt2020
Pixel format: yuv420p10le
Ref frames: 1

**Comment by oNSXo** [comment]
I can confirm this is still an issue as well on an updated LG C3
