### ISSUE TITLE
Remote control navigation keys not displayed

### ISSUE THREAD

**Issue by Nickbert7** [jellyfin/jellyfin-web#579]
When connected to Kodi via the Web UI (Remote Control) the navigation buttons are not displayed.
After removing the "hide" class the navigation is possible. (Even if the layout is not good)

https://github.com/jellyfin/jellyfin-web/blob/957184b81c59e6a0b16a99a62fe1e4958bd58eb2/src/nowplaying.html#L78

![image](https://user-images.githubusercontent.com/14938497/69152631-11266300-0add-11ea-83be-0902eba5a11f.png)

It would ba a nice feature to navigate trough Kodi via the Jellyfin Web-UI or App on the smartphone.
Also for the upcoming TV-layout improvements or the Android TV app it would be a nice feature.

**Comment by KeepBotting** [comment]
I can confirm this issue exists using Jellyfin 10.4.0 and jellyfin-kodi 0.3.8

It doesn't seem to me that these navigation controls should ever be hidden, as they are relvant and usable at any point while connected to Kodi.

The layout should be fixed and these buttons should be displayed by default whenever jellyfin-web is connected to jellyfin-kodi

**Comment by Nickbert7** [comment]
Fixed by https://github.com/jellyfin/jellyfin-web/pull/584
