### ISSUE TITLE
DLNA Profile Condition detail pages cut off at top

### ISSUE THREAD

**Issue by PrplHaz4** [jellyfin/jellyfin-web#581]
**Describe the bug**

When editing a profile condition on DLNA profile page, they are cut off on the top.

**To Reproduce**

1. Go to 'https://jellyfin/web/index.html#!/dlnaprofile.html'
2. Click on "Default" under System Profiles
3. Go to the "Direct Play" tab
4. Click first condition "Video -> Container -> All"
5. See form is cut off at the top

**Expected behavior**

Complete form to edit/enter data is displayed

**Logs**

**Screenshots**

![image](https://user-images.githubusercontent.com/841414/69179704-f1da0680-0ad9-11ea-9af6-098a36c3781e.png)

**System (please complete the following information):**
 - OS: Docker
 - Browser: Firefox
 - Jellyfin Version: 10.4.1

**Additional context**

**Comment by dkanada** [comment]
@PrplHaz4 is this an issue on the latest nightly?

**Comment by PrplHaz4** [comment]
Closing - it seems to have been fixed somewhere along the journey to 10.5.5.
