### ISSUE TITLE
same episode suggested as recommandation than the one selected

### ISSUE THREAD

**Issue by bmillemathias** [jellyfin/jellyfin-web#5814]
**Describe The Bug**

while being on a episode, I've had the same episode listed in the suggestion list (« Plus de saison 1» in french in the provided screenshot).

**Expected Behavior**
not having the same episode in the suggestion

**Logs**
n/a

**Screenshots**
![image](https://github.com/user-attachments/assets/43ed1201-f21b-423f-b06d-fbdea5a017b5)

**System (please complete the following information):**
 - Platform: n/a
 - Browser: firefox 
 - Jellyfin Version: 10.9.8

**Additional Context**

**Comment by viown** [comment]
Not sure if this is a bug as the "More from Season x" is just a slider that shows all episodes from that season. Removing the current episode might lead to confusion.
