### ISSUE TITLE
Collections don't load

### ISSUE THREAD

**Issue by MelanX** [jellyfin/jellyfin-web#5828]
**Describe The Bug**
After updating Jellyfin to 10.9.7, I wasn't able to view my collections anymore. I thought "Just wait for 10.9.8, maybe it's fixed", but now it isn't. In the log below, it's only the information after pressing F5 to reload the collections page.
My collections contain a few automatically generated collections, and I think 5 own-made collections. 

**Steps To Reproduce**
1. Click "Collections"
2. Wait
3. Look at log

**Expected Behavior**
Collections loading

**Logs**
https://gist.github.com/MelanX/0b1709823350b9b3f55b610ede4900ad

**Screenshots**
![image](https://github.com/user-attachments/assets/07bade55-559d-455c-8ff2-96cbb66755ee)

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Chrome 127.0.6533.72
 - Jellyfin Version: 10.9.8

**Comment by MelanX** [comment]
It only happens here at this location:
![image](https://github.com/user-attachments/assets/89d42926-a04c-43b3-b891-81f250ccc000)

When clicking on "Filme" (Movies) and then click "Collections" (see image), it loads fine.
![image](https://github.com/user-attachments/assets/e9e96cc9-6a75-4a10-a94a-d34fe9dfe187)

**Comment by venkat-karasani** [comment]
seems to be back-end(jellyfin) issue rather than the front-end(jellyfin-web).

**Comment by viown** [comment]
I'm unable to reproduce this issue on my end, but it does look like one of your collections has an issue preventing the JF server from loading it. If you could investigate further, you should open an issue at https://github.com/jellyfin/jellyfin

**Comment by theguymadmax** [comment]
@MelanX Are you running this in a container? If yes, check for the environment variable ```DOTNET_SYSTEM_GLOBALIZATION_INVARIANT``` and remove it.

**Comment by MelanX** [comment]
I fixed it by setting `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` from 1 to 0. Everything works like a charm again. Not sure if this issue should stay open for anything. Thank you and sorry for the late response!

**Comment by thornbill** [comment]
This is mentioned in the release post for 10.9: https://jellyfin.org/posts/jellyfin-release-10.9.0#key-release-notesbreaking-changes
