### ISSUE TITLE
[Feature] Title with now playing song/video

### ISSUE THREAD

**Issue by filipe-silva** [jellyfin/jellyfin-web#586]
Hello, I just installed this app and it works great, and mostly use this for songs for now.
Before this one I had madsonic, didn't enjoy it as much, however there was one thing I liked on it the website title showed the "now playing" file. 
This is mostly useful since I'm only listening and sometimes want to see the name of the song or artist without switching tabs.

I noticed jellyfin didn't had it, would it be possible to do it?

**Comment by filipe-silva** [comment]
Didn't know this was separated, nice.

So after a quick search to implement this we just need to do this:
[https://github.com/jellyfin/jellyfin-web/blob/31fe3a9f61956b450fe9ae186ad2d9d9a4316768/src/components/nowplayingbar/nowplayingbar.js](url)
`function updateNowPlayingInfo(context, state) {
(...)
if (textLines.length > 1) {
            textLines[1].secondary = true;
        }
        var newTitle = "";
        var serverId = nowPlayingItem ? nowPlayingItem.ServerId : null;
        nowPlayingTextElement.innerHTML = textLines.map(function (nowPlayingName) {

            var cssClass = nowPlayingName.secondary ? ' class="nowPlayingBarSecondaryText"' : '';

            if (nowPlayingName.item) {
                if(newTitle == ""){
                        newTitle = nowPlayingName.text;
                }
                else{
                        newTitle = newTitle + " - " +  nowPlayingName.text;
                }
                return '<div' + cssClass + '>' + getTextActionButton(nowPlayingName.item, nowPlayingName.text, serverId) + '</div>';
            }

            return '<div' + cssClass + '>' + nowPlayingName.text + '</div>';

        }).join('');

        window.document.title = newTitle;
        var imgHeight = 70;

(...)
}`

I changed my own server code and worked without any problems.
However there's still a few kinks, examples:
You start playing on the mainpage then go to nowplaying.html title reverts to Jellyfin, until next song.
You press back from nowplaying.html to mainpage it also reverts to Jellyfin.

So aside from navigation resetting title, the code above does the trick.

**Comment by hamburglar2160** [comment]
On 10.6 master the title currently displays the current TV show, but not episode. It does not display song information.

**Comment by MrTimscampi** [comment]
In keeping with the decision around #1224, I'm closing this.
