### ISSUE TITLE
Add sass-embedded as an optional dependency

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-web#5862]
The latest `sass-loader` release added support for using `sass-embedded` by default for improved build performance. We should add it as an optional dependency so `sass-loader` will use it by default and fallback to `sass` on platforms that are not supported by `sass-embedded`.

Refs: https://github.com/webpack-contrib/sass-loader/blob/master/CHANGELOG.md#1500-2024-07-23

**Comment by jwaresoft** [comment]
PR here
https://github.com/jellyfin/jellyfin-web/pull/5933
