### ISSUE TITLE
Switching tabs in a library doesn't change the `tab` URL parameter

### ISSUE THREAD

**Issue by Kladki** [jellyfin/jellyfin-web#5868]
**Describe The Bug**

When switching tabs in any library view, the `tab` URL parameter doesn't change, meaning that when you refresh or share the page, you end up on the page that you originally started on

**Steps To Reproduce**

1. Click on any library from the home page 
2. Switch tabs (e.g. to "suggested", "genres", etc.)
3. Reload the page
4. End up on the tab you started on

**Expected Behavior**

The tab should not change when refreshed, by changing the `tab` parameter whenever the tab changes.

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Firefox
 - Jellyfin Version: 10.9.8

**Example**

https://github.com/user-attachments/assets/0f1ecf4d-336f-474d-a7e0-4f9f4defadc1

**Comment by prsantos-com** [comment]
Confirmed that this bug exists today on master.

It mainly has to do with how navigation occurs. When selecting any of the link tabs, navigation occurs through the `ControllerFactory`.

If you select any of the links in the side bar, then navigation occurs through the `appRouter`, which will appropriately change the route and by default, set the `tab` parameter.

![image](https://github.com/user-attachments/assets/4fdad51e-4332-4d4d-a180-4d7d8d248e59)

**Comment by viown** [comment]
Note that this works as expected on the experimental layout.

**Comment by prsantos-com** [comment]
With that being said, does it still make sense to fix this bug? I'm wondering, because if the experimental layout will no longer be experimental soon, then maybe it doesn't make sense to fix.

**Comment by thornbill** [comment]
I don't think it is worth the effort to try to fix this in the legacy code. This is how the tabs have always behaved there so it isn't a regression.
