### ISSUE TITLE
Remote controls in dashboard "active devices" always defaults to pause button

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-web#5874]
**Describe The Bug**

The remote controls in the "active devices" section of the dashboard always default to pause button. Even when the media is already paused. Pressing the pause buttons will still trigger correct behavior (playing again) and afterwards the visuals are corrected.

**Steps To Reproduce**

1. In another window/client play media, then pause it
2. Open dashboard
3. See bug
4. Press the "pause" button to actually play again

**Expected Behavior**

It should display the play icon instead of the pause icon.

**Logs**

**Screenshots**

![93200003a7](https://github.com/user-attachments/assets/644e02cf-0e08-4089-a461-8b42b376d0b7)

**System (please complete the following information):**
 - Platform: [e.g. Linux, Windows, iPhone, Tizen]
 - Browser: [e.g. Firefox, Chrome, Safari]
 - Jellyfin Version: [e.g. 10.6.0]

**Additional Context**

Literally unusable

**Comment by kuligs2** [comment]
i wonder why there is no next/prev buttons here? Is there an API endpoint where i could trigger remotely to skip to the next movie if a playlist is playing? Plan is to set up this in homeassistant
