### ISSUE TITLE
Stop Playback/Fullscreen like Youtube

### ISSUE THREAD

**Issue by platinum55** [jellyfin/jellyfin-web#589]
currently when doubleclicking the movie, for fullscreen, it stops for a moment... youtube handles it likes this:

when a click is recognized, it waits for 500ms - if no other click followed, then the playback stops. if a second click follows within 500ms, then fullscreen is triggered.

would be nice if someone could implement this behavior into jellyfin

**Comment by JustAMan** [comment]
Major feature requests are accepted here: https://features.jellyfin.org/
This one doesn't look major, plus it belongs to a Web UI, so I transferred it.
