### ISSUE TITLE
Set clear rules for which browsers and platforms to support and which to not support

### ISSUE THREAD

**Issue by Tthecreator** [jellyfin/jellyfin-web#59]
I've got the following base proposal subject to changes.

All options are divided in 4 groups:
- critical
- medium priority
- low priority
- don't bother priority

Besides that, support in development versions of the web portal may be prioritized using the number before the list entry where 1 is highest priority and n is the lowest priority in the list. So the critical browsers should always work on master, but on dev only chrome and safari might work for a certain feature.

Critical browsers to support:
1. Chrome
2. Safari
3. firefox
4. MS Edge

Medium priority browsers to support:
5. Chromium based browsers (Opera for example)
6. UC Browser (Is this even applicable to our target audience)

Low priority browsers:
7. IE 11
8. Gecko based browsers (IceWeasel for example)

Don't bother browsers:
n. IE <11

Is something like this useful to state or will it just get in the way of development?

**Comment by cvium** [comment]
This sounds good to me
