### ISSUE TITLE
Playback Error when using shuffle

### ISSUE THREAD

**Issue by putridpete** [jellyfin/jellyfin-web#5909]
Whenever I shuffle media that I've filtered by genre, such as horror for instance, I get a Playback error that says "No player found for the requested media" every time. Happens on any web browser, JMP and on the WebOS app.

**Steps To Reproduce**

1. Go to 'Movies' (TV shows have this issue too)
2. Click on 'Genres'
3. Select any genre
4. Click 'Shuffle'
5. Error occurs

**Expected Behavior**
Media should play shuffled.

**Logs**
Because it refuses to play, I see no relevant logs, but after opening the browser dev console (Firefox) I saw this message that could be related: "No player found for the requested media: undefined main.jellyfin.bundle.js:2:142706".

**System:**
 - Platform: Linux, WebOS
 - Browser: Firefox
 - Jellyfin Version: 10.9.9, 1.11.1 (JMP)

**Additional Context**
Curiously enough, no problem occurs when clicking on "Play all" instead. This issue [was first reported on the Jellyfin forums](https://forum.jellyfin.org/t-playback-error-when-using-shuffle?pid=30753#pid30753), some additional info could be posted here.

**Comment by dmitrylyzo** [comment]
I don't know how it worked before, but now we don't generate a play queue for `Genre` item: https://github.com/jellyfin/jellyfin-web/blob/7c651d0a5dae957843c1d2f061038b17c17fab41/src/components/playback/playbackmanager.js#L1827
I tried adding a similar thing to `MusicGenre`: https://github.com/jellyfin/jellyfin-web/blob/7c651d0a5dae957843c1d2f061038b17c17fab41/src/components/playback/playbackmanager.js#L1857-L1864
But it fetches items across different libraries because `Genre` item has no parent (and the query as well).

**Comment by WhateverTheyCallMe** [comment]
This is still happening to me in browser and iOS apps

Server version
10.10.6
Web version
10.10.6 (c335a3024)
Build version
10.10.6

**Comment by SylvainBigonneau** [comment]
Same on Android (v2.6.2, server and web on v10.10.6)

**Comment by Itschotsch** [comment]
Seems to still be happening on the latest version of Jellyfin on the Firefox web UI and the Android app.

**Comment by Fabeson** [comment]
@thornbill @dmitrylyzo Could you please have a look into this? 

Issue is still present in v10.11.5 and also affecting general shuffle playback of eg. "Home Videos and Photos" libraries without genre selection. It also happens in certain genre selections. It also affects the Jellyfin iOSmobile app (Swiftfin and Streamyfin do not support Shuffle playback in genre view)

Examples in my case:

Action & Adventure
6 Series (Folders)
with 26, 8, 43, 24 ,32 ,4 episodes respectively - 137 total
--> Playback Error - Unable to find a valid media source to play.

Animation
3 Series (Folders)
with 99+, 26, 99+ episodes respectively - >226 total
--> shuffle works

No log entries referring to the Playback error, only successful play attempts are being logged.

Please advise what info I can provide to analyse / fix?
