### ISSUE TITLE
Double click to fullscreen not working on Firefox  

### ISSUE THREAD

**Issue by camcs1** [jellyfin/jellyfin-web#5911]
**Describe The Bug**

Double clicking the center of the playback does not cause it to full screen consistently 
**Steps To Reproduce**

1. Open Firefox and maximize the window
2. Double click the player

**Expected Behavior**

I expect to toggle between full screen and windowed playback when double clicking
**Logs**

> loading installed plugins main.jellyfin.bundle.js:2:248341
loading packages main.jellyfin.bundle.js:2:221169
The Notification permission may only be requested in a secure context. index.html
HLS Error: Type: otherError Details: internalException Fatal: false main.jellyfin.bundle.js:2:73379
    P http://homepc.local:8096/web/main.jellyfin.bundle.js?4eb8ea179f4fc2baed3a:2
    emit http://homepc.local:8096/web/node_modules.hls.js.970a5cb5618e7282c138.chunk.js:1
    emit http://homepc.local:8096/web/node_modules.hls.js.970a5cb5618e7282c138.chunk.js:1
    trigger http://homepc.local:8096/web/node_modules.hls.js.970a5cb5618e7282c138.chunk.js:1
    onerror http://homepc.local:8096/web/node_modules.hls.js.970a5cb5618e7282c138.chunk.js:1
ReferenceError: t is not defined e0782231-f337-4db5-ad82-5d9ab9db15c3:1:100
    e blob:http://homepc.local:8096/e0782231-f337-4db5-ad82-5d9ab9db15c3:1
    <anonymous> blob:http://homepc.local:8096/e0782231-f337-4db5-ad82-5d9ab9db15c3:1
HLS Error: Type: otherError Details: internalException Fatal: false main.jellyfin.bundle.js:2:73379
    P http://homepc.local:8096/web/main.jellyfin.bundle.js?4eb8ea179f4fc2baed3a:2
    emit http://homepc.local:8096/web/node_modules.hls.js.970a5cb5618e7282c138.chunk.js:1
    emit http://homepc.local:8096/web/node_modules.hls.js.970a5cb5618e7282c138.chunk.js:1
    trigger http://homepc.local:8096/web/node_modules.hls.js.970a5cb5618e7282c138.chunk.js:1
    onerror http://homepc.local:8096/web/node_modules.hls.js.970a5cb5618e7282c138.chunk.js:1
ReferenceError: t is not defined e951a427-69bc-45c4-b434-8dd9309df388:1:100
    e blob:http://homepc.local:8096/e951a427-69bc-45c4-b434-8dd9309df388:1
    <anonymous> blob:http://homepc.local:8096/e951a427-69bc-45c4-b434-8dd9309df388:1
HLS Error: Type: mediaError Details: bufferStalledError Fatal: false main.jellyfin.bundle.js:2:73379
    P http://homepc.local:8096/web/main.jellyfin.bundle.js?4eb8ea179f4fc2baed3a:2
    emit http://homepc.local:8096/web/node_modules.hls.js.970a5cb5618e7282c138.chunk.js:1
    emit http://homepc.local:8096/web/node_modules.hls.js.970a5cb5618e7282c138.chunk.js:1
    trigger http://homepc.local:8096/web/node_modules.hls.js.970a5cb5618e7282c138.chunk.js:1
    _reportStall http://homepc.local:8096/web/node_modules.hls.js.970a5cb5618e7282c138.chunk.js:1
    poll http://homepc.local:8096/web/node_modules.hls.js.970a5cb5618e7282c138.chunk.js:1
    checkBuffer http://homepc.local:8096/web/node_modules.hls.js.970a5cb5618e7282c138.chunk.js:1
    onTickEnd http://homepc.local:8096/web/node_modules.hls.js.970a5cb5618e7282c138.chunk.js:1
    doTick http://homepc.local:8096/web/node_modules.hls.js.970a5cb5618e7282c138.chunk.js:1
    tick http://homepc.local:8096/web/node_modules.hls.js.970a5cb5618e7282c138.chunk.js:1

**Screenshots**

**System (please complete the following information):**
 - Platform: Windows 10 22H2
 - Browser: Firefox 129.0.1 (64-bit) 
 - Jellyfin Version: 10.9.9 (Also present on 10.9.8)
 - Display resolution: 3840 x 2160

**Additional Context**

I have noticed that if I double click with the window not maximized (or with dev tools open) I am able to full screen the player with an initial double click but I am then unable to exit with a subsequent double click

**Comment by dmitrylyzo** [comment]
Double click works for me (Firefox 129, Chromium 127). :man_shrugging:

**Comment by camcs1** [comment]
Doh! I had my display mode set to experimental, changing back to auto restores the ability to double click to full screen (and also restores single click to play/pause) 

Apologies for any time wasted...
