### ISSUE TITLE
Multiple Artists on an Album Wrecks the UI (Library view and album view)

### ISSUE THREAD

**Issue by picasso566** [jellyfin/jellyfin-web#5963]
**Describe The Bug**
Web version  10.9.9
Server version 10.9.9
_Similar to https://github.com/jellyfin/jellyfin-web/issues/4228 which was closed 2 years ago._ 

Even a single album with many artists (Compilation, Mix, Various Artists Collections, etc.) wrecks the Music library UI:
1. The Album View overflows with the names of artists. 
![Jellyfin Multiple Artists in Album](https://github.com/user-attachments/assets/97d47804-c120-4ba8-9c30-6723a95be75c)

2. The Artists List is filled with names from a single album. 
![Jelly Huge Artists List](https://github.com/user-attachments/assets/ba16341e-fc5e-45c4-be56-31757164ba75)

**Steps To Reproduce**
Add an album to your Music library with over 10 artists. It's even worse if the artists are made up names and don't exist in meta sites since the Artists List in the Library View displays possibly hundreds of unknown artists. 

**Expected Behavior**
If an album has more than X artists, truncate the list in the Album View 
It would be great if a single item could be excluded from the paradigm which all albums follow. Turn off artists for an album an force it to "Artist: None" or "Various Artists".

**Comment by viown** [comment]
Your issue will be fixed in https://github.com/jellyfin/jellyfin-web/pull/4830, which should release in 10.10

**Comment by picasso566** [comment]
For anyone else running into this I was being a bit obtuse. 
A work around is just deleting the Artist and Album from the meta on each track and rescan. The mp3tag app worked for me.
