### ISSUE TITLE
Epiphany (Gnome Web): buttons in player controls are too wide

### ISSUE THREAD

**Issue by agboom** [jellyfin/jellyfin-web#598]
**Describe the bug**

In Epiphany browser (Gnome Web), buttons in player controls are too wide in bottom player and queue page.

**To Reproduce**

1. Open a Jellyfin web player in Epiphany
2. Play a random song
3. Notice the bottom player is not as is should be (some buttons are too wide)
4. Click on the queue button in the bottom right corner
5. Notice that some buttons here are too wide as well

**Expected behavior**

Buttons are round

**Logs**

**Screenshots**

Bottom player:
![2019-11-25-200034_screenshot](https://user-images.githubusercontent.com/1269113/69570315-dbdbb280-0fbf-11ea-86b7-709a48ee3857.png)
Queue player:
![2019-11-25-200824_screenshot](https://user-images.githubusercontent.com/1269113/69570325-e1d19380-0fbf-11ea-9e0a-118b7f298135.png)

**System (please complete the following information):**
 - OS: Docker
 - Browser: Epiphany 3.34.1 (WebKitGTK 2.26.2)
 - Jellyfin Version: 10.4.2

**Comment by JustAMan** [comment]
Should probably wait till we implement Babel (and CSS compilation, too).

**Comment by MrTimscampi** [comment]
Seems to be fixed on master with Gnome Web 3.34.3.1

![image](https://user-images.githubusercontent.com/19396809/75561861-f9e60280-5a47-11ea-91ad-d524e68c80fc.png)
