### ISSUE TITLE
High CPU load

### ISSUE THREAD

**Issue by Iowerth** [jellyfin/jellyfin-web#6019]
**Describe The Bug**
When watching movie in browser then CPU loads at high level depending of how many cores (threads in transcoding options) are using.

**Media Information**
Any movie.

**Screenshots**
2 cores (4th column):
![2 cores](https://github.com/user-attachments/assets/27a35755-530a-4573-a647-c5670d4a2e6f)

All cores:
![all](https://github.com/user-attachments/assets/15df9a38-4cc8-4dab-961f-322869ba3c2f)

**System (please complete the following information):**
 - Platform: Windows 10 x64
 - Browser: Firefox latest version
 - Jellyfin Version: 10.9.10

For example, Media Player Classic loads CPU in about 1-2%. I assume that Jellyfin high loads CPU because of transcoding. Didn't found how to disable it and use direct play instead.

**Comment by viown** [comment]
This is normal. Your browser does not support as many codecs as Jellyfin Media Player does, so the server will transcode them to something that is compatible. You can't disable this and still get playable video.

To reduce CPU usage, look into enabling hardware acceleration: https://jellyfin.org/docs/general/administration/hardware-acceleration/

**Comment by Iowerth** [comment]
Thanks. I'll try.
