### ISSUE TITLE
Music Genre not displaying any Song altough populated with Songs

### ISSUE THREAD

**Issue by Markusvanhode** [jellyfin/jellyfin-web#6021]
**Describe The Bug**
When navigating to the genre tab inside my music library no identified song is displayed. When trying to click in the middle of the genre cover picture songs get played that are identified to this genre. So in simple words, songs get correctls identified to be releated to a genre but wont show up in the list inside the genre.

**Steps To Reproduce**

1. Go to music library
2. Click on genre
3. Choose any genre and click on its name which is displayed right below
4. See error as there are no song displayed
5. Navigate back to genre list
6. Click in the middle of the genre preview picture to trigger the play button
7. Songs play that are related to the genre altough 0 are listed inside the genre

**Expected Behavior**
Genre displays songs it identified to match

**Screenshots**
![path](https://github.com/user-attachments/assets/75220832-23d2-4443-82da-ae70ab6206ee)
![Screenshot 2024-09-04 at 18-04-39 Musik](https://github.com/user-attachments/assets/1cfa6772-34aa-4840-8062-65134d010715)
![songmetadata](https://github.com/user-attachments/assets/c3aadf97-78e4-4f5b-bd01-1d3b75007746)
![Screenshot 2024-09-04 at 17-59-03 Afro House](https://github.com/user-attachments/assets/4e3fd80d-fcaf-4f3a-a605-8cb47aba04e9)
![Screenshot 2024-09-04 at 17-58-52 Musik](https://github.com/user-attachments/assets/98166f93-07fe-4ab4-a88c-1a4e665a2eb5)

**System (please complete the following information):**
 - Platform: Main Windows 10 with Jellyfin v. 10.9.9 + another Windows 10 machine with Jellyfin v. 10.9.10 + Docker with Jellyfin v. 10.9.10
 - Browser: Firefox 129.0.2
 - Jellyfin Version: stated above

**Additional Context**
Might be related, might not be related. When checking the metadata path of the genre, the path showen is supposed to be "C:\Users\Server\AppData\Local\Jellyfin\metadata\MusicGenre\Afro House". When checking that exact path there is none after metadata that is named MusicGenre. So i assume the metadata is incorrectly saved.

I also made sure that the metadata tags are correct within the song. So jellyfin should be able to properly identify the song.

**Comment by viown** [comment]
Your issue seems similar to mine (https://github.com/jellyfin/jellyfin-web/issues/5917), but I'm able to list the items from the Genres tab. Have you tried a full re-scan?

In either case, I believe this is due to a server issue returning invalid ids.

**Comment by Markusvanhode** [comment]
Yep tried full rescan. I also tried to add the music to different librarys with the same outcome. In the end i tried retagging my library using MusicBrainz Picard, still no change. But all in all the metadata seems to be correct on my songs, just jellyfin somehow wont recognize it properly or wont display it.

There also seem to be issues with the display of artist and bands as they dont show any song either.

When playing a song and clicking on the album name im also able to trigger a endless loading circle that only stops when refreshing the site. The link it sends me too is the following: http://192.168.178.71:8056/web/#/details?id=undefined&serverId=821c69cba0224713a90d6832908ec7d0

**Comment by Markusvanhode** [comment]
@viown could you tell me with which version of jellyfin server you started implementing your music library. I have tested the last version of 10.8.x on a different machine and cant seem to even get genre working there.

**Comment by viown** [comment]
> @viown could you tell me with which version of jellyfin server you started implementing your music library. I have tested the last version of 10.8.x on a different machine and cant seem to even get genre working there.

Hmm, have you tested with a fresh Jellyfin install? This could be a problem with your media, but I can't tell you at first glance what's causing it. Also don't worry about the missing metadata path as those don't represent real paths.

Here are some things I'd try:

- Just for testing, try converting some of the files to MP3 or FLAC (you can use a tool like ffmpeg to do this) and make sure they have the correct metadata in something like Picard.
- Try creating a fresh install of Jellyfin through Docker (https://jellyfin.org/docs/general/installation/container/)

**Comment by Markusvanhode** [comment]
Thanks for the tips. In the end i sadly figured out that altough the jellyfin music description from my perspective suggest that a certain folder structur isnt mandatory and data will be scraped from metadata, it is mandatory to have a certain folder structur. Only Album folders get displayed within the genre tabs. Single tracks without album folders wont be displayed.
