### ISSUE TITLE
Subtitles menu is way too big

### ISSUE THREAD

**Issue by Vitorvlv** [jellyfin/jellyfin-web#603]
Sometimes when I open the subtitles menu it is way too big, and it gets kinda cut off from the screen. This happens randomly, never noticed a pattern. If I close the Jellyfin tab and open a new one it fixes it.

 - OS: Manjaro
 - Browser: Firefox
 - Jellyfin Version: 10.4.2

I've added one screenshot of the oversized menu and one of it working normally after I closed the jellyfin tab and opened it again.

![Screenshot_20191128_183327](https://user-images.githubusercontent.com/26132870/69832639-408c4c80-120e-11ea-9430-40883de32f24.png)
![Screenshot_20191128_183523](https://user-images.githubusercontent.com/26132870/69832640-4124e300-120e-11ea-9d24-4868fa1ad9e8.png)

**Comment by Nickbert7** [comment]
I saw this also sometimes with the cast menu. I'll make some screenshots next time.

**Comment by JustAMan** [comment]
Could you see if applying https://github.com/jellyfin/jellyfin-web/pull/601 and https://github.com/jellyfin/jellyfin-web/pull/597 fixes that, or (might be easier) if those issues happen only in Firefox and don't happen in e.g. Chromium?

**Comment by Nickbert7** [comment]
This was in Chrome 78
To big:
![image](https://user-images.githubusercontent.com/14938497/69878874-5a896600-12c6-11ea-8dad-84b6abd32693.png)

How it should look like:
![image](https://user-images.githubusercontent.com/14938497/69878880-5e1ced00-12c6-11ea-84a7-f4440bd2eb81.png)

**Comment by Vitorvlv** [comment]
Also, since Firefox is apparently having issues with jellyfin recently, I think it's important to add that this is an old issue I've had since before 10.4.x

I was just too lazy to report it, but this was not something that started recently.

**Comment by dkanada** [comment]
Right now we have a lot of style issues that are caused by the rules getting applied out of order based on when the files are loaded. Not sure how we can easily fix this, but that's probably the issue here as well.

**Comment by dkanada** [comment]
Actually, I think 90% of the issues are with this element (list items that inherit buttons) and a few minor issues with the card builder, so it might not be as bad as I thought.

**Comment by Nickbert7** [comment]
Sometimes also the user settings menu looks weird.
I think this is the same issue:
![image](https://user-images.githubusercontent.com/14938497/70228808-52fa0f00-1755-11ea-91c8-2f1f8656c414.png)
![image](https://user-images.githubusercontent.com/14938497/70228811-555c6900-1755-11ea-8981-ad08d1d1342b.png)

**Comment by JustAMan** [comment]
I wonder if those issues have the same problem with `material-icons` load order (`.material-icon` class sets `display: inline-block` while some of our things need other `display`), see https://github.com/jellyfin/jellyfin-web/issues/842 for reference

**Comment by Vitorvlv** [comment]
![Screenshot_20200602_134222](https://user-images.githubusercontent.com/26132870/83546498-2130ed80-a4d7-11ea-8cdb-e986ac85303d.png)

Looks like the issue is still present, shoo bot
