### ISSUE TITLE
ASS Subtitles not found in some specific case

### ISSUE THREAD

**Issue by lekoOwO** [jellyfin/jellyfin-web#6048]
**Describe The Bug**

Let's say we have a media file named `MyVideo.mp4`,

Jellyfin web does not recognize `MyVideo.custom.ass` as its subtitle, but the TV App do.

**Expected Behavior**
 `MyVideo.custom.ass` recognized as `MyVideo.mp4`'s subtitle and is available as a choice.

**System (please complete the following information):**
 - Platform: Web
 - Browser: Chrome
 - Jellyfin Version: 10.9.7

**Comment by dmitrylyzo** [comment]
Please elaborate the "does not recognize" because web doesn't recognize anything - it receives everything from the server.

**Comment by lekoOwO** [comment]
> Please elaborate the "does not recognize" because web doesn't recognize anything - it receives everything from the server.

I mean, the subtitle is not available for choice when playback (the "CC" button didn't even show up)

**Comment by lekoOwO** [comment]
Uhh, It turns out that there is delay for jellyfin to detect the ASS subtitle (the subtitle wont show up in the first few hours when subtitle is put it to the video folder), might not be a specific problem for web.

Sorry for bothering.
