### ISSUE TITLE
Audio playback gets cut off followed by infinite loading spinner.

### ISSUE THREAD

**Issue by shyzus** [jellyfin/jellyfin-web#6054]
**Describe The Bug**
When playing back media specifically audio/music. The jellyfin web client suddenly starts showing its loading spinner and the music stops. No way to play any other type of media. Audio or video for that matter without doing a full refresh and creating a new session.

**Media Information**
```
ffprobe version 6.0.1-Jellyfin Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 13 (Ubuntu 13.2.0-23ubuntu4)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, flac, from 'Nero - Welcome Reality - 01 - 2808.flac':
  Metadata:
    ALBUM           : Welcome Reality
    album_artist    : Nero
    ARTIST          : Nero
    COMMENT         : ®™©_py
    DATE            : 2011
    disc            : 1
    GENRE           : Dubstep
    TITLE           : 2808
    DISCTOTAL       : 1
    TRACKTOTAL      : 14
    track           : 01
  Duration: 00:01:53.67, start: 0.000000, bitrate: 846 kb/s
  Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
  ```

**Screenshots**
![afbeelding](https://github.com/user-attachments/assets/18d2b810-c258-438b-b1a1-4d4f3cd0a7d1)

**System:**
 - Platform: Fedora Linux 40
 - Browser: Firefox
 - Jellyfin Version: 10.9.11

**Additional Context**
Noticed a 404 HTTP error in the firefox web developer console.
Method + URL: ```GET https://${MY_DOMAIN}/web/${MY_DOMAIN}/system/info/public```

This url seems malformed and should probably be ```https://${MY_DOMAIN}/web/system/info/public```

For what its worth this issue also happens with the jellyfin desktop app on both windows clients and linux clients.

**Comment by shyzus** [comment]
@viown 
I have provided a redacted HAR file here: https://file.io/EkpXPqGFiG1a

This should give you a good amount of info on all HTTP traffic of the web client from my new attempt of listening to music until jellyfin breaks.

I have checked the jellyfin server logs and found no errors or warnings or any out of the ordinary logs.

**Comment by viown** [comment]
Your error seems to be coming from here:

https://github.com/jellyfin-archive/jellyfin-apiclient-javascript/blob/0595869949a6da0b9e62f6a2c4a4e349f5282109/src/apiClient.js#L216

Which triggers the error when it can't find 'http' in your address.

If I try to add a server address to jellyfin-web without specifying http, it'll correctly recognize that it's missing and add it automatically. I'm not sure why it's missing for you, but you most likely have a configuration error *somewhere*.

Interestingly, if I manually change the address to not include http, I do see a similar malformed URL to yours: `http://${MY_DOMAIN}/web/${MY_DOMAIN}/system/info/public`

So I'd say double-check your networking config. Check your 'Networking' tab in the dashboard. If you're using docker with `JELLYFIN_PublishedServerUrl`, make sure it includes the protocol (http/https) in the beginning.

**Comment by shyzus** [comment]
> So I'd say double-check your networking config. Check your 'Networking' tab in the dashboard. If you're using docker with `JELLYFIN_PublishedServerUrl`, make sure it includes the protocol (http/https) in the beginning.

In my case the published server url does not include the protocol. il modify it and see if it still happens

**Comment by shyzus** [comment]
Oh I forgot this issue was still open. @viown adding the protocol indeed resolved the bug I was facing. Thanks for your help!

Hopefully the LSIO jellyfin readme will be updated to include this in their example as well.
