### ISSUE TITLE
No pinch to zoom feature in personal picture gallery. 

### ISSUE THREAD

**Issue by HugoPourrierNunez** [jellyfin/jellyfin-web#606]
Hi, 
I currently can't find any way to zoom in a photo on the android app in version 0.9.4.
I didn't find anything in the parameters ? Is this a bug or a missing feature ? 
I have tested on a Galaxy s10e and a Huawei p20 pro. 
Thank you for your help  :)

**Comment by JustAMan** [comment]
Activity tracking moved to https://github.com/jellyfin/jellyfin-web/issues/857
