### ISSUE TITLE
Favorite detail list fails to load

### ISSUE THREAD

**Issue by enter-a-random-username** [jellyfin/jellyfin-web#6074]
**Describe The Bug**

I can't load list view for shows or movies inside favorites.

**Steps To Reproduce**

1. Go to Favorites overview
2. Click to list shows or movies

**Logs/Additional Context**

```js
{showTitle: undefined, showYear: true, imageType: 'primary', viewType: 'images'}
```
Exception is caused because object above is used in
https://github.com/jellyfin/jellyfin-web/blob/master/src/controllers/list.js#L859
and has no `Type`

_Workaround/fix_
`item?.Type`

I don't know the origin of the issue. Seems like wrong object is passed to/inside the list functionality.

Only list broken. Search and other lists + filters are working.

**System (please complete the following information):**
 - Jellyfin Version: main/master + some patches - closed to that code is properly to display Art (Clearart)
 in listing like logos (extended a few lists).
- Display React is used

**Comment by viown** [comment]
The origin is here https://github.com/jellyfin/jellyfin-web/pull/5949 (my bad). Fix PR here: https://github.com/jellyfin/jellyfin-web/pull/6041

**Comment by viown** [comment]
It should be backported to master by the next release. Until then, you can temporarily patch it yourself and rebase afterwards.
