### ISSUE TITLE
Cannot Favorite tracks on Mobile

### ISSUE THREAD

**Issue by alpha1** [jellyfin/jellyfin-web#614]
Right now you can favorite albums and artists but not songs, from various lists (Songs etc) in the mobile apps You can favorite songs in the mobile app.

**Comment by grafixeyehero** [comment]
https://github.com/jellyfin/jellyfin-web/blob/bbf1f8d5df66a58c29f07969caa476852d86ab4a/src/css/librarybrowser.css#L837-L841

**Comment by hamburglar2160** [comment]
i believe that this is fixed in android build 0.9.9

**Comment by samuel9554** [comment]
Fix with the revamp of the player. #1056
