### ISSUE TITLE
Subtitles need to be turned off and on again when playing next episode

### ISSUE THREAD

**Issue by mayankpatibandla** [jellyfin/jellyfin-web#6141]
**Describe The Bug**
When the next episode starts playing, subtitles are not being shown. Opening the subtitle menu shows that the correct subtitle option is already selected, but the subtitles won't show until I turn off the subtitles and then turn them on again.

**Steps To Reproduce**
1. Play an episode with subtitles enabled
2. When next episode starts, subtitles will not be shown
3. Opening the subtitle menu shows that the same subtitle option is selected
4. Selecting "Off" and then turning on the subtitles again will fix the issue

**Expected Behavior**
I shouldn't have to turn subtitles off and on every episode, it should show the subtitles that are already selected.

**System:**
 - Platform: Windows
 - Browser: Chrome
 - Jellyfin Version: 10.9.11

**Comment by viown** [comment]
Your issue may have already been fixed here: https://github.com/jellyfin/jellyfin-web/pull/6112 (set for 10.10)

If you'd like, you can confirm if it fixes it by testing out the latest unstable image (I recommend creating a separate one as you cannot downgrade once you've upgraded).

**Comment by mayankpatibandla** [comment]
Just tested on master branch, seems to be fixed now.
