### ISSUE TITLE
Picture in picture does not work in Firefox

### ISSUE THREAD

**Issue by hypervtechnics** [jellyfin/jellyfin-web#616]
**Describe the bug**
The picture in picture mode on Firefox does not start when clicking. Sometimes the button is missing.

**To Reproduce**
1. Start a video stream
2. When playing click the blue button on the right side

**Expected behavior**
Opening the picture in picture mode.

**Logs**
There are no errors. The Progress is requested.

**Screenshots**
Not required I think. Tell me if you need some.

**System:**
 - OS: Docker on Ubuntu 16
 - Browser: Firefox
 - Jellyfin Version: 10.4.2

**Comment by PrplHaz4** [comment]
I believe this is referring to the Firefox specific feature for PIP.

> Note: The Firefox preference media.videocontrols.picture-in-picture.enabled determines whether Picture-in-Picture mode is enabled.

More info:
https://www.ghacks.net/2019/10/29/a-look-at-firefoxs-upcoming-picture-in-picture-mode/

@hypervtechnics can you provide the OS and version of FF you are on?

**Comment by hypervtechnics** [comment]
It's enabled in `about:config`.

OS: Windows 10 1903
FF: 71.0

**Comment by Froghut** [comment]
if I hide all the <div>'s that are on top of the actual <video> element (using style="display:none") the right click menu will show video related entries and selecting the picture-in-picture entry then works. I guess it has to do with sort order of those elements or something like this.

**Comment by YouKnowBlom** [comment]
This seems to have been fixed recently. Works for me on firefox 72.0.2

```Implementation detail

The Firefox Picture-in-Picture toggle exists in the same privileged shadow DOM space within the 
<video> element as the built-in HTML <video> controls. Because this part of the DOM is inaccessible 
to page JavaScript and CSS stylesheets, it is much more difficult for sites to detect, disable, or hijack the feature.

Into the shadow DOM

Early on, however, we faced a challenge when making the toggle visible on hover. Sites commonly 
structure their DOM such that mouse events never reach a <video> that the user is watching.

Often, websites place transparent nodes directly over top of <video> elements. These can be used to 
show a preview image of the underlying video before it begins, or to serve an interstitial 
advertisement. Sometimes transparent nodes are used for things that only become visible when the 
user hovers the player — for example, custom player controls. In configurations like this, transparent 
nodes prevent the underlying <video> from matching the :hover pseudo-class.

...

To work around these problems, we rely on the fact that the web page is being sent events from the 
browser engine. At Firefox, we control the browser engine! Before sending out a mouse event, we can 
check to see what sort of DOM nodes are directly underneath the cursor (re-using much of the same 
code that powers the elementsFromPoint function).

If any of those DOM nodes are a visible <video>, we tell that <video> that it is being hovered, which 
shows the toggle. Likewise, we use a similar technique to determine if the user is clicking on the 
toggle.]```
[source](https://hacks.mozilla.org/2020/01/how-we-built-picture-in-picture-in-firefox-desktop/)

**Comment by hypervtechnics** [comment]
@YouKnowBlom can confirm this
