### ISSUE TITLE
Playback Bug

### ISSUE THREAD

**Issue by ThamsanQue** [jellyfin/jellyfin-web#6188]
**Describe The Bug**
When you fast forward it jumps back to the start of the video, even when you pause.

**Steps To Reproduce**
1. Click on a video
2. try to fastforward, it should prevent you from doing so or when you in the middle of watching press pause, play should take you back to start of the video.
3. Its happening on the jellyfin mobile client as well

**Expected Behavior**
It should continue from where i left of or allow me to fastforward.

**Logs**

**Screenshots**
[Screencast from 2024-10-10 19-51-06.webm](https://github.com/user-attachments/assets/02f06072-410e-47b6-a70e-031011f68eb2)

**System (please complete the following information):**
 - Platform: Linux Raspberry Pi 5
 - Browser: Brave
 - Jellyfin Version: 10.9.11

**Additional Context**

**Comment by FireGamer3** [comment]
I was unable to reproduce this issue using Brave on Jellyfin 10.9.11

I also attempted this with the master branch of jellyfin-web and also could not reproduce this bug

https://github.com/user-attachments/assets/908038d6-05d1-4b0a-89e4-0ff67156ebca

**Comment by ThamsanQue** [comment]
I tested on firefox its working fine, i think 

1. it might because it hadnt downloaded the frames ahead(the light gray bar).

or hardware limitations of the pi.

**Comment by thornbill** [comment]
It sounds like you are not still having this issue but if you encounter it again please use the resources on [this page](https://jellyfin.org/docs/general/getting-help) for help troubleshooting. (I suspect you might have been hitting some limitations of the pi though.)
