### ISSUE TITLE
"Splash" icon on iOS is stretched weirdly

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [jellyfin/jellyfin-web#620]
The icon is stretched weirdly when added to the home screen on iOS. It's the one that shows when you open the shortcut. Tested on 10.4.2, need to test on 10.4.3

Screenshots to follow.

**Comment by JustAMan** [comment]
@anthonylavado wasn't it fixed by some of your PRs?

**Comment by anthonylavado** [comment]
This should be fixed.
