### ISSUE TITLE
LG WebOS Transport Controls not accessable

### ISSUE THREAD

**Issue by Narfinger** [jellyfin/jellyfin-web#621]
Using jellyfin-webos as wrapper, the transport controls while playing a movie seem inaccessable.
Ok button does nothing and back button returns to the info screen of a file.

The expected behavior is that the ok button brings up the transport controls.

WebOS: 5.50.55
Jellyfin-web: 398b399ec60247ffa659424231eaa05dce2b7b45
Jellyfin: 6f283d80dc00fe63b59dfb7a134528f295615da7

**Comment by JustAMan** [comment]
What are "transport controls" precisely?

**Comment by Narfinger** [comment]
Transport controls is the bar that contains play, pause, forward, backward etc.

**Comment by JustAMan** [comment]
So, when you start the playback, does it already miss the controls, or are they present but you cannot use them?

**Comment by Narfinger** [comment]
Starting playback shows them but after it vanishes the ok button (binding
to enter on a keyboard, I think) does not bring it back up.

**Comment by JustAMan** [comment]
@dmitrylyzo any ideas? Is this broken in the same way on Tizen?

@Narfinger can you test if it works on desktop browser but with TV mode enabled (not sure how to enable it, but reading the source could give pointers) by e.g. pressing Enter?

**Comment by dmitrylyzo** [comment]
@JustAMan yes, on `Enter` OSD don't show up both in Tizen 4 (real) and Chrome in TV mode. I look git log - `Enter` handling (as `Pause`) was removed in 658aedf96a4e337f7e1e3980ba9cb9d0b53095b6.

Currently, for TV layout, OSD shows up on navigation keys (in addition to other shortcuts).Not totally sure, but I think it will be safe to catch `Enter` in TV layout and just `showOsd`. To do this, it can be added to the `NavigationKeys` array.

**Comment by JustAMan** [comment]
I personally feel that in TV layout Enter should pause/unpause _and_ show OSD controls at the same time, I think this is also a way WebOS YouTube app behaves.

**Comment by dmitrylyzo** [comment]
In Tizen 4 YouTube:
* `OK`/`Enter` - show OSD
* `Space` - show OSD and pause
* `Back`/`Esc` - hide OSD (if visible) or back to previous page.

**Comment by JustAMan** [comment]
Yeah, I think on WebOS YouTube uses same scheme (though I didn't test a `Space` as I don't have a keyboard hooked to my TV). Looks like a solid keyboard scheme to follow.

**Comment by Narfinger** [comment]
I can't test at the moment but should this be closed now by the pull request?

**Comment by dmitrylyzo** [comment]
At least in webOS 4 emulator, it works like in https://github.com/jellyfin/jellyfin-web/issues/621#issuecomment-574847608
I just didn't mark this issue as fixed in PR. So you may close issue if you trust me :smile: 
Anyway, you can reopen it at any time if something is wrong.
