### ISSUE TITLE
LG WebOS Back button does not stop the playback

### ISSUE THREAD

**Issue by Narfinger** [jellyfin/jellyfin-web#622]
When a file is playing and the back button on the remote is hit, the movie keeps playing in the background (literally) while the item info page is displayed.

The expected behavior is that the movie is stopped. 

WebOS: 5.50.55
Jellyfin-webos wrapper
Jellyfin-web: 398b399ec60247ffa659424231eaa05dce2b7b45
Jellyfin: 6f283d80dc00fe63b59dfb7a134528f295615da7

**Comment by dmitrylyzo** [comment]
I also had such issue (in emulator). But it is gone :confused: I cannot reproduce it with nightly `jellyfin` and `jellyfin-web` 398b399ec60247ffa659424231eaa05dce2b7b45
