### ISSUE TITLE
Event Listeners are not registered correctly inside "inputManager"

### ISSUE THREAD

**Issue by nerxses** [jellyfin/jellyfin-web#623]
**Describe the bug**
I came across this bug by searching for the reason, why i cannot control a photo slideshow with my arrowkeys. As it turns out the "exists" check for counter "eventListenerCount" inside the methods  "on" and "off"  of  "src/scripts/inputManager" is  wrong. 

''fix on the current master branch''

**To Reproduce**
1. Go to a photo libary
2. start slideshow
3. wait till bottombar is closed after x seconds (why? this "feature" is annyoing see method "onInput" inside "slideshow.js")
4. press right/left Arrowkey (nothing will happen)

**Expected behavior**
right/left Arrowkey should move you to the next/previous picture

**Additional context**
this is the original code of function "on"/"off" inside "src/scripts/inputManager"

    var eventListenerCount = 0;
    function on(scope, fn) {
        if (eventListenerCount) {
            eventListenerCount++;
        }
        dom.addEventListener(scope, 'command', fn, {});
    }

    function off(scope, fn) {
        if (eventListenerCount) {
            eventListenerCount--;
        }
        dom.removeEventListener(scope, 'command', fn, {});
    }

this code will result in the expected behaveior.

    var eventListenerCount = 0;
    function on(scope, fn) {
        if (typeof eventListenerCount != "undefined") {
            eventListenerCount++;
        }
        dom.addEventListener(scope, 'command', fn, {});
    }
    function off(scope, fn) {
        if (typeof eventListenerCount != "undefined") {
            eventListenerCount--;
        }
        dom.removeEventListener(scope, 'command', fn, {});
    }

**Comment by dmitrylyzo** [comment]
IMHO you are right - the code is incorrect.

But...

`eventListenerCount` is defined in `var eventListenerCount = 0;`

So, your code is equal to:
```
var eventListenerCount = 0;
function on(scope, fn) {
    eventListenerCount++;
    dom.addEventListener(scope, 'command', fn, {});
}
function off(scope, fn) {
    eventListenerCount--;
    dom.removeEventListener(scope, 'command', fn, {});
}
```
which is good for the ideal case: `off` calls correspond to `on` ones.

Ideally, `eventListenerCount` should be incremented on successful `addEventListener` and decremented on successful `removeEventListener`.

**Comment by nerxses** [comment]
@dmitrylyzo yeah, your right the "exists" check is unnecessary here :smile: and the counter should only be incremented/decremented if adding/removing of the EventListener was successful. 

I wrote this small fix with as less changes as possible :cry: . Next time i will put some more thought into it :smile:

**Comment by dmitrylyzo** [comment]
@nerxses, perhaps my "Ideally" is not needed at all. _(I am a kind of perfectionist)_

I checked the history.
9956084443b736c08900c024c9b07f66e1e90040
4c3af5b9dde98689d731bc494714079f9e4bbe8e

@dkanada, is an extra check in `on` just a "typo"? And should the code be
```
var eventListenerCount = 0;
function on(scope, fn) {
    eventListenerCount++;                          <-- No need to check
    dom.addEventListener(scope, 'command', fn, {});
}

function off(scope, fn) {
    if (eventListenerCount) {                      <-- Check to not become negative
        eventListenerCount--;
    }
    dom.removeEventListener(scope, 'command', fn, {});
}
```

It works in TV mode. I have not noticed any conflicts with navigation yet. The only thing, you can exit the slide show using the "Back" button on the remote control, but I have not figured out how to do this using the keyboard.

**Comment by dkanada** [comment]
I think at the time someone just commented they should both be checked.

**Comment by nerxses** [comment]
@dmitrylyzo yeah, the commit https://github.com/jellyfin/jellyfin-web/commit/4c3af5b9dde98689d731bc494714079f9e4bbe8e definitly broke the counter.

From my point of view the removed code inside the "on/off" functions of https://github.com/jellyfin/jellyfin-web/commit/9956084443b736c08900c024c9b07f66e1e90040 makes more sense, because the counter will work as expected and it cannot be negative (preventing unexpected behaveiour). Best solution so far!
