### ISSUE TITLE
HTML character codes broken because ampersands replaced with &amp;

### ISSUE THREAD

**Issue by blsz** [jellyfin/jellyfin-web#6235]
Here is an example of a tv series episode title which contains quotation marks.  The result is that `&quot;` is displayed in the web view.

The quotes in the title of the episode should be replaced with `&quot;` not `&amp;quot;`.

```
<div class="listItemBody itemAction">
    <div class="listItemBodyText"><bdi>title &amp;quot;of the&amp;quot; episode</bdi></div>
    <div class="secondary listItemMediaInfo listItemBodyText">
```

**Comment by thornbill** [comment]
Please complete the issue template as requested.

**Comment by blsz** [comment]
This issue affects the android-tv client as well.

**Comment by blsz** [comment]
A similar issue was previously fixed in https://github.com/jellyfin/jellyfin-web/pull/3160 and https://github.com/jellyfin/jellyfin-web/issues/2699.

The web and android-tv clients both render ampersand html codes like this:
![image](https://github.com/user-attachments/assets/99f46853-9018-4008-82cd-712518a20fdd)
