### ISSUE TITLE
Date and time drop down has language options 

### ISSUE THREAD

**Issue by Hmadena** [jellyfin/jellyfin-web#6260]
**Describe The Bug**

Date and time drop down has language options 

**Steps To Reproduce**

1. Go to 'Display settings '
2. Click on 'Date time locale'
3. See error

**Expected Behavior**

Should show date and time options 

**Screenshots**

![image](https://github.com/user-attachments/assets/e6a79153-08ff-4003-a4de-3a7f527832bb)

![image](https://github.com/user-attachments/assets/6ee76536-a71b-4f32-b719-e75524a32d52)

**System (please complete the following information):**
 - Platform: [Windows]
 - Browser: [Chrome]
 - Jellyfin Version: [e.g. 10.9.11]

**Comment by viown** [comment]
What's the issue here?

**Comment by Hmadena** [comment]
Mb

**Comment by viown** [comment]
@Hmadena Sorry, I was just trying to understand your report better. If I understand correctly, you think a date and time example for each locale should be shown there instead of a language?
