### ISSUE TITLE
Persistent filter issue in shows and music libraries

### ISSUE THREAD

**Issue by theguymadmax** [jellyfin/jellyfin-web#6263]
**Describe The Bug**

In a shows or music library, selecting a letter to filter by on the vertical index persists when leaving the library. In contrast, the filter resets upon exiting the following library types: Movies, Mixed Movies & Shows, and Collections.

**Steps To Reproduce**

1. Navigate to your Jellyfin homepage
2. Select a Shows/Music library
3. Click on a letter to filter the library
4. Click the Home icon to return to the homepage
5. Return to the Shows/Music library 
6. Observe that the library remains filtered by the previous selection.

**Expected Behavior**

The filter should be cleared when leaving the library, returning to an unfiltered view.

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Firefox
 - Jellyfin Version: 10.10.0

**Comment by aaemon** [comment]
btnShuffle, btnSelectView, btnSort, btnFilter, and alphaPicker are all persistent across different devices. So, trying to use a filter on one device will mess up all other devices connected to the same account.
