### ISSUE TITLE
Web Interface not Honoring Library Page Size

### ISSUE THREAD

**Issue by JRGonz** [jellyfin/jellyfin-web#6268]
When setting the Library Page Size to 0 (continuous scrolling) my library will still stop at 100 and not advance when the next (right arrow) is clicked. If I change the setting to 500 (as an example) then it will still only display 100 and advance to the next page but it is not 500, it is 100. 

Another library is stuck on continuous scrolling. If I change the Library Page Size setting to 500 then it will still show all shows in the library. 

I have tried to clear the browser cache, used private browsing, and tried 3 different browsers. Even more strange is if I use a different browser (with no Jellyfin cache / cookie data / etc) then it will be broken as well. I do not see this behavior for movie libraries. They seem to follow the setting just fine. I haven't checked music libraries, but show libraries are definitely affected. 

1. Go to Settings, Display
2. Change Library Page Size to 0 (zero)
3. Go to a library with > 100 items. 
4. The page will show 100 and not advance to the next 100 items (even though it should be showing all items instead of only 100)

The expected behavior is that the web client will honor the Library Page Size setting

I did not see any logs applicable to an issue. 

 - Platform: Debian Linux
 - Browser: LibreWolf, Brave, Epiphany, Jellyfin Media Player
 - Jellyfin Version: 10.10.0

Client is Ubuntu running above browsers. 
![Pasted image](https://github.com/user-attachments/assets/4fcf010b-8c5d-4855-8820-7159b2b76f84)
![Pasted image (2)](https://github.com/user-attachments/assets/aabd4974-e3e9-4668-8303-73c4be67e09c)
![Pasted image (3)](https://github.com/user-attachments/assets/c786fa43-3bb1-47e0-bdcc-b9ab9640a568)
![Pasted image (4)](https://github.com/user-attachments/assets/640c62fe-c6e0-4740-ad40-bef985da8dfc)
![Pasted image (5)](https://github.com/user-attachments/assets/3b89c1df-4387-40e4-b89e-4db1dbbcbfa4)
![Pasted image (6)](https://github.com/user-attachments/assets/68a31947-9506-4815-b619-1a6b749b4e15)

**Comment by JRGonz** [comment]
No. This is with the standard web interface (I tried the browsers listed above)  and the official Jellyfin Media Player flatpak. I can't seem to sort out why it is doing it. I even went so far as to remove one of the shows libraries and re-add it and it still persists.

**Comment by JRGonz** [comment]
Just to make absolutely sure. I went into a couple VMs. The problem persists across browsers and is unrelated to the client. First time logging in on the other systems and the Shows library is stuck at the last spot it was on another system. So in this case opening up the library started me off at 401-500 instead of 0. The expectation is a fresh browser with no cache/cookies would not even have the setting at all. It would need to be set under the user settings (defaulted to 100). This doesn't happen. I will attempt to reboot the jellyfin container in a bit and see if that does anything.

**Comment by viown** [comment]
Got it. Your issue may be because of https://github.com/jellyfin/jellyfin-web/pull/5717

In which case, I've already had a fix ready. I was initially waiting for https://github.com/jellyfin/jellyfin-web/pull/6264 to be merged, but it makes more sense to fix these in one PR.

**Comment by viown** [comment]
Feel free to test the cloudflare deployment in that PR and see if it fixes your issue.

**Comment by JRGonz** [comment]
I already rolled back to 10.9. I’ll just wait on the patches to be pushed. Appreciate it.
