### ISSUE TITLE
LG webOS Client forces wrong audio selection when DTS enabled on multi audio track media

### ISSUE THREAD

**Issue by armanckeser** [jellyfin/jellyfin-web#6289]
**Describe The Bug**

When playing media with DTS audio tracks with DTS enabled in client settings, the audio is forced to be a track you might not have chosen. (I belive it is the bottom most listed track, in one video it forced descriptive audio, in the other the wrong language)

**Steps To Reproduce**

1. Enable dts
2. Go to a media with multiple DTS audio tracks
3. Play media
4. Audio is the wrong track and cannot be changed to anything else.

**Expected Behavior**

The chosen audio track is streamed instead of the wrong one

**Logs**

No errors or transcoding goes on, not sure where to get logs for just direct streams.

**Screenshots**

**System (please complete the following information):**
 - Platform: [e.g. Linux, Windows, iPhone, Tizen]
 - Browser: [e.g. Firefox, Chrome, Safari]
 - Jellyfin Version: [e.g. 10.6.0]
- Platform: Windows
- Browser: webOS app LG c1 
- Jellyfin: 10.9.6

**Additional Context**

I had this happen in a movie where the last audio track was descriptive audio, and I couldn't change it. I just got another video that also had DTS audio, after enabling it, the problem of having another audio being forced happened again.

**Comment by viown** [comment]
Could you update to 10.10 and confirm it still happens there?

**Comment by armanckeser** [comment]
Updated to 10.10 and the issue is still there.
Tested from the webOS app and the webOS browser, the issue is still there.
I can't replicate on my computer as my computer doesn't support DTS (even if I enable it in the settings), is there a way to fake that to test?

**Comment by armanckeser** [comment]
Looks like LG C1 doesn't even support passing DTS through.
