### ISSUE TITLE
10.10.0 Subtitles not displayed when playing on web page

### ISSUE THREAD

**Issue by Godzeze** [jellyfin/jellyfin-web#6290]
**Hello, my jellyfin was upgraded to version 10.10.0 today, but it cannot display embedded subtitles and external subtitles.**
**你好，我的jellyfin今天升级到10.10.0版本，但是无法显示内嵌字幕和外挂字幕。**

![Image](https://github.com/user-attachments/assets/02b25251-1b25-43bc-a32e-13ff469ac9d1)

The first picture has embedded subtitles
第一张图片是内嵌字幕
Mark 1, Chinese and English subtitles cannot be displayed
Mark 2, English and Chinese subtitles cannot be displayed
Mark 3, Chinese can be displayed
标记1，无法显示中英文字幕
标记2，无法显示英中文字幕
标记3，可以显示中文

6. can be displayed![Image](https://github.com/user-attachments/assets/746ee42a-7aac-4eed-80d4-81a3002c885f)

The second picture has external subtitles. 
第二张图片有外挂字幕
Mark 1: Unable to display.
标记1：无法显示

I tried to modify the subtitles or reinstall the jellyfin server, but neither solved the problem.
我尝试过修改字幕，或者重装jellyfin服务器，但是都没有解决问题。
Please help me see how to solve this problem, Thank you very much.
请帮我看下，如何解决这样问题，感谢。

Server name: DS718
Server version: 10.10.0
Web version: 10.10.0 (6b1b259)
Build version: Release
服务器名称：DS718
服务器版本：10.10.0
网页版本：10.10.0 (6b1b259)
构建版本：Release

**Comment by viown** [comment]
Please clear your browser cache and try again.

**Comment by Godzeze** [comment]
> Please clear your browser cache and try again.

Yes, I have solved it. It is caused by browser cache, just like you said. Thank you for your reply.
