### ISSUE TITLE
Background picture lost for some themes in 10.10.1

### ISSUE THREAD

**Issue by gnattu** [jellyfin/jellyfin-web#6292]
**Describe The Bug**

**Steps To Reproduce**

1. Go to Settings
2. Change theme to a theme that has background picture like blue radiance
3. See the picture is lost

**Expected Behavior**

The bg.jpg should be loaded

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Platform: All
 - Browser: All
 - Jellyfin Version: 10.10.1

**Additional Context**

I suspect it is due to https://github.com/jellyfin/jellyfin-web/pull/6284 so that the bg.jpg for themes are no longer being packed into the bundle. By manually coping the image file the background image loads as before.

**Comment by thornbill** [comment]
This should be fixed when 10.10.2 is released.
