### ISSUE TITLE
Android Webbrowser Fullscreen doesn't hide nav buttons

### ISSUE THREAD

**Issue by gpulido** [jellyfin/jellyfin-web#63]
Using Chrome browser on android, when watching a video and going to full screen the Android nav bar is not hidden (android 8.1)
Just for reference, same scenario with emby hides them.

**Comment by bugfixin** [comment]
This may be fixed by changing the "display" key in the manifest.json -- I'll do some testing on it

**Comment by dkanada** [comment]
[this](https://stackoverflow.com/a/55826754) might be related
