### ISSUE TITLE
Preview "Ask To Skip" - No Button

### ISSUE THREAD

**Issue by AbandonedCart** [jellyfin/jellyfin-web#6322]
**Describe The Bug**
Enabling "Ask To Skip" for "Preview Segments" doesn't enable a skip button

**Steps To Reproduce**

1. Generate a preview segment (dealer's choice)
2. Open the client settings
3. Select "Playback"
4. Scroll to "Preview Segments"
5. Enable "Ask To Skip"
6. Save
7. Play media file with know preview segment
8. Observe nothing happening during preview

**Expected Behavior**
A button similar to the intro and outro button to appear

**Logs**
No errors encountered.

**Screenshots**
![Image](https://github.com/user-attachments/assets/832bf1f0-b728-4270-849e-0e394981bc5d)

**System (please complete the following information):**
 - Platform: macOS / Windows / Android
 - Browser: Firefox / Jellyfin Media Player
 - Jellyfin Version: 10.10.1

**Additional Context**
Tested in Firefox on Mac, Windows, and Android. Tested in Jellyfin Media Player on Windows.
Enabling the "Skip" option appears to function normally.

**Comment by viown** [comment]
This works as expected on my end in 10.10.1:

![Image](https://github.com/user-attachments/assets/ce47674d-1eaf-4947-9896-d315ec4ea1c9)

Have you confirmed the segment is within the expected range and is of type "Preview" (2)?

**Comment by AbandonedCart** [comment]
> Have you confirmed the segment is within the expected range and is of type "Preview" (2)?

Yes

> Do you also see a "found Preview segment" log message in console?

Server? Browser? Can you be more specific?

**Comment by AbandonedCart** [comment]
I did some messing around and realized the problem is that the labeling is convoluted.

In television, a recap typically recaps the season so far and a preview previews the upcoming episode.

In jellyfin, a preview is at the beginning (probably attributed to movie previews) and a recap is at the end (I don't have good logic for why anyone thought a show or movie recaps itself)
