### ISSUE TITLE
Plugin structure and examples

### ISSUE THREAD

**Issue by ryandikdan** [jellyfin/jellyfin-web#6343]
Is there documentation anywhere about the proper structure for making plugins? What class must be made/what methods are called? I want to add a simple menu option in the actionSheet for Albums and I don't generally work with javascript so I'm a bit stuck. 

Also some documentation for plugins might make it easier for other modifications. Thanks for all the great work!

**Comment by viown** [comment]
https://github.com/jellyfin/jellyfin-web/blob/2616432bdd07785b5bfb24fb0f56b8410f12e15b/src/components/itemContextMenu.js

Is this what you're looking for?

**Comment by viown** [comment]
Is this what you're looking for? https://github.com/jellyfin/jellyfin-web/blob/master/src/components/itemContextMenu.js

**Comment by ryandikdan** [comment]
That's it! I was hoping to be able to make a simpler plugin, but I can modify this quite easily, thanks!

**Comment by thornbill** [comment]
There is no supported way for plugins to modify the web ui.
