### ISSUE TITLE
Cannot download files when the name contain an apostrophe

### ISSUE THREAD

**Issue by valmar** [jellyfin/jellyfin-web#637]
If I try to download a file via the web interface, and the file name contains an apostrophe, the download fails

To reproduce, just click on the three dots close to a file, and choose Download. If the file name contains an apostrophe, the size of the downloaded file will be 0. The file should be fully downloaded instead.

The log files shows this:

jellyfin    | [00:14:35] [ERR] Could not find handler for /service/recordings/get
jellyfin    | [00:14:35] [ERR] Error processing request: Unable to find the specified file.

I am running version 10.4.3 (Docker) on a Raspberry Pi 4

The download fails using both firefox and Vivaldi (latest versions)

**Comment by JustAMan** [comment]
Can you post a link you're trying to download (sanitize your server and other potential data)?

**Comment by valmar** [comment]
Unfortunately not, because my server is running on a LAN, with no access to outside.
For now, as a workaround, I renamed the file. Please notice that a single quote works, just not an apostrophe

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by JustAMan** [comment]
Heh, why running inside LAN contradicts what I said? I merely wanted to see the link (not download stuff by following it). Something like right click -> copy link to clipboard -> go to this issue -> paste a comment with that link :)

**Comment by valmar** [comment]
Ah sorry I misunderstood! I will send you the link as soon as I get home from work this evening. Thank you for looking into this

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by valmar** [comment]
Ok, this is the link generated by clicking the download button:

http://192.168.2.106:8096/Items/11ef0233270ee58530182d32ff4cf41c/Download?api_key=<api_key_here>

**Comment by JustAMan** [comment]
Hmm, it gives no key to why it's failing... what is your client you're using? OS, browser, browser version?
Also can you restart your server, try to download bad file, and then post the whole log (remember to sanitize it if it has some sensitive information)? It might be server-side, not client one.

**Comment by valmar** [comment]
I run the docker container and in the docker love.I only see what I posted in the first message. Is there a way to obtain a more detailed log?

Browser is firefox, but I also tried with Chrome. OS is Fedora Linux 31 (client) and raspbian buster (server)

-------- Original Message --------

**Comment by JustAMan** [comment]
You can try enabling debug (more verbose) logging, see https://jellyfin.org/docs/general/administration/connectivity.html#debug-logging

Also just downloading the whole log file via web interface and, looking at timestamps, cutting a relevant piece could help (those two lines are certainly not enough).
