### ISSUE TITLE
transcode used for ogg vorbis files unecessarily in chrome browser

### ISSUE THREAD

**Issue by bd4** [jellyfin/jellyfin-web#638]
In chrome, playing ogg vorbis files causes Jellyfin to do a transcode, because of this in the device profile:
https://github.com/jellyfin/jellyfin-web/blob/master/src/scripts/browserdeviceprofile.js#L118

Are there any versions of chrome still deployed that have trouble playing ogg vorbis files? This strikes me as a legacy concern, that is causing unneeded server resource usage and the quality loss of the re-encode. When I comment out those lines in jellyfin-web on my server, my version of chrome (78.0.3904.108) plays them just fine (and I can verify in the server log that transcoding is no longer being done).

It also is related to a bug in jellyfin-andorid, which includes / uses jellyfin-web. The user-agent string jellyfin-android passes to the server includes Chrome, among many others, so it is counted as not supporting ogg, when in fact it does. And in this case, instead of just causing an unneeded transcode, it doesn't play at all for some reason:
https://github.com/jellyfin/jellyfin-android/issues/83

We could monkey patch a change into jellyfin-android after it pulls jellyfin-web, but I am wondering if disabling ogg vorbis in chrome is really still needed in jellyfin-web? Note that opus is enabled to play directly, and also works fine.

**Comment by JustAMan** [comment]
There are funny devices like Smart TVs which have embedded Chrome (which never updates), though they probably also play ogg, as, per Wiki, ogg support was added in Chrome 3.0...

**Comment by dkanada** [comment]
should be working in the next release
