### ISSUE TITLE
[FeatureRequest] disable numeric key for skipping

### ISSUE THREAD

**Issue by coucoy** [jellyfin/jellyfin-web#6417]
Would it be possible to add configuration options to disable the numeric key [0-9] to change playback position.

Sometimes I disable NumLock and completely lose my current position.

See : https://github.com/jellyfin/jellyfin-web/blob/3311a1407f7f6cf2c802afdf1f6086d21192a374/src/controllers/playback/video/index.js#L1363C1-L1377C14

Have a nice day.

**Comment by thornbill** [comment]
Feature requests belong at https://features.jellyfin.org/
