### ISSUE TITLE
Helper when no libraries are added

### ISSUE THREAD

**Issue by hammerings** [jellyfin/jellyfin-web#642]
I created a new user without setting up any libraries when doing so. So the home view is naturally empty. I would find it helpful to have a direct link to adding libraries there and perhaps under "media" in the lefthand navigation menu. Something like "Seems like you haven't added any libraries folders yet. Add now?" where add now would be a link.

**Comment by JustAMan** [comment]
I don't think non-admin users can create libraries, can they now?..

**Comment by anthonylavado** [comment]
@JustAMan I think he means if you set up Jellyfin but don’t add any libraries in the startup wizard. Right now you just get placed in to an empty home screen.
