### ISSUE TITLE
The "Watched" and "Favorite" icons aren't very clear

### ISSUE THREAD

**Issue by MrTimscampi** [jellyfin/jellyfin-web#647]
**Describe the bug**

The icons used for "Watched" and "Favorite" aren't very clear right now.

Right now, due to using filled icons of the same colours as other icons, these two icons look "enabled". So when going on a media's details page, a user may think the media has already been watched or added to the favourites.

**To Reproduce**

1. Go to a media details page (Movie, TV show or other
2. Look at the icons

**Expected behavior**

When unwatched, the icon used should be an X (Or better, move the icon to the expanded menu, as it's not really a primary icon)  
When not added to favourites, the heart shouldn't be filled.

**Logs**

n/a

**Screenshots**

![image](https://user-images.githubusercontent.com/19396809/71320432-763df180-24ab-11ea-9e0c-8752e17c450e.png)

**System (please complete the following information):**
 - OS: Docker
 - Browser: Firefox
 - Jellyfin Version: 10.4.3

**Additional context**

n/a

**Comment by Xalaxis** [comment]
I disagree, I think it's pretty clear that an unlit icon is disabled.  I also think watch status and favorite status are definitely a primary icon, they're one of the most likely actions a user would want to toggle besides watching the item selected.
