### ISSUE TITLE
No GUI focus in user selection screen

### ISSUE THREAD

**Issue by WilcoVertegaal** [jellyfin/jellyfin-web#662]
**Describe the bug**
When opening the Jellyfin web application, if you are not logged in automatically, you are presented a list of user accounts to choose from. At that moment, none of the items on the screen has focus. Therefore, on any device that is not touch enabled, it cannot be navigated without giving focus to an element by clicking it with the mouse. This is a problem for mouseless systems obviously, like TVs.

**To Reproduce**
1. Go to Jellyfin web application
2. Make sure you have multiple user accounts
3. Logout by selecting the user icon in the upper right of the screen and clicking logout
4. You are presented a list of user accounts
5. Try to select one of the user accounts without using a mouse or touch.
6. You are stuck.

**Expected behavior**
Expected behaviour is for one of the screen elements to receive focus upon creation. First user account seems the most appropriate candidate. From there, the user should be able to cycle through the GUI elements with the tab key and/or arrow keys, or a TV remote in case of TV systems.

**Screenshots**
![image](https://user-images.githubusercontent.com/31270359/71689638-e0577000-2da2-11ea-94f1-ae898adabf17.png)

**System:**
 - OS: Ubuntu server 18.04
 - Browser: Windows 10 Chrome 79.0.3945.88; LG WebOS TV
 - Jellyfin Version: 10.4.3

**Comment by WilcoVertegaal** [comment]
I think it can be fixed by adding the following line to the end of the "loadUserList" function in controllers/loginpage.js:

`        context.querySelector("#divUsers").querySelector("button").focus();
`

There is no focus indicator on the user account button (I guess this should be solved in CSS?) but the GUI responds to keyboard/remote controller input.

**Comment by dmitrylyzo** [comment]
This should be fixed in #563, but I suppose it is not released.

> There is no focus indicator on the user account button (I guess this should be solved in CSS?) but the GUI responds to keyboard/remote controller input.

#535

**Comment by WilcoVertegaal** [comment]
This seems indeed fixed when I run the nightly build in WebOS emulator on Windows 10, but when I run it on a physical LG WebOS TV, the login screen is just black and stays that way.

What to do now? Close this bug and file a new one (if it doesn't already exist)?

**Comment by JustAMan** [comment]
Are you referring to "black screen" issue https://github.com/jellyfin/jellyfin-web/issues/646 ?

**Comment by WilcoVertegaal** [comment]
That's it I think. Problem is, as long as #646 is not closed I can't really verify if #563 solves #662. Leave it open then?

**Comment by ferferga** [comment]
Heads-up! How is this going with 10.5?

**Comment by WilcoVertegaal** [comment]
Excellent! I just tested it with 10.5 and the issue is completely gone.
