### ISSUE TITLE
Subtitles offset not working in firefox

### ISSUE THREAD

**Issue by gabri94** [jellyfin/jellyfin-web#669]
**Describe the bug**
Adjusting the timing of the subtitles using Firefox 68.0.2 (64-bit) does not produce any result. On the other hand trying to adjust the time of the same srt file, on the same movie using the same server with chrome browers works as expected.

**To Reproduce**

1. Pick a movie
2. Select an additional subtitle
3. Click on the option button
4. Select subtitles offset
5. Move the slider

**Expected behavior**
I expect the subtitles to change time wrt the movie

**System:**
 - OS: Debian sid
 - Jellyfin Version: 10.4.3

**Comment by dkanada** [comment]
should be working in the next release
