### ISSUE TITLE
Redundant Disconnect Dialog

### ISSUE THREAD

**Issue by iganeshk** [jellyfin/jellyfin-web#671]
**Redundant Disconnect Dialog**
The web-server implementation of disconnecting from the chromecast/player prompts two dialog windows.

![First Dialog](https://i.imgur.com/ME0UrD6.png)

![Second Dialog](https://i.imgur.com/8A9hxAw.png)

**Additional context**
`ConfirmEndPlayerSession`

**Comment by JustAMan** [comment]
These seem to be two different issues related to same component, please don't make single issue for several pieces. I would suggest you make a new issue for your point 2.

**Comment by iganeshk** [comment]
> These seem to be two different issues related to same component, please don't make single issue for several pieces. I would suggest you make a new issue for your point 2.

Sure, filed it as a different issue.

**Comment by JustAMan** [comment]
Now back to your original issue, what is wrong with having a confirmation here?

**Comment by iganeshk** [comment]
Nothing really wrong but it seems to require additional step to disconnect when comparing it to the standard implementation of cast UX.

**Comment by dkanada** [comment]
It's not technically required, but most casting apps will either default to closing the stream if you disconnect or leaving it open. Currently we let the user choose, which I don't think is a bad idea in theory, but it does require an extra step.

**Comment by JustAMan** [comment]
We can probably have a checkbox in the first dialog, and remember user choice (whether it's ticked or not) in cookies.

**Comment by iganeshk** [comment]
Since this would be a user preference, how about having it as an option/checkbox under media playback or Remote control in user settings?

**Comment by dkanada** [comment]
I'd be fine moving it to the playback settings with a default of keeping the stream running.

**Comment by DMouse10462** [comment]
I think current behavior is best practice with some conditions; I certainly wouldn't consider leaving an application open on Chromecast uncontrollable as an ideal default and propose a flow similar to one when saving a document in an office suite:

![UI Flowchart](https://user-images.githubusercontent.com/2002606/72413186-30d4b300-373d-11ea-847a-76d3d03acf64.png)

As an alternative similar to YouTube (with only one controlling device), pressing Disconnect stops all media and shuts down the Chromecast app without any prompts whatsoever. Of course, YouTube has multi-seat queue capabilities which, if memory serves, keeps the app alive until all controlling devices have disconnected or a timeout with no playing media is reached.

**Comment by dkanada** [comment]
I might be inclined to just put a button next to disconnect that says shut down.

**Comment by hamburglar2160** [comment]
i recommend:

Completely doing away with the "shutdown confirmation."
Rename "disconnect" to "stop casting" to be more in line with guidelines and move that button to the "remote control" interface. Then do away with what remains.

**Comment by dkanada** [comment]
I'd rather not make changes to the remote control component, because that has to be as generic as possible to stay convenient.
