### ISSUE TITLE
WebOS 4: Most icons are missing

### ISSUE THREAD

**Issue by MrTimscampi** [jellyfin/jellyfin-web#678]
**Describe the bug**

On WebOS 4, most icons are blank, leading to navigation issues

**To Reproduce**

1. Start WebOS App
2. Connect to server

**Expected behavior**

Icons should be shown

**Logs**

N/a

**Screenshots**

![screenshot_20200109_212558](https://user-images.githubusercontent.com/19396809/72102239-c24fb980-3326-11ea-80bf-fe3b609f37f5.png)

![screenshot_20200109_212630](https://user-images.githubusercontent.com/19396809/72102244-c67bd700-3326-11ea-8ab4-6dc441bd158f.png)

![screenshot_20200109_212652](https://user-images.githubusercontent.com/19396809/72102247-c8de3100-3326-11ea-8277-73e417f6b5d1.png)

**System (please complete the following information):**
 - OS: WebOS
 - Browser: Chrome 53
 - Jellyfin Version: Master

**Additional context**

None

**Comment by thornbill** [comment]
I suspect this was caused by this change https://github.com/jellyfin/jellyfin-web/pull/582

**Comment by MrTimscampi** [comment]
I'll revert it and test, thanks :)

**Comment by samcon** [comment]
Can confirm that this doesn't work in WebOS 4 and the reason is the #582. I changed an icon back to the unicode format and it displayed correctly.

**Comment by dmitrylyzo** [comment]
220bbb50a8f70179d905931c98be4abe759f6dc6
Looked at Network tab - almost all fonts are "pending". Only one has been downloaded.
![webos4-1](https://user-images.githubusercontent.com/56478732/74341722-3c0d1400-4db9-11ea-8ea8-9121757fe5a4.png)
This seems to be why the icons are not displayed.
No proxy.

Also, tested the same on 51cece9c2574c40c7e81bd4e447895784f82129a
![webos4-2](https://user-images.githubusercontent.com/56478732/74342429-8773f200-4dba-11ea-966b-293bbffc67be.png)
