### ISSUE TITLE
Actor pages are broken

### ISSUE THREAD

**Issue by Bond-009** [jellyfin/jellyfin-web#685]
**Describe the bug**
Actor pages are broken

**To Reproduce**

1. Go to an actor page

**Expected behavior**
The page doesn't start in the middle of the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/21289123/72203594-e5d14c00-346d-11ea-8e09-7c2d1e0d0f6d.png)

**System (please complete the following information):**
 - OS: Debian
 - Browser: Firefox
 - Jellyfin Version: 10.5.0

**Comment by Bond-009** [comment]
Reopening because music artist pages still have this issue

**Comment by ferferga** [comment]
Fixed already for 10.5 release

![image](https://user-images.githubusercontent.com/10274099/75934200-2a7cd080-5e7c-11ea-96b2-23d7a75e37cb.png)

Artists/Actors with backgrounds looks good as well:

![image](https://user-images.githubusercontent.com/10274099/75934296-59934200-5e7c-11ea-92c9-4db250c4ba89.png)
