### ISSUE TITLE
Mkv improperly labeled webm during Playback Stats in Firefox

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-web#687]
**Describe the bug**

Webm is a restricted subset of mkv. Playback doesn't properly report the container type.

**To Reproduce**

Play any mkv file

**Expected behavior**

container should be labeled mastroka or mkv

**Comment by Artiume** [comment]
So firefox improperly sees the files as webm. I also can't prevent Jellyfin from remuxing the container. Firefox won't direct play H26410Bit, nor FLAC even when forced. It's transcoding Flac to aac. come on firefox, you were the chosen one!
Firefox:
![image](https://user-images.githubusercontent.com/20715731/72228762-8e1f0780-3577-11ea-9a43-73fc6fc467bf.png)


Interesting point and kind of exciting, Chrome sees and respects mkv files. I was able to play a mkv file with H264 10Bit, aac/flac, and ass subtitles natively. No issues or transcoding. 
Chrome:
![image](https://user-images.githubusercontent.com/20715731/72228721-308abb00-3577-11ea-82d7-77cc4e0338e8.png)

If I force a lower bitrate in Chrome to force it to transcode, it converts the flac to MP3... That hurts on trying to figure out that logic.
![image](https://user-images.githubusercontent.com/20715731/72228915-c115cb00-3578-11ea-87fe-2fbae139d28b.png)

**Comment by dkanada** [comment]
I'm pretty sure any video transcode will also convert the audio to MP3 for compatibility reasons, but I'm not entirely sure.

**Comment by Artiume** [comment]
na, it will check the audio independently, but the playback profiles are jacked up and probably stream builder as well.

**Comment by JustAMan** [comment]
> If I force a lower bitrate in Chrome to force it to transcode, it converts the flac to MP3

The thing is, anything but direct play is delivered to a browser via HLS, which is a (kind of) series of mp4 files that can carry h264 and mp3/aac (certainly not FLAC). On why it chooses to transcode to mp3 instead of aac is another issue.

**Comment by Artiume** [comment]
Right, that makes sense, i forgot about the streaming container. so HLS supports ts and fmp4, neither of which support flac. So I can play Flac 2ch music in Firefox. Which makes me suspect it's the mkv container that was causing the entire issue for no flac support.

**Comment by Artiume** [comment]
Shoo bot

**Comment by MrTimscampi** [comment]
Should be fixed on 10.6.
