### ISSUE TITLE
Web UI won't load in Firefox on Mac

### ISSUE THREAD

**Issue by translit** [jellyfin/jellyfin-web#690]
**Describe the bug**
Web UI won't load in Firefox on Mac

**To Reproduce**
1. Go to WebUI URL
2. See black screen

**Expected behavior**
WebUI loads

**System (please complete the following information):**
 - OS: macOS Mojave 10.14.6 (18G1012)
 - Browser: Firefox 71.0
 - Jellyfin Version: 10.4.3 (official Docker container, Linux X64)
 - Installed Plugins: none
 - Reverse proxy: no

**Comment by MrTimscampi** [comment]
Hi @translit , would you happen to have any logs ?

To get logs for the web client, press F12 in an empty Firefox tab, go to the Console tab and click "Persist logs" on the right. Then enter the URL of your web client, load the page and copy-paste the lines that appear in the Console to a text file.

We're especially interested in the lines highlighted in red, if there are any. This should help us track down your issue.

**Comment by translit** [comment]
Thank you, Timscampi, for guidance. The issue has been resolved after updating Firefox to 73.0b7.

**Comment by JustAMan** [comment]
Should we close it then?

**Comment by translit** [comment]
Yes, let's close for now.
