### ISSUE TITLE
[Bug] Chromecast music will not play the good song from android apps

### ISSUE THREAD

**Issue by samuel9554** [jellyfin/jellyfin-web#692]
**Describe the bug :**
When connected to a Chromecast connected trough the android apps pressing the song title will often lead to the wrong song to played. 

**Work Around :**
Pressing on the 3 dot on the right of the title and selecting play will play the good song.

**To Reproduce :**
Connect to a Chromecast with the android apps and select a song by clicking on the song title. 

**Expected behavior :**
The selected song should start playing on the Chromecast.

System (please complete the following information):

    OS: [ Docker, Unraid]
    Browser: Android Apps
    Jellyfin Version: 10.4.3
    Reverse proxy: Nginx

**Comment by dlahoti** [comment]
I think it may be at least fixable independent of the other issue. The file `playbackmanager.js` has a function `translateItemsForPlayback` that it uses to sort lists returned by the server into the correct order, but this only applies to local playback. It seems like replicating this in `chromecastplayer.js` would fix the problem.

**Comment by JustAMan** [comment]
paging @cvium
