### ISSUE TITLE
Playback Hidden in Firefox

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-web#695]
**Describe the bug**

When you click the Settings icon, the Playback option is hidden and have to use arrow keys to access it. I am only noticing this in Firefox. 

**Screenshots**

![image](https://user-images.githubusercontent.com/20715731/72358656-e7dc1a80-36ba-11ea-8c27-f83035ee6728.png)
Arrow keys for the win.
![image](https://user-images.githubusercontent.com/20715731/72358688-f62a3680-36ba-11ea-8c94-4f2f61c88094.png)

System:

This is happening on my Windows box that I remote into so that might have something to do with it since I can't reproduce it on Linux+Firefox.

**Comment by Bond-009** [comment]
Works for me on the latest master

**Comment by Shadowghost** [comment]
No problems here on Firefox and latest debian nightly.

**Comment by Artiume** [comment]
my nightly is a few days old but I'll pull more snaps. If i click on a large menu option such as a music song that's near the bottom of the screen, the menu won't respect the bottom of the browser where there's plenty of room overall

**Comment by Shadowghost** [comment]
I remember having that one on an earlier nightly. Just checked on my Linux system with wayland and apparently it seemed to have both of the bugs. Cleared the website data since I had some weird wrong textfields and tried again - and both of the issues were gone.

**Comment by Artiume** [comment]
Ok, i'll purge and see what i get

**Comment by dkanada** [comment]
Definitely purge especially if you're using the nightly. Without webpack the resources will only get refreshed after a version bump, which can cause style issues.

**Comment by Artiume** [comment]
clearing cache appears to have fixed this. resolving ticket
