### ISSUE TITLE
[Bug] [Regression] Android client suggestion tile swipe broken

### ISSUE THREAD

**Issue by samuel9554** [jellyfin/jellyfin-web#696]
**Describe the bug**
In the suggestion tab of the android client swipe from left to right will only work on the first row. The next row while cause a tab change.
Here's a video for easy understanding.
[https://www.youtube.com/watch?v=9Jd1pupS47U](https://www.youtube.com/watch?v=9Jd1pupS47U)

**To Reproduce**
1. Open the android client
2. Click on your movie library
3. Go to tab suggestion
4. Try to swipe left or right some of the row

**Expected behavior**
The row should scroll to show the content

**System (please complete the following information):**
 - OS: [e.g. Docker]
 - Browser: [Android Client]
 - Jellyfin Version: [10.4.3]
 - Reverse proxy: [nginx]

**Comment by JustAMan** [comment]
Definitely a web issue so moved, not sure if it's a regression on our part or a change in browsers tho.

**Comment by MrTimscampi** [comment]
Closing, as the fix is merged into master.
