### ISSUE TITLE
Update BrowserDeviceProfile.js

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-web#703]
**Describe the bug**
The copy of BrowserDeviceProfile.js we have is largely untouched, with only minor changes since the fork. As a result, there are many supported codecs/formats that are marked as unsupported for certain browsers.

**To fix**
Review each platform/browser that BrowserDeviceProfile can identify, and ensure that the correct capabilities are reported back.

**Additional context**
Resources to use:
* https://caniuse.com/
* https://jellyfin.org/docs/general/clients/codec-support.html

**Comment by the-r0cket06** [comment]
I can help anyone that is planning on tackling this. I started to poke around a little bit today, and might have some stuff ready for a PR in the coming days.

**Comment by JustAMan** [comment]
@the-r0cket06 Go ahead, and make a draft PR when you have at least something, so others know your approximate progress (and the fact that you're working on it).

**Comment by timo95** [comment]
Related:
https://github.com/jellyfin/jellyfin-expo/issues/106

**Comment by thornbill** [comment]
This file received regular updates now 🙃
