### ISSUE TITLE
Visually distinguish between fully watched series and series with unwatched episodes.

### ISSUE THREAD

**Issue by Redsandro** [jellyfin/jellyfin-web#706]
Right now, fully watched series have a blue check mark and series with new episodes have a blue number:

![image](https://user-images.githubusercontent.com/1702193/72668261-586d9900-3a25-11ea-9ea2-f8cbd99a8d86.png)

I keep getting that small moment of excitement thinking there is a new episode, and upon closer inspection it's just the same blue circle with a check mark. I've ignored this for a while but I can't get used to it. I guess there are two groups of people: Those sensitive to textual communication (number versus check mark) and those sensitive to visual communication for lack of a better word (like red versus green in traffic lights).

Can we make the circle with a checkbox have a different color, like green?

![image](https://user-images.githubusercontent.com/1702193/72668370-2b6db600-3a26-11ea-906d-d50911966950.png)

**Comment by Artiume** [comment]
My concern for making green the default is for those who are color blind (deuteranomalous). I think a better idea is to introduce community css for allowing customization and provide the css templates on the JF website. 

That being said, this exact request is being made here
https://github.com/jellyfin/jellyfin-web/pull/707

**Comment by DMouse10462** [comment]
Judging from a lot of the comments in #707, it seems we have a few goals to accomplish:
- More clearly distinguish between fully watched and in-progress series (aka this issue)
- [Maintain distinction between fully watched and completely unwatched series](https://github.com/jellyfin/jellyfin-web/pull/707#issuecomment-577026654)
- Keep a consistent shape in the upper-right corner? [1](https://github.com/jellyfin/jellyfin-web/pull/707#issuecomment-577451804)
- Accessibility concerns: Aim for [high visual contrast over subtlety and recognizability](https://github.com/jellyfin/jellyfin-web/pull/707#issuecomment-578055918)

Ideas presented in #707 that countered the commit included changing the indicator shape, creating either a square or a rotated "flag", both of which were regarded as either too subtle and/or degraded the legibility of the content of the indicator.

---

I suggested using a progressbar along the bottom of the video similar to those already found when browsing a video or individual episodes and moving the numeric indicator to the lower-left as a sort of "tag" indicator that pops out of the progressbar. This not only creates a large visual distinction but provides a quicker means of giving value to the indicated number by visualizing it as a part of a whole. Attached is a new image demonstrating my idea in the Jellyfin interface:

![Screenshot from 2020-01-26 03-02-47](https://user-images.githubusercontent.com/2002606/73132599-44a8d080-3feb-11ea-8160-0691c126af6d.png)

**Comment by nvllsvm** [comment]
The custom CSS feature _should_ work for those wanting this now. However, it seems to be partially broken. https://github.com/jellyfin/jellyfin-web/issues/742

**Comment by grantwest** [comment]
I think @DMouse10462 pretty much nailed it, but I don't see the value in keeping a consistent shape in the upper right corner. Consistency is directly opposed to the other goals of being distinguishable. Consistency for consistencies sake, especially in this scenario where it provides little to no aesthetic benefit, might be a mistake. Just my 2 cents.

**Comment by DMouse10462** [comment]
This is still relevant, and I still show interest in this. I may take some time to look at a solution, but for the time being can this issue maybe be re-tagged as "enhancement" (to scare away the stale bot) and "ui & ux"? Since this is more of a UI design change, I would argue that this is more of a usability enhancement than a "bug."

**Comment by MrTimscampi** [comment]
Please redirect feature requests and suggestions to https://features.jellyfin.org/
