### ISSUE TITLE
banner-light.png not found while using Dark theme

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [jellyfin/jellyfin-web#729]
**Describe the bug**
Logo doesn't appear in navbar while using the Dark theme

**To Reproduce**

1. Open the web app

**Expected behavior**
The logo should be there

**Logs**
```
[19:30:02] [ERR] [13] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: Could not find a part of the path '/usr/lib/jellyfin/bin/jellyfin-web/themes/dark/assets/img/banner-light.png'.
```

**System (please complete the following information):**
 - OS: Custom Docker container that uses Nightly binaries (based off LSIO's)
 - Browser: Firefox
 - Jellyfin Version: 10.5.0

**Comment by nyanmisaka** [comment]
https://github.com/jellyfin/jellyfin-web/pull/725

**Comment by JustAMan** [comment]
ping @dkanada

**Comment by dkanada** [comment]
I needed to add some things there first and address the code reviews. Shouldn't be too long.

**Comment by MrTimscampi** [comment]
Closing as the fix is now merged.
