### ISSUE TITLE
Custom CSS (branding) Not Taking Priority

### ISSUE THREAD

**Issue by nvllsvm** [jellyfin/jellyfin-web#742]
**Describe the bug**
Custom CSS is not taking priority when rendering a page. It briefly flashes, but is then replaced by the original theme's styling.

**To Reproduce**

![image](https://user-images.githubusercontent.com/6550543/73145445-a0229f00-407b-11ea-9777-431112ef09ab.png)
1. Set custom branding 
2. Navigate to home page
3. Notice flicker

**Expected behavior**
Custom CSS takes priority.

**Workaround**
Add `!important` to the property.

**Logs**
![image](https://user-images.githubusercontent.com/6550543/73145548-2939d600-407c-11ea-9de9-15cc1fe57a63.png)

**System (please complete the following information):**
 - OS: Docker
 - Browser: Firefox 72
 - Jellyfin Version: 10.4.3

**Comment by dkanada** [comment]
I assume the CSS is just getting loaded normally. Unless you think we should append `!important` to every rule in the custom CSS then I wouldn't consider this a bug in most cases.

**Comment by thornbill** [comment]
I would agree that this is a bug. The custom css should be applied last so it will properly override the theme without needing to increase the specificity of the custom rules.

**Comment by YouKnowBlom** [comment]
I believe this can be closed now that #763 has been merged
