### ISSUE TITLE
Firefox ESR Support Regression

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-web#748]
**Describe the bug**
Firefox ESR (Version 68) currently is broken on nightly. It fails to build out the page due to lack of polyfill support. 

![image](https://user-images.githubusercontent.com/20715731/73385490-40a2da00-429b-11ea-8d54-e3f666f40199.png)

**Comment by Bond-009** [comment]
Duplicate of #693?

**Comment by Artiume** [comment]
Probably. It is the same FF version. I didn't notice any artifacts until the main menu, the wizard seemed fine.

**Comment by Artiume** [comment]
fixed in nightly. resolving
