### ISSUE TITLE
Why only 946 movies in the library, while I actually have 5000?

### ISSUE THREAD

**Issue by dg9999cn** [jellyfin/jellyfin-web#749]
Why only 946 movies in the library, while I actually have 5000? There is limit?

**Comment by MrTimscampi** [comment]
Hi, please respect the issue template [here](https://github.com/jellyfin/jellyfin-web/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), as it contains information that helps us help you.

Thank you.
