### ISSUE TITLE
Some media not seeking properly

### ISSUE THREAD

**Issue by viggy96** [jellyfin/jellyfin-web#752]
On some video files, when the user selects a position on the seekbar, the video playback freezes on the frame at the position selected by the user, but the audio continues playing from the selected point as expected. The seekbar and play clock are also reset to the beginning regardless of the position selected by the user. I have tried to capture the log for this via logcat. 
https://pastebin.com/eX6EkYJP

**Comment by dkanada** [comment]
cc @redSpoutnik @Unhelpful

**Comment by viggy96** [comment]
I should also note that this only occurs for media when being casted. When being played directly on the device, its fine.

**Comment by redSpoutnik** [comment]
What is the version of the server where the problem occurs?

**Comment by viggy96** [comment]
@redSpoutnik 10.4.3

**Comment by JustAMan** [comment]
When casted, do you mean Chromecast?

**Comment by viggy96** [comment]
@JustAMan Yes.

**Comment by JustAMan** [comment]
cc @YouKnowBlom
