### ISSUE TITLE
WebOS 4 has a horizontal scroll on itemdetails page

### ISSUE THREAD

**Issue by dmitrylyzo** [jellyfin/jellyfin-web#753]
**Describe the bug**
In WebOS 3/4 (emulators), I have horizontal scroll: `mainDetailButtons` is larger than its content

**To Reproduce**
1. Open Jellyfin in WebOS app.
2. Open some music album or movie.
3. Navigate to "More" button.
4. Page scrolls horizontally.

**Expected behavior**
Page should not scroll horizontally.

**Screenshots**
![jellyfin-overscroll1](https://user-images.githubusercontent.com/56478732/73592110-c460fe80-4507-11ea-91fd-408bb5e5b2e9.png)
_`mainDetailButtons` with scrollbars_
![jellyfin-overscroll2](https://user-images.githubusercontent.com/56478732/73592111-c88d1c00-4507-11ea-826d-e916e1eaeb7f.png)

**System (please complete the following information):**
 - OS: WebOS 4
 - Browser: Chrome 53
 - Jellyfin Version: 51cece9c2574c40c7e81bd4e447895784f82129a

**Additional context**
I changed this single button to Unicode identifier - this fixes the "overscroll" and changes the icon to the same as in Chrome on PC.
![jellyfin-overscroll3](https://user-images.githubusercontent.com/56478732/73592189-a1831a00-4508-11ea-9f71-4f990a4748b5.png)

Also, tried to revert d310cbf008b71e6fc35aa21978b3c44075b23090 - wrong icon, but no "overscoll".

I think this related to #678. Probably WebOS has a problem loading `Material Icons`.
In addition, in Tizen 3/4/5, everything is fine. Chrome 47/56/63.

Edit:
WebOS 3 is fine too (even icons are good). Chrome 38

**Comment by JustAMan** [comment]
@dmitrylyzo can you confirm it works using latest master?

**Comment by dmitrylyzo** [comment]
Yes, it is fixed.
