### ISSUE TITLE
Can import a font using custom CSS but cannot import a custom CSS

### ISSUE THREAD

**Issue by classicjazz** [jellyfin/jellyfin-web#756]
**Describe the bug**
I can define custom CSS in JellyFin including importing a custom font. For example, this works perfectly:

```
@import url('https://fonts.googleapis.com/css?family=Karla:400,600,700');
body {
    font-family: 'Karla', sans-serif;
}
h1, h2, h3 {
   font-family: 'Karla', sans-serif; text-transform: uppercase;
   color: rgba(255, 255, 255, 0.87) !important;
}
h2, h3 {
   letter-spacing: .3px;
}

```

But I cannot import this as custom CSS. Use this line in the custom CSS field instead:

`@import url('https://raw.githubusercontent.com/classicjazz/photon-theme/master/theme.css')`

**To Reproduce**
See above. Anything pasted into the custom CSS field works. But anything imported (other than the font itself) does not work.

**Expected behavior**
Users should be able to import complete stylesheets (with or without custom fonts) and they should take precedence over built-in styles.

**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: Docker
 - Browser: Firefox, Chrome, Safari
 - Jellyfin Version: 10.4.3

**Additional context**

**Comment by ferferga** [comment]
Duplicate of #742

**Comment by thornbill** [comment]
I think this might be caused by something strange in the way github hosts these files. I would try publishing it using github pages and try importing that url instead. I noticed the content-type is plain text instead of css. I'm not sure if that alone would prevent it from loading or not.

**Comment by ferferga** [comment]
Just opened the link to check the css file, and the problem that @thornbill states is caused by the first two commented lines, which makes the interpreter think that the files aren't stylesheets. Had some problems as well with that exact issue while creating the jellyfin-noto package, and I solved them by removing all the commented lines that are at the top of the file.

**Comment by classicjazz** [comment]
Removing the commented lines alone didn't seem to solve the problem. Checking @thornbill recommendation next...

**Comment by classicjazz** [comment]
Moving the same CSS file to my private web server seems to work.

**Comment by dkanada** [comment]
Can we consider this a browser quirk then rather than a Jellyfin issue?

**Comment by classicjazz** [comment]
Yes. Closing this bug.
