### ISSUE TITLE
Shuffle only shows on few TV series

### ISSUE THREAD

**Issue by ZMOT7S** [jellyfin/jellyfin-web#761]
The shuffle option only shows on a few of my TV series. Using Jellyfin android app version 0.9.7 on a Pixel XL phone using android 9.

The only show that has the shuffle option for me is Rick and Morty. All of my other shows including South Park, Futurama, King of the Hill, Superstore, etc do NOT have the shuffle option. 

https://i.imgur.com/HtwkMCc.jpg

https://i.imgur.com/fPtaf1j.jpg

**Comment by YouKnowBlom** [comment]
@ZMOT7S 
what jellyfin version are you running on the server?

Do the layout on all shows where the shuffle is hidden look equally as broken as the South Park one?

**Comment by ZMOT7S** [comment]
Jellyfin 10.4.3

Yes, the layout is messed up on all shows that DON'T have shuffle and is fine on the few shows that DO have shuffle.
