### ISSUE TITLE
Ratings have too many decimal places

### ISSUE THREAD

**Issue by MrTimscampi** [jellyfin/jellyfin-web#768]
**Expected behavior**

As reported on Matrix, ratings currently can have 3 (more?) decimal places.  
Ratings should be limited to 1 decimal place.

**Logs**

**Screenshots**

![Screenshot_20200205-201044](https://user-images.githubusercontent.com/19396809/73829255-f5d91300-4802-11ea-8dec-39aab9eb2a6d.jpg)

**System (please complete the following information):**
 - OS: All
 - Browser: All
 - Jellyfin Version: 10.5.0

**Additional context**

**Comment by CalebHopper** [comment]
jellyfin-web/src/components/mediainfo/mediainfo.js 
Line 293, possibly wrap the passed in variable with some sort of rounding pre-applied? Possibly Math.round(item.OfficialRating). Preferably something that gives better control of the result, of course. Selectively not adding x.0 to numbers close enough to x.
