### ISSUE TITLE
Gestures for default step on sliders / avoid sliders for values. 

### ISSUE THREAD

**Issue by k6Q28k5w5eWuRuuzTg9j7GrKCbjt7** [jellyfin/jellyfin-web#776]
Hi. I'm having difficulties using the "sliders" to hit correct values on options such as: offset and seeking, especially on smaller devices (touch). 

There might be a better experience to allow input fields / plus-minus buttons, or similar. Another option is gestures to increase/decrease the slider by some default step.

**Comment by YouKnowBlom** [comment]
Subtitle offset has an input field, click on the "0s" above the slider and it'll let you type it in. With that said, I do think it could be made more obvious

**Comment by MrTimscampi** [comment]
Closing this, as we follow the pattern of most other media apps and there are no plans to change it.
