### ISSUE TITLE
Favorite button is on different row

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [jellyfin/jellyfin-web#777]
Image: https://e-six-two.one/i/ekeyli2e.png
Different occurrence: https://e-six-two.one/i/h88a6kpi.png

Nightly from 02/08/20

**Comment by MrTimscampi** [comment]
Hi, could you provide us with you OS and browser (Along with versions for these). It helps us track down weird behavior by different browsers on different platform, which is why they are in the issue template.

Thanks.

**Comment by ThatNerdyPikachu** [comment]
Windows 10, Firefox 72.0.2

Sorry for not using the template.

**Comment by MrTimscampi** [comment]
No worries, I found the source of the issue and it's fixed in the PR monetioned above.

Thanks for the report :)
