### ISSUE TITLE
Next Up Section: Removal of Partially Played Content

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-web#789]
So if you watch a lot of partial content, it gets duplicated in both sections of Continue Watching and Next Up. Should we perhaps only show partial content in the Continue Watching section?

![image](https://user-images.githubusercontent.com/20715731/74108782-a6208180-4b4b-11ea-8d77-5b64fdfb74b1.png)

**Comment by YouKnowBlom** [comment]
I think that's a good idea, it makes much more sense to separate them imo.

**Comment by nielsvanvelzen** [comment]
This is probably a server change. Looking at the code it should be changed [here](https://github.com/jellyfin/jellyfin/blob/f8ad6655fbf2909bd3368ceac4b7947bea41b009/Emby.Server.Implementations/TV/TVSeriesManager.cs#L31)

**Comment by Artiume** [comment]
Hm, I'm not too familiar with the frontend vars so I couldn't really tell what I was looking for. I did find this though,
https://github.com/jellyfin/jellyfin/blob/f8ad6655fbf2909bd3368ceac4b7947bea41b009/Emby.Server.Implementations/TV/TVSeriesManager.cs#L113
Think we should expose this and make it customizable? ;)

What's this? 
https://github.com/jellyfin/jellyfin/blob/f8ad6655fbf2909bd3368ceac4b7947bea41b009/Emby.Server.Implementations/TV/TVSeriesManager.cs#L189

**Comment by thornbill** [comment]
Fixed by https://github.com/jellyfin/jellyfin/pull/4628
