### ISSUE TITLE
Suggestion: Add skip forward / back buttons

### ISSUE THREAD

**Issue by tilllt** [jellyfin/jellyfin-web#791]
On long movies it's very hard to accurately position the playback marker (i.e. when skipping titles) for the small space a phone display has. It would be easier if there were skip buttons (like 30s forward / backward) additionally, like other players have.

**Comment by JustAMan** [comment]
All this is handled by bundled web copy of UI, so I moved the issue.

**Comment by YouKnowBlom** [comment]
On Android/mobile you can double click each side to move 10s forward or back. It seems transcoded content does not like this very much though, might just be my server.

**Comment by dkanada** [comment]
I think there's about a thirty second delay before a transcode job gets killed on the server, which would mean skipping around spawns a ton of new jobs that kill the efficiency.

**Comment by YouKnowBlom** [comment]
Oh alright, that makes sense

**Comment by tilllt** [comment]
Forgot to mention that i am not watching the movie on the Phone, but casting to my chromecast. So the double-tap to skip option does not exist afaik.

**Comment by MrTimscampi** [comment]
Please redirect feature requests and suggestions to https://features.jellyfin.org/
