### ISSUE TITLE
Next Episode Button showing Disabled in "TV Shows"

### ISSUE THREAD

**Issue by Mantu120** [jellyfin/jellyfin-web#792]
Next episode button in player is showing disabled.
I think, its very important for "TV Shows"

![Screenshot_20200209-182022](https://user-images.githubusercontent.com/59708776/74101954-20abca00-4b69-11ea-92ee-33ace2169840.jpg)

**Comment by JustAMan** [comment]
This is most likely web issue, as Android uses a bundled version, so I moved the issue.

**Comment by telans** [comment]
Does this happen with just this episode or show? I've never had it disappear unless there just wasn't an episode it could go to.
