### ISSUE TITLE
Default Preferred Metadata Language

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-web#794]
During the startup wizard, you are forced to explicitly select the language and country you want, you can't just hit Next. It would be convenient if we could have Defaults set or if left blank, it would default to assumed values (eng/usa?). Since this isn't an english/usa bound program, I'm open to discussion. 

![image](https://user-images.githubusercontent.com/20715731/74341384-9dab8f00-4d75-11ea-9ff4-c883be1d4604.png)

**Comment by dmitrylyzo** [comment]
Can language be retrieved from server locale?
Something like this:
```sh
: locale
LANG=ru_RU.UTF-8
LANGUAGE=ru:en_US:en_GB
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC=ru_RU.UTF-8
LC_TIME=ru_RU.UTF-8
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY=ru_RU.UTF-8
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER=ru_RU.UTF-8
LC_NAME=ru_RU.UTF-8
LC_ADDRESS=ru_RU.UTF-8
LC_TELEPHONE=ru_RU.UTF-8
LC_MEASUREMENT=ru_RU.UTF-8
LC_IDENTIFICATION=ru_RU.UTF-8
LC_ALL=
```

**Comment by Artiume** [comment]
I like the idea

**Comment by ThibaultNocchi** [comment]
Shouldn't we use the preferred display language, chosen at the first step of the wizard?

**Comment by MrTimscampi** [comment]
> Shouldn't we use the preferred display language, chosen at the first step of the wizard?

Agreed, the locale on the server might be different than what the user wants to use. Using the current displayed language would be the best option.
