### ISSUE TITLE
navigator.mediaSession.metadata has "artist" and "title" fields swapped

### ISSUE THREAD

**Issue by rigrig** [jellyfin/jellyfin-web#796]
**Describe the bug**

The "artist" and "title" fields in [`navigator.mediaSession.metadata`](https://developer.mozilla.org/en-US/docs/Web/API/MediaSession/metadata) are swapped.
This causes plugins (like [Plasma Integration](https://addons.mozilla.org/en-US/firefox/addon/plasma-integration/)) to display the wrong information about current playing songs.

**To Reproduce**

1. Play a song in Jellyfin (in this case: "The Last Supper" by "Grave digger")
2. Look at the Jellyfin web UI, confirm that the title+artist are displayed correctly
3. Open the developer console
4. Type `navigator.mediaSession.metadata`
5. See that the artist/title fields are swapped:
`Object { title: "Grave Digger", artist: "The Last Supper", ...`

**Expected behavior**

Correct metadata:
`Object { title: "The Last Supper", artist: "Grave Digger", ...`

**Screenshots**

Browser UI, showing the correct title+artist:
![browser_ui_ok](https://user-images.githubusercontent.com/2941436/74439761-193c3780-4e6d-11ea-8bf1-faf0db0ccb29.png)
Developer console, swapped artist/title fields:
![devtools_wrong](https://user-images.githubusercontent.com/2941436/74439771-1d685500-4e6d-11ea-91f0-633b7903bf24.png)
Plasma Integration plugin, displaying the swapped metadata:
![tray_wrong](https://user-images.githubusercontent.com/2941436/74439782-20fbdc00-4e6d-11ea-8b1c-0421d2fcef55.png)

**System (please complete the following information):**
 - OS: Linux (Docker on Synology NAS)
 - Browser: Firefox 68.0.1
 - Jellyfin Version: e.g. 10.4.3

(I'm not 100% sure that plugin uses `navigator.mediaSession.metadata` instead of some other way to get the metadata, but the fields are definitely swapped here at least)

**Comment by dkanada** [comment]
@Artiume this has been fixed right?

**Comment by Artiume** [comment]
Yes. Is android ready for another release point?

**Comment by dkanada** [comment]
It's still waiting on the image improvements.

**Comment by Artiume** [comment]
![image](https://user-images.githubusercontent.com/20715731/74442691-f0517d80-4e3f-11ea-827a-9fc5a393a334.png)

**Comment by rigrig** [comment]
Thanks! Works fine in 10.5.0 now.
