### ISSUE TITLE
ASS Subtitles not correctly showing

### ISSUE THREAD

**Issue by Amasuke** [jellyfin/jellyfin-web#799]
I have a video file that shows subtitles in firefox and the android app.
In chrome they don't show at all. They only show when I disable "Allow subtitle extraction on the fly".
And then they show all subtitles, even the stylized ones. 

![mkvtoolnix-gui_2020-02-13_22-42-32](https://user-images.githubusercontent.com/10835994/74482116-37795600-4eb4-11ea-8084-8d38e73f53c4.png)
These are the fonts that are embedded in the video file. I guess some of them can't be extracted on the fly and cause issues?

![firefox_2020-02-13_21-25-47](https://user-images.githubusercontent.com/10835994/74482193-5b3c9c00-4eb4-11ea-972f-f3592e82f602.png)
This is the information of the video that does not display any subtitles in chrome when "Allow subtitle extraction on the fly" is enabled.

To reporduce this issue:
1. Have this video file I guess, or a video file with stylized ASS subtitles (those found in anime fansubs)
2. enable "Allow subtitle extraction on the fly"
3. play the video with subtitles on in chrome

**Expected behavior**
Subtitles shouldn't be there.

**Logs**
I don't have logs for this but a subtitle file I extracted with mkvtoolnix
But that file type is not supported here

This is a screenshot of a working video file. Firefox, Chrome and the android app all display subtitles for this video even with "Allow subtitle extraction on the fly" enabled.

System:
 - OS: Raspbian upgraded to Buster
 - Browser: Chrome
 - Jellyfin Version: 10.4.3

**Comment by Amasuke** [comment]
It works in chrome again. I'm not sure if chrome got an update or not. But for now it shows the subtitles again, jsut like Firefox.

**Comment by dannymichel** [comment]
recently i've had the same issue on chrome but it hasn't been fixed.
half the time the same behavior you have got going on happens and the other half the same subtitles that load in mpv and plex dont load on jf 10.4.3 or 10.5
