### ISSUE TITLE
Missing error message while on mobile browsers

### ISSUE THREAD

**Issue by eltiel** [jellyfin/jellyfin-web#804]
**Describe the bug**
When attempting to play a HEVC 10bit file, Jellyfin 10.4.3 will supposedly will fail and return
PlaybackErrorNoCompatibleStream error. However when on mobile browsers (tested with Firefox Preview and Chrome on Android) there are no error messages to indicate what is wrong.

**To Reproduce**

1. Play a H265 10bit video with a mobile browser
2. The video will fail to play, but will result in different behaviours depending on the browser:

Chrome Android - gets stuck in this screen:
![74503741-dc377a00-4f2c-11ea-8297-fb404d1ddbce](https://user-images.githubusercontent.com/11868456/74554102-bb563f80-4f93-11ea-9ba3-721213fc1416.jpg)

Firefox Preview - this message appears for several seconds before turning into a blank screen:
![74503727-c5912300-4f2c-11ea-9278-f4a8ad636f74](https://user-images.githubusercontent.com/11868456/74554199-e771c080-4f93-11ea-8087-afd47759ab24.jpg)

**Expected behavior**
An error message with specific error code should be displayed to indicate what is wrong. When trying to play the same video on Firefox Windows 7, the proper error message appears:
![74505097-2de20380-4f31-11ea-8d48-579f5e036a48](https://user-images.githubusercontent.com/11868456/74554295-26077b00-4f94-11ea-8b64-0db1b4c437ce.JPG)

**Logs**
Error messages as seen in screenshots

**Screenshots**
As above

**System (please complete the following information):**
 - OS: Android
 - Browser: Chrome / Firefox Preview
 - Jellyfin Version: 10.4.3

**Additional context**
https://github.com/jellyfin/jellyfin/issues/2406

**Comment by dkanada** [comment]
added this string in #801
