### ISSUE TITLE
remove libraries from source control

### ISSUE THREAD

**Issue by dkanada** [jellyfin/jellyfin-web#81]
We can pull out the libraries and use #33 to download dependencies during a build step. I will list any libraries I can find below and their most likely version, I didn't see any easy way to get a list of installed libraries so I will just be looking through the bower dependencies folder.

**Comment by cvium** [comment]
Keep in mind that libjass is Apache2. We should switch to https://ass.js.org or https://github.com/Dador/JavascriptSubtitlesOctopus
