### ISSUE TITLE
[Firefox] Sometimes doesn't open "Manage library" window

### ISSUE THREAD

**Issue by simonbcn** [jellyfin/jellyfin-web#826]
- Arch Linux
- Firefox 73.0
- Jellyfin 10.5.0 (_installed from jellyfin-git AUR package_)

`Dashboard`>`Libraries`, click `...` on any library and select `Manage library`. Sometimes it doesn't open anything. I have to reopen the web client to this works.
In Firefox browser console no error or warning.

**Comment by JustAMan** [comment]
Does it happen with any other browser?

**Comment by simonbcn** [comment]
With Chromium works well.
