### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by vladimirjendrol** [jellyfin/jellyfin-web#83]
I  was working on translation of the Emby, now I would like to help translate Jellyfin. Would it be possible to set up some translation interface? Emby uses [oneskyapp](oneskyapp.com). [Transifex](https://www.transifex.com) is also popular for translation of open-source projects.

**Comment by joshuaboniface** [comment]
We've set up a Weblate instance at https://translate.jellyfin.org that should be working well now. This has also been added to the docs in jellyfin/jellyfin-docs#33.
