### ISSUE TITLE
Creating a library should pre-select the language information from current language settings

### ISSUE THREAD

**Issue by MrTimscampi** [jellyfin/jellyfin-web#830]
**Describe the bug**

When creating a library, no display language is selected by default in the wizard.

To improve usability, since most people will create libraries in their locale anyway, we should default the language field (and country ? If we have the full locale, it should be possible to infer this) in the library creation wizard to the user's current display language.

**To Reproduce**

1. Go to the admin dashboard > Library
2. Create a new library
3. The Language and Country fields are empty by default

**Expected behavior**

The fields should be populated according to the user's current display locale.

**Logs**

None

**Screenshots**

None

**System (please complete the following information):**
 - OS: All
 - Browser: All
 - Jellyfin Version: pre-10.5.0

**Additional context**

None

**Comment by Artiume** [comment]
Similar issue I opened here for the startup wizard
https://github.com/jellyfin/jellyfin-web/issues/794
