### ISSUE TITLE
[Safari] Playback doesn’t start automatically

### ISSUE THREAD

**Issue by philosen** [jellyfin/jellyfin-web#832]
**Describe the bug**
When watching any file the playback doesn’t start automatically. I have to click on the play button and then it starts immediately. This doesn’t happen all the time, but pretty frequently.

**System (please complete the following information):**
 - OS: macOS 10.14.6
 - Virtualization: Docker
 - Clients: Safari
 - Browser: Safari
 - Jellyfin Version: 10.5 nightly 20200218
 - Playback: Direct Stream
 - Installed Plugins: Trakt, Playback Reporting, TMDb Box Sets
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Bridge
 - Storage: local

**To Reproduce**
1. Go to 'Home'
2. Click on 'any video play button'
3. Video opens, but doesn’t start playback

**Expected behavior**
Playback should start automatically

**Logs**
Not sure what to look for

**Comment by JustAMan** [comment]
This is a web issue, so I moved it.

Does it manifest in Safari only (that said, does it work in Chrome or FF)?

**Comment by philosen** [comment]
Thanks for moving.

I just checked again. Didn't automatically start using Safari again. Immediately after that tried with Chrome and it started right away. So I guess it is related to Safari. I'm on Catalina with the latest updates installed.

Actually I just tried it on my iPad with Safari as well. Same issue. No issue using the Jellyfin Mobile beta.

**Comment by randrey** [comment]
Safari blocks auto-playback of any audible content.
https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/
Other browsers are supposed to do the same, but, I guess, decided not to enforce this behavior.
In any case, allowing auto play in Safari preferences does resolve this nuisance. Not sure about IOS.
<img width="892" alt="image" src="https://user-images.githubusercontent.com/798485/79415429-45a22c00-7f62-11ea-91b2-1a0a937008c6.png">

**Comment by philosen** [comment]
@randrey good catch. But how come Youtube, Netflix etc. don't have this problem (also Plex IIRC)..

**Comment by MrTimscampi** [comment]
> @randrey good catch. But how come Youtube, Netflix etc. don't have this problem (also Plex IIRC)..

Safari might have a whitelist of domains or use some heuristics to determine if you've interacted with the videos before and would like to play them by default.

As-is, there isn't much we can do about this, afaik, so I'm closing this for now.
