### ISSUE TITLE
Unable to change another user's preference settings via the admin dashboard

### ISSUE THREAD

**Issue by HanFox** [jellyfin/jellyfin-web#833]
**Describe the bug**
Unable to change another user's preference settings via the admin dashboard.

**To Reproduce**
1. Create a new account (i.e. "Test")
2. Try to use the Admin account to edit the Test users settings on `mypreferencesmenu.html` i.e. Display, Home, Playback, or Subtitles section (note: "Profile" works).
3. Observe error in Browser's Developer Console

**Expected behaviour**
User settings pages will be accessible.

**Logs**
From Chromium:
```
display.js?v=10.5.0:14 Uncaught (in promise) TypeError: userSettings is not a constructor
    at new <anonymous> (display.js?v=10.5.0:14)
    at viewManager.js?v=10.5.0:27
    at viewContainer.js?v=10.5.0:107
```

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: Docker
 - Browser: Firefox & Chromium
 - Jellyfin Version: nightly (e03bf0146ab9) (pulled ~10 mins before this bug report).

**Additional context**
I recall this function working on the stable releases recently.

**Comment by mezzovide** [comment]
Hello, i think this issues reappear in 10.7.0-rc3. Anyone have same problem with me? And settings -> client settings for android is also not available from web admin page
