### ISSUE TITLE
2 speakers icons next to volume slider

### ISSUE THREAD

**Issue by Bond-009** [jellyfin/jellyfin-web#841]
**Describe the bug**
The volume slider has 2 speaker icons next to it.

**To Reproduce**

1. Play something
2. Look at the volume slider
3. Create a bug on the web repo because you know nothing about web development

**Expected behavior**
There should only be 1 icon.

**Screenshots**
![image](https://user-images.githubusercontent.com/21289123/75094358-99a81a00-558a-11ea-924e-2990a82e8aea.png)
![image](https://user-images.githubusercontent.com/21289123/75094359-9c0a7400-558a-11ea-8278-9e4df1707275.png)

**System (please complete the following information):**
 - OS: Debian
 - Browser: Firefox 73.0.1
 - Jellyfin Version: web commit: b377878fd355b8b4c42954ccbc95a69aa227f302

**Comment by nyanmisaka** [comment]
It's related to this PR: https://github.com/jellyfin/jellyfin-web/pull/814

**Comment by JustAMan** [comment]
@Bond-009 can you confirm it's fixed with #814?

**Comment by nyanmisaka** [comment]
> @Bond-009 can you confirm it's fixed with #814?

Yes. It has been fixed.
