### ISSUE TITLE
Play button is off center

### ISSUE THREAD

**Issue by Bond-009** [jellyfin/jellyfin-web#842]
**Describe the bug**
Play button is off center

**To Reproduce**
1. Hover over an item
2. "Literally unplayable"

**Expected behavior**
A play button that doesn't trigger everyone's OCD

**Screenshots**
![Screenshot_2020-02-22_22-31-33](https://user-images.githubusercontent.com/21289123/75099669-9f225600-55c4-11ea-8bb2-529f34baff31.png)

**System (please complete the following information):**
 - OS: Debian
 - Browser: Firefox 73.0.1
 - Jellyfin Version: web commit: b377878fd355b8b4c42954ccbc95a69aa227f302

**Comment by JustAMan** [comment]
I've tried to repro using web 9162f53b98872c60af923bccd06f761d48872639 and Firefox x64 73.0.1 on Windows. For me play hover is centered (in "movies").

**Comment by JustAMan** [comment]
Okay, I reproduced it. Seems there's a data race between loading `card.css` and material icons package, whichever comes last wins and sets the `display` property of that arrow.

**Comment by JustAMan** [comment]
With a hack mentioned in my PR (making server wait before responding to `bundle.js` request for 3 seconds) and clearing cache I can reproduce the problem in other browsers as well, and my PR fixes those, too.
