### ISSUE TITLE
[Feature Request] Filters more friendly user and other features.

### ISSUE THREAD

**Issue by ruCyberPoison** [jellyfin/jellyfin-web#850]
Hi everyone, 

There some filters can be improves, as i can see on the emby it doesn't has been improved but i would like it as been something to be improved.

Filters like this is welcome to be developed 

![image](https://user-images.githubusercontent.com/26681688/75176705-f0515780-5734-11ea-9f7d-51732fc1bea1.png)

![image](https://user-images.githubusercontent.com/26681688/75177140-de23e900-5735-11ea-9fb9-c5db197eff70.png)

A tab like this will be very appreciated is more polarized and friendly user than the emby have, 
please merge this request to the https://features.jellyfin.org/ as JF team can.

a other feature will be to [Download/Sync From...] option on the JF but this is maybe related with this feature since JF doesn't support DL on Android Device /iOS/Android TV...

[https://features.jellyfin.org/posts/218/jellyfin-mobile-app-offline-downloads](https://features.jellyfin.org/posts/218/jellyfin-mobile-app-offline-downloads
)

Allow Direct Play on the JF Web Player without disabling the Transcode on the server/user,
 
![image](https://user-images.githubusercontent.com/26681688/75177535-a5d0da80-5736-11ea-83ce-9bd1b006151a.png)

A other feature well be to stop the playback from the admin dashboard like Plex allows .

Kind Regards,

Feel free for anyone to developer this features 

Love JF

**Comment by sparky8251** [comment]
I see that you've used 2 of your own accounts to give the illusion that your feature request has more support than it does.

![Screenshot_20200226_060444](https://user-images.githubusercontent.com/1992688/75339254-29391b80-585e-11ea-9ddb-818f44c1f95e.png)

I haven't read the request and frankly, with you doing shit like this I don't care.

Remove them or I will be closing this issue for being unacceptable conduct.
