### ISSUE TITLE
Search results are hard to discern

### ISSUE THREAD

**Issue by gerroon** [jellyfin/jellyfin-web#859]
Hi

The resulting listing of the search results are really hard to understand because the listings have truncated video names, and there are no other helpers to figure out what the user is looking at. 

Please see the image below. As you see all I can see is that they are "Blender related"  but the rest is not much clear. There should be a way to increase the text length and the way the search results are displayed, maybe a list based search listing is better.

![eRK1byv](https://user-images.githubusercontent.com/8519469/75268114-b75cc580-57bc-11ea-9fbd-828a78f1e0a9.png)

**Comment by JustAMan** [comment]
This is a web UI issue, so I moved it.

**Comment by ThibaultNocchi** [comment]
In the latest repo version, if you hover the names with your cursor it displays the entire name. Is it sufficient?
![info_bubble](https://user-images.githubusercontent.com/1619359/75432156-4cdb8f00-594e-11ea-91d9-146eaa60ab05.png)

**Comment by gerroon** [comment]
@ThibaultNocchi  

Well, this solution assumes one has a mouse to hover around. Try this on a mobile this or some kind of smart tv.

**Comment by MrTimscampi** [comment]
For mobile, we could use a tap and hold on the truncated elements to show the full text.

For TV, a solution could be to have scrolling text if the text is too big to fit.

This would likely require quite a bit of work on the affected elements, though.

**Comment by gerroon** [comment]
Wy not make the listing vertical and show the text properly?

**Comment by ThibaultNocchi** [comment]
Maybe a listing as when you open the search bar without typing anything?

![print_screen_2020-02-29-13-09-31](https://user-images.githubusercontent.com/1619359/75607204-d200a880-5af4-11ea-9b79-0367aba763ab.png)

We could maybe add a client setting to choose between listing mode or "poster" mode?

**Comment by Artiume** [comment]
https://github.com/jellyfin/jellyfin/pull/2478

This will fix the search engine. It still needs work on proper sorting for non-movies.

**Comment by JustAMan** [comment]
@Artiume I think this issue is about showing the results, not about the results themselves :)

**Comment by Artiume** [comment]
That's why I put `This doesn't really help the UI situation, just wanted to link it :)` ;)

**Comment by MrTimscampi** [comment]
Please redirect feature requests and suggestions to https://features.jellyfin.org/
