### ISSUE TITLE
 Remove remaining uneeded lang references

### ISSUE THREAD

**Issue by sparky8251** [jellyfin/jellyfin-web#87]
As part of #386 I also found a large number of unneeded lang file strings that are refereed to elsewhere.

The vast majority of these are still tied into JS that we dont need, but is referred to anyways. Since it requires additional effort, it has been left outside of the PR that removes the unreferenced strings.

Below is the complete list of strings I found that are referred to in code but we have no need for:

- [ ] ButtonLearnMoreAboutJellyfinConnect
- [ ] ButtonSendInvitation
- [ ] ErrorAddingJellyfinConnectAccount1
- [ ] ErrorAddingJellyfinConnectAccount2
- [ ] ErrorAddingJellyfinConnectAccount3
- [ ] ErrorMessageEmailInUse
- [ ] ErrorRemovingJellyfinConnectAccount
- [ ] FeatureRequiresJellyfinPremiere
- [ ] GuestUserNotFound
- [ ] HeaderAddLocalUser
- [ ] HeaderBecomeProjectSupporter
- [ ] HeaderBranding
- [ ] HeaderBrandingHelp
- [ ] HeaderFreeApps
- [ ] HeaderInvitationSent
- [ ] HeaderInvitations
- [ ] HeaderInviteUser
- [ ] HeaderInviteWithJellyfinConnect
- [ ] HeaderPendingInvitations
- [ ] HeaderSupportTheTeam
- [ ] HeaderSupporterBenefits
- [ ] HeaderTermsOfService
- [ ] HeaderWelcomeToJellyfin
- [ ] HowToConnectFromJellyfinApps
- [ ] Invitations
- [ ] InviteAnJellyfinConnectUser
- [ ] JellyfinIntroDownloadMessage
- [ ] JellyfinIntroDownloadMessageWithoutLink
- [ ] JellyfinIntroMessage
- [ ] LabelAddConnectSupporterHelp
- [ ] LabelConnectGuestUserName
- [ ] LabelConnectGuestUserNameHelp
- [ ] LabelConnectUserName
- [ ] LabelConnectUserNameHelp
- [ ] LabelEmail
- [ ] LabelEmailAddress
- [ ] LabelEnterConnectUserNameHelp
- [ ] LinkLearnMoreAboutSubscription
- [ ] MessageConnectAccountRequiredToInviteGuest
- [ ] MessageGuestSharingPermissionsHelp
- [ ] MessageJellyfinAccontRemoved
- [ ] MessageJellyfinAccountAdded
- [ ] MessagePendingJellyfinAccountAdded
- [ ] MessagePleaseAcceptTermsOfServiceBeforeContinuing
- [ ] MessagePluginRequiresSubscription
- [ ] MessagePremiumPluginRequiresMembership
- [ ] MessageProfileInfoSynced
- [ ] MessageThankYouForConnectSignUp
- [ ] MessageThankYouForConnectSignUpNoValidation
- [ ] MessageThankYouForSupporting
- [ ] MessageTrialExpired
- [ ] MessageTrialWillExpireIn
- [ ] RegisterWithPayPal
- [ ] TermsOfUseTermsOfUse
- [ ] TextEnjoyBonusFeatures
- [x] XmlTvPremiere

**Comment by dkanada** [comment]
@sparky8251 this can probably be closed, we have no unused strings. I actually keep a branch with some python scripts I use to maintain the string files as well.
