### ISSUE TITLE
Handling of external links in TV apps

### ISSUE THREAD

**Issue by dmitrylyzo** [jellyfin/jellyfin-web#873]
**Describe the bug**
On itemdetails page, we have some external links: `IMDb`, `TheMovieDb`, `Trakt`. At current moment, when we click on them in TV app (Tizen, WebOS), window location changes, and we lose control over `Back` button due to manual handling.

Before my "framed"-PR, WebOS app can go back due to built-in `Back` handling as `history.back`.

**To Reproduce**
1. Open Jellyfin WebOS app
2. Go to Movie / Some_movie
3. Scroll down to "Added ... , Links ..."
4. Click on some external link: `IMDb`, `TheMovieDb`, `Trakt`
5. Now you are not able to go back

**Expected behavior**
Logically, we want to be able to go back on `Back` pressed.
On the other hand, what can we do with keyboard/remote navigation on the foreign site?
How should external links be handled?

**System (please complete the following information):**
 - OS: WebOS 4, Tizen 4
 - Browser: apps (Chrome 53, Chrome 56)
 - Jellyfin Version: pre-10.5.0

**Comment by JustAMan** [comment]
Can we make it so links would open in TV browser?

**Comment by dmitrylyzo** [comment]
> Can we make it so links would open in TV browser?

I thought about it. I added `NativeShell.openUrl` handling in app and stuck with opening browser in WebOS :smile: WebOS 4 emulator has no pre-installed browser.

**Comment by MrTimscampi** [comment]
Should we perhaps disable those links on TV apps, since it leads away from the server and the platform holders may not like an app that's potentially able to browse whatever ?

**Comment by dmitrylyzo** [comment]
_Just to let you know_
I found a way to run browser from WebOS app: https://webostv.developer.lge.com/api/webostvjs/webosdev?wos_flag=APP#APP
Tested in WebOS 3 emulator. The only way to return from opened browser to Jellyfin app is WebOS Home menu.

**Comment by JustAMan** [comment]
That is fine. IMHO we should either disable external links or open them in browser.
Returning via Home menu isn't that bad IMHO.
