### ISSUE TITLE
Video playback offset after skipping in Safari on macOS

### ISSUE THREAD

**Issue by lldsolitude** [jellyfin/jellyfin-web#879]
**Update 4/13**
I have discovered that it's not the subtitle that is out of sync, but rather the video (and audio) gets randomly offset after skipping forward or back during playback and does not match the timestamp displayed in the progress bar anymore. The subtitles are correctly timed.

**Describe the bug**

Subtitle goes out of sync whenever I skip forward during playback or when playback starts at a time other than the beginning. Also the subtitle can't be disabled once it's enabled; the subtitle still displays even if I switch the setting to "Off". 
**To Reproduce**

Out of sync:
1. Start playback.
2. Click fast-forward button or progress bar to skip forward.
or
1. Resume incomplete playback.

Subtitle can't be disabled:
1. Start playback.
2. Choose any subtitle track in subtitle selection menu.
3. Choose "Off" in subtitle selection menu. The subtitle still displays.

**Expected behavior**

1. Subtitles stay in sync at all times.
2. Subtitles can be turned off.

**System (please complete the following information):**
 - OS: macOS 10.15.3
 - Browser: Safari 13.0.5
 - Jellyfin Version: 10.4.3

**Comment by JustAMan** [comment]
Wait until we release 10.5.0 (expected really soon) then update and re-test.
I doubt we would be fixing issues on 10.4.x branch with 10.5.0 being almost ready.

**Comment by lldsolitude** [comment]
I have tested 10.5.0. Subs are now in sync all the time, but still can't be turned off. I can switch between different languages but can't turn it off.

**Comment by JustAMan** [comment]
cc @redSpoutnik as our main contributor to subtitles sync :)

**Comment by redSpoutnik** [comment]
Unfortunately I don't have access to a macOS device, and it seems that safari is unavailable for linux.

It will be difficult to me to reproduce the error.

**Comment by JustAMan** [comment]
@lldsolitude what subtitles are you using? can you try with Chrome/Firefox?

**Comment by lldsolitude** [comment]
I'm using English srt subtitles. Chrome/Firefox doesn't have sync problems, only Safari does. Unfortunately, only Safari supports subtitle display in picture-in-picture mode (in Chrome/Firefox the subtitles stay in the main window and not in the PiP window), so I'd like subtitle sync to work on Safari if possible.

**Comment by JustAMan** [comment]
@lldsolitude can you please tell me how much they're out of sync on Safari? I think that this might fix your issue: https://github.com/jellyfin/jellyfin-web/pull/1040

**Comment by lldsolitude** [comment]
@JustAMan It's more than 2.5 seconds, sometimes too early, sometimes too late (even for the same file in different playback sessions). I built the latest code and tested it, but the problem is still there.

**Comment by JustAMan** [comment]
@cvium IIRC you have a Mac, can you look into this?

**Comment by Artiume** [comment]
https://github.com/jellyfin/jellyfin-android/issues/301

I imagine these two are related

**Comment by mariusoei** [comment]
> [jellyfin/jellyfin-android#301](https://github.com/jellyfin/jellyfin-android/issues/301)
> 
> I imagine these two are related

To see if it's the same problem, could you check if it's the subtitles or the video that's offset?
I filed that issue and thought it was a subtitle problem, but in my case the video playback didn't match the playback bar.
You can use another media player such as VLC to see if the video playback matches the playback bar.

**Comment by lldsolitude** [comment]
@mariusoei You are absolutely right!
It's not the subtitle that is out of sync, it's the video that is out of sync!
I'm going to update the title and content of the issue.

**Comment by JustAMan** [comment]
I'm pretty sure it has something to do with the fact that Safari and mobile Chrome (and our app) are the only browsers that support native HLS playback. I've already fixed a few issues arising due to not accounting for that fact.

Now I probably need a reproducer I can run on my end, as I don't see why it doesn't work for you.
If you can share a test video, probably by messaging me on Matrix, that could give me pointers.

**Comment by lldsolitude** [comment]
I have tested a lot of videos in my library with different encodings (both x264 and x265) and different qualities (from 480p to 1080p), playing them with and without transcoding, and they all have the same problem, so I don't think the problem is specific to certain videos. Of course if you still want one of the videos I'd be happy to share it.

**Comment by JustAMan** [comment]
Would be pretty hard for me to repro if it's showing only in Safari... can you test using mobile Chrome on Android? I'm hoping it exhibits the same problem.

P.S. I cannot accept your invite on Matrix for some reason, pls hop on one of our channels there so we can initiate the communication there and then go to DM.

**Comment by lldsolitude** [comment]
You're right, mobile Chrome on Android does have the same problem.
Since I live in China so it's really late when I invited you on Matrix, and after a while I had to go to sleep. I have no idea why the invitation failed, but since I am new to Matrix maybe I did something wrong. I'll try the invitation again.

**Comment by lyz-code** [comment]
This issue is still present in 10.7.7

**Comment by realtofuine** [comment]
This issue persists on 10.8.8
