### ISSUE TITLE
Artist and Album External id tags

### ISSUE THREAD

**Issue by hamburglar2160** [jellyfin/jellyfin-web#891]
In a music library folder the Artist page accepts only two External id tags: MusicBrainz id and TheAudioDb id (this is for albums). 

The Album page accepts MusicBrainz Album id; MusicBrainz Artist Id (it does not get matched when scanned and JF does not retrieve this tag already embedded in the file); MusicBrainz Release Group Id; TheAudioDb Id; and TheAudioDb Artist Id.

The Artist page SHOULD accept a few of the id tags present in the Album page-- especially MusicBrainz Artist Id and TheAudioDb Artist Id. Adding the latter should therefore provide the artist bio to the Artist page thus bringing them more on par with their album and video counterparts. Hopefully additional artist images as well.

**Comment by dkanada** [comment]
might be related to #900
