### ISSUE TITLE
unneccesary transcoding of AV1 when target is compatible

### ISSUE THREAD

**Issue by PoepiePeppie** [jellyfin/jellyfin-web#893]
Jellyfin transcodes AV1 content even though it is not necessary for the target to play AV1 content.
Disabling transcoding for the user makes the file play with no issues.

 - OS: Debian
 - Virtualization: None
 - Played on browser
 - Browser: Firefox 73.1
 - Jellyfin Version: 10.4.3
 - Playback: Direct Play/Transcoding/Remux
 - Installed Plugins: OpenSubtitles
 - Reverse Proxy: Apache
 - Base URL:  /jellyfin
 - Storage: Local

**Steps to reproduce behaviour**
1. Play an AV1 file on firefox 73.1 with transcoding permissions for the user.
2. Playback will crash and give a playback error

**Expected behavior**
AV1 content plays without transcoding if AV1 is supported.

**Logs**
[https://pastebin.com/fWA5xHHp](https://pastebin.com/fWA5xHHp)

**Additional context**
Playback of AV1 content is possible. Disable all transcoding permissions for the users makes the file playback without any issue.

**Comment by JustAMan** [comment]
This is most likely a bug in `deviceprofile.js` or somewhere around, so moving it to web.

**Comment by Maltahl** [comment]
Same problem here:
Log files: 
[transcode error AV1 + OPUS.txt](https://github.com/jellyfin/jellyfin-web/files/4394083/transcode.error.AV1.%2B.OPUS.txt)
[Remux log error AV1 + OPUS.txt](https://github.com/jellyfin/jellyfin-web/files/4394084/Remux.log.error.AV1.%2B.OPUS.txt)
[Jellyfin logs with av1 fail and success direct play.txt](https://github.com/jellyfin/jellyfin-web/files/4394085/Jellyfin.logs.with.av1.fail.and.success.direct.play.txt)

Video file used: 
https://tools.woolyss.com/html5-audio-video-tester/?u=woolyss.com/f/caminandes-1-llama-drama-av1-opus-480p.webm 
file from:
https://tools.woolyss.com/html5-audio-video-tester/

**Comment by PoepiePeppie** [comment]
From looking in the file it seems it's not really a bug but rather that there's just nothing defined for AV1 content.

**Comment by JustAMan** [comment]
@thornbill was it you who last time wanted to clean up `deviceprofile.js`?..

**Comment by PoepiePeppie** [comment]
Should be resolved with #1167
