### ISSUE TITLE
Add "select all" to selection menu

### ISSUE THREAD

**Issue by hamburglar2160** [jellyfin/jellyfin-web#895]
After pressing and holding a media entry the selection menu should include "select all" so one does not have to individually select several additional entries.

![image](https://user-images.githubusercontent.com/61879508/76103299-72e0df00-5f9f-11ea-8836-b4d28608ce92.png)

**Comment by dmitrylyzo** [comment]
As an option:
"Select All" could be placed in the top blue bar. Only device screen size could be a problem.

**Comment by MrTimscampi** [comment]
Having the button accessible in the blue bar would be the preferred solution on desktop, since it's a common action.

We could hide it on mobile if needed, then show it as part of the dropdown.

**Comment by Likeachampxx** [comment]
+1!!!!

**Comment by Gummibaer** [comment]
+1!

**Comment by privilegejunkie** [comment]
Not sure if this is the right place for logging such a request or not but yeah, I would like to see this as well.

**Comment by andrienko** [comment]
As a workaround... I usually do something like this:
