### ISSUE TITLE
Chrome Mobile / Android Resume not working on non-Direct Play

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-web#899]
Behavior observed on mobile browsers and android. You can only start a partially played episode from the beginning, there is no resume option. Related note, on home page, you can only resume an episode using the play button. 

![Screenshot_20200307-050341_Jellyfin](https://user-images.githubusercontent.com/20715731/76141984-0e715e80-6037-11ea-82c8-803177648093.jpg)

**Comment by eltiel** [comment]
Having this problem as well.

**Comment by JustAMan** [comment]
Apparently this only happens for transcoded items, direct play items should be fine.
Right @Artiume ?

**Comment by Artiume** [comment]
Yup, direct play resumed perfectly

![Screenshot_20200401-172106_Chrome](https://user-images.githubusercontent.com/20715731/78187889-42c11a80-743d-11ea-80ac-e1eb20fe75f7.jpg)

**Comment by bnichs5** [comment]
When can we expect to see the update. Just tried with the newest nightly version. Still having the same problems.

**Comment by JustAMan** [comment]
@bnichs5 this was released as part of 10.5.4 (only as web part), Android client is yet to be released.
See https://github.com/jellyfin/jellyfin-android/pull/309

If you're seeing seek issues in mobile Chrome on 10.5.4 please open a new ticket.
