### ISSUE TITLE
Dark overlay staying on

### ISSUE THREAD

**Issue by Numline1** [jellyfin/jellyfin-web#90]
Hello!

First of all, thanks for all the great work done on Jellyfin! I've noticed an issue over the past few days since I started using this fork.

The modal popup overlay tends to stay on over the player in some situations. By overlay I mean the dark cover that appears when you perform an action in the player menu, like picking subtitle or displaying the 'stats for nerds'.

Example:

![image](https://user-images.githubusercontent.com/12192684/50525652-210c1180-0add-11e9-8577-a2f06cef70f4.png)

I've noticed this behaviour in both Safari and Chrome. In this case, I was watching a video for a few minutes, decided to pick English subtitles by clicking the "CC" button at the bottom. After i did that, the video started re-encoding, as it should, the series poster appeared and once the video started playing a few seconds later, the black overlay was there, as seen in the picture.

This dissapears after reload/reselecting the episode from home screen, which basically reloads the players/page.

I did some digging and found out which div causes the issue (it went away after I set "display: none" property on it, see screenshot below.

![image](https://user-images.githubusercontent.com/12192684/50525837-4baa9a00-0ade-11e9-9b6b-ae9cf997b889.png)

I hope it helps with debugging. Thanks in advance!

**Comment by sparky8251** [comment]
If someone can provide instructions that reliably produce this I can take a crack at it. I occasionally get it as well, but I haven't been able to find an exacerbating factor or reliable means of causing it.

**Comment by Numline1** [comment]
Not really? I didn't have that issue in a while. I feel like it was happening when I was on vacation by the end of 2018 with shitty internet. When I opened the "Stats for nerds" and the video started buffering, sometimes it stayed. Since I've been back home, the video never buffers, so that's probably why it stopped happening.

This might be a start, but I'm not sure whether this is the exact way of how to reproduce it or more of a anecdotal coincidence.

**Comment by Bond-009** [comment]
Didn't this get fixed by #218?

**Comment by dkanada** [comment]
@Bond-009 is correct
