### ISSUE TITLE
Library Page Resets Location Marker

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-web#901]
While performing some actions (such as clicking Edit Metadata) will reset the location marker to the top of the pagnation instead of maintaining the current location.

Click Identify and then pressing Back will maintain the page location.

Click Edit metadata and then pressing Back will return you to the top of the page.

**Comment by ferferga** [comment]
Fixed in #1442

As discussed in Matrix, the behaviour for edit metadata makes sense as we need to see the changes that have been made
