### ISSUE TITLE
Identify Sources Labels

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-web#902]
The left picture is from IMDb, the one on the right is from TMDB. Perhaps add the option for displaying where the metadata is being pulled from. Also, what about nfo? D:

![image](https://user-images.githubusercontent.com/20715731/76147435-2b735500-606a-11ea-87b8-78afaf553182.png)

**Comment by Artiume** [comment]
Also, could we append the Path to the top? I have a bad memory and can't ever remember the exact details once I'm on the Identify page lol. 

This would be much helpful
![image](https://user-images.githubusercontent.com/20715731/76147729-44313a00-606d-11ea-863b-e58bd5ee20c5.png)

**Comment by MrTimscampi** [comment]
Fixed as of 10.6.
