### ISSUE TITLE
[Enhancement] Search Categories

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-web#905]
So currently, the blank search preview shows some random movies. I first thought we could do could be generic titles like movies shows music, but I think a better idea could be the libraries. We could allow dynamic presorting of the libraries. With perhaps some default ones of the 'movies TV music'. 

![Screenshot_20200307-191101_Chrome](https://user-images.githubusercontent.com/20715731/76154329-99d70800-60a8-11ea-9d7e-69a22916c350.jpg)

**Comment by MrTimscampi** [comment]
Please redirect feature requests and suggestions to https://features.jellyfin.org/
