### ISSUE TITLE
Can't enter fullscreen through the UI or hotkey

### ISSUE THREAD

**Issue by Jordy3D** [jellyfin/jellyfin-web#906]
Title, really. I and other users on my server can't seem to enter fullscreen through the UI or the F key. The F11 key in Chrome for example does work, however. 

Not exactly sure if it's a problem with my server or something, but either way I couldn't find anything about it.

Apologies if this is in the wrong place or a repeat issue or somethng like that. 

**Expected behavior**
Hitting the Fullscreen button or pressing the fullscreen hotkey to bring the video to fullscreen

**System (please complete the following information):**
 - OS: Windows 10
 - Browser: Tested on Chrome and Edge (Chromium)
 - Jellyfin Version: 10.4.3

**Comment by JustAMan** [comment]
Could you please re-test with most recent release (probably 10.5.2 at this moment)?

**Comment by Jordy3D** [comment]
Just tested with the new version and it was also broken there, unfortunately.

**Comment by dmitrylyzo** [comment]
If you use proxy, please check for `Feature-Policy: fullscreen 'none'`.
And logs from browser could be helpful.

With mentioned feature blocking, I got:
```
Uncaught (in promise) TypeError: fullscreen error
    at fullscreenManager.requestFullscreen (fullscreenManager.js?v=10.5.0:13)
    at PlaybackManager.self.toggleFullscreen (playbackmanager.js?v=10.5.0:1534)
    at onWindowKeyDown (videoosd.js?v=10.5.0:1136)
```

**Comment by Jordy3D** [comment]
This is the log I got on pressing the Fullscreen button
```
fullscreenManager.js?v=10.5.2:13 Uncaught (in promise) TypeError: fullscreen error
    at fullscreenManager.requestFullscreen (fullscreenManager.js?v=10.5.2:13)
    at PlaybackManager.self.toggleFullscreen (playbackmanager.js?v=10.5.2:1534)
    at HTMLButtonElement.<anonymous> (videoosd.js?v=10.5.2:1347)
```

I'm not aware of any proxy set up anywhere, however I can say it works as intended if I access the server through the IP directly rather than through my domain.

**Comment by dmitrylyzo** [comment]
> This is the log I got on pressing the Fullscreen button ...

I have the same with feature blocking.

In browser, you can look into `Network`/`<some js>`/`Headers`/`Response Headers` for `Feature-Policy`.

> however I can say it works as intended if I access the server through the IP directly rather than through my domain.

Good. This means that Jellyfin is OK.
What do you use to up a domain?
