### ISSUE TITLE
Move to video.js as media player 

### ISSUE THREAD

**Issue by JustAMan** [jellyfin/jellyfin-web#91]
Let's consider moving to video.js, it seems to be more-or-less a de facto html5 standard player now. It also seem to have more features (like mpeg-dash, webm-dash and cross-browser multiple audio tracks support) than the currently used solution which relies on browser support for multiple tracks and can either direct-play or use hls (forcing transcode to h264/mp3 even if you just want to remux a track in webm).

**Comment by cvium** [comment]
@JustAMan video.js is Apache2 though

**Comment by JustAMan** [comment]
Dammit, I didn't check the exact OSS license out there... We really need to work on re-licensing to GPLv3 or something like that to make Apache2 a non-issue in the future.

For now closing as an impossible thing due to licensing.
