### ISSUE TITLE
Limit number of genres shown in playlist

### ISSUE THREAD

**Issue by hamburglar2160** [jellyfin/jellyfin-web#914]
Trim out the number of genres displayed on a playlist. Online audio databases don't have completely standardized genres so there could very easily be several outliers in a thematic playlist. Omit the 20-30% least prevalent genres listed on the top of each playlist.

For example pictured is a ~1000 song Jazz playlist. A few songs have erroneously tagged genres (Dizzy Gillespie; Country; Dancehall; etc.). While they may be present they are no way representing the spirit of the playlist. Down the line this could make the "more like this" view more useful.
![Screenshot_20200309-120702](https://user-images.githubusercontent.com/61879508/76234491-306a0d00-6200-11ea-84d5-bd2db35396ab.png)

**Comment by Artiume** [comment]
For playlists specifically, what about a tolerance? It might help filter out the songs that have bad genres tags. So if only one song is tagged with country, and the overall tolerance is 3, it won't show up. Only the genres that have at least 3 songs with that genre tag.

**Comment by hamburglar2160** [comment]
That sounds good. Bump it up to 5 though!

**Comment by Artiume** [comment]
I think it should be customizable. If I have a playlist of 10 songs, it might be too restrictive. If I have a playlist of 10000 songs, it might not be restrictive enough

**Comment by JustAMan** [comment]
Take tags that are present in >= 10% of playlist, but not less than 3 (for super-small playlists)?

**Comment by Artiume** [comment]
Sounds reasonable
