### ISSUE TITLE
[Question] Is the "Image of the loaded camera" notification necessary?

### ISSUE THREAD

**Issue by 97carmine** [jellyfin/jellyfin-web#917]
I remember this feature in Emby, but I haven't seen anything related in Jellyfin.

![Screenshot_2020-03-10 Jellyfin](https://user-images.githubusercontent.com/6619414/76297689-2b649680-62b0-11ea-942a-548a4cd25b88.png)

**Comment by dkanada** [comment]
We haven't removed it yet, but the functionality never existed.
