### ISSUE TITLE
add feature - photos library - forward / backward - arrow keyboard

### ISSUE THREAD

**Issue by lelamamalgache** [jellyfin/jellyfin-web#918]
**Describe the bug**
On jellyfin web, i'm not able to  forward or backward pictures with arrow of the keyboard except if i click with my mouse on icons on each borders

**System (please complete the following information):**
 - Clients: Browser
 - Browser: Chrome, Microsoft edge
 - Jellyfin Version: 10.5.0

**To Reproduce**

1. Go to your Photos libarary
2. Play an album
3. Press arrow right arrow key to forward or left arrow key to backward
4. Nothing happen

**Expected behavior**
map left arrow to backward and the right arrow to forward manually like you did with the key "space" to pause or play the item

<img width="936" alt="keyboardarrow" src="https://user-images.githubusercontent.com/58141187/76268816-a9ed1400-626f-11ea-93d1-9b9270d570e8.png">

**Comment by lelamamalgache** [comment]
hello :)

forward / backward - arrows keyboard do not work
Could you have a look ?

**Comment by MrTimscampi** [comment]
Hi @lelamamalgache. The rework of the image viewer was done after 10.5 hit so it'll be released in 10.6.

If you are using master and still face the issue, opening a new issue might be good (Do note that the nightly builds are severely out of date, at this point).
