### ISSUE TITLE
Broken Help Links in Dashboard

### ISSUE THREAD

**Issue by mgpat-gm** [jellyfin/jellyfin-web#925]
**Describe the bug**
The help links for DLNA and Networking settings in the Dashboard are no longer working.

**To Reproduce**
1. Go to Admin/Dashboard
2. Click on Devices/DLNA
3. Click on "Help" button.
4. Directs to "https://jellyfin.org/docs/general/administration/connectivity.html#DLNA"
5. Follow similar steps for Advanced/Networking.
6. Directs to "https://jellyfin.org/docs/general/administration/networking.html"

**Expected behavior**
DLNA help should direct to "https://jellyfin.org/docs/general/networking/dlna.html"
Networking help should direct to "https://jellyfin.org/docs/general/networking/index.html"

**System (please complete the following information):**
 - OS: Ubuntu 18.04 (any?)
 - Browser: Brave (any?)
 - Jellyfin Version: 10.5.0

**Comment by ThibaultNocchi** [comment]
I think this issue can now be close.

**Comment by MrTimscampi** [comment]
Thanks Thibault, closing this :+1:
