### ISSUE TITLE
Revamp toolbar

### ISSUE THREAD

**Issue by hamburglar2160** [jellyfin/jellyfin-web#927]
Jellyfin is (in part) about showing off all of your media in one place. When you first open the app having "favorites" there eating that screen space detracts from that. There are a few redundancies and perhaps unnecessary buttons that take up more space than necessary on the home screen, especially on mobile. 

edit:

Revised and more concise after discussions here and on matrix:

1. On mobile: Show hamburger menu on align-left (#932). Next to that show the Jellyfin logo without the "jellyfin" text in the interest of space. Chromecast button and search button remain. 
2. All Favorites (just named **Favorites**) placed in hamburger menu under "Media"
3. Add specific "favorites" to the header for TV Shows (currently missing)
4. Remove "home" and "favorites" and the header that contain them and reduce librarypage padding (pictured is 3.5em).

![Screenshot_20200316-112818](https://user-images.githubusercontent.com/61879508/76773848-80555080-6779-11ea-9309-45a306b5dab1.png)

**Comment by MrTimscampi** [comment]
We should keep UI consistent between screens, so I'm against having the tabs moved up on home (Besides, it could get messy on smaller screens).

The headerbar hides itself on mobile anyway, so it's a non issue.

The hamburger menu should be shown though, for sure.

**Comment by hamburglar2160** [comment]
the tabs already move up on non-mobile displays. i'm not advocating moving them up on mobile. i am advocating moving "favorites" up in the form of a "heart" button to free up valuable space.

the headerbar does not hide itself automatically on mobile but DOES on the non-mobile display. 

CSS code provided by thornbill will bandage this but still leaves a massive gap.
"
@media all and (max-width: 62.5em) {
  .noHomeButtonHeader .headerTabs {
    display: none;
  }
}
"
![image](https://user-images.githubusercontent.com/61879508/76426264-35a29580-6381-11ea-89b2-a0351ac11b0d.png)

**Comment by dmitrylyzo** [comment]
> the tabs already move up on non-mobile displays. i'm not advocating moving them up on mobile. i am advocating moving "favorites" up in the form of a "heart" button to free up valuable space.

_This is just quick CSS test._
![test](https://user-images.githubusercontent.com/56478732/76440723-572a6e00-63cf-11ea-98b8-bda03d3a9ce9.png)
In this case we need to extract favorite in its one page.

> the headerbar does not hide itself automatically on mobile but DOES on the non-mobile display.

it should hide on scroll down

**Comment by MrTimscampi** [comment]
> _This is just quick CSS test._
> ![test](https://user-images.githubusercontent.com/56478732/76440723-572a6e00-63cf-11ea-98b8-bda03d3a9ce9.png)

This isn't good usability wise, though. It suggests you can favorite this page, since that's what that icon does on every other screen.

**Comment by hamburglar2160** [comment]
Updated thoughts: 
1. Align-Center the Jellyfin logo rather than align-left (in line with other streaming apps)
2. Hamburger menu visible on the top left where Jellyfin logo used to be
3. All Favorites (just named **Favorites**) placed in hamburger menu under "Media"
4. Add specific "favorites" to the header for TV Shows (currently missing)

**Comment by hamburglar2160** [comment]
If we move Favorites into the hamburger menu from the home screen, here's the space that will be reallocated to displaying media items (taken from Android 1.0.0:
Before:
![image](https://user-images.githubusercontent.com/61879508/80497143-12837380-8938-11ea-885b-cdfa65188464.png)

After:
![image](https://user-images.githubusercontent.com/61879508/80497176-18795480-8938-11ea-90d4-65ad698cf32f.png)
