### ISSUE TITLE
Copy Stream url not workin in iOS safari/chrome/firefox

### ISSUE THREAD

**Issue by macr** [jellyfin/jellyfin-web#935]
**Describe the bug**
Tapping "Copy Stream URL" does nothing.

**To Reproduce**

1. Use Safari/Chrome/Firefox using an iPad/iPhone
2. Click on any media menu
3. Click on "Copy Stream URL"

**Expected behavior**
It should present a dialogue to copy the Stream URL 

**System (please complete the following information):**
 - OS: iPadOS 13.3.1
 - Browser: Firefox, Chrome, Safari
 - Jellyfin Version: 10.5.0

**Additional context**
This bug was introduced in 10.5.0, I believe from commit https://github.com/jellyfin/jellyfin-web/commit/0d0f210c6a2c737e0bc892106a6d2c59b8f1215d .
`navigator.clipboard` is `undefined` on [iOS safari][1]  so the fallback code never gets run.
Moving the fallback code outside `navigator.clipboard.writeText` fixes the issue.

[1]: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard

**Comment by jorritsmit** [comment]
Is this only for iOS? because it also doesn't seem to be working for me on android

**Comment by macr** [comment]
I tried it on both Firefox and chrome on android and it works fine for me. Chrome automatically copies the url to clipboard while firefox gives you the prompt to copy the url text. You can also see [here:](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard#Browser_compatibility) that browser the api it uses is compatible with android browsers so you are likely running into a different issue.
