### ISSUE TITLE
Make the poster a play button

### ISSUE THREAD

**Issue by theg00s3** [jellyfin/jellyfin-web#940]
The poster/episode screencap should play the movie/tv show when pressed, instead of editing the pictures. I've marked the area in case I'm not clear.
![Screenshot_2020-03-13 Jellyfin](https://user-images.githubusercontent.com/18522748/76604849-98ec1d80-6563-11ea-882c-cbc960d2c736.jpg)

Given that the "Continue Watching" row on the home page reacts similarly, it would feel more cohesive UI wise for the poster to do the same thing.

**Comment by MrTimscampi** [comment]
Covered by an open PR, but please redirect feature requests and suggestions to https://features.jellyfin.org/
