### ISSUE TITLE
New web Interface only use 2/3rd of the screen 

### ISSUE THREAD

**Issue by sxales** [jellyfin/jellyfin-web#941]
The new interface design creates an empty gap down the left side of the screen--under the poster. This wastes space by shoving useful information to the right and therefore truncating it or making the page longer. It also leaves most of the content looking off center. Ideally, all the content starting with Next Up should be left aligned--as it used to be.

System:
 - OS: Windows 10 1909 18363.719
 - Clients: Browser
 - Browser: Firefox 74
 - Jellyfin Version: 10.5.0

Current behavior: 
![interface with gap](https://i.imgur.com/gh5CA1w.jpg)

Expected behavior (mock-up):
![interface without gap](https://i.imgur.com/nb1s2si.jpg)

**Comment by sxales** [comment]
@MrTimscampi You could move the description to under the poster. It won't help much for longer series like the Simpsons, but series with around 8 seasons would look a bit cleaner. 

Mock-up:
![Description on the side](https://i.imgur.com/kREFwqt.jpg)

Short Series Mock-up:
![Description on the side](https://i.imgur.com/pqnkiC7.jpg)

**Comment by dkanada** [comment]
I definitely like that first suggestion a lot better. Something else that would improve the look a lot is adding three or four subsequent episodes in Next Up to fill the row.

**Comment by MrTimscampi** [comment]
In my opinion, the description should be visible at a glance, without having to scroll, which isn't possible if it's below the poster.

There's some concept of the "importance of data" you have to design for. What does most users want to see immediately? What's the important info ? Here, it's the title, the year, the directory, synopsys, etc.

So all that info needs to be on the first screen the user see.

**Comment by sxales** [comment]
That is reasonable. Although I would say reducing the user action needed to start watching is the primary function of the page and metadata is secondary. You only read the synopsis once, if ever, and after that every time you navigate to the series it will be to find an episode to watch. So, synopses shouldn't be taking up large amounts of screen real estate and while scrolling is cheaper than clicks, it is sufficient that the metadata be present (and prominent) on the first screen (so that the user is aware of its presence). 

Nonetheless, I prefer the first suggestion anyway but I thought, since I was mocking up examples that, I might as well give alternatives.

**Comment by dkanada** [comment]
@MrTimscampi @sxales I think we're all in agreement then!

**Comment by Deepcuts** [comment]
Not the end of the world, but maybe the poster should not be so low on page.
Chrome 2560x1440. Scale 125%. Windows
![image](https://user-images.githubusercontent.com/4704834/77233399-ceba8300-6baf-11ea-935b-d041e0189061.png)

**Comment by NebelNidas** [comment]
.

**Comment by MrTimscampi** [comment]
Please redirect feature requests and suggestions to https://features.jellyfin.org/
