### ISSUE TITLE
Double "Play" button when manually starting task

### ISSUE THREAD

**Issue by Shadowghost** [jellyfin/jellyfin-web#942]
**Describe the bug**
When manually starting a task the "play" buttons of the other tasks double most of the time.
There are different flavours of this:
* All "Play" buttons double after starting a task
* Play button flashes up in front of the "Stop" button of the started task and after that everything is as it should
* Additional "Play" Button flashes up before all other "Play" buttons and after that everything is as it should
* The additional buttons hide when you start another task

**To Reproduce**
1. Go to *Scheduled Tasks*
2. Start a task
3. Watch the screen

**Expected behavior**
Don't show doubled button

**Screenshots**
![Screenshot_2020-03-13 Jellyfin](https://user-images.githubusercontent.com/3741446/76645591-9d133d80-6559-11ea-9930-09e56637cce7.png)

**System:**
 - OS: Arch, Windows 10
 - Browser: Firefox, Opera
 - Jellyfin Version: 10.5.0 nightly

**Comment by dmitrylyzo** [comment]
Should be fixed by #919
