### ISSUE TITLE
Unreadable text with light theme and dark backdrops

### ISSUE THREAD

**Issue by Evoley** [jellyfin/jellyfin-web#97]
I am on 10.0.0.1 and I changed to the light theme for the dashboard and I am unable to read the text of almost anything.

![2019-01-10_23-17-39](https://user-images.githubusercontent.com/10457130/51012971-fd5db800-152d-11e9-8741-2ea9e54ff869.jpg)
![2019-01-10_23-10-00](https://user-images.githubusercontent.com/10457130/51012775-e36fa580-152c-11e9-8aee-aa5ddace1d75.jpg)

**Comment by sparky8251** [comment]
I don't know of a good way to handle this... Since dark backgrounds will vary.

Maybe just uniformly use white text with black borders for all themes?

**Comment by sparky8251** [comment]
Well, a light rect will cover chunks of artwork and will make light themes different from dark themes.

**Comment by sparky8251** [comment]
Thinking more like this personally:

![image](https://user-images.githubusercontent.com/1992688/52632107-96b21e00-2e8e-11e9-9547-9cac4408d131.png)

**Comment by JustAMan** [comment]
This is good for headings, but having this outline for paragraphs and paragraphs of text?.. not so sure.
Plus is it easy to achieve using css?..

**Comment by sparky8251** [comment]
No idea... but I don't like the idea of covering up artwork with rectangles to show text.

Maybe a better fix is updating the theme files and praying that they allow us to set font colors for UI elements differently from body text.

**Comment by JustAMan** [comment]
When talking about a rect I imagined half-translucent one, so it just makes some area where text would be lighter. IMHO looks nicer than thick outline around every letter on a page...

**Comment by sparky8251** [comment]
Think if I try and tackle this, I'll approach it from the theme perspective at least for a start...

That said, I'm *really* unsure what a good answer for this is. This is not an easy problem...

**Comment by dkanada** [comment]
CSS supports text shadows and text backgrounds so it can be solved in the custom themes for now.

**Comment by Evoley** [comment]
I've been going through some of my media and using the dark theme (white text) and it seems that white text is sort of hard to read with some backdrops. I guess this is why you can hardly see the backdrops by default. I've marked the areas on 2 movies and 1 tv show that I have a problem reading due to it being white text on a white-ish backdrop

![54482592-58f13e00-481c-11e9-983e-e3a5ff0db7eb](https://user-images.githubusercontent.com/10457130/54482640-357ac300-481d-11e9-82ab-906d7096fd90.png)
![54482605-8a6a0980-481c-11e9-88ba-8e9ef5ae43ff](https://user-images.githubusercontent.com/10457130/54482641-357ac300-481d-11e9-948d-799afc93f43e.png)
![Untitled](https://user-images.githubusercontent.com/10457130/54482682-dff2e600-481d-11e9-9e70-0730708eba57.png)

**Comment by dkanada** [comment]
@Evoley you should actually have a translucent overlay between the text and the background image that improves the contrast, not sure why that's not showing up but it would solve your problem. This might be a bug rather than an enhancement.
