### ISSUE TITLE
10.5.2 Can't find any image

### ISSUE THREAD

**Issue by agilob** [jellyfin/jellyfin-web#973]
**Describe the bug**
After upgrade to 10.5.2 no image can be loaded, all are 404'd

**Screenshots**

![image](https://user-images.githubusercontent.com/2544251/77291834-e50f2e80-6cd6-11ea-9f55-bd12322ba961.png)

**System (please complete the following information):**
 - OS: docker
 - Browser: Firefox
 - Jellyfin Version: 10.5.2

**Comment by agilob** [comment]
All loads fine after downgrade to 10.5.0
![image](https://user-images.githubusercontent.com/2544251/77292623-9498d080-6cd8-11ea-8f91-dee52d766360.png)

**Comment by JustAMan** [comment]
Could you please show server logs? We got quite a few other successful upgrades, so it's not 100% reproducible.

**Comment by agilob** [comment]
Ok, I upgraded again to check the logs, and it all works now...
