### ISSUE TITLE
Chrome 80 tab freeze feature breaks Chromecast control

### ISSUE THREAD

**Issue by mooninite** [jellyfin/jellyfin-web#977]
**Describe the bug**

I use the Chrome browser in Android for casting to my Chromecast. Chrome 78 introduced a feature to freeze inactive tabs after 5 minutes, which was disabled by default. Unfortunately in Chrome 80 they turned it on by default and removed the flag. This now freezes the Jellyfin tab after 5 minutes of inactivity and breaks the Chromecast connection.

**To Reproduce**

1. Open Chrome on Android
2. Cast Jellyfin to a Chromecast
3. Let Jellyfin tab go inactive for 5 minutes
4. Open Jellyfin tab and try to control Chromecast

**Expected behavior**

Playtime bar should increase time. Stop, pause buttons should work.

The tab freeze feature causes the playtime bar to freeze and stop/pause buttons to not work.
**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: Android 10
 - Browser: Chrome 80
 - Jellyfin Version: 10.5.0

**Additional context**

A workaround is to refresh the tab. Jellyfin is able to reconnect to the Chromecast without disrupting the playing video and control is returned.

My complaint may be with Chrome instead of Jellyfin unless there is another workaround.

**Comment by YouKnowBlom** [comment]
Unfortunately I don't think there's much we can do. Best approach is probably asking them directly for a way to disable it.

Just cause I'm curious, do you prefer accessing jellyfin via chrome rather than the app?

**Comment by mooninite** [comment]
My Chrome usage started with Emby when their Android app required a subscription. Besides that, Chrome allows picture-in-picture.

Chrome bug filed: https://bugs.chromium.org/p/chromium/issues/detail?id=1065654

**Comment by JustAMan** [comment]
I wonder if this is related to https://github.com/jellyfin/jellyfin-web/issues/35

**Comment by mooninite** [comment]
It is not related.

**Comment by JustAMan** [comment]
How come? That scenario looks the same to yours - connection to a Chromecast is lost upon page reload.

**Comment by mooninite** [comment]
I know how to reproduce issue #35 as I am familiar with it and am affected by it. They are not the same issue as the connection is not immediately lost upon page reload. Please re-read my reproducing steps.

Issue #38:
- Open Jellyfin
- Cast to Chromecast
- Navigate to Server Dashboard page
- Chromecast connection is 'lost'

This issue:
- Open Jellyfin
- Cast to Chromecast
- Do not touch Chrome browser for 5 minutes - Change apps, or set phone down, or walk away, etc.
- Open Jellyfin tab after 5 minutes, Tab Freeze feature kills Chromecast connection, remote control buttons do not function.
- Page reload **reconnects** tab to Chromecast - remote control buttons function again

If you use the browser tab the entire time while casting to the Chromecast the Tab Freeze feature never kicks in and the connection does not drop.
