### ISSUE TITLE
Skip to next episode prompt is way too big and blocks ui

### ISSUE THREAD

**Issue by hawken93** [jellyfin/jellyfin-web#98]
The idea is to make it smaller and less intrusive so that it can still be possible to control the playback and see the subtitles.
~~Blocked by #513~~

**Comment by sparky8251** [comment]
I've tagged this "discussion needed"

I agree this seriously needs doing but we need to seek input on how best to go about addressing this rather than just dictating it. Might be worth bringing this to a Reddit post as well and discussing there as well.

**Comment by Unimeron** [comment]
Hello folks

My take on this: make this user configurable. And add the option to disable it. ;)

Being a purist, when watching a movie/tv show on Netflix or Amazon, I'm annoyed to the max as soon as the ads/notifications near the end show up. Every. single. time!

So I'd suggest to have at least the option to turn this off or only show a button/screen as soon as playback has stopped.

I think this is a topic worth a discussion with a broader context: having a clutter/distraction free UI (at least during playback). I know and respect that people want their trailers, logos and banners and info screens in every corner. But on the other hand you surely don't want to annoy those few movie enthusiasts while watching their own stuff at home. And it can be a performance issue on some slower devices.

**Comment by JustAMan** [comment]
There is already a setting to turn it off (inherited from Emby). Dunno if it works, didn't check.

You can find it here: User preferences -> Playback -> Enable next video info during playback.

**Comment by Unimeron** [comment]
Haha, didn't even knew that option existed. :D Thanks a lot!

Hope, other things like ui-less pause mode will be there, too. On any platform. I was highly disappointed when I learned that there's no Kodi skin offering this, so I modified one myself.

**Comment by MrTimscampi** [comment]
We are cleaning up issues to be more in line with our current templates and accepted issue types here.

As this is more of a feature request/ui suggestion, please redirect it to https://features.jellyfin.org/
