### ISSUE TITLE
Subtitles cannot be configured on TV

### ISSUE THREAD

**Issue by Nazar78** [jellyfin/jellyfin-web#988]
Hi there,

I'm very excited to stumble into this project. Quickly setup everything, build then installed on my UA65RU8000 without issues. However I noticed the followings:

1. The subtitles configuration seems to be missing the appearance portion where we can change and preview the font size etc. Currently the default text is too small unlike on the normal web UI.

2. I removed the inject:js to temporarily fix the remote control cursor skipping issue mentioned in the other report. It's working great but in the subtitle sync portion after bringing it up, I wasn't able to navigate into the subtitle sync slider.

**Comment by dmitrylyzo** [comment]
@Nazar78 you can try.

**Comment by Nazar78** [comment]
Thanks @dmitrylyzo it's working great now!
