### ISSUE TITLE
Home screen sections aren't updating on Firefox ESR and Edge

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-web#994]
When opening mobile on Firefox, it appears to have a cache issue. When loading Firefox, the homepage is blank and you have to trick it to appear. I tried going to the profile page and dashboard, but no go. I got it working by selecting Favorites then going back to Home, it loads up instantly. 

![Screenshot_20200327-135353_Firefox](https://user-images.githubusercontent.com/20715731/77786709-a3fb7f00-7034-11ea-83f7-c428a03a7fbd.jpg)

**Comment by Artiume** [comment]
If I select Favorites then hit the Home icon, it does not fix the glitch. i have to explicitly click the Home lettering to get the home page to appear

**Comment by Artiume** [comment]
Verified same issue on Firefox ESR on desktop

**Comment by Artiume** [comment]
Going into a library then back to the home screen, it is missing again. Overlay issue?

**Comment by Artiume** [comment]
@MrTimscampi you want to take a stab at this one? It appears the xbox suffers the same issue

**Comment by MrTimscampi** [comment]
@Artiume Can you confirm if this is still a thing?

**Comment by Artiume** [comment]
Firefox mobile is good for 10.6.0
