### ISSUE TITLE
Chrome Mobile Updating Images

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-web#995]
When trying to add new images, the screen doesn't properly exit once the image has been added. It stays stuck on this screen. If you forcefully exit, the image does update so it seems like a simple call error. Works properly in Firefox mobile. 

![Screenshot_20200327-155400_Chrome](https://user-images.githubusercontent.com/20715731/77795084-5afef700-7043-11ea-9dd6-e7713022df2d.jpg)

**Comment by JustAMan** [comment]
I think we'd need web console logs... try simulating mobile with a desktop Chrome, does it exhibit the same issue?

**Comment by Artiume** [comment]
fixed. resolving
