### ISSUE TITLE
Reposition and resize arrow icons on home carousel

### ISSUE THREAD

**Issue by hamburglar2160** [jellyfin/jellyfin-web#998]
This can't be done with CSS alone. The idea would be to resize and reposition the arrow buttons from the top right of each home section carousel to something more accessible for non-swipe clients. HBO does this pretty well (pictured).
![image](https://user-images.githubusercontent.com/61879508/77825683-3bb6a700-70e1-11ea-81ec-748f6449f036.png)

**Comment by YouKnowBlom** [comment]
I kinda like it. This could probably go hand in hand with an ES6 migration of that component

**Comment by dkanada** [comment]
That's what it used to look like but I moved them to the top right to match Plex (which I would argue is a better design) and because the old controls would overlap against the cards on the ends.

**Comment by hamburglar2160** [comment]
...toggle? it's honestly a chore to scroll with that setup.

**Comment by YouKnowBlom** [comment]
Wouldn't it be more of a chore with this change as you'd have the arrows even further apart

**Comment by MrTimscampi** [comment]
Yeah, it doesn't make sense that the current ones are a chore despite being next to each other and pretty easy to click on, while the ones you propose are on opposite sides of the screen...

If anything, I find the current ones more practical to use.

**Comment by hamburglar2160** [comment]
they're so small! i have to aim on a high resolution display. the odds of me scrolling left after are rather slim as well.

**Comment by dkanada** [comment]
> more of a chore with this change as you'd have the arrows even further apart

This is exactly why I think Plex does it a different way, a normal use case has you paging back and forth in the row, which would be extremely annoying with the arrows on opposite ends of the page.

**Comment by YouKnowBlom** [comment]
A good middle ground might be to play around with the arrow sizes I suppose.

**Comment by MrTimscampi** [comment]
They're honestly fairly big already:

![image](https://user-images.githubusercontent.com/19396809/77846034-7721a600-71b3-11ea-80f4-243540a7d5da.png)

All the blue zone is hoverable and clickable.

**Comment by dkanada** [comment]
There's a small issue with them not properly showing and hiding due to the asynchronous container load, but that's only marginally related.

**Comment by hamburglar2160** [comment]
This isn't something Jellyfin should get their cues from Plex for. All of the major streaming platforms use this scheme and certainly they people to figure out what UX is best.

i'm not saying that JF should copy everything from these platforms but this is certainly one of them. The current implementation is very annoying.

**Comment by hamburglar2160** [comment]
Courtesy of dmitrylyzo, here is the CSS to achieve most of this, which can be tossed into the custom CSS setting son the dashboard. Making these arrows clickable for the entirety of the height of the thumb/poster images is what I had in mind. Making a PR for this would be ideal, otherwise users can refer to the documentation and implement this via custom CSS. Either outcome closes this issue.


.emby-scrollbuttons {
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    padding: 0;
    justify-content: space-between;
    pointer-events: none;
}
.emby-scrollbuttons-button {
    pointer-events: initial;
}
